### ISSUE TITLE
When will support FCOS3d deploy? Thanks

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmdeploy#1010]

**Comment by tpoisonooo** [comment]
WIP, mmdet3d developer would support it.

**Comment by FDInSky** [comment]
> WIP, mmdet3d developer would support it.

So, could mmdeploy export fcos3d until now ?

**Comment by tpoisonooo** [comment]
check https://github.com/open-mmlab/mmdeploy/pull/1047

**Comment by tpoisonooo** [comment]
Already merged, so close this issue.
