### ISSUE TITLE
Tensorrt batch inference is much slower when batch size is larger.

### ISSUE THREAD

**Issue by yuanyuangoo** [open-mmlab/mmdeploy#1013]
I convert a deeplabv3+ model to a Tensorrt engine with dynamic input size. I found when I use a larger batch size, the inference speed is much slower.

The test code is as below. When I use batch size 8, I got fps 7-8, when I use batchsize 1, I got fps about 60. It feels like batch inference here is doing inference one frame by frame, not in a batch.

`import time
import numpy as np
from mmdeploy_python import Segmentor

segmentor = Segmentor(
    model_path='./deeplabv3plus_dynamic_bud/', device_name='cuda', device_id=0)
prev_frame_time = 0
new_frame_time = 0
batch_size = 8
im = np.zeros((batch_size, 512, 1024, 3))
while(True):
    seg = segmentor.batch(im)
    new_frame_time = time.time()
    fps = 1/(new_frame_time-prev_frame_time)
    prev_frame_time = new_frame_time
    fps = str(float(fps))
    print(fps)
`

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by lzhangzz** [comment]
You may find this helpful https://github.com/open-mmlab/mmdeploy/issues/839#issuecomment-1206029364

**Comment by yuanyuangoo** [comment]
I added "is_batched": true to pipeline.json, still get much slower performance with batch_size > 1.

**Comment by lzhangzz** [comment]
The segmentation model is large enough to saturate your device, don't expect large speed up using batch inference.
