### ISSUE TITLE
ImportError: cannot import name 'create_trt_engine' from 'mmdeploy.backend.tensorrt'

### ISSUE THREAD

**Issue by Oscillated** [open-mmlab/mmdeploy#1019]
I follow the [tutorial](https://mmdeploy.readthedocs.io/zh_CN/latest/01-how-to-build/linux-x86_64.html), and build SDK without errors. But find errors when I try to add plugins into TensorRT backends. (follow [第七章： TENSORRT 自定义插件](https://mmdeploy.readthedocs.io/zh_CN/latest/tutorial/07_write_a_plugin.html) )

![image](https://user-images.githubusercontent.com/48610672/188819086-fe349fc7-52d2-42a5-8723-5695de19b1b5.png)

This is my env

![image](https://user-images.githubusercontent.com/48610672/188820288-7eb899a8-d12c-49aa-948b-c32ecc6d3a5a.png)

![image](https://user-images.githubusercontent.com/48610672/188820376-30f8e2ce-47c7-495e-9549-f8611796064f.png)

**Comment by tpoisonooo** [comment]
Have you `python3 -m pip install /path/to/tensorrt/python/tensorrt-pyxxxx-.whl`  ?

**Comment by irexyc** [comment]
you also shoud install pycuda through `pip install pycuda`

**Comment by Oscillated** [comment]
> 

Yes, I have installed tensorrt-8.4.1.5-cp38-none-linux_x86_64.whl in tensorrt directory.

**Comment by Oscillated** [comment]
> you also shoud install pycuda through `pip install pycuda`

Thanks for advice, but I have also installed pycuda during the setup process.

**Comment by AllentDan** [comment]
Hi, @Oscillated . `create_trt_engine` has been deprecated in the latest MMDeploy. Please use `from_onnx` instead.

**Comment by Oscillated** [comment]
> Hi, @Oscillated . `create_trt_engine` has been deprecated in the latest MMDeploy. Please use `from_onnx` instead.

I re-build mmdeploy, now it is version 0.8.0, but it still seems to have errors when I follow the [example](https://mmdeploy.readthedocs.io/zh_CN/latest/api.html?highlight=from_onnx#mmdeploy.apis.tensorrt.from_onnx) of `from_onnx` function. How can I solve it ? Thanks.

![error](https://user-images.githubusercontent.com/48610672/189902205-5833c28b-15c4-4d18-9393-fa098ce219c0.png)

**Comment by AllentDan** [comment]
You may refer to PR #1021.
