### ISSUE TITLE
Failed to convert swinTransformer of mmcls to trt.

### ISSUE THREAD

**Issue by Lyinan** [open-mmlab/mmdeploy#1022]
Hi, I tried to convert swinTransformer of mmcls to trt, but failed. 
Here is the convert command:
![image](https://user-images.githubusercontent.com/30928004/189022284-f28586f9-b808-4357-bce5-9c438db64543.png)

The problem is:
![image](https://user-images.githubusercontent.com/30928004/189021166-c2f01ccf-2b5f-4337-a856-cf3d9730d344.png)

And my env is:
cuda: 10.2
TensorRT: 8.2.3.0
Python: 3.7.9
mmdeploy: 0.8.0
mmcls: 0.23.0
PyTorch: 1.8.0
onnxruntime: 1.10.0

**Comment by AllentDan** [comment]
Could you try running `from mmdeploy.backend.torchscript import ts_optimizer`?

**Comment by AllentDan** [comment]
If possible, please paste your env info through `python tools/check_env.py`.

**Comment by Lyinan** [comment]
I converted the model to trt sucessfully after I installed pytorch=1.10.0 and rebuilded mmdeploy according to [https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/linux-x86_64.md](url)
