### ISSUE TITLE
Convert mmpose:TopDownAffine Transform to cuda compatible

### ISSUE THREAD

**Issue by yeeyangtee** [open-mmlab/mmdeploy#1030]
[`mmdeploy/csrc/mmdeploy/codebase/mmpose/topdown_affine.cpp` 
](https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/codebase/mmpose/topdown_affine.cpp)
I am trying to modify the above file to allow preprocessing on cuda.

The model I am using is [HRNet](https://github.com/open-mmlab/mmpose/blob/master/configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/hrnet_w48_coco_wholebody_256x192.py).

TopDownAffine uses cv2.warpaffine, but at inference it only performs crop and resize, so this could be easily changed to a cuda compatible transform.

Before doing that, is there a way to quickly put in an existing cuda-resize Transform to replace TopDownAffine in the pipeline and look at the potential speed gain?

My current workflow is:
- Rewrite .cpp code at [topdown_affine.cpp](https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/codebase/mmpose/topdown_affine.cpp) to perform resize, and import from the cuda kernel [here](https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/preprocess/cuda/resize_impl.cpp).
- Rebuild tensorRT using commands [here](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/linux-x86_64.md)
- Reconvert model with tools/deploy.py

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by irexyc** [comment]
Current, the `TopDownAffine` can be processed on gpu.
