### ISSUE TITLE
Has anyone tried converting a SAR model from onnx to tensorrt format?

### ISSUE THREAD

**Issue by EYcab** [open-mmlab/mmdeploy#107]
I have tried  converting a SAR model from onnx to tensorrt format, but ended up with a failure.
I wonder where may go wrong since I have changed the config file accordingly

[TensorRT] INFO: [MemUsageSnapshot] Builder begin: CPU 4793 MiB, GPU 2718 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +747, GPU +320, now: CPU 5546, GPU 3038 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +587, GPU +266, now: CPU 6133, GPU 3304 (MiB)
[TensorRT] WARNING: Detected invalid timing cache, setup a local cache instead
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 7026, GPU 3688 (MiB)
[TensorRT] ERROR: 1: [codeGenerator.cpp::compileGraph::476] Error Code 1: Myelin (Mismatched shape for tensor 228'_ForeignNode[Cast_230___Sub_123]_, current shape:f32,[], vs. expected shape:f32,[1].)
2022-01-26 11:08:45,378 - mmdeploy - ERROR - Failed to create TensorRT engine
2022-01-26 11:08:45,378 - mmdeploy - ERROR - onnx2tensorrt failed.

**Comment by AllentDan** [comment]
Hi, check [it](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/supported_models.md) out that we only support exporting SARNet to onnx.

**Comment by EYcab** [comment]
Yes, it was well said in the site. I wonder what make it difficult to do a onnx2tensorrt conversion in SARNet. Could you provide any related posts or specs on this matter? Thank you in advance.

**Comment by AllentDan** [comment]
Well, the SARNet trained for Chinese characters is larger than 2GB making it nearly impossible to be converted to TensorRT. That's why we don't support it for other backends.

However, for the error log provided above, it is highly likely that changing the version of TensorRT can avoid the error.

**Comment by EYcab** [comment]
Thanks for your commment. I see, the SARNET I trained only has 800MB in onnx format, would it be possible to do a conversion via onnx2tensorrt? And is there a model capacity/volume estimation that a conversion from the torch format to tenorRT's impossible or infeasible in the mmdeploy framework?

**Comment by AllentDan** [comment]
First question, basically yes but not quite sure. The second question, size limitation of a single file comes from [onnx itself](https://github.com/onnx/onnx/blob/83fa57c74edfd13ddac9548b8a12f9e3e2ed05bd/onnx/checker.py#L32).

**Comment by EYcab** [comment]
OK, thank you.
