### ISSUE TITLE
mmdeploy_python 没有编译出这个库

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmdeploy#1075]
我执行的脚本的命令 `python tools/scripts/build_ubuntu_x64_ncnn.py 20`
但是 结束后 import mmdeploy_python 这个是出错的 ，我想知道这个可能的问题是什么？希望大佬们给与解答

**Comment by lvhan028** [comment]
The path of python package `mmdeploy_python` is supposed to append to the environment variable `PYTHONPATH`.
```
cd mmdeploy
export PYTHONPATH=$(pwd)/build/lib:$PYTHONPATH
```
