### ISSUE TITLE
solov2 export onnx？

### ISSUE THREAD

**Issue by KongCang** [open-mmlab/mmdeploy#1077]
is there any schedule to support solov2 exporting to onnx ？or is there some document that can help convert the model?

**Comment by lvhan028** [comment]
Hi, we haven't made a plan to support solov2 yet. 
You may refer to #367 for how to support a new model.

**Comment by KongCang** [comment]
Thanks for your reply! convert to onnx success refer [SOLOv2.tensorRT](https://github.com/zhangjinsong3/SOLOv2.tensorRT)
