### ISSUE TITLE
Parsing CenterPoint Output ONNX Nodes 

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmdeploy#1079]
I managed to get the ONNX export for mmdet3d's centerpoint. However I am not sure how do I parse the outputs. For example, I have the ONNX model as in the screenshot, for a network with 3 tasks each with 1 class. Direction, 3D boxes and confidences from all tasks are concated at the output. How do i be sure that any given index or slice of these output tensors is associated to a specific task `t` and class `c`. What is the recommended approach to getting this kind of mapping info for each architecture, is it simply the same order in the cfg file maybe?

![Screenshot from 2022-09-20 11-41-24](https://user-images.githubusercontent.com/75477646/191211507-cf7ddcfb-d9b9-4fc2-95db-9901360ffe66.png)

      pts_bbox_head=dict(
        type='CenterHead',
        in_channels=sum([128, 128, 128]),
        tasks=[
            dict(num_class=1, class_names=['car']),
            dict(num_class=1, class_names=['bicycle']),
            dict(num_class=1, class_names=['pedestrian']),
        ],
        common_heads=dict(
            reg=(2, 2), height=(1, 2), dim=(3, 2), rot=(2, 2)),

         ...

**Comment by tpoisonooo** [comment]
1. The output (`dir_score`, `bbox_preds` and `scores`) needs  postprocess here:  https://github.com/open-mmlab/mmdeploy/blob/1c5dcb799badbad717f6bfed615acb4a8e52f92f/mmdeploy/codebase/mmdet3d/models/centerpoint.py#L68

`centerpoint__get_bbox` is actually called [here](https://github.com/open-mmlab/mmdeploy/blob/1c5dcb799badbad717f6bfed615acb4a8e52f92f/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py#L226) 

Finally `get_bbox` would return real bbox/score/label. The label value `[0,1,2]` maps to `[car, bicyle, ped]`

2. End2End centerpoint model (without postprocess) is still WIP.

**Comment by OrcunCanDeniz** [comment]
Thanks !
