### ISSUE TITLE
windows_cpu_onnx_mmdeploy_error

### ISSUE THREAD

**Issue by shanchao0906** [open-mmlab/mmdeploy#1096]
![image](https://user-images.githubusercontent.com/56211787/191954300-99f2c377-fefe-4c40-bc4a-d312a2fb3c58.png)

Thank you very much for your warehouse
I use your precompiled package to compile an executable program on windows.
And put mmdeloy.dll, opencv_world460.dll and onnx_runtime.dll in the executable program folder, but the following error occurred, what is the reason?

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by irexyc** [comment]
Could you first try to run the provided executable of sdk/bin/image_classification.exe ?
Our prebuit package use onnxruntiem-win-x64-1.8.1, what is your version of onnxruntime? Could you try this version?
