### ISSUE TITLE
TensorRT ".engine" python inference

### ISSUE THREAD

**Issue by Rm1n90** [open-mmlab/mmdeploy#111]
Hi, 
 Is there any documentation about how to deploy TensorRT engine file for python inference??

Thanks!

**Comment by RunningLeon** [comment]
@Rm1n90 Hi, you could refer to https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/apis/inference.py or call `inference_model` from `from mmdeploy.apis import inference_model`.
