### ISSUE TITLE
C++ guide

### ISSUE THREAD

**Issue by hch-baobei** [open-mmlab/mmdeploy#1113]
I want to build a C++ inference framework modeled after mmdeploy. Where should I start? Is Demo/CSRC /object_detection. CPP a good choice?

**Comment by lvhan028** [comment]
Sorry for being so late reply.

If you want to learn how to use mmdeploy SDK to perform model inference, `demos/csrc` is a good start.
`demos/csrc/c` lists predictors, such as the classifier, detector, segmentor, and so on, which are implemented based on SDK's C API. Meanwhile, `demos/csrc/cpp` presents predictors that are built on SDK's C++ API.
