### ISSUE TITLE
Building mmdeploy on jetpack 4.5.1, TensorRT 7.1.3.0 

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#114]
Hello,

After testing mmdeploy further on a Jetson AGX platform, I have noticed a few issues when building using older tensorrt as found on jetpack 4.5.1. Unfortunately, I cannot update to latest Jetpack yet due to a custom hardware platform in use.

* Install dependencies as instructed by documentation (except h5py, as it cannot be installed on jetson)
* build MMdeploy
```
cd ${PROJECT_DIR}/MMDeploy
git submodule update --init --recursive
pip install -e .
mkdir build -p && cd build
cmake .. \
  -DMMDEPLOY_BUILD_SDK=ON \
  -DCMAKE_CXX_COMPILER=g++ \
  -Dpplcv_DIR=${PROJECT_DIR}/logends/ppl.cv/cuda-build/install/lib/cmake/ppl \
  -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
  -DMMDEPLOY_TARGET_BACKENDS=trt \
  -DMMDEPLOY_CODEBASES=all
cmake --build . -- -j$(nproc) && cmake --install .
```

* Build error
```
...
[ 93%] Linking CXX shared library ../../../lib/libmmdeploy_segmentor.so
[ 93%] Built target mmdeploy_segmentor
[ 94%] Linking CXX shared module ../../../lib/libmmdeploy_tensorrt_ops.so
[ 94%] Built target mmdeploy_tensorrt_ops
[ 95%] Linking CXX static library ../../../lib/libmmdeploy_tensorrt_ops_static.a
[ 95%] Built target mmdeploy_tensorrt_ops_static
[ 96%] Building CXX object csrc/net/trt/CMakeFiles/mmdeploy_trt_net.dir/trt_net.cpp.o
/../MMDeploy/csrc/net/trt/trt_net.cpp: In member function ‘virtual mmdeploy::Result<void> mmdeploy::TRTNet::Init(const mmdeploy::Value&)’:
/../MMDeploy/csrc/net/trt/trt_net.cpp:153:13: error: ‘class nvinfer1::IExecutionContext’ has no member named ‘setOptimizationProfileAsync’; did you mean ‘setOptimizationProfile’?
   context_->setOptimizationProfileAsync(0, static_cast<cudaStream_t>(stream_.GetNative()));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
             setOptimizationProfile
```

* Solution: In `csrc/net/trt/trt_net.cpp`, replace line 153 with the following
```
..
#if NV_TENSORRT_MAJOR > 7
  context_->setOptimizationProfileAsync(0, static_cast<cudaStream_t>(stream_.GetNative()));
#else
  context_->setOptimizationProfile(0);
#endif
```

I am however not sure which TensorRT version introduces `setOptimizationProfileAsync()`

**Comment by lzhangzz** [comment]
Thanks for reporting the issue. 

I just confirmed that `setOptimizationProfileAsync` is added on TensorRT 7.2.

https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-713/api/c_api/classnvinfer1_1_1_i_execution_context.html
https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-720/api/c_api/classnvinfer1_1_1_i_execution_context.html

**Comment by tehkillerbee** [comment]
@lzhangzz Ok! In that case, I guess we should look at both major/minor version. Something like:
```
#if NV_TENSORRT_MAJOR > 7 && NV_TENSORRT_MINOR > 1
...
```

**Comment by lvhan028** [comment]
> @lzhangzz Ok! In that case, I guess we should look at both major/minor version. Something like:
> 
> ```
> #if NV_TENSORRT_MAJOR > 7 && NV_TENSORRT_MINOR > 1
> ...
> ```

Agreed. Could you please fix it?

**Comment by tehkillerbee** [comment]
@lvhan028 Sure, I have added PR #133

**Comment by tehkillerbee** [comment]
Closing issue, as TRT7 will not be supported at this point

**Comment by azuryl** [comment]
> Thanks for reporting the issue.
> 
> I just confirmed that `setOptimizationProfileAsync` is added on TensorRT 7.2.
> 
> https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-713/api/c_api/classnvinfer1_1_1_i_execution_context.html https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-720/api/c_api/classnvinfer1_1_1_i_execution_context.html

It sees you not  fixed
it is occoured in https://github.com/open-mmlab/mmdeploy/issues/2260 again

**Comment by azuryl** [comment]
> Closing issue, as TRT7 will not be supported at this point

you should reopen this issue

**Comment by tehkillerbee** [comment]
> > Closing issue, as TRT7 will not be supported at this point
> 
> you should reopen this issue,more than one year passed it still occoured !

This issue was closed since TensorRT v7 will not be supported. I fixed the issue by upgrading to Tensor RT v8.
