### ISSUE TITLE
trt model could convert by tensorrt C++ API？If i want run them in different pc，i must install a python environment

### ISSUE THREAD

**Issue by xinsuinizhuan** [open-mmlab/mmdeploy#1147]
### Motivation

now it seems that i must use the python to convert the model to trt mode, and if i want run them in different pc，i must install a python environment, it is so tedious. Could support convert with tensorrt api c++？

**Comment by lvhan028** [comment]
We have no plans to integrate tensorrt c++ api for converting model.
