### ISSUE TITLE
How to convert a segmentation model to tensorrt engine that can output probability map ?

### ISSUE THREAD

**Issue by yuanyuangoo** [open-mmlab/mmdeploy#1153]
Hi, Now the tensorrt engine can output result that has been passed through argmax function, how to also get output of the seg_logit before that?

**Comment by RunningLeon** [comment]
@yuanyuangoo Hi, a simple way is to return the seg_logit in the rewritings function, just like [here](https://github.com/open-mmlab/mmdeploy/blob/b2cb5722f732c4789a11e282d13b00b6e25e2b0d/mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py#L35).

**Comment by yuanyuangoo** [comment]
Hi, Thanks. It works to get seg_logit. Then How can I modify csrc/mmdeploy/codebase/mmseg/segment.cpp to accommodate the new output size? It gives me error like "[2022-10-10 08:50:36.869] [mmdeploy] [error] [segment.cpp:35] unsupported `output` tensor, shape: [1, 8, 512, 1024]"

**Comment by RunningLeon** [comment]
@yuanyuangoo Hi, if you want to support this in sdk, you have to add  another `post_process` with `resize and argmax`.

**Comment by AllentDan** [comment]
#1379 might be what you need. @yuanyuangoo
