### ISSUE TITLE
使用python mmdeploy/tools/deploy.py 部署时报错

### ISSUE THREAD

**Issue by Chriost** [open-mmlab/mmdeploy#1163]
命令：python mmdeploy/tools/deploy.py     mmdeploy/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py     mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py     mmdeploy/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth     mmdetection/demo/demo.jpg     --work-dir mmdeploy_model/faster-rcnn     --device cuda     --dump-info

报错：
ImportError: cannot import name 'DistancePointBBoxCoder' from 'mmdet.core.bbox.coder'

**Comment by hanrui1sensetime** [comment]
Could you please execute `python tools/check_env.py` for more information? Seems like your env has wrong version match.

**Comment by siriasadeddin** [comment]
I am having the same issue when trying to export a gfl model.
```
 File "mmdeploy\mmdeploy\codebase\mmdet\models\dense_heads\base_dense_head.py", line 3, in <module>
    from mmdet.core.bbox.coder import (DeltaXYWHBBoxCoder, DistancePointBBoxCoder,      
ImportError: cannot import name 'DistancePointBBoxCoder' from 'mmdet.core.bbox.coder' (mmdet\core\bbox\coder\__init__.py)       
2022-12-31 00:50:03,735 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```
