### ISSUE TITLE
When i run the pip install -e . it fail.

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdeploy#1175]
When i run the `pip install -e .` 
![image](https://user-images.githubusercontent.com/86214036/194757481-4d92f9d0-022f-4715-a7fb-9ef33f7dbe55.png)

It occur this problem
![image](https://user-images.githubusercontent.com/86214036/194757513-94fe8cf2-4f28-465a-9d47-ea3c44fec6ed.png)
By the way my jetpack is 5.0.2.

**Comment by lvhan028** [comment]
It shows "ModuleNotFoundError: no module named 'torch'". 
Could you paste the message after running `pip3 show torch`? Let's find out if `torch` is installed successfully

**Comment by lijoe123** [comment]
Yes
![image](https://user-images.githubusercontent.com/86214036/194833190-fbb5bb3b-a6a2-4d40-9215-f6d851a3445d.png)

**Comment by lijoe123** [comment]
Hello, i asked the torchvision official ,they give me the answer: `pip install -e . --no-build-isolation` , and it work.

**Comment by lvhan028** [comment]
Hi, @lijoe123 would you mind adding our solution to mmdeploy's FAQ? 
https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md
https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/faq.md

**Comment by lijoe123** [comment]
Never mind.

**Comment by lvhan028** [comment]
> Never mind.

Look forward to your PR

**Comment by lijoe123** [comment]
> > Never mind.
> 
> Look forward to your PR

This is my first time to write PR , i don't right or not. You can have a check.
https://github.com/open-mmlab/mmdeploy/pull/1181

**Comment by lijoe123** [comment]
it fail , i'm sorry. i don't know how to write PR
