### ISSUE TITLE
When I run pip install -e . the following issues have arisen

### ISSUE THREAD

**Issue by Luxiangxianghy** [open-mmlab/mmdeploy#1180]
![image](https://user-images.githubusercontent.com/105439021/194889132-0a837bf8-bc0b-4bed-b09b-057fbb432bc3.png)
When I run pip install -e . the following issues have arisen，in windows

**Comment by grimoire** [comment]
Try install the Window10 SDK in Visual Studio installer.

**Comment by Luxiangxianghy** [comment]
> Try install the Window10 SDK in Visual Studio installer.

I've installed it and configured the environment variables, but it doesn't work.

**Comment by irexyc** [comment]
On my machine, the stddef.h is located `C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\stddef.h`. The path may similar to yours except the version.

When I install  window10 sdk, I didn't remember it ask me to configure any environment variables. 
Which version of window10 sdk have you installed？

**Comment by Luxiangxianghy** [comment]
> On my machine, the stddef.h is located `C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\stddef.h`. The path may similar to yours except the version.
> 
> When I install window10 sdk, I didn't remember it ask me to configure any environment variables. Which version of window10 sdk have you installed？
I chose Visual Studio 2019, install Visual Studio 2019 , window10 sdk will also follow, but may be different: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\ stddef.h, this path is in C disk, but my Visual Studio 2019 installation path is in D disk, then I add the environment variable: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt, still show that stddef cannot be found stddef .h, I don't know what's going on.

**Comment by irexyc** [comment]
Can you check the value of InstallationFolder of HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0 ?

**Comment by Luxiangxianghy** [comment]
> Can you check the InstallationFolder value of HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0 ?
I didn't find it on my computer
![image](https://user-images.githubusercontent.com/105439021/195107120-169c4e06-8344-4250-b80a-6544a8acc1cf.png)

**Comment by irexyc** [comment]
The path should be `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0` other than `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft`. If you have installed windows 10 sdk, there should exists the key.  

To be honest, I suspect you have installed the sdk. You can use tools like everything to check if stddef.h exists in your D drive.

**Comment by Luxiangxianghy** [comment]
> The path should be `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0` other than `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft`. If you have installed windows 10 sdk, there should exists the key.
> 
> To be honest, I suspect you have installed the sdk. You can use tools like everything to check if stddef.h exists in your D drive.
Sorry, I misread it...

It is this
![image](https://user-images.githubusercontent.com/105439021/195370603-764bf5bc-4e72-4402-91eb-c8bfbab2cd8d.png)

**Comment by irexyc** [comment]
I think cl.exe will use the registry to search windows 10 sdk. On your machine, the registry says the sdk installation path is 
`C:\Program Files (x86)\Windows Kits\10\`, please chech if it truly exists in that path. If not, there may be some problems for you environment. You can choose to uninstall the sdk and reinstall through VS or download from [this](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/). Or you can try to use `everything` tool to search where is `stddef.h` located on your disk and modify the key `InstallationFolder` in registry editor on your condition. While I recommend the reinstall method.

**Comment by Luxiangxianghy** [comment]
> I think cl.exe will use the registry to search windows 10 sdk. On your machine, the registry says the sdk installation path is `C:\Program Files (x86)\Windows Kits\10\`, please chech if it truly exists in that path. If not, there may be some problems for you environment. You can choose to uninstall the sdk and reinstall through VS or download from [this](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/). Or you can try to use `everything` tool to search where is `stddef.h` located on your disk and modify the key `InstallationFolder` in registry editor on your condition. While I recommend the reinstall method.

ok，thanks！！I'll try.
