### ISSUE TITLE
No module named 'mmdeploy_python'?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdeploy#1184]
When i run this `python mmdeploy/demo/python/object_detection.py work_dir/end2end.onnx mmdeploy/demo.jpg`
It occur this problem:
![29121946bc6d9df5f9ec4b0ec7369aa](https://user-images.githubusercontent.com/86214036/195084943-b3ec90c5-419f-47f5-8354-974def4e2b66.jpg)
Thank you.

**Comment by lvhan028** [comment]
If you build mmdeploy from source, make sure to open `MMDEPLOY_BUILD_SDK_PYTHON_API`.
You will find `mmdeploy_python.cpython-37m-x86_64-linux-gnu.so*` in you `build/lib` directory.
Then append the path of `mmdepoy_python` library to `PYTHONPATH`.
For example,
```
export PYTHONPATH=${MMDEPLOY_DIR}/build/lib
```

**Comment by lijoe123** [comment]
Thank you, it work.
But i had met the other problem:
i run the command:
`python mmdeploy/demo/python/object_detection.py cuda mmdeploy/work_dir/end2end.onnx mmdeploy/image/demo.jpg
`
the problem:
![image](https://user-images.githubusercontent.com/86214036/195263235-65f04077-dccc-4b8b-894c-86d1048e7dc4.png)

Thank you!!!

**Comment by irexyc** [comment]
Use `model dir` instead of onnx model.

`python mmdeploy/demo/python/object_detection.py cuda mmdeploy/work_dir/ mmdeploy/image/demo.jpg`

**Comment by lijoe123** [comment]
Thank you!!!!
By the way, when i run the deploy.py in  mask r-cnn trained by my own dataset.
```
python ./tools/deploy.py \
    configs/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py \
    $PATH_TO_MMDET/configs/mask-rcnn/mask_r_cnn_ fpn_2x.py\
    latest.pth \
    $PATH_TO_MMDET/demo/demo.jpg \
    --work-dir work_dir \
    --show \
    --device cuda:0 \
    --dump-info
```
it show two different label in the images. （tensorrt and pytorch）
![image](https://user-images.githubusercontent.com/86214036/195334207-d31a1ebd-3742-47c3-9d36-744d21bcd7ed.png)
the person label is right.
Why it occur this situation?
Thank you!

**Comment by lvhan028** [comment]
@grimoire could you check the above label issue?

**Comment by grimoire** [comment]
Can you provide more detail about the model config?

**Comment by lijoe123** [comment]
Yes, of course.
I use the empirical_attention config to improve the mask r-cnn:
```
_base_ = '..**/mask_rcnn/mask_rcnn_r50_fpn_2x_coco.py'**
model = dict(
    backbone=dict(
        plugins=[
            dict(
                cfg=dict(
                    type='GeneralizedAttention',
                    spatial_range=-1,
                    num_heads=8,
                    attention_type='0010',
                    kv_stride=2),
                stages=(False, False, True, True),
                position='after_conv2')
        ],
        dcn=dict(type='DCN', deform_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True)))
```
And the dataset is collect by myself, including: person、uav、building、tree、wire_pole、tower.

**Comment by lijoe123** [comment]
Thank you for your answer, i had fix it

**Comment by Msameim181** [comment]
> Thank you for your answer, i had fix it

How did you fix it?
