### ISSUE TITLE
Support for deformable detr

### ISSUE THREAD

**Issue by frankxyy** [open-mmlab/mmdeploy#1188]
When I tried to export deformable detr to onnx for deployment, ``AttributeError: 'DeformableDETRHead' object has no attribute 'input_proj'`` error occurred. Can u provide the feature for deploying of deformable detr? Thanks a lot.

**Comment by grimoire** [comment]
Try add your own rewriter to support your model.
[here](https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/codebase/mmdet/models/dense_heads/detr_head.py) is an example.
