### ISSUE TITLE
ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis'

### ISSUE THREAD

**Issue by Lenan22** [open-mmlab/mmdeploy#1191]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

Traceback (most recent call last):
  File "tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
ImportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/workspace/frameWork/mmdeploy-debug/mmdeploy/apis/__init__.py)

奇怪啊，为什么会报这个错误呢

### Reproduction

python tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py ../mmdetection-debug/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ../mmdetection-debug/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth ../mmdetection-debug/demo/demo.jpg --work-dir /workspace/frameWork/mmdeploy-debug/tmp --device cuda:0 --dump-info

### Environment

```Shell
my docker
```

**Comment by Lenan22** [comment]
no

**Comment by SHX9610** [comment]
hallo, how to solve this problem? @Lenan22

**Comment by guangminglftg** [comment]
i met the same problem as you
