### ISSUE TITLE
Different results with SDK and Python API

### ISSUE THREAD

**Issue by Harhammer** [open-mmlab/mmdeploy#1195]
I just recognized that i get different detection results when i use the SDK and Python API. During development i always used `mmdeploy.apis.visualize_model` to visually check the results after converting my MaskRCNN Model to TensorRT. In my project code i use the Python API for the inference. Now i have accidentally found out that i get way less Detection's when i use the Python API.

I use the exact same model for both methods but the SDK delivers a lot more correct Detections then the Python API. The only difference is, that i have to give the whole directory with dumped info to the Python API while i only give the .engine file, the model_config, and the deploy_config to the SDK.

Do you have any idea why this could happen?

**Comment by irexyc** [comment]
Could you follow the bug report template to add the essential information for reproduction?

When your convert the a model, the output_xxx.jpg is inferenced by pytorch or backend engine(official onnxruntime/pytorch python package etc.), it is not sdk output. The output by python api is actually the sdk output.
