### ISSUE TITLE
deploy dev-1.x docs to https://mmdeploy.readthedocs.io

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#1198]
### Motivation

deploy dev-1.x docs   to https://mmyolo.readthedocs.io

### Related resources

deploy dev-1.x docs  to https://mmyolo.readthedocs.io

### Additional context

deploy dev-1.x docs  to https://mmyolo.readthedocs.io

**Comment by lvhan028** [comment]
Please check if the following URL is available.
https://mmdeploy.readthedocs.io/en/dev-1.x/

**Comment by vansin** [comment]
> Please check if the following URL is available. https://mmdeploy.readthedocs.io/en/dev-1.x/

https://mmdeploy.readthedocs.io/en/dev-1.x/ is available

but https://mmdeploy.readthedocs.io/zh_CN/dev-1.x is not available~

**Comment by lvhan028** [comment]
`zh_CN` has been configured. Please recheck it. 
https://mmdeploy.readthedocs.io/zh_CN/dev-1.x/

**Comment by vansin** [comment]
> `zh_CN` has been configured. Please recheck it. https://mmdeploy.readthedocs.io/zh_CN/dev-1.x/

Thanks~
