### ISSUE TITLE
Not able to find the path of the logs and tensorrt model 

### ISSUE THREAD

**Issue by ghoshsdeep** [open-mmlab/mmdeploy#1205]
Following the reference https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/02-how-to-run/convert_model.md
I ran an inference using an mmseg model .

python ./tools/deploy.py  configs/mmseg/segmentation_tensorrt_static-512x1024.py ~/ghosh_ws/MMDeployment/mmsegmentation/pspnet_r50-d8_512x1024_40k_cityscapes.py ~/ghosh_ws/MMDeployment/mmsegmentation/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth ~/ghosh_ws/MMDeployment/mmsegmentation/demo/demo.png --work-dir ~/ghosh_ws/MMDeployment/mmdeploy --show --device cuda:0

It worked perfectly generating the following ouput 
![Screenshot from 2022-10-16 03-16-56](https://user-images.githubusercontent.com/112154951/196009152-d80816df-aee2-40e8-b101-13c0ecf927d2.png)

![Screenshot from 2022-10-16 03-27-28](https://user-images.githubusercontent.com/112154951/196009095-fa66299a-05ed-42df-b50d-7180558362f2.png)

However I cannot find the path to the exported  tensorrt model and the logs .There is no such generated  .trt file or log file in the working directory I specified 
Can you tell me how to get the path of the  exported model i.e. the tensorrt model?

**Comment by lvhan028** [comment]
The converted model locates in the directory specified by `--work-dir` with suffix `.engine`

**Comment by ghoshsdeep** [comment]
Yes,Its clear now.Thank you so much for attending to the query in such a short time.I will close this issue
