### ISSUE TITLE
yolox转成onnx的疑问？

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmdeploy#1209]
为什么focus转成onnx之后 看到的是reshape-transpose这两种算子的组合呢？

**Comment by hanrui1sensetime** [comment]
Because `Focus` is not an onnx ops, so it must be combined with reshape and transpose ops.

**Comment by huoshuai-dot** [comment]
> Because `Focus` is not an onnx ops, so it must be combined with reshape and transpose ops.

但是 为啥不是slice+concat的组合呢？这个转换是在哪里实现的？

**Comment by huoshuai-dot** [comment]
mmdeploy重写了ncnn后端的focus实现，这个问题已澄清
