### ISSUE TITLE
[Bug] module 'mmcv' has no attribute 'Config'

### ISSUE THREAD

**Issue by right123123** [open-mmlab/mmdeploy#1211]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi, Please help me with the problem,I failed to convert my model to onnx in windows.

### Reproduction

The following is the command that I used:

 .\tools\deploy.py .\configs\mmpose\pose-detection_onnxruntime_static.py ..\mmpose\associative_embedding_hrnet_w32_coco_512x512.py ..\mmpose\hrnet_w32_coco_512x512-bcb8c247_20200816.pth ..\mmpose\tests\data\coco\000000000785.jpg --work-dir ..\mmpose\work_dir\ --show

### Environment

```Shell
The folloowing is my environment:
mmcv = 2.0.0rc1
mmcv-full = 1.6.2
mmdeploy = 0.9.0
mmdeploy-python = 0.9.0
mmpose = 0.28.1
onnx = 1.12.0
onnxruntime = 1.12.1
python = 3.8
```

**Comment by RunningLeon** [comment]
Hi, pls uninstall mmcv==2.0.0rc1 if you are using master branch of mmdeploy or released mmdeploy.

**Comment by right123123** [comment]
Thank for your reply! But It doesn't work after I uninstall mmcv.

> Hi, pls uninstall mmcv==2.0.0rc1 if you are using master branch of mmdeploy or released mmdeploy.

**Comment by RunningLeon** [comment]
@right123123 Hi, how do you install mmdeploy? which branch？

**Comment by right123123** [comment]
> @right123123 Hi, how do you install mmdeploy? which branch？

master

**Comment by RunningLeon** [comment]
> > @right123123 Hi, how do you install mmdeploy? which branch？
> 
> master, the bug had fixed by adding from mmcv.utils.config import *,then replace mmcv.Config with mmcv.utils.config in mmdeploy/utils/config_utils.py

@right123123 It seems something wrong here. If you are indeed using `mmcv-full==1.6.2`, then using `mmcv.Config` is Ok base on https://github.com/open-mmlab/mmcv/blob/847612dfffbcd917b6c267fe9decd4f8afed676e/mmcv/__init__.py#L6 and https://github.com/open-mmlab/mmcv/blob/847612dfffbcd917b6c267fe9decd4f8afed676e/mmcv/utils/__init__.py#L3

**Comment by right123123** [comment]
> > > @right123123 Hi, how do you install mmdeploy? which branch？
> > 
> > 
> > master, the bug had fixed by adding from mmcv.utils.config import *,then replace mmcv.Config with mmcv.utils.config in mmdeploy/utils/config_utils.py
> 
> @right123123 It seems something wrong here. If you are indeed using `mmcv-full==1.6.2`, then using `mmcv.Config` is Ok base on https://github.com/open-mmlab/mmcv/blob/847612dfffbcd917b6c267fe9decd4f8afed676e/mmcv/__init__.py#L6 and https://github.com/open-mmlab/mmcv/blob/847612dfffbcd917b6c267fe9decd4f8afed676e/mmcv/utils/__init__.py#L3

yeah,I made a mistake,The Config is a class in config.py

**Comment by RunningLeon** [comment]
Glad to know it solved.

**Comment by kingoo123** [comment]
I also had the same problem.How did you solve it? https://github.com/open-mmlab/mmdeploy/issues/1114#issuecomment-1309894649
