### ISSUE TITLE
[Bug] TransNet is not in the models registry

### ISSUE THREAD

**Issue by ghoshsdeep** [open-mmlab/mmdeploy#1218]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

A **customized OpenMMLab attention model** needs to be exported to a TensorRT backend .The following doc https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/02-how-to-run/convert_model.md was being referred for this 
![Screenshot from 2022-10-17 20-43-38](https://user-images.githubusercontent.com/112154951/196394089-184cf977-7f63-4441-b9fa-b87c717f2324.png)

### Reproduction

1.Upon using the running the command  python ./tools/deploy using the specified arguments., the error was encountered.

2.The input shape were adjusted according to the dataset in deploy_cfg.Original model config for the customized OpenMMLab attention model was used as model_cfg.

### Environment

```Shell
Refererring to the doc https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/linux-x86_64.md, Pytorch and other necessary installations were done using conda.
```

**Comment by grimoire** [comment]
The best solution is to integrate your own model into a custom branch of OpenMMLab repo. Or you can convert your model with apis:
```
from mmdeploy.apis.onnx import export
from mmedploy.backend.tensorrt import from_onnx

model = create_your_model()

export(model,.....)
from_onnx(onnx_file, ....)
```

Note that since you are using a custom model, you might need to register some rewriter to support the conversion.

**Comment by ghoshsdeep** [comment]
Thank you so much for the quick response to my query .It would really be helpful if you can provide a link to any  documentation/demo file regarding registry of rewriters for custom models.

**Comment by grimoire** [comment]
Read [this](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/07-developer-guide/support_new_model.md) for more detail.

**Comment by ghoshsdeep** [comment]
Thank you for sharing the documentation
