### ISSUE TITLE
[Docs] Is 'input' a parameter or a function in the given example

### ISSUE THREAD

**Issue by xox9943** [open-mmlab/mmdeploy#1258]
### 📚 The doc issue

https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/tutorial/02_challenges.md

这里的NewInterpolate类中第一个方法
 def symbolic(g,input,scales):
使用的input，input不是python关键字吗，这里是想传入的input方法还是input名字的参数啊

**Comment by lvhan028** [comment]
`input` is a variable. It works well if you don't try to use it as a callable object.
