### ISSUE TITLE
INVALID_ARGUMENT: getPluginCreator could not find plugin TRTBatchedNMS version 1

### ISSUE THREAD

**Issue by sanjaypavo** [open-mmlab/mmdeploy#126]
I am trying to host the yolov3 tenosrrt engine created in MMdeploy by following the instructions in the link(https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_convert_model.html) in Triton server. Facing the below attached error while hosting this engine, kindly respond.

![Screenshot from 2022-02-01 21-57-00](https://user-images.githubusercontent.com/93761297/152008683-20a18e0c-6b22-4b42-b1f6-82148193378d.png)

**Comment by RunningLeon** [comment]
> Triton

@sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.

**Comment by sanjaypavo** [comment]
> > Triton
> 
> @sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.

Thank you, @RunningLeon , I have resolved the issue by building the custom ops in the triton server.

**Comment by guoxiaojie-schinper** [comment]
> > > Triton
> > 
> > 
> > @sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.
> 
> Thank you, @RunningLeon , I have resolved the issue by building the custom ops in the triton server.

I face the same problem as you. Could you share the steps you use to build the custom ops in the triton server?  Looking forward to your reply, thank you very much.

**Comment by RunningLeon** [comment]
> > > > Triton
> > > 
> > > 
> > > @sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.
> > 
> > 
> > Thank you, @RunningLeon , I have resolved the issue by building the custom ops in the triton server.
> 
> I face the same problem as you. Could you share the steps you use to build the custom ops in the triton server? Looking forward to your reply, thank you very much.

@guoxiaojie-schinper Hi, have you tried according to this [doc](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops)? There should be no much difference with regard to building custom ops in Triton server.

**Comment by sanjaypavo** [comment]
> > > > Triton
> > > 
> > > 
> > > @sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.
> > 
> > 
> > Thank you, @RunningLeon , I have resolved the issue by building the custom ops in the triton server.
> 
> I face the same problem as you. Could you share the steps you use to build the custom ops in the triton server? Looking forward to your reply, thank you very much.

This [doc](https://github.com/triton-inference-server/server/blob/main/docs/custom_operations.md) helped me build custom ops in the triton server. Hope it helps.. @guoxiaojie-schinper

**Comment by guoxiaojie-schinper** [comment]
> > > > > Triton
> > > > 
> > > > 
> > > > @sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.
> > > 
> > > 
> > > Thank you, @RunningLeon , I have resolved the issue by building the custom ops in the triton server.
> > 
> > 
> > I face the same problem as you. Could you share the steps you use to build the custom ops in the triton server? Looking forward to your reply, thank you very much.
> 
> This [doc](https://github.com/triton-inference-server/server/blob/main/docs/custom_operations.md) helped me build custom ops in the triton server. Hope it helps.. @guoxiaojie-schinper

It works for me, thanks very much.

**Comment by Tpoc311** [comment]
> > > > > Triton
> > > > 
> > > > 
> > > > @sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.
> > > 
> > > 
> > > Thank you, @RunningLeon , I have resolved the issue by building the custom ops in the triton server.
> > 
> > 
> > I face the same problem as you. Could you share the steps you use to build the custom ops in the triton server? Looking forward to your reply, thank you very much.
> 
> This [doc](https://github.com/triton-inference-server/server/blob/main/docs/custom_operations.md) helped me build custom ops in the triton server. Hope it helps.. @guoxiaojie-schinper

The page is unavailable. Any changes about it?

**Comment by SushmaDG** [comment]
> > > > > > Triton
> > > > > 
> > > > > 
> > > > > @sanjaypavo Hi, could post here what script you ran? It seems custom ops for TensorRT are not built. You build tensorrt [custom ops](https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html#build-custom-ops) on your machine and try it again.
> > > > 
> > > > 
> > > > Thank you, @RunningLeon , I have resolved the issue by building the custom ops in the triton server.
> > > 
> > > 
> > > I face the same problem as you. Could you share the steps you use to build the custom ops in the triton server? Looking forward to your reply, thank you very much.
> > 
> > 
> > This [doc](https://github.com/triton-inference-server/server/blob/main/docs/custom_operations.md) helped me build custom ops in the triton server. Hope it helps.. @guoxiaojie-schinper
> 
> The page is unavailable. Any changes about it?

You can find the custom-ops for tensorrt doc here -> https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/06-custom-ops/tensorrt.md#trtbatchednms

MMDeploy documentation regarding the same : https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/tensorrt.html#build-custom-ops
