### ISSUE TITLE
cannot install "mmdeploy_python" package correctly

### ISSUE THREAD

**Issue by evergardenauok** [open-mmlab/mmdeploy#1262]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I can not generate "mmdeploy_python" package correctly, either by installing a precompiled package [here](https://github.com/open-mmlab/mmdeploy/releases) or [build MMDeploy from source](https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/build_from_source.html)

The precompiled package I installed is [mmdeploy-0.9.0-windows-amd64-onnxruntime1.8.1.zip](https://github.com/open-mmlab/mmdeploy/releases/download/v0.9.0/mmdeploy-0.9.0-windows-amd64-onnxruntime1.8.1.zip)

### Reproduction

1.According to the [tutorial](https://mmdeploy.readthedocs.io/en/latest/02-how-to-run/prebuilt_package_windows.html#how-to-use-prebuilt-package-on-windows10), when i was using SDK’s Python API for inference:
`python .\mmdeploy\demo\python\image_classification.py cpu .\work_dir\onnx\resnet\ .\mmclassification\demo\demo.JPEG`

the error occured:
`ImportError: DLL load failed while importing mmdeploy_python: %1 不是有效的 Win32 应用程序。`

after that i check the "mmdeploy_python" package in my virtual conda environment, and i think it's not installed completely:

![1666859708298](https://user-images.githubusercontent.com/116792636/198234119-145b5170-646a-47d4-b94c-d21ac16a8c0d.jpg)

![IFTXAM(6{TAR2SBOBIM FZ8](https://user-images.githubusercontent.com/116792636/198233754-5678c77d-051b-445e-8b19-f0437adf0977.png)

2.No, i didn't make any modifications on the code or config.

### Environment

```Shell
2022-10-27 15:46:36,259 - mmdeploy - INFO - 

2022-10-27 15:46:36,274 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-10-27 15:46:40,810 - mmdeploy - INFO - sys.platform: win32
2022-10-27 15:46:40,810 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
2022-10-27 15:46:40,810 - mmdeploy - INFO - CUDA available: True
2022-10-27 15:46:40,810 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 2060
2022-10-27 15:46:40,810 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3        
2022-10-27 15:46:40,810 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
2022-10-27 15:46:40,810 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30040 版
2022-10-27 15:46:40,829 - mmdeploy - INFO - GCC: n/a
2022-10-27 15:46:40,829 - mmdeploy - INFO - PyTorch: 1.8.0
2022-10-27 15:46:40,829 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

2022-10-27 15:46:40,830 - mmdeploy - INFO - TorchVision: 0.9.0
2022-10-27 15:46:40,830 - mmdeploy - INFO - OpenCV: 4.6.0
2022-10-27 15:46:40,830 - mmdeploy - INFO - MMCV: 1.6.2
2022-10-27 15:46:40,830 - mmdeploy - INFO - MMCV Compiler: MSVC 192930137
2022-10-27 15:46:40,830 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-10-27 15:46:40,830 - mmdeploy - INFO - MMDeploy: 0.9.0+
2022-10-27 15:46:40,830 - mmdeploy - INFO -

2022-10-27 15:46:40,831 - mmdeploy - INFO - **********Backend information**********
2022-10-27 15:46:42,302 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-10-27 15:46:42,306 - mmdeploy - INFO - tensorrt: None      ops_is_avaliable : False
2022-10-27 15:46:42,356 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-10-27 15:46:42,360 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-10-27 15:46:42,363 - mmdeploy - INFO - openvino_is_avaliable: False
2022-10-27 15:46:42,423 - mmdeploy - INFO - snpe_is_available: False
2022-10-27 15:46:42,427 - mmdeploy - INFO - ascend_is_available: False
2022-10-27 15:46:42,430 - mmdeploy - INFO - coreml_is_available: False
2022-10-27 15:46:42,430 - mmdeploy - INFO -

2022-10-27 15:46:42,430 - mmdeploy - INFO - **********Codebase information**********
2022-10-27 15:46:42,472 - mmdeploy - INFO - mmdet:      2.25.1
2022-10-27 15:46:42,472 - mmdeploy - INFO - mmseg:      None
2022-10-27 15:46:42,472 - mmdeploy - INFO - mmcls:      0.24.0
2022-10-27 15:46:42,472 - mmdeploy - INFO - mmocr:      None
2022-10-27 15:46:42,473 - mmdeploy - INFO - mmedit:     None
2022-10-27 15:46:42,473 - mmdeploy - INFO - mmdet3d:    None
2022-10-27 15:46:42,473 - mmdeploy - INFO - mmpose:     None
2022-10-27 15:46:42,473 - mmdeploy - INFO - mmrotate:   None
```

### Error traceback

```Shell
(mmdeploy) D:\code\AI>python .\mmdeploy\demo\python\image_classification.py cpu .\work_dir\onnx\resnet\ .\mmclassification\demo\demo.JPEG
Traceback (most recent call last):
  File ".\mmdeploy\demo\python\image_classification.py", line 5, in <module>
    from mmdeploy_python import Classifier
  File "D:\anaconda3\envs\mmdeploy\lib\site-packages\mmdeploy_python\__init__.py", line 21, in <module>
    from .mmdeploy_python import *  # noqa
ImportError: DLL load failed while importing mmdeploy_python: %1 不是有效的 Win32 应用程序。
```

**Comment by evergardenauok** [comment]
Have you ever encountered this problem? It has been bothering me for several days. I searched on github but still can't solve it.Hope for your solution.

**Comment by irexyc** [comment]
Hi, @evergardenauok are you using the 64-bit python.exe?

You can check throught:
```
import platform
print(platform.architecture())
```

**Comment by evergardenauok** [comment]
> Hi, @evergardenauok are you using the 64-bit python.exe?
> 
> You can check throught:
> 
> ```
> import platform
> print(platform.architecture())
> ```

```
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print(platform.architecture())
('64bit', 'WindowsPE')
```

**Comment by evergardenauok** [comment]
So what does it mean and what could i do?

**Comment by irexyc** [comment]
Coud you use [this](https://github.com/lucasg/Dependencies) to check if the dependencies of mmdeploy_python.cp38-win_amd64.pyd exists in your PATH

**Comment by irexyc** [comment]
Hi, I found the reason.  It's because  mmdeploy_python.cp38-win_amd64.pyd rely on onnxruntime.dll, but there are two onnxruntime.dll exists in `C:\Windows\System32\onnxruntime.dll` and `C:\Windows\SysWOW64\onnxruntime.dll` which will load first. You can use depencencies-gui.exe to check this.

The simple solutiion is to rename that files. like rename `C:\Windows\System32\onnxruntime.dll` to `C:\Windows\System32\onnxruntime.dll--` and `C:\Windows\SysWOW64\onnxruntime.dll` to `C:\Windows\SysWOW64\onnxruntime.dll--`

**Comment by evergardenauok** [comment]
> Coud you use [this](https://github.com/lucasg/Dependencies) to check if the dependencies of mmdeploy_python.cp38-win_amd64.pyd exists in your PATH

i do this and it shows “C:\Windows\system32\onnxruntime.dll module has missing imports”

![1667287093802](https://user-images.githubusercontent.com/116792636/199179975-7fb24619-dcc0-4fe2-b854-adbbf89ed425.png)

**Comment by irexyc** [comment]
1. Hide C:\Windows\system32\onnxruntime.dll and C:\Windows\SysWOW64\onnxruntime.dll by renaming them.
2. Add the downloaded onnxruntime lib to the PATH. ( If it exists in D:\onnxruntime-1.8.1\lib, and D:\onnxruntime-1.8.1\lib to the PATH)

**Comment by evergardenauok** [comment]
> You have to let the mmdeploy_python.cp38-win_amd64.pyd load the right onnxruntime.dll. The onnxruntime.dll exists in the system folder is not the right dll and I can't find any information about it.
> 
> 1. Hide C:\Windows\system32\onnxruntime.dll and C:\Windows\SysWOW64\onnxruntime.dll by renaming them.
> 2. Add the downloaded onnxruntime lib to the PATH. ( If it exists in D:\onnxruntime-1.8.1\lib, and D:\onnxruntime-1.8.1\lib to the PATH)
I have added onnxruntime to the PATH from the beginning，but this error still occurred.

I tried step 1 as you suggest but failed. I cannot rename the onnxruntime.dll in C:\Windows\system32 because of system permissions problem，although I made changes according to some tutorials.

If you don't have other solution，I would give up python API and use C++ API instead.

**Comment by irexyc** [comment]
To change the onnxruntime.dll in above two dirs, you have to change the owner of onnxruntime.dll first.

Or you can paste the right onnxruntime.dll to the same folder where python.exe exists.

**Comment by evergardenauok** [comment]
> To change the onnxruntime.dll in above two dirs, you have to change the owner of onnxruntime.dll first. （you can refer to this https://blog.csdn.net/kissdead0xzy/article/details/79562562)

I tried it and this window pops up after the last step:
![0940)TKITDMT3VAG74QLY`3](https://user-images.githubusercontent.com/116792636/199424657-32069ba0-5604-482d-82b6-b34db184ce33.jpg)

**Comment by evergardenauok** [comment]
> > To change the onnxruntime.dll in above two dirs, you have to change the owner of onnxruntime.dll first. （you can refer to this https://blog.csdn.net/kissdead0xzy/article/details/79562562)
> 
> I tried it and this window pops up after the last step: ![0940)TKITDMT3VAG74QLY`3](https://user-images.githubusercontent.com/116792636/199424657-32069ba0-5604-482d-82b6-b34db184ce33.jpg)

I can rename the dll now！I followed this article：https://www.pianshen.com/article/89251716622/

**Comment by irexyc** [comment]
Is the problem still exists?

**Comment by evergardenauok** [comment]
The dependencies of mmdeploy_python.cp38-win_amd64.pyd are normal，but I still haven't install the mmdeploy-python package successfully. I'll try again tomorrow.

**Comment by evergardenauok** [comment]
I still cannot install the  mmdeploy-python package successfully.
Meanwhile I find that the code [here](https://github.com/open-mmlab/mmdeploy/blob/master/tools/package_tools/packaging/mmdeploy_python/__init__.py) is the same as the mmdeploy_python package I installed in the virtual environment several days ago.
I wonder if it's incomplete

![image](https://user-images.githubusercontent.com/116792636/199670447-c0d8f81f-bc75-486d-8862-77f405d52fe8.png)

**Comment by evergardenauok** [comment]
I just want to execute this script（python API） in the [tutorial](https://mmdeploy.readthedocs.io/en/latest/get_started.html#python-api).

![image](https://user-images.githubusercontent.com/116792636/199670789-7a6e4f29-90d2-402a-8362-07dfd8af8d15.png)

And I can't find import Detector from the mmdeploy_python package since there are not any module in the mmdeploy_python package, as I mentioned before.

**Comment by evergardenauok** [comment]
Can you install the mmdeploy_python package correctly? If you can, could you show me the screenshot for what's the correct structure of the  mmdeploy_python package in the virtual environment?

**Comment by irexyc** [comment]
The [tutorial](https://mmdeploy.readthedocs.io/en/latest/get_started.html#python-api) you posted use the  precompiled mmdeploy_python package. If you install the precompiled package, you will get the right structure of mmdeploy_python.

If you compile mmdeploy youself, there are to ways to use. The one is generate mmdeploy_python whl package and install it, you could refer to tools/package_tools/mmdeploy_builder.py. To use the build script, you need to modify some environment variables in tools/package_tools/configs/windows_x64.yaml. However I suggest the other way, you only need to add two environment variables like below:
```
// powershell, temporarily
$env:PYTHONPATH="dir/to/mmdeploy_python.cp38-win_amd64.pyd"
$env:PATH="env:PATH;dir/to/build/Release/bin"

python demo/python/object_detection.py ...

// for persistence
// You should add the two variables to the System Settings, you can refer to this:
// https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0
```

**Comment by evergardenauok** [comment]
Thank you for your help! I can execute the order now:
`python .\mmdeploy\demo\python\image_classification.py cpu .\work_dir\onnx\resnet\ .\mmclassification\demo\demo.JPEG`
I confirmed the reason for the error
`ImportError: DLL load failed while importing mmdeploy_python: %1 不是有效的 Win32 应用程序。`
is the onnxruntime.dll in C:\Windows\System32. After I rename it to onnxruntime--.dll as you suggest, I can use the Python API for inference.

Though I don't understand how the mmdeploy_python package with a strange structure works, it doesn't cause a bug.
You can close this issue now.

**Comment by GSusan** [comment]
Through copy onnxruntime.dll and onnxruntime_providers_shared.dll to path of "Lib\site-packages\mmdeploy_python", I solve it.
