### ISSUE TITLE
On Jetson platform with older TRT7, output bbox and mask appears distorted.

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#127]
I have previously used mmdeploy to deploy a model to TensorRT backend using MMDeploy/tools/deploy.py and inference based on the mmdeploy SDK `object_detection.cpp` example.

When on the PC, the test output images generated by deploy.py contain identical detections in both pytorch and tensorrt.

However, when I repeat the steps on a Jetson platform, it does not result in identical results. Instead, the detections appear shifted and the masks are distorted. I have used identical mmdeploy configurations for both platforms and identical model input.

I am not sure where to proceed but I suspect there is an incompatibility with the version of tensorrt installed on my Jetson AGX. Before I upgrade to latest Jetpack, I would like to know if you have seen this issue before.

**Comment by SingleZombie** [comment]
Hi, we have tested detection models on Jetson TX2 and Xavier. We haven't seen the issue before. Could you please provide your model_cfg, deploy_cfg, deploy command as well as your TensorRT version on both platforms? We can try to reproduce this issue.

**Comment by SingleZombie** [comment]
Hi, I tested Mask R-CNN on our Jetson TX2:
```
NVIDIA Jetson TX2
 L4T 32.6.1 [ JetPack 4.6 ]
   Ubuntu 18.04.5 LTS
   Kernel Version: 4.9.253-tegra
 CUDA 10.2.300
   CUDA Architecture: 6.2
 OpenCV version: 4.1.1
   OpenCV Cuda: NO
 CUDNN: 8.2.1.32
 TensorRT: 8.0.1.6
 Vision Works: 1.6.0.501
 VPI: ii libnvvpi1 1.1.12 arm64 NVIDIA Vision Programming Interface library
 Vulcan: 1.2.70
```
I used the following command. The checkpoint is downloaded from MMDetection.
```
python   ~/mmdeploy/tools/deploy.py  
 ~/mmdeploy/configs/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py 
/home/pjlab/mmdetection/configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_1x_coco.py
/home/pjlab/mmdetection/checkpoints/mask_rcnn_r50_caffe_fpn_1x_coco_bbox_mAP-0.38__segm_mAP-0.344_20200504_231812-0ebd1859.pth
work_dirs/demo2.jpg
--test-img work_dirs/demo2.jpg 
--work-dir work_dirs/output/mmdet-is-trt-8-0/ 
--device cuda:0 
--log-level INFO
```
The results of PyTorch and TensorRT were identical. I am sorry to say I cannot reproduce the bug.

**Comment by tehkillerbee** [comment]
@SingleZombie I should clarify, that I get identical/correct results on Jetpack 4.6 but not on Jetpack 4.5. Both platforms use the same versions of mmdeploy and dependencies. Main difference is TensorRT version.

**Comment by SingleZombie** [comment]
Yes, we think the issue is caused by TensorRT 7.1. Thank you for reporting this bug. We don't plan to support TensorRT <= 7.1 now. Maybe we will support it in the future.

**Comment by tehkillerbee** [comment]
@SingleZombie That makes sense. In that case this issue and #114 can probably be closed.

**Comment by tehkillerbee** [comment]
Closing this issue,as TRT7 will not be supported at this point
