### ISSUE TITLE
[Feature] prepare install script in no proxy network

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#1283]
### Motivation

in the no proxy environment，the github submodule can't aceess, may we provide install script in no proxy network

### Related resources

in the no proxy environment，the github submodule can't aceess, may we provide install script in no proxy network

### Additional context

in the no proxy environment，the github submodule can't aceess, may we provide install script in no proxy network

**Comment by lvhan028** [comment]
@tpoisonooo any good ideas?

**Comment by tpoisonooo** [comment]
Build a mirror website, upload prebuilt mmdeploy and requirements to aliyun .
