### ISSUE TITLE
[Bug] Can't get attribute 'target_wrapper' on <module '__main__>  of deploy.py in debug mode

### ISSUE THREAD

**Issue by hhaAndroid** [open-mmlab/mmdeploy#13]
**Reproduction**

In debug mode, deploy will have attribute errors. The reason is that spawn starts multiple processes and does not allow target_wrapper to be located under the `__main__` module.  You can refer to https://github.com/ipython/ipython/issues/10894

**Error traceback**

```none
(<class 'AttributeError'>, 
AttributeError("Can't get attribute 'target_wrapper' on <module '__main__' (built-in)>"), 
<traceback object at 0x7fb63cdb7b40>)
```

**Bug fix**

Move the `target_wrapper` function to other files.

**Comment by AllentDan** [comment]
Hi, @hhaAndroid. Could you help review #20 ?
