### ISSUE TITLE
Documentation on mounting local dir to mmdeploy container

### ISSUE THREAD

**Issue by davodogster** [open-mmlab/mmdeploy#1304]
### 📚 The doc issue

docker run --gpus all -v `pwd`:/workspace -it mmdeploy:master-gpu

When I run this, I cant see any of my local files inside the container. Do you know why it wont work? Is it bad to be inside the container as root user?

![image](https://user-images.githubusercontent.com/46079516/199869840-fdcd39ac-3315-4ad4-a2eb-9d35afbbbe15.png)

Thanks!

### Suggest a potential alternative/fix

More detailed documentation here https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/build_from_docker.md

**Comment by lvhan028** [comment]
In the command, it maps the local directory to `/workspace` in your container. But you are accessing `~/workspace` according to the captured image.
Please move to `/workspace` and check it again.
