### ISSUE TITLE
[Bug] quant_image_dataset crashed with mmcv.DataContainer

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmdeploy#1351]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

https://github.com/open-mmlab/mmdeploy/blob/18c6ae57cfc5f555d556fe8f4a70f91fb213897b/tools/quant_image_dataset.py#L85
这里面经过mmedet pipeline里面的defaultformatbundle之后result[‘img']不再是tensor而是datacontainer https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/formatting.py#L230
然后就会出错 请问这个问题如何处理？

### Reproduction

。

### Environment

```Shell
。
```

**Comment by tpoisonooo** [comment]
According to mmcv DataConcatiner source code here  https://github.com/open-mmlab/mmcv/blob/6254ebef8d1d106e9cca8d4097786c6172cf70ce/mmcv/parallel/data_container.py#L59 ,

We can use  `return {'img': data['img'].data().squeeze()} `  to extract image tensor.

**Comment by huoshuai-dot** [comment]
> According to mmcv DataContainer source code here https://github.com/open-mmlab/mmcv/blob/6254ebef8d1d106e9cca8d4097786c6172cf70ce/mmcv/parallel/data_container.py#L59 ,
> 
> We can use `return {'img': data['img'].data().squeeze()} ` to extract image tensor.
> 
> 这里有 mmcv Concatiner 源码， 加个 data() 提出 tensor 就行。临时 fix 是这样，感觉我得加个 PR fix 一下这里。
貌似这里返回的data['img']还是一个data_container的list ，而且 collate([data],samples_per_gpu=1)会导致data['img'].data还是一个data_container的list，直接按照上面的改法不太行

**Comment by tpoisonooo** [comment]
一环套一环... 给我个完整的复现命令。
