### ISSUE TITLE
How can I get the feature from trt engine?

### ISSUE THREAD

**Issue by dklee98** [open-mmlab/mmdeploy#1377]
I already know how I get the feature in pytorch model, but the trt engine can't support feature hook. The inference module only saves the results of an image. How can I get the feature during converting model or inference? Is there an easy way?

My converter code is deploy.py and inference code is object_detection.py in mmdeploy/demo/python.

Thank you

**Comment by lvhan028** [comment]
As far as I know, the TensorRT engine is a static graph.
Thus, if you want to get feature map from a detection model, you can export the pytorch model backbone (or neck if it exists in the model) to onnx omdel

**Comment by dklee98** [comment]
Thank you I will try it
