### ISSUE TITLE
Original research backbone  architecture missing！

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmdeploy#1389]
### 📚 The doc issue

hi，
     Is there some original research backbone  architecture by MMLAB or sensetime？ Could you show some model like that or share the link with me？  
     Looking forward to your reply ~   

BR 

### Suggest a potential alternative/fix

hi，
     Is there some original research backbone  architecture by MMLAB or sensetime？ Could you show some model like that or share the link with me？  
     Looking forward to your reply ~   

BR

**Comment by lvhan028** [comment]
This is not an issue related to MMDeploy, since MMDeploy focuses on model deployment rather than designing models.
