### ISSUE TITLE
[Bug] mmdeploy_python not in offical docker image

### ISSUE THREAD

**Issue by yuanyuangoo** [open-mmlab/mmdeploy#1400]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

I build a docker container using official docker file. I still got ModuleNotFoundError: No module named 'mmdeploy_python'.

What should I do to get mmdeploy_python in docker?

### Reproduction

python -m "from mmdeploy_python import Segmentor"

### Environment

```Shell
nvidia-docker
```

### Error traceback

```Shell
from mmdeploy_python import Segmentor
ModuleNotFoundError: No module named 'mmdeploy_python'
```

**Comment by lvhan028** [comment]
Could you append the path of `/root/workspace/mmdeploy/build/lib` to the environment variable `PYTHONPATH` in the dockerfile and try it again?

**Comment by yuanyuangoo** [comment]
Thanks, problem solved.
