### ISSUE TITLE
[Docs] ctypes.CDLL(lib_path)

### ISSUE THREAD

**Issue by hch-baobei** [open-mmlab/mmdeploy#1443]
### 📚 The doc issue

I have a question for you. When I read the mmdeploy source code, I keep seeing this line of code when loading a custom plugin:
mmdeploy.backend.tensorrt.init_plugins.py 29-39
`ctypes.CDLL(lib_path)`
It doesn't return anything, so why is it okay to call some of these functions or variables? Where does the DLL load into python?

**Comment by lvhan028** [comment]
I suggest learning compile and linker at first. https://www.lurklurk.org/linkers/linkers.html
