### ISSUE TITLE
When run deploy.py [Bug] 

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmdeploy#1449]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When run deploy.py with my own model

### Reproduction

deploy.py

### Environment

```Shell
pytorch 1.8.0
```

### Error traceback

```Shell
RuntimeError: Exporting the operator col2im to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

**Comment by xin-li-67** [comment]
Hi, this col2im issue has been fixed in onnx officially. Would you please check the version of your onnx and onnxruntime? Try to update them if you can.

**Comment by lvhan028** [comment]
May provide more information. 
- the actual running command
- the result of `python tools/check_env.py`
