### ISSUE TITLE
[Bug]c++ SDK 推理mmdet-swin的onnx模型时出错：[mmdeploy] [error] [instance_segmentation.cpp:68] invalid argument (1)

### ISSUE THREAD

**Issue by kywish** [open-mmlab/mmdeploy#1466]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

在使用mmdeploy/tools/deploy.py导出swin-transformer-object-detection的onnx模型时成功，并生成deploy.json等信息。在使用c++ SDK加载这个模型时成功，但推理时出错：[error] [instance_segmentation.cpp:68] invalid argument (1)

### Reproduction

  //使用mmdeploy预编译包中的.\example\cpp\cpp\detector.cxx测试，代码如下：

  auto device_name = "cpu";
  auto model_path = "./work-dir";
  auto image_path = "./work-dir/test1.jpg";
  cv::Mat img = cv::imread(image_path);
  if (!img.data) {
    fprintf(stderr, "failed to load image: %s\n", image_path);
    return 1;
  }

  mmdeploy::Model model(model_path);
  mmdeploy::Detector detector(model, mmdeploy::Device{device_name, 0});

  //这步出错，貌似在create mask时传参不对
  auto dets = detector.Apply(img);

### Environment

```Shell
vs-2019
opencv-4.6.0
onnxruntime-1.11.1
mmdeploy-预编译包mmdeploy-0.10.0-windows-amd64-onnxruntime1.8.1.zip
```

### Error traceback

```Shell
[2022-11-30 11:13:38.183] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
[2022-11-30 11:13:38.271] [mmdeploy] [info] [model.cpp:39] DirectoryModel successfully load model
...
...
...
[2022-11-30 11:13:39.659] [mmdeploy] [info] [inference.cpp:50] ["img"] <- ["image"]
[2022-11-30 11:13:39.659] [mmdeploy] [info] [inference.cpp:61] ["post_output"] -> ["dets"]
[2022-11-30 11:13:43.082] [mmdeploy] [error] [instance_segmentation.cpp:68] invalid argument (1)
```

**Comment by AllentDan** [comment]
Did not reproduce the error of MMDeploy master branch in Ubuntu. Hi, @irexyc could you give a hand on this?

**Comment by irexyc** [comment]
I use [this config](https://github.com/open-mmlab/mmdetection/blob/master/configs/swin/mask_rcnn_swin-t-p4-w7_fpn_1x_coco.py) and the prebuilt package mmdeploy-0.10.0-windows-amd64-onnxruntime1.8.1.zip, the everything goes well.

Please provide the more information like:
```
1. the convert command
2. the config file, link or paste
3. the full log after your run
```

**Comment by kywish** [comment]
> 

[issues.md](https://github.com/open-mmlab/mmdeploy/files/10137791/issues.md)

**Comment by irexyc** [comment]
According the information you provide, It seems you are using pycharm console to run the detector.exe which may hide some errors. Please just use `cmd` or `powershell` to run `detector.exe`

As there already exists the prebuilt detector.exe in sdk/bin/, you shoud first try to use it to run the model.

Also, there may be problems when you build your executable, you could provide the CMakeLists.txt for build detector.exe.

**Comment by kywish** [comment]
Hi~ , the result of use powershell to run detector.exe is the same as before. 
And the executable is build&launched by clion. Plz check cmakelists.txt in the appendix.
[issuse.md](https://github.com/open-mmlab/mmdeploy/files/10139377/issuse.md)

**Comment by irexyc** [comment]
@kywish 
Have you tried the prebuilt detector.exe in `sdk/bin/` folder?

**Comment by kywish** [comment]
> @kywish Have you tried the prebuilt detector.exe in `sdk/bin/` folder?

Yes，the log is print by  `sdk/bin/detector.exe`

**Comment by kywish** [comment]
> > @kywish Have you tried the prebuilt detector.exe in `sdk/bin/` folder?
> 
> Yes，the log is print by `sdk/bin/detector.exe`

I tested other model，like yolo, the detector.exe work normally。
But in swin-transformer , error occurred in  `instance_segmentation.cpp `，function  `ResizeInstanceMask() `.

And my project ,if necessary：
https://pan.baidu.com/s/1zP1aKL5ZzYvFmU9ez40FIA?pwd=3ywf 
my cmakelists.txt is in `.\mmdeploy-sdk\example\cpp\CMakeLists.txt`

**Comment by irexyc** [comment]
It seems like I missed something.

I checked you model, the error is due to the wrong `deploy_cfg` you used when convert the model.

According to your first issue.md, you used `../mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py` as `deploy_cfg`. However, you should use `../mmdeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py` instead.

> > 
> 
> [issues.md](https://github.com/open-mmlab/mmdeploy/files/10137791/issues.md)
