### ISSUE TITLE
python demo/python/object_detection error[Bug] 

### ISSUE THREAD

**Issue by ChenZhenGui** [open-mmlab/mmdeploy#1474]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

When I used the changed model from pytorch to tensorrt(engine) with the model fastet-rcnn to run the demo ,here are some error

### Reproduction

python demo/python/object_detection.py 
device_name=cuda model_path=/home/nvidia/Desktop/mmdeploy/mmdeploy_models/mmdet/tensorrt/end2end.engine 
image_path=home/nvidia/Desktop/mmdeploy/demo/resources/det.jpg

### Environment

```Shell
12/01 11:03:32 - mmengine - INFO - **********Environmental information**********
/home/nvidia/miniforge3/envs/mobilevit_test/lib/python3.6/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
12/01 11:03:36 - mmengine - INFO - sys.platform: linux
12/01 11:03:36 - mmengine - INFO - Python: 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 19:12:04) [GCC 9.4.0]
12/01 11:03:36 - mmengine - INFO - CUDA available: True
12/01 11:03:36 - mmengine - INFO - numpy_random_seed: 2147483648
12/01 11:03:36 - mmengine - INFO - GPU 0: NVIDIA Tegra X1
12/01 11:03:36 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-10.2
12/01 11:03:36 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.300
12/01 11:03:36 - mmengine - INFO - GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
12/01 11:03:36 - mmengine - INFO - PyTorch: 1.8.0
12/01 11:03:36 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.2.1
    - Built with CuDNN 8.0
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=8.0.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, 

12/01 11:03:36 - mmengine - INFO - TorchVision: 0.11.3
12/01 11:03:36 - mmengine - INFO - OpenCV: 4.6.0
12/01 11:03:36 - mmengine - INFO - MMEngine: 0.3.1
12/01 11:03:36 - mmengine - INFO - MMCV: 2.0.0rc2
12/01 11:03:36 - mmengine - INFO - MMCV Compiler: GCC 7.5
12/01 11:03:36 - mmengine - INFO - MMCV CUDA Compiler: 10.2
12/01 11:03:36 - mmengine - INFO - MMDeploy: 0.10.0+71344b2
12/01 11:03:36 - mmengine - INFO - 

12/01 11:03:36 - mmengine - INFO - **********Backend information**********
12/01 11:03:40 - mmengine - INFO - onnxruntime: None	ops_is_avaliable : False
12/01 11:03:41 - mmengine - INFO - tensorrt: 8.0.1.6	ops_is_avaliable : True
12/01 11:03:41 - mmengine - INFO - ncnn: None	ops_is_avaliable : False
12/01 11:03:41 - mmengine - INFO - pplnn_is_avaliable: False
12/01 11:03:41 - mmengine - INFO - openvino_is_avaliable: False
12/01 11:03:41 - mmengine - INFO - snpe_is_available: False
12/01 11:03:41 - mmengine - INFO - ascend_is_available: False
12/01 11:03:41 - mmengine - INFO - coreml_is_available: False
12/01 11:03:41 - mmengine - INFO - 

12/01 11:03:41 - mmengine - INFO - **********Codebase information**********
12/01 11:03:41 - mmengine - INFO - mmdet:	3.0.0rc3
12/01 11:03:41 - mmengine - INFO - mmseg:	None
12/01 11:03:41 - mmengine - INFO - mmcls:	None
12/01 11:03:41 - mmengine - INFO - mmocr:	None
12/01 11:03:41 - mmengine - INFO - mmedit:	None
12/01 11:03:41 - mmengine - INFO - mmdet3d:	None
12/01 11:03:41 - mmengine - INFO - mmpose:	1.0.0rc0
12/01 11:03:41 - mmengine - INFO - mmrotate:	None
12/01 11:03:41 - mmengine - INFO - mmaction:	None
```

### Error traceback

```Shell
[2022-12-01 11:01:20.187] [mmdeploy] [info] [model.cpp:98] Register 'DirectoryModel'
[ WARN:0@0.134] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('image_path=home/nvidia/Desktop/mmdeploy/demo/resources/det.jpg'): can't open/read file: check file path/integrity
[2022-12-01 11:01:20.201] [mmdeploy] [error] [model.cpp:45] no ModelImpl can read model /home/nvidia/Desktop/mmdeploy/mmdeploy_models/mmdet/tensorrt/end2end.engine
[2022-12-01 11:01:20.201] [mmdeploy] [error] [model.cpp:15] load model failed. Its file path is '/home/nvidia/Desktop/mmdeploy/mmdeploy_models/mmdet/tensorrt/end2end.engine'
[2022-12-01 11:01:20.202] [mmdeploy] [error] [model.cpp:21] failed to create model: not supported (2) @ /home/nvidia/Desktop/mmdeploy/csrc/mmdeploy/core/model.cpp:46
Traceback (most recent call last):
  File "demo/python/object_detection.py", line 48, in <module>
    main()
  File "demo/python/object_detection.py", line 26, in main
    model_path=args.model_path, device_name=args.device_name, device_id=0)
RuntimeError: failed to create detector
```

**Comment by AllentDan** [comment]
The model path should be `/home/nvidia/Desktop/mmdeploy/mmdeploy_models/mmdet/tensorrt`.

**Comment by irexyc** [comment]
There are two errors in your command.

1. the `device_name` , `model_path`, `image_path` are positional arguments, you don't need to pass key=value
2. model_path should be model dir instead of engine file

So, the right command shoud be:
```
python demo/python/object_detection.py cuda /home/nvidia/Desktop/mmdeploy/mmdeploy_models/mmdet/tensorrt/ /home/nvidia/Desktop/mmdeploy/demo/resources/det.jpg
```

**Comment by ChenZhenGui** [comment]
I get it! Thx! by the way ,I wander that why I successfully  convert the model which is used my own backbone(mobilevit), I just see some report that doesn't convert success because they used their own model

**Comment by ChenZhenGui** [comment]
hello ,I want to know how to use the vedio_recognition.py ? I use this command and report the following error:
python demo/python/video_recognition.py cuda /home/nvidia/Desktop/mmdeploy/mmdeploy_models/mmpose/tensorrt/ /home/nvidia/Desktop/mmpose/demo/demo.mp4

[2022-12-01 12:20:16.998] [mmdeploy] [warning] [transform.h:47] Cannot find TopDownAffine implementation on platform cuda
[2022-12-01 12:20:16.998] [mmdeploy] [info] [transform.h:51] Fallback TopDownAffine implementation to platform cpu
[2022-12-01 12:20:20.629] [mmdeploy] [info] [inference.cpp:50] ["img"] <- ["video"]
[2022-12-01 12:20:20.629] [mmdeploy] [info] [inference.cpp:61] ["post_output"] -> ["label"]
[2022-12-01 12:20:21.124] [mmdeploy] [error] [module_adapter.h:34] unhandled exception: invalid argument (1) @ /home/nvidia/Desktop/mmdeploy/csrc/mmdeploy/core/value.h:853
terminate called after throwing an instance of 'system_error2::status_error<mmdeploy::StatusDomain>'
  what():  unknown (6) @ /home/nvidia/Desktop/mmdeploy/csrc/mmdeploy/experimental/module_adapter.h:35
Aborted

**Comment by irexyc** [comment]
`video_recognition.py` is use for classification model used for mmaction2 (tsn or slowfast)

May be you want  to use [pose_detection.py](https://github.com/open-mmlab/mmdeploy/blob/master/demo/python/pose_detection.py)

**Comment by ChenZhenGui** [comment]
ok, I want to detect with the webcam ,is there some demo for it?

**Comment by irexyc** [comment]
[pose_detection.py](https://github.com/open-mmlab/mmdeploy/blob/master/demo/python/pose_detection.py) accept image as input, you can use `VideoCapture` in opencv for simple usage.

**Comment by lvhan028** [comment]
> I get it! Thx! by the way ,I wander that why I successfully convert the model which is used my own backbone(mobilevit), I just see some report that doesn't convert success because they used their own model

Congrats, you won the lottery 😄 

As far as I know, backbone models are usually onnx-friendliness, i.e., they can be successfully exported to onnx without making any changes. 
Among all mmclassification deployable models supported by mmdeploy, we only hack two of them, which can be found here: https://github.com/open-mmlab/mmdeploy/tree/master/mmdeploy/codebase/mmcls/models/backbones
So, replacing an openmmlab model's backbone with another one **probably** won't cause trouble. 

But head models are not as onnx friendly as backbone models. They are more complicated and usually cannot be exported to onnx easily. You may find mmdeploy rewrites lots of head models for mmdetection model deployment. 
Thus, customizing a head model will probably suffer when exporting to onnx.
