### ISSUE TITLE
[Docs] Build for Jetson

### ISSUE THREAD

**Issue by dongL-Wu** [open-mmlab/mmdeploy#1479]
### 📚 The doc issue

Hi, thanks for your hard work first. Docs for building is very clear. When I follow [Build for Jetson](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/jetsons.md) and have a question on part of Install MMDeploy:  
Whether part of "Install Model Converter" and part of "Install C/C++ Inference SDK"  all build in directory of  mmdeploy?  If that, why need two steps?

```Bash
# Install Model Converter
mkdir -p build && cd build
cmake .. -DMMDEPLOY_TARGET_BACKENDS="trt"
make -j$(nproc) && make install
cd ${MMDEPLOY_DIR}
pip install -v -e .
```

```Bash
# Install C/C++ Inference SDK
mkdir -p build && cd build
cmake .. \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
    -DMMDEPLOY_TARGET_BACKENDS="trt" \
    -DMMDEPLOY_CODEBASES=all \
    -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl
make -j$(nproc) && make install
```

**Comment by hanrui1sensetime** [comment]
If you only need model converter to get the `.onnx`, and backend models like trt engine, you can only install model converter.
If you also need c++ inference, you can install c/c++ inference sdk.

**Comment by dongL-Wu** [comment]
> If you only need model converter to get the `.onnx`, and backend models like trt engine, you can only install model converter. If you also need c++ inference, you can install c/c++ inference sdk.

Thanks for you reply. And I just want to know both of them can be built at the same time?

**Comment by hanrui1sensetime** [comment]
> > If you only need model converter to get the `.onnx`, and backend models like trt engine, you can only install model converter. If you also need c++ inference, you can install c/c++ inference sdk.
> 
> Thanks for you reply. And I just want to know both of them can be built at the same time?

Of course you can. In fact, the latter `install c++ inference sdk` compilation includes the former compilation.

**Comment by lvhan028** [comment]
More precisely,
```
## install mmdeploy converter python code
pip install -v -e .

## build custom ops and SDK together
mkdir -p build && cd build
cmake .. \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
    -DMMDEPLOY_TARGET_BACKENDS="trt" \
    -DMMDEPLOY_CODEBASES=all \
    -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl
make -j$(nproc) && make install
```
