### ISSUE TITLE
[Feature] 多模型推理

### ISSUE THREAD

**Issue by kacifer999** [open-mmlab/mmdeploy#1482]
### Motivation

我目前用C#的SDK，想部署一套模型，由1个mmcls模型和1个mmseg模型组成。这两个模型是串行关系。目前mmdeploy是否能够支持？

**Comment by lzhangzz** [comment]
Can you elaborate how are you feeding the classification output to the segmentation model?

**Comment by lzhangzz** [comment]
Can you elaborate on how are you feeding the classification output to the segmentation model?

**Comment by lzhangzz** [comment]
That seems to be trivial using a combination of classifier and segmentor API. So what's preventing you from conditionally applying the segmentor after obtaining the classification result using the C# API?
