### ISSUE TITLE
On barnch dev-1.x, I just submitted a problem (# 1438) because of a bug in the Docker version. I finally saw this change(#1320) when I had time to verify it today. Why?

### ISSUE THREAD

**Issue by labmanno004** [open-mmlab/mmdeploy#1503]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

[RunningLeon](https://github.com/RunningLeon) [[Enhancement]: add md link check github action (](https://github.com/open-mmlab/mmdeploy/commit/25aa0d4c0a4c83357ba453de35c70c3443bbdc55)https://github.com/open-mmlab/mmdeploy/pull/1320[)](https://github.com/open-mmlab/mmdeploy/commit/25aa0d4c0a4c83357ba453de35c70c3443bbdc55)
…
Latest commit [25aa0d4](https://github.com/open-mmlab/mmdeploy/commit/25aa0d4c0a4c83357ba453de35c70c3443bbdc55) 1 hour ago
[ History](https://github.com/open-mmlab/mmdeploy/commits/dev-1.x/docker/CPU/Dockerfile)
* add md link check action

* add config

* fix doc link

* fix dead links

* **change dev-1.x to 1.x**

* fix mmocr url

### Reproduction

/

### Environment

```Shell
/
```

**Comment by lvhan028** [comment]
Sorry. Can you use this commit 09c6bd75 in dev-1.x branch at first?

**Comment by labmanno004** [comment]
> Sorry. Can you use this commit [09c6bd7](https://github.com/open-mmlab/mmdeploy/commit/09c6bd75aae5cfee35a89b39e97d06855748c70c) in dev-1.x branch at first?

Fine, this commit is no problem.
