### ISSUE TITLE
[Feature] support mmyolo SDK inference

### ISSUE THREAD

**Issue by caj-github** [open-mmlab/mmdeploy#1506]
### Motivation

when to support mmyolo SDK inference

**Comment by AllentDan** [comment]
Hi, @caj-github I've add the support of MMYOLO on rv1126 device to SDK in PR #1321. You may try it out.

**Comment by AllentDan** [comment]
#1508

**Comment by lvhan028** [comment]
@caj-github I think mmdeploy SDK has supported mmyolo. You can convert mmyolo model with mmdeploy's `tools/deploy.py` by enabling `--dump-info`. Then you'll get mmyolo's SDK model, the package specified by `--work-dir`.
Regarding how to use SDK to infer a model, please refer to the `demo/python/object_detection.py` or `demo/python/csrc/c/object_detection.cpp`.

**Comment by caj-github** [comment]
![image](https://user-images.githubusercontent.com/55951697/219751644-47d45c7e-c9f5-421d-ab5b-33a64e655310.png)
it can not works, report a error like this
