### ISSUE TITLE
[Feature] Convert onnx to TensorRT by SDK

### ISSUE THREAD

**Issue by step404** [open-mmlab/mmdeploy#1507]
### Motivation

I want to convert the model from onnx to Tensorrt during deployment to make full use of Tensort's optimization of the model.

**Comment by lvhan028** [comment]
I didn't get it. What's "make full use of TensorRT optimization"?
Can't mmdeploy meet your requirements?
You can convert openmmlab model to tensorrt (FP32, FP16, INT8). Plus mmdeploy offers inference SDK.

**Comment by step404** [comment]
> I didn't get it. What's "make full use of TensorRT optimization"? Can't mmdeploy meet your requirements? You can convert openmmlab model to tensorrt (FP32, FP16, INT8). Plus mmdeploy offers inference SDK.

抱歉，没说清楚。
是想要在开发机器上训练模型，并通过mmdeploy转换到onnx，然后在部署机器上通过mmdeploy的SDK将onnx模型转换成TensorRT的engine，然后完成推理。[这样目的是：避免因os、trt版本和gpu型号不同而带来一系列的问题](https://forums.developer.nvidia.com/t/deploying-linux-built-tensorrt-model-on-windows/147963/3)

**Comment by lvhan028** [comment]
SDK hasn't the ability to convert models. It focuses on the model inference after the conversion is done.

You can use `tools/deploy.py` to convert PyTorch model to the TensorRT model. F.Y.I, remember to use `--dump-info` to generate the inference meta info for SDK.

Then you can use SDK to perform the model inference.

**Comment by step404** [comment]
Thanks
