### ISSUE TITLE
 how to add mmflow to mmdeploy codebase?

### ISSUE THREAD

**Issue by pedroHuang123** [open-mmlab/mmdeploy#1516]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

if I want to add mmflow,I don't know how to refer to mmcls to implement the rewrite of backbone network parts.
![image](https://user-images.githubusercontent.com/72126736/206894164-6b6e63a4-c985-447d-96d2-6106c893d516.png)

### Reproduction

mmdeploy

### Environment

```Shell
no
```

**Comment by RunningLeon** [comment]
@pedroHuang123 Hi, if there're some backbones used in mmflow and you want to rewrite them, then you could rewrite these backbones in `mmdeploy/codebase/mmcls/models/backbones` and add the `mmflow` dependecy `Codebase.MMFLOW: ['mmcls']` in [here](https://github.com/open-mmlab/mmdeploy/blob/ae785f42e1524ecf40493c37457ad9b102cbdc5f/mmdeploy/codebase/__init__.py#L9)

BTW, you can refer to some PRs as well: https://github.com/open-mmlab/mmdeploy/pull/428,  https://github.com/open-mmlab/mmdeploy/pull/1183

**Comment by RunningLeon** [comment]
@pedroHuang123 Only when a  function cannot be exported to ONNX, then a rewriting is needed.
