### ISSUE TITLE
请问如何导出指定batch size大小的onnx模型？

### ISSUE THREAD

**Issue by VJoer** [open-mmlab/mmdeploy#154]
我在使用MMDeploy将mmdetection中训练的模型导出为onnx时发现base_static.py中不能设置batch size 大小，导出的onnx模型输入为[1, 3, input_shape]，请问如何设置导出的onnx模型的batch size? 谢谢。

**Comment by RunningLeon** [comment]
> 我在使用MMDeploy将mmdetection中训练的模型导出为onnx时发现base_static.py中不能设置batch size 大小，导出的onnx模型输入为[1, 3, input_shape]，请问如何设置导出的onnx模型的batch size? 谢谢。
@VJoer 
Hi, 如果是只需要batch_size动态可变的话，可以修改`base_dynamic.py` 中的 onnx_config 配置
如
```
onnx_config = dict(
    dynamic_axes={
        'input': {
            0: 'batch'
        },
        'dets': {
            0: 'batch'
        },
        'labels': {
            0: 'batch'
        },
    }, )

```

**Comment by VJoer** [comment]
> > 我在使用MMDeploy将mmdetection中训练的模型导出为onnx时发现base_static.py中不能设置batch size 大小，导出的onnx模型输入为[1, 3, input_shape]，请问如何设置导出的onnx模型的batch size? 谢谢。
> > @VJoer
> > Hi, 如果是只需要batch_size动态可变的话，可以修改`base_dynamic.py` 中的 onnx_config 配置
> > 如
> 
> ```
> onnx_config = dict(
>     dynamic_axes={
>         'input': {
>             0: 'batch'
>         },
>         'dets': {
>             0: 'batch'
>         },
>         'labels': {
>             0: 'batch'
>         },
>     }, )
> ```

谢谢，已经导出成功了

**Comment by RunningLeon** [comment]
@VJoer Hi, you may post your solution here for the benefit of whole community.

**Comment by VJoer** [comment]
> @VJoer Hi, you may post your solution here for the benefit of whole community.

Well, as you said, I changed `onnx_config` in the `configs/mmdet/_base_/base_dynamic.py `, 
`
onnx_config = dict(
    dynamic_axes={
        'input': {
            0: '16',
            2: '640',
            3: '640'
        },
        'dets': {
            0: '16',
            1: '100',
        },
        'labels': {
            0: '16',
            1: '100',
        },
    }, )
`
thank you very much.

**Comment by RunningLeon** [comment]
Thanks. Good to know it works.
