### ISSUE TITLE
sdk demo c 检测错误

### ISSUE THREAD

**Issue by zgq91** [open-mmlab/mmdeploy#157]
你好：
  当我运行sdk demo c的检测 demo时出现以下错误。
环境:onnxruntime1.8.1，检测模型yolov3
执行mmdeploy sdk demo 
错误log:
[2022-02-14 17:24:58.583] [mmdeploy] [info] [model.cpp:97] Register 'DirectoryModel'
[2022-02-14 17:24:58.698] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "image"
  ],
  "name": "mmdetection",
  "output": [
    "det"
  ],
  "params": {
    "model": "end2end.engine"
  },
  "type": "Inference"
}
[2022-02-14 17:24:58.698] [mmdeploy] [error] [model.cpp:51] no ModelImpl can read sdk_model end2end.engine
[2022-02-14 17:24:58.698] [mmdeploy] [error] [model.cpp:22] load model failed. Its file path is 'end2end.engine'
[2022-02-14 17:24:58.698] [mmdeploy] [error] [detector.cpp:58] exception caught: not supported (2) @ /home/gpu/workspace/mmdeploy/csrc/core/model.cpp:52
failed to create detector, code: 6

**Comment by lvhan028** [comment]
Hi, can you share you command when converting yolov3 model to trt model?

**Comment by zgq91** [comment]
@lvhan028  
yolov3结构:
checkpoint_config = dict(interval=50)
log_config = dict(interval=20, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
dataset_type = 'VOCDataset'
data_root = '/data/dataset/worker_dataset/'
img_norm_cfg = dict(mean=[0, 0, 0], std=[255.0, 255.0, 255.0], to_rgb=True)
img_scale = (640, 480)
train_pipeline = [
    dict(type='Mosaic', img_scale=(640, 480), pad_val=114.0),
    dict(type='Expand', mean=[0, 0, 0], to_rgb=True, ratio_range=(1, 2)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.4, 0.5, 0.6, 0.7, 0.8, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=[(640, 480)], keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[0, 0, 0],
        std=[255.0, 255.0, 255.0],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(640, 480),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[0, 0, 0],
                std=[255.0, 255.0, 255.0],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=8,
    train=dict(
        type='MultiImageMixDataset',
        dataset=dict(
            type='VOCDataset',
            classes=['head', 'helmet'],
            min_size=10,
            ann_file='/data/dataset/worker_dataset/ImageSets/Main/train.txt',
            img_prefix='/data/dataset/worker_dataset/',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True)
            ]),
        pipeline=[
            dict(type='Mosaic', img_scale=(640, 480), pad_val=114.0),
            dict(
                type='Expand', mean=[0, 0, 0], to_rgb=True,
                ratio_range=(1, 2)),
            dict(
                type='MinIoURandomCrop',
                min_ious=(0.4, 0.5, 0.6, 0.7, 0.8, 0.9),
                min_crop_size=0.3),
            dict(type='Resize', img_scale=[(640, 480)], keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[0, 0, 0],
                std=[255.0, 255.0, 255.0],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ]),
    val=dict(
        type='VOCDataset',
        classes=['head', 'helmet'],
        ann_file='/data/dataset/worker_dataset/ImageSets/Main/val.txt',
        img_prefix='/data/dataset/worker_dataset/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 480),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[0, 0, 0],
                        std=[255.0, 255.0, 255.0],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='VOCDataset',
        classes=['head', 'helmet'],
        ann_file='/data/dataset/worker_dataset/ImageSets/Main/val.txt',
        img_prefix='/data/dataset/worker_dataset/JPEGImages/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 480),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[0, 0, 0],
                        std=[255.0, 255.0, 255.0],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
model = dict(
    type='YOLOV3',
    init_cfg=None,
    backbone=dict(type='CSPDarknet', deepen_factor=0.3, widen_factor=0.5),
    neck=dict(
        type='PAFPN',
        in_channels=[128, 256, 512],
        out_channels=256,
        num_outs=3),
    bbox_head=dict(
        type='YOLOV3Head',
        num_classes=2,
        in_channels=[256, 256, 256],
        out_channels=[256, 512, 1024],
        anchor_generator=dict(
            type='YOLOAnchorGenerator',
            base_sizes=[[(12, 10), (17, 14), (21, 18)],
                        [(27, 23), (35, 29), (45, 38)],
                        [(60, 52), (85, 74), (134, 119)]],
            strides=[8, 16, 32]),
        bbox_coder=dict(type='YOLOBBoxCoder'),
        featmap_strides=[8, 16, 32],
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_conf=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_xy=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=2.0,
            reduction='sum'),
        loss_wh=dict(type='MSELoss', loss_weight=2.0, reduction='sum')),
    train_cfg=dict(
        assigner=dict(
            type='GridAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0)),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        conf_thr=0.005,
        nms=dict(type='nms', iou_threshold=0.45),
        max_per_img=100))
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=2000,
    warmup_ratio=0.1,
    step=[218, 350])
runner = dict(type='EpochBasedRunner', max_epochs=500)
evaluation = dict(interval=50, metric=['mAP'])
work_dir = './work_dirs/yolov5_cspdarnet'
gpu_ids = range(0, 4)


step1: build MMDeploy SDK with cuda device and TensorRT backend :  
cmake .. \
-DMMDEPLOY_BUILD_SDK=ON \
 -DCMAKE_CXX_COMPILER=g++ \
-Dpplcv_DIR=/home/gpu/thirdDepend/pplcv/lib/cmake/ppl \
-DTENSORRT_DIR=/home/gpu/thirdDepend/tensorrt8.0-11.3 \
 -DCUDNN_DIR=/home/gpu/thirdDepend/cudnn8.2-11.3 \
-DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
 -DMMDEPLOY_TARGET_BACKENDS=trt \
 -DMMDEPLOY_CODEBASES=all
生成lib:
![image](https://user-images.githubusercontent.com/18069515/153973742-9e9222d6-dd24-4bab-8027-4e9a4818b364.png)

step2: 执行 python tool/check_env.py 
![image](https://user-images.githubusercontent.com/18069515/153973895-ce85649f-6ee8-489d-bb1b-8cf31529077f.png)

step3: python tools/deploy.py --deploy_cfg configs/mmdet/detection/detection_tensorrt_static-300x300.py  --model_cfg model_config/mmdet/yolo_cspdarnet.py --checkpoint weights/mmdet/yolo_cspdarnet.pth --img images/000222.jpg --work_dir convert_model --device cuda:0

转换过程log:

2022-02-15 09:19:56,848 - mmdeploy - WARNING - Can not find mmdet.models.dense_heads.FoveaHead.get_bboxes, function rewrite will not be applied
2022-02-15 09:19:56,849 - mmdeploy - WARNING - Can not find mmdet.models.detectors.rpn.RPN.simple_test, function rewrite will not be applied
2022-02-15 09:19:56,849 - mmdeploy - WARNING - Can not find mmdet.models.detectors.two_stage.TwoStageDetector.extract_feat, function rewrite will not be applied
2022-02-15 09:19:56,849 - mmdeploy - WARNING - Can not find mmdet.models.detectors.two_stage.TwoStageDetector.simple_test, function rewrite will not be applied
2022-02-15 09:19:56,850 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.bbox_heads.convfc_bbox_head.ConvFCBBoxHead.forward, function rewrite will not be applied
2022-02-15 09:19:56,850 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.bbox_heads.bbox_head.BBoxHead.forward, function rewrite will not be applied
2022-02-15 09:19:56,850 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.bbox_heads.bbox_head.BBoxHead.get_bboxes, function rewrite will not be applied
2022-02-15 09:19:56,851 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.cascade_roi_head.CascadeRoIHead.simple_test, function rewrite will not be applied
2022-02-15 09:19:56,851 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.mask_heads.fcn_mask_head.FCNMaskHead.get_seg_masks, function rewrite will not be applied
2022-02-15 09:19:56,851 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.SingleRoIExtractor.forward, function rewrite will not be applied
2022-02-15 09:19:56,851 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.standard_roi_head.StandardRoIHead.simple_test, function rewrite will not be applied
2022-02-15 09:19:56,852 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.test_mixins.BBoxTestMixin.simple_test_bboxes, function rewrite will not be applied
2022-02-15 09:19:56,852 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.test_mixins.MaskTestMixin.simple_test_mask, function rewrite will not be applied
2022-02-15 09:19:56,852 - mmdeploy - WARNING - Can not find mmdet.models.roi_heads.roi_extractors.single_level_roi_extractor.SingleRoIExtractor.forward, function rewrite will not be applied
/home/gpu/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py:97: UserWarning: `strip_doc_string' is deprecated and ignored. Will be removed in next PyTorch release. It's combined with `verbose' argument now. 
  warnings.warn("`strip_doc_string' is deprecated and ignored. Will be removed in "
/home/gpu/workspace/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/home/gpu/workspace/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py:25: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  img_shape = [int(val) for val in img_shape]
/home/gpu/workspace/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/base.py:25: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  img_shape = [int(val) for val in img_shape]
/home/gpu/workspace/mmdetection/mmdet/models/dense_heads/yolo_head.py:127: UserWarning: DeprecationWarning: `anchor_generator` is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: `anchor_generator` is deprecated, '
/home/gpu/workspace/mmdetection/mmdet/core/anchor/anchor_generator.py:344: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/home/gpu/workspace/mmdetection/mmdet/core/anchor/anchor_generator.py:380: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  warnings.warn(
/home/gpu/workspace/mmdetection/mmdet/core/bbox/coder/yolo_bbox_coder.py:74: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(-1) == bboxes.size(-1) == 4
/home/gpu/workspace/mmdeploy/mmdeploy/pytorch/functions/topk.py:54: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
/home/gpu/workspace/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:260: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dets, labels = TRTBatchedNMSop.apply(boxes, scores, int(scores.shape[-1]),
/home/gpu/workspace/mmdeploy/mmdeploy/mmcv/ops/nms.py:177: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::TRTBatchedNMS type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
2022-02-15 09:20:01,462 - mmdeploy - INFO - torch2onnx success.
2022-02-15 09:20:01,602 - mmdeploy - INFO - onnx2tensorrt of convert_model/end2end.onnx start.
2022-02-15 09:20:03,258 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/gpu/workspace/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +332, GPU +0, now: CPU 412, GPU 258 (MiB)
[TensorRT] WARNING: onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:390: One or more weights outside the range of INT32 was clamped
[TensorRT] INFO: No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[TensorRT] INFO: Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace: 
[TensorRT] INFO: Successfully created plugin: TRTBatchedNMS
[TensorRT] INFO: [MemUsageSnapshot] Builder begin: CPU 3522 MiB, GPU 1540 MiB
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +326, GPU +166, now: CPU 3850, GPU 1706 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +97, GPU +174, now: CPU 3947, GPU 1880 (MiB)
[TensorRT] WARNING: Detected invalid timing cache, setup a local cache instead
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 2 output network tensors.
[TensorRT] INFO: Total Host Persistent Memory: 110256
[TensorRT] INFO: Total Device Persistent Memory: 38217216
[TensorRT] INFO: Total Scratch Memory: 512000
[TensorRT] INFO: [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 10 MiB, GPU 4 MiB
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 4166, GPU 2114 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 4166, GPU 2124 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 4166, GPU 2108 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 4165, GPU 2090 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] Builder end: CPU 4165 MiB, GPU 2090 MiB
2022-02-15 09:21:04,730 - mmdeploy - INFO - onnx2tensorrt of convert_model/end2end.onnx success.
2022-02-15 09:21:04,731 - mmdeploy - INFO - visualize tensorrt model start.
2022-02-15 09:21:11,733 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/gpu/workspace/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
2022-02-15 09:21:11,733 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /home/gpu/workspace/mmdeploy/build/lib/libmmdeploy_tensorrt_ops.so
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
/home/gpu/workspace/mmdetection/mmdet/datasets/utils.py:65: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2022-02-15 09:21:17,501 - mmdeploy - INFO - visualize tensorrt model success.
2022-02-15 09:21:17,502 - mmdeploy - INFO - visualize pytorch model start.
load checkpoint from local path: weights/mmdet/yolo_cspdarnet.pth
/home/gpu/workspace/mmdetection/mmdet/datasets/utils.py:65: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
/home/gpu/workspace/mmdetection/mmdet/models/dense_heads/yolo_head.py:270: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  flatten_bboxes /= flatten_bboxes.new_tensor(
2022-02-15 09:21:28,718 - mmdeploy - INFO - visualize pytorch model success.
2022-02-15 09:21:28,718 - mmdeploy - INFO - All process success.

最终转换生成的文件:
end2end.engine  end2end.onnx  output_onnxruntime.jpg  output_pytorch.jpg  output_tensorrt.jpg

**Comment by lvhan028** [comment]
python tools/deploy.py --deploy_cfg configs/mmdet/detection/detection_tensorrt_static-300x300.py --model_cfg model_config/mmdet/yolo_cspdarnet.py --checkpoint weights/mmdet/yolo_cspdarnet.pth --img images/000222.jpg --work_dir convert_model --device cuda:0 **--dump-info**

Please add "--dump-info" option when converting the model. This option is used to generate metafiles of SDK model, which are necessary for SDK creating inference handle.

**Comment by zgq91** [comment]
@lvhan028 [2022-02-15 13:08:07.441] [mmdeploy] [info] [model.cpp:97] Register 'DirectoryModel'
[2022-02-15 13:08:07.661] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "image"
  ],
  "name": "mmdetection",
  "output": [
    "det"
  ],
  "params": {
    "model": "/home/gpu/workspace/mmdeploy/convert_model"
  },
  "type": "Inference"
}
[2022-02-15 13:08:07.662] [mmdeploy] [info] [model.cpp:45] DirectoryModel successfully load sdk model /home/gpu/workspace/mmdeploy/convert_model
[2022-02-15 13:08:07.662] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": false,
      "size": [
        480,
        640
      ],
      "type": "Resize"
    },
    {
      "mean": [
        0,
        0,
        0
      ],
      "std": [
        255.0,
        255.0,
        255.0
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 1,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "ori_shape",
        "img_norm_cfg",
        "scale_factor",
        "valid_ratio",
        "ori_filename",
        "flip",
        "flip_direction",
        "filename",
        "pad_shape",
        "img_shape"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-02-15 13:08:07.662] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": false,
      "size": [
        480,
        640
      ],
      "type": "Resize"
    },
    {
      "mean": [
        0,
        0,
        0
      ],
      "std": [
        255.0,
        255.0,
        255.0
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 1,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "ori_shape",
        "img_norm_cfg",
        "scale_factor",
        "valid_ratio",
        "ori_filename",
        "flip",
        "flip_direction",
        "filename",
        "pad_shape",
        "img_shape"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-02-15 13:08:07.662] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "yolov3",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-02-15 13:08:07.662] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "yolov3",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-02-15 13:08:07.662] [mmdeploy] [info] [cuda_device.cpp:84] Default CUDA allocator initialized
[2022-02-15 13:08:08.618] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
[2022-02-15 13:08:08.981] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
[2022-02-15 13:08:08.991] [mmdeploy] [info] [common.h:15] config: {
  "component": "ResizeBBox",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmdet",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {
    "conf_thr": 0.005,
    "max_per_img": 100,
    "min_bbox_size": 0,
    "nms": {
      "iou_threshold": 0.45,
      "type": "nms"
    },
    "nms_pre": 1000,
    "score_thr": 0.05
  },
  "type": "Task"
}
[2022-02-15 13:08:08.991] [mmdeploy] [info] [common.h:15] config: {
  "component": "ResizeBBox",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmdet",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {
    "conf_thr": 0.005,
    "max_per_img": 100,
    "min_bbox_size": 0,
    "nms": {
      "iou_threshold": 0.45,
      "type": "nms"
    },
    "nms_pre": 1000,
    "score_thr": 0.05
  },
  "type": "Task"
}
[ERROR][2022-02-15 13:08:09.006][copymakeborder.cu:351] Assertion failed: dst_stride >= cols * channels * (int)sizeof(float)
[2022-02-15 13:08:09.006] [mmdeploy] [error] [pad_impl.cpp:84] unexpected exception happened
[2022-02-15 13:08:09.006] [mmdeploy] [error] [transform_module.cpp:34] error: not supported (2) @ /home/gpu/workspace/mmdeploy/csrc/preprocess/cuda/pad_impl.cpp:86
[2022-02-15 13:08:09.006] [mmdeploy] [error] [module_adapter.h:34] unhandled exception: not supported (2) @ /home/gpu/workspace/mmdeploy/csrc/preprocess/cuda/pad_impl.cpp:86
[2022-02-15 13:08:09.006] [mmdeploy] [error] [detector.cpp:145] exception caught: unknown (6) @ /home/gpu/workspace/mmdeploy/csrc/experimental/module_adapter.h:35
failed to apply detector, code: 6

**Comment by lvhan028** [comment]
Will fix it in next version
