### ISSUE TITLE
[WIP] Propsal to MMDeploy's build document in zh_cn

### ISSUE THREAD

**Issue by lvhan028** [open-mmlab/mmdeploy#158]
**Motivation**
- 社区反馈 MMDeploy 文档不够详实，可读性不好。
- 随着支持的平台、设备和功能的增多，也需要对当前的文档，尤其是build.md、get_started文档，做出必要的调整。使得文档的结构更清晰，内容更完整，可读性更好
- 编译安装命令整理为脚本，放在代码库中管理

**Modification**

以下为 MMDeploy 安装文档说明书草案。欢迎大家多提宝贵意见

---

# 下载 MMDeploy

```bash
git clone -b master git@github.com:open-mmlab/mmdeploy.git MMDeploy
cd MMDeploy
export MMDEPLOY_DIR=$(pwd)
git submodule update --init --recursive
```
提示:
-  如果由于网络等原因导致拉取仓库子模块失败，可以尝试通过如下指令手动再次安装子模块:

```bash
  git clone git@github.com:NVIDIA/cub.git third_party/cub
  cd third_party/cub
  git checkout c3cceac115
   # 返回至 third_party 目录, 克隆 pybind11
  cd ..
  git clone git@github.com:pybind/pybind11.git pybind11
  cd pybind11
  git checkout 70a58c5
```

# Linux-x86_64 下构建方式

在 linux-x86_64 下，MMDeploy 提供 3 种构建包的方式，分别是Dockerfile方式、源码安装、和直接使用预编译包。

## 1. Dockerfile 方式（推荐）
MMDeploy 分别提供了 cpu 和 cuda 平台下的 dockerfile。其中，ONNXRuntime、ncnn 和 OpenVINO 等推理引擎安装在 cpu docker镜像中，而 TensorRT 将会安装在 cuda docker镜像中。
用户可以根据文档 [使用docker构建MMDeploy](https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/tutorials/how_to_use_docker.md) 的详细步骤，构建 MMDeploy

### 安装编译工具链

<table>
<tr>
<th> 名称 </th> <th> 版本 </th> <th> 安装脚本 </th>
</tr>
<tr>
  <td align="center"> gcc </td>
  <td align="center"> >= 7 </td> 
  <td align="center">

  ```bash
  bash build_scripts/linux-x86_64/gcc.sh
  ```

  </td>
</tr>
<tr>
  <td align="center"> cmake </td>
  <td align="center"> >= 3.14.0 </td> 
  <td align="center">
    
  ```bash
  bash build_scripts/linux-x86_64/cmake.sh
  ```

  </td>
</tr>
</table>

#### MMDeploy Converter 专用依赖

<table>
<thead>
  <tr>
    <th>依赖项名称</th>
    <th>安装方法</th>
  </tr>
</thead>
<tbody>
<tr>
  <td>conda</td>
  <td>
  通过 conda 创建并激活 Python 环境

  ```bash
  conda create -n mmdeploy python=3.7 -y
  conda activate mmdeploy
  ```
  </td>
</tr>
<tr>
  <td>pytorch</td>
  <td>
  要求版本是 torch>=1.8.0, 可查看<a href="https://pytorch.org/" target="_blank" rel="noopener noreferrer">官网</a>获取更详细的安装教程。

  ```bash
  # CUDA 11.1
  conda install pytorch==1.8.0 torchvision==0.9.0 cudatoolkit=11.1 -c pytorch -c conda-forge
  ``` 

  </td>
 </tr>
<tr>
  <td>mmcv-full</td>
  <td>
  更多安装方式可查看<a href="https://github.com/open-mmlab/mmcv#installation">教程</a>

  ```bash
  export cu_version=cu111 # cuda 11.1
  export torch_version=torch1.8.0
  pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/${cu_version}/${torch_version}/index.html
  ```

  </td>
</tr>
<tr>
  <td>OpenMMLab Codebase</td>
  <td>
   比如安装mmdetection

  ```bash
  pip install mmdet==2.19.0
  ```

  </td>
</tr>
</tbody>
</table>

#### MMDeploy SDK 专用依赖
执行下述安装脚本，默认把依赖安装到 mmdeploy/.deps下
<table>
<thead>
  <tr>
    <th>依赖项名称</th>
    <th>安装方法</th>
  </tr>
</thead>
<tbody>
<tr>
  <td>spdlog</td>
  <td>
  
  ```bash
  # 在该脚本中，1）下载依赖包v1.9.2；2）编译&安装；3）设置环境变量SPDLOG_DIR
  bash build_scripts/linux-x86_64/spdlog.sh <destination_path>
  ```

  </td>
</tr>
<tr>
  <td>OpenCV</td>
    <td>
  
  ```bash
  # 在该脚本中，1）下载依赖包v4,5.5；2）编译&安装；3）设置环境变量OPENCV_DIR
  bash build_scripts/linux-x86_64/opencv.sh <destination_path>
  ```

  </td>
</tr>
<tr>
  <td>ppl.cv</td>
    <td>
    **当推理平台为 cuda 时，需要安装该依赖项**

  ```bash
  # 在该脚本中，1）下载依赖包v0.6.1；2）编译&安装；3）设置环境变量PPLCV_DIR
  bash build_scripts/linux-x86_64/ppl.cv.sh <destination_path>
  ```

  </td>
</tr>
</tbody>
</table>

#### MMDeploy 推理引擎依赖

MMDeploy Converter & SDK 共享推理引擎。用户可以参考下表，选择并安装感兴趣的推理引擎

<table>
<thead>
  <tr>
    <th>推理引擎</th>
    <th>依赖项名称</th>
    <th>安装方法</th>
  </tr>
</thead>
<tbody>
<tr>
  <td rowspan="2">TensorRT</td>
  <td>TensorRT</td>
  <td>1. 从 NVIDIA 官网下载二进制包<br>2. 执行安装脚本<br>

  ```bash
   # 1) 解压包; 2) 安装whl文件; 3) 写环境变量 TENSORRT_DIR
   bash build_scripts/tensorrt.sh ${package_path} ${destination_path}
  ```

  </td>
</tr>
<tr>
  <td>cudnn</td>
  <td>1. 从 NVIDIA 官网下载二进制包<br>2. 执行安装脚本<br>

  ```bash
  # 1) 解压包；2）安装whl文件；3）写环境变量CUDNN_DIR
  bash build_scripts/cudnn.sh ${package_path} ${destination_path}
  ```

  </td>
</tr>
<tr>
  <td>pplnn</td>
  <td>ppl.nn</td>
  <td>

  ```bash
  # 1）下载pplnn；2）编译&安装；3）写环境变量PPLNN_DIR
  bash build_scripts/pplnn.sh
  ```

  </td>
</tr>
<tr>
  <td>ONNXRuntime</td>
  <td>ONNXRuntime</td>
  <td>
  
  ```bash
    # 1）下载onnxruntime；2）安装；3）写环境变量ONNXRUNTIME_DIR
  bash build_scripts/onnxruntime.sh
  ```
  
  </td>
</tr>
<tr>
  <td>OpenVINO</td>
  <td>OpenVINO</td>
  <td>

  ```bash
  bash build_scripts/openvino.sh
  ```
  
  </td>
</tr>
<tr>
  <td>ncnn</td>
  <td>ncnn</td>
  <td>
  
  ```bash
    # 1）下载ncnn；2）编译&安装；3）写环境变量NCNN_DIR
  bash build_scripts/ncnn.sh
  ```

  </td>
</tr>
</tbody>
</table>

#### 编译安装 Converter

**1. 编译自定义算子**

```bash
bash build_scripts/linux_x86-64/build_custom_ops.sh -DMMDEPLOY_TARGET_BACKENDS=ort 
```

- TensorRT 自定义算子

```bash
bash build_scripts/linux_x86-64/build_custom_ops.sh -DMMDEPLOY_TARGET_BACKENDS=trt
```

- ncnn 自定义算子

```bash
bash build_scripts/linux_x86-64/build_custom_ops.sh -DMMDEPLOY_TARGET_BACKENDS=ncnn
```

**2. 安装**
```bash
cd ${MMDEPLOY_DIR} # 切换至项目根目录
pip install -e .
```

#### 编译 SDK

**1. 设置目标设备**

  cpu 是 SDK 目标设备的默认选项。你也可以通过`MMDEPLOY_TARGET_DEVICES`传入其他设备名称。SDK 支持 "cpu" 和 "cuda" 两种设备。当有多个设备时，设备名称之间使用分号隔开。
  比如，`-DMMDEPLOY_TARGET_DEVICES="cpu;cuda"`。
  如果你的开发环境中有多个cuda版本，则需要通过`-DCUDA_TOOLKIT_ROOT_DIR=/path/of/cuda`来明确使用的版本。

**2. 设置推理后端**

  **默认情况下，SDK不设置任何后端**, 因为它与应用场景高度相关。你可以通过设置`MMDEPLOY_TARGET_BACKENDS`激活感兴趣的推理后端。已支持的推理后端有‘ort’, 'trt', 'ncnn', 'pplnn' 和 'openvino'
  当选择多个时， 中间使用分号隔开。比如，`-DMMDEPLOY_TARGET_BACKENDS="trt;ort;pplnn;ncnn;openvino"`

**3. 设置后处理组件**

  需要通过`MMDEPLOY_CODEBASES`设置SDK后处理组件，才能加载OpenMMLab算法仓库的后处理功能。已支持的算法仓库有'mmcls'，'mmdet'，'mmedit'，'mmseg'和'mmocr'。
  如果选择多个codebase，中间使用分号隔开。比如，`-DMMDEPLOY_CODEBASES=mmcls;mmdet`。也可以通过`-DMMDEPLOY_CODEBASES=all`方式，加载所有codebase。

- 汇总以上
``` bash
# 使用cpu设备和ONNXRuntime推理
bash build_scripts/linux-x86_64/mmdeploy_sdk.sh -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=ort -DMMDEPLOY_CODEBASES=all

# 使用cuda设备和TensorRT推理
bash build_scripts/linux-x86_64/mmdeploy_sdk.sh -DMMDEPLOY_TARGET_DEVICES=cuda -DMMDEPLOY_TARGET_BACKENDS=trt -DMMDEPLOY_CODEBASES=all

```

## 3. 预编译包
提供 linux-x86_64/cpu/mmdeploy_onnxruntime.tar.gz，linux-x86_64/cuda/mmdeploy_cu111_trt8.2.3.tar.gz

# NVIDIA Jetson 下构建方式

### 编译安装 MMDeploy

# Windows 下构建方式

## 2. 预编译包

# Android 下构建方式

**Comment by RunningLeon** [comment]
文档开头可以加个目录，方便用户快速索引到目标平台的构建教程。

**Comment by grimoire** [comment]
文档内容无异议；考虑到文档中提到了build_scripts，针对这一点存在一些问题：
1. build_scripts中是否包含非mmdeploy内容的安装（比如推理引擎）
2. 是否考虑一些交互式的安装方式（交互式脚本，窗口程序）
3. 是否应该针对特定平台定制一些特殊的使用策略（比如jetson平台下仅进行onnx2tensorrt，这部分与pytorch解偶）

**Comment by lvhan028** [comment]
> 文档开头可以加个目录，方便用户快速索引到目标平台的构建教程。

好主意

**Comment by lvhan028** [comment]
> 文档内容无异议；考虑到文档中提到了build_scripts，针对这一点存在一些问题：
> 
> 1. build_scripts中是否包含非mmdeploy内容的安装（比如推理引擎）
> 2. 是否考虑一些交互式的安装方式（交互式脚本，窗口程序）
> 3. 是否应该针对特定平台定制一些特殊的使用策略（比如jetson平台下仅进行onnx2tensorrt，这部分与pytorch解偶）。在这种情况下，安装过程可以大幅简化

1. 打算包含非mmdeploy内容的安装，比如提供tensorrt.sh，用来解压下载包，安装其中的whl文件，以及把TENSORRT_DIR设置到环境变量中
2. 可以考虑。尽可能对用户友好。
3. 同意，是需要针对平台定制化的。

**Comment by uniyushu** [comment]
1.  能说下NVIDIA Jetson部署计划么。
2. mmlab其他代码库啥时候支持啊，比如[mmtracking](https://github.com/open-mmlab/mmtracking)。

**Comment by tehkillerbee** [comment]
I am not sure if this issue is only related to the CN documentation but in case help is needed with the EN documentation, I will be glad to help.

**Comment by haofanwang** [comment]
请问build_scripts/linux-x86_64/mmdeploy_sdk.sh 和linux-x86_64/cuda/mmdeploy_cu111_trt8.2.3.tar.gz在哪里？

**Comment by lvhan028** [comment]
> 请问build_scripts/linux-x86_64/mmdeploy_sdk.sh 和linux-x86_64/cuda/mmdeploy_cu111_trt8.2.3.tar.gz在哪里？

脚本其实还没有开发。有兴趣的话，欢迎一起合作开发。

这里主要是想调研用户是否觉得这份文档内容符合自己的预期。如果符合预期的话，相关的文档、脚本完善工作会尽快开展

**Comment by zgq91** [comment]
新的编译安装说明文档什么时候能更新

**Comment by lvhan028** [comment]
> 新的编译安装说明文档什么时候能更新

2.25 之前

**Comment by zgq91** [comment]
> > 新的编译安装说明文档什么时候能更新
> 
> 2.25 之前。对上面的文档架构有什么建议不？

能否添加csrc推荐框架说明，刚开始使用demo的sdk出错的都不知道在哪里找，刚开始看源码封装的有点深看不知道在哪里找出错；

**Comment by haofanwang** [comment]
建议加上tensorRT版本号，以及FQA里可以补充一些容易出现的安装/使用问题

**Comment by lvhan028** [comment]
> I am not sure if this issue is only related to the CN documentation but in case help is needed with the EN documentation, I will be glad to help.
Hi, @tehkillerbee. MMDeploy has supported windows platform. I've made a build document in Chinese, referring to `docs/zh_cn/build/windows.md`. Could you help update its English version in `docs/en/build/windows.md`.

**Comment by tehkillerbee** [comment]
@lvhan028 Sure, I will take a look ASAP

**Comment by tehkillerbee** [comment]
Sorry @lvhan028, I had forgotten about this. I will make a PR with an english build document based on `docs/zh_cn/build/windows.md`

**Comment by lvhan028** [comment]
merged in v0.4.0
