### ISSUE TITLE
[Feature] yolox convert to onnx, but the inference time cost increase

### ISSUE THREAD

**Issue by VincentMy** [open-mmlab/mmdeploy#1616]
### Motivation

i conver yolox to onnx with detection_onnxruntime_dynamic.py, but when inference image with onnxruntime, no speed increase.
Besides 
`ort.InferenceSession(model_path, providers=['CUDAExecutionProvider'])` cost 2.4s
 `ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])` cost0.18s instead. could anyone can explain it?

![image](https://user-images.githubusercontent.com/47235130/210753995-f4221d51-06ee-4a91-b299-bd721bba11f0.png)
![image](https://user-images.githubusercontent.com/47235130/210754033-39d9e120-179e-4dda-877d-81cdfe666040.png)

### Related resources

inference code

`import onnx
import onnxruntime as ort
import numpy as np
import cv2
import time

model_path = 'weights/end2end.onnx'

onnx_model = onnx.load(model_path)
onnx.checker.check_model(onnx_model)

image = cv2.imread('images/demo.jpg').astype('float32')
image = cv2.resize(image, (640, 640), interpolation=cv2.INTER_AREA).reshape(3, 640, 640)
image = np.expand_dims(image, axis=0)

t = time.time()
ort_sess = ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])
tcost = time.time() - t
print(f"tcost = {tcost}")

outputs = ort_sess.run(None, {'input': image})
print('batch size: {}'.format(len(outputs[0])))
print('Num of detection: {}'.format(len(outputs[0][0])))

for bbox, label in zip(outputs[0][0], outputs[1][0]):
      print('label: {}, bbox: {}'.format(label, bbox))`

### Additional context
package version
torch == 1.10.2
onnxruntime-gpu == 1.12.1
mmcv-full == 1.7.0
mmdeploy == 0.12.0
_No response_

**Comment by lzhangzz** [comment]
You are timing the creation of a `InferenceSession` instead of `InferenceSession.run`.

**Comment by VincentMy** [comment]
thanks for your reply，but when i  correct the error, the result still incorrect

here the code:
`import onnx
import onnxruntime as ort
import numpy as np
import cv2
import time

model_path = 'weights/end2end.onnx'

onnx_model = onnx.load(model_path)
onnx.checker.check_model(onnx_model)

image = cv2.imread('images/demo.jpg').astype('float32')
image = cv2.resize(image, (640, 640), interpolation=cv2.INTER_AREA).reshape(3, 640, 640)
image = np.expand_dims(image, axis=0)

ort_sess = ort.InferenceSession(model_path, providers=['CUDAExecutionProvider'])
t = time.time()
outputs = ort_sess.run(None, {'input': image})
tcost = time.time() - t
print(f"tcost = {tcost}")
print('batch size: {}'.format(len(outputs[0])))
print('Num of detection: {}'.format(len(outputs[0][0])))
for bbox, label in zip(outputs[0][0], outputs[1][0]):
    print('label: {}, bbox: {}'.format(label, bbox))`

CUDAExecutionProvider cost 0.95s
![image](https://user-images.githubusercontent.com/47235130/211228223-235dbf77-1d6d-4aa0-b311-9322d8560883.png)

CPUExecutionProvider cost 0.15s
![image](https://user-images.githubusercontent.com/47235130/211228259-986fd50c-7de0-4695-910d-b3224def4f0d.png)

**Comment by VincentMy** [comment]
> You are timing the creation of a `InferenceSession` instead of `InferenceSession.run`.

thanks for your reply，but when i correct the error, the result still incorrect

here the code:
`import onnx
import onnxruntime as ort
import numpy as np
import cv2
import time

model_path = 'weights/end2end.onnx'

onnx_model = onnx.load(model_path)
onnx.checker.check_model(onnx_model)

image = cv2.imread('images/demo.jpg').astype('float32')
image = cv2.resize(image, (640, 640), interpolation=cv2.INTER_AREA).reshape(3, 640, 640)
image = np.expand_dims(image, axis=0)

ort_sess = ort.InferenceSession(model_path, providers=['CUDAExecutionProvider'])
t = time.time()
outputs = ort_sess.run(None, {'input': image})
tcost = time.time() - t
print(f"tcost = {tcost}")
print('batch size: {}'.format(len(outputs[0])))
print('Num of detection: {}'.format(len(outputs[0][0])))
for bbox, label in zip(outputs[0][0], outputs[1][0]):
print('label: {}, bbox: {}'.format(label, bbox))`

CUDAExecutionProvider cost 0.95s
![image](https://user-images.githubusercontent.com/47235130/211228319-e227e2d6-58e9-402e-b7b8-533319cb4280.png)

CPUExecutionProvider cost 0.15s
![image](https://user-images.githubusercontent.com/47235130/211228329-889f551c-259e-4062-8b84-39e3df407f1b.png)

**Comment by hanrui1sensetime** [comment]
GPU speed test needs warm up, so you can calculate the time in 1000 loops, then the calculation on gpu is faster than cpu.
