### ISSUE TITLE
[Bug] After modifying the trunk and neck in the export of mmyolo, exporting onnx failed

### ISSUE THREAD

**Issue by chen-del** [open-mmlab/mmdeploy#1654]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

After modifying the trunk and neck in the export of mmyolo, I want to export onnxruntime but an error occurs?

### Reproduction

1. The tools/deploy.py export command in the mmdloy directory is used，脚本为
export MMDEPLOY_DIR=/home/dell/bag-torch/darkpull/mmlab/mmdeploy
export PATH_TO_CHECKPOINTS=/home/dell/bag-torch/darkpull/mmlab/mmyolo/model/yolov5_moblienetv3.pth

python3 ${MMDEPLOY_DIR}/tools/deploy.py \
       configs/deploy/detection_onnxruntime_static.py \
       configs/deploy/model/yolov5_s-static.py \
       ${PATH_TO_CHECKPOINTS} \
       ./demo/demo.jpg \
       --work-dir  \
       --device cpu \
       --show
3. Just migrate the bankbone of mmcls to mmyolo

### Environment

```Shell
01/13 20:54:24 - mmengine - INFO - 

01/13 20:54:24 - mmengine - INFO - **********Environmental information**********
01/13 20:54:25 - mmengine - INFO - sys.platform: linux
01/13 20:54:25 - mmengine - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
01/13 20:54:25 - mmengine - INFO - CUDA available: True
01/13 20:54:25 - mmengine - INFO - numpy_random_seed: 2147483648
01/13 20:54:25 - mmengine - INFO - GPU 0,1: NVIDIA GeForce RTX 3090
01/13 20:54:25 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.4
01/13 20:54:25 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.100
01/13 20:54:25 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
01/13 20:54:25 - mmengine - INFO - PyTorch: 1.10.0+cu111
01/13 20:54:25 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

01/13 20:54:25 - mmengine - INFO - TorchVision: 0.11.0+cu111
01/13 20:54:25 - mmengine - INFO - OpenCV: 4.6.0
01/13 20:54:25 - mmengine - INFO - MMEngine: 0.4.0
01/13 20:54:25 - mmengine - INFO - MMCV: 2.0.0rc2
01/13 20:54:25 - mmengine - INFO - MMCV Compiler: GCC 7.3
01/13 20:54:25 - mmengine - INFO - MMCV CUDA Compiler: 11.1
01/13 20:54:25 - mmengine - INFO - MMDeploy: 1.0.0rc1+89580eb
01/13 20:54:25 - mmengine - INFO - 

01/13 20:54:25 - mmengine - INFO - **********Backend information**********
01/13 20:54:25 - mmengine - INFO - tensorrt:    None
01/13 20:54:25 - mmengine - INFO - ONNXRuntime: 1.12.0
01/13 20:54:25 - mmengine - INFO - ONNXRuntime-gpu:     None
01/13 20:54:25 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
01/13 20:54:25 - mmengine - INFO - pplnn:       None
01/13 20:54:25 - mmengine - INFO - ncnn:        None
01/13 20:54:25 - mmengine - INFO - snpe:        None
01/13 20:54:25 - mmengine - INFO - openvino:    None
01/13 20:54:25 - mmengine - INFO - torchscript: 1.10.0+cu111
01/13 20:54:25 - mmengine - INFO - torchscript custom ops:      NotAvailable
01/13 20:54:25 - mmengine - INFO - rknn-toolkit:        None
01/13 20:54:25 - mmengine - INFO - rknn-toolkit2:       None
01/13 20:54:25 - mmengine - INFO - ascend:      None
01/13 20:54:25 - mmengine - INFO - coreml:      None
01/13 20:54:25 - mmengine - INFO - tvm: None
01/13 20:54:25 - mmengine - INFO - 

01/13 20:54:25 - mmengine - INFO - **********Codebase information**********
01/13 20:54:25 - mmengine - INFO - mmdet:       3.0.0rc3
01/13 20:54:25 - mmengine - INFO - mmseg:       None
01/13 20:54:25 - mmengine - INFO - mmcls:       1.0.0rc5
01/13 20:54:25 - mmengine - INFO - mmocr:       None
01/13 20:54:25 - mmengine - INFO - mmedit:      None
01/13 20:54:25 - mmengine - INFO - mmdet3d:     None
01/13 20:54:25 - mmengine - INFO - mmpose:      1.0.0rc0
01/13 20:54:25 - mmengine - INFO - mmrotate:    None
01/13 20:54:25 - mmengine - INFO - mmaction:    None
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/dell/bag-torch/darkpull/mmlab/mmdeploy/tools/deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
  File "/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/mmdeploy/__init__.py", line 4, in <module>
    from mmdeploy.utils import get_root_logger
  File "/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/mmdeploy/utils/__init__.py", line 2, in <module>
    from .config_utils import (cfg_apply_marks, get_backend, get_backend_config,
  File "/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/mmdeploy/utils/config_utils.py", line 11, in <module>
    def load_config(*args) -> List[mmcv.Config]:
AttributeError: module 'mmcv' has no attribute 'Config'
```

**Comment by Typiqally** [comment]
Seems like you don't have the `mmcv` or `mmcv-full` package installed. Try installing using open MIM: `mim install mmcv-full`. You can install open MIM: `pip install openmim`.

**Comment by vansin** [comment]
where is the mmdeploy version?

**Comment by Typiqally** [comment]
Please try the latest versions of `mmcv` and `mmcv-full` which is 1.7.1.

**Comment by vansin** [comment]
> Please try the latest versions of `mmcv` and `mmcv-full` which is 1.7.1.

mmdeploy  1.x is based on mmcv 2.x

**Comment by Typiqally** [comment]
I'm not familiar with release candidate and or unreleased versions of MMDeploy, and I would personally refrain from using them for now since they may contain issues such as this. Is there any reason you need the latest unreleased version?

**Comment by chen-del** [comment]
mmdeploy used mim install. mmdeploy was installed, and when I checked it, I found that it was version 0.2.0 and it seemed, there seemed to be a problem, and mmcv-full I didn't install it, I used mmcv=2.0roc series




---Original---
From: ***@***.***&gt;
Date: Fri, Jan 13, 2023 21:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdeploy] [Bug]  (Issue #1654)




 
where is the mmdeploy version?

**Comment by chen-del** [comment]
@vansin @Typiqally Another problem occurred after using mim install mmcv-full, the error is as follows:


mportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/mmdeploy/apis/__init__.py)

**Comment by vansin** [comment]
if you use the mmdeploy 1.x , you must use mmcv 2.x. the mmdeploy may have some bug, next Monday the mmdeploy core developer will try to fix the bug

**Comment by vansin** [comment]
> @vansin @Typiqally Another problem occurred after using mim install mmcv-full, the error is as follows:
> 
> mportError: cannot import name 'create_calib_input_data' from 'mmdeploy.apis' (/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/mmdeploy/apis/**init**.py)


if you use the mmdeploy 1.x , you must use mmcv 2.x. the mmdeploy may have some bug, next Monday the mmdeploy core developer will try to fix the bug

**Comment by chen-del** [comment]
@vansin So if I want to export onnx in mmyolo, is there any other way? Change to dev-0.3 branch and so on

**Comment by vansin** [comment]
> 

https://github.com/open-mmlab/mmyolo/blob/main/projects/easydeploy/docs/model_convert.md

**Comment by vansin** [comment]
> @vansin So if I want to export onnx in mmyolo, is there any other way? Change to dev-0.3 branch and so on

you can try to use easy deploy to export onnx in mmyolo

https://github.com/open-mmlab/mmyolo/blob/main/projects/easydeploy/docs/model_convert.md

**Comment by chen-del** [comment]
@vansin thank you very much!

**Comment by hanrui1sensetime** [comment]
Hi, @chen-del: has this issue solved? If you still have problems, contact me.

**Comment by chen-del** [comment]
@hanrui1sensetime ，Now the export does not seem to have this problem. I built and compiled the source code in the linux system once, but this problem still exists in the docker.

**Comment by hanrui1sensetime** [comment]
> @hanrui1sensetime ，Now the export does not seem to have this problem. I built and compiled the source code in the linux system once, but this problem still exists in the docker.

It is about your environment of docker:
Focus on the error log:
```
from .config_utils import (cfg_apply_marks, get_backend, get_backend_config,
  File "/home/dell/anaconda3/envs/mmp/lib/python3.8/site-packages/mmdeploy/utils/config_utils.py", line 11, in <module>
    def load_config(*args) -> List[mmcv.Config]:
AttributeError: module 'mmcv' has no attribute 'Config'
```
and your mmdeploy version:
```
mmengine - INFO - MMDeploy: 1.0.0rc1+89580eb
```
In [line 11](https://github.com/open-mmlab/mmdeploy/blob/89580eb4967b57a4b7b5d0ab867d150144a27576/mmdeploy/utils/config_utils.py#L11) is not the code which is `def load_config(*args) -> List[mmcv.Config]:`

So, it is because the mmdeploy from `tools/check_env.py` and `anaconda3/envs/mmp/lib/python3.8/site-packages` are different.
Please check it carefully.
