### ISSUE TITLE
[Bug] "mmcv has no attribute 'Config'" when running deploy.py

### ISSUE THREAD

**Issue by mattiasbax** [open-mmlab/mmdeploy#1655]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When trying to export models (tried both RTMDet and Yolov3) using deploy.py script I just get an error return that mmcv has no attribute 'Config'.

I have followed the following guide which installs mmengine, mmcv and mmdet: https://mmdetection.readthedocs.io/en/3.x/get_started.html

I tried both from source and using mim, with the same result.

### Reproduction

python ./tools/deploy.py configs/mmdet/detection/detection_onnxruntime_static.py ../mmdetection/checkpoints/yolov3_mobilenetv2_8xb24-320-300e_coco.py ../mmdetection/checkpoints/yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth demo/resources/det.jpg --device cuda

### Environment

```Shell
Unfortunately, check_env is not working and only return following error:

python tools/check_env.py
Traceback (most recent call last):
  File "C:\Users\mattias.backstrom\git\mmdet_demo\mmdeploy\tools\check_env.py", line 4, in <module>
    from mmcv.utils import get_git_hash
ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (c:\users\mattias.backstrom\git\mmdet_demo\mmcv\mmcv\utils\__init__.py)
(mmlab)
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "C:\Users\mattias.backstrom\git\mmdet_demo\mmdeploy\tools\deploy.py", line 12, in <module>
    from mmdeploy.apis import (create_calib_input_data, extract_model,
  File "c:\users\mattias.backstrom\git\mmdet_demo\mmdeploy\mmdeploy\__init__.py", line 4, in <module>
    from mmdeploy.utils import get_root_logger
  File "c:\users\mattias.backstrom\git\mmdet_demo\mmdeploy\mmdeploy\utils\__init__.py", line 18, in <module>
    from .config_utils import (cfg_apply_marks, get_backend,
  File "c:\users\mattias.backstrom\git\mmdet_demo\mmdeploy\mmdeploy\utils\config_utils.py", line 10, in <module>
    def load_config(*args) -> List[mmcv.Config]:
AttributeError: module 'mmcv' has no attribute 'Config'
(mmlab)
```

**Comment by grimoire** [comment]
You need https://github.com/open-mmlab/mmdeploy/tree/dev-1.x branch to export model in mmdetection 3.x

**Comment by mattiasbax** [comment]
> You need https://github.com/open-mmlab/mmdeploy/tree/dev-1.x branch to export model in mmdetection 3.x

Ok, so the steps to set everything up with correct versioning would be (for a windows machine):

conda create --name openmmlab
conda activate openmmlab
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0rc1"
mim install "mmdet>=3.0.0rc0" (or from sources)

and then to install mmdeploy. would the following be sufficient if i'm just interested in converting to .onnx format:
git clone -b dev-1.x https://github.com/open-mmlab/mmdeploy.git
cd mmdeploy
pip install -e .

or would I need to follow this guide?
https://github.com/open-mmlab/mmdeploy/blob/1.x/docs/en/02-how-to-run/prebuilt_package_windows.md


Am I missing any other important step?

Thanks!

**Comment by grimoire** [comment]
Yes, that should be ok if you just need to export onnx.

**Comment by mattiasbax** [comment]
> Yes, that should be ok if you just need to export onnx.

I just wanted to let you know that following the above steps solved my issue! 
I could now export both the yolo and RTMDet models to onnx successfully and the returned example output from the onnx model looks good.

Thank you!
