### ISSUE TITLE
[Bug] ssd report a error: IndexError: max(): Expected reduction dim 2 to have non-zero size.

### ISSUE THREAD

**Issue by caj-github** [open-mmlab/mmdeploy#1699]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://user-images.githubusercontent.com/55951697/216222367-c4027dd3-95ea-45cd-bebf-e9dbea731788.png)
when my dataset only one classes，report a error like this, muiltple classes works

### Reproduction

ssd512

### Environment

```Shell
win10 mmdeploy1.0.0rc1
```

**Comment by hanrui1sensetime** [comment]
This is because when `self.use_sigmoid_cls` is False, the classes must have the background class. So only one class case may not use `self.use_sigmoid_cls=False` config.

**Comment by 20171758** [comment]
I am facing the same problem.
