### ISSUE TITLE
problem for install

### ISSUE THREAD

**Issue by Aaronwd** [open-mmlab/mmdeploy#17]
(openmmlab) root@Ailab:~/nlp/mmdeploy/build# make -j$(nproc)
Consolidate compiler generated dependencies of target mmdeploy_onnxruntime_ops_obj
[ 16%] Building CXX object csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/grid_sample/grid_sample.cpp.o
[ 33%] Building CXX object csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/roi_align/roi_align.cpp.o
[ 50%] Building CXX object csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/modulated_deform_conv/modulated_deform_conv.cpp.o
In file included from /root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/grid_sample/grid_sample.cpp:9:0:
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:34:25: error: the value of ‘mmdeploy::__domain_mmdeployGridSampleOp’ is not usable in a constant expression
   static OrtOpsRegistry<__domain_##domain##name, name> ort_ops_registry_##domain##name {}
                         ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/grid_sample/grid_sample.cpp:293:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmdeploy, GridSampleOp);
 ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:33:15: note: ‘mmdeploy::__domain_mmdeployGridSampleOp’ was not declared ‘constexpr’
   static char __domain_##domain##name[] = #domain; \
               ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/grid_sample/grid_sample.cpp:293:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmdeploy, GridSampleOp);
 ^
In file included from /root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp:7:0:
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:34:25: error: the value of ‘mmdeploy::__domain_mmdeployMMCVModulatedDeformConvOp’ is not usable in a constant expression
   static OrtOpsRegistry<__domain_##domain##name, name> ort_ops_registry_##domain##name {}
                         ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp:269:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmdeploy, MMCVModulatedDeformConvOp);
 ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:33:15: note: ‘mmdeploy::__domain_mmdeployMMCVModulatedDeformConvOp’ was not declared ‘constexpr’
   static char __domain_##domain##name[] = #domain; \
               ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp:269:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmdeploy, MMCVModulatedDeformConvOp);
 ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:34:25: error: the value of ‘mmdeploy::__domain_mmcvMMCVModulatedDeformConvOp’ is not usable in a constant expression
   static OrtOpsRegistry<__domain_##domain##name, name> ort_ops_registry_##domain##name {}
                         ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp:270:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmcv, MMCVModulatedDeformConvOp);
 ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:33:15: note: ‘mmdeploy::__domain_mmcvMMCVModulatedDeformConvOp’ was not declared ‘constexpr’
   static char __domain_##domain##name[] = #domain; \
               ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp:270:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmcv, MMCVModulatedDeformConvOp);
 ^
In file included from /root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/roi_align/roi_align.cpp:6:0:
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:34:25: error: the value of ‘mmdeploy::__domain_mmdeployMMCVRoiAlignCustomOp’ is not usable in a constant expression
   static OrtOpsRegistry<__domain_##domain##name, name> ort_ops_registry_##domain##name {}
                         ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/roi_align/roi_align.cpp:254:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmdeploy, MMCVRoiAlignCustomOp);
 ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/common/ort_utils.h:33:15: note: ‘mmdeploy::__domain_mmdeployMMCVRoiAlignCustomOp’ was not declared ‘constexpr’
   static char __domain_##domain##name[] = #domain; \
               ^
/root/nlp/mmdeploy/csrc/backend_ops/onnxruntime/roi_align/roi_align.cpp:254:1: note: in expansion of macro ‘REGISTER_ONNXRUNTIME_OPS’
 REGISTER_ONNXRUNTIME_OPS(mmdeploy, MMCVRoiAlignCustomOp);
 ^
csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/build.make:89: recipe for target 'csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/grid_sample/grid_sample.cpp.o' failed
make[2]: *** [csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/grid_sample/grid_sample.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/build.make:103: recipe for target 'csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/modulated_deform_conv/modulated_deform_conv.cpp.o' failed
make[2]: *** [csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/modulated_deform_conv/modulated_deform_conv.cpp.o] Error 1
csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/build.make:131: recipe for target 'csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/roi_align/roi_align.cpp.o' failed
make[2]: *** [csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/roi_align/roi_align.cpp.o] Error 1
CMakeFiles/Makefile2:129: recipe for target 'csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/all' failed
make[1]: *** [csrc/backend_ops/onnxruntime/CMakeFiles/mmdeploy_onnxruntime_ops_obj.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hanrui1sensetime** [comment]
Hi, first welcome to use our project!
And could you provide your command history before `make -j$(nproc)`?
Also, if you could provide the result after executing `python tools/check_env.py` is better.

**Comment by shenzhangzhou** [comment]
> Hi, first welcome to use our project! And could you provide your command history before `make -j$(nproc)`? Also, if you could provide the result after executing `python tools/check_env.py` is better.

Hi, I have the same problem, and the result after executing python tools/check_env.py is 
INFO:root:sys.platform: linux
INFO:root:Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
INFO:root:CUDA available: True
INFO:root:GPU 0,1,2,3: Tesla P40
INFO:root:CUDA_HOME: /usr/local/cuda-11.1
INFO:root:NVCC: Build cuda_11.1.TC455_06.29069683_0
INFO:root:GCC: gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
INFO:root:PyTorch: 1.9.0+cu111
INFO:root:PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

INFO:root:TorchVision: 0.10.0+cu111
INFO:root:OpenCV: 4.5.2
INFO:root:MMCV: 1.3.15
INFO:root:MMCV Compiler: GCC 7.3
INFO:root:MMCV CUDA Compiler: 11.1
INFO:root:MMDeployment: 0.1.0+c6fccd0
INFO:root:onnxruntime: 1.8.1 ops_is_avaliable : True
INFO:root:tensorrt: 7.2.3.4 ops_is_avaliable : True
INFO:root:ncnn: None ops_is_avaliable : False
INFO:root:pplnn_is_avaliable: False
INFO:root:openvino_is_avaliable: False

**Comment by hanrui1sensetime** [comment]
> INFO:root:GCC: gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010

Attention with this info. You could have a try to upgrade gcc and g++ to gcc-7 and g++-7.

**Comment by MuskAI** [comment]
> > INFO:root:GCC: gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
> 
> Attention to this info. You could have a try to upgrade gcc and g++ to gcc-7 and g++-7.

Thanks for your answer ,I had installed gcc-7 and g++-7, but it doesn't be set to default setting, and I solve it by:

`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 20 --slave /usr/bin/g++ g++ /usr/bin/g++-7`

**Comment by 19823326860** [comment]
> Hi, first welcome to use our project! And could you provide your command history before `make -j$(nproc)`? Also, if you could provide the result after executing `python tools/check_env.py` is better.

Hi, I have the same problem, and the result after executing python tools/check_env.py is
10/26 15:27:22 - mmengine - INFO - **********Environmental information**********
10/26 15:27:23 - mmengine - INFO - sys.platform: linux
10/26 15:27:23 - mmengine - INFO - Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
10/26 15:27:23 - mmengine - INFO - CUDA available: True
10/26 15:27:23 - mmengine - INFO - numpy_random_seed: 2147483648
10/26 15:27:23 - mmengine - INFO - GPU 0,1,2,3: NVIDIA GeForce RTX 2080 Ti
10/26 15:27:23 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
10/26 15:27:23 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.74
10/26 15:27:23 - mmengine - INFO - GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
10/26 15:27:23 - mmengine - INFO - PyTorch: 1.10.1+cu111
10/26 15:27:23 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

10/26 15:27:23 - mmengine - INFO - TorchVision: 0.11.2+cu111
10/26 15:27:23 - mmengine - INFO - OpenCV: 4.8.1
10/26 15:27:23 - mmengine - INFO - MMEngine: 0.9.0
10/26 15:27:23 - mmengine - INFO - MMCV: 2.1.0
10/26 15:27:23 - mmengine - INFO - MMCV Compiler: GCC 5.4
10/26 15:27:23 - mmengine - INFO - MMCV CUDA Compiler: 11.1
10/26 15:27:23 - mmengine - INFO - MMDeploy: 1.3.0+
10/26 15:27:23 - mmengine - INFO -

10/26 15:27:23 - mmengine - INFO - **********Backend information**********
10/26 15:27:23 - mmengine - INFO - tensorrt:    None
10/26 15:27:23 - mmengine - INFO - ONNXRuntime: None
10/26 15:27:23 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
10/26 15:27:23 - mmengine - INFO - ONNXRuntime custom ops:      Available
10/26 15:27:23 - mmengine - INFO - pplnn:       None
10/26 15:27:23 - mmengine - INFO - ncnn:        None
10/26 15:27:23 - mmengine - INFO - snpe:        None
10/26 15:27:23 - mmengine - INFO - openvino:    None
10/26 15:27:23 - mmengine - INFO - torchscript: 1.10.1+cu111
10/26 15:27:23 - mmengine - INFO - torchscript custom ops:      NotAvailable
10/26 15:27:23 - mmengine - INFO - rknn-toolkit:        None
10/26 15:27:23 - mmengine - INFO - rknn-toolkit2:       None
10/26 15:27:23 - mmengine - INFO - ascend:      None
10/26 15:27:23 - mmengine - INFO - coreml:      None
10/26 15:27:23 - mmengine - INFO - tvm: None
10/26 15:27:23 - mmengine - INFO - vacc:        None
10/26 15:27:23 - mmengine - INFO -

10/26 15:27:23 - mmengine - INFO - **********Codebase information**********
10/26 15:27:23 - mmengine - INFO - mmdet:       None
10/26 15:27:23 - mmengine - INFO - mmseg:       None
10/26 15:27:23 - mmengine - INFO - mmpretrain:  None
10/26 15:27:23 - mmengine - INFO - mmocr:       None
10/26 15:27:23 - mmengine - INFO - mmagic:      None
10/26 15:27:23 - mmengine - INFO - mmdet3d:     None
10/26 15:27:23 - mmengine - INFO - mmpose:      None
10/26 15:27:23 - mmengine - INFO - mmrotate:    None
10/26 15:27:23 - mmengine - INFO - mmaction:    None
10/26 15:27:23 - mmengine - INFO - mmrazor:     None
10/26 15:27:23 - mmengine - INFO - mmyolo:      None
