### ISSUE TITLE
CARAFE op to onnx Fails and why not support it yet?

### ISSUE THREAD

**Issue by ethanyhzhang** [open-mmlab/mmdeploy#172]
I have a question why carefe op is not supported in mmdeploy. And I have tried myself to export it, but error like below happens:

`IndexError: _Map_base::at`

Could anyone tell me what's wrong with this custom op? 

For the same way, dcn export works well.

Thanks.

Related issue: https://github.com/onnx/onnx/issues/2698

**Comment by RunningLeon** [comment]
> 
@ethanyhzhang Hi, please be known that supporting deployment of models with custom ops is complex. We don't support models with `carefe` op by now. At the moment, you could fill your request in issue #170 .

**Comment by ethanyhzhang** [comment]
> > 
> 
> @ethanyhzhang Hi, please be known that supporting deployment of models with custom ops is complex. We don't support models with `carefe` op by now. At the moment, you could fill your request in issue #170 .

Thanks!
