### ISSUE TITLE
PillarFeatureNet object has no attribute 'vz'

### ISSUE THREAD

**Issue by aimen123** [open-mmlab/mmdeploy#1744]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

the output error : 
PillarFeatureNet object has no attribute 'vz'

but i try in mmseg , it is OK!!!!
please help me , thanks

### Reproduction

I run 
python tools/deploy.py configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py ../mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py ../checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20200620_230614-77663cd6.pth ../mmdetection3d/demo/data/kitti/kitti_000008.bin --work-dir work-dir

### Environment

```Shell
torch 1.9.0
onnxruntime 1.8.1 cpu
cuda 11.1
mmdeploy 0.12.0
mmdet3d 0.18.0
```

**Comment by aimen123** [comment]
just  voxel？dont   pillar？

**Comment by aimen123** [comment]
another question is onnx opset version 11 is not supported , i try   11 、 12、13、9， the error is the same .....
so why？

**Comment by aimen123** [comment]
the torch.linspace is not supported , use arrange?    but the error is cuda of memory

**Comment by tpoisonooo** [comment]
please run `cd mmdeploy  && python3 tools/check_env.py`  and give the output.

**Comment by tpoisonooo** [comment]
Please run `python3 tools/check_env.py` and give the output.

**Comment by tpoisonooo** [comment]
I am trying to reproduce this error.

If mmdet3d version is not important for you .. try our new production to convert pointpillar model **online**, I have tried mmdeploy v1.0.0rc0 + mmdet3d v1.1.0rc3 + onnxruntime 

This production is still in testing, you can access it here https://staging.platform.openxxlab.com/deploee

* click '模型转换' and login with github user
* click '新建转换任务'
* choose your codebase, type `configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py` into '模型训练配置'
* submit conversion task and just wait result

**Comment by aimen123** [comment]
@tpoisonooo  thanks , I did it yesterday, in my own environment, had to make changes on mmdet3d. use arrange!

**Comment by tpoisonooo** [comment]
Any PR is welcome +_+
