### ISSUE TITLE
[Feature] About version of mmdepoly

### ISSUE THREAD

**Issue by majintao1994** [open-mmlab/mmdeploy#1765]
### Motivation

Please tell me which version of mmdepoly is needed to convert the model of mmdetection3

**Comment by tpoisonooo** [comment]
[mmdeploy v1.0.0rc1](https://github.com/open-mmlab/mmdeploy/tree/v1.0.0rc1)  matches  mmdet v3.x

**Comment by majintao1994** [comment]
Can I use the yolo5-yolox trained by mmyolo to convert it

**Comment by tpoisonooo** [comment]
https://github.com/open-mmlab/mmyolo/tree/v0.4.0  also matches   mmdeploy v1.0.0rc1

check the doc here https://mmyolo.readthedocs.io/zh_CN/latest/deploy/basic_deployment_guide.html

**Comment by majintao1994** [comment]
ok，thanks for your reply.
