### ISSUE TITLE
[Feature] Compiled binary for release

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdeploy#1774]
### Motivation

Thanks for this cool repo, and thanks for the recent  1.0.0RC2 @grimoire  :+1: 
https://github.com/open-mmlab/mmdeploy/releases/tag/v1.0.0rc2

Suggestion:
I think providing pre-compiled binaries in the release could help new user installing the tools. (at the moment no artifact was joined in the release, maybe it's just an oversight ?)

**Comment by grimoire** [comment]
Thanks for the suggestion! We are building the package now and will release it ASAP.
