### ISSUE TITLE
[Feature] Support for Bottom up for HRNet in MMPose

### ISSUE THREAD

**Issue by rtgunti** [open-mmlab/mmdeploy#1787]
### Motivation

There is no detector that supports the bottom-up model in the codebase.

**Comment by RunningLeon** [comment]
@rtgunti Hi, there are a lot of supported [detectors](https://mmdeploy.readthedocs.io/en/latest/03-benchmark/supported_models.html#supported-models) from mmdet codebase supported in mmdeploy. You could give it a try.
