### ISSUE TITLE
[BUG] yolox openvino bug

### ISSUE THREAD

**Issue by q3394101** [open-mmlab/mmdeploy#179]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

YOLOX-tiny 和YOLOX-s 都无法导出openvino，修改过config 600x600动态输入依然无效。

**Reproduction**

1. What command or script did you run?

(mm) ubuntu@y9000p:~/work/jobs/mmdeploy$ python tools/deploy.py     configs/mmdet/detection/detection_openvino_dynamic-600x600.py     /home/ubuntu/work/COCO/mmdetection/configs/yolox/yolox_tiny_8x8_300e_coco.py  /home/ubuntu/work/COCO/checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth     tests/data/tiger.jpeg     --work-dir test_openvino/yolox_tiny/     --device cpu     --log-level INFO
2022-02-22 23:19:23,740 - mmdeploy - INFO - torch2onnx start.
load checkpoint from local path: /home/ubuntu/work/COCO/checkpoints/yolox_tiny_8x8_300e_coco_20211124_171234-b4047906.pth
/home/ubuntu/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/utils.py:97: UserWarning: `strip_doc_string' is deprecated and ignored. Will be removed in next PyTorch release. It's combined with `verbose' argument now. 
  warnings.warn("`strip_doc_string' is deprecated and ignored. Will be removed in "
/home/ubuntu/work/COCO/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/home/ubuntu/miniconda3/envs/mm/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/ubuntu/work/COCO/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:92: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/home/ubuntu/work/COCO/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:93: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/home/ubuntu/work/COCO/mmdeploy/mmdeploy/pytorch/functions/topk.py:27: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/home/ubuntu/work/COCO/mmdeploy/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/home/ubuntu/work/COCO/mmdeploy/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/home/ubuntu/work/COCO/mmcv/mmcv/ops/nms.py:160: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/home/ubuntu/work/COCO/mmcv/mmcv/ops/nms.py:161: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/home/ubuntu/work/COCO/mmcv/mmcv/ops/nms.py:29: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
/home/ubuntu/miniconda3/envs/mm/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:2815: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn("Exporting aten::index operator of advanced indexing in opset " +
2022-02-22 23:19:31,741 - mmdeploy - INFO - torch2onnx success.
2022-02-22 23:19:31,808 - mmdeploy - INFO - onnx2openvino with test_openvino/yolox_tiny/end2end.onnx start.
2022-02-22 23:19:33,087 - mmdeploy - INFO - Args for Model Optimizer: mo --input_model="test_openvino/yolox_tiny/end2end.onnx" --output_dir="test_openvino/yolox_tiny/" --output="dets,labels" --input="input" --input_shape="[1, 3, 600, 600]" --disable_fusing 
2022-02-22:23:19:35,root ERROR    [utils.py:41] Command 'mo --input_model="test_openvino/yolox_tiny/end2end.onnx" --output_dir="test_openvino/yolox_tiny/" --output="dets,labels" --input="input" --input_shape="[1, 3, 600, 600]" --disable_fusing ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/ubuntu/work/COCO/mmdeploy/mmdeploy/utils/utils.py", line 36, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/ubuntu/work/COCO/mmdeploy/mmdeploy/backend/openvino/onnx2openvino.py", line 89, in onnx2openvino
    mo_output = run(command, stdout=PIPE, stderr=PIPE, shell=True, check=True)
  File "/home/ubuntu/miniconda3/envs/mm/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mo --input_model="test_openvino/yolox_tiny/end2end.onnx" --output_dir="test_openvino/yolox_tiny/" --output="dets,labels" --input="input" --input_shape="[1, 3, 600, 600]" --disable_fusing ' returned non-zero exit status 1.
2022-02-22 23:19:35,699 - mmdeploy - ERROR - onnx2openvino with test_openvino/yolox_tiny/end2end.onnx failed.

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

mmdet mmcv mmdeploy 全部是最新的版本
openvino也是

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RunningLeon** [comment]
@q3394101 Hi, could try `800x1344` or `640x640` at first?

**Comment by RunningLeon** [comment]
Feel free to reopen if still have the issue.
