### ISSUE TITLE
[Docs]  没有看到关于mmaction2的deploy部署方案呀？是在其他文档吗？

### ISSUE THREAD

**Issue by gzchenjiajun** [open-mmlab/mmdeploy#1807]
### 📚 The doc issue

mmdeploy/mmaction2.md at master · open-mmlab/mmdeploy
https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmaction2.md

没有看到关于mmaction2的deploy部署方案呀？是在其他文档吗？

**Comment by gzchenjiajun** [comment]
where can I see the doc about mmaction2 deploy in jetson platform @openmmlab-bot ？

https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmaction2.md 
there's too little information here

**Comment by gzchenjiajun** [comment]
@openmmlab-bot  how to solved ?

**Comment by irexyc** [comment]
@gzchenjiajun 

You can refer to dev-1.x branch which is based on openmmlab 2.0.  The docs is [here](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/docs/en/04-supported-codebases/mmaction2.md).

Currently, mmdeploy only support deploy recognition task (tsn, slowfast).

We are now write new deployment framework to support model convertion that are not trained by openmmlab frameworks. When the framework update work is done, we will add the detection task (ava) and localization task, and you are welcome to add this feature at that time
