### ISSUE TITLE
[Feature] I hope to test the reasoning speed on the edge computing unit and compile it into a static file because it is an embedded device

### ISSUE THREAD

**Issue by Dark1Forest** [open-mmlab/mmdeploy#1808]
### Motivation

My edge computing unit cannot install the mmdeploy environment, so I hope to test the reasoning speed of the model in the edge computing unit by cross compiling to generate binary files

**Comment by lzhangzz** [comment]
When building mmdeploy, you may alter CMake flags to achieve that 
```
-DMMDEPLOY_SHARED_LIBS=OFF
-DMMDEPLOY_BUILD_SDK_MONOLITHIC=OFF
```
this will give you a few static libs which you can link to by `mmdeploy_load_static(target_name MMDeployStaticModules)` as shown in the C/C++ demo.
