### ISSUE TITLE
编译文档什么时候更新

### ISSUE THREAD

**Issue by zgq91** [open-mmlab/mmdeploy#183]
您好： 
     新的编译文档什么时候更新

**Comment by lvhan028** [comment]
Hi, we are working on it. Hope to release it by the end of this month. 

B.T.W, could you describe the issue's title and contents in English, so that people oversea can understand what it about?

**Comment by lvhan028** [comment]
Please refer to `docs/zh_cn/build/windows.md`

**Comment by zgq91** [comment]
> Please refer to `docs/zh_cn/build/windows.md`

thanks
