### ISSUE TITLE
[Bug] MMCV is incompatible with MMOCR

### ISSUE THREAD

**Issue by PETEPEtrek** [open-mmlab/mmdeploy#1830]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I tried to install mmocr using conda (on Windows 11) and followed instructions. On the `python mmocr/utils/ocr.py --det DB_r18 --recog CRNN demo/demo_text_det.jpg --imshow` stage I discovered that there are no ocr.py in utils, but anyway, I found ocr.py in mmocr dir. After that I run the command, but get `AssertionError: MMCV 1.7.1 is incompatible with MMOCR 1.0.0rc1. Please use MMCV >= 2.0.0rc1, < 2.1.0 instead.` After that I tried to do `pip install mmcv==2.0.0rc1`, but then I got `AssertionError: MMCV==2.0.0rc1 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.` Could say I got into cycle. I didn't found any issue with this problem, all of them were too old. Do you know what I can do with this problem or this is some sort of bug?

### Reproduction

I'd done everything in guide until that command with ocr.py but also there was an error that I didn't had mmengine so I installed it using pip, and after that I got errors that I described previously.

### Environment

```Shell
I didn't find 'check_env.py' file at tools
```

**Comment by xin-li-67** [comment]
Hi, would you please check the versions or the branches of MMOCR and MMDeploy you are trying to use?? You can try with the `mim list` if you have openmim installed in your working env.

**Comment by PETEPEtrek** [comment]
> Hi, would you please check the versions or the branches of MMOCR and MMDeploy you are trying to use?? You can try with the `mim list` if you have openmim installed in your working env.

Hi, I checked the versions but didn't get anything about MMDeploy, could it be my error?
`Package    Version    Source
---------  ---------  -----------------------------------------
mmcv       2.0.0rc1   https://github.com/open-mmlab/mmcv
mmcv-full  1.7.1      https://github.com/open-mmlab/mmcv
mmdet      2.28.2     https://github.com/open-mmlab/mmdetection
mmengine   0.6.0      https://github.com/open-mmlab/mmengine
mmocr      1.0.0rc1   https://github.com/open-mmlab/mmocr
`

**Comment by PETEPEtrek** [comment]
Hmm, I tried installing mmdeploy using `pip install mmdeploy` but still nothing about it in `mim list`

**Comment by xin-li-67** [comment]
> > Hi, would you please check the versions or the branches of MMOCR and MMDeploy you are trying to use?? You can try with the `mim list` if you have openmim installed in your working env.
> 
> Hi, I checked the versions but didn't get anything about MMDeploy, could it be my error? `Package Version Source
> 
> mmcv 2.0.0rc1 https://github.com/open-mmlab/mmcv mmcv-full 1.7.1 https://github.com/open-mmlab/mmcv mmdet 2.28.2 https://github.com/open-mmlab/mmdetection mmengine 0.6.0 https://github.com/open-mmlab/mmengine mmocr 1.0.0rc1 https://github.com/open-mmlab/mmocr `

Well, it seems like you have both MM2.0 projects and non-MM2.0 projects installed in the same virtual environment. It is better to isolate the two versions in separate envs.

**Comment by ozzmanmuhammad** [comment]
getting the same issue: AssertionError: MMDetection 3.2.0 is incompatible with MMOCR 1.0.1. Please use MMDetection >= 3.0.0rc5, < 3.2.0 instead.

I think the latest update of mmdet 3.2.0 (which was at the start of October 2023) is causing the error. I even tired to install lower version of mmdet but it causes error with mmcv.

**Comment by nouranali** [comment]
> getting the same issue: AssertionError: MMDetection 3.2.0 is incompatible with MMOCR 1.0.1. Please use MMDetection >= 3.0.0rc5, < 3.2.0 instead.
> 
> I think the latest update of mmdet 3.2.0 (which was at the start of October 2023) is causing the error. I even tired to install lower version of mmdet but it causes error with mmcv.

I'm having the same problem
