### ISSUE TITLE
[Feature] Does it support MMYOLO?

### ISSUE THREAD

**Issue by Howe-Young** [open-mmlab/mmdeploy#1835]
### Motivation

Does it support mmolo model conversion?

**Comment by tpoisonooo** [comment]
Yes you can search converted mmyolo with mmdeploy here (https://platform.openmmlab.com/deploee/onnx-list)

**Comment by tpoisonooo** [comment]
![sendpix7](https://user-images.githubusercontent.com/7872421/223069884-df3fc1aa-7d7a-4e75-adc7-af0df188e05e.jpg)

**Comment by Howe-Young** [comment]
> Yes you can search converted mmyolo with mmdeploy here (https://platform.openmmlab.com/deploee/onnx-list)

But When I convert MMYOLO(yolov5) model, the following error occurred: 
`AttributeError: 'YOLOv5Head' object has no attribute 'cfg'
03/06 17:03:26 - mmengine - ERROR - /workdir/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.`

**Comment by AllentDan** [comment]
Please paste the conversion command.

**Comment by Howe-Young** [comment]
> Please paste the conversion command.

python mmdeploy/tools/deploy.py \
    /yolo/mmyolo/configs/deploy/detection_tensorrt_static-640x640.py \
    /yolo/yolo_workdir/yolov5_s-v61_syncbn_8xb16-300e_coco.py \
    /yolo/yolo_workdir/epoch_40.pth \
    /yolo/mmyolo/demo/demo.jpg \
    --work-dir mmdeploy_model/yolov5 \
    --device cuda:0 \
    --dump-info

**Comment by AllentDan** [comment]
I see. Please use the latest mmyolo and mmdeploy dev-1.x.

**Comment by Howe-Young** [comment]
> use the latest mmyolo and mmdeploy dev-1.x.

The problem has been solved after upgrading mmyolo, thanks!

**Comment by AllentDan** [comment]
Close since the issue was solved.
