### ISSUE TITLE
[Feature] how can we convert models like resnet to fpga backend?

### ISSUE THREAD

**Issue by jeannotes** [open-mmlab/mmdeploy#1840]
### Motivation

how can we convert models like resnet to fpga backend?
any tutorials?

**Comment by lvhan028** [comment]
Sorry, mmdeploy doesn't support FPGA now. 
There are some tutorials on the internet, such as https://www.luffca.com/2022/08/dnn-accelerator-gemmini-part3/
Hope it can help you
