### ISSUE TITLE
[Bug] RTMDet-Ins inference with SDK , the result without mask 

### ISSUE THREAD

**Issue by flyzxm5177** [open-mmlab/mmdeploy#1849]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

**Python:**
![image](https://user-images.githubusercontent.com/36351639/223660360-67e3b928-b5a3-4b9d-a195-f6d2ebfaf434.png)
![image](https://user-images.githubusercontent.com/36351639/223660878-617895cf-08d7-4e4f-be4b-7fae7247b1be.png)

**TIt doesn't exist in C++ either:**
![image](https://user-images.githubusercontent.com/36351639/223662237-677a1727-92ab-42fd-81ed-94a8c146461d.png)
![image](https://user-images.githubusercontent.com/36351639/223662895-b8ef9c95-ce40-455e-8617-9630017b13f5.png)

**This issue is also mentioned in this link:**
https://github.com/open-mmlab/mmdeploy/issues/1722#issue-1573976926 

How to fix it? Thanks!

### Reproduction

Official example:
https://github.com/open-mmlab/mmdetection/tree/3.x/configs/rtmdet 
https://mmdeploy.readthedocs.io/en/1.x/get_started.html#installation

### Environment

```Shell
It seems to have nothing to do with the environment.
```

**Comment by lzhangzz** [comment]
1. Which deploy config are you using to convert the model?
2. Can you share the `pipeline.json` exported in the model work-dir?

**Comment by flyzxm5177** [comment]
> 1. Which deploy config are you using to convert the model?
> 2. Can you share the `pipeline.json` exported in the model work-dir?

**1**
```
python mmdeploy/tools/deploy.py \
  mmdeploy/configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py \
  mmdetection/configs/rtmdet/rtmdet-ins_tiny_8xb32-300e_coco.py \
  checkpoints/rtmdet-ins_tiny_8xb32-300e_coco_20221130_151727-ec670f7e.pth \
  mmdetection/demo/demo.jpg \
  --work-dir ./work_dirs/rtmdet-ins \
  --device cpu \
  --dump-info
```
**2**
`{
    "pipeline": {
        "input": [
            "img"
        ],
        "output": [
            "post_output"
        ],
        "tasks": [
            {
                "type": "Task",
                "module": "Transform",
                "name": "Preprocess",
                "input": [
                    "img"
                ],
                "output": [
                    "prep_output"
                ],
                "transforms": [
                    {
                        "type": "LoadImageFromFile",
                        "file_client_args": {
                            "backend": "disk"
                        }
                    },
                    {
                        "type": "Resize",
                        "keep_ratio": true,
                        "size": [
                            640,
                            640
                        ]
                    },
                    {
                        "type": "Pad",
                        "size": [
                            640,
                            640
                        ],
                        "pad_val": {
                            "img": [
                                114,
                                114,
                                114
                            ]
                        }
                    },
                    {
                        "type": "Normalize",
                        "to_rgb": false,
                        "mean": [
                            103.53,
                            116.28,
                            123.675
                        ],
                        "std": [
                            57.375,
                            57.12,
                            58.395
                        ]
                    },
                    {
                        "type": "Pad",
                        "size_divisor": 1
                    },
                    {
                        "type": "DefaultFormatBundle"
                    },
                    {
                        "type": "Collect",
                        "meta_keys": [
                            "valid_ratio",
                            "pad_shape",
                            "flip_direction",
                            "filename",
                            "flip",
                            "img_id",
                            "img_shape",
                            "img_norm_cfg",
                            "pad_param",
                            "img_path",
                            "ori_shape",
                            "scale_factor",
                            "ori_filename"
                        ],
                        "keys": [
                            "img"
                        ]
                    }
                ]
            },
            {
                "name": "rtmdet",
                "type": "Task",
                "module": "Net",
                "is_batched": false,
                "input": [
                    "prep_output"
                ],
                "output": [
                    "infer_output"
                ],
                "input_map": {
                    "img": "input"
                },
                "output_map": {}
            },
            {
                "type": "Task",
                "module": "mmdet",
                "name": "postprocess",
                "component": "ResizeBBox",
                "params": {
                    "nms_pre": 1000,
                    "min_bbox_size": 0,
                    "score_thr": 0.05,
                    "nms": {
                        "type": "nms",
                        "iou_threshold": 0.6
                    },
                    "max_per_img": 100,
                    "mask_thr_binary": 0.5
                },
                "output": [
                    "post_output"
                ],
                "input": [
                    "prep_output",
                    "infer_output"
                ]
            }
        ]
    }
}`

**Comment by lzhangzz** [comment]
There is a bug when exporting the pipeline that cause the mask output to be ignored. You may try to modify "ResizeBBox" to "ResizeInstanceMask" in `pipeline.json` for now.

And the config `instance-seg_rtmdet-ins_onnxruntime_static-640x640.py` is exporting the mask post-processing in the model which conflicts with SDK mask post-processing. You may need to set `export_postprocess_mask=False` in the config for SDK to work.

**Comment by flyzxm5177** [comment]
> There is a bug when exporting the pipeline that cause the mask output to be ignored. You may try to modify "ResizeBBox" to "ResizeInstanceMask" in `pipeline.json` for now.
> 
> And the config `instance-seg_rtmdet-ins_onnxruntime_static-640x640.py` is exporting the mask post-processing in the model which conflicts with SDK mask post-processing. You may need to set `export_postprocess_mask=False` in the config for SDK to work.

**Hi! I tried to modify "ResizeBBox" to "ResizeInstanceMask" in `pipeline.json` and mask output does have information, but it just have the w,h instead of the points of mask. how can i get the mask? There are also some issues with the output image.**

![image](https://user-images.githubusercontent.com/36351639/223947909-aea97be3-f767-48d6-b354-4a060325bf65.png)
![detector_output](https://user-images.githubusercontent.com/36351639/223948034-9bdbbb5c-6a6c-4076-9f35-90dc062eb961.jpg)

**After I set `export_postprocess_mask=False` in the config and exported new json to infer with the SDK of C++ , I got an error:**

![image](https://user-images.githubusercontent.com/36351639/223951724-b8bbe52d-1d4b-4731-bbd1-b73d59cd3804.png)

**Comment by lzhangzz** [comment]
I just verified that the `export_postprocess_mask` has no effect on the converted model. RTMDet-Ins is generating full frame masks of every instance anyway. The kind the of masks are not supported by the SDK yet. (It was verified on Mask R-CNN which generates 7x7 masks of the instances)

**Comment by flyzxm5177** [comment]
> I just verified that the `export_postprocess_mask` has no effect on the converted model. RTMDet-Ins is generating full frame masks of every instance anyway.
> 
> The kind the of masks are not supported by the SDK yet. (It was verified on Mask R-CNN which generates 7x7 masks of the instances)

Will RTMDet-Ins support SDK deployment in the future, and currently it will make an error when converting its own trained model, I mentioned here https://github.com/open-mmlab/mmdeploy/issues/1853#issue-1615054132
Waiting for your good news!

**Comment by lzhangzz** [comment]
@flyzxm5177 Can you verify if #1867 works for you? Thanks.

**Comment by flyzxm5177** [comment]
> @flyzxm5177 Can you verify if #1867 works for you? Thanks.

How to verify it, do I need to recompile this library like this? https://mmdeploy.readthedocs.io/en/1.x/02-how-to-run/prebuilt_package_windows.html#how-to-use-prebuilt-package-on-windows10

**Comment by Tyreal30416** [comment]
> @flyzxm5177 Can you verify if #1867 works for you? Thanks.

@lzhangzz That works! But the inference time is lower when modify "ResizeBBox" to "ResizeInstanceMask" in pipeline.json. It costs near 70ms on my 3080 GPU than 10ms before

**Comment by mydhui** [comment]
> > @flyzxm5177 Can you verify if #1867 works for you? Thanks.
> 
> @lzhangzz That works! But the inference time is lower when modify "ResizeBBox" to "ResizeInstanceMask" in pipeline.json. It costs near 70ms on my 3080 GPU than 10ms before

Hi I updated the newest commit from @lzhangzz , it outpus the masks, but masks are not shaped as 640x640 but some strange shape, did you also met this issue. Besides, I also found inference speed gets slower.

**Comment by mydhui** [comment]
@lzhangzz Hi, after convert rtmdet-ins model to tensorrt engine, and test with test.py

python tools/test.py \
  configs/mmdet/instance-seg/instance-seg_rtmdet-ins_tensorrt_static-640x640.py \
  ${PATH_TO_MMDET}/output/sing_rtmdet-ins_s_8xb32/sing_rtmdet-ins_s_8xb32.py \
  --model work_dirs/rtmdet-ins/end2end.engine \
  --work-dir ./work_dirs/rtmdet-ins \
  --device cuda:0 \
  --speed-test

I get FPS 212 with A100, but when inference with SDK python API,  after modified "ResizeBBox" to "ResizeInstanceMask", the FPS of mmdeploy_python.Detector() is only 20. How to reproduce the 200+ FPS with SDK? and are there other ways to perform fast inference directly on a folder of images?
