### ISSUE TITLE
[Bug] Conversion of RTMDet-Ins model which trained on custom dataset failed

### ISSUE THREAD

**Issue by flyzxm5177** [open-mmlab/mmdeploy#1853]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

**I use the following code to convert the model successfully，although visualize onnxruntime model failed.**

`python mmdeploy/tools/deploy.py \
  mmdeploy/configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py \
  mmdetection/configs/rtmdet/rtmdet-ins_tiny_8xb32-300e_coco.py \
  checkpoints/rtmdet-ins_tiny_8xb32-300e_coco_20221130_151727-ec670f7e.pth \
  mmdetection/demo/demo.jpg \
  --work-dir ./work_dirs/rtmdet-ins \
  --device cpu \
  --dump-info`

**When I convert the model I trained, I get an error**
![image](https://user-images.githubusercontent.com/36351639/223691421-4907c571-c972-406c-ae76-2e5dc76e6dea.png)
![image](https://user-images.githubusercontent.com/36351639/223691518-06c0ca6e-695c-4bd3-aced-df5e5a0a6882.png)

how i fix it? Thanks!

### Reproduction

https://github.com/open-mmlab/mmdetection/tree/3.x/configs/rtmdet

### Environment

```Shell
https://github.com/open-mmlab/mmdetection/tree/3.x/configs/rtmdet
```

**Comment by hanrui1sensetime** [comment]
Try #1884
