### ISSUE TITLE
the segment mask score is different between onnx and tensorrt backend[Bug] 

### ISSUE THREAD

**Issue by centerzong** [open-mmlab/mmdeploy#1860]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

i deploy the same segment model on onnx and tensorrt backend,  i run the same picture, however, the mask score of tensorrt is always lower than that of onnx ,ranges from 1% to 20%.

### Reproduction

i run the onnx engine with python API, but run the tensorrt engine with C# api.

### Environment

```Shell
the model is trained/deploy and test on the windows 10.
```

**Comment by irexyc** [comment]
Please provide more information like model config and pth to allow us to reproduce the issue.
