### ISSUE TITLE
[Feature] Could mmdeploy support mask2former?

### ISSUE THREAD

**Issue by kelvinwang139** [open-mmlab/mmdeploy#1880]
### Motivation

In mmdetection project, there are mask2former related configuration, does mmdeploy support it?

From paperwithcode, we could mask2former has good result in multiple areas:
https://paperswithcode.com/paper/masked-attention-mask-transformer-for

### Related resources

https://paperswithcode.com/paper/masked-attention-mask-transformer-for

**Comment by lvhan028** [comment]
Not yet

**Comment by kelvinwang139** [comment]
> 
is any plan to it?

**Comment by fernandorovai** [comment]
any news on it?

**Comment by RunningLeon** [comment]
@kelvinwang139 @fernandorovai hi, guys. If you have time, pls. try this PR https://github.com/open-mmlab/mmdeploy/pull/2347. Any comment on the PR is greatly appreciated.
