### ISSUE TITLE
Differnce between MMDeploy and MMDeploy SDK

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmdeploy#189]
What is the differnce between MMDeploy and MMDeploy SDK? Is it possible to setup MMDeploy SDK on Jetson nano?
Which MMPose models do have the support for MMDeploy currently?

**Comment by lvhan028** [comment]
Hi, thanks for your attention to MMDeploy.

MMDeploy is OpenMMLab's model deployment toolkit. It includes two major components. One is the model converter that converts the training models of OpenMMLab codebases to different inference backend models, such as the TensorRT model, OpenVINO model, and so on. The other is SDK which can be viewed as the model inference engine. It divides the model inference into a 3-step pipeline (`csrc/graph`), i.e., preprocessing (`csrc/preprocess`), NN forward (`csrc/net`), and postprocessing (`csrc/codebase`)

MMDeploy SDK can run on Jetson devices, including Nano, TX2, and Xavier.

HRNet, LiteHRNet, and MSPN of MMPose are supported in v0.3.0. You can refer to https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/benchmark.md for more detailed information

**Comment by Thevakumar-Luheerathan** [comment]
Thank you..

**Comment by FraPochetti** [comment]
Hi there, I might be looking in the wrong place but where exactly would I find info on how to use the MMDeploy-SDK, please?

Also, once we create `.onnx` and `.engine` files for ONNX and TRT respectively, can we use them as they are outside the MMDeploy ecosystem?
If yes, I assume we'd have to handle the preprocessing ourselves?

**Comment by ayush-AkulaTech** [comment]
@FraPochetti Hi, did you get an answer to your question?

**Comment by Petros626** [comment]
@FraPochetti did you used the supported models for backend export or non supported models?
