### ISSUE TITLE
[Docs] Does the onnxruntime inference engine SDK not support GPU in source code compilation?

### ISSUE THREAD

**Issue by xiabo123** [open-mmlab/mmdeploy#1893]
### 📚 The doc issue

https://github.com/open-mmlab/mmdeploy/blob/v1.0.0rc3/docs/zh_cn/01-how-to-build/linux-x86_64.md
![image](https://user-images.githubusercontent.com/40659418/226264751-ce8b908c-4a10-4ddf-adca-a6d5a3ce7db0.png)
The onnxruntime in this file only has a CPU, is it not supported by the GPU?

**Comment by irexyc** [comment]
It support onnxruntime-gpu.

You have to：
1) build with -DMMDEPLOY_TARGET_DEVICES="cpu;cuda"
2) use onnxruntime-gpu lib
3) use like `./image_classification cuda /path/to/onnxmodel/dir /path/to/imagepath`

**Comment by xiabo123** [comment]
@irexyc Thank you for your answer.

**Comment by xiabo123** [comment]
![image](https://user-images.githubusercontent.com/40659418/226537739-7033a981-9c5c-4cbb-b619-f3aba6ab8814.png)
Excuse me again, the content mentioned here only supports CPU.
Link ”https://github.com/open-mmlab/mmdeploy/releases/download/v0.13.0/mmdeploy-0.13.0-linux-x86_64-onnxruntime1.8.1.tar.gz“. 
Is the SDK for the release port a CPU or a GPU?

**Comment by irexyc** [comment]
The prebuild  `mmdeploy-0.13.0-linux-x86_64-onnxruntime1.8.1.tar.gz` package  built with `-DMMDEPLOY_TARGET_DEVICES="cpu"`. So, if you wan't to use gpu, you have to build yourself.
