### ISSUE TITLE
[Bug] failed to get rtmdet-ins mask result by c++ detector

### ISSUE THREAD

**Issue by XuErShuo** [open-mmlab/mmdeploy#1897]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### mask is empty from detect SDK
Hello, when I run the c++ detector and python object_detection.py in [demo](https://github.com/open-mmlab/mmdeploy/tree/master/demo), using onnx conversion model from [rtmdet-ins_s_8xb32-300e_coco.py](https://github.com/open-mmlab/mmdetection/blob/61dd8d518b13c7ee4bdf609595b7e803f3ac0224/configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py), but there is no mask in the detect result, that is, the mask is always empty, like that the code always evaluates to empty " [if (mask) ](https://github.com/open-mmlab/mmdeploy/blob/34c68663b6c1865b702247dc48d99781b8bd748e/demo/csrc/cpp/utils/visualize.h#L86)" in c++ and break "[if masks[index].size:](https://github.com/open-mmlab/mmdeploy/blob/34c68663b6c1865b702247dc48d99781b8bd748e/demo/python/object_detection.py#L36)" in python. 

### **Details:**
I convert the instance-seg model refer to this [documentation](https://github.com/open-mmlab/mmdetection/blob/61dd8d518b13c7ee4bdf609595b7e803f3ac0224/configs/rtmdet/README.md)，and successfully generated the onnx model

- /rtmdet-ins/
-- deploy.json
-- detail.json
-- pipeline.json
-- end2end.onnx
-- output_onnxruntime.jpg
-- output_pytorch.jpg

using the commond

`python tools/deploy.py \
  configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py  \
  ${PATH_TO_MMDET}/configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py \
  checkpoint/rtmdet-ins_s_8xb32-300e_coco/rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth \
  demo/resources/det.jpg \
  --work-dir ./work_dirs/rtmdet-ins \
  --device cuda:0 \
  --show`

I checked that there is no problem with the test images (output_onnxruntime.jpg and output_pytorch.jpg), the original image is [det.jpg](https://github.com/open-mmlab/mmdeploy/blob/34c68663b6c1865b702247dc48d99781b8bd748e/demo/resources/det.jpg)
I both tried python and c++ detector，using the commond
`./detcetor cuda  {my path to }/work_dirs/rtmdet-ins   {my path to }/demo/resources/det.jpg`
or
`python object_detection.py  cuda  {my path to }/work_dirs/rtmdet-ins   {my path to }/demo/resources/det.jpg`
but the result img "detector_output.jpg" only plot bboxes without its masks. I check the value [masks](https://github.com/open-mmlab/mmdeploy/blob/34c68663b6c1865b702247dc48d99781b8bd748e/demo/python/object_detection.py#L26)  and [det.mask](https://github.com/open-mmlab/mmdeploy/blob/34c68663b6c1865b702247dc48d99781b8bd748e/demo/csrc/cpp/detector.cxx#L38), and both them are empty.  **Please help me, thanks !**

### Reproduction

`./detcetor cuda  {my path to }/work_dirs/rtmdet-ins   {my path to }/demo/resources/det.jpg`
`python object_detection.py  cuda  {my path to }/work_dirs/rtmdet-ins   {my path to }/demo/resources/det.jpg`

### Environment

```Shell
03/21 10:39:41 - mmengine - INFO - 

03/21 10:39:41 - mmengine - INFO - **********Environmental information**********
03/21 10:39:42 - mmengine - INFO - sys.platform: linux
03/21 10:39:42 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
03/21 10:39:42 - mmengine - INFO - CUDA available: True
03/21 10:39:42 - mmengine - INFO - numpy_random_seed: 2147483648
03/21 10:39:42 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1060
03/21 10:39:42 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
03/21 10:39:42 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
03/21 10:39:42 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
03/21 10:39:42 - mmengine - INFO - PyTorch: 1.13.0+cu117
03/21 10:39:42 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

03/21 10:39:42 - mmengine - INFO - TorchVision: 0.14.0+cu117
03/21 10:39:42 - mmengine - INFO - OpenCV: 4.7.0
03/21 10:39:42 - mmengine - INFO - MMEngine: 0.7.0
03/21 10:39:42 - mmengine - INFO - MMCV: 2.0.0rc4
03/21 10:39:42 - mmengine - INFO - MMCV Compiler: GCC 9.3
03/21 10:39:42 - mmengine - INFO - MMCV CUDA Compiler: 11.7
03/21 10:39:42 - mmengine - INFO - MMDeploy: 1.0.0rc3+50bd7e9
03/21 10:39:42 - mmengine - INFO - 

03/21 10:39:42 - mmengine - INFO - **********Backend information**********
03/21 10:39:42 - mmengine - INFO - tensorrt:	8.2.3.0
03/21 10:39:42 - mmengine - INFO - tensorrt custom ops:	NotAvailable
03/21 10:39:42 - mmengine - INFO - ONNXRuntime:	None
03/21 10:39:42 - mmengine - INFO - ONNXRuntime-gpu:	1.8.1
03/21 10:39:42 - mmengine - INFO - ONNXRuntime custom ops:	Available
03/21 10:39:42 - mmengine - INFO - pplnn:	None
03/21 10:39:42 - mmengine - INFO - ncnn:	None
03/21 10:39:42 - mmengine - INFO - snpe:	None
03/21 10:39:42 - mmengine - INFO - openvino:	None
03/21 10:39:42 - mmengine - INFO - torchscript:	1.13.0+cu117
03/21 10:39:42 - mmengine - INFO - torchscript custom ops:	NotAvailable
03/21 10:39:42 - mmengine - INFO - rknn-toolkit:	None
03/21 10:39:42 - mmengine - INFO - rknn-toolkit2:	None
03/21 10:39:42 - mmengine - INFO - ascend:	None
03/21 10:39:42 - mmengine - INFO - coreml:	None
03/21 10:39:42 - mmengine - INFO - tvm:	None
03/21 10:39:42 - mmengine - INFO - vacc:	None
03/21 10:39:42 - mmengine - INFO - 

03/21 10:39:42 - mmengine - INFO - **********Codebase information**********
03/21 10:39:42 - mmengine - INFO - mmdet:	3.0.0rc6
03/21 10:39:42 - mmengine - INFO - mmseg:	None
03/21 10:39:42 - mmengine - INFO - mmcls:	None
03/21 10:39:42 - mmengine - INFO - mmocr:	None
03/21 10:39:42 - mmengine - INFO - mmedit:	None
03/21 10:39:42 - mmengine - INFO - mmdet3d:	None
03/21 10:39:42 - mmengine - INFO - mmpose:	None
03/21 10:39:42 - mmengine - INFO - mmrotate:	None
03/21 10:39:42 - mmengine - INFO - mmaction:	None
03/21 10:39:42 - mmengine - INFO - mmrazor:	None
```

**Comment by lvhan028** [comment]
Similar issue to https://github.com/open-mmlab/mmdeploy/issues/1849
PR https://github.com/open-mmlab/mmdeploy/pull/1867 is addressing this issue. You can have a try

**Comment by XuErShuo** [comment]
> Similar issue to #1849 PR #1867 is addressing this issue. You can have a try

Thank you first. I try today, and output result is same as yours. #1849  
![223948034-9bdbbb5c-6a6c-4076-9f35-90dc062eb961](https://user-images.githubusercontent.com/46214949/226862107-5220ede8-2125-4d93-9722-af5d0f7f7f8a.jpg)

**Comment by lvhan028** [comment]
Please try the latest dev-1.x branch. This is what I got:
![image](https://user-images.githubusercontent.com/4560679/227145875-8e32e122-c589-4eea-b059-e85cee778bd1.png)
