### ISSUE TITLE
debug dbnet tensorrt bug

### ISSUE THREAD

**Issue by zgq91** [open-mmlab/mmdeploy#190]

**Comment by zgq91** [comment]
[2022-02-28 13:43:04.209] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-02-28 13:43:04.401] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "name": "text-detector",
  "output": [
    "dets"
  ],
  "params": {
    "model": "/home/gpu/workspace/mmdeploy/convert_model/dbnet.engine"
  },
  "type": "Inference"
}
[2022-02-28 13:43:04.401] [mmdeploy] [error] [model.cpp:44] no ModelImpl can read sdk_model /home/gpu/workspace/mmdeploy/convert_model/dbnet.engine
[2022-02-28 13:43:04.401] [mmdeploy] [error] [model.cpp:15] load model failed. Its file path is '/home/gpu/workspace/mmdeploy/convert_model/dbnet.engine'
[2022-02-28 13:43:04.402] [mmdeploy] [error] [text_detector.cpp:56] exception caught: not supported (2) @ /home/gpu/workspace/mmdeploy/csrc/core/model.cpp:45
failed to create text_detector, code: 6

**Comment by lzhangzz** [comment]
`dbnet.engine` is a backend engine file, can't be used with SDK directly.

For inference with SDK, add `--dump-info` when converting the model (by `tools/deploy.py`) and pass the working directory (the one specified by `--work-dir`) to SDK.

**Comment by zgq91** [comment]
> `dbnet.engine` is a backend engine file, can't be used with SDK directly.
> 
> For inference with SDK, add `--dump-info` when converting the model (by `tools/deploy.py`) and pass the working directory (the one specified by `--work-dir`) to SDK.

[2022-02-28 17:09:46.208] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2022-02-28 17:09:46.388] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "name": "text-detector",
  "output": [
    "dets"
  ],
  "params": {
    "model": "/home/gpu/workspace/mmdeploy/convert_model/"
  },
  "type": "Inference"
}
[2022-02-28 17:09:46.388] [mmdeploy] [info] [model.cpp:38] DirectoryModel successfully load sdk model /home/gpu/workspace/mmdeploy/convert_model/
[2022-02-28 17:09:46.389] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "color_type": "color_ignore_orientation",
      "type": "LoadImageFromFile"
    },
    {
      "img_scale": [
        320,
        320
      ],
      "keep_ratio": false,
      "size": [
        320,
        320
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "filename",
        "flip",
        "flip_direction",
        "ori_filename",
        "pad_shape",
        "img_norm_cfg",
        "valid_ratio",
        "ori_shape",
        "img_shape",
        "scale_factor"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-02-28 17:09:46.389] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "color_type": "color_ignore_orientation",
      "type": "LoadImageFromFile"
    },
    {
      "img_scale": [
        320,
        320
      ],
      "keep_ratio": false,
      "size": [
        320,
        320
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "filename",
        "flip",
        "flip_direction",
        "ori_filename",
        "pad_shape",
        "img_norm_cfg",
        "valid_ratio",
        "ori_shape",
        "img_shape",
        "scale_factor"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-02-28 17:09:46.389] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "dbnet",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-02-28 17:09:46.389] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "dbnet",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-02-28 17:09:46.389] [mmdeploy] [info] [cuda_device.cpp:84] Default CUDA allocator initialized
[2022-02-28 17:09:47.432] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
[2022-02-28 17:09:47.945] [mmdeploy] [warning] [trt_net.cpp:24] TRTNet: TensorRT was linked against cuBLAS/cuBLAS LT 11.5.1 but loaded cuBLAS/cuBLAS LT 11.4.2
[2022-02-28 17:09:47.950] [mmdeploy] [info] [common.h:15] config: {
  "component": "DBHead",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmocr",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {
    "in_channels": 256,
    "loss": {
      "alpha": 5.0,
      "bbce_loss": true,
      "beta": 10.0,
      "type": "DBLoss"
    },
    "postprocessor": {
      "text_repr_type": "quad",
      "type": "DBPostprocessor"
    }
  },
  "type": "Task"
}
[2022-02-28 17:09:47.950] [mmdeploy] [info] [common.h:15] config: {
  "component": "DBHead",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmocr",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {
    "in_channels": 256,
    "loss": {
      "alpha": 5.0,
      "bbce_loss": true,
      "beta": 10.0,
      "type": "DBLoss"
    },
    "postprocessor": {
      "text_repr_type": "quad",
      "type": "DBPostprocessor"
    }
  },
  "type": "Task"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img",
    "dets"
  ],
  "module": "WarpBoxes",
  "name": "warp",
  "output": [
    "patches"
  ],
  "type": "Task"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img",
    "dets"
  ],
  "module": "WarpBoxes",
  "name": "warp",
  "output": [
    "patches"
  ],
  "type": "Task"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "patches"
  ],
  "name": "flatten",
  "output": [
    "patch_flat",
    "patch_index"
  ],
  "type": "Flatten"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "patch_flat"
  ],
  "name": "recog",
  "output": [
    "texts"
  ],
  "params": {
    "batch_size": 1,
    "model": "/home/gpu/workspace/mmdeploy/convert_model/"
  },
  "type": "Inference"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [model.cpp:38] DirectoryModel successfully load sdk model /home/gpu/workspace/mmdeploy/convert_model/
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "color_type": "color_ignore_orientation",
      "type": "LoadImageFromFile"
    },
    {
      "img_scale": [
        320,
        320
      ],
      "keep_ratio": false,
      "size": [
        320,
        320
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "filename",
        "flip",
        "flip_direction",
        "ori_filename",
        "pad_shape",
        "img_norm_cfg",
        "valid_ratio",
        "ori_shape",
        "img_shape",
        "scale_factor"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "color_type": "color_ignore_orientation",
      "type": "LoadImageFromFile"
    },
    {
      "img_scale": [
        320,
        320
      ],
      "keep_ratio": false,
      "size": [
        320,
        320
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "keys": [
        "img"
      ],
      "type": "ImageToTensor"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "filename",
        "flip",
        "flip_direction",
        "ori_filename",
        "pad_shape",
        "img_norm_cfg",
        "valid_ratio",
        "ori_shape",
        "img_shape",
        "scale_factor"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "dbnet",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-02-28 17:09:47.951] [mmdeploy] [info] [common.h:15] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "dbnet",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-02-28 17:09:47.952] [mmdeploy] **[error] [trt_net.cpp:105] TRTNet: device must be a GPU!**
[2022-02-28 17:09:47.952] [mmdeploy] [error] [text_recognizer.cpp:77] exception caught: unknown (6) @ /home/gpu/workspace/mmdeploy/csrc/net/net_module.cpp:44
failed to create text_recognizer, code: 6

**Comment by lzhangzz** [comment]
`--device cuda`
