### ISSUE TITLE
Different results with mmyolo exported models

### ISSUE THREAD

**Issue by LidiaFantauzzo** [open-mmlab/mmdeploy#1903]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi everyone,

I used the yolov8 model from mmyolo to train a model with my customized dataset in python (config file in "Reproduction" section).
Then I exported the model both with TensorRT and ONNX to be used on a c++ application, but when I compared the results obtained with all of them (original in pyhton, tensorrt and onnx in c++), I noticed a lot of differences.
The score threshold used for all the inferences was 0.01.

So, I tested the trained model with Python using the script
`python mmyolo-0.5.0/demo/image_demo.py /software/OpenMMLab/data/images/1234.bmp mmyolo-0.5.0/configs/custom_dataset/yolov8_test.py mmdeploy-1.0.0rc3/models/Yolo/latest.pth --out-dir output --device cuda:0 --score-thr 0.01`

Here, the command used to export the model are reported
TENSORRT
`python ./tools/deploy.py ../mmyolo-0.5.0/configs/deploy/detection_tensorrt-fp16_dynamic-64x64-1344x1344.py ../mmyolo-0.5.0/configs/custom_dataset/yolov8.py ./models/Yolo/latest.pth ./models/Yolo/test_yolo.bmp --work-dir ./deployed/YOLO/TRT --device cuda:0 --dump-info`

ONNX
`python ./tools/deploy.py ../mmyolo-0.5.0/configs/deploy/detection_onnxruntime_dynamic.py ../mmyolo-0.5.0/configs/custom_dataset/yolov8.py ./models/Yolo/latest.pth ./models/Yolo/test_yolo.bmp --work-dir ./deployed/YOLO/ONNX --device cuda:0 --dump-info`

At this point I used the c++ API mmdeploy-1.0.0rc3/demo/csrc/cpp/detector.cxx to test the exported models and these are some of the results obtained, compared:
respectively original model - exported TRT model - exported ONNX model

![IMG_68781098_68785242_61](https://user-images.githubusercontent.com/65127026/226832866-c32a320f-9862-41c2-95a3-fc1d9966e243.jpg)
![IMG_51567518_51574426_61](https://user-images.githubusercontent.com/65127026/226832883-193bce8f-2d4d-427b-8508-84f0bd7b05b4.jpg)

Can you help me find out why there are so many differences between original and exported models?
Thank you so much

### Reproduction

- YOLOV8 CONFIG FILE

base = '../yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py'
max_epochs = 200
data_root = '/home/PycharmProjects/OpenMMYolo/mmyolo/data/unified/'
work_dir = './work_dirs/yolov8'
load_from = '/home/PycharmProjects/OpenMMYolo/mmyolo/yolov8_s_syncbn_fast_8xb16-500e_coco_20230117_180101-5aa5f0f1.pth'
train_batch_size_per_gpu = 16
train_num_workers = 16
save_epoch_intervals = 20
base_lr = 0.01
class_name = ('Gap', 'Squat', 'Wheelslip', 'LightSquat', 'AggregatedSquat', 'Weld', 'SideSquat', 'Corrugation', 'HeadChecking')
num_classes = len(class_name)
metainfo = dict(
classes=class_name,
palette=[(220, 20, 60), (191, 157, 216), (230, 250, 100), (160, 250, 100), (100, 250, 220), (31, 112, 233), (200, 81, 94), (233, 92, 224), (255, 32, 0)])
train_cfg = dict(
max_epochs=max_epochs,
val_begin=20,
val_interval=save_epoch_intervals )
model = dict(
bbox_head=dict(
head_module=dict(num_classes=num_classes)),
train_cfg=dict(
initial_assigner=dict(num_classes=num_classes),
assigner=dict(num_classes=num_classes)))
train_dataloader = dict(
batch_size=train_batch_size_per_gpu,
num_workers=train_num_workers,
dataset=dict(
type=base.dataset_type,
data_root=data_root,
metainfo=metainfo,
ann_file='annotations/trainval.json',
data_prefix=dict(img='images/'),
filter_cfg=dict(filter_empty_gt=False, min_size=32),
pipeline=base.train_pipeline))
val_dataloader = dict(
dataset=dict(
metainfo=metainfo,
data_root=data_root,
ann_file='annotations/test.json',
data_prefix=dict(img='images/')))
test_dataloader = val_dataloader
val_evaluator = dict(ann_file=data_root + 'annotations/test.json')
test_evaluator = val_evaluator
optim_wrapper = dict(optimizer=dict(lr=base_lr))
default_hooks = dict(
checkpoint=dict(
type='CheckpointHook',
interval=save_epoch_intervals,
max_keep_ckpts=5,
save_best='auto'),
param_scheduler=dict(max_epochs=max_epochs),
logger=dict(type='LoggerHook', interval=10))
visualizer = dict(vis_backends=[dict(type='LocalVisBackend'), dict(type='WandbVisBackend')])

- .pth file obtained by training the yolov8 model and then used to export the model
[yolov8_model.pth](https://drive.google.com/file/d/1REH7wOBRP-G9mI3TXcgZflVDe9jROxU1/view?usp=sharing)

### Environment

```Shell
MMDEPLOY ENV 

03/22 08:40:14 - mmengine - INFO - 
03/22 08:40:14 - mmengine - INFO - **********Environmental information**********
03/22 08:40:15 - mmengine - INFO - sys.platform: linux
03/22 08:40:15 - mmengine - INFO - Python: 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
03/22 08:40:15 - mmengine - INFO - CUDA available: True
03/22 08:40:15 - mmengine - INFO - numpy_random_seed: 2147483648
03/22 08:40:15 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 2070 SUPER
03/22 08:40:15 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
03/22 08:40:15 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
03/22 08:40:15 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
03/22 08:40:15 - mmengine - INFO - PyTorch: 1.13.1
03/22 08:40:15 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

03/22 08:40:15 - mmengine - INFO - TorchVision: 0.14.1
03/22 08:40:15 - mmengine - INFO - OpenCV: 4.7.0
03/22 08:40:15 - mmengine - INFO - MMEngine: 0.7.0
03/22 08:40:15 - mmengine - INFO - MMCV: 2.0.0rc4
03/22 08:40:15 - mmengine - INFO - MMCV Compiler: GCC 9.3
03/22 08:40:15 - mmengine - INFO - MMCV CUDA Compiler: 11.7
03/22 08:40:15 - mmengine - INFO - MMDeploy: 1.0.0rc3+
03/22 08:40:15 - mmengine - INFO - 

03/22 08:40:15 - mmengine - INFO - **********Backend information**********
03/22 08:40:16 - mmengine - INFO - tensorrt:    8.5.3.1
03/22 08:40:16 - mmengine - INFO - tensorrt custom ops: Available
03/22 08:40:16 - mmengine - INFO - ONNXRuntime: None
03/22 08:40:16 - mmengine - INFO - ONNXRuntime-gpu:     1.14.1
03/22 08:40:16 - mmengine - INFO - ONNXRuntime custom ops:      Available
03/22 08:40:16 - mmengine - INFO - pplnn:       None
03/22 08:40:16 - mmengine - INFO - ncnn:        None
03/22 08:40:16 - mmengine - INFO - snpe:        None
03/22 08:40:16 - mmengine - INFO - openvino:    None
03/22 08:40:16 - mmengine - INFO - torchscript: 1.13.1
03/22 08:40:16 - mmengine - INFO - torchscript custom ops:      NotAvailable
03/22 08:40:16 - mmengine - INFO - rknn-toolkit:        None
03/22 08:40:16 - mmengine - INFO - rknn-toolkit2:       None
03/22 08:40:16 - mmengine - INFO - ascend:      None
03/22 08:40:16 - mmengine - INFO - coreml:      None
03/22 08:40:16 - mmengine - INFO - tvm: None
03/22 08:40:16 - mmengine - INFO - 

03/22 08:40:16 - mmengine - INFO - **********Codebase information**********
03/22 08:40:16 - mmengine - INFO - mmdet:       3.0.0rc6
03/22 08:40:16 - mmengine - INFO - mmseg:       None
03/22 08:40:16 - mmengine - INFO - mmcls:       None
03/22 08:40:16 - mmengine - INFO - mmocr:       None
03/22 08:40:16 - mmengine - INFO - mmedit:      None
03/22 08:40:16 - mmengine - INFO - mmdet3d:     None
03/22 08:40:16 - mmengine - INFO - mmpose:      None
03/22 08:40:16 - mmengine - INFO - mmrotate:    None
03/22 08:40:16 - mmengine - INFO - mmaction:    None


MMYOLO collect_env.py

sys.platform: linux
Python: 3.8.0 (default, Nov 6 2019, 21:49:08) [GCC 7.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2070 SUPER
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:

GCC 9.3
C++ Version: 201402
Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
OpenMP 201511 (a.k.a. OpenMP 4.5)
LAPACK is enabled (usually provided by MKL)
NNPACK is enabled
CPU capability usage: AVX2
CUDA Runtime 11.7
NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
CuDNN 8.5
Magma 2.6.1
Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
TorchVision: 0.14.1
OpenCV: 4.7.0
MMEngine: 0.7.0
MMCV: 2.0.0rc4
MMDetection: 3.0.0rc6
MMYOLO: 0.5.0+
```

**Comment by hanrui1sensetime** [comment]
Only score > det_thr are shown in SDK output image, see [here](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/csrc/cpp/detector.cxx). This design will avoid too many minority bboxes in real scene usage.

**Comment by LidiaFantauzzo** [comment]
I set the det_thr parameter to 0.01 too, so all the experiments were done with the same score threshold.
| RAW Model - PTH (test with mmyolo/image_demo.py) | TRT model with Python (test with mmdeploy/tool/test.py)| TRT model with c++ (test with Detector.cxx) |
|-----------|-----------|-----------|
|    0.01 |  0.01 |  0.01 |

**Comment by LidiaFantauzzo** [comment]
To make it more clear, in the image below, the TRT model tested in c++ does not recognize the bottom element that instead was detected with the raw model and with TRT model in Python, with a really high score (83%).
So, even if we had a drop in confidence, the TRT model should have detected it, even with a lower score. Instead, it is completely absent and I can't explain it.


![img_2](https://user-images.githubusercontent.com/65127026/227201282-21328e65-8106-49ec-a069-378a6f95bfc6.jpg)

**Comment by hanrui1sensetime** [comment]
> So, even if we had a drop in confidence, the TRT model should have detected it, even with a lower score. Instead, it is completely absent and I can't explain it.

Could you please provide me the original test image for my test?

**Comment by LidiaFantauzzo** [comment]
Sure, at [this ](https://drive.google.com/drive/folders/1yzL_IeLcvKyclBWqNNGhPaz13Yma4djS?usp=sharing)link you can find all the three images showed in my past comments with relative labels.

**Comment by hanrui1sensetime** [comment]
> Sure, at [this ](https://drive.google.com/drive/folders/1yzL_IeLcvKyclBWqNNGhPaz13Yma4djS?usp=sharing)link you can find all the three images showed in my past comments with relative labels. To make things easier, in the TRT folder, there is also the latest.pth model already exported with TensorRT.

Change [this line](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/csrc/c/object_detection.cpp#L56) here.

**Comment by LidiaFantauzzo** [comment]
Thank you for your answer, but you are referring to a line in a script that I have never used. 
That line is in [mmdeploy/demo/csrc/c/object_detection.cpp](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/csrc/c/object_detection.cpp), while the script that I used to do inference in c++ was [mmdeploy/demo/csrc/cpp/detector.cxx](https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/csrc/cpp/detector.cxx), as we discussed in previous comments. Am I missing something?

**Comment by LidiaFantauzzo** [comment]
Hi, is there any update on this?

**Comment by carminez88** [comment]
Hello, I'm experiencing the same problem that @LidiaFantauzzo shared.

Can you give us any update about this topic? 

Thanks

**Comment by carminez88** [comment]
After having recompiled the library in Debug mode and tried to see the raw outputs from the backends (both ONNX and TensorRT), it seems that the problem here is actually triggered by the resize method used.

In particular, when executing  `mmdeploy::Detector::Result dets = detector.Apply(img);` and putting a breakpoint in `opencv_utils.cpp:110`

```cpp
Result<int> GetInterpolationMethod(const std::string_view& method) {
  if (method == "bilinear") {
    return cv::INTER_LINEAR;
```

I see that the "bilinear" interpolation is mapped to `cv::INTER_LINEAR`. If I map into `cv::INTER_AREA` instead, I got the expected result, coherent to the Python API output. So I think we got different behaviours based on the reside method currently used.

Is there any way to configure the resize method before the inference?

**Comment by carminez88** [comment]
I've took a look at the Python counterpart, debugging a bit more. I stopped at this point:

```python
                # resize image according to the ratio
                image = mmcv.imrescale(
                    img=image,
                    scale=ratio,
                    interpolation='area' if ratio < 1 else 'bilinear',
                    backend=self.backend)
```

This code snippet is from `mmyolo\datasets\transforms\transforms.py:102`. So it seems that the resize policy is evaluated at "runtime" based on the ratio parameter.

Debugging the C++ codebase, I see that the resize step is built during the Detector initialization. In particular in `letter_resize.cpp:45`:

```cpp
    interpolation_ = args.value<string>("interpolation", "bilinear");
```

So apparently, we have two different behaviours based on the type of API:

- Python: the resize policy is selected based on the current image aspect ratio
- C++: the resize policy is selected based on the JSON content **pipeline.json** (`"interpolation": "area"`) and **isn't** based on the current image aspect ratio

So, overall, changing the resize algorithm, result in dramatic changes on the inference results.

@hanrui1sensetime @lvhan028  Can you please comment the above observations?
