### ISSUE TITLE
[Feature] Does mmdeploy support pytorch 2.0?

### ISSUE THREAD

**Issue by kelvinwang139** [open-mmlab/mmdeploy#1910]
### Motivation

support pytorch 2.0

pytorch 2.0 is official released. Does mmdeploy support pytorch 2.0 (officially announced by pytorch that 2.0 is 100% backward compatible by definition.)

**Comment by lvhan028** [comment]
mmdeploy hasn't tested pytorch2.0 yet.

**Comment by kelvinwang139** [comment]
Hi any progress for supporting pytorch 2.0 under latest mmdeploy version?

**Comment by lvhan028** [comment]
It supports now, deosn't it? @RunningLeon

**Comment by RunningLeon** [comment]
> Hi any progress for supporting pytorch 2.0 under latest mmdeploy version?

@kelvinwang139 hi, yes. Pls. have a try.

**Comment by kelvinwang139** [comment]
> > Hi any progress for supporting pytorch 2.0 under latest mmdeploy version?
> 
> @kelvinwang139 hi, yes. Pls. have a try.

Thanks Leon!
