### ISSUE TITLE
The given version [8] is not supported, only version 1 to 7 is supported in this build.关于使用sdk来进行部署

### ISSUE THREAD

**Issue by fangfangssj** [open-mmlab/mmdeploy#1913]
### 📚 The doc issue

使用官方提供的sdk进行python的部署，已按照教程把onnxruntime放进环境变量，按照教程进行推理的时候报错The given version [8] is not supported, only version 1 to 7 is supported in this build.
网上查询到是onnxruntime的版本不对应而产生的报错，但设置环境变量后仍未解决。
<img width="303" alt="image" src="https://user-images.githubusercontent.com/99968055/227239850-c864e866-8310-427a-af6d-cc263b0907cc.png">

**Comment by irexyc** [comment]
Search from the web, I think you may load the wrong onnxruntime.dll, may similiar to https://github.com/microsoft/onnxruntime/issues/11230

You can check the `PATH` and use [everything](https://www.voidtools.com/support/everything/) to search if there are multi version of onnxruntime.dll on you pc.

[Dependencies](https://github.com/lucasg/Dependencies/releases) is also a usefull tool to check the dependencies of dll. You can use it to check the pyd file of mmdeploy_python
