### ISSUE TITLE
[Feature] No latency benchmark of mmrotate

### ISSUE THREAD

**Issue by fuqianya** [open-mmlab/mmdeploy#1920]
### Motivation

Hi,

I have noticed that there is a performance benchmark for mmrotate in the [benchmark.md](https://github.com/open-mmlab/mmdeploy/blob/1.x/docs/en/03-benchmark/benchmark.md). However, there is no corresponding latency benchmark available.

**Comment by RunningLeon** [comment]
@fuqianya Hi, sorry for the late reply. The latency benchmark for mmrotate is not planned yet.
