### ISSUE TITLE
[Bug] 经过mmrotate训练的模型pth利用mmdeploy转换后检测框消失了.

### ISSUE THREAD

**Issue by xuexisuanfa** [open-mmlab/mmdeploy#1924]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

利用mmdeploy对mmrotate生成的pth进行模型转换后，会生成一张被检测后的图，但是这个图却不显示任何检测框，而这个pth文件在mmrotate的test脚本测试中是能框的，而且标的数值很多是0.9几。

相关文件材料（data文件夹为数据集，out压缩包是当时用mmrotate中test.py生成的结果）|：
链接：https://pan.baidu.com/s/1ZjAyq0YxuKlWCKgj8Kw5kw 
提取码：h909

### Reproduction

利用mmdeploy对mmrotate生成的pth进行模型转换后，会生成一张被检测后的图，但是这个图却不显示任何检测框，而这个pth文件在mmrotate的test脚本测试中是能框的，而且标的数值很多是0.9几。

相关文件材料（data文件夹为数据集，out压缩包是当时用mmrotate中test.py生成的结果）|：
链接：https://pan.baidu.com/s/1ZjAyq0YxuKlWCKgj8Kw5kw 
提取码：h909

### Environment

```Shell
利用mmdeploy对mmrotate生成的pth进行模型转换后，会生成一张被检测后的图，但是这个图却不显示任何检测框，而这个pth文件在mmrotate的test脚本测试中是能框的，而且标的数值很多是0.9几。

相关文件材料（data文件夹为数据集，out压缩包是当时用mmrotate中test.py生成的结果）|：
链接：https://pan.baidu.com/s/1ZjAyq0YxuKlWCKgj8Kw5kw 
提取码：h909
```

复现方法：
注意将mmdeploy文件夹和rotated文件夹放在同一个文件夹里。

然后命令行运行：
python mmdeploy/tools/deploy.py rotated/rotated-detection_tensorrt_dynamic-320x320-1024x1024.py rotated/rotated-faster-rcnn-le90_r50_fpn_1x_dota.py   rotated/epoch_12.pth  rotated/1.jpg  --work-dir mmdeploy_model/rotatedfasterrcnn  --device cuda  --dump-info  --test-img rotated/1.jpg

相关文件（比上面那个百度网盘文件小很多，但是不包含数据集等）：
链接：https://pan.baidu.com/s/1L1lpNvcBd-3EFDPUfZLh7w 
提取码：a2sy

**Comment by irexyc** [comment]
Please supply more details information like how your convert the model and inferenced by pytorch and mmdeploy.

You can refer to https://github.com/open-mmlab/mmdeploy/issues/1912

**Comment by irexyc** [comment]
After communicating with xuexisuanfa, it seems the problem is due to the mismatch pth and model config.
