### ISSUE TITLE
[Bug] MMCVRoiAlign: could not find any supported formats consistent with input/output data types

### ISSUE THREAD

**Issue by tobymu** [open-mmlab/mmdeploy#1928]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

MMCVRoiAlign: could not find any supported formats consistent with input/output data types

### Reproduction

[onnx2trt_new.py.zip](https://github.com/open-mmlab/mmdeploy/files/11087038/onnx2trt_new.py.zip)

### Environment

```Shell
onnx.__version__   '1.10.1'
tensorrt.__version__  '8.2.3.0'
mmcv.__version__   '1.7.1'
Cuda compilation tools, release 11.3, V11.3.109
```

### Error traceback

```Shell
[03/28/2023-14:18:22] [TRT] [E] 9: [pluginV2Builder.cpp::reportPluginError::23] Error Code 9: Internal Error (MMCVRoiAlign783: could not find any supported formats consistent with input/output data types)
Traceback (most recent call last):
  File "onnx2trt_new.py", line 273, in <module>
    engine.building_engine()
  File "onnx2trt_new.py", line 230, in building_engine
    with builder.build_engine(network, config) as engine, open(self.trt_file, "wb") as f:
AttributeError: __enter__
```

**Comment by tobymu** [comment]
`ioDesc[pos].type:0 ioDesc[pos].format:0 nvinfer1::DataType::kFLOAT:0 nvinfer1::TensorFormat::kLINEAR:0
ioDesc[pos].type:0 ioDesc[pos].format:0 nvinfer1::DataType::kFLOAT:0 nvinfer1::TensorFormat::kLINEAR:0
ioDesc[pos].type:3 ioDesc[pos].format:0 nvinfer1::DataType::kFLOAT:0 nvinfer1::TensorFormat::kLINEAR:0
ioDesc[pos].type:0 ioDesc[pos].format:5 nvinfer1::DataType::kFLOAT:0 nvinfer1::TensorFormat::kLINEAR:0
[03/29/2023-11:08:07] [TRT] [E] 9: [pluginV2Builder.cpp::reportPluginError::23] Error Code 9: Internal Error (MMCVRoiAlign783: could not find any supported formats consistent with input/output data types)
`
I print the input / output data type in cpp. Confused.

**Comment by RunningLeon** [comment]
@tobymu Hi, pls make sure inputs are float32 type. You can refer to the [doc](https://mmdeploy.readthedocs.io/en/latest/06-custom-ops/tensorrt.html#id25) or the code https://github.com/open-mmlab/mmdeploy/blob/bbee83da6cb33e93cac46149842461c1230975e5/csrc/mmdeploy/backend_ops/tensorrt/roi_align/trt_roi_align.cpp#L59-L64

**Comment by tobymu** [comment]
> return

Thanks for reply. My inputs are FP32. You can check my python code. I'm not sure whether TRT changes the data type when fusion layers?

**Comment by tobymu** [comment]
@RunningLeon

**Comment by RunningLeon** [comment]
> ioDesc[pos].type:3
As the log suggested, type3 is not FP32.
Pls.  double check inputs of MMCVRoiAlign op in onnx.
