### ISSUE TITLE
[Bug] Can not use TensorRT sdk with mmaction2 model

### ISSUE THREAD

**Issue by aixiaodewugege** [open-mmlab/mmdeploy#1930]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Error is reported when using mmaction2 conveted TensroRT model sdk. 

### Reproduction

self.action_detector = VideoRecognizer(model_path='projects/mmyolo/mmdeploy_models/mmaction2/csn', device_name='cuda')

action = self.action_detector(video) 

# video shape (64, 480, 640, 3)

### Environment

```Shell
03/28 21:53:33 - mmengine - INFO - **********Environmental information**********
03/28 21:53:33 - mmengine - INFO - sys.platform: linux
03/28 21:53:33 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
03/28 21:53:33 - mmengine - INFO - CUDA available: True
03/28 21:53:33 - mmengine - INFO - numpy_random_seed: 2147483648
03/28 21:53:33 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3090
03/28 21:53:33 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
03/28 21:53:33 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.64
03/28 21:53:33 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
03/28 21:53:33 - mmengine - INFO - PyTorch: 1.13.1+cu117
03/28 21:53:33 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.8.1  (built against CUDA 11.8)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

03/28 21:53:33 - mmengine - INFO - TorchVision: 0.14.1+cu117
03/28 21:53:33 - mmengine - INFO - OpenCV: 4.5.5
03/28 21:53:33 - mmengine - INFO - MMEngine: 0.6.0
03/28 21:53:33 - mmengine - INFO - MMCV: 2.0.0rc4
03/28 21:53:33 - mmengine - INFO - MMCV Compiler: GCC 9.3
03/28 21:53:33 - mmengine - INFO - MMCV CUDA Compiler: 11.7
03/28 21:53:33 - mmengine - INFO - MMDeploy: 1.0.0rc3+032ce75
03/28 21:53:33 - mmengine - INFO - 

03/28 21:53:33 - mmengine - INFO - **********Backend information**********
03/28 21:53:33 - mmengine - INFO - tensorrt:    8.4.2.4
03/28 21:53:33 - mmengine - INFO - tensorrt custom ops: Available
03/28 21:53:33 - mmengine - INFO - ONNXRuntime: None
03/28 21:53:33 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
03/28 21:53:33 - mmengine - INFO - ONNXRuntime custom ops:      Available
03/28 21:53:33 - mmengine - INFO - pplnn:       None
03/28 21:53:33 - mmengine - INFO - ncnn:        None
03/28 21:53:33 - mmengine - INFO - snpe:        None
03/28 21:53:33 - mmengine - INFO - openvino:    2022.3.0
03/28 21:53:33 - mmengine - INFO - torchscript: 1.13.1
03/28 21:53:33 - mmengine - INFO - torchscript custom ops:      NotAvailable
03/28 21:53:33 - mmengine - INFO - rknn-toolkit:        None
03/28 21:53:33 - mmengine - INFO - rknn-toolkit2:       None
03/28 21:53:33 - mmengine - INFO - ascend:      None
03/28 21:53:33 - mmengine - INFO - coreml:      None
03/28 21:53:33 - mmengine - INFO - tvm: None
03/28 21:53:33 - mmengine - INFO - vacc:        None
03/28 21:53:33 - mmengine - INFO - 

03/28 21:53:33 - mmengine - INFO - **********Codebase information**********
03/28 21:53:33 - mmengine - INFO - mmdet:       3.0.0rc6
03/28 21:53:33 - mmengine - INFO - mmseg:       None
03/28 21:53:33 - mmengine - INFO - mmcls:       None
03/28 21:53:33 - mmengine - INFO - mmocr:       None
03/28 21:53:33 - mmengine - INFO - mmedit:      None
03/28 21:53:33 - mmengine - INFO - mmdet3d:     None
03/28 21:53:33 - mmengine - INFO - mmpose:      1.0.0rc1
03/28 21:53:33 - mmengine - INFO - mmrotate:    None
03/28 21:53:33 - mmengine - INFO - mmaction:    1.0.0rc3
03/28 21:53:33 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
Exception in thread human action recognition:
Traceback (most recent call last):
  File "/home/wushuchen/anaconda3/envs/open-mmyolo/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/wushuchen/PycharmProjects/mmpose_final/mmpose/mmpose/apis/webcam/nodes/node.py", line 396, in run
    output_msg = self.process(input_msgs)
  File "/home/wushuchen/PycharmProjects/mmpose_final/mmpose/mmpose/apis/webcam/nodes/model_nodes/action_recognition_node.py", line 248, in process
    action = self.action_detector(np.array(video))
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: mmdeploy_python.VideoRecognizer, arg0: List[numpy.ndarray[numpy.uint8]], arg1: Tuple[int, int]) -> List[Tuple[int, float]]

Invoked with: <mmdeploy_python.VideoRecognizer object at 0x7f9878ed5a30>, array([[[[ 16,  17,  15],
         [ 16,  17,  15],
         [ 14,  17,  15],
         ...,
         [138, 130, 120],
         [137, 129, 119],
         [138, 130, 120]],
```

**Comment by aixiaodewugege** [comment]
Thanks for your relpy! I tried your suggestion. But another error is reported. 

(open-mmyolo) wushuchen@wushuchen:~/PycharmProjects/mmpose_final$ python videorecognition.py 
[2023-03-29 11:06:57.971] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/wushuchen/projects/mmyolo/mmdeploy_models/mmaction2/csn"
32
[2023-03-29 11:06:58.798] [mmdeploy] [error] [trt_net.cpp:28] TRTNet: 3: [executionContext.cpp::setBindingDimensions::965] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::965, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [1,96,3,1,256,256] for bindings[0] exceed min ~ max range at index 1, maximum dimension in profile is 30, minimum dimension in profile is 30, but supplied dimension is 96.
)

I take a look at the my trt detail.json file, it is as follow. Is the conver not correct?

{
    "version": "1.0.0rc3",
    "codebase": {
        "task": "VideoRecognition",
        "codebase": "mmaction",
        "version": "1.0.0rc3",
        "pth": "/home/wushuchen/.cache/torch/hub/checkpoints/ircsn_ig65m_pretrained_bnfrozen_r152_32x2x1_58e_kinetics400_rgb_20200812-9037a758.pth",
        "config": "../mmaction2/configs/recognition/csn/ircsn_ig65m-pretrained-r152-bnfrozen_8xb12-32x2x1-58e_kinetics400-rgb.py"
    },
    "codebase_config": {
        "type": "mmaction",
        "task": "VideoRecognition"
    },
    "onnx_config": {
        "type": "onnx",
        "export_params": true,
        "keep_initializers_as_inputs": false,
        "opset_version": 11,
        "save_file": "end2end.onnx",
        "input_names": [
            "input"
        ],
        "output_names": [
            "output"
        ],
        "input_shape": [
            256,
            256
        ],
        "optimize": true
    },
    "backend_config": {
        "type": "tensorrt",
        "common_config": {
            "fp16_mode": false,
            "max_workspace_size": 1073741824
        },
        "model_inputs": [
            {
                "input_shapes": {
                    "input": {
                        "min_shape": [
                            1,
                            30,
                            3,
                            32,
                            256,
                            256
                        ],
                        "opt_shape": [
                            1,
                            30,
                            3,
                            32,
                            256,
                            256
                        ],
                        "max_shape": [
                            1,
                            30,
                            3,
                            32,
                            256,
                            256
                        ]
                    }
                }
            }
        ]
    },
    "calib_config": {}
}

**Comment by aixiaodewugege** [comment]
> I think it's better to take a look first at https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/python/video_recognition.py .
> 
> Currently, mmdeploy only support recognition task of mmaction2. If that suits for you, you can have a look at what is the input of `VideoRecognizer` and how the input is generated https://github.com/open-mmlab/mmdeploy/blob/dev-1.x/demo/python/video_recognition.py#L70-L73

**Comment by irexyc** [comment]
According to https://github.com/open-mmlab/mmaction2/blob/dev-1.x/configs/recognition/csn/ircsn_ig65m-pretrained-r152-bnfrozen_8xb12-32x2x1-58e_kinetics400-rgb.py#L55-L68, if only consider `SampleFrame` the input shape should be 1 x 10 x 3 x 32 x 256 x 256, along with `ThreeCrop` the shape should be 1 x 30 x 3 x 32 x 256 x 256. 

Please take a look at `SampleFrame` function https://github.com/open-mmlab/mmdeploy/blob/master/demo/python/video_recognition.py#L28

**Comment by aixiaodewugege** [comment]
Thanks I manger to have it worked with use ThreeCrop. But I am curious about is ThreeCrop necessary for the model inference? Or don't add it will affect the accuracy?

**Comment by irexyc** [comment]
I haven't test without `ThreeCrop`. You can test first with pytorch and determine whether to have it or replace it with `CenterCrop` when convert to tensorrt.

**Comment by aixiaodewugege** [comment]
Dose the sdk you supply already have ThreeCrop or other pre-process step in it? Do I need to add it before feed the data to sdk myself?

**Comment by irexyc** [comment]
The sdk have implemented `threecrop/tencrop/centercrop` and other common preprocess steps in it.

When you feed date to VideoRecognizer,  you need to process date like `SampleFrame`. function. The function is just example, it didn't consider every situation. For example, the videocapture may not get the number of video frame.

**Comment by aixiaodewugege** [comment]
Thanks for your reply! I have succeed using the mmaction2 trt sdk. However I found that the inference speed is much slower than the origin pytorch format.... I have reported a new issue. 

Could you please help me with it?

**Comment by irexyc** [comment]
Closed as new topic will be discussed in https://github.com/open-mmlab/mmdeploy/issues/1964
