### ISSUE TITLE
why set keep_ratio to False in process_model_config for mmseg

### ISSUE THREAD

**Issue by liuyunfeng2016** [open-mmlab/mmdeploy#195]
https://github.com/open-mmlab/mmdeploy/blob/34879e638cc2db511e798a376b9a4b9932660fe1/mmdeploy/codebase/mmseg/deploy/segmentation.py#L39
我在转换自己的训练的模型时，发现推理时这一行会将我的keep_ration=True的配置修改成False，这影响了我模型转换的推理结果！

**Comment by RunningLeon** [comment]
@liuyunfeng2016 Hi, it is used to make sure preprocessed image has same shape  as `input_shape` for conversion a model with static shape as `input_shape`. You could evaluate your model with tools/test.py: https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_evaluate_a_model.html.

**Comment by liuyunfeng2016** [comment]
> @liuyunfeng2016 Hi, it is used to make sure preprocessed image has same shape as `input_shape` for conversion a model with static shape as `input_shape`. There maybe be a problem if you use this process to do inference. And, you could evaluate your model with tools/test.py: https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_evaluate_a_model.html.
> 
> BTW, we strongly suggest to make an issue in **English**.

OK, Now I have a new question.
I find that the inference latency of my converted model is longer than that of the original pytorch model.
My environment configuration information is as follows:

**Comment by RunningLeon** [comment]
@liuyunfeng2016 Hi, 
1. speed test should be done with certain number of iterations and should exclude first N iterations.
2. For int8 conversion, you could refer to [how_to_convert_model](https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_convert_model.html) and use a deployment config with int8 such as `configs/mmdet/detection/detection_tensorrt-int8_dynamic-320x320-1344x1344.py`
3. Warnings of FP16 could be ignored since there are some int64 tensor in ONNX and there is no int64 in TensorRT, thus it would be converted to int32 automatically.

**Comment by liuyunfeng2016** [comment]
> @liuyunfeng2016你好，
> 
> 1. 速度测试应该用一定数量的迭代来完成，并且应该排除前 N 次迭代。
> 2. 对于 int8 转换，您可以参考[how_to_convert_model](https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_convert_model.html)并使用带有 int8 的部署配置，例如`configs/mmdet/detection/detection_tensorrt-int8_dynamic-320x320-1344x1344.py`
> 3. FP16 的警告可以忽略，因为 ONNX 中有一些 int64 张量，而 TensorRT 中没有 int64，因此它会自动转换为 int32。

Okay, you're right. Thanks for your help.

**Comment by liuyunfeng2016** [comment]
@RunningLeon 
hello，I have some new questions I'd like to ask you.
1.I have completed the conversion of the int8 model. Would model.half() take effect on the tensorrt model?
2.I find that the inference latency is faster after I half() input. Why?
![image](https://user-images.githubusercontent.com/21154156/156478494-d53bbfde-a73b-4601-8973-3e3c3899de79.png)
3.Half() corresponds to fp16 optimization. If this can be accelerated, is there an optimization operation for int8 or directly convert img to int8 input? Does the tensorrt model have the corresponding int8 operation?

**Comment by RunningLeon** [comment]
fixed in https://github.com/open-mmlab/mmdeploy/pull/199
