### ISSUE TITLE
an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，ModuleNotFoundError: No module named 'mmdeploy.apis'

### ISSUE THREAD

**Issue by likecv** [open-mmlab/mmdeploy#1955]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，ModuleNotFoundError: No module named 'mmdeploy.apis'

### Reproduction

an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，ModuleNotFoundError: No module named 'mmdeploy.apis'

### Environment

```Shell
an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，ModuleNotFoundError: No module named 'mmdeploy.apis'
```

### Error traceback

```Shell
an error occurred while converting the onnx model using mmdeploy/tools/deploy.py，ModuleNotFoundError: No module named 'mmdeploy.apis'
```

**Comment by likecv** [comment]
git clone --recursive https://github.com/open-mmlab/mmdeploy.git

**Comment by 6sz** [comment]
Hello, how did you solve this problem? Can re cloning the code repository solve the problem
