### ISSUE TITLE
[Feature] Extracting Feature Maps from Existing Object Detection Models

### ISSUE THREAD

**Issue by LukasFreudenmann** [open-mmlab/mmdeploy#1962]
### Motivation

Hello, I am currently working with TensorRT object detector models, specifically the Faster R-CNN models powered by the TensorRT engine. I am interested in obtaining feature maps from these models in addition to the already existing output of labels and bboxes. 
In particular, it is about the output of the [backbone+neck](https://github.com/open-mmlab/mmdetection/blob/9d3e162459590eee4cfc891218dfbb5878378842/mmdet/models/detectors/two_stage.py#L65)
But unfortunately there are no examples that address this issue.

I would greatly appreciate any guidance or suggestions on how to extract feature maps from TensorRT object detector models. Thank you for your assistance.

**Comment by RunningLeon** [comment]
@LukasFreudenmann hi, you could edit the onnx file and add new outputs manually. https://github.com/onnx/onnx/issues/3277

**Comment by qiaotian-huang** [comment]
Onnx models are all small ops, how to locate the output node of the feature?

**Comment by RunningLeon** [comment]
you could create a debug node in pytorch code and then convert the node to output node. Could refer to the zhihu tutorial https://zhuanlan.zhihu.com/p/543973749 and https://zhuanlan.zhihu.com/p/516920606
