### ISSUE TITLE
[Bug] CMake Error when compiling release v. 1.0.0

### ISSUE THREAD

**Issue by carminez88** [open-mmlab/mmdeploy#1968]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When setting up the CMake build for the latest release (v1.0.0), I receive the following error:

> Configuring done
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_execution" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_cpu_device" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_cuda_device" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_graph" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_directory_model" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_zip_model" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_operation" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_operation_cpu" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_operation_cuda" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_operation_dummy" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_transform" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_transform_module" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_net_module" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmcls" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmdet" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmseg" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmocr" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmedit" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmpose" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmrotate" that is not in any export set.
> CMake Error: install(EXPORT "MMDeployTargets" ...) includes target "mmdeploy" which requires target "mmdeploy_mmaction" that is not in any export set.
> Generating done

I have set the following build options:

![mmdeploy-cmake-options](https://user-images.githubusercontent.com/13303028/230589268-8858c09d-a871-40a4-b068-203eb0e099a1.PNG)

Using CMake 3.25.1.

### Reproduction

To reproduce:

- Download https://github.com/open-mmlab/mmdeploy/archive/refs/tags/v1.0.0.tar.gz
- Run CMake with the above compile options

### Environment

```Shell
04/07 12:03:32 - mmengine - INFO - **********Environmental information**********
04/07 12:03:33 - mmengine - INFO - sys.platform: linux
04/07 12:03:33 - mmengine - INFO - Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
04/07 12:03:33 - mmengine - INFO - CUDA available: True
04/07 12:03:33 - mmengine - INFO - numpy_random_seed: 2147483648
04/07 12:03:33 - mmengine - INFO - GPU 0,1,2,3: NVIDIA GeForce RTX 3090
04/07 12:03:33 - mmengine - INFO - CUDA_HOME: /software/cuda/
04/07 12:03:33 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.7, V11.7.99
04/07 12:03:33 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
04/07 12:03:33 - mmengine - INFO - PyTorch: 1.13.1
04/07 12:03:33 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

04/07 12:03:33 - mmengine - INFO - TorchVision: 0.14.1
04/07 12:03:33 - mmengine - INFO - OpenCV: 4.7.0
04/07 12:03:33 - mmengine - INFO - MMEngine: 0.7.0
04/07 12:03:33 - mmengine - INFO - MMCV: 2.0.0rc4
04/07 12:03:33 - mmengine - INFO - MMCV Compiler: GCC 9.3
04/07 12:03:33 - mmengine - INFO - MMCV CUDA Compiler: 11.7
04/07 12:03:33 - mmengine - INFO - MMDeploy: 1.0.0rc3+
04/07 12:03:33 - mmengine - INFO - 

04/07 12:03:33 - mmengine - INFO - **********Backend information**********
04/07 12:03:33 - mmengine - INFO - tensorrt:    8.5.3.1
04/07 12:03:33 - mmengine - INFO - tensorrt custom ops: Available
04/07 12:03:33 - mmengine - INFO - ONNXRuntime: None
04/07 12:03:33 - mmengine - INFO - ONNXRuntime-gpu:     1.14.1
04/07 12:03:33 - mmengine - INFO - ONNXRuntime custom ops:      Available
04/07 12:03:33 - mmengine - INFO - pplnn:       None
04/07 12:03:33 - mmengine - INFO - ncnn:        None
04/07 12:03:33 - mmengine - INFO - snpe:        None
04/07 12:03:33 - mmengine - INFO - openvino:    None
04/07 12:03:33 - mmengine - INFO - torchscript: 1.13.1
04/07 12:03:33 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/07 12:03:33 - mmengine - INFO - rknn-toolkit:        None
04/07 12:03:33 - mmengine - INFO - rknn-toolkit2:       None
04/07 12:03:33 - mmengine - INFO - ascend:      None
04/07 12:03:33 - mmengine - INFO - coreml:      None
04/07 12:03:33 - mmengine - INFO - tvm: None
04/07 12:03:33 - mmengine - INFO - 

04/07 12:03:33 - mmengine - INFO - **********Codebase information**********
04/07 12:03:33 - mmengine - INFO - mmdet:       3.0.0rc6
04/07 12:03:33 - mmengine - INFO - mmseg:       None
04/07 12:03:33 - mmengine - INFO - mmcls:       None
04/07 12:03:33 - mmengine - INFO - mmocr:       None
04/07 12:03:33 - mmengine - INFO - mmedit:      None
04/07 12:03:33 - mmengine - INFO - mmdet3d:     None
04/07 12:03:33 - mmengine - INFO - mmpose:      None
04/07 12:03:33 - mmengine - INFO - mmrotate:    None
04/07 12:03:33 - mmengine - INFO - mmaction:    None
```

**Comment by irexyc** [comment]
1. `-DMMDEPLOY_SHARED_LIBS=ON -DMMDEPLOY_BUILD_SDK_MONOLITHIC=OFF` 
will build a bunch of dynamic library, and shoud be used [this way](https://github.com/open-mmlab/mmdeploy/blob/main/demo/csrc/CMakeLists.txt#L22-L26)

2. `-DMMDEPLOY_SHARED_LIBS=OFF -DMMDEPLOY_BUILD_SDK_MONOLITHIC=ON` 
will build a single dynamic library (mmdeploy.so). And could only link [mmdeploy.so](https://github.com/open-mmlab/mmdeploy/blob/main/demo/csrc/CMakeLists.txt#L19-L21) when you use mmdeploy.

3. `-DMMDEPLOY_SHARED_LIBS=OFF -DMMDEPLOY_BUILD_SDK_MONOLITHIC=OFF` 
will build a bunch of static library, and shoud be used [this way](https://github.com/open-mmlab/mmdeploy/blob/main/demo/csrc/CMakeLists.txt#L22-L26)

**Comment by carminez88** [comment]
Ok, I tried with option 2 and in fact the cmake process now completes without errors.

But at build time, now I'm receveing link errors on the examples subproject:

> [ 96%] Linking CXX executable ../../bin/rotated_detector
> [ 97%] Linking CXX executable ../../bin/classifier
> ../../lib/libmmdeploy.so.0.13.0: undefined reference to `spdlog::logger::err_handler_(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> ../../lib/libmmdeploy.so.0.13.0: undefined reference to `spdlog::details::os::getenv[abi:cxx11](char const*)'
> ../../lib/libmmdeploy.so.0.13.0: undefined reference to `std::shared_ptr<spdlog::logger> spdlog::stdout_color_mt<spdlog::synchronous_factory>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, spdlog::color_mode)'
> ../../lib/libmmdeploy.so.0.13.0: undefined reference to `spdlog::cfg::helpers::load_levels(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> ../../lib/libmmdeploy.so.0.13.0: undefined reference to `fmt::v9::vformat[abi:cxx11](fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)'

I've using SPDLOG 1.11.0 from inside the **third_party/spdlog**, built as a static library.

**Comment by irexyc** [comment]
Are you first build spdlog yourself and then build mmdeploy with the built spdlog?

If so, you could try to compile mmdeploy and let mmdeploy build spdlog:
```
git clone --recursive https://github.com/open-mmlab/mmdeploy.git
cd mmdeploy
mkdir build
cd build
cmake .. -DMMDEPLOY_BUILD_SDK=ON   \
    -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
    -DMMDEPLOY_SHARED_LIBS=OFF \
    -DMMDEPLOY_BUILD_SDK_MONOLITHIC=ON \
    -DMMDEPLOY_BUILD_TEST=OFF \
    -DMMDEPLOY_TARGET_BACKENDS="trt" \
    -DMMDEPLOY_CODEBASES=all \
    -DTENSORRT_DIR=/opt/TensorRT-8.2.3.0 \
    -Dpplcv_DIR=/opt/ppl.cv/cuda-build/install/lib/cmake/ppl \
    -DCUDNN_DIR=/opt/cudnn-8.2.1 \
    -DOpenCV_DIR=/opt/opencv-4.5.5/build_static/install/lib/cmake/opencv4 \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_DYNAMIC_BACKEND=ON \
    -DMMDEPLOY_SPDLOG_EXTERNAL=OFF

make -j8
```

**Comment by carminez88** [comment]
Yes, this is exactly what I was trying to do.

- Download https://github.com/open-mmlab/mmdeploy/archive/refs/tags/v1.0.0.tar.gz
- Download https://github.com/gabime/spdlog/archive/refs/tags/v1.11.0.tar.gz
- Extract the content of SPDLOG 1.11.0 and copy it into _mmdeploy-1.0.0/third_party/spdlog/_
- Configure CMake with -DMMDEPLOY_SPDLOG_EXTERNAL=OFF (SPDLOG as static library)
- Execute build

Everything seems going well until the link time as the examples fail to link. The error is the one I shared previously.

**Comment by irexyc** [comment]
I can't reproduce your error on my pc and have no clue what caused it. 

The `libmmdeploy.so` should contains the symbols of spdlog.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/16019484/230629280-e717fa00-a5d4-4f56-9f6a-e60755e474c7.png">

You may try to remove the build folder before configure the project. If it doesn't help, you could use our [prebuid package](https://github.com/open-mmlab/mmdeploy/releases/tag/v1.0.0) or use [docker](https://hub.docker.com/layers/openmmlab/mmdeploy/ubuntu20.04-cuda11.3-mmdeploy1.0.0rc2/images/sha256-7d72b3998cda05f8fc2edf4ee4e94b9cc816d58ae2cbe9c39c7dfe57ce0b4309?context=explore) to build it.

**Comment by carminez88** [comment]
Thanks for trying. I tried with your command but unfortunately I don't see those symbols in `libmmdeploy.so` . So I suspect it is kind of an issue with Kubuntu 18.04 and its GCC version (7.5).

I cannot use docker nor prebuild packages as I am strictly bounded to CUDA 11.7.

**Comment by irexyc** [comment]
The library should be compatibility since they all link to libcudart.so.11.0. Or you can build a docker yourself (ubuntu base)

You can also try not to build example when you build mmdeploy, and when build examples, try to link libsdplog.a manually （not sure if this could work)
