### ISSUE TITLE
Include NMS in Engine

### ISSUE THREAD

**Issue by KleinYuan** [open-mmlab/mmdeploy#1969]
### Motivation

I’m using mmdeploy to compile the detection models without problem. One challenge is that the NMS is not part of the engine. I will have to do it in Python which can be slow… 

I wonder whether there is a way to include that? Compile the engine with NMS included.

**Comment by irexyc** [comment]
Hi, @KleinYuan What is your convertion command? The nms should be contained in the model.

**Comment by KleinYuan** [comment]
Hi @irexyc , my command is a standard one:

```
>> python mmdeploy/tools/deploy.py    mmdeploy/configs/mmdet/detection/detection_tensorrt-fp16_dynamic-320x320-1344x1344.py  mmdetection/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person.py  mmdetection/data//test/test.pth   mmdetection/data/test.png     --work-dir mmdetection/data/test   --device cuda    --dump-info
```

which yields both onnx and engine. When I check the onnx with https://netron.app/, I already do not see nms anywhere.

**Comment by irexyc** [comment]
Are you looking for TRTBatchedNMS？


<img width="891" alt="image" src="https://user-images.githubusercontent.com/16019484/231046526-a1a3148b-3a0a-4528-a6dd-9715ade5b2f9.png">
