### ISSUE TITLE
[Bug]  Run in androrid adb throw a error terminating with uncaught exception of type system_error2::status_error<mmdeploy::StatusDomain>: unknown (6) Aborted

### ISSUE THREAD

**Issue by tomjeans** [open-mmlab/mmdeploy#1984]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I have compiled this program mmdeploy examples! aftet convert model .pth by using python3 /tools/deploy 
=============================================================
python3 deploy.py     /mnt/h/mmdeploy/configs/mmpose/pose-detection_ncnn_static-256x192.py     /mnt/h/mmpose/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-m_8xb256-420e_coco-256x192.py     ./rtmpose-tiny_simcc-aic-coco_pt-aic-coco_420e-256x192-cfc8f33d_2023012.pth     /mnt/h/mmdeploy/demo/resources/human-pose.jpg     --work-dir mmdeploy_models/mmpose/ort     --device cpu     --show--dump-info
=============================================================
python3 deploy.py     /mnt/h/mmdeploy/configs/mmdet/detection/single-stage_ncnn_static-320x320.py     /mnt/h/mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py     ./rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth     /mnt/h/mmdeploy/demo/resources/human-pose.jpg     --work-dir mmdeploy_models/mmdet/ort     --device cpu     --show --dump-info
=============================================================
the mode output path is
![image](https://user-images.githubusercontent.com/37204571/231442174-4f9f6086-3534-4c38-b57f-146c1a0ee31c.png)
![image](https://user-images.githubusercontent.com/37204571/231442591-a22da013-45cb-473f-9c06-ee130dc97ba1.png)
=============================================================
A error happed while I run 
![image](https://user-images.githubusercontent.com/37204571/231442999-dbcc2740-e8d0-4aae-919e-e0823bd4de22.png)

### Reproduction

./det_pose ./mmdet/ort/ ./mmpose/ort/ 1.jpg

### Environment

```Shell
04/12 19:26:13 - mmengine - INFO -

04/12 19:26:13 - mmengine - INFO - **********Environmental information**********
04/12 19:26:14 - mmengine - INFO - sys.platform: linux
04/12 19:26:14 - mmengine - INFO - Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
04/12 19:26:14 - mmengine - INFO - CUDA available: False
04/12 19:26:14 - mmengine - INFO - numpy_random_seed: 2147483648
04/12 19:26:14 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
04/12 19:26:14 - mmengine - INFO - PyTorch: 2.0.0+cpu
04/12 19:26:14 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

04/12 19:26:14 - mmengine - INFO - TorchVision: 0.15.1+cpu
04/12 19:26:14 - mmengine - INFO - OpenCV: 4.7.0
04/12 19:26:14 - mmengine - INFO - MMEngine: 0.7.2
04/12 19:26:14 - mmengine - INFO - MMCV: 2.0.0
04/12 19:26:14 - mmengine - INFO - MMCV Compiler: GCC 7.3
04/12 19:26:14 - mmengine - INFO - MMCV CUDA Compiler: not available
04/12 19:26:14 - mmengine - INFO - MMDeploy: 1.0.0+
04/12 19:26:14 - mmengine - INFO -

04/12 19:26:14 - mmengine - INFO - **********Backend information**********
04/12 19:26:14 - mmengine - INFO - tensorrt:    None
04/12 19:26:15 - mmengine - INFO - ONNXRuntime: 1.8.1
04/12 19:26:15 - mmengine - INFO - ONNXRuntime-gpu:     None
04/12 19:26:15 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
04/12 19:26:15 - mmengine - INFO - pplnn:       None
04/12 19:26:15 - mmengine - INFO - ncnn:        None
04/12 19:26:15 - mmengine - INFO - snpe:        None
04/12 19:26:15 - mmengine - INFO - openvino:    None
04/12 19:26:15 - mmengine - INFO - torchscript: 2.0.0+cpu
04/12 19:26:15 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/12 19:26:15 - mmengine - INFO - rknn-toolkit:        None
04/12 19:26:15 - mmengine - INFO - rknn-toolkit2:       None
04/12 19:26:15 - mmengine - INFO - ascend:      None
04/12 19:26:15 - mmengine - INFO - coreml:      None
04/12 19:26:15 - mmengine - INFO - tvm: None
04/12 19:26:15 - mmengine - INFO - vacc:        None
04/12 19:26:15 - mmengine - INFO -

04/12 19:26:15 - mmengine - INFO - **********Codebase information**********
04/12 19:26:15 - mmengine - INFO - mmdet:       3.0.0
04/12 19:26:15 - mmengine - INFO - mmseg:       None
04/12 19:26:15 - mmengine - INFO - mmcls:       None
04/12 19:26:15 - mmengine - INFO - mmocr:       None
04/12 19:26:15 - mmengine - INFO - mmedit:      None
04/12 19:26:15 - mmengine - INFO - mmdet3d:     None
04/12 19:26:15 - mmengine - INFO - mmpose:      1.0.0
04/12 19:26:15 - mmengine - INFO - mmrotate:    None
04/12 19:26:15 - mmengine - INFO - mmaction:    None
04/12 19:26:15 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
terminating with uncaught exception of type system_error2::status_error<mmdeploy::StatusDomain>: unknown (6)
Aborted
```

**Comment by irexyc** [comment]
For rtmpose, please use `configs/mmpose/pose-detection_simcc_ncnn_static-256x192.py` config.

**Comment by tomjeans** [comment]
> For rtmpose, please use `configs/mmpose/pose-detection_simcc_ncnn_static-256x192.py` config.

Thanks! I can run and get the results using the config,however the body keypoints looks like the wrong positon,how to work correctly?
![image](https://user-images.githubusercontent.com/37204571/231628555-64aea4c7-5e08-4283-916b-e383f8db6280.png)

**Comment by irexyc** [comment]
Can you make a screenshot and feed the screenshot to the pytorch model to confirm your pytorch model can inference correctly?

If so, you could supply your model (if you trained yourself), model config and the bug image so that I can reproduce.

**Comment by tomjeans** [comment]
![image](https://user-images.githubusercontent.com/37204571/231638819-af1c5f2a-5512-4094-9b4e-5a88ddf970a4.png)
I download this model to convert ncnn deploy model!
Could you prioved the right ncnn backend deploy model runing?thanks

**Comment by tomjeans** [comment]
Thank you so much! after converting the rtmpose by the suitable config! The good points shows the image.
![image](https://user-images.githubusercontent.com/37204571/231719352-7f241bb6-0308-435d-bbd6-38a1113b5660.png)
