### ISSUE TITLE
[Feature] How to convert the model to remove the nms operation

### ISSUE THREAD

**Issue by baiguosummer** [open-mmlab/mmdeploy#1985]
### Motivation

When using mmdeploy to convert the model, I want to keep only the onnx file, and I don't want to add nms-related model post-processing operations to the onnx or engine model. How should I modify it?

### Related resources

this is mmyolo/configs/deploy/base_static.py
onnx_config = dict(
    type='onnx',
    export_params=True,
    keep_initializers_as_inputs=False,
    opset_version=11,
    save_file='end2end.onnx',
    input_names=['input'],
    output_names=['dets', 'labels'],
    # input_names=['images'],
    # output_names=['output'],
    input_shape=None,
    optimize=True)
codebase_config = dict(
    type='mmyolo',
    task='ObjectDetection',
    model_type='end2end',
    post_processing=dict(
        score_threshold=0.05,
        confidence_threshold=0.005,
        iou_threshold=0.5,
        max_output_boxes_per_class=200,
        pre_top_k=5000,
        keep_top_k=100,
        background_label_id=-1),
    module=['mmyolo.deploy'])

**Comment by RunningLeon** [comment]
@baiguosummer Hi, you could create marker nodes and get splitted onnx files. Pls. refer to https://mmdeploy.readthedocs.io/en/latest/07-developer-guide/partition_model.html
