### ISSUE TITLE
[Bug] mask rcnn tensorrt c++ API opencv 裁剪后的图片 输入无结果，但是 clone() 后，再输入就有结果了。

### ISSUE THREAD

**Issue by 1095788063** [open-mmlab/mmdeploy#2000]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

mask rcnn tensorrt c++ API opencv 裁剪后的图片 输入无结果，但是 clone() 后，再输入就有结果了。
这个问题，我去年就发现了。
![image](https://user-images.githubusercontent.com/29217820/232651613-fc41842c-7398-4fc5-815e-9c03d78db47e.png)

### Reproduction

  //原图输入
  mmdeploy_mat_t mat1{ img.data, img.rows, img.cols, 3, MMDEPLOY_PIXEL_FORMAT_BGR, MMDEPLOY_DATA_TYPE_UINT8 };
  mmdeploy_detection_t* bboxes1{};
  int* res_count1{};
  status = mmdeploy_detector_apply(detector, &mat1, 1, &bboxes1, &res_count1);
  if (status != MMDEPLOY_SUCCESS) {
      fprintf(stderr, "failed to apply detector, code: %d\n", (int)status);
      return 1;
  }
  fprintf(stdout, "原图 bbox_count=%d\n", *res_count1);

  //裁剪 指定的区域 内边距 - 5 px
  cv::Mat mat2 = img(cv::Rect(5,5, img.cols-10, img.rows - 10));//裁剪图片
  mmdeploy_mat_t mat{ mat2.data, mat2.rows, mat2.cols, 3, MMDEPLOY_PIXEL_FORMAT_BGR, MMDEPLOY_DATA_TYPE_UINT8};
  mmdeploy_detection_t* bboxes{};
  int* res_count{};
  status = mmdeploy_detector_apply(detector, &mat, 1, &bboxes, &res_count);
  if (status != MMDEPLOY_SUCCESS) {
    fprintf(stderr, "failed to apply detector, code: %d\n", (int)status);
    return 1;
  }
  fprintf(stdout, "裁剪图片 bbox_count=%d\n", *res_count);

  //clone 一份裁剪后的图片
  cv::Mat matclone = mat2.clone();
  mmdeploy_mat_t mat3{ matclone.data, matclone.rows, matclone.cols, 3, MMDEPLOY_PIXEL_FORMAT_BGR, MMDEPLOY_DATA_TYPE_UINT8 };
  mmdeploy_detection_t* bboxes2{};
  int* res_count2{};
  status = mmdeploy_detector_apply(detector, &mat3, 1, &bboxes2, &res_count2);
  if (status != MMDEPLOY_SUCCESS) {
      fprintf(stderr, "failed to apply detector, code: %d\n", (int)status);
      return 1;
  }
  fprintf(stdout, "裁剪图片clone bbox_count=%d\n", *res_count2);

### Environment

```Shell
D:\Python\Python38\python.exe D:\ayjdata\Code\Deep_learning\OpenMMLab\mmdeploy\mmdeploy-1.0.0-2023-04-17\tools\check_env.py 
04/18 10:09:29 - mmengine - INFO - 

04/18 10:09:29 - mmengine - INFO - **********Environmental information**********
04/18 10:09:32 - mmengine - INFO - sys.platform: win32
04/18 10:09:32 - mmengine - INFO - Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
04/18 10:09:32 - mmengine - INFO - CUDA available: True
04/18 10:09:32 - mmengine - INFO - numpy_random_seed: 2147483648
04/18 10:09:32 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3060
04/18 10:09:32 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
04/18 10:09:32 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
04/18 10:09:32 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30148 版
04/18 10:09:32 - mmengine - INFO - GCC: n/a
04/18 10:09:32 - mmengine - INFO - PyTorch: 1.11.0+cu113
04/18 10:09:32 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

04/18 10:09:32 - mmengine - INFO - TorchVision: 0.12.0+cu113
04/18 10:09:32 - mmengine - INFO - OpenCV: 4.5.5
04/18 10:09:32 - mmengine - INFO - MMEngine: 0.7.2
04/18 10:09:32 - mmengine - INFO - MMCV: 2.0.0
04/18 10:09:32 - mmengine - INFO - MMCV Compiler: MSVC 192829924
04/18 10:09:32 - mmengine - INFO - MMCV CUDA Compiler: 11.3
04/18 10:09:32 - mmengine - INFO - MMDeploy: 1.0.0+
04/18 10:09:32 - mmengine - INFO - 

04/18 10:09:32 - mmengine - INFO - **********Backend information**********
04/18 10:09:32 - mmengine - INFO - tensorrt:	8.4.3.1
04/18 10:09:32 - mmengine - INFO - tensorrt custom ops:	Available
04/18 10:09:33 - mmengine - INFO - ONNXRuntime:	1.8.1
04/18 10:09:33 - mmengine - INFO - ONNXRuntime-gpu:	None
04/18 10:09:33 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
04/18 10:09:33 - mmengine - INFO - pplnn:	None
04/18 10:09:33 - mmengine - INFO - ncnn:	None
04/18 10:09:33 - mmengine - INFO - snpe:	None
04/18 10:09:33 - mmengine - INFO - openvino:	None
04/18 10:09:33 - mmengine - INFO - torchscript:	1.11.0+cu113
04/18 10:09:33 - mmengine - INFO - torchscript custom ops:	NotAvailable
04/18 10:09:33 - mmengine - INFO - rknn-toolkit:	None
04/18 10:09:33 - mmengine - INFO - rknn-toolkit2:	None
04/18 10:09:33 - mmengine - INFO - ascend:	None
04/18 10:09:33 - mmengine - INFO - coreml:	None
04/18 10:09:33 - mmengine - INFO - tvm:	None
04/18 10:09:33 - mmengine - INFO - vacc:	None
04/18 10:09:33 - mmengine - INFO - 

04/18 10:09:33 - mmengine - INFO - **********Codebase information**********
04/18 10:09:33 - mmengine - INFO - mmdet:	3.0.0
04/18 10:09:33 - mmengine - INFO - mmseg:	None
04/18 10:09:33 - mmengine - INFO - mmcls:	None
04/18 10:09:33 - mmengine - INFO - mmocr:	None
04/18 10:09:33 - mmengine - INFO - mmedit:	None
04/18 10:09:33 - mmengine - INFO - mmdet3d:	None
04/18 10:09:33 - mmengine - INFO - mmpose:	None
04/18 10:09:33 - mmengine - INFO - mmrotate:	None
04/18 10:09:33 - mmengine - INFO - mmaction:	None
04/18 10:09:33 - mmengine - INFO - mmrazor:	None

进程已结束,退出代码0
```

**Comment by 1095788063** [comment]
测试的图片
![img_rgb](https://user-images.githubusercontent.com/29217820/232651869-423e0ad3-dad9-477a-b5a0-daaed8482a03.jpg)

**Comment by 1095788063** [comment]
正确的检测结果是：
![output_detection](https://user-images.githubusercontent.com/29217820/232652091-530443d4-101e-4ec5-b617-38956f7b6f29.png)

**Comment by irexyc** [comment]
The result is as expected.

The mat data you feed to the network should be continous. While if you only crop the image, the data isn't continous.

You can refer to [opencv docs](https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#aa90cea495029c7d1ee0a41361ccecdf3)

**Comment by 1095788063** [comment]
> The result is as expected.
> 
> The mat data you feed to the network should be continous. While if you only crop the image, the data isn't continous.
> 
> You can refer to [opencv docs](https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#aa90cea495029c7d1ee0a41361ccecdf3)

除了clone() 这个方法还有其他的解决方法吗？

**Comment by irexyc** [comment]
The key point is to make the image data continous.

If you don't want to use `clone` method, you can edit `transforms` in `pipeline.json`. Insert `CenterCrop` in the appropriate place as you actually made a center crop to the input image. If the pipeline.json already have a `CenterCrop`, you may edit the `crop_size` to merge these two crop operations.

**Comment by 1095788063** [comment]
> The key point is to make the image data continous.
> 
> If you don't want to use `clone` method, you can edit `transforms` in `pipeline.json`. Insert `CenterCrop` in the appropriate place as you actually made a center crop to the input image. If the pipeline.json already have a `CenterCrop`, you may edit the `crop_size` to merge these two crop operations.

好的，谢谢
