### ISSUE TITLE
[Bug] create detector using cuda error

### ISSUE THREAD

**Issue by yuanjincai** [open-mmlab/mmdeploy#2007]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

from mmdeploy_runtime import Detector
import cv2

# 读取图片
img = cv2.imread('../mmdetection/demo/demo.jpg')

# 创建检测器
detector = Detector(model_path='../mmdeploy_models/faster-rcnn', device_name='cuda', device_id=0)
# 执行推理
bboxes, labels, _ = detector(img)
# 使用阈值过滤推理结果，并绘制到原图中
indices = [i for i in range(len(bboxes))]
for index, bbox, label_id in zip(indices, bboxes, labels):
  [left, top, right, bottom], score = bbox[0:4].astype(int),  bbox[4]
  if score < 0.3:
      continue
  cv2.rectangle(img, (left, top), (right, bottom), (0, 255, 0))

cv2.imwrite('output_detection.png', img)

loading libmmdeploy_ort_net.so ...
Traceback (most recent call last):
  File "/home/tieren/model_deploy_test/test_model3.py", line 8, in <module>
    detector = Detector(model_path='../mmdeploy_models/faster-rcnn', device_name='cuda', device_id=0)
RuntimeError: failed to create detector
[2023-04-19 15:47:38.872] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "../mmdeploy_models/faster-rcnn"
[2023-04-19 15:47:38.872] [mmdeploy] [error] [common.cpp:67] Device "cuda" not found

### Reproduction

../anaconda3/envs/yjcmmlab/bin/python example/python/object_detection.py cuda ../mmdeploy_models/faster-rcnn ../mmdetection/demo/demo.jpg
loading libmmdeploy_ort_net.so ...
[2023-04-19 15:52:39.406] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "../mmdeploy_models/faster-rcnn"
[2023-04-19 15:52:39.407] [mmdeploy] [error] [common.cpp:67] Device "cuda" not found
Traceback (most recent call last):
  File "example/python/object_detection.py", line 51, in <module>
    main()
  File "example/python/object_detection.py", line 25, in main
    detector = Detector(
RuntimeError: failed to create detector

this is an example in mmdeploy-1.0.0-linux-x86_64-cuda11.3

### Environment

```Shell
./anaconda3/envs/yjcmmlab/bin/python mmdeploy/tools/check_env.py

04/19 15:54:02 - mmengine - INFO - 

04/19 15:54:02 - mmengine - INFO - **********Environmental information**********
04/19 15:54:03 - mmengine - INFO - sys.platform: linux
04/19 15:54:03 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
04/19 15:54:03 - mmengine - INFO - CUDA available: True
04/19 15:54:03 - mmengine - INFO - numpy_random_seed: 2147483648
04/19 15:54:03 - mmengine - INFO - GPU 0: Quadro RTX 5000
04/19 15:54:03 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
04/19 15:54:03 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
04/19 15:54:03 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
04/19 15:54:03 - mmengine - INFO - PyTorch: 1.13.1
04/19 15:54:03 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

04/19 15:54:03 - mmengine - INFO - TorchVision: 0.14.1
04/19 15:54:03 - mmengine - INFO - OpenCV: 4.7.0
04/19 15:54:03 - mmengine - INFO - MMEngine: 0.7.2
04/19 15:54:03 - mmengine - INFO - MMCV: 2.0.0
04/19 15:54:03 - mmengine - INFO - MMCV Compiler: GCC 9.3
04/19 15:54:03 - mmengine - INFO - MMCV CUDA Compiler: 11.6
04/19 15:54:03 - mmengine - INFO - MMDeploy: 1.0.0+
04/19 15:54:03 - mmengine - INFO - 

04/19 15:54:03 - mmengine - INFO - **********Backend information**********
04/19 15:54:03 - mmengine - INFO - tensorrt:    8.2.3.0
04/19 15:54:03 - mmengine - INFO - tensorrt custom ops: Available
04/19 15:54:03 - mmengine - INFO - ONNXRuntime: 1.8.1
04/19 15:54:03 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
04/19 15:54:03 - mmengine - INFO - ONNXRuntime custom ops:      Available
04/19 15:54:03 - mmengine - INFO - pplnn:       None
04/19 15:54:03 - mmengine - INFO - ncnn:        None
04/19 15:54:03 - mmengine - INFO - snpe:        None
04/19 15:54:03 - mmengine - INFO - openvino:    None
04/19 15:54:03 - mmengine - INFO - torchscript: 1.13.1
04/19 15:54:03 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/19 15:54:03 - mmengine - INFO - rknn-toolkit:        None
04/19 15:54:03 - mmengine - INFO - rknn-toolkit2:       None
04/19 15:54:03 - mmengine - INFO - ascend:      None
04/19 15:54:03 - mmengine - INFO - coreml:      None
04/19 15:54:03 - mmengine - INFO - tvm: None
04/19 15:54:03 - mmengine - INFO - vacc:        None
04/19 15:54:03 - mmengine - INFO - 

04/19 15:54:03 - mmengine - INFO - **********Codebase information**********
04/19 15:54:03 - mmengine - INFO - mmdet:       3.0.0
04/19 15:54:03 - mmengine - INFO - mmseg:       None
04/19 15:54:03 - mmengine - INFO - mmcls:       None
04/19 15:54:03 - mmengine - INFO - mmocr:       None
04/19 15:54:03 - mmengine - INFO - mmedit:      None
04/19 15:54:03 - mmengine - INFO - mmdet3d:     None
04/19 15:54:03 - mmengine - INFO - mmpose:      None
04/19 15:54:03 - mmengine - INFO - mmrotate:    None
04/19 15:54:03 - mmengine - INFO - mmaction:    None
04/19 15:54:03 - mmengine - INFO - mmrazor:     None

i install pytorch by conda
$PATH:
-bash: /home/tieren/bin:/home/tieren/anaconda3/envs/yjcmmlab/bin:/home/tieren/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin: 没有那个文件或目录
$LD_LIBRARY_PATH
-bash: /home/tieren/onnxruntime-linux-x64-gpu-1.8.1/lib:/home/tieren/TensorRT-8.2.3.0/lib:/home/tieren/mmdeploy-1.0.0rc0-linux-x86_64-cuda11.3-tensorrt8.2.3.0/sdk/lib:/usr/lib:/usr/local/cuda/lib64: 没有那个文件或目录
```

**Comment by irexyc** [comment]
It seems you installed `mmdeploy-runtime`(which support onnxruntime cpu) instead of `mmdeploy-runtime-gpu` (which support onnxruntime gpu and tensorrt)

What backend is your model `/mmdeploy_models/faster-rcnn` ? If it's a onnxruntime model, you need to pass `cpu` backend. If it's tensorrt model, you shou install `mmdeploy-runtime-gpu`

**Comment by yuanjincai** [comment]
thank you ,
first  i installed both mmdeploy-runtime and mmdeploy-runtime-gpu ,but they have some conflict。
second， net backendwrong is wrong
2023-04-19 18:19:52.621] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "../mmdeploy_model_gpu/faster-rcnn"
[2023-04-19 18:19:52.704] [mmdeploy] [error] [net_module.cpp:47] Net backend not found: tensorrt, available backends: [("onnxruntime", 0)]
[2023-04-19 18:19:52.705] [mmdeploy] [error] [task.cpp:99] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "fasterrcnn",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}

**Comment by LLH-Harward** [comment]
Same problem. Have you solve that?
