### ISSUE TITLE
Problems Related to the ONNX Model

### ISSUE THREAD

**Issue by likecv** [open-mmlab/mmdeploy#2009]
### 📚 The doc issue

How to know the model input shape and input names of the original detection model, look forward to your answer.

**Comment by irexyc** [comment]
They are defined in deploy config file.

You can refer to this docs:
https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/get_started.md
https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/02-how-to-run/convert_model.md

**Comment by likecv** [comment]
MMDetection contains some instance segmentation models. During online inference, the model output contains three parts: bboxes, labels, and masks. An error occurs when the detection configuration file of mmdeploy is used to convert the ONNX model to the ONNX model, and the masks are missing in output_names.

**Comment by likecv** [comment]
I think the configuration files in the mmdeploy are not fully adapted to mainstream detection models, right?

**Comment by irexyc** [comment]
> MMDetection contains some instance segmentation models. During online inference, the model output contains three parts: bboxes, labels, and masks. An error occurs when the detection configuration file of mmdeploy is used to convert the ONNX model to the ONNX model, and the masks are missing in output_names.

For mmdetection model, there exists two kind of config, `detection` config and `instance-seg` configs. I think what you wnat is `instance-seg` config which contains three output (bboxes, labels, masks).

https://github.com/open-mmlab/mmdeploy/tree/main/configs/mmdet

**Comment by likecv** [comment]
> > MMDetection contains some instance segmentation models. During online inference, the model output contains three parts: bboxes, labels, and masks. An error occurs when the detection configuration file of mmdeploy is used to convert the ONNX model to the ONNX model, and the masks are missing in output_names.
> 
> For mmdetection model, there exists two kind of config, `detection` config and `instance-seg` configs. I think what you want is `instance-seg` config which contains three output (bboxes, labels, masks).
> 
> https://github.com/open-mmlab/mmdeploy/tree/main/configs/mmdet

Hello, I would like to convert the PTH model of Mask RCNN to ONNX. Can you recommend the configuration file for mmdeploy?

>

**Comment by likecv** [comment]
Hello, I would like to convert the PTH model of Mask RCNN to ONNX. Can you recommend the configuration file for mmdeploy?

**Comment by irexyc** [comment]
@likecv 

It depends on your inputs, if your input is always with same shape for examle 512 x 512, you can use `configs/mmdet/instance-seg/instance-seg_onnxruntime_static.py` with a image of shape 512 x 512 when you convert the model. If you input is not stable, you can use `configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py`
