### ISSUE TITLE
[Docs] cannot import name 'to_backend' from 'mmdeploy.apis.utils'

### ISSUE THREAD

**Issue by xu19971109** [open-mmlab/mmdeploy#2011]
# cannot import name 'to_backend' from 'mmdeploy.apis.utils'
First, I followed [mmdet 3.0](https://mmdetection.readthedocs.io/zh_CN/latest/get_started.html) to install mmdetection.
Then, I followed [mmdeploy install](https://mmdeploy.readthedocs.io/zh_CN/1.x/get_started.html#mmdeploy) to install mmdeploy. 
I followed **[Linux-x86_64, CPU, onnx Runtime 1.8.1](https://mmdeploy.readthedocs.io/zh_CN/1.x/get_started.html#mmdeploy)** all the commands to install mmdeploy. And make sure that each of the commands is executed successfully!
Last, I try the demo of [Convert Model](https://mmdeploy.readthedocs.io/zh_CN/1.x/get_started.html#id4), but a problem is appear:
`File "mmdeploy/tools/deploy.py", line 23, in <module>
    from mmdeploy.apis.utils import to_backend
ImportError: cannot import name 'to_backend' from 'mmdeploy.apis.utils' (/opt/conda/lib/python3.8/site-packages/mmdeploy/apis/utils/__init__.py)`

The path of my dir is like:
rootpath/mmdeploy
rootpath/mmdedetection
rootpath/mmcv
rootpath/mmengine
rootpath/mmdeploy-1.0.0rc0-linux-x86_64-onnxruntime1.8.1

I run the command of `convert model` in **rootpath**.

How do I fix the problem? I try to add Path and ROOT in the top of mmdeploy/tools/deploy.py but doesn't work!

And today I find your Chinese doc and English doc is different in cloning the mmdeploy.
`git clone --recursive https://github.com/open-mmlab/mmdeploy.git `
`git clone -b dev-1.x https://github.com/open-mmlab/mmdeploy.git`
Does the clone of mmdeploy cause the problem?

Thank you very much!

**Comment by xu19971109** [comment]
I solved the problem by following #98
cd mmdeploy  
pip install -e . build
I hope you can add the commad on your doc! Thank you!

**Comment by xu19971109** [comment]
Another little bug:
In your Chinese doc:[ convert model](https://mmdeploy.readthedocs.io/zh_CN/1.x/get_started.html#id4) is 
`mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py`
but in your English doc, [convert model](mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py) is 
`mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py`
Actually, it is `mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py`, your Chinese doc is wrong.

**Comment by RunningLeon** [comment]
> Another little bug: In your Chinese doc:[ convert model](https://mmdeploy.readthedocs.io/zh_CN/1.x/get_started.html#id4) is `mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py` but in your English doc, [convert model](mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py) is `mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py` Actually, it is `mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py`, your Chinese doc is wrong.

@xu19971109 hi, thanks for your feedback. Could offer us a PR to fix it ?
