### ISSUE TITLE
[Bug] No module named 'mmdeploy_runtime'

### ISSUE THREAD

**Issue by Josh1021** [open-mmlab/mmdeploy#2019]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

1. on ubuntu, i builded mmdeploy from docker, and i work well.
2. on windows10, 64bit, AMD, i builded mmdeploy=0.14.0, from source, and got end2end.onnx,
i want to infer on windows by onnxruntime-gpu, so i install onnxruntime-win-gpu-x64-1.8.1, 
but when i run " python .\mmdeploy\demo\python\object_detection.py cuda D:\project\mmdeploy_model\cascade_rcnn D:\project\mmdetection\demo\demo.jpg " , got error"No module named 'mmdeploy_runtime'",

### Reproduction

1. command 
` python .\mmdeploy\demo\python\object_detection.py cuda D:\project\mmdeploy_model\cascade_rcnn D:\project\mmdetection\demo\demo.jpg `
3. this is build command 
` cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 
     -DMMDEPLOY_BUILD_SDK=ON 
     -DMMDEPLOY_BUILD_EXAMPLES=ON 
     -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON 
     -DMMDEPLOY_TARGET_DEVICES="cuda" 
     -DMMDEPLOY_TARGET_BACKENDS="ort" 
     -DONNXRUNTIME_DIR="$env:ONNXRUNTIME_DIR" 
     -Dpplcv_DIR="$env:PPLCV_DIR/pplcv-build/install/lib/cmake/ppl" 
     -DMMDEPLOY_BUILD_EXAMPLES=ON 
     -DMMDEPLOY_BUILD_TEST=ON `

### Environment

```Shell
1. (mmdeploy0.14.0) PS D:\project\mmdeploy> python tools/check_env.py
2023-04-23 15:34:03,662 - mmdeploy - INFO -

2023-04-23 15:34:03,662 - mmdeploy - INFO - **********Environmental information**********
'tail' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-04-23 15:34:05,244 - mmdeploy - INFO - sys.platform: win32
2023-04-23 15:34:05,244 - mmdeploy - INFO - Python: 3.8.2 (default, May  6 2020, 09:02:42) [MSC v.1916 64 bit (AMD64)]
2023-04-23 15:34:05,245 - mmdeploy - INFO - CUDA available: True
2023-04-23 15:34:05,245 - mmdeploy - INFO - GPU 0: NVIDIA GeForce GTX 1660 Ti
2023-04-23 15:34:05,245 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2023-04-23 15:34:05,245 - mmdeploy - INFO - NVCC: Not Available
2023-04-23 15:34:05,245 - mmdeploy - INFO - GCC: n/a
2023-04-23 15:34:05,245 - mmdeploy - INFO - PyTorch: 1.10.0
2023-04-23 15:34:05,245 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

2023-04-23 15:34:05,245 - mmdeploy - INFO - TorchVision: 0.11.0
2023-04-23 15:34:05,246 - mmdeploy - INFO - OpenCV: 4.7.0
2023-04-23 15:34:05,246 - mmdeploy - INFO - MMCV: 1.4.0
2023-04-23 15:34:05,246 - mmdeploy - INFO - MMCV Compiler: MSVC 192930137
2023-04-23 15:34:05,246 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2023-04-23 15:34:05,247 - mmdeploy - INFO - MMDeploy: 0.14.0+c737563
2023-04-23 15:34:05,247 - mmdeploy - INFO -

2023-04-23 15:34:05,247 - mmdeploy - INFO - **********Backend information**********
2023-04-23 15:34:05,279 - mmdeploy - INFO - tensorrt:   None
2023-04-23 15:34:05,323 - mmdeploy - INFO - ONNXRuntime:        None
2023-04-23 15:34:05,323 - mmdeploy - INFO - ONNXRuntime-gpu:    1.8.1
2023-04-23 15:34:05,324 - mmdeploy - INFO - ONNXRuntime custom ops:     Available
2023-04-23 15:34:05,325 - mmdeploy - INFO - pplnn:      None
2023-04-23 15:34:05,328 - mmdeploy - INFO - ncnn:       None
2023-04-23 15:34:05,359 - mmdeploy - INFO - snpe:       None
2023-04-23 15:34:05,359 - mmdeploy - INFO - openvino:   None
2023-04-23 15:34:05,359 - mmdeploy - INFO - torchscript:        1.10.0
2023-04-23 15:34:05,359 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-04-23 15:34:05,406 - mmdeploy - INFO - rknn-toolkit:       None
2023-04-23 15:34:05,406 - mmdeploy - INFO - rknn2-toolkit:      None
2023-04-23 15:34:05,411 - mmdeploy - INFO - ascend:     None
2023-04-23 15:34:05,413 - mmdeploy - INFO - coreml:     None
2023-04-23 15:34:05,414 - mmdeploy - INFO - tvm:        None
2023-04-23 15:34:05,414 - mmdeploy - INFO -

2023-04-23 15:34:05,414 - mmdeploy - INFO - **********Codebase information**********
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmdet:      2.28.2
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmseg:      None
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmcls:      None
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmocr:      None
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmedit:     None
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmdet3d:    None
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmpose:     None
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmrotate:   None
2023-04-23 15:34:05,414 - mmdeploy - INFO - mmaction:   None

2. this echo $env:PATH, and i add "D:\project\mmdeploy\build\lib\Release" to PATH
C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bin;C:\ProgramData\Anaconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\project\mmdeploy\build\lib\Release;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\libnvvp;C:\Program Files\Git\bin;C:\ProgramData\opencv\build\x64\vc15\bin;C:\ProgramData\Microsoft VS Code\bin;D:\project\mmdeploy\build\lib\Release;C:\ProgramData\onnxruntime-win-gpu-x64-1.8.1\lib;.
```

### Error traceback

```Shell
Traceback (most recent call last):
  File ".\mmdeploy\demo\python\object_detection.py", line 5, in <module>
    from mmdeploy_runtime import Detector
ModuleNotFoundError: No module named 'mmdeploy_runtime'
```

**Comment by irexyc** [comment]
1. check if the `D:\project\mmdeploy\build\lib\Release` contains mmdeploy_python.cp38-win_amd64.pyd.
if the folder have the pyd file, the right command (almost) should be:
```
PYTHONPATH=D:\project\mmdeploy\build\lib\Release python .\mmdeploy\demo\python\object_detection.py cuda D:\project\mmdeploy_model\cascade_rcnn D:\project\mmdetection\demo\demo.jpg
```

2. As you use python 3.8, you have to add the dependencies of the `pyd` file manually, similiar to [this](https://github.com/open-mmlab/mmdeploy/issues/1949#issuecomment-1491849630), you may modify the code like below. If you meet error like `not a valid Win32 application`, you can refer to this issue.
```
import os
os.add_dll_directory(r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin')
os.add_dll_directory(r'C:\ProgramData\onnxruntime-win-gpu-x64-1.8.1\lib')

from mmdeploy_runtime import Detector

# ... other code
```

Our compile scripts are not very well organized for custom build of python packages. If you just want to use the python api of sdk, you can use the precompiled version(main branch). You can install it through `pip install mmdeploy-runtime-gpu==1.0.0`

**Comment by Josh1021** [comment]
Thank you for the fast response!!
1. I have `mmdeploy_runtime.cp38-win_amd64.pyd` in `D:\project\mmdeploy\build\**bin**\Release`, does it ok?
2. Does  'PYTHONPATH=D:\project\mmdeploy\build\lib\Release '  mean add this path to $env:PYTHONPATH, then run `python .\mmdeploy\demo\python\object_detection.py cuda D:\project\mmdeploy_model\cascade_rcnn D:\project\mmdetection\demo\demo.jpg`, 
I do that ,but it doesn't work; i  directly run full command is also wrong, 
3. I also add below code to my script, but still have above error
` import os
os.add_dll_directory(r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin')
os.add_dll_directory(r'C:\ProgramData\onnxruntime-win-gpu-x64-1.8.1\lib') `
4. Because my model is trained by mmdetection0.28.0, i dont know  whether  mmdeploy-runtime-gpu==1.0.0 can convert and infer

**Comment by irexyc** [comment]
1. my mistake, it should be in bin\release folder
2. My last command have two mistakes, $env:PYTHONPATH and bin (not lib)
```
$env:PYTHONPATH="D:\project\mmdeploy\build\bin\Release" 
python .\mmdeploy\demo\python\object_detection.py cuda D:\project\mmdeploy_model\cascade_rcnn D:\project\mmdetection\demo\demo.jpg
```
4. mmdeploy_python(mmdeploy_runtime) is only for inference and have no dependent on the version of mmdetection.

**Comment by Josh1021** [comment]
After add `$env:PYTHONPATH="D:\project\mmdeploy\build\bin\Release" ` to  `$env:PYTHONPATH`  
add  `onnxruntime.dll` to `mmdeploy/build/bin/Release` 
and add 
 ` import os
os.add_dll_directory(r'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin')
os.add_dll_directory(r'C:\ProgramData\onnxruntime-win-gpu-x64-1.8.1\lib') ` to code 
solve the problem of `'No module named 'mmdeploy_runtime'' ` and ` not a valid Win32 application `, thank you very much!!

there is anthor problem, when i infer with cpu, it work well, command:
`python .\mmdeploy\build\install\example\python\object_detection.py cpu D:\project\mmdeploy_model\cascade_rcnn D:\project\mmdetection\demo\demo.jpg`
but infer with cuda , 
`(mmdeploy0.14.0) PS D:\project> python .\mmdeploy\build\install\example\python\object_detection.py cuda D:\project\mmdeploy_model\cascade_rcnn D:\project\mmdetection\demo\demo.jpg
[2023-04-24 10:08:31.885] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "D:\project\mmdeploy_model\cascade_rcnn"
2023-04-24 10:08:32.2228366 [E:onnxruntime:, provider_bridge_ort.cc:901 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126
[2023-04-24 10:08:32.236] [mmdeploy] [error] [ort_net.cpp:205] unhandled exception when creating ORTNet: OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
[2023-04-24 10:08:32.236] [mmdeploy] [error] [net_module.cpp:54] Failed to create Net backend: onnxruntime, config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "cascadercnn",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}`

and this is onnxruntime in python,

`Python 3.8.2 (default, May  6 2020, 09:02:42) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> print(onnxruntime.get_device())
GPU
>>> onnxruntime.get_available_providers()
['CUDAExecutionProvider', 'CPUExecutionProvider']`

**Comment by irexyc** [comment]
@Josh1021 Hi，you can try delete onnxruntime.dll in the `mmdeploy/build/bin/Release` folder **or** copy all dll in `C:\ProgramData\onnxruntime-win-gpu-x64-1.8.1\lib` to `mmdeploy/build/bin/Release`

**Comment by Josh1021** [comment]
@irexyc hi,  thanks a lot, my problem solved after delete `onnxruntime.dll` and copy all dll in `C:\ProgramData\onnxruntime-win-gpu-x64-1.8.1\lib` to `mmdeploy/build/bin/Release`

**Comment by ljl02521** [comment]
Build MMDeploy tensorrt SDK 
![err](https://github.com/open-mmlab/mmdeploy/assets/18475216/130c0dab-30e4-4cdb-9ade-f4da677f4f3c)
07/09 11:18:28 - mmengine - INFO - **********Environmental information**********
07/09 11:18:29 - mmengine - INFO - sys.platform: linux
07/09 11:18:29 - mmengine - INFO - Python: 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0]
07/09 11:18:29 - mmengine - INFO - CUDA available: True
07/09 11:18:29 - mmengine - INFO - MUSA available: False
07/09 11:18:29 - mmengine - INFO - numpy_random_seed: 2147483648
07/09 11:18:29 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3090
07/09 11:18:29 - mmengine - INFO - CUDA_HOME: /usr
07/09 11:18:29 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.8, V11.8.89
07/09 11:18:29 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
07/09 11:18:29 - mmengine - INFO - PyTorch: 2.1.2+cu118
07/09 11:18:29 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

07/09 11:18:29 - mmengine - INFO - TorchVision: 0.16.2+cu118
07/09 11:18:29 - mmengine - INFO - OpenCV: 4.10.0
07/09 11:18:29 - mmengine - INFO - MMEngine: 0.10.3
07/09 11:18:29 - mmengine - INFO - MMCV: 2.1.0
07/09 11:18:29 - mmengine - INFO - MMCV Compiler: GCC 9.3
07/09 11:18:29 - mmengine - INFO - MMCV CUDA Compiler: 11.8
07/09 11:18:29 - mmengine - INFO - MMDeploy: 1.3.1+bc75c9d
07/09 11:18:29 - mmengine - INFO - 

07/09 11:18:29 - mmengine - INFO - **********Backend information**********
07/09 11:18:30 - mmengine - INFO - tensorrt:	8.6.1
07/09 11:18:30 - mmengine - INFO - tensorrt custom ops:	Available
07/09 11:18:30 - mmengine - INFO - ONNXRuntime:	1.8.1
07/09 11:18:30 - mmengine - INFO - ONNXRuntime-gpu:	None
07/09 11:18:30 - mmengine - INFO - ONNXRuntime custom ops:	Available
07/09 11:18:30 - mmengine - INFO - pplnn:	None
07/09 11:18:30 - mmengine - INFO - ncnn:	None
07/09 11:18:30 - mmengine - INFO - snpe:	None
07/09 11:18:30 - mmengine - INFO - openvino:	None
07/09 11:18:30 - mmengine - INFO - torchscript:	2.1.2+cu118
07/09 11:18:30 - mmengine - INFO - torchscript custom ops:	NotAvailable
07/09 11:18:30 - mmengine - INFO - rknn-toolkit:	None
07/09 11:18:30 - mmengine - INFO - rknn-toolkit2:	None
07/09 11:18:30 - mmengine - INFO - ascend:	None
07/09 11:18:30 - mmengine - INFO - coreml:	None
07/09 11:18:30 - mmengine - INFO - tvm:	None
07/09 11:18:30 - mmengine - INFO - vacc:	None
07/09 11:18:30 - mmengine - INFO - 

07/09 11:18:30 - mmengine - INFO - **********Codebase information**********
07/09 11:18:30 - mmengine - INFO - mmdet:	3.3.0
07/09 11:18:30 - mmengine - INFO - mmseg:	None
07/09 11:18:30 - mmengine - INFO - mmpretrain:	None
07/09 11:18:30 - mmengine - INFO - mmocr:	None
07/09 11:18:30 - mmengine - INFO - mmagic:	None
07/09 11:18:30 - mmengine - INFO - mmdet3d:	None
07/09 11:18:30 - mmengine - INFO - mmpose:	1.3.1
07/09 11:18:30 - mmengine - INFO - mmrotate:	None
07/09 11:18:30 - mmengine - INFO - mmaction:	None
07/09 11:18:30 - mmengine - INFO - mmrazor:	None
07/09 11:18:30 - mmengine - INFO - mmyolo:	None
