### ISSUE TITLE
error on ubuntu20.04

### ISSUE THREAD

**Issue by sidh1603** [open-mmlab/mmdeploy#2023]
### 📚 The doc issue

Hi, after installing rtmpose , i run it on windows by using command

python pose_tracker.py cpu rtmpose-ort/rtmdet-nano/ rtmpose-ort/rtmpose-m/ 0

it work well and the speed is also good on cpu .

but when i run the same command on ubuntu20.04 , i got the error
![9c88ffbe507edebeb539f0b0dca3fa0b20093194b640d0ba66cebc6f9948879a](https://user-images.githubusercontent.com/51013394/233869103-c2a58d8d-4f90-4368-90e1-b96ab6260924.png)

**Comment by irexyc** [comment]
Hi, can you share the `rtmpose-ort/` folder ?

**Comment by sidh1603** [comment]
rtmpose-cpu.zip
<https://drive.google.com/file/d/1CdqytHbR_vpEoLlN4K-rAM6ldvM8Kz_u/view?usp=drive_web>
HI,

THanks for your reply.

i am sharing the rtmpose-ort folder with you

**Comment by sidh1603** [comment]
Hi,

Any solution??

**Comment by irexyc** [comment]
Hi @sidh1603 
Sorry for late reply, You issue may similiar to [wizardly_ellis](https://github.com/open-mmlab/mmdeploy/issues/1632).

The error may due to some UB in our code and revelent to gcc _GLIBCXX_ASSERTIONS flag. However I can't reproduce on my machine.

You machine seems are not ubuntu20.04? I don't think gcc will be installed in `/opt/rh/devtoolset-9` on ubuntu. Or are you run the program in a docker container? If so, please provide your container information. If not, plesase provide the output of `uname -a` so I can try to reproduce it with same env.

**Comment by sidh1603** [comment]
Hi, output of uname -aSent from my iPhoneOn Apr 26, 2023, at 1:14 AM, Chen Xin ***@***.***> wrote:﻿
Hi @sidh1603
Sorry for late reply, You issue may similiar to wizardly_ellis.
The error may due to some UB in our code and revelent to gcc _GLIBCXX_ASSERTIONS flag. However I can't reproduce on my machine.
You machine seems are not ubuntu20.04? I don't think gcc will be installed in /opt/rh/devtoolset-9 on ubuntu. Or are you run the program in a docker container? If so, please provide your container information. If not, plesase provide the output of uname -a so I can try to reproduce it with same env.

**Comment by irexyc** [comment]
@sidh1603

Are you work in docker? 

And you seems not provide the output of uname -a.

**Comment by sidh1603** [comment]
Hi,its ubuntu 20.04Sent from my iPhoneOn Apr 27, 2023, at 1:07 AM, Chen Xin ***@***.***> wrote:﻿
@sidh1603
Are you work in docker?
And you seems not provide the output of uname -a.

**Comment by irexyc** [comment]
@sidh1603 

Hi, ubuntu 20.04 won't have gcc installed in /opt/rh/devtoolset-9/

**Comment by NicolasPetermann134** [comment]
Could you solve the problem? I'm facing the same issue. Would appreciate any help a lot.

**Comment by sidh1603** [comment]
Hi,No for the same i switched to windows , because i want to run on cpu.  i tried everything but nothing worked.Sent from my iPhoneOn Jun 25, 2023, at 1:16 PM, NicolasPetermann134 ***@***.***> wrote:﻿
Could you solve the problem? I'm facing the same issue. Would appreciate any help a lot.

**Comment by NicolasPetermann134** [comment]
oh okay, thx for your feedback, will try the same then.

**Comment by sidh1603** [comment]
Hi,i am able to run on ubuntuSent from my iPhoneOn Sep 22, 2023, at 8:48 PM, github-actions[bot] ***@***.***> wrote:﻿
This issue is marked as stale because it has been marked as invalid or awaiting response for 7 days without any further response. It will be closed in 5 days if the stale label is not removed or if there is no further response.

**Comment by irexyc** [comment]
To any who has the same problem.

The vector assert error might due to onnxruntime. We found on some pc, running onnxruntime 1.8.1 will face this assert error. We upgrade our dependencies of onnxruntime to 1.15.1 on mmdeploy 1.3.0. The latest version may fix this problem.
