### ISSUE TITLE
[Bug] scope_name should be a string, but got None when pth converted to onnx

### ISSUE THREAD

**Issue by tlzhaoboling** [open-mmlab/mmdeploy#2030]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

AssertionError: class `Segmentation` in mmdeploy/codebase/mmseg/deploy/segmentation.py: scope_name should be a string, but got None

This error has confused me for 3 days, and I've no idea what to do.

Many thanks in advance.

### Reproduction

My command is:
(_mmdeploy) w@X299-WU8:/demo/w/MMDeploy$ python tools/deploy.py configs/mmseg/segmentation_onnxruntime_dynamic.py workdir/fpn_van_b1_ade20k_40k.py workdir/latest.pth workdir/ADE_train_00000001.jpg

Note that MMDeploy is downloaded from https://github.com/open-mmlab/mmdeploy

NO modifications on any code or config of MMDeploy, including deploy.py.

### Environment

```Shell
(_mmdeploy) w@X299-WU8:/demo/w/MMDeploy$ python tools/check_env.py
04/26 10:42:57 - mmengine - INFO -

04/26 10:42:57 - mmengine - INFO - **********Environmental information**********
04/26 10:42:58 - mmengine - INFO - sys.platform: linux
04/26 10:42:58 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
04/26 10:42:58 - mmengine - INFO - CUDA available: True
04/26 10:42:58 - mmengine - INFO - numpy_random_seed: 2147483648
04/26 10:42:58 - mmengine - INFO - GPU 0,1,2,3: NVIDIA GeForce RTX 3080 Ti
04/26 10:42:58 - mmengine - INFO - CUDA_HOME: /usr
04/26 10:42:58 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.55
04/26 10:42:58 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
04/26 10:42:58 - mmengine - INFO - PyTorch: 1.13.1+cu116
04/26 10:42:58 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.4
    - Built with CuDNN 8.3.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

04/26 10:42:58 - mmengine - INFO - TorchVision: 0.14.1+cu116
04/26 10:42:58 - mmengine - INFO - OpenCV: 4.7.0
04/26 10:42:58 - mmengine - INFO - MMEngine: 0.7.2
04/26 10:42:58 - mmengine - INFO - MMCV: 2.0.0rc4
04/26 10:42:58 - mmengine - INFO - MMCV Compiler: GCC 9.3
04/26 10:42:58 - mmengine - INFO - MMCV CUDA Compiler: 11.6
04/26 10:42:58 - mmengine - INFO - MMDeploy: 1.0.0+6bccf05
04/26 10:42:58 - mmengine - INFO -

04/26 10:42:58 - mmengine - INFO - **********Backend information**********
04/26 10:42:58 - mmengine - INFO - tensorrt:    None
04/26 10:42:58 - mmengine - INFO - ONNXRuntime: 1.13.1
04/26 10:42:58 - mmengine - INFO - ONNXRuntime-gpu:     None
04/26 10:42:58 - mmengine - INFO - ONNXRuntime custom ops:      Available
04/26 10:42:58 - mmengine - INFO - pplnn:       None
04/26 10:42:58 - mmengine - INFO - ncnn:        None
04/26 10:42:58 - mmengine - INFO - snpe:        None
04/26 10:42:58 - mmengine - INFO - openvino:    None
04/26 10:42:58 - mmengine - INFO - torchscript: 1.13.1+cu116
04/26 10:42:58 - mmengine - INFO - torchscript custom ops:      NotAvailable
04/26 10:42:58 - mmengine - INFO - rknn-toolkit:        None
04/26 10:42:58 - mmengine - INFO - rknn-toolkit2:       None
04/26 10:42:58 - mmengine - INFO - ascend:      None
04/26 10:42:58 - mmengine - INFO - coreml:      None
04/26 10:42:58 - mmengine - INFO - tvm: None
04/26 10:42:58 - mmengine - INFO - vacc:        None
04/26 10:42:58 - mmengine - INFO -

04/26 10:42:58 - mmengine - INFO - **********Codebase information**********
04/26 10:42:58 - mmengine - INFO - mmdet:       None
04/26 10:42:58 - mmengine - INFO - mmseg:       1.0.0
04/26 10:42:58 - mmengine - INFO - mmcls:       None
04/26 10:42:58 - mmengine - INFO - mmocr:       None
04/26 10:42:58 - mmengine - INFO - mmedit:      None
04/26 10:42:58 - mmengine - INFO - mmdet3d:     None
04/26 10:42:58 - mmengine - INFO - mmpose:      None
04/26 10:42:58 - mmengine - INFO - mmrotate:    None
04/26 10:42:58 - mmengine - INFO - mmaction:    None
04/26 10:42:58 - mmengine - INFO - mmrazor:     None

By considering that MMDeploy in https://github.com/open-mmlab/mmdeploy is the lastest, I install MMDeploy 1.0.0 using pip according to https://github.com/open-mmlab/mmdeploy/releases/ instead of 0.12.0 as in https://mmdeploy.readthedocs.io/zh_CN/latest/get_started.html

The following commands are used in my installation:
conda create -n _mmdeploy python=3.7
conda activate _mmdeploy
pip install mmdeploy==1.0.0
pip install onnxruntime==1.13.1
pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116
pip install mmcv==2.0.0rc4 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.13/index.html
pip install mmsegmentation==1.0.0
```

### Error traceback

```Shell
(_mmdeploy) w@X299-WU8:/demo/w/MMDeploy$ python tools/deploy.py configs/mmseg/segmentation_onnxruntime_dynamic.py workdir/fpn_van_b1_ade20k_40k.py workdir/latest.pth workdir/ADE_train_00000001.jpg
04/26 11:12:35 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
04/26 11:12:35 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
04/26 11:12:35 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
Process Process-2:
Traceback (most recent call last):
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 134, in __init__
    super(Segmentation, self).__init__(model_cfg, deploy_cfg, device)
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmdeploy/codebase/base/task.py", line 55, in __init__
    scope_name=self.model_cfg.get('default_scope'))
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmengine/registry/default_scope.py", line 37, in __init__
    str), (f'scope_name should be a string, but got {scope_name}')
AssertionError: scope_name should be a string, but got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmdeploy/apis/pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmdeploy/codebase/base/mmcodebase.py", line 50, in build_task_processor
    device=device))
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
AssertionError: class `Segmentation` in mmdeploy/codebase/mmseg/deploy/segmentation.py: scope_name should be a string, but got None
04/26 11:12:35 - mmengine - ERROR - /home/w/anaconda3/envs/_mmdeploy/lib/python3.7/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 81 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by RunningLeon** [comment]
@tlzhaoboling hi, have you changed any thing in deploy config?

**Comment by gorgeousjohnny** [comment]
Describe the bug:
I have the similar error message while I want to change mmdetection model to tensorrt model. I 
I am running the program inside a Docker container

Reproduction
My command is:
python tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py frange/test_flange_probe/cascade_rcnn_r50_fpn_1x_coco_20230316.py frange/test_flange_probe/latest20230316.pth frange/test_flange_probe/test_frame/20221014-1018/20221114video/MOV20221114_101817/image_MOV20221114_101817_5.jpg --device cuda:0 --show --dump-info

Note that MMDeploy is downloaded from https://github.com/open-mmlab/mmdeploy

NO modifications on any code or config of MMDeploy, including deploy.py.

Environment
root@fpc-GT83VR-7RF:~/workspace/volume# python tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py frange/test_flange_probe/cascade_rcnn_r50_fpn_1x_coco_20230316.py frange/test_flange_probe/latest20230316.pth frange/test_flange_probe/test_frame/20221014-1018/20221114video/MOV20221114_101817/image_MOV20221114_101817_5.jpg --device cuda:0 --show --dump-info
04/27 06:54:42 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
04/27 06:54:42 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 132, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/deploy.py", line 335, in <module>
    main()
  File "tools/deploy.py", line 129, in main
    export2SDK(
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 347, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 262, in get_deploy
    _, customs = get_model_name_customs(
  File "/root/workspace/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 61, in get_model_name_customs
    task_processor = build_task_processor(
  File "/root/workspace/mmdeploy/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AssertionError: class `ObjectDetection` in mmdeploy/codebase/mmdet/deploy/object_detection.py: scope_name should be a string, but got None

**Comment by kateob** [comment]
I have the exact same error as gorgeousjohnny. I installed mmdet following the official instructions inside the Nvidia tensorrt docker image 22.07. I was able to verify the installation of mmdet worked with their demo example. It took a few hours to install all the mmdeploy packages, following the instructions on the mmdeploy site. I got this error when I went to convert a yolo v3 pytorch model to onnx.

**Comment by RunningLeon** [comment]
@kateob @tlzhaoboling @gorgeousjohnny hi, guys. I've tried and cannot reproduce the issue. Could you guys use our docker image and try again?
## examples
### create container
```
docker pull openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.0.0
docker run -it --rm -gpus=all openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.0.0
```
### download and install mmseg inside container
```
cd /root/workspace
git clone --depth 1 https://github.com/open-mmlab/mmsegmentation.git
cd mmsegmentation
python3 -m mim install -r requirements/mminstall.txt
python3 -m pip install -r requirements.txt
python3 -m pip install -e .
```
### check env
```
cd ../mmdeploy
python3 tools/check_env.py
```
### convert model with mmdeploy
```
python3 tools/deploy.py \
    configs/mmseg/segmentation_onnxruntime_dynamic.py \
    ../mmsegmentation/configs/fcn/fcn_r50-d8_4xb2-40k_cityscapes-512x1024.py \
    ../mmdeploy_checkpoints/mmseg/fcn/fcn_r50-d8_512x1024_40k_cityscapes_20200604_192608-efe53f0d.pth \
    ../mmsegmentation/demo/demo.png --work-dir workdir/fcn
```

**Comment by Charlyo** [comment]
Same issues here with the following env:

-  mmdet 3.0.0
- mmdeploy 1.0.0,
- mmcv 2.0.0
- python3.8
- TensorRT 8.6.1
- Cuda 11.8
- Ubuntu22.04

I'm trying to convert a detectoRS model to tensorrt FP16.

**Comment by RunningLeon** [comment]
@Charlyo hi, did not reproduce it. Could you try with our docker image?

**Comment by Charlyo** [comment]
Cannot change the current versions in my env since I'm constrained by other projects that I have.
