### ISSUE TITLE
convert 

### ISSUE THREAD

**Issue by wm901115nwpu** [open-mmlab/mmdeploy#2035]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I use mmdeploy to convert second_secfpn model to onnx model.

### Reproduction

python tools/torch2onnx.py configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py ../mmdetection3d/configs/second/second_hv_secfpn_8xb6-80e_kitti-3d-car.py https://download.openmmlab.com/mmdetection3d/v1.0.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20220608_002749-718c73ca.pth  ../mmdetection3d/tests/data/nuscenes/sweeps/LIDAR_TOP/n008-2018-09-18-12-07-26-0400__LIDAR_TOP__1537287083900561.pcd.bin --work-dir secfpn_car

### Environment

```Shell
python tools/check_env.py                                                                                                                                                            ─╯
04/26 19:57:59 - mmengine - INFO -

04/26 19:57:59 - mmengine - INFO - **********Environmental information**********
04/26 19:58:01 - mmengine - INFO - sys.platform: darwin
04/26 19:58:01 - mmengine - INFO - Python: 3.8.16 (default, Jan 17 2023, 16:39:35) [Clang 14.0.6 ]
04/26 19:58:01 - mmengine - INFO - CUDA available: False
04/26 19:58:01 - mmengine - INFO - numpy_random_seed: 2147483648
04/26 19:58:01 - mmengine - INFO - GCC: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
04/26 19:58:01 - mmengine - INFO - PyTorch: 2.0.0
04/26 19:58:01 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 4.2
  - C++ Version: 201703
  - clang 13.1.6
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_13.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DUSE_COREML_DELEGATE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=braced-scalar-init -Werror=range-loop-construct -Werror=bool-operation -Winconsistent-missing-override -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wvla-extension -Wno-range-loop-analysis -Wno-pass-failed -Wsuggest-override -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-constexpr-not-const -Wno-missing-braces -Wunused-lambda-capture -Wunused-local-typedef -Qunused-arguments -fcolor-diagnostics -fdiagnostics-color=always -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -Wno-unused-private-field -Wno-missing-braces -Wno-constexpr-not-const, LAPACK_INFO=accelerate, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.0, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, USE_ROCM=OFF,

04/26 19:58:01 - mmengine - INFO - TorchVision: 0.15.1
04/26 19:58:01 - mmengine - INFO - OpenCV: 4.7.0
04/26 19:58:01 - mmengine - INFO - MMEngine: 0.7.2
04/26 19:58:01 - mmengine - INFO - MMCV: 2.0.0
04/26 19:58:01 - mmengine - INFO - MMCV Compiler: clang 14.0.0
04/26 19:58:01 - mmengine - INFO - MMCV CUDA Compiler: not available
04/26 19:58:01 - mmengine - INFO - MMDeploy: 1.0.0rc3+0196cd0
04/26 19:58:01 - mmengine - INFO -

04/26 19:58:01 - mmengine - INFO - **********Backend information**********
04/26 19:58:01 - mmengine - INFO - tensorrt:	None
04/26 19:58:01 - mmengine - INFO - ONNXRuntime:	None
04/26 19:58:01 - mmengine - INFO - ONNXRuntime-gpu:	None
04/26 19:58:01 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
04/26 19:58:01 - mmengine - INFO - pplnn:	None
04/26 19:58:01 - mmengine - INFO - ncnn:	None
04/26 19:58:01 - mmengine - INFO - snpe:	None
04/26 19:58:01 - mmengine - INFO - openvino:	None
04/26 19:58:01 - mmengine - INFO - torchscript:	2.0.0
04/26 19:58:01 - mmengine - INFO - torchscript custom ops:	NotAvailable
04/26 19:58:01 - mmengine - INFO - rknn-toolkit:	None
04/26 19:58:01 - mmengine - INFO - rknn-toolkit2:	None
04/26 19:58:01 - mmengine - INFO - ascend:	None
04/26 19:58:01 - mmengine - INFO - coreml:	None
04/26 19:58:01 - mmengine - INFO - tvm:	None
04/26 19:58:01 - mmengine - INFO - vacc:	None
04/26 19:58:01 - mmengine - INFO -

04/26 19:58:01 - mmengine - INFO - **********Codebase information**********
04/26 19:58:01 - mmengine - INFO - mmdet:	3.0.0
04/26 19:58:01 - mmengine - INFO - mmseg:	None
04/26 19:58:01 - mmengine - INFO - mmcls:	None
04/26 19:58:01 - mmengine - INFO - mmocr:	None
04/26 19:58:01 - mmengine - INFO - mmedit:	None
04/26 19:58:01 - mmengine - INFO - mmdet3d:	1.1.0
04/26 19:58:01 - mmengine - INFO - mmpose:	None
04/26 19:58:01 - mmengine - INFO - mmrotate:	None
04/26 19:58:01 - mmengine - INFO - mmaction:	None
04/26 19:58:01 - mmengine - INFO - mmrazor:	None
```

### Error traceback

```Shell
python tools/torch2onnx.py configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py ../mmdetection3d/configs/second/second_hv_secfpn_8xb6-80e_kitti-3d-car.py https://download.openmmlab.com/mmdetection3d/v1.0.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20220608_002749-718c73ca.pth  ../mmdetection3d/tests/data/nuscenes/sweeps/LIDAR_TOP/n008-2018-09-18-12-07-26-0400__LIDAR_TOP__1537287083900561.pcd.bin --work-dir secfpn_car
04/26 20:04:17 - mmengine - INFO - torch2onnx:
	model_cfg: ../mmdetection3d/configs/second/second_hv_secfpn_8xb6-80e_kitti-3d-car.py
	deploy_cfg: configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py
04/26 20:04:18 - mmengine - WARNING - Import mmdeploy.codebase.mmdet3d.deploy failedPlease check whether the module is the custom module.Numba requires at least version 0.40.0 of llvmlite.
Installed version is 0.39.1.
Please update llvmlite.
Traceback (most recent call last):
  File "tools/torch2onnx.py", line 85, in <module>
    main()
  File "tools/torch2onnx.py", line 47, in main
    torch2onnx(
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/codebase/__init__.py", line 35, in import_codebase
    codebase = get_codebase_class(codebase_type)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 86, in get_codebase_class
    return CODEBASE.build({'type': codebase.value})
  File "/Users/unicorn/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine-0.7.2-py3.8.egg/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/Users/unicorn/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmengine-0.7.2-py3.8.egg/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'mmdet3d is not in the Codebases registry. Please check whether the value of `mmdet3d` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

**Comment by RunningLeon** [comment]
@wm901115nwpu hi, pls. double-check whether mmdet3d is correctly installed in your env.

**Comment by wm901115nwpu** [comment]
ok，it's my fault, I reinstall mmdet3d, but occur this error:
python tools/torch2onnx.py configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py ../mmdetection3d/configs/second/second_hv_secfpn_8xb6-80e_kitti-3d-car.py https://download.openmmlab.com/mmdetection3d/v1.0.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20220608_002749-718c73ca.pth  ../mmdetection3d/tests/data/nuscenes/sweeps/LIDAR_TOP/n008-2018-09-18-12-07-26-0400__LIDAR_TOP__1537287083900561.pcd.bin --work-dir secfpn_car
04/27 14:24:00 - mmengine - INFO - torch2onnx:
	model_cfg: ../mmdetection3d/configs/second/second_hv_secfpn_8xb6-80e_kitti-3d-car.py
	deploy_cfg: configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py
/Users/unicorn/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet3d-1.1.0-py3.8.egg/mmdet3d/evaluation/functional/kitti_utils/eval.py:10: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41):
04/27 14:24:06 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
04/27 14:24:06 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "mmdet3d_tasks" registry tree. As a workaround, the current "mmdet3d_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
/Users/unicorn/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet3d-1.1.0-py3.8.egg/mmdet3d/models/dense_heads/anchor3d_head.py:92: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20220608_002749-718c73ca.pth
04/27 14:24:06 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
04/27 14:24:06 - mmengine - INFO - Export PyTorch model to ONNX: secfpn_car/end2end.onnx.
Traceback (most recent call last):
  File "tools/torch2onnx.py", line 85, in <module>
    main()
  File "tools/torch2onnx.py", line 47, in main
    torch2onnx(
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/Users/unicorn/workspace/mmdeploy/mmdeploy/apis/onnx/export.py", line 131, in export
    torch.onnx.export(
  File "<@beartype(torch.onnx.utils.export) at 0x110fb3790>", line 63, in export
beartype.roar.BeartypeCallHintParamViolation: @beartyped torch.onnx.utils.export() parameter args=[tensor([[[  4.0000,  -4.1292,  -0.3588,  -1.8576],
         [  4.0000,  -4.1323,  -0.3104, .... violates type hint typing.Union[typing.Tuple[typing.Any, ...], torch.Tensor], as list [tensor([[[  4.0000,  -4.1292,  -0.3588,  -1.8576],
         [  4.0000,  -4.1323,  -0.3104, .... not <protocol "torch.Tensor"> or tuple.

**Comment by RunningLeon** [comment]
@wm901115nwpu hi, the model Second is not supported by far: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet3d.html#supported-models. Maybe you could support by yourself and contribute the code to mmdeploy through PR.
