### ISSUE TITLE
"mmdeploy_detector_apply" returns nothing[Bug] 

### ISSUE THREAD

**Issue by GSusan** [open-mmlab/mmdeploy#2036]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi, thanks for all your jobs with mmdeploy firstly.
I have met a confused question when I use "mmdeploy_detector_apply()" . I found it return nothing when I excute my project in some times.  I excute the same image again and again. Sometimes, it returns 0, and it's correctly. But in some other times, it returns nothing. I try to use "try {} catch{}" to find some errors, but nothing returns to me. I test it on three computers, and only one computer occures this question. Is it related to the system of computer or else?
I don't know what's wrong with it. 

### Reproduction

mmdeploy-0.13.0-onnxruntime C++ sdk
mask_rcnn+swin_transformer

### Environment

```Shell
nothing special
```

**Comment by irexyc** [comment]
```cpp
MMDEPLOY_API int mmdeploy_detector_apply(mmdeploy_detector_t detector, const mmdeploy_mat_t* mats,
                                         int mat_count, mmdeploy_detection_t** results,
                                         int** result_count);
```

According to the api, when you call it, it will return two arrays of `results` and `results_count`. The length of `result_count` is `mat_count`(for example 1, 3, 7, the number of boxes for each image) and the length of  `results` will be the sum of `result_count`(for example 1+3+7).

What do you mean by return nothings ? Does 0 refer to the status code? 

If you refer to the status code that is not 0, it indicates an internal error, what is the value you met? Are this situation can be reproduced stably or occasionally?

**Comment by GSusan** [comment]
In normally, status  is 0, and there are results and results_count. "It returns nothing" I mean that status is not 0, 1,2,3,..., and then project doesn't continue running anymore。So, I suspect that it's a internal error. Or some other reasons. I don't know.
![微信图片_20230427120852](https://user-images.githubusercontent.com/8318174/234757270-263826d0-2b5b-4282-9f0b-1e9d9a70304e.jpg)

**Comment by irexyc** [comment]
Are you using tensorrt backend? Is the model have dynamic shape support? If so, the image after resize(keep ratio) may have shape not in shape range that the model support and will cause error.

When the status is no zero, does there have any information in your terminal?

**Comment by GSusan** [comment]
I used ONNXRuntime on windows_X64。And the model is static shape support. I've tried to use image with different shape, it's an error info at this situation. So, it may have nothing to do with image shape.  When the status is no zero, there is no any information.

**Comment by irexyc** [comment]
```cpp
  // from object_detection.cpp
  if (argc != 4) {
    fprintf(stderr, "usage:\n  object_detection device_name model_path image_path\n");
    return 1;
  }
```
You seems modified the code according the args you passed to the executable, could you please provide the code?

**Comment by GSusan** [comment]
Yeah , I modified the code. Because, status has nothing return, and stderr also not be excuted. So I add some log info and "try...catch..". At last,my code is as follows:

    mmdeploy_detection_t *bboxes{};
    int *res_count{};
    fprintf(stdout, "begin mmdeploy_detector_apply\n");
    try {
      status = mmdeploy_detector_apply(detector, &mat, 1, &bboxes, &res_count);
    }
    catch (std::exception & e)
    {
      std::string strMsg(e.what());
      fprintf(stdout, "%s\n",strMsg.c_str());
    }
    catch (...)
    {
      fprintf(stdout, "mmdeploy_detector_apply throw unknow error.\n");
    }
    fprintf(stdout, "status of creation of mmdeploy detector apply: %d\n",
            int(status));
    if (status != MMDEPLOY_SUCCESS) 
    {
        fprintf(stderr, "failed to apply detector, code: %d\n", (int)status);
        return 1;
    }

**Comment by GSusan** [comment]
Because of some reasons, I still can't provide you the image. Sorry.

**Comment by irexyc** [comment]
The log your provide seems right ? The first and second image doesn't have any boxes output and the third image have 26 boxes output.

The args you passed to `object_detection.cpp` is not same with current demo and I don't know the change of the code as there are logs like `convertFormat finished, read bandRaster finished ...` you may provide the full code of `object_detection.cpp`.

If it is not convenient to share code, you may use the original code to do the inference on your dateset to see if there are any error happens and happens always on the same image.

**Comment by GSusan** [comment]
Exactly, I just add some preprocess code(for example, I convert a 4-band tiff to 3-band Mat as an input of mmdeploy_mat_t, the 4rd band is abandoned).Then I debug it, it's all normal. To continue debug the error, I add some fprintf log, which will not affect the result. The only difference between my code with offical code, is just that proprocess.
Supplemently, the code can work correctly in two computer,but unnormally in another one. Now I'm trying to find what's wrong with it. If I find or solved it, I'll be back. Thanks for your patience.
