### ISSUE TITLE
Can you support Chinese LoongArch?

### ISSUE THREAD

**Issue by wzb1005** [open-mmlab/mmdeploy#2037]
### Motivation

support Chinese LoongArch

**Comment by irexyc** [comment]
We don't have our own inference backends but provide a unified api to use tensorrt, ncnn and other backends to inference the model. 

NCNN seems have optimization for LoongArch. Therefore, you can use mmdeploy with ncnn as inference engine.

Here are some useful docs you can refer to
https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/get_started.md
https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/01-how-to-build/linux-x86_64.md
