### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by GeorgePearse** [open-mmlab/mmdeploy#2041]
### 📚 The doc issue

Hard to know how to match the required preprocessing. 

I've converted my faster rcnn to torcschript. I can see that the predictions are 'correct' and the export has been succesful. But I can't easily extract the preprocessing that is used to create that output.

It takes a lot of sifting through code. 

The whole aim of these formats is to be framework agnostic, but here I am, relying on preprocessing I can't find / understand.

### Suggest a potential alternative/fix

write a python file that includes the postprocessing code that's been used. I think mmdeploy might already be written in a way which makes this feasible though I could be wrong.

**Comment by irexyc** [comment]
Sorry for late reply. 

Currently, we don't have apis to get the middle results(preprocess / inference) of a task but the final result. We noticed that this is actually inconvenient, and will add related APIs later
