### ISSUE TITLE
[Docs]  How to run torchscript model from raw image input 

### ISSUE THREAD

**Issue by GeorgePearse** [open-mmlab/mmdeploy#2045]
### 📚 The doc issue

MMDeploy does not provide any obvious way to run a model over a raw image input. 

That is normally the whole point of things like torchscript export, to separate the model from the framework.

(this is me trying to workout how it might work)

![image](https://user-images.githubusercontent.com/47161914/235675456-f747c3ab-df94-4e2a-866f-ba9027ed2119.png)

**Comment by GeorgePearse** [comment]
For anyone else who hits this, the biggest problem was just that I was feeding through a tensor for a single image. But the torchscript export is setup to accept a batch. e.g the second tensor works, the first does not.

![image](https://user-images.githubusercontent.com/47161914/235889892-0ddc97c9-5cff-4058-933c-31221688106a.png)

**Comment by RunningLeon** [comment]
@GeorgePearse Hi, for the pre-processing you could double check the test_pipeline in the model config.
