### ISSUE TITLE
[Bug] Obvious performance degradation for TRT-fp16 model compared to original Pytorch model

### ISSUE THREAD

**Issue by KingofAsianPopJC** [open-mmlab/mmdeploy#2059]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

The performence of TRT-fp32 and OnnxRuntime is equal to the original Pytorch model， while there is obvious performance degradation in TRT-fp16，what is the reason and how to solve it?
![image](https://user-images.githubusercontent.com/35302032/236729208-6aa9206b-0a4a-434d-9d6d-b3852d63c9f3.png)

### Reproduction

I run the tools/deploy.py with args like

"/mnt/Data/mmdeploy/configs/self/segmentation_tensorrt-int8_static-512x512.py", "/mnt/Data/mmsegmentation/configs/self/swin-base-patch4-window7-in1k-pre_upernet_8xb2-320k_octbvsstent-512x512-reduce-negative.py",
 "/mnt/Data/mmsegmentation/work_dirs/swin-base-patch4-window7-in1k-pre_upernet_8xb2-320k_octbvsstent-512x512-reduce-negative/publis-ed99c834.pth",
 "/mnt/Data/mmsegmentation/data/OCT-BVS-Stent_Polar/imgs/P_0000_0042_2_realoctimg.png",
 "--test-img", "/mnt/Data/mmsegmentation/data/OCT-BVS-Stent_Polar/imgs/P_0000_0042_2_realoctimg.png",
 "--work-dir", "/mnt/Data/mmdeploy/work_dir/segmentation_tensorrt-int8_static-512x512",
 "--device", "cuda:0",
 "--show",

 And I only modified the code of mmdeploy/codebase/mmseg/deploy/segmentation.py:
(1 ) def process_model_config:
      delete:
      "if isinstance(imgs[0], np.ndarray):
           set loading pipeline type
          cfg.test_pipeline[0].type = 'LoadImageFromNDArray'"
     aims to use my custom defined loading method

(2) class Segmentation(BaseTask) / def create_input:
     delete:
     "imgs = [mmcv.imread(_) for _ in imgs]"
     aims to make the item in "imgs" is the path of images rather than loaded numpy.array  

### Environment

```Shell
Pytorch: 2.0.0
CUDA: 11.4
Cudnn: 8.6.0
TensorRT: 8.5-GA
Graphic Cards: Nvidia A100
System: Ubuntu 20.04

deplpy config：

onnx_config = dict(
    type='onnx',
    export_params=True,
    keep_initializers_as_inputs=False,
    opset_version=11,
    save_file='end2end.onnx',
    input_names=['input'],
    output_names=['output'],
    input_shape=[512, 512],
    optimize=True
    )

codebase_config = dict(type='mmseg', task='Segmentation')

backend_config = dict(
    type='tensorrt', common_config=dict(fp16_mode=True, max_workspace_size=1 << 30),
    model_inputs=[
         dict(
             input_shapes=dict(
                 input=dict(
                     min_shape=[1, 3, 512, 512],
                     opt_shape=[1, 3, 512, 512],
                     max_shape=[1, 3, 512, 512])))
    ])
```

**Comment by RunningLeon** [comment]
@KingofAsianPopJC Hi, TRT-FP16 may perform worse with some models due to the less precision and sometime, over-optimization. Suggest you go for help from [TensorRT](https://github.com/NVIDIA/TensorRT)
