### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'img_scale'[Bug] 

### ISSUE THREAD

**Issue by zj603252818** [open-mmlab/mmdeploy#2086]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Centernet encountered a problem exporting onnx

### Reproduction

python tools/deploy.py mmdeploy-dev-1.x/mmdeploy-dev-1.x/configs/mmdet/detection/detection_onnxruntime_dynamic.py configs/centernet/centernet_resnet18_dcnv2_140e_coco.py /data/zhangj/rim/red_point_center/epoch_190.pth demo/2.jpg --device cpu --dump-info --work-dir /data/zhangj/rim/red_point_center/

### Environment

```Shell
addict            2.4.0
certifi           2023.5.7
cycler            0.11.0
dill              0.3.6
fonttools         4.38.0
grpcio            1.54.2
kiwisolver        1.4.4
markdown-it-py    2.2.0
matplotlib        3.5.3
mdurl             0.1.2
mkl-fft           1.3.1
mkl-random        1.2.2
mkl-service       2.4.0
mmcv-full         1.5.3
mmdeploy          0.13.0
mmdet             2.25.0
mmengine          0.7.3
multiprocess      0.70.14
numpy             1.21.5
olefile           0.46
onnx              1.8.1
opencv-python     4.7.0.72
packaging         23.1
Pillow            9.5.0
pip               22.3.1
protobuf          3.20.2
pycocotools       2.0.6
Pygments          2.15.1
pyparsing         3.0.9
python-dateutil   2.8.2
PyYAML            6.0
rich              13.3.5
setuptools        65.6.3
six               1.16.0
termcolor         2.3.0
terminaltables    3.1.10
tomli             2.0.1
torch             1.10.0
torchaudio        0.10.0
torchvision       0.11.0
typing_extensions 4.5.0
wheel             0.38.4
yapf              0.33.0
```

**Comment by RunningLeon** [comment]
@zj603252818 hi, could you try with latest `main` branch?

**Comment by zj603252818** [comment]
> 

hello,I tried to update mmdeploy to the latest version, but an error occurred:
  File "tools/deploy.py", line 308, in <module>
    main()
  File "tools/deploy.py", line 134, in main
    device=args.device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 347, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 263, in get_deploy
    deploy_cfg, model_cfg, work_dir=work_dir, device=device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 62, in get_model_name_customs
    model_cfg=model_cfg, deploy_cfg=deploy_cfg, device=device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/codebase/__init__.py", line 36, in import_codebase
    codebase.register_all_modules()
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 36, in register_all_modules
    from mmdet.utils.setup_env import register_all_modules
ImportError: cannot import name 'register_all_modules' from 'mmdet.utils.setup_env' (/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdet-2.25.0-py3.7.egg/mmdet/utils/setup_env.py)

**Comment by RunningLeon** [comment]
hi, you should use "mmdet>=3.0.0rc0". Pls install by `pip install openmim` and `mim install 'mmdet>=3.0.0rc0'`

**Comment by zj603252818** [comment]
> hi, you should use "mmdet>=3.0.0rc0". Pls install by `pip install openmim` and `mim install 'mmdet>=3.0.0rc0'`

I tried to upgrade MMDET, but there were other errors:
Traceback (most recent call last):
  File "tools/deploy.py", line 308, in <module>
    main()
  File "tools/deploy.py", line 126, in main
    mmcv.mkdir_or_exist(osp.abspath(args.work_dir))
AttributeError: module 'mmcv' has no attribute 'mkdir_or_exist'


pip list:
addict             2.4.0
aenum              3.1.12
certifi            2023.5.7
charset-normalizer 3.1.0
click              8.1.3
colorama           0.4.6
cycler             0.11.0
dill               0.3.6
fonttools          4.38.0
grpcio             1.54.2
idna               3.4
importlib-metadata 6.6.0
kiwisolver         1.4.4
Markdown           3.4.3
markdown-it-py     2.2.0
matplotlib         3.5.3
mdurl              0.1.2
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
mmcv               2.0.0rc1
mmcv-full          1.5.3
mmdeploy           1.0.0
mmdet              3.0.0rc0
mmengine           0.7.3
model-index        0.1.11
multiprocess       0.70.14
numpy              1.21.5
olefile            0.46
onnx               1.14.0
opencv-python      4.7.0.72
openmim            0.3.7
ordered-set        4.1.0
packaging          23.1
pandas             1.3.5
Pillow             9.5.0
pip                22.3.1
prettytable        3.7.0
protobuf           3.20.2
pycocotools        2.0.6
Pygments           2.15.1
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0
requests           2.30.0
rich               13.3.5
scipy              1.7.3
setuptools         65.6.3
shapely            2.0.1
six                1.16.0
tabulate           0.9.0
termcolor          2.3.0
terminaltables     3.1.10
tomli              2.0.1
torch              1.10.0
torchaudio         0.10.0
torchvision        0.11.0
typing_extensions  4.5.0
urllib3            2.0.2
wcwidth            0.2.6
wheel              0.38.4
yapf               0.33.0
zipp               3.15.0

**Comment by RunningLeon** [comment]
@zj603252818 hi, mmdet3.0.0 depends on mmcv>=2.0.0 and you have installed both mmcv(2.0.0) and mmcv-full(1.5.3). you have to uninstall mmcv-full by `pip uninstall mmcv-full`

> mmcv 2.0.0rc1
mmcv-full 1.5.3

**Comment by zj603252818** [comment]
> Collaborator
I uninstalled MMCV-FULL, but it is still the same error:
Traceback (most recent call last):
  File "tools/deploy.py", line 308, in <module>
    main()
  File "tools/deploy.py", line 126, in main
    mmcv.mkdir_or_exist(osp.abspath(args.work_dir))
AttributeError: module 'mmcv' has no attribute 'mkdir_or_exist'

pip list:
addict             2.4.0
aenum              3.1.12
certifi            2023.5.7
charset-normalizer 3.1.0
click              8.1.3
colorama           0.4.6
cycler             0.11.0
dill               0.3.6
fonttools          4.38.0
grpcio             1.54.2
idna               3.4
importlib-metadata 6.6.0
kiwisolver         1.4.4
Markdown           3.4.3
markdown-it-py     2.2.0
matplotlib         3.5.3
mdurl              0.1.2
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
mmcv               2.0.0rc1
mmdeploy           1.0.0
mmdet              3.0.0rc0
mmengine           0.7.3
model-index        0.1.11
multiprocess       0.70.14
numpy              1.21.5
olefile            0.46
onnx               1.14.0
opencv-python      4.7.0.72
openmim            0.3.7
ordered-set        4.1.0
packaging          23.1
pandas             1.3.5
Pillow             9.5.0
pip                22.3.1
prettytable        3.7.0
protobuf           3.20.2
pycocotools        2.0.6
Pygments           2.15.1
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0
requests           2.30.0
rich               13.3.5
scipy              1.7.3
setuptools         65.6.3
shapely            2.0.1
six                1.16.0
tabulate           0.9.0
termcolor          2.3.0
terminaltables     3.1.10
tomli              2.0.1
torch              1.10.0
torchaudio         0.10.0
torchvision        0.11.0
typing_extensions  4.5.0
urllib3            2.0.2
wcwidth            0.2.6
wheel              0.38.4
yapf               0.33.0
zipp               3.15.0

**Comment by RunningLeon** [comment]
@zj603252818 Could you double check your env and reinstall the latest mmdeploy? Cause here is the latest line that throws error:
https://github.com/open-mmlab/mmdeploy/blob/11af78caae8373488f8ec3d7f3f27c189c87ef6b/tools/deploy.py#L126

>Traceback (most recent call last):
File "tools/deploy.py", line 308, in
main()
File "tools/deploy.py", line 126, in main
mmcv.mkdir_or_exist(osp.abspath(args.work_dir))
AttributeError: module 'mmcv' has no attribute 'mkdir_or_exist'

**Comment by zj603252818** [comment]
> mmengine
I modified the error again：
Traceback (most recent call last):
  File "tools/deploy.py", line 313, in <module>
    main()
  File "tools/deploy.py", line 139, in main
    device=args.device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 347, in export2SDK
    deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir, device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 263, in get_deploy
    deploy_cfg, model_cfg, work_dir=work_dir, device=device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/backend/sdk/export_info.py", line 62, in get_model_name_customs
    model_cfg=model_cfg, deploy_cfg=deploy_cfg, device=device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy/codebase/base/mmcodebase.py", line 50, in build_task_processor
    device=device))
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhangj/miniconda3/envs/mmdeploy/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 145, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
AssertionError: class `ObjectDetection` in mmdeploy/codebase/mmdet/deploy/object_detection.py: scope_name should be a string, but got None
