### ISSUE TITLE
编译的推理SDK  是可执行文件，如何修改代码呢？

### ISSUE THREAD

**Issue by ainndejj11** [open-mmlab/mmdeploy#2087]
### Motivation

我使用mmdeploy 编译了 tensorrt 推理SDK后， 然后是可执行文件推理。
我是用的是pose_detect 关键点模型，输出的推理图片结果名为：output_pose.png    
例如我想把名字换下，换成result.png   

问题是源码在哪里呢。csrc  下没有看到包含pose_detect的主函数的cpp代码

我在demo/csrc/cpp/  下看到了有那种pose_detector的   但是修改这里的代码，编译后  并没有任何作用

请问我应该修改那里的源码呢

**Comment by irexyc** [comment]
pose_detection 的话对应的是 demo/csrc/c/pose_detection.cpp
det_pose 的话对应的是 demo/csrc/cpp/pose_detector.cxx

**Comment by ainndejj11** [comment]
呀，太感谢了，我在dmeo/scrp/cpp下改的&nbsp; &nbsp; 没想到在c里。

还一个问题想请教一下，编译好的build文件中.&nbsp; &nbsp; ./bin下的 执行文件可以跑&nbsp; &nbsp; 还一个./install/bin 下的也可以跑，这两个一样么？&nbsp; &nbsp; 有啥区别呢


@w
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月18日(星期四) 下午3:08
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdeploy] 编译的推理SDK  是可执行文件，如何修改代码呢？ (Issue #2087)





 
pose_detection 的话对应的是 demo/csrc/c/pose_detection.cpp
 det_pose 的话对应的是 demo/csrc/cpp/pose_detector.cxx

**Comment by irexyc** [comment]
cmake --build . --config Release 在build目录下编译
cmake --install . --config Release 安装到目标文件夹(这里是install)

你可以去查一下source tree, build tree, installation tree
