### ISSUE TITLE
[Bug] IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])

### ISSUE THREAD

**Issue by sammilei** [open-mmlab/mmdeploy#2098]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

Converting from onnx2tensorrt and met this error.

```
2023-05-21 14:13:28,788 - mmdeploy - INFO - onnx2tensorrt: 
	onnx_path: work-dir/segmenter_vit-s_linear_8x1_512x512_160k_ade20k.onnx 
	deploy_cfg: configs/mmseg/segmentation_tensorrt_dynamic-512x1024-2048x2048.py
2023-05-21 14:13:28,916 - mmdeploy - WARNING - Could not load the library of tensorrt plugins.             Because the file does not exist: 
[05/21/2023-14:13:29] [TRT] [I] [MemUsageChange] Init CUDA: CPU +181, GPU +0, now: CPU 258, GPU 4779 (MiB)
[05/21/2023-14:13:32] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +131, GPU +122, now: CPU 408, GPU 4917 (MiB)
[05/21/2023-14:13:33] [TRT] [W] onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/21/2023-14:13:33] [TRT] [W] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[05/21/2023-14:13:33] [TRT] [E] [shuffleNode.cpp::symbolicExecute::390] Error Code 4: Internal Error (Reshape_31: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
2023-05-21 14:13:33,240 - mmdeploy - ERROR - Failed to parse onnx, In node 42 (parseGraph): INVALID_NODE: Invalid Node - Pad_42
[shuffleNode.cpp::symbolicExecute::390] Error Code 4: Internal Error (Reshape_31: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])

2023-05-21 14:13:33,240 - mmdeploy - ERROR - onnx2tensorrt failed.
```
Met similar error using [onnx-tensorrt](https://github.com/onnx/onnx-tensorrt/tree/release/8.4-GA)

```
~/Documents/onnx-tensorrt$ onnx2trt ~/Documents/mmdeploy/work-dir/end2end.onnx -o test.trt
----------------------------------------------------------------
Input filename:   /home/gvsc/Documents/mmdeploy/work-dir/end2end.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.12.0
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
[2023-05-21 21:17:25 WARNING] onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[2023-05-21 21:17:25 WARNING] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[2023-05-21 21:17:25   ERROR] [shuffleNode.cpp::symbolicExecute::390] Error Code 4: Internal Error (Reshape_31: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
While parsing node number 42 [Pad -> "input.1"]:
ERROR: ModelImporter.cpp:180 In function parseGraph:
[6] Invalid Node - Pad_42
[shuffleNode.cpp::symbolicExecute::390] Error Code 4: Internal Error (Reshape_31: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
```

### Reproduction

python3 tools/onnx2tensorrt.py configs.py work-dir/segmenter_vit-s_linear_8x1_512x512_160k_ade20k.onnx segmenter_vit-s_linear_8x1_512x512_160k_ade20k.tensorrt

### Environment

```Shell
- GCC 9.4
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_87,code=sm_87
  - CuDNN 8.4.1
    - Built with CuDNN 8.3.2
```

**Comment by RunningLeon** [comment]
hi, pls. try with fixed shape configs such as `configs/mmseg/segmentation_tensorrt_static-1024x2048.py`

**Comment by sammilei** [comment]
Thanks @RunningLeon for the quick reply. I used 512x512 to match the size but I got the same error :( :
You can duplicate it by doing this:

1. generate the onnx model: 
`ubuntu:~/Documents/mmdeploy$ python3 tools/torch2onnx.py configs/mmseg/segmentation_onnxruntime_dynamic.py ~/Documents/mmsegmentation/configs/segmenter/segmenter_vit-s_linear_8x1_512x512_160k_ade20k.py ~/Downloads/segmenter_vit-s_linear_8x1_512x512_160k_ade20k_20220105_151713-39658c46.pth an_image.jpg
`
3. attempts to convert it to tensorRT:
`ubuntu:~/Documents/mmdeploy$ python3 tools/onnx2tensorrt.py configs/mmseg/segmentation_tensorrt_static-512x512.py work-dir/end2end.onnx segmenter_vit-s_linear_8x1_512x512_160k_ade20k.tensorrt
`

It said [here](https://forums.developer.nvidia.com/t/ishufflelayer-applied-to-shape-tensor-must-have-0-or-1-reshape-dimensions-dimensions-were-1-2/200183/2) that I can resolve it by using the tensorRT but I got issue running the local built [TensorRT](https://github.com/NVIDIA/TensorRT/tree/master)

**Comment by sammilei** [comment]
@RunningLeon meanwhile. I was able to convert PSPNet from `.pth` to `.engine`: 
`python3 tools/torch2onnx.py configs/mmseg/segmentation_onnxruntime_dynamic.py ~/Documents/mmsegmentation/configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py ~/Downloads/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth image.jpg ` and 
`python3 tools/onnx2tensorrt.py configs/mmseg/segmentation_tensorrt_static-512x1024.py work-dir/end2end.onnx pspnet_512x1024.tensorrt` 

So the issue is only with segmenter unfortunately.

**Comment by RunningLeon** [comment]
> Thanks @RunningLeon for the quick reply. I used 512x512 to match the size but I got the same error :( : You can duplicate it by doing this:
> 
> 1. generate the onnx model:
>    `ubuntu:~/Documents/mmdeploy$ python3 tools/torch2onnx.py configs/mmseg/segmentation_onnxruntime_dynamic.py ~/Documents/mmsegmentation/configs/segmenter/segmenter_vit-s_linear_8x1_512x512_160k_ade20k.py ~/Downloads/segmenter_vit-s_linear_8x1_512x512_160k_ade20k_20220105_151713-39658c46.pth an_image.jpg `
> 2. attempts to convert it to tensorRT:
>    `ubuntu:~/Documents/mmdeploy$ python3 tools/onnx2tensorrt.py configs/mmseg/segmentation_tensorrt_static-512x512.py work-dir/end2end.onnx segmenter_vit-s_linear_8x1_512x512_160k_ade20k.tensorrt `
> 
> It said [here](https://forums.developer.nvidia.com/t/ishufflelayer-applied-to-shape-tensor-must-have-0-or-1-reshape-dimensions-dimensions-were-1-2/200183/2) that I can resolve it by using the tensorRT but I got issue running the local built [TensorRT](https://github.com/NVIDIA/TensorRT/tree/master)

@sammilei hi, you  could use deploy.py to do the work and use same deploy config
```
python3 tools/torch2onnx.py configs/mmseg/segmentation_tensorrt_static-512x512.py \
~/Documents/mmsegmentation/configs/segmenter/segmenter_vit-s_linear_8x1_512x512_160k_ade20k.py \
~/Downloads/segmenter_vit-s_linear_8x1_512x512_160k_ade20k_20220105_151713-39658c46.pth \
an_image.jpg \
--work-dir workdir \
--device cuda:0
```

**Comment by sammilei** [comment]
> > Thanks @RunningLeon for the quick reply. I used 512x512 to match the size but I got the same error :( : You can duplicate it by doing this:
> > 
> > 1. generate the onnx model:
> >    `ubuntu:~/Documents/mmdeploy$ python3 tools/torch2onnx.py configs/mmseg/segmentation_onnxruntime_dynamic.py ~/Documents/mmsegmentation/configs/segmenter/segmenter_vit-s_linear_8x1_512x512_160k_ade20k.py ~/Downloads/segmenter_vit-s_linear_8x1_512x512_160k_ade20k_20220105_151713-39658c46.pth an_image.jpg `
> > 2. attempts to convert it to tensorRT:
> >    `ubuntu:~/Documents/mmdeploy$ python3 tools/onnx2tensorrt.py configs/mmseg/segmentation_tensorrt_static-512x512.py work-dir/end2end.onnx segmenter_vit-s_linear_8x1_512x512_160k_ade20k.tensorrt `
> > 
> > It said [here](https://forums.developer.nvidia.com/t/ishufflelayer-applied-to-shape-tensor-must-have-0-or-1-reshape-dimensions-dimensions-were-1-2/200183/2) that I can resolve it by using the tensorRT but I got issue running the local built [TensorRT](https://github.com/NVIDIA/TensorRT/tree/master)
> 
> @sammilei hi, you could use deploy.py to do the work and use same deploy config
> 
> ```
> python3 tools/deploy.py configs/mmseg/segmentation_tensorrt_static-512x512.py \
> ~/Documents/mmsegmentation/configs/segmenter/segmenter_vit-s_linear_8x1_512x512_160k_ade20k.py \
> ~/Downloads/segmenter_vit-s_linear_8x1_512x512_160k_ade20k_20220105_151713-39658c46.pth \
> an_image.jpg \
> --work-dir workdir \
> --device cuda:0
> ```

It works!!! `deploy.py` got me the `.engine` and output the segmented images!! Thanks a ton!
