### ISSUE TITLE
error when I convert self-trained yolox detection model to onnxruntime

### ISSUE THREAD

**Issue by oym050922021** [open-mmlab/mmdeploy#2102]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I tried to convert the self-trained yolox detection model to onnxruntime, but it failed. 
Could you please help to have a look? Thanks!

### Reproduction

python tools/deploy.py
configs/mmdet/detection/detection_onnxruntime_dynamic.py
/root/Ouyangmei/openmmlab/mmdetection/configs/yolox/yolox_m_1xb2-300e_coco.py
/root/Ouyangmei/openmmlab/mmdetection/work_dirs/yolox_m_1xb2-300e_coco/epoch_300-CBAM.pth
/root/Ouyangmei/openmmlab/mmdetection/datasets/teeth/images/test/0128.png
--work-dir deploy_model/mmdet/ort
--dump-info

### Environment

```Shell
05/22 17:38:02 - mmengine - INFO - TorchVision: 0.14.1+cu117
05/22 17:38:02 - mmengine - INFO - OpenCV: 4.7.0
05/22 17:38:02 - mmengine - INFO - MMEngine: 0.7.2
05/22 17:38:02 - mmengine - INFO - MMCV: 2.0.0rc4
05/22 17:38:02 - mmengine - INFO - MMCV Compiler: GCC 9.3
05/22 17:38:02 - mmengine - INFO - MMCV CUDA Compiler: 11.7
05/22 17:38:02 - mmengine - INFO - MMDeploy: 1.0.0+8670d83
05/22 17:38:02 - mmengine - INFO - 

05/22 17:38:02 - mmengine - INFO - **********Backend information**********
05/22 17:38:02 - mmengine - INFO - tensorrt:    None
05/22 17:38:02 - mmengine - INFO - ONNXRuntime: 1.8.1
05/22 17:38:02 - mmengine - INFO - ONNXRuntime-gpu:     None
05/22 17:38:02 - mmengine - INFO - ONNXRuntime custom ops:      Available
05/22 17:38:02 - mmengine - INFO - pplnn:       None
05/22 17:38:02 - mmengine - INFO - ncnn:        None
05/22 17:38:02 - mmengine - INFO - snpe:        None
05/22 17:38:02 - mmengine - INFO - openvino:    None
05/22 17:38:02 - mmengine - INFO - torchscript: 1.13.1
05/22 17:38:02 - mmengine - INFO - torchscript custom ops:      NotAvailable
05/22 17:38:02 - mmengine - INFO - rknn-toolkit:        None
05/22 17:38:02 - mmengine - INFO - rknn-toolkit2:       None
05/22 17:38:02 - mmengine - INFO - ascend:      None
05/22 17:38:02 - mmengine - INFO - coreml:      None
05/22 17:38:02 - mmengine - INFO - tvm: None
05/22 17:38:02 - mmengine - INFO - vacc:        None
05/22 17:38:02 - mmengine - INFO - 

05/22 17:38:02 - mmengine - INFO - **********Codebase information**********
05/22 17:38:02 - mmengine - INFO - mmdet:       3.0.0
05/22 17:38:02 - mmengine - INFO - mmseg:       None
05/22 17:38:02 - mmengine - INFO - mmpretrain:  None
05/22 17:38:02 - mmengine - INFO - mmocr:       None
05/22 17:38:02 - mmengine - INFO - mmagic:      None
05/22 17:38:02 - mmengine - INFO - mmdet3d:     None
05/22 17:38:02 - mmengine - INFO - mmpose:      None
05/22 17:38:02 - mmengine - INFO - mmrotate:    None
05/22 17:38:02 - mmengine - INFO - mmaction:    None
05/22 17:38:02 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
(oym) root@h2-02:~/Ouyangmei/openmmlab/mmdeploy# python tools/deploy.py --show  --dump-info
05/22 17:54:43 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/22 17:54:43 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/22 17:54:44 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
05/22 17:54:44 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/22 17:54:44 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
***************neck attention*******************
Loads checkpoint by local backend from path: /root/Ouyangmei/openmmlab/mmdetection/work_dirs/yolox_m_1xb2-300e_coco/epoch_300-CBAM.pth
05/22 17:54:45 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
05/22 17:54:45 - mmengine - INFO - Export PyTorch model to ONNX: deploy_model/mmdet/ort/end2end.onnx.
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/core/optimizers/function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
Process Process-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/oym/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/oym/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/onnx/export.py", line 131, in export
    torch.onnx.export(
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/onnx/export.py", line 123, in wrapper
    return forward(*arg, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py", line 89, in single_stage_detector__forward
    return __forward_impl(self, batch_inputs, data_samples=data_samples)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/core/optimizers/function_marker.py", line 266, in g
    rets = f(*args, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/codebase/mmdet/models/detectors/single_stage.py", line 22, in __forward_impl
    x = self.extract_feat(batch_inputs)
  File "/root/Ouyangmei/openmmlab/mmdetection/mmdet/models/detectors/single_stage.py", line 148, in extract_feat
    x = self.neck(x)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdetection/mmdet/models/necks/yolox_pafpn.py", line 194, in forward
    outs[idx] = self.attention_module_list[idx](tmp_feature)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdetection/mmdet/models/layers/se_layer.py", line 100, in forward
    x = x * self.channelattention(x)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/Ouyangmei/openmmlab/mmdetection/mmdet/models/layers/se_layer.py", line 58, in forward
    avg_out = self.fc2(self.relu(self.fc1(self.avg_pool(x))))
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:
(1,1,.,.) = 
 0.01 *

[ torch.cuda.FloatTensor{24,192,1,1} ]
05/22 17:55:21 - mmengine - ERROR - /root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by RunningLeon** [comment]
@huayuan4396 Could you take a look at this issue?

**Comment by huayuan4396** [comment]
OK

**Comment by oym050922021** [comment]
> OK

@huayuan4396  hello, is the above question  caused by the attention mechanism CBAM which I added to yolox model? When I remove the CBAM module,  the onnx file can be generated and a new problem will appear.  Will this new problem affect the predicted results please?  Thank you very much!


**Reproduction:**
python tools/deploy.py
configs/mmdet/detection/detection_onnxruntime_dynamic.py
/root/Ouyangmei/openmmlab/mmdetection/configs/yolox/yolox_m_1xb2-300e_coco.py
/root/Ouyangmei/openmmlab/mmdetection/work_dirs/yolox_m_1xb2-300e_coco/epoch_300.pth
/root/Ouyangmei/openmmlab/mmdetection/datasets/teeth/images/test/0128.png
--work-dir deploy_model/mmdet/ort
--dump-info


**onnx file:**
Generate 4 files: pipeline.json, end2end.onnx, detail.json, deploy.json



**Error traceback:**

05/24 19:24:46 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/24 19:24:46 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/24 19:24:46 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
05/24 19:24:47 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/24 19:24:47 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: /root/Ouyangmei/openmmlab/mmdetection/work_dirs/yolox_m_1xb2-300e_coco/best_coco_bbox_mAP_epoch_80-CIou.pth
05/24 19:24:47 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
05/24 19:24:47 - mmengine - INFO - Export PyTorch model to ONNX: mmdeploy_models/mmdetection/yolox/end2end.onnx.
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/core/optimizers/function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525539683/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/mmcv/ops/nms.py:270: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/mmcv/ops/nms.py:271: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/pytorch/functions/topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/mmcv/ops/nms.py:44: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/mmcv/ops/nms.py:45: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/root/anaconda3/envs/oym/lib/python3.9/site-packages/mmcv/ops/nms.py:123: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/root/anaconda3/envs/oym/lib/python3.9/site-packages/mmcv/ops/nms.py:124: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/root/anaconda3/envs/oym/lib/python3.9/site-packages/torch/onnx/symbolic_opset9.py:5408: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn(
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/mmcv/ops/nms.py:86: FutureWarning: 'torch.onnx._patch_torch._graph_op' is deprecated in version 1.13 and will be removed in version 1.14. Please note 'g.op()' is to be removed from torch.Graph. Please open a GitHub issue if you need this functionality..
  max_output_boxes_per_class = g.op(
/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/mmcv/ops/nms.py:100: FutureWarning: 'torch.onnx._patch_torch._graph_op' is deprecated in version 1.13 and will be removed in version 1.14. Please note 'g.op()' is to be removed from torch.Graph. Please open a GitHub issue if you need this functionality..
  return g.op('NonMaxSuppression', boxes, scores,
05/24 19:24:49 - mmengine - INFO - Execute onnx optimize passes.
05/24 19:24:49 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
05/24 19:24:49 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
05/24 19:24:49 - mmengine - INFO - Finish pipeline mmdeploy.apis.utils.utils.to_backend
05/24 19:24:49 - mmengine - INFO - visualize onnxruntime model start.
05/24 19:24:52 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/24 19:24:52 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/24 19:24:52 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "backend_detectors" registry tree. As a workaround, the current "backend_detectors" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/24 19:24:52 - mmengine - INFO - Successfully loaded onnxruntime custom ops from /root/Ouyangmei/openmmlab/mmdeploy/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so
05/24 19:24:52 - mmengine - ERROR - /root/Ouyangmei/openmmlab/mmdeploy/tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.

**Comment by huayuan4396** [comment]
Hi, @oym050922021  I notice that you use a model config `yolox_m_1xb2-300e_coco.py` which is not in `mmdetection/config/yolox` , could you provide this file? Since I tried `yolox_s_8xb8-300e_coco.py` provided by `mmdet` and it works fine.

**Comment by oym050922021** [comment]
@huayuan4396  hi, thank you for your reply. The configs file is as follows:

**the configs file (yolox_m_1xb2-300e_coco.py)**

_base_ = './yolox_s_8xb8-300e_coco.py'

# model settings
model = dict(backbone=dict(deepen_factor=0.67, widen_factor=0.75),
             neck=dict(in_channels=[192, 384, 768], out_channels=192, num_csp_blocks=2),  
             bbox_head=dict(in_channels=192, 
                            feat_channels=192,        
                            loss_cls=dict(
                                 _delete_=True,
                                 type='VarifocalLoss',
                                 use_sigmoid=True,
                                 reduction='sum',
                                 alpha=0.75,
                                 gamma=2.0,
                                 iou_weighted=True,
                                 loss_weight=1.0),
                            loss_bbox=dict(
                                 _delete_=True,
                                 type='CIoULoss',  
                                 eps=1e-16,
                                 reduction='sum',
                                 loss_weight=5.0),
                            loss_obj=dict(     
                                 _delete_=True,
                                 type='FocalLoss',
                                 use_sigmoid=True,
                                 reduction='sum',
                                 gamma=2.0,
                                 alpha=0.25,
                                 loss_weight = 1.0),
                            loss_l1=dict(type='L1Loss', reduction='sum', loss_weight=1.0)))

load_from = "./work_dirs/yolox_m_1xb2-300e_coco/best_coco_bbox_mAP_epoch_80-CIou.pth"      
resume = None

**Comment by swantyhi** [comment]
我遇到的情况好像一样，期待大神解决。
(yolo) PS C:\AI\mmdeploy> python tools/deploy.py `
>>     configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py `
>>     ../mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py `
>>     ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth `
>>     ../mmdetection/demo/demo.jpg `
>>     --work-dir mmdeploy_model/faster-rcnn `
>>     --device cuda `
>>     --dump-info
05/25 15:55:48 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/25 15:55:48 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/25 15:55:52 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
05/25 15:55:53 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
05/25 15:55:53 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: ../mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
05/25 15:55:56 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
05/25 15:55:56 - mmengine - INFO - Export PyTorch model to ONNX: mmdeploy_model/faster-rcnn\end2end.onnx.
05/25 15:55:56 - mmengine - WARNING - Can not find torch.nn.functional._scaled_dot_product_attention, function rewrite will not be applied
05/25 15:55:56 - mmengine - WARNING - Can not find mmdet.models.utils.transformer.PatchMerging.forward, function rewrite will not be applied
c:\ai\mmdeploy\mmdeploy\core\optimizers\function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
c:\ai\mmdetection\mmdet\models\dense_heads\anchor_head.py:115: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
c:\ai\mmdetection\mmdet\models\task_modules\prior_generators\anchor_generator.py:356: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors``
  warnings.warn('``grid_anchors`` would be deprecated soon. '
c:\ai\mmdetection\mmdet\models\task_modules\prior_generators\anchor_generator.py:392: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  warnings.warn(
c:\ai\mmdeploy\mmdeploy\codebase\mmdet\models\dense_heads\rpn_head.py:89: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
c:\ai\mmdeploy\mmdeploy\pytorch\functions\topk.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
c:\ai\mmdeploy\mmdeploy\codebase\mmdet\models\task_modules\coders\delta_xywh_bbox_coder.py:38: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
c:\ai\mmdeploy\mmdeploy\codebase\mmdet\models\task_modules\coders\delta_xywh_bbox_coder.py:40: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
c:\ai\mmdeploy\mmdeploy\codebase\mmdet\deploy\utils.py:95: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
c:\ai\mmdeploy\mmdeploy\mmcv\ops\nms.py:451: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(scores.shape[-1]),
c:\ai\mmdeploy\mmdeploy\mmcv\ops\nms.py:148: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
c:\ai\mmdeploy\mmdeploy\codebase\mmdet\models\roi_heads\standard_roi_head.py:41: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  rois_dims = int(rois.shape[-1])
05/25 15:56:23 - mmengine - ERROR - c:\ai\mmdeploy\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 84 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

**Comment by oym050922021** [comment]
@huayuan4396  hi, the problem has been fixed. The onnxruntime version can cause the model conversion  error in the cpu.

**Comment by swantyhi** [comment]
> 6 hi, the problem has been fixed. The onnxruntime version can cause the model conversion error in the cpu

Could you help me to fix the problem? Thank you

**Comment by swantyhi** [comment]
It's Okay Now 

> hi, the problem has been fixed.

the problem has been fixed. I change another config file ,then another problem happens , and it is okay when I changed the config file back.
