### ISSUE TITLE
[Docs] How to deploy an unsupported model

### ISSUE THREAD

**Issue by vavanade** [open-mmlab/mmdeploy#2110]
### 📚 The doc issue

Is there any documentation on how to create support for deployment of a model that is not yet supported? I'm particularly interested in the MMRotate models.

**Comment by RunningLeon** [comment]
@vavanade Hi, you can refer to the short tutorial: https://mmdeploy.readthedocs.io/en/latest/07-developer-guide/support_new_model.html
