### ISSUE TITLE
[Bug]  The python sdk result only shows the lower half of the picture

### ISSUE THREAD

**Issue by lxiaoxiaoxing** [open-mmlab/mmdeploy#2116]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/04-supported-codebases/mmseg.md#sdk%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86
I just followed the tutorial on this link, when I run python tools/deploy.py --show or backend model inference mmdeploy.apis, the result is correct, but when I use SDK model inference, it successfully saves the picture, but only has results in the lower half of the picture. How can I make the SDK inference result correct. This is a Baidu cloud link about the model and results, hope it helps you.
【超级会员V5】通过百度网盘分享的文件：tmp
链接:https://pan.baidu.com/s/1JhYqiwo6a5nk0wDsFKGZiQ 
提取码:oipi
复制这段内容打开「百度网盘APP 即可获取」

### Reproduction
```
from mmdeploy_runtime import Segmentor
import cv2
import numpy as np
img = cv2.imread('0001392.jpg')
segmentor = Segmentor(model_path='./onnx_out', device_name='cpu',device_id=0)
seg = segmentor(img)
palette = np.random.randint(0, 256, size=(256, 3))
color_seg = np.zeros((seg.shape[0], seg.shape[1], 3), dtype=np.uint8)
for label, color in enumerate(palette):
    color_seg[seg == label, :] = color
color_seg = color_seg[..., ::-1]
img = img * 0.5 + color_seg * 0.5
img = img.astype(np.uint8)
cv2.imwrite('output_segmentation.png', img)
```
### Environment

```Shell
05/25 10:02:14 - mmengine - INFO - TorchVision: 0.11.0+cpu
05/25 10:02:14 - mmengine - INFO - OpenCV: 4.6.0
05/25 10:02:14 - mmengine - INFO - MMEngine: 0.7.3
05/25 10:02:14 - mmengine - INFO - MMCV: 2.0.0
05/25 10:02:14 - mmengine - INFO - MMCV Compiler: GCC 7.3
05/25 10:02:14 - mmengine - INFO - MMCV CUDA Compiler: not available
05/25 10:02:14 - mmengine - INFO - MMDeploy: 1.1.0+faf05fe
05/25 10:02:14 - mmengine - INFO - 

05/25 10:02:14 - mmengine - INFO - **********Backend information**********
05/25 10:02:14 - mmengine - INFO - tensorrt:	None
05/25 10:02:14 - mmengine - INFO - ONNXRuntime:	1.8.1
05/25 10:02:14 - mmengine - INFO - ONNXRuntime-gpu:	None
05/25 10:02:14 - mmengine - INFO - ONNXRuntime custom ops:	Available
05/25 10:02:14 - mmengine - INFO - pplnn:	None
05/25 10:02:14 - mmengine - INFO - ncnn:	None
05/25 10:02:14 - mmengine - INFO - snpe:	None
05/25 10:02:14 - mmengine - INFO - openvino:	2022.3.0
05/25 10:02:14 - mmengine - INFO - torchscript:	1.10.0+cpu
05/25 10:02:14 - mmengine - INFO - torchscript custom ops:	NotAvailable
05/25 10:02:14 - mmengine - INFO - rknn-toolkit:	None
05/25 10:02:14 - mmengine - INFO - rknn-toolkit2:	None
05/25 10:02:14 - mmengine - INFO - ascend:	None
05/25 10:02:14 - mmengine - INFO - coreml:	None
05/25 10:02:14 - mmengine - INFO - tvm:	None
05/25 10:02:14 - mmengine - INFO - vacc:	None
05/25 10:02:14 - mmengine - INFO - 

05/25 10:02:14 - mmengine - INFO - **********Codebase information**********
05/25 10:02:14 - mmengine - INFO - mmdet:	None
05/25 10:02:14 - mmengine - INFO - mmseg:	1.0.0
05/25 10:02:14 - mmengine - INFO - mmpretrain:	None
05/25 10:02:14 - mmengine - INFO - mmocr:	None
05/25 10:02:14 - mmengine - INFO - mmagic:	None
05/25 10:02:14 - mmengine - INFO - mmdet3d:	None
05/25 10:02:14 - mmengine - INFO - mmpose:	None
05/25 10:02:14 - mmengine - INFO - mmrotate:	None
05/25 10:02:14 - mmengine - INFO - mmaction:	None
05/25 10:02:14 - mmengine - INFO - mmrazor:	None
```

**Comment by irexyc** [comment]
Hi @lxiaoxiaoxing ,

There is a bug in mmdeploy_runtime for Segmentor when use onnxruntime and cpu.

You can fix by changing it as PR2122  and rebuild the python api.

**Comment by RunningLeon** [comment]
[mmdeploy_runtime-1.1.0-cp36-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575161/mmdeploy_runtime-1.1.0-cp36-none-win_amd64.zip)
[mmdeploy_runtime-1.1.0-cp310-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575166/mmdeploy_runtime-1.1.0-cp310-none-win_amd64.zip)
[mmdeploy_runtime-1.1.0-cp37-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575168/mmdeploy_runtime-1.1.0-cp37-none-win_amd64.zip)
[mmdeploy_runtime-1.1.0-cp38-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575169/mmdeploy_runtime-1.1.0-cp38-none-win_amd64.zip)
[mmdeploy_runtime-1.1.0-cp39-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575170/mmdeploy_runtime-1.1.0-cp39-none-win_amd64.zip)

**Comment by lxiaoxiaoxing** [comment]
> Hi @lxiaoxiaoxing ,
> 
> There is a bug in mmdeploy_runtime for Segmentor when use onnxruntime and cpu.
> 
> You can fix by changing it as PR2122 and rebuild the python api.

I'm sorry, I don't understand. Can you please provide more details? It seems like you just made a change to a file under the 'mmdeploy' project. If I make changes to it, what should I do next to rebuild the Python API?

**Comment by lxiaoxiaoxing** [comment]
> [mmdeploy_runtime-1.1.0-cp36-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575161/mmdeploy_runtime-1.1.0-cp36-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp310-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575166/mmdeploy_runtime-1.1.0-cp310-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp37-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575168/mmdeploy_runtime-1.1.0-cp37-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp38-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575169/mmdeploy_runtime-1.1.0-cp38-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp39-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575170/mmdeploy_runtime-1.1.0-cp39-none-win_amd64.zip)

HI, Is this a new installation package to fix the bug? If it is, I need a Linux installation package, please. Thank you.

**Comment by RunningLeon** [comment]
> > [mmdeploy_runtime-1.1.0-cp36-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575161/mmdeploy_runtime-1.1.0-cp36-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp310-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575166/mmdeploy_runtime-1.1.0-cp310-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp37-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575168/mmdeploy_runtime-1.1.0-cp37-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp38-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575169/mmdeploy_runtime-1.1.0-cp38-none-win_amd64.zip) [mmdeploy_runtime-1.1.0-cp39-none-win_amd64.zip](https://github.com/open-mmlab/mmdeploy/files/11575170/mmdeploy_runtime-1.1.0-cp39-none-win_amd64.zip)
> 
> @RunningLeon HI, Is this a new installation package to fix the bug? If it is, I need a Linux installation package, please. Thank you.

@lxiaoxiaoxing Hi, this maybe is a mistake. You can ignore the comment.

**Comment by irexyc** [comment]
@lxiaoxiaoxing 

Hi, the linux installation package

链接: https://pan.baidu.com/s/10UmsuPj6ywVrhngAEnXcsw?pwd=fxxb 提取码: fxxb 
--来自百度网盘超级会员v6的分享

**Comment by lxiaoxiaoxing** [comment]
> @lxiaoxiaoxing
> 
> Hi, the linux installation package
> 
> 链接: https://pan.baidu.com/s/10UmsuPj6ywVrhngAEnXcsw?pwd=fxxb 提取码: fxxb --来自百度网盘超级会员v6的分享

Thanks. It solved my problem.
