### ISSUE TITLE
[Bug]ValueError: cpu is invalid for the backend tensorrt

### ISSUE THREAD

**Issue by wuasace** [open-mmlab/mmdeploy#2123]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

Traceback (most recent call last):
  File "tools/test.py", line 159, in <module>
    main()
  File "tools/test.py", line 105, in main
    task_processor = build_task_processor(model_cfg, deploy_cfg, args.device)
  File "/home/dell/MM3D/mmdeploy-main/mmdeploy/apis/utils/utils.py", line 43, in build_task_processor
    check_backend_device(deploy_cfg=deploy_cfg, device=device)
  File "/home/dell/MM3D/mmdeploy-main/mmdeploy/apis/utils/utils.py", line 28, in check_backend_device
    raise ValueError(f'{device} is invalid for the backend {backend}')
ValueError: cpu is invalid for the backend tensorrt

### Reproduction

python tools/test.py \
>     /home/dell/MM3D/mmdeploy-main/configs/mmpretrain/classification_tensorrt-fp16_static-384x384.py \
>     /home/dell/MM3D/mmpretrain/configs/resnet/resnet50_8xb16_cifar100.py \
>     --model /home/dell/MM3D/mmdeploy-main/work_dir/end2end.onnx \

### Environment

```Shell
1
```

**Comment by irexyc** [comment]
Please try :

```python
python tools/test.py \
/home/dell/MM3D/mmdeploy-main/configs/mmpretrain/classification_tensorrt-fp16_static-384x384.py \
/home/dell/MM3D/mmpretrain/configs/resnet/resnet50_8xb16_cifar100.py \
--model /home/dell/MM3D/mmdeploy-main/work_dir/end2end.engine \
--device cuda:0
```

**Comment by wuasace** [comment]
Hello, I would like to test the model inference of pointpicker now, which. pkl file do we need to use.

python tools/test.py \
    configs/mmpretrain/classification_onnxruntime_static.py \
    {MMPRETRAIN_DIR}/configs/resnet/resnet50_b32x8_imagenet.py \
    --model model.onnx \
    --out out.pkl \
    --device cuda:0


How to change this command? We are using TensorRT thank you ！

**Comment by wuasace** [comment]
> Please try :
> 
> ```python
> python tools/test.py \
> /home/dell/MM3D/mmdeploy-main/configs/mmpretrain/classification_tensorrt-fp16_static-384x384.py \
> /home/dell/MM3D/mmpretrain/configs/resnet/resnet50_8xb16_cifar100.py \
> --model /home/dell/MM3D/mmdeploy-main/work_dir/end2end.engine \
> --device cuda:0
> ```

Hello, I would like to test the model inference of pointpicker now, which. pkl file do we need to use.

python tools/test.py
configs/mmpretrain/classification_onnxruntime_static.py
{MMPRETRAIN_DIR}/configs/resnet/resnet50_b32x8_imagenet.py
--model model.onnx
--out out.pkl
--device cuda:0

How to change this command? We are using TensorRT thank you ！

**Comment by irexyc** [comment]
The first arg of `tools/test.py` is called `deploy_config`. If you want to test the model, you shouldn't pass `classification_onnxruntime_static.py` as it is used for onnxruntime.

You can have a look at https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/02-how-to-run/profile_model.md
