### ISSUE TITLE
关于骨骼点模型 C++demo的问题

### ISSUE THREAD

**Issue by ainndejj11** [open-mmlab/mmdeploy#2128]
### Motivation

请问下，mmpose中coco数据集的人体骨骼关键点，使用下载的预训练模型推理图片，像是输入这种半身的图片，也会输出17个点，腿和脚那就完全错误了。  这种情况怎么办，关键点阈值的源码在什么位置呢？

**Comment by irexyc** [comment]
c++ 的demo https://github.com/open-mmlab/mmdeploy/blob/main/demo/csrc/cpp/pose_detector.cxx#L25

res的定义可以看 
https://github.com/open-mmlab/mmdeploy/blob/main/csrc/mmdeploy/apis/cxx/mmdeploy/pose_detector.hpp#L13，https://github.com/open-mmlab/mmdeploy/blob/main/csrc/mmdeploy/apis/c/mmdeploy/pose_detector.h#L19-L23

```
typedef struct mmdeploy_pose_detection_t {
  mmdeploy_point_t* point;  ///< keypoint
  float* score;             ///< keypoint score
  int length;               ///< number of keypoint
} mmdeploy_pose_detection_t;
```

输出除了坐标外，有score的。你可以按照score来决定是否显示，但是我不确定这是不是一个可行的方式，因为一些模型采用regression的方式来得到点，然后分数全部为1.0。

建议你去mmpose repo下面问问算法的同学这种场景推荐的策略。
