### ISSUE TITLE
[Feature]Support for semantic segmentation, such as cyclinder 3D, minkunet, etc.？

### ISSUE THREAD

**Issue by CreepingBird** [open-mmlab/mmdeploy#2143]
### Motivation

Hello, may I ask if there is any support for semantic segmentation, such as cyclinder 3D, minkunet, etc. I look forward to your reply.

**Comment by RunningLeon** [comment]
hi, no [supported](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmseg.html#supported-models) model trained on this kind of dataset. Maybe you could create the dataset and train yourself.
