### ISSUE TITLE
[Bug] infer yolox onnx model used by python infrence sdk failed

### ISSUE THREAD

**Issue by PancakeAwesome** [open-mmlab/mmdeploy#2144]
used### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

code running until below:
bboxes, labels, _ = detector(img)
with errors:
### Reproduction

```
img = cv2.imread('mmyolo/data/6.jpg')

detector = Detector(model_path='mmdeploy_models/coco/yolox_s.py', device_name='cuda', device_id=0)
bboxes, labels, _ = detector(img)
```
errors:
Segmentation fault (core dumped)

### Environment

```Shell
### Environment

sys.platform: linux
Python: 3.8.16 (default, Mar 2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (GCC) 8.3.1 20190604
PyTorch: 2.0.0+cu117
TorchVision: 0.15.1+cu117
OpenCV: 4.7.0
MMEngine: 0.7.3
MMCV: 2.0.0
MMDetection: 3.0.0
MMYOLO: 0.5.0+
```
# onnx convert
python3 mmdeploy/tools/deploy.py \
    mmyolo/configs/deploy/detection_onnxruntime_static.py \
    mmyolo/yolox_s_fast_1xb32-300e-rtmdet-hyp_coco.py \
    mmyolo/yolox_s_fast_1xb32-300e-rtmdet-hyp_coco/best_coco_bbox_mAP_70.pth \
    mmyolo/data/6.jpg \
    --work-dir mmdeploy_models/coco/yolox_s_fast_1xb32-300e-rtmdet-hyp_guix \
    --device cuda:0 \
    --dump-info

used this config py: https://github.com/open-mmlab/mmyolo/blob/main/configs/deploy/detection_onnxruntime_dynamic.py

**Comment by RunningLeon** [comment]
@PancakeAwesome hi,  can you run `demo/python/object_detection.py` in [here](https://github.com/open-mmlab/mmdeploy/blob/main/demo/python/object_detection.py) and post here the error log?

**Comment by PancakeAwesome** [comment]
> @PancakeAwesome hi, can you run `demo/python/object_detection.py` in [here](https://github.com/open-mmlab/mmdeploy/blob/main/demo/python/object_detection.py) and post here the error log?

here is log:
loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-06-02 17:02:20.818] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "../mmdeploy_models//yolox_s_fast_1xb32-300e-rtmdet-hyp_/"
[2023-06-02 17:02:21.061] [mmdeploy] [error] [compose.cpp:37] Unable to find Transform creator: mmdet.Resize. Available transforms: [("CenterCrop", 0), ("Collect", 0), ("Compose", 0), ("DefaultFormatBundle", 0), ("FormatShape", 0), ("ImageToTensor", 0), ("LetterResize", 0), ("Lift", 0), ("LoadImageFromFile", 0), ("Normalize", 0), ("Pad", 0), ("RescaleToHeight", 0), ("Resize", 0), ("ResizeOCR", 0), ("ShortScaleAspectJitter", 0), ("TenCrop", 0), ("ThreeCrop", 0), ("TopDownAffine", 0), ("TopDownGetBboxCenterScale", 0)]
[2023-06-02 17:02:21.061] [mmdeploy] [error] [task.cpp:99] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "file_client_args": {
        "backend": "disk"
      },
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "scale": [
        640,
        640
      ],
      "type": "mmdet.Resize"
    },
    {
      "pad_to_square": true,
      "pad_val": {
        "img": [
          114.0,
          114.0,
          114.0
        ]
      },
      "type": "mmdet.Pad"
    },
    {
      "mean": [
        0,
        0,
        0
      ],
      "std": [
        1,
        1,
        1
      ],
      "to_rgb": false,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "type": "DefaultFormatBundle"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "valid_ratio",
        "img_shape",
        "img_id",
        "flip",
        "img_norm_cfg",
        "img_path",
        "ori_filename",
        "flip_direction",
        "scale_factor",
        "pad_param",
        "ori_shape",
        "filename",
        "pad_shape"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
Segmentation fault (core dumped)

**Comment by PancakeAwesome** [comment]
> @PancakeAwesome hi, can you run `demo/python/object_detection.py` in [here](https://github.com/open-mmlab/mmdeploy/blob/main/demo/python/object_detection.py) and post here the error log?

after modify pipeline json here is error log:
`$python mmdeploy/demo/python/object_detection.py cpu ./mmdeploy_models/yolox_s_fast_1xb32-300e-rtmdet-hyp/  ./data/20230524_trainv2/coco/images/trainval/1206.jpg 
loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-06-02 17:30:31.395] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "./mmdeploy_models/yolox_s_fast_1xb32-300e-rtmdet-hyp/"
[2023-06-02 17:30:31.396] [mmdeploy] [error] [compose.cpp:37] Unable to find Transform creator: mmdet.Resize. Available transforms: [("CenterCrop", 0), ("Collect", 0), ("Compose", 0), ("DefaultFormatBundle", 0), ("FormatShape", 0), ("ImageToTensor", 0), ("LetterResize", 0), ("Lift", 0), ("LoadImageFromFile", 0), ("Normalize", 0), ("Pad", 0), ("RescaleToHeight", 0), ("Resize", 0), ("ResizeOCR", 0), ("ShortScaleAspectJitter", 0), ("TenCrop", 0), ("ThreeCrop", 0), ("TopDownAffine", 0), ("TopDownGetBboxCenterScale", 0)]
[2023-06-02 17:30:31.396] [mmdeploy] [error] [task.cpp:99] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "file_client_args": {
        "backend": "disk"
      },
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "size": [
        640,
        640
      ],
      "type": "mmdet.Resize"
    },
    {
      "pad_to_square": true,
      "pad_val": {
        "img": [
          114.0,
          114.0,
          114.0
        ]
      },
      "type": "Pad"
    },
    {
      "mean": [
        0,
        0,
        0
      ],
      "std": [
        1,
        1,
        1
      ],
      "to_rgb": false,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "type": "DefaultFormatBundle"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "valid_ratio",
        "img_shape",
        "img_id",
        "flip",
        "img_norm_cfg",
        "img_path",
        "ori_filename",
        "flip_direction",
        "scale_factor",
        "pad_param",
        "ori_shape",
        "filename",
        "pad_shape"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
Segmentation fault (core dumped)`
