### ISSUE TITLE
how to load so for c++ engine inference?

### ISSUE THREAD

**Issue by shuyuan-wang** [open-mmlab/mmdeploy#2145]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I can find how python load the so file and load the plugin. Is there an example of how C++ load the so file and init the engine? Not using h file?

### Reproduction

As above, general question

### Environment

```Shell
As above, general question
```

**Comment by RunningLeon** [comment]
@shuyuan-wang hi, did you mean here?
https://github.com/open-mmlab/mmdeploy/blob/a26945cb070382d71ccbc98e7ba51515bf06c7c3/csrc/mmdeploy/net/trt/CMakeLists.txt#L12

**Comment by shuyuan-wang** [comment]
> @shuyuan-wang hi, did you mean here?
> 
> https://github.com/open-mmlab/mmdeploy/blob/a26945cb070382d71ccbc98e7ba51515bf06c7c3/csrc/mmdeploy/net/trt/CMakeLists.txt#L12

Could be, I now directly dlopen the so file and it works. I'll try this later. Closing
