### ISSUE TITLE
int 8 and fp16 accuracy

### ISSUE THREAD

**Issue by blue-q** [open-mmlab/mmdeploy#2150]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I trained a model, and the accuracy is ok when using pth test, but after converting to fp16 or int8, I tested a number of different categories of videos, the output category is the same, and the score is less than 1, but the same video is predicted with pth model and the score is relatively large, what is the reason? I trained a model, The accuracy is ok when using pth test, but after converting to fp16 or int8, multiple different categories of videos are tested, the output category is the same, and the score is less than 1, but the same video is predicted with pth model and the score is relatively large, what is the reason

### Reproduction

python tools/deploy.py     configs/mmaction/video-recognition/video-recognition_2d_tensorrt_static-224x224.py     tsn_imagenet-pretrained-r50_8xb32-1x1x3-100e_kinetics400-rgb.py    best_acc_top1_epoch_24.pth     tests/data/arm_wrestling.mp4     --work-dir mmdeploy_models/mmaction/tsn_fp16_test/ort     --device cuda     --show     --dump-info

### Environment

```Shell
06/05 10:20:07 - mmengine - INFO - **********Backend information**********
06/05 10:20:07 - mmengine - INFO - tensorrt:    7.2.3.4
06/05 10:20:07 - mmengine - INFO - tensorrt custom ops: Available
06/05 10:20:07 - mmengine - INFO - ONNXRuntime: None
06/05 10:20:07 - mmengine - INFO - pplnn:       None
06/05 10:20:07 - mmengine - INFO - ncnn:        None
06/05 10:20:07 - mmengine - INFO - snpe:        None
06/05 10:20:07 - mmengine - INFO - openvino:    None
06/05 10:20:07 - mmengine - INFO - torchscript: 1.12.1
06/05 10:20:07 - mmengine - INFO - torchscript custom ops:      NotAvailable
06/05 10:20:07 - mmengine - INFO - rknn-toolkit:        None
06/05 10:20:07 - mmengine - INFO - rknn-toolkit2:       None
06/05 10:20:07 - mmengine - INFO - ascend:      None
06/05 10:20:07 - mmengine - INFO - coreml:      None
06/05 10:20:07 - mmengine - INFO - tvm: None
06/05 10:20:07 - mmengine - INFO - vacc:        None
06/05 10:20:07 - mmengine - INFO -
```

**Comment by irexyc** [comment]
Hi @blue-q , could you provide the test script and bug video that you have different results with pth and tensorrt.

**Comment by blue-q** [comment]
> Hi @blue-q , could you provide the test script and bug video that you have different results with pth and tensorrt.

I found the reason, in mmdeploy.so all use cv::mat, but I use cv::cuda::gpumat so this problem occurs, mmdeploy currently does not support gpumat? For the tsn task of video classification, if I wanted to change the relevant cpumat in mmdeploy to gpumat, how much work would I need to do and what changes would I need to make.

**Comment by irexyc** [comment]
Hi @blue-q ,

You can use gpumat but make the data is continous.

I make some changes to demo/csrc/c/image_classification.cpp that you can refer to:

```cpp
#include <fstream>
#include <opencv2/core/cuda.hpp>
#include <opencv2/imgcodecs/imgcodecs.hpp>
#include <string>

#include "mmdeploy/classifier.h"

int main(int argc, char* argv[]) {
  if (argc != 4) {
    fprintf(stderr, "usage:\n  image_classification device_name dump_model_directory image_path\n");
    return 1;
  }
  auto device_name = argv[1];
  auto model_path = argv[2];
  auto image_path = argv[3];
  cv::Mat img = cv::imread(image_path);
  if (!img.data) {
    fprintf(stderr, "failed to load image: %s\n", image_path);
    return 1;
  }

  mmdeploy_classifier_t classifier{};
  int status{};
  status = mmdeploy_classifier_create_by_path(model_path, device_name, 0, &classifier);
  if (status != MMDEPLOY_SUCCESS) {
    fprintf(stderr, "failed to create classifier, code: %d\n", (int)status);
    return 1;
  }

  // mmdeploy_mat_t mat{
  //     img.data, img.rows, img.cols, 3, MMDEPLOY_PIXEL_FORMAT_BGR, MMDEPLOY_DATA_TYPE_UINT8};

  cv::cuda::GpuMat gpumat;
  cv::cuda::createContinuous(img.rows, img.cols, img.type(), gpumat);

  gpumat.upload(img);
  // printf("gpumat.isContinuous() %d\n", (int)gpumat.isContinuous());
  mmdeploy_device_t device;
  mmdeploy_device_create("cuda", 0, &device);
  mmdeploy_mat_t mat{
      gpumat.data, img.rows, img.cols, 3, MMDEPLOY_PIXEL_FORMAT_BGR, MMDEPLOY_DATA_TYPE_UINT8,
      device};

  mmdeploy_classification_t* res{};
  int* res_count{};
  status = mmdeploy_classifier_apply(classifier, &mat, 1, &res, &res_count);
  if (status != MMDEPLOY_SUCCESS) {
    fprintf(stderr, "failed to apply classifier, code: %d\n", (int)status);
    return 1;
  }
  for (int i = 0; i < res_count[0]; ++i) {
    fprintf(stderr, "label: %d, score: %.4f\n", res[i].label_id, res[i].score);
  }

  mmdeploy_classifier_release_result(res, res_count, 1);

  mmdeploy_classifier_destroy(classifier);

  mmdeploy_device_destroy(device);

  return 0;
}

```

You have to manage the lifetime of gpumat.data

**Comment by blue-q** [comment]
Here is my code, the doinfer function calls mmdeploy_video_recognizer_apply method and mmdeploy_video_recognizer_create_by_path method of mmdeploy.so for model loading and inference. The purpose of the doinfer method is to perform real-time action classification, and the input is gpumat. The buffer is std::map<int, cv::cuda::GpuMat>, and copy_frame is std::vector<cv::cuda::GpuMat>. The problem is that when I input gpumat, mmdeploy_video_recognizer_apply gets inaccurate inference results, but when I uniformly change to cv::mat, the prediction is relatively accurate. What is the reason?

`infer_res fightDetect::doinfer(const cv::cuda::GpuMat& _image,const char* model_path, const int clip_len,const int frame_interval,const int num_clips, const int num_frames)
{
    float t_time_use = 0;
    struct timeval start;
    struct timeval end;
    gettimeofday(&start, NULL);
    //-------------------------------

    std::map<int, cv::cuda::GpuMat> buffer;
    std::vector<mmdeploy_mat_t> clips;
    std::vector<mmdeploy_video_sample_info_t> clip_info;
   

    int ori_clip_len = clip_len * frame_interval;
    float avg_interval = (num_frames - ori_clip_len + 1.f) / num_clips;

    std::vector<int> frame_inds;
    // num_clips=10
    for (int i = 0; i < num_clips; i++) {
        //间隔7 3.5 10.5 17.5 24.5 31.5 38.5 45.5 52.5 59.5 66.5
        int clip_offset = i * avg_interval + avg_interval / 2.0; 
        
        for (int j = 0; j < clip_len; j++) {
            int ind = (j * frame_interval + clip_offset) % num_frames;
            if (num_frames <= ori_clip_len - 1) {
                ind = j % num_frames;
            }
            frame_inds.push_back(ind);
        }
    }

    std::vector<int> unique_inds(frame_inds.begin(), frame_inds.end());
    std::sort(unique_inds.begin(), unique_inds.end());
    auto last = std::unique(unique_inds.begin(), unique_inds.end());
    unique_inds.erase(last, unique_inds.end());


    gettimeofday(&end, NULL);
    t_time_use = (end.tv_sec - start.tv_sec) * 1000.0 + (end.tv_usec - start.tv_usec) / 1000.0;
    cout <<"frame process time is :"<< t_time_use << endl;
    //-------------------------------


    //图像判断是否满足队列长度
    if(copy_frame.size() <num_frames){
        copy_frame.push_back(_image);

    }else if(copy_frame.size() == num_frames){
        gettimeofday(&start, NULL);

        for (int i = 0; i < unique_inds.size(); i++) {
            int tid = unique_inds[i];
            buffer[tid] = copy_frame[tid]; 
        }
        copy_frame.erase(copy_frame.begin());
        copy_frame.push_back(_image);

        clips.resize(frame_inds.size());
        for (int i = 0; i < frame_inds.size(); i++) {
            auto& img = buffer[frame_inds[i]];
            mmdeploy_mat_t mat{
                img.data, img.rows, img.cols, 3, MMDEPLOY_PIXEL_FORMAT_BGR, MMDEPLOY_DATA_TYPE_UINT8};
            clips[i] = mat;
        }

        clip_info.push_back({clip_len, num_clips});

        gettimeofday(&end, NULL);
        t_time_use = (end.tv_sec - start.tv_sec) * 1000.0 + (end.tv_usec - start.tv_usec) / 1000.0;
        cout <<"clips process time is :"<< t_time_use << endl;
        gettimeofday(&start, NULL);


        // mmdeploy_video_recognizer_t recognizer{};
        int status{};
        if (recognizer == nullptr){
            status = mmdeploy_video_recognizer_create_by_path(model_path, "cuda", 0, &recognizer); //300ms这个单独拿出来，不用写到doinfer里面 模型只加载一次（判断recognizer是否为空）
            if (status != MMDEPLOY_SUCCESS) {
                fprintf(stderr, "failed to create recognizer, code: %d\n", (int)status);
                infer_res1.label_id = -1;
                infer_res1.score = -1;

                return infer_res1;
                // return -1;
            }
            std::cout<<"recognizer00000000:   "<<recognizer<<std::endl;
        }
        
        gettimeofday(&end, NULL);
        t_time_use = (end.tv_sec - start.tv_sec) * 1000.0 + (end.tv_usec - start.tv_usec) / 1000.0;
        cout <<"mmdeploy_video_recognizer_create_by_path process time is :"<< t_time_use << endl;
        gettimeofday(&start, NULL);
        mmdeploy_video_recognition_t* res{};
        int* res_count{};
        //推理
        status = mmdeploy_video_recognizer_apply(recognizer, clips.data(), clip_info.data(), 1, &res,
                                                &res_count);
        
        gettimeofday(&end, NULL);
        t_time_use = (end.tv_sec - start.tv_sec) * 1000.0 + (end.tv_usec - start.tv_usec) / 1000.0;
        cout <<"mmdeploy_video_recognizer_apply process time is :"<< t_time_use << endl;

        if (status != MMDEPLOY_SUCCESS) {
            fprintf(stderr, "failed to apply classifier, code: %d\n", (int)status);
            // return -1;
            infer_res1.label_id = -1;
            infer_res1.score = -1;

            return infer_res1;
        }

        int label_id = -2;
        float score = -100.;
        for (int i = 0; i < res_count[0]; ++i) {
            fprintf(stderr, "label: %d, score: %.4f\n", res[i].label_id, res[i].score);
            label_id = res[i].label_id;
            score = res[i].score;
            std::cout<<"label_id: "<<label_id<<std::endl;
            std::cout<<"score: "<<score<<std::endl;
            infer_res1.label_id = res[i].label_id;
            infer_res1.score = res[i].score;
        }

        mmdeploy_video_recognizer_release_result(res, res_count, 1);
        // mmdeploy_video_recognizer_destroy(recognizer);
        mmdeploy_device_destroy(device);


        // return label_id;
        return infer_res1;
    }
    // mmdeploy_video_recognizer_destroy(recognizer);
    fprintf(stderr, "failed to do infer");
    // return -1;
    infer_res1.label_id = -1;
    infer_res1.score = -1;

    return infer_res1;
}`

**Comment by irexyc** [comment]
@blue-q 

你可以看下上面我修改的代码和仓库中代码的区别。主要的就是一点，创建mmdeploy_mat_t的时候，会有一个device参数，你的代码里面没有。

```cpp
mmdeploy_mat_t mat{
      gpumat.data, img.rows, img.cols, 3, MMDEPLOY_PIXEL_FORMAT_BGR, MMDEPLOY_DATA_TYPE_UINT8,
      device};
```


另外mmdeploy_mat_t中的data内存是需要连续的。你的代码中，没有体现_image是怎么得到的，你可以用[isContinuous()](https://docs.opencv.org/3.4/d0/d60/classcv_1_1cuda_1_1GpuMat.html#a400fc4c7880bf132f2ffea03892486b0)来检查是否连续。如果不连续，可能需要使用`createContinuous`和`copyTo`来达到目的。

还有就是Gpumat的创建销毁也挺耗时的，你可以考虑使用显存池来规避这一点。
