### ISSUE TITLE
[Bug] The TensorRT model occasionally produces all zeros detection boxes

### ISSUE THREAD

**Issue by Josh1021** [open-mmlab/mmdeploy#2151]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I have converted my own model using mmdeploy and used SDK for inference, the onnx model works correctly on different graphics cards, but the TensorRT model occasionally produces all zeros detection boxes with different score only on the 1060 using docker, this problem occurs with a relatively high probability, could you please advise me how to locate this problem? 
this is pipeline.json
```
{
    "pipeline": {
        "input": [
            "img"
        ],
        "output": [
            "post_output"
        ],
        "tasks": [
            {
                "type": "Task",
                "module": "Transform",
                "name": "Preprocess",
                "input": [
                    "img"
                ],
                "output": [
                    "prep_output"
                ],
                "transforms": [
                    {
                        "type": "LoadImageFromFile"
                    },
                    {
                        "type": "FixResize",
                        "scale": 1.2000000000000002,
                        "max_area": 1210000
                    },
                    {
                        "type": "Normalize",
                        "mean": [
                            243.13,
                            239.5,
                            248.55
                        ],
                        "std": [
                            32.26,
                            40.86,
                            16.42
                        ],
                        "to_rgb": true
                    },
                    {
                        "type": "Pad",
                        "size_divisor": 32
                    },
                    {
                        "type": "DefaultFormatBundle"
                    },
                    {
                        "type": "Collect",
                        "keys": [
                            "img"
                        ],
                        "meta_keys": [
                            "scale_factor",
                            "flip_direction",
                            "filename",
                            "valid_ratio",
                            "ori_filename",
                            "img_shape",
                            "img_norm_cfg",
                            "pad_shape",
                            "flip",
                            "ori_shape"
                        ]
                    }
                ]
            },
            {
                "name": "xdetnet",
                "type": "Task",
                "module": "Net",
                "is_batched": true,
                "input": [
                    "prep_output"
                ],
                "output": [
                    "infer_output"
                ],
                "input_map": {
                    "img": "input"
                },
                "output_map": {}
            },
            {
                "type": "Task",
                "module": "mmdet",
                "name": "postprocess",
                "component": "ResizeBBox",
                "params": {
                    "rpn": {
                        "nms_pre": 1000,
                        "max_per_img": 1000,
                        "nms": {
                            "type": "nms",
                            "iou_threshold": 0.85
                        },
                        "min_bbox_size": 0
                    },
                    "rcnn": {
                        "score_thr": 0.05,
                        "nms": {
                            "type": "nms",
                            "iou_threshold": 0.5
                        },
                        "max_per_img": 100
                    },
                    "min_bbox_size": 0,
                    "score_thr": 0.05
                },
                "output": [
                    "post_output"
                ],
                "input": [
                    "prep_output",
                    "infer_output"
                ]
            }
        ]
    }
}
```

### Reproduction

1 python mmdeploy/build/install/example/python/object_detection.py cuda trt_model/ demo.jpg

2 I have tried the TensorRT model of Cascade_rcnn and it is working properly on 1060.

### Environment

```Shell
2023-06-05 06:38:58,268 - mmdeploy - INFO - 

2023-06-05 06:38:58,268 - mmdeploy - INFO - **********Environmental information**********
2023-06-05 06:39:00,520 - mmdeploy - INFO - sys.platform: linux
2023-06-05 06:39:00,521 - mmdeploy - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
2023-06-05 06:39:00,521 - mmdeploy - INFO - CUDA available: True
2023-06-05 06:39:00,521 - mmdeploy - INFO - GPU 0: NVIDIA GeForce GTX 1060 6GB
2023-06-05 06:39:00,521 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-06-05 06:39:00,521 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
2023-06-05 06:39:00,521 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2023-06-05 06:39:00,521 - mmdeploy - INFO - PyTorch: 1.10.0
2023-06-05 06:39:00,521 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2023-06-05 06:39:00,521 - mmdeploy - INFO - TorchVision: 0.11.0
2023-06-05 06:39:00,521 - mmdeploy - INFO - OpenCV: 4.7.0
2023-06-05 06:39:00,521 - mmdeploy - INFO - MMCV: 1.5.3
2023-06-05 06:39:00,521 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2023-06-05 06:39:00,521 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2023-06-05 06:39:00,521 - mmdeploy - INFO - MMDeploy: 0.14.0+c737563
2023-06-05 06:39:00,521 - mmdeploy - INFO - 

2023-06-05 06:39:00,521 - mmdeploy - INFO - **********Backend information**********
2023-06-05 06:39:00,863 - mmdeploy - INFO - tensorrt:	8.2.4.2
2023-06-05 06:39:00,863 - mmdeploy - INFO - tensorrt custom ops:	Available
2023-06-05 06:39:01,364 - mmdeploy - INFO - ONNXRuntime:	None
2023-06-05 06:39:01,364 - mmdeploy - INFO - ONNXRuntime-gpu:	1.8.1
2023-06-05 06:39:01,364 - mmdeploy - INFO - ONNXRuntime custom ops:	Available
2023-06-05 06:39:01,417 - mmdeploy - INFO - pplnn:	None
2023-06-05 06:39:01,433 - mmdeploy - INFO - ncnn:	None
2023-06-05 06:39:01,437 - mmdeploy - INFO - snpe:	None
2023-06-05 06:39:01,439 - mmdeploy - INFO - openvino:	None
2023-06-05 06:39:01,458 - mmdeploy - INFO - torchscript:	1.10.0
2023-06-05 06:39:01,459 - mmdeploy - INFO - torchscript custom ops:	NotAvailable
2023-06-05 06:39:01,484 - mmdeploy - INFO - rknn-toolkit:	None
2023-06-05 06:39:01,484 - mmdeploy - INFO - rknn2-toolkit:	None
2023-06-05 06:39:01,485 - mmdeploy - INFO - ascend:	None
2023-06-05 06:39:01,487 - mmdeploy - INFO - coreml:	None
2023-06-05 06:39:01,488 - mmdeploy - INFO - tvm:	None
2023-06-05 06:39:01,488 - mmdeploy - INFO - 

2023-06-05 06:39:01,488 - mmdeploy - INFO - **********Codebase information**********
2023-06-05 06:39:03,911 - mmdeploy - INFO - mmdet:	2.23.0
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmseg:	None
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmcls:	None
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmocr:	None
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmedit:	None
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmdet3d:	None
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmpose:	None
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmrotate:	None
2023-06-05 06:39:03,912 - mmdeploy - INFO - mmaction:	None
```

**Comment by RunningLeon** [comment]
@Josh1021 If your input image shape is dynamic, then some dummy bbox with zeros would be padded in certain case.
You can refer to here
https://github.com/open-mmlab/mmdeploy/blob/cbfe99505ce0a12305035322a5803751bf0788a5/mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py#L128-L130

**Comment by Josh1021** [comment]
Hi, thank you for your response. Yes, my model input is dynamic shape. 
Could you tell me under what circumstances this problem occurs? According to my experiments, I inferenced 10 images using sdk，and did not encounter this problem on 3090 and 1660, and it only occurs probabilistically on 1060 when using Docker. Could it be related to graphics card or software version?

**Comment by RunningLeon** [comment]
@Josh1021 hi, could be possible for cases like FP16 and INT8 precision. Maybe could  compare three models with FP32.

**Comment by RunningLeon** [comment]
For dynamic shape, the input images of small size tend to have padded zeros detection bboxes.

**Comment by Josh1021** [comment]
> For dynamic shape, the input images of small size tend to have padded zeros detection bboxes.

Sorry, I still can’t get your point，could you please explain it in more detail。As I understand，the same input should yield the same result, but when I tested it with a same image, sometimes I got the correct detection boxes, and sometimes I got dozens of detection boxes with all-zero coordinates.

**Comment by RunningLeon** [comment]
> > For dynamic shape, the input images of small size tend to have padded zeros detection bboxes.
> 
> Sorry, I still can’t get your point，could you please explain it in more detail。As I understand，the same input should yield the same result, but when I tested it with a same image, sometimes I got the correct detection boxes, and sometimes I got dozens of detection boxes with all-zero coordinates.

This case is a bit complicated. I've met once and it's because the input is not contiguous as it is dealt in here
https://github.com/open-mmlab/mmdeploy/blob/cbfe99505ce0a12305035322a5803751bf0788a5/mmdeploy/backend/tensorrt/wrapper.py#L156

**Comment by Josh1021** [comment]
> This case is a bit complicated. I've met once and it's because the input is not contiguous :
> 
> https://github.com/open-mmlab/mmdeploy/blob/cbfe99505ce0a12305035322a5803751bf0788a5/mmdeploy/backend/tensorrt/wrapper.py#L156

All right, I checked TensorRT `wrapper.py`, the input is contiguous. So on the 1060, it is not recommended to use SDK TensorRT for inference？

**Comment by Josh1021** [comment]
@RunningLeon, And I have another quentions: when using the SDK for inference, the CPU usage is around 100%. Is there any way to reduce it? Because the SDK needs to perform inference together with other applications, high CPU usage may preempt resources. If it can be reduced, will the inference speed be reduced as well?

**Comment by RunningLeon** [comment]
> @RunningLeon, And I have another quentions: when using the SDK for inference, the CPU usage is around 100%. Is there any way to reduce it? Because the SDK needs to perform inference together with other applications, high CPU usage may preempt resources. If it can be reduced, will the inference speed be reduced as well?

@irexyc hi, any idea that how to reduce CPU usage for pre&post processing with SDK inference?

**Comment by Josh1021** [comment]
> > @RunningLeon, And I have another quentions: when using the SDK for inference, the CPU usage is around 100%. Is there any way to reduce it? Because the SDK needs to perform inference together with other applications, high CPU usage may preempt resources. If it can be reduced, will the inference speed be reduced as well?
> 
> @irexyc hi, any idea that how to reduce CPU usage for pre&post processing with SDK inference?

@irexyc, hi, could you help me take a look at this question?

**Comment by irexyc** [comment]
@Josh1021 

What backend and device are you using? If you are using tensort+cuda, there is limit for optimization. If you are using onnxruntime+cpu and you have cuda device, you can make preprocessing run on cuda by edit the pipeline.json
```
        "tasks": [
            {
                "type": "Task",
                "module": "Transform",
                "device": "cuda",
                "name": "Preprocess",
                "input": [
                    "img"
                ],
            ...
```

**Comment by Josh1021** [comment]
I 

> @Josh1021
> 
> What backend and device are you using? If you are using tensort+cuda, there is limit for optimization. If you are using onnxruntime+cpu and you have cuda device, you can make preprocessing run on cuda by edit the pipeline.json
> 
> ```
>         "tasks": [
>             {
>                 "type": "Task",
>                 "module": "Transform",
>                 "device": "cuda",
>                 "name": "Preprocess",
>                 "input": [
>                     "img"
>                 ],
>             ...
> ```

I'm using  tensort+cuda, ,  It’s okay if it can’t be optimized，Thanks！
