### ISSUE TITLE
How can I test a image with ncnn model?

### ISSUE THREAD

**Issue by oym050922021** [open-mmlab/mmdeploy#2158]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

How can I test a image with ncnn model? Are there any reference example? 
my detection model is yolox，and Image preprocessing was consistent with mmdetection.
I wrote a test script and I don't know if it's correct.
Can you help me?  Thank you!

### Reproduction

model_path_param = "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy_models/mmdeploy_ncnn/mmdeploy/yolox/end2end.param"
    model_path_bin = "/root/Ouyangmei/openmmlab/mmdeploy/mmdeploy_models/mmdeploy_ncnn/mmdeploy/yolox/end2end.bin"
    images_folder = "/root/Ouyangmei/openmmlab/mmdetection/datasets/teeth/images/test"
    

    batch_data, batch_images_matrix, batch_images_list, images_cnt = preprocess(images_folder, batchsize=4)
  
    net = ncnn.Net()
    net.load_param(model_path_param)
    net.load_model(model_path_bin)
    input_names = net.input_names()
    output_names = net.output_names()
    assert len(input_names)>0 and len(output_names)>0

    for data, images_matrix, images_list in zip(batch_data, batch_images_matrix, batch_images_list):
        inputs_matrix = data['inputs'].numpy()
        in_mat = ncnn.Mat(inputs_matrix)
        with net.create_extractor() as ex:
            ex.input("input", in_mat)
            ret, out_mat = ex.extract('detection_output')
   

### Environment

```Shell
06/06 14:19:53 - mmengine - INFO - TorchVision: 0.14.1+cu117
06/06 14:19:53 - mmengine - INFO - OpenCV: 4.7.0
06/06 14:19:53 - mmengine - INFO - MMEngine: 0.7.2
06/06 14:19:53 - mmengine - INFO - MMCV: 2.0.0rc4
06/06 14:19:53 - mmengine - INFO - MMCV Compiler: GCC 9.3
06/06 14:19:53 - mmengine - INFO - MMCV CUDA Compiler: 11.7
06/06 14:19:53 - mmengine - INFO - MMDeploy: 1.1.0+faf05fe
06/06 14:19:53 - mmengine - INFO - 

06/06 14:19:53 - mmengine - INFO - **********Backend information**********
06/06 14:19:53 - mmengine - INFO - tensorrt:    None
06/06 14:19:53 - mmengine - INFO - ONNXRuntime: 1.14.1
06/06 14:19:53 - mmengine - INFO - ONNXRuntime-gpu:     None
06/06 14:19:53 - mmengine - INFO - ONNXRuntime custom ops:      Available
06/06 14:19:53 - mmengine - INFO - pplnn:       None
06/06 14:19:53 - mmengine - INFO - ncnn:        1.0.20230606
06/06 14:19:53 - mmengine - INFO - ncnn custom ops:     Available
06/06 14:19:53 - mmengine - INFO - snpe:        None
06/06 14:19:53 - mmengine - INFO - openvino:    None
06/06 14:19:53 - mmengine - INFO - torchscript: 1.13.1
06/06 14:19:53 - mmengine - INFO - torchscript custom ops:      NotAvailable
06/06 14:19:53 - mmengine - INFO - rknn-toolkit:        None
06/06 14:19:53 - mmengine - INFO - rknn-toolkit2:       None
06/06 14:19:53 - mmengine - INFO - ascend:      None
06/06 14:19:53 - mmengine - INFO - coreml:      None
06/06 14:19:53 - mmengine - INFO - tvm: None
06/06 14:19:53 - mmengine - INFO - vacc:        None
06/06 14:19:53 - mmengine - INFO - 

06/06 14:19:53 - mmengine - INFO - **********Codebase information**********
06/06 14:19:53 - mmengine - INFO - mmdet:       3.0.0
06/06 14:19:53 - mmengine - INFO - mmseg:       None
06/06 14:19:53 - mmengine - INFO - mmpretrain:  None
06/06 14:19:53 - mmengine - INFO - mmocr:       None
06/06 14:19:53 - mmengine - INFO - mmagic:      None
06/06 14:19:53 - mmengine - INFO - mmdet3d:     None
06/06 14:19:53 - mmengine - INFO - mmpose:      None
06/06 14:19:53 - mmengine - INFO - mmrotate:    None
06/06 14:19:53 - mmengine - INFO - mmaction:    None
06/06 14:19:53 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
the result of out_mat is ncnn:mat.
```

**Comment by RunningLeon** [comment]
@oym050922021 hi, for model inference, pls. refer to this doc and use ncnn
https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html#model-inference

**Comment by oym050922021** [comment]
@RunningLeon hi, thank you!  If I want to apply the ncnn model to the mobile side, do I need to install mmdeploy in the android environment and use the files named  mmdeploy/demo/csrc/cpp/detector.cxx  to infer?

**Comment by RunningLeon** [comment]
@oym050922021 hi, you could refer to here:
https://github.com/open-mmlab/mmdeploy/tree/main/demo/java
