### ISSUE TITLE
[Bug] visualize onnxruntime model failed. all output are zeros onnx/tensorrt

### ISSUE THREAD

**Issue by lonely0000cc** [open-mmlab/mmdeploy#2161]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi, when I try to convert models trained from mmsegmentation (unet, deeplabv3plus, swin) using tensorrt, the outputs are all zeros. However, if I use the same backbone in a classification model trained in mmpretrain, it is okay.
To resolve this problem, I tried the official example stated in [here](https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/04-supported-codebases/mmseg.md). but encountered "visualize onnxruntime model failed." Is the anything wrong with my setting?

### Reproduction

for tensorrt:
DEPLOY_CFG="configs/mmseg/segmentation_tensorrt_static-512x512.py"
for onnx:
DEPLOY_CFG="configs/mmseg/segmentation_onnxruntime_static-512x512.py"

python tools/deploy.py \
    ${DEPLOY_CFG} \
    ${MODEL_CFG} \
    ${CHECKPOINT} \
    ${INPUT_IMG} \
    --device ${DEVICE} \
    --dump-info \
    --work-dir ${WORK_DIR}

### Environment

```Shell
06/07 15:43:29 - mmengine - INFO -

06/07 15:43:29 - mmengine - INFO - **********Environmental information**********
06/07 15:43:30 - mmengine - INFO - sys.platform: linux
06/07 15:43:30 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
06/07 15:43:30 - mmengine - INFO - CUDA available: True
06/07 15:43:30 - mmengine - INFO - numpy_random_seed: 2147483648
06/07 15:43:30 - mmengine - INFO - GPU 0,1: NVIDIA GeForce RTX 3060
06/07 15:43:30 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
06/07 15:43:30 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.74
06/07 15:43:30 - mmengine - INFO - GCC: x86_64-conda_cos6-linux-gnu-gcc (conda-forge gcc 12.1.0-17) 12.1.0
06/07 15:43:30 - mmengine - INFO - PyTorch: 1.10.1+cu111
06/07 15:43:30 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

06/07 15:43:30 - mmengine - INFO - TorchVision: 0.11.2+cu111
06/07 15:43:30 - mmengine - INFO - OpenCV: 4.7.0
06/07 15:43:30 - mmengine - INFO - MMEngine: 0.7.2
06/07 15:43:30 - mmengine - INFO - MMCV: 2.0.0
06/07 15:43:30 - mmengine - INFO - MMCV Compiler: GCC 7.3
06/07 15:43:30 - mmengine - INFO - MMCV CUDA Compiler: not available
06/07 15:43:30 - mmengine - INFO - MMDeploy: 1.1.0+faf05fe
06/07 15:43:30 - mmengine - INFO -

06/07 15:43:30 - mmengine - INFO - **********Backend information**********
06/07 15:43:30 - mmengine - INFO - tensorrt:    8.6.1
06/07 15:43:30 - mmengine - INFO - tensorrt custom ops: Available
06/07 15:43:30 - mmengine - INFO - ONNXRuntime: None
06/07 15:43:30 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
06/07 15:43:30 - mmengine - INFO - ONNXRuntime custom ops:      Available
06/07 15:43:30 - mmengine - INFO - pplnn:       None
06/07 15:43:30 - mmengine - INFO - ncnn:        None
06/07 15:43:30 - mmengine - INFO - snpe:        None
06/07 15:43:30 - mmengine - INFO - openvino:    None
06/07 15:43:30 - mmengine - INFO - torchscript: 1.10.1+cu111
06/07 15:43:30 - mmengine - INFO - torchscript custom ops:      NotAvailable
06/07 15:43:30 - mmengine - INFO - rknn-toolkit:        None
06/07 15:43:30 - mmengine - INFO - rknn-toolkit2:       None
06/07 15:43:30 - mmengine - INFO - ascend:      None
06/07 15:43:30 - mmengine - INFO - coreml:      None
06/07 15:43:30 - mmengine - INFO - tvm: None
06/07 15:43:30 - mmengine - INFO - vacc:        None
06/07 15:43:30 - mmengine - INFO -

06/07 15:43:30 - mmengine - INFO - **********Codebase information**********
06/07 15:43:30 - mmengine - INFO - mmdet:       None
06/07 15:43:30 - mmengine - INFO - mmseg:       1.0.0
06/07 15:43:30 - mmengine - INFO - mmpretrain:  1.0.0rc7
06/07 15:43:30 - mmengine - INFO - mmocr:       None
06/07 15:43:30 - mmengine - INFO - mmagic:      1.0.1.dev0
06/07 15:43:30 - mmengine - INFO - mmdet3d:     None
06/07 15:43:30 - mmengine - INFO - mmpose:      None
06/07 15:43:30 - mmengine - INFO - mmrotate:    None
06/07 15:43:30 - mmengine - INFO - mmaction:    None
06/07 15:43:30 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
06/07 15:44:33 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
06/07 15:44:33 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
06/07 15:44:34 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
06/07 15:44:35 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
06/07 15:44:35 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
/home/huangyh/code/mmsegmentation/mmseg/models/builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()``
  warnings.warn('``build_loss`` would be deprecated soon, please use '
/home/huangyh/code/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
Loads checkpoint by local backend from path: fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes_20211210_145204-6860854e.pth
06/07 15:44:35 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
06/07 15:44:35 - mmengine - INFO - Export PyTorch model to ONNX: mmdeploy_model/mmseg/back_seg/fcn/onnx/end2end.onnx.
06/07 15:44:35 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
/home/huangyh/code/mmdeploy/mmdeploy/core/optimizers/function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/home/huangyh/code/mmsegmentation/mmseg/models/backbones/unet.py:431: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (h % whole_downsample_rate == 0) \
06/07 15:44:42 - mmengine - INFO - Execute onnx optimize passes.
06/07 15:44:43 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
06/07 15:44:43 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
06/07 15:44:43 - mmengine - INFO - Finish pipeline mmdeploy.apis.utils.utils.to_backend
06/07 15:44:43 - mmengine - INFO - visualize onnxruntime model start.
06/07 15:44:44 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
06/07 15:44:44 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
06/07 15:44:44 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "backend_segmentors" registry tree. As a workaround, the current "backend_segmentors" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
06/07 15:44:44 - mmengine - INFO - Successfully loaded onnxruntime custom ops from /home/huangyh/code/mmdeploy/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
06/07 15:44:44 - mmengine - ERROR - tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.
```

**Comment by RunningLeon** [comment]
@lonely0000cc hi, maybe you could try activate rewritings for mmpretrain by adding `import mmdeploy.codebase.mmpretrain.models` after here


https://github.com/open-mmlab/mmdeploy/blob/439f88b543f4ffc0f2453f404ce1d8471147fb8e/mmdeploy/codebase/mmseg/deploy/segmentation.py#L111

**Comment by lonely0000cc** [comment]
> @lonely0000cc hi, maybe you could try activate rewritings for mmpretrain by adding `import mmdeploy.codebase.mmpretrain.models` after here
> 
> https://github.com/open-mmlab/mmdeploy/blob/439f88b543f4ffc0f2453f404ce1d8471147fb8e/mmdeploy/codebase/mmseg/deploy/segmentation.py#L111

Hi, thanks for your reply. I added `import mmdeploy.codebase.mmpretrain.models` in the noted place but the outputs of tensorrt and onnx are still all zero.

Is this problem anything to do with 'visualize onnxruntime model failed' mentioned above? to note , the output of my machine 'uname -a' is Linux AST1 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux . I use conda and the gcc/g++ version of conda is 12.1

**Comment by RunningLeon** [comment]
The failure of visualization shows something wrong with the model in inference. Could you try uninstall onnxruntime-gpu and install CPU with `pip install onnxruntime==1.8.1`

**Comment by lonely0000cc** [comment]
> The failure of visualization shows something wrong with the model in inference. Could you try uninstall onnxruntime-gpu and install CPU with `pip install onnxruntime==1.8.1`

Hi, thanks for your reply.
I didn't install SDK, maybe this is the reason? However, the outputs all zero problems still remained. 
I reinstalled annother conda environment to follow exactly like that in the tutorial and the conversion of the demo in [mmseg](https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/04-supported-codebases/mmseg.md) is successful but the conversion of deeplabv3plus and swin failed. would it be the reason that my environment is incompatible with some models?
Besides, how can I solve the warning **Failed to search registry with scope "mmseg" in the "Codebases" registry tree.** I use my own custom dataset type, would it be the reason?
there are also warnings like **Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied** and **Can not find torch._C._jit_pass_onnx_deduplicate_initializers, function rewrite will not be applied**

**Comment by RunningLeon** [comment]
hi, these warnings could be ignored.

**Comment by lonely0000cc** [comment]
> hi, these warnings could be ignored.

Hi, I upgrade onnxruntime to 1.15.0 and error of visualization is gone, however, the outputs are still all zeros except unet for onnxruntime inference. What shall I do?

**Comment by lonely0000cc** [comment]
Just to update, the problem is caused by out_channels=1 following the suggestion of mmsegmentation for binary segmentation. then all the output class is 0 as argmax. It is supposed to be solved in https://github.com/open-mmlab/mmdeploy/pull/1997 I just rescently pull the code from main branch but it seems this change haven't been merged into main branch.

**Comment by RunningLeon** [comment]
> Just to update, the problem is caused by out_channels=1 following the suggestion of mmsegmentation for binary segmentation. then all the output class is 0 as argmax. It is supposed to be solved in #1997 I just rescently pull the code from main branch but it seems this change haven't been merged into main branch.

@lonely0000cc Where do yo change the `out_channels=1` and do you know where is it dealt with sigmoid instead of argmax in mmseg?

**Comment by lonely0000cc** [comment]
> > Just to update, the problem is caused by out_channels=1 following the suggestion of mmsegmentation for binary segmentation. then all the output class is 0 as argmax. It is supposed to be solved in #1997 I just rescently pull the code from main branch but it seems this change haven't been merged into main branch.
> 
> @lonely0000cc Where do yo change the `out_channels=1` and do you know where is it dealt with sigmoid instead of argmax in mmseg?

the `out_channels=1` is set in decode_head and auxiliary_head of mmseg model, take **mmsegmentation/configs/_base_/models/deeplabv3plus_r50-d8.py** for example.
The settings of seg model may look like this:
model = dict(
    type='EncoderDecoder',
    data_preprocessor=data_preprocessor,
    pretrained='open-mmlab://resnet50_v1c',
    backbone=dict(
        type='ResNetV1c',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 2, 4),
        strides=(1, 2, 1, 1),
        norm_cfg=norm_cfg,
        norm_eval=False,
        style='pytorch',
        contract_dilation=True),
    decode_head=dict(
        type='DepthwiseSeparableASPPHead',
        in_channels=2048,
        in_index=3,
        channels=512,
        dilations=(1, 12, 24, 36),
        c1_in_channels=256,
        c1_channels=48,
        dropout_ratio=0.1,
        num_classes=2,
        # **out_channels=1**, # mmdeploy failed
        # threshold=0.3,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0, class_weight=[1.0, 2.0])),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=2,
        # **out_channels=1**,
        # threshold=0.3,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4, class_weight=[1.0, 2.0])),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))

and you have to set use_sigmoid=True if out_channels=1. During forward of the model, mode='predict', the code to deal with this issue is in **mmseg/models/segmentors/base.py** in function postprocess_result where 
`        if C > 1:
              i_seg_pred = i_seg_logits.argmax(dim=0, keepdim=True)
          else:
              i_seg_logits = i_seg_logits.sigmoid()
              i_seg_pred = (i_seg_logits >
                            self.decode_head.threshold).to(i_seg_logits)`

**Comment by RunningLeon** [comment]
@lonely0000cc hi, could you try this PR https://github.com/open-mmlab/mmdeploy/pull/2179?

**Comment by lonely0000cc** [comment]
> @lonely0000cc hi, could you try this PR #2179?

hi, it failed on my side for "out_channels=1"

2023-06-13:15:09:12 - root - ERROR - Error in execution: Invalid Output Name:output
Traceback (most recent call last):
  File "/home/huangyh/code/mmdeploy/mmdeploy/utils/utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/huangyh/code/mmdeploy/mmdeploy/apis/visualize.py", line 72, in visualize_model
    result = model.test_step(model_inputs)[0]
  File "/home/huangyh/anaconda3/envs/env_py38/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/huangyh/anaconda3/envs/env_py38/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/home/huangyh/anaconda3/envs/env_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/huangyh/code/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation_model.py", line 86, in forward
    batch_outputs = self.wrapper({self.input_name:
  File "/home/huangyh/anaconda3/envs/env_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/huangyh/code/mmdeploy/mmdeploy/backend/onnxruntime/wrapper.py", line 97, in forward
    self.__ort_execute(self.io_binding)
  File "/home/huangyh/code/mmdeploy/mmdeploy/utils/timer.py", line 67, in fun
    result = func(*args, **kwargs)
  File "/home/huangyh/code/mmdeploy/mmdeploy/backend/onnxruntime/wrapper.py", line 113, in __ort_execute
    self.sess.run_with_iobinding(io_binding)
  File "/home/huangyh/anaconda3/envs/env_py38/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 276, in run_with_iobinding
    self._sess.run_with_iobinding(iobinding._iobinding, run_options)
RuntimeError: Error in execution: Invalid Output Name:output
06/13 15:09:12 - mmengine - ERROR - tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.

**Comment by lonely0000cc** [comment]
> the output name is not right. pls. check. `python -c "import onnx;print(onnx.load('end2end.onnx').graph.input)"`

Hi, I pull your branch **fix_mmseg_binary_cls** through `gh pr checkout`
when test with `out_channels=1` the output of `python -c "import onnx;print(onnx.load('end2end.onnx').graph.output)"` is 
![image](https://github.com/open-mmlab/mmdeploy/assets/20694930/790e708a-43cd-4b4e-aa07-8eeb85e5479f)
which is wrong. netron also shows 
<img width="1031" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/20694930/16e0a9d2-1fcb-4832-837f-2d819db3fe70">
However, when I switch to main branch, there is no error and the name is correct.

**Comment by lonely0000cc** [comment]
> > the output name is not right. pls. check. `python -c "import onnx;print(onnx.load('end2end.onnx').graph.input)"`
> 
> Hi, I pull your branch **fix_mmseg_binary_cls** through `gh pr checkout` when test with `out_channels=1` the output of `python -c "import onnx;print(onnx.load('end2end.onnx').graph.output)"` is ![image](https://user-images.githubusercontent.com/20694930/245436399-790e708a-43cd-4b4e-aa07-8eeb85e5479f.png) which is wrong. netron also shows <img alt="image" width="1031" src="https://user-images.githubusercontent.com/20694930/245436577-16e0a9d2-1fcb-4832-837f-2d819db3fe70.png"> However, when I switch to main branch, there is no error and the name is correct.

as for input 
![image](https://github.com/open-mmlab/mmdeploy/assets/20694930/16a16489-816a-446d-ae02-7d6467a57781)
here I use `configs/mmseg/segmentation_onnxruntime_dynamic.py` as the config file.
the detail.json
{
    "version": "1.1.0",
    "codebase": {
        "task": "Segmentation",
        "codebase": "mmseg",
        "version": "1.0.0",
        "pth": "../mmsegmentation/work_dirs/deeplabv3plus_r50_back_seg/iter_200.pth",
        "config": "../mmsegmentation/configs/deeplabv3plus/deeplabv3plus_r50_back_seg.py"
    },
    "codebase_config": {
        "type": "mmseg",
        "task": "Segmentation",
        "with_argmax": true
    },
    "onnx_config": {
        "type": "onnx",
        "export_params": true,
        "keep_initializers_as_inputs": false,
        "opset_version": 11,
        "save_file": "end2end.onnx",
        "input_names": [
            "input"
        ],
        "output_names": [
            "output"
        ],
        "input_shape": null,
        "optimize": true,
        "dynamic_axes": {
            "input": {
                "0": "batch",
                "2": "height",
                "3": "width"
            },
            "output": {
                "0": "batch",
                "2": "height",
                "3": "width"
            }
        }
    },
    "backend_config": {
        "type": "onnxruntime"
    },
    "calib_config": {}
}

**Comment by aRibra** [comment]
> 06/07 15:44:44 - mmengine - ERROR - tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.

Error has gone after updating onnxruntime to `onnxruntime==1.16.3`. 
onnxruntime (CPU) inference passed successfully.

**Comment by ir2718** [comment]
In case anyone else runs into this and wants to run it on gpu, uninstalling onnxruntime and onnxruntime-gpu, and then reinstalling onnxruntime-gpu 1.18 solved the issue for me:

```
pip uninstall onnxruntime 
pip uninstall onnxruntime-gpu

pip install onnxruntime-gpu==1.18
```
