### ISSUE TITLE
[Bug] - convert mmdeploy::Segmentor::Result to Opencv

### ISSUE THREAD

**Issue by quizzy5889** [open-mmlab/mmdeploy#2165]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi everybody,
Actually the question is quite easy:

how is it possible to convert mask and scores produced by 

```
mmdeploy::Segmentor segmentor{mmdeploy::Model{ARGS_model}, mmdeploy::Device{FLAGS_device}};

  // apply the detector, the result is an array-like class holding a reference to
  // `mmdeploy_segmentation_t`, will be released automatically on destruction
  mmdeploy::Segmentor::Result seg = segmentor.Apply(img);

```

in cv::Mat? More specifically I would like to convert seg.mask and seg.scores!

Thanks a lot

### Reproduction

-

### Environment

```Shell
-
```

**Comment by irexyc** [comment]
First of all, I would like to explain that currently you cannot get score and mask at the same time. If set `with_argmax=True` in [config](https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmseg/segmentation_static.py#L2), it will output mask If set `with_argmax=False` it will output score.

To convert score/mask to cv::Mat, you can do like this:
```
// convert the model with with_argmax=True
// the mask doesn't own its data, the data lifetime depends on mmdeploy::Segmentor::Result
// If you wan't to make cv::Mat mask own data, you need call clone() method.
cv::Mat mask = cv::Mat(seg->height, seg->width, CV_32S, seg.mask); 
```

```
// when convert the model with with_argmax=False, the output score is in CHW format.
// While the cv::Mat is in HWC format, so you can't simple create cv::Mat with seg.score address, you need to
// copy data from seg.score to cv::Mat you created according to the format.


// a native way may look like this
cv::Mat score = cv::Mat(seg->height, seg->width, CV_32F(seg->classes));
auto src = seg->score;
auto dst = score.data<float>;
for (int i = 0; i < seg->height; i++) {
  for (int j = 0; j < seg->width; j++) {
    for (int k = 0; k < seg->classes; k++) {
      int dst_index = i * seg->width * seg->classes + j * seg->classes + k;
      int src_idnex = k * seg->height * seg->width + i * seg->width + j;
      dst[dst_index] =  src[index];
    }
  }
}

// you can refer to this for a more efficiency may to do the permute
// csrc/mmdeploy/operation/cpu/permute.cpp
```
