### ISSUE TITLE
[Feature] csrc/mmdeploy c++ do not contain mmpretrain

### ISSUE THREAD

**Issue by caj-github** [open-mmlab/mmdeploy#2166]
### Motivation

c++ inference classification report a error:
![image](https://github.com/open-mmlab/mmdeploy/assets/55951697/57dcb487-e22c-441a-95e5-033141f1da39)

**Comment by irexyc** [comment]
Hi, @caj-github can you shared `detail.json` and `pipeline.json`?

**Comment by caj-github** [comment]
i have found the problem， i rewrite the mmdeploy.backend.sdk.export_info.get_postprocess to solve the mmcls StackedLinearClsHead problem, i change the code file mmdeploy\backend\sdk\export_info.py like this, it  works now
![image](https://github.com/open-mmlab/mmdeploy/assets/55951697/d064a8f1-f92f-42f1-892c-359d4a5af5d3)

**Comment by irexyc** [comment]
It‘s better to modify the code in [this file](https://github.com/open-mmlab/mmdeploy/blob/main/mmdeploy/codebase/mmpretrain/deploy/classification.py#L328).

If it's convenient for you, you can make a PR to update the code.
