### ISSUE TITLE
[Feature] yolox_s model cpu int8 quant

### ISSUE THREAD

**Issue by PancakeAwesome** [open-mmlab/mmdeploy#2167]
### Motivation

I want to implement the trained yolox model: int8 quantization and cpu infer
like this tur:
https://github.com/open-mmlab/mmdeploy/blob/439f88b543f4ffc0f2453f404ce1d8471147fb8e/docs/zh_cn/02-how-to-run/quantize_model.md

**Comment by PancakeAwesome** [comment]
@irexyc @RunningLeon

**Comment by RunningLeon** [comment]
@PancakeAwesome which backend you want to deploy? onnxruntime+int8? ncnn+int8?openvino+int8?

**Comment by PancakeAwesome** [comment]
> @PancakeAwesome which backend you want to deploy? onnxruntime+int8? ncnn+int8?openvino+int8?

openvino+int8+cpu

**Comment by RunningLeon** [comment]
for now, you can either use mmdeploy export onnx and then quantize on onnx using [ppq](https://github.com/openppl-public/ppq) or using [nncf ](https://docs.openvino.ai/2023.0/openvino_docs_model_optimization_guide.html) from openvino

**Comment by PancakeAwesome** [comment]
> for now, you can either use mmdeploy export onnx and then quantize on onnx using [ppq](https://github.com/openppl-public/ppq) or using [nncf ](https://docs.openvino.ai/2023.0/openvino_docs_model_optimization_guide.html) from openvino

can i use mmraor for this feature?
