### ISSUE TITLE
[Bug] nn.LayerNorm gives wrong shape in onnx with PyTorch <= 1.12.0, how can I solve it?

### ISSUE THREAD

**Issue by Jacobew** [open-mmlab/mmdeploy#2169]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

As stated in https://github.com/open-mmlab/mmdeploy/pull/1015/files#diff-1eaaa8490375cdb3dae032d386a306a506ad821626664b89a417df0918b40ae6, nn.LayerNorm gives wrong shape in onnx with PyTorch <= 1.12.0. 
How can I fix this issue without changing the version of pytorch? Or, how can I adapt the fix in this link to export onnx? 
Thanks for your reply!!

### Reproduction

See the Link above.

### Environment

```Shell
PyTorch: 1.10.0
```

**Comment by RunningLeon** [comment]
@Jacobew hi, isn't it fixed in the linked PR?

**Comment by Jacobew** [comment]
yes it did, I wonder how I can use this layer_norm__default function when exporting onnx? Could you give me an example?

**Comment by RunningLeon** [comment]
> @RunningLeon yes it did, I wonder how I can use this layer_norm__default function when exporting onnx? Could you give me an example?

Did you mean to make it effective outside of mmdeploy for torch2onnx?

**Comment by Jacobew** [comment]
@RunningLeon Yes. I want to use this export function so I do not need to implement a new LayerNorm with reducemean issue fixed. :)

**Comment by RunningLeon** [comment]
Maybe you  could modify the source code of pytorch, eg here https://github.com/pytorch/pytorch/blob/2961ea80f5d5fbcb9ef86d95ce08f1fa603863bf/torch/onnx/symbolic_opset9.py#L2929

**Comment by talentCODE** [comment]
> Maybe you could modify the source code of pytorch, eg here https://github.com/pytorch/pytorch/blob/2961ea80f5d5fbcb9ef86d95ce08f1fa603863bf/torch/onnx/symbolic_opset9.py#L2929

Thanks a lot.  It works for me
