### ISSUE TITLE
pytorch to onnx

### ISSUE THREAD

**Issue by wangzixiang99** [open-mmlab/mmdeploy#2174]
### Motivation

你好，我利用mmocr中的svtr算法训练出来模型后，利用mmdeploy将其pth文件转成onnx时报如下的警告：
06/12 14:00:33 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.

/home/wang/code/mmocr-1.x/mmocr/models/textrecog/preprocessors/tps_preprocessor.py:90: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert source_control_points.size(1) == self.num_control_points

WARNING: The shape inference of mmdeploy::grid_sampler type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.

最后停留在：
06/12 14:00:39 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
文件夹中也生成了end2end.onnx

转换指令：
 python mmdeploy-master/tools/deploy.py mmdeploy-master/configs/mmocr/text-recognition/text-recognition_onnxruntime_dynamic.py     configs/textrecog/svtr/svtr-small_20e_st_mj.py     checkpoints/english_epoch_2000.pth     demo/demo_text_ocr.jpg     --work-dir work_dirs/mmdeploy_model/svtr     --device cpu     --dump-info

请问这是已经转换成功了吗？这个警告有意义吗？
我看你们提供的支持的模型的目录中并没有SVTR算法，为何这个生成了一个end2end.onnx？

**Comment by wangzixiang99** [comment]
> SVTR is not officially supported up to now. But it is a good sign that you converted it to ONNX format. To test if the output ONNX is correct, you may try visualizing the result of ONNX inference through `deploy.py`. Or, you can directly compare the input and output of the PyTorch model and ONNX model.

想请问一下，从pt模型转成onnx模型时onnx_cfg中的'input'和‘output’需要修改吗？也就是'mmdeploy-master/configs/mmocr/text-recognition/text-recognition_onnxruntime_dynamic.py'中链接到的text-recognition_dynamic中的：
_base_ = ['./text-recognition_static.py']
onnx_config = dict(
    dynamic_axes={
        'input': {
            0: 'batch',
            3: 'width'
        },
        'output': {
            0: 'batch',
            1: 'seq_len',
            2: 'num_classes'
        }
    }, )
是否需要修改呢？不修改的话我转出来的onnx模型中输入就是batch*3*64*width，输出就是[batch,seq_len,num_classes]，它不是具体的数值，比如输入应该是1*3*64*228，是有哪些地方配置需要修改的吗？

**Comment by AllentDan** [comment]
Generally, no need to modify `text-recognition_onnxruntime_dynamic.py` if the output is correct.

**Comment by AllentDan** [comment]
> 我改用mmdeploy-master/configs/mmocr/text-recognition/text-recognition_onnxruntime_static.py后输出的onnx文件中在netron中显示输入是(1,3,64,256),但最后的输出是float32[Softmaxoutput_dim_0,Softmaxoutput_dim_1,Softmaxoutput_dim_2]，为啥不是具体的数字呢？这是正常的吗？

That is typical of ONNX.
