### ISSUE TITLE
Failed to install MMCV for Model Converter on Jetson Nano

### ISSUE THREAD

**Issue by lostsword** [open-mmlab/mmdeploy#2176]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hello, I'm failed to install MMCV on Jetson Nano when following the [Build for Jetson](https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/jetsons.md). 
When building the MMCV from source, the error is:

```
$ sudo apt-get install -y libssl-dev
$ git clone --branch 2.x https://github.com/open-mmlab/mmcv.git
$ cd mmcv
$ MMCV_WITH_OPS=1 pip install -e .

Obtaining file:///home/xgy/dependencies/mmcv
  Preparing metadata (setup.py) ... done
Collecting addict
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting mmengine>=0.2.0
  Using cached mmengine-0.4.0-py3-none-any.whl (317 kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from mmcv==2.0.0) (1.13.3)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Requirement already satisfied: Pillow in /home/xgy/.local/lib/python3.6/site-packages (from mmcv==2.0.0) (8.4.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from mmcv==2.0.0) (3.12)
Collecting yapf
  Using cached yapf-0.33.0-py2.py3-none-any.whl (200 kB)
ERROR: Package 'mmcv' requires a different Python: 3.6.9 not in '>=3.7'
```

The environment is:

```
JetPack: 4.6.1
Python: 3.6.9
CUDA: 10.2
torch: 1.10.0
torchvision: 0.11.1
```

Are there any solutions to install MMCV in Python3.6 ? Thanks very much !

### Reproduction

```
$ sudo apt-get install -y libssl-dev
$ git clone --branch 2.x https://github.com/open-mmlab/mmcv.git
$ cd mmcv
$ MMCV_WITH_OPS=1 pip install -e .
```

### Environment

I install torch and torchvision following the [instruction](https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048)
```
JetPack: 4.6.1
Python: 3.6.9
CUDA: 10.2
torch: 1.10.0
torchvision: 0.11.1
```

### Error traceback

```
Obtaining file:///home/xgy/dependencies/mmcv
  Preparing metadata (setup.py) ... done
Collecting addict
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting mmengine>=0.2.0
  Using cached mmengine-0.4.0-py3-none-any.whl (317 kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from mmcv==2.0.0) (1.13.3)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Requirement already satisfied: Pillow in /home/xgy/.local/lib/python3.6/site-packages (from mmcv==2.0.0) (8.4.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from mmcv==2.0.0) (3.12)
Collecting yapf
  Using cached yapf-0.33.0-py2.py3-none-any.whl (200 kB)
ERROR: Package 'mmcv' requires a different Python: 3.6.9 not in '>=3.7'
```

**Comment by RunningLeon** [comment]
@lostsword hi, for building mmcv on jetson, you could search in https://github.com/open-mmlab/mmcv. @zhouzaida

**Comment by RunningLeon** [comment]
@lostsword hi, if you do not want to upgrade python, you change [here](https://github.com/open-mmlab/mmcv/blob/558742c9cb1fc593996e55522a08568f79ff51e5/setup.py#LL434C1-L434C1) to 3.6 and rebuild mmcv

**Comment by lurenzhouyi** [comment]
> @lostsword hi, if you do not want to upgrade python, you could try to change [here](https://github.com/open-mmlab/mmcv/blob/558742c9cb1fc593996e55522a08568f79ff51e5/setup.py#LL434C1-L434C1) to 3.6 and rebuild mmcv

It works, thank you

**Comment by RunningLeon** [comment]
> > @lostsword hi, if you do not want to upgrade python, you could try to change [here](https://github.com/open-mmlab/mmcv/blob/558742c9cb1fc593996e55522a08568f79ff51e5/setup.py#LL434C1-L434C1) to 3.6 and rebuild mmcv
> 
> It works, thank you

@lurenzhouyi hi, if you feel mmdeploy is useful, pls. give us a star on the github.

**Comment by lostsword** [comment]
> @lostsword hi, if you do not want to upgrade python, you could try to change [here](https://github.com/open-mmlab/mmcv/blob/558742c9cb1fc593996e55522a08568f79ff51e5/setup.py#LL434C1-L434C1) to 3.6 and rebuild mmcv
It works. Thanks a lot!
