### ISSUE TITLE
c++推理mmrotate模型报错

### ISSUE THREAD

**Issue by kc-w** [open-mmlab/mmdeploy#2181]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

[2023-06-14 14:11:27.833] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "E:/projectTest/mmdeploy-1.0.0/tools/rtmdet_fp16"
[ERROR][2023-06-14 14:13:24.765][copymakeborder.cu:278] Assertion failed: dst_stride >= cols * channels * (int)sizeof(uchar)
[2023-06-14 14:13:24.766] [mmdeploy] [error] [pad.cpp:72] unexpected exception happened

### Reproduction

![image](https://github.com/open-mmlab/mmdeploy/assets/39193398/76497714-84d8-4e4b-91a6-0254bded6544)

### Environment

```Shell
06/14 14:17:15 - mmengine - INFO - 

06/14 14:17:15 - mmengine - INFO - **********Environmental information**********
06/14 14:17:27 - mmengine - INFO - sys.platform: win32
06/14 14:17:27 - mmengine - INFO - Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
06/14 14:17:27 - mmengine - INFO - CUDA available: True
06/14 14:17:27 - mmengine - INFO - numpy_random_seed: 2147483648
06/14 14:17:27 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3060
06/14 14:17:27 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
06/14 14:17:27 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
06/14 14:17:27 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30147 版
06/14 14:17:27 - mmengine - INFO - GCC: n/a
06/14 14:17:27 - mmengine - INFO - PyTorch: 1.11.0+cu113
06/14 14:17:27 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

06/14 14:17:27 - mmengine - INFO - TorchVision: 0.12.0+cu113
06/14 14:17:27 - mmengine - INFO - OpenCV: 4.5.3
06/14 14:17:27 - mmengine - INFO - MMEngine: 0.7.3
06/14 14:17:27 - mmengine - INFO - MMCV: 2.0.0
06/14 14:17:27 - mmengine - INFO - MMCV Compiler: MSVC 192829924
06/14 14:17:27 - mmengine - INFO - MMCV CUDA Compiler: 11.3
06/14 14:17:27 - mmengine - INFO - MMDeploy: 1.0.0+HEAD
06/14 14:17:27 - mmengine - INFO - 

06/14 14:17:27 - mmengine - INFO - **********Backend information**********
tensorrt
06/14 14:17:27 - mmengine - INFO - tensorrt:	8.4.1.5
06/14 14:17:27 - mmengine - INFO - tensorrt custom ops:	Available
onnxruntime
06/14 14:17:28 - mmengine - INFO - ONNXRuntime:	1.13.1
06/14 14:17:28 - mmengine - INFO - ONNXRuntime-gpu:	None
06/14 14:17:28 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
pplnn
06/14 14:17:29 - mmengine - INFO - pplnn:	None
ncnn
06/14 14:17:30 - mmengine - INFO - ncnn:	None
snpe
06/14 14:17:30 - mmengine - INFO - snpe:	None
openvino
06/14 14:17:30 - mmengine - INFO - openvino:	2022.1.0
torchscript
06/14 14:17:30 - mmengine - INFO - torchscript:	1.11.0+cu113
06/14 14:17:30 - mmengine - INFO - torchscript custom ops:	NotAvailable
rknn
06/14 14:17:30 - mmengine - INFO - rknn-toolkit:	None
06/14 14:17:30 - mmengine - INFO - rknn-toolkit2:	None
ascend
06/14 14:17:31 - mmengine - INFO - ascend:	None
coreml
06/14 14:17:31 - mmengine - INFO - coreml:	None
tvm
06/14 14:17:31 - mmengine - INFO - tvm:	None
vacc
06/14 14:17:31 - mmengine - INFO - vacc:	None
06/14 14:17:31 - mmengine - INFO - 

06/14 14:17:31 - mmengine - INFO - **********Codebase information**********
06/14 14:17:31 - mmengine - INFO - mmdet:	3.0.0
06/14 14:17:31 - mmengine - INFO - mmseg:	1.0.0
06/14 14:17:31 - mmengine - INFO - mmcls:	None
06/14 14:17:31 - mmengine - INFO - mmocr:	None
06/14 14:17:31 - mmengine - INFO - mmedit:	None
06/14 14:17:31 - mmengine - INFO - mmdet3d:	None
06/14 14:17:31 - mmengine - INFO - mmpose:	None
06/14 14:17:31 - mmengine - INFO - mmrotate:	1.0.0rc1
06/14 14:17:31 - mmengine - INFO - mmaction:	None
06/14 14:17:31 - mmengine - INFO - mmrazor:	None
```

**Comment by irexyc** [comment]
Error seems in preprocessing, please provide the `pipeline.json` and error image.

**Comment by kc-w** [comment]
> 预测中出现错误，请提供`pipeline.json`错误图像。

{
    "version": "1.0.0",
    "task": "RotatedDetector",
    "models": [
        {
            "name": "mmdet.rtmdet",
            "net": "end2end.engine",
            "weights": "",
            "backend": "tensorrt",
            "precision": "FP16",
            "batch_size": 1,
            "dynamic_shape": true
        }
    ],
    "customs": []
}

**Comment by kc-w** [comment]
> 



> Error seems in preprocessing, please provide the `pipeline.json` and error image.

The image is a.bmp suffix and cannot be uploaded

**Comment by irexyc** [comment]
是提供pipeline.json，你上面贴的应该是deploy.json

图片你可以改成jpg后缀上传。

**Comment by kc-w** [comment]
> 是提供pipeline.json，你上面贴的应该是deploy.json
> 
> 图片你可以改成jpg后缀上传。

{
    "pipeline": {
        "input": [
            "img"
        ],
        "output": [
            "post_output"
        ],
        "tasks": [
            {
                "type": "Task",
                "module": "Transform",
                "name": "Preprocess",
                "input": [
                    "img"
                ],
                "output": [
                    "prep_output"
                ],
                "transforms": [
                    {
                        "type": "LoadImageFromFile",
                        "file_client_args": {
                            "backend": "disk"
                        }
                    },
                    {
                        "type": "Resize",
                        "keep_ratio": true,
                        "size": [
                            1440,
                            1056
                        ]
                    },
                    {
                        "type": "Pad",
                        "size": [
                            1440,
                            1056
                        ],
                        "pad_val": {
                            "img": [
                                114,
                                114,
                                114
                            ]
                        }
                    },
                    {
                        "type": "Normalize",
                        "to_rgb": false,
                        "mean": [
                            103.53,
                            116.28,
                            123.675
                        ],
                        "std": [
                            57.375,
                            57.12,
                            58.395
                        ]
                    },
                    {
                        "type": "Pad",
                        "size_divisor": 1
                    },
                    {
                        "type": "DefaultFormatBundle"
                    },
                    {
                        "type": "Collect",
                        "meta_keys": [
                            "valid_ratio",
                            "img_shape",
                            "flip_direction",
                            "img_norm_cfg",
                            "img_path",
                            "img_id",
                            "flip",
                            "ori_filename",
                            "pad_shape",
                            "scale_factor",
                            "filename",
                            "ori_shape"
                        ],
                        "keys": [
                            "img"
                        ]
                    }
                ]
            },
            {
                "name": "mmdet.rtmdet",
                "type": "Task",
                "module": "Net",
                "is_batched": true,
                "input": [
                    "prep_output"
                ],
                "output": [
                    "infer_output"
                ],
                "input_map": {
                    "img": "input"
                },
                "output_map": {}
            },
            {
                "type": "Task",
                "module": "mmrotate",
                "name": "postprocess",
                "component": "ResizeRBBox",
                "params": {
                    "nms_pre": 2000,
                    "min_bbox_size": 0,
                    "score_thr": 0.05,
                    "nms": {
                        "type": "nms_rotated",
                        "iou_threshold": 0.1
                    },
                    "max_per_img": 2000
                },
                "output": [
                    "post_output"
                ],
                "input": [
                    "prep_output",
                    "infer_output"
                ]
            }
        ]
    }
}

![2022_04_13_10_16_36_548](https://github.com/open-mmlab/mmdeploy/assets/39193398/f5f7e94e-7ba1-4554-9f3e-d5e1e9ad01cc)

**Comment by irexyc** [comment]
1.0.0的代码有一个对pad参数的解析有问题，会认为是(h, w)。所以你把第一个pad的尺寸换一下应该就好了。第二个pad没必要，可以删掉。

```json
{
    "pipeline":{
        "input":[
            "img"
        ],
        "output":[
            "post_output"
        ],
        "tasks":[
            {
                "type":"Task",
                "module":"Transform",
                "name":"Preprocess",
                "input":[
                    "img"
                ],
                "output":[
                    "prep_output"
                ],
                "transforms":[
                    {
                        "type":"LoadImageFromFile",
                        "file_client_args":{
                            "backend":"disk"
                        }
                    },
                    {
                        "type":"Resize",
                        "keep_ratio":true,
                        "size":[
                            1056,
                            1440
                        ]
                    },
                    {
                        "type":"Pad",
                        "size":[
                            1440,
                            1056
                        ],
                        "pad_val":{
                            "img":[
                                114,
                                114,
                                114
                            ]
                        }
                    },
                    {
                        "type":"Normalize",
                        "to_rgb":false,
                        "mean":[
                            103.53,
                            116.28,
                            123.675
                        ],
                        "std":[
                            57.375,
                            57.12,
                            58.395
                        ]
                    },
                    {
                        "type":"DefaultFormatBundle"
                    },
                    {
                        "type":"Collect",
                        "meta_keys":[
                            "valid_ratio",
                            "img_shape",
                            "flip_direction",
                            "img_norm_cfg",
                            "img_path",
                            "img_id",
                            "flip",
                            "ori_filename",
                            "pad_shape",
                            "scale_factor",
                            "filename",
                            "ori_shape"
                        ],
                        "keys":[
                            "img"
                        ]
                    }
                ]
            },
            {
                "name":"mmdet.rtmdet",
                "type":"Task",
                "module":"Net",
                "is_batched":true,
                "input":[
                    "prep_output"
                ],
                "output":[
                    "infer_output"
                ],
                "input_map":{
                    "img":"input"
                },
                "output_map":{

                }
            },
            {
                "type":"Task",
                "module":"mmrotate",
                "name":"postprocess",
                "component":"ResizeRBBox",
                "params":{
                    "nms_pre":2000,
                    "min_bbox_size":0,
                    "score_thr":0.05,
                    "nms":{
                        "type":"nms_rotated",
                        "iou_threshold":0.1
                    },
                    "max_per_img":2000
                },
                "output":[
                    "post_output"
                ],
                "input":[
                    "prep_output",
                    "infer_output"
                ]
            }
        ]
    }
}
```

**Comment by kc-w** [comment]
> 1.0.0的代码有一个对pad参数的解析有问题，会认为是(h, w)。所以你把第一个pad的尺寸换一下应该就好了。第二个pad没必要，可以删掉。
> 
> #2063
> 
> ```json
> {
>     "pipeline":{
>         "input":[
>             "img"
>         ],
>         "output":[
>             "post_output"
>         ],
>         "tasks":[
>             {
>                 "type":"Task",
>                 "module":"Transform",
>                 "name":"Preprocess",
>                 "input":[
>                     "img"
>                 ],
>                 "output":[
>                     "prep_output"
>                 ],
>                 "transforms":[
>                     {
>                         "type":"LoadImageFromFile",
>                         "file_client_args":{
>                             "backend":"disk"
>                         }
>                     },
>                     {
>                         "type":"Resize",
>                         "keep_ratio":true,
>                         "size":[
>                             1056,
>                             1440
>                         ]
>                     },
>                     {
>                         "type":"Pad",
>                         "size":[
>                             1440,
>                             1056
>                         ],
>                         "pad_val":{
>                             "img":[
>                                 114,
>                                 114,
>                                 114
>                             ]
>                         }
>                     },
>                     {
>                         "type":"Normalize",
>                         "to_rgb":false,
>                         "mean":[
>                             103.53,
>                             116.28,
>                             123.675
>                         ],
>                         "std":[
>                             57.375,
>                             57.12,
>                             58.395
>                         ]
>                     },
>                     {
>                         "type":"DefaultFormatBundle"
>                     },
>                     {
>                         "type":"Collect",
>                         "meta_keys":[
>                             "valid_ratio",
>                             "img_shape",
>                             "flip_direction",
>                             "img_norm_cfg",
>                             "img_path",
>                             "img_id",
>                             "flip",
>                             "ori_filename",
>                             "pad_shape",
>                             "scale_factor",
>                             "filename",
>                             "ori_shape"
>                         ],
>                         "keys":[
>                             "img"
>                         ]
>                     }
>                 ]
>             },
>             {
>                 "name":"mmdet.rtmdet",
>                 "type":"Task",
>                 "module":"Net",
>                 "is_batched":true,
>                 "input":[
>                     "prep_output"
>                 ],
>                 "output":[
>                     "infer_output"
>                 ],
>                 "input_map":{
>                     "img":"input"
>                 },
>                 "output_map":{
> 
>                 }
>             },
>             {
>                 "type":"Task",
>                 "module":"mmrotate",
>                 "name":"postprocess",
>                 "component":"ResizeRBBox",
>                 "params":{
>                     "nms_pre":2000,
>                     "min_bbox_size":0,
>                     "score_thr":0.05,
>                     "nms":{
>                         "type":"nms_rotated",
>                         "iou_threshold":0.1
>                     },
>                     "max_per_img":2000
>                 },
>                 "output":[
>                     "post_output"
>                 ],
>                 "input":[
>                     "prep_output",
>                     "infer_output"
>                 ]
>             }
>         ]
>     }
> }
> ```

这个问题在1.1.0修复了吗?

**Comment by irexyc** [comment]
> 这个问题在1.1.0修复了吗?

修复了

**Comment by kc-w** [comment]
> 

好的,谢谢,我再试试看

**Comment by kc-w** [comment]
> @kc-w
> 
> 上面的删除了多余的Pad，顺序那个忘改了，跟你最初的是一样的，你那边改改看。

ok,成了
