### ISSUE TITLE
[Bug] convert mmocr model to tensorrt error

### ISSUE THREAD

**Issue by leemayi** [open-mmlab/mmdeploy#2188]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I run the follow cmd:
python ./tools/deploy.py configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-2240x2240.py D:/mmdep/mm/datas/ocr_mydata2/det/config.py D:/mmdep/mm/datas/ocr_mydata2/det/latest.pth D:/mmdep/mm/datas/ocr_mydata2/det/1.jpg --work-dir D:/mmdep/mm/datas/ocr_mydata2/det/trt --show --device cuda:0

error info:

(mmdeploy_1.1) PS D:\mmdep\mmdeploy-1.1.0\mmdeploy-1.1.0> python ./tools/deploy.py configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-2240x2240.py D:/mmdep/mm/datas/ocr_mydata2/det/config.py D:/mmdep/mm/datas/ocr_mydata2/det/latest.pth D:/mmdep/mm/datas/ocr_mydata2/det/1.jpg --work-dir D:/mmdep/mm/datas/ocr_mydata2/det/trt --show --device cuda:0
06/15 15:19:22 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
06/15 15:19:23 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
06/15 15:19:23 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: D:/mmdep/mm/datas/ocr_mydata2/det/latest.pth
06/15 15:19:25 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
06/15 15:19:25 - mmengine - INFO - Export PyTorch model to ONNX: D:/mmdep/mm/datas/ocr_mydata2/det/trt\end2end.onnx.
06/15 15:19:25 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
06/15 15:19:25 - mmengine - WARNING - Can not find mmdet.models.utils.transformer.PatchMerging.forward, function rewrite will not be applied
06/15 15:20:27 - mmengine - ERROR - d:\mmdep\mmdeploy-1.1.0\mmdeploy-1.1.0\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

### Reproduction

python ./tools/deploy.py configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-2240x2240.py D:/mmdep/mm/datas/ocr_mydata2/det/config.py D:/mmdep/mm/datas/ocr_mydata2/det/latest.pth D:/mmdep/mm/datas/ocr_mydata2/det/1.jpg --work-dir D:/mmdep/mm/datas/ocr_mydata2/det/trt --show --device cuda:0

### Environment

```Shell
06/15 16:25:37 - mmengine - INFO -

06/15 16:25:37 - mmengine - INFO - **********Environmental information**********
06/15 16:25:40 - mmengine - INFO - sys.platform: win32
06/15 16:25:40 - mmengine - INFO - Python: 3.8.16 (default, Jun 12 2023, 21:00:42) [MSC v.1916 64 bit (AMD64)]
06/15 16:25:40 - mmengine - INFO - CUDA available: True
06/15 16:25:40 - mmengine - INFO - numpy_random_seed: 2147483648
06/15 16:25:40 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3060
06/15 16:25:40 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
06/15 16:25:40 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.112
06/15 16:25:40 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31629 版
06/15 16:25:40 - mmengine - INFO - GCC: n/a
06/15 16:25:40 - mmengine - INFO - PyTorch: 1.12.1+cu116
06/15 16:25:40 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

06/15 16:25:40 - mmengine - INFO - TorchVision: 0.13.1+cu116
06/15 16:25:40 - mmengine - INFO - OpenCV: 4.7.0
06/15 16:25:40 - mmengine - INFO - MMEngine: 0.7.4
06/15 16:25:40 - mmengine - INFO - MMCV: 2.0.0
06/15 16:25:40 - mmengine - INFO - MMCV Compiler: MSVC 192829924
06/15 16:25:40 - mmengine - INFO - MMCV CUDA Compiler: 11.6
06/15 16:25:40 - mmengine - INFO - MMDeploy: 1.1.0+
06/15 16:25:40 - mmengine - INFO -

06/15 16:25:40 - mmengine - INFO - **********Backend information**********
06/15 16:25:40 - mmengine - INFO - tensorrt:    8.2.3.0
06/15 16:25:40 - mmengine - INFO - tensorrt custom ops: Available
06/15 16:25:40 - mmengine - INFO - ONNXRuntime: None
06/15 16:25:40 - mmengine - INFO - pplnn:       None
06/15 16:25:40 - mmengine - INFO - ncnn:        None
06/15 16:25:40 - mmengine - INFO - snpe:        None
06/15 16:25:40 - mmengine - INFO - openvino:    None
06/15 16:25:40 - mmengine - INFO - torchscript: 1.12.1+cu116
06/15 16:25:40 - mmengine - INFO - torchscript custom ops:      NotAvailable
06/15 16:25:40 - mmengine - INFO - rknn-toolkit:        None
06/15 16:25:40 - mmengine - INFO - rknn-toolkit2:       None
06/15 16:25:40 - mmengine - INFO - ascend:      None
06/15 16:25:40 - mmengine - INFO - coreml:      None
06/15 16:25:40 - mmengine - INFO - tvm: None
06/15 16:25:40 - mmengine - INFO - vacc:        None
06/15 16:25:40 - mmengine - INFO -

06/15 16:25:40 - mmengine - INFO - **********Codebase information**********
06/15 16:25:40 - mmengine - INFO - mmdet:       3.0.0
06/15 16:25:40 - mmengine - INFO - mmseg:       None
06/15 16:25:40 - mmengine - INFO - mmpretrain:  None
06/15 16:25:40 - mmengine - INFO - mmocr:       1.0.0
06/15 16:25:40 - mmengine - INFO - mmagic:      None
06/15 16:25:40 - mmengine - INFO - mmdet3d:     None
06/15 16:25:40 - mmengine - INFO - mmpose:      None
06/15 16:25:40 - mmengine - INFO - mmrotate:    None
06/15 16:25:40 - mmengine - INFO - mmaction:    None
06/15 16:25:40 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
(mmdeploy_1.1) PS D:\mmdep\mmdeploy-1.1.0\mmdeploy-1.1.0> python ./tools/deploy.py configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-2240x2240.py D:/mmdep/mm/datas/ocr_mydata2/det/config.py D:/mmdep/mm/datas/ocr_mydata2/det/latest.pth D:/mmdep/mm/datas/ocr_mydata2/det/1.jpg --work-dir D:/mmdep/mm/datas/ocr_mydata2/det/trt --show --device cuda:0
06/15 15:19:22 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
06/15 15:19:23 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
06/15 15:19:23 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: D:/mmdep/mm/datas/ocr_mydata2/det/latest.pth
06/15 15:19:25 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
06/15 15:19:25 - mmengine - INFO - Export PyTorch model to ONNX: D:/mmdep/mm/datas/ocr_mydata2/det/trt\end2end.onnx.
06/15 15:19:25 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
06/15 15:19:25 - mmengine - WARNING - Can not find mmdet.models.utils.transformer.PatchMerging.forward, function rewrite will not be applied
06/15 15:20:27 - mmengine - ERROR - d:\mmdep\mmdeploy-1.1.0\mmdeploy-1.1.0\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

**Comment by AllentDan** [comment]
Please provide detailed information about the model, I can not get any clue which text detection model you used.

**Comment by leemayi** [comment]
model = dict(
    type='DBNet',
    backbone=dict(
        type='mmdet.ResNet',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet18'),
        norm_eval=False,
        style='caffe'),
    neck=dict(
        type='FPNC', in_channels=[64, 128, 256, 512], lateral_channels=256),
    det_head=dict(
        type='DBHead',
        in_channels=256,
        module_loss=dict(type='DBModuleLoss'),
        postprocessor=dict(type='DBPostprocessor', text_repr_type='quad')),
    data_preprocessor=dict(
        type='TextDetDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_size_divisor=32))
train_pipeline = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    dict(
        type='LoadOCRAnnotations',
        with_polygon=True,
        with_bbox=True,
        with_label=True),
    dict(
        type='TorchVisionWrapper',
        op='ColorJitter',
        brightness=0.12549019607843137,
        saturation=0.5),
    dict(
        type='ImgAugWrapper',
        args=[['Fliplr', 0.5], {
            'cls': 'Affine',
            'rotate': [-10, 10]
        }, ['Resize', [0.5, 3.0]]]),
    dict(type='RandomCrop', min_side_ratio=0.1),
    dict(type='Resize', scale=(640, 640), keep_ratio=True),
    dict(type='Pad', size=(640, 640)),
    dict(
        type='PackTextDetInputs',
        meta_keys=('img_path', 'ori_shape', 'img_shape'))
]
test_pipeline = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    dict(type='Resize', scale=(1333, 736), keep_ratio=True),
    dict(
        type='LoadOCRAnnotations',
        with_polygon=True,
        with_bbox=True,
        with_label=True),
    dict(
        type='PackTextDetInputs',
        meta_keys=('img_path', 'ori_shape', 'img_shape', 'scale_factor'))
]
icdar2015_textdet_data_root = 'data/mydata2'
icdar2015_textdet_train = dict(
    type='OCRDataset',
    data_root='data/mydata2',
    ann_file='det.json',
    filter_cfg=dict(filter_empty_gt=True, min_size=32),
    pipeline=[
        dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
        dict(
            type='LoadOCRAnnotations',
            with_polygon=True,
            with_bbox=True,
            with_label=True),
        dict(
            type='TorchVisionWrapper',
            op='ColorJitter',
            brightness=0.12549019607843137,
            saturation=0.5),
        dict(
            type='ImgAugWrapper',
            args=[['Fliplr', 0.5], {
                'cls': 'Affine',
                'rotate': [-10, 10]
            }, ['Resize', [0.5, 3.0]]]),
        dict(type='RandomCrop', min_side_ratio=0.1),
        dict(type='Resize', scale=(640, 640), keep_ratio=True),
        dict(type='Pad', size=(640, 640)),
        dict(
            type='PackTextDetInputs',
            meta_keys=('img_path', 'ori_shape', 'img_shape'))
    ])
icdar2015_textdet_test = dict(
    type='OCRDataset',
    data_root='data/mydata2',
    ann_file='det.json',
    test_mode=True,
    pipeline=[
        dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
        dict(type='Resize', scale=(1333, 736), keep_ratio=True),
        dict(
            type='LoadOCRAnnotations',
            with_polygon=True,
            with_bbox=True,
            with_label=True),
        dict(
            type='PackTextDetInputs',
            meta_keys=('img_path', 'ori_shape', 'img_shape', 'scale_factor'))
    ])
default_scope = 'mmocr'
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
randomness = dict(seed=None)
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=5),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=20),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    sync_buffer=dict(type='SyncBuffersHook'),
    visualization=dict(
        type='VisualizationHook',
        interval=1,
        enable=True,
        show=False,
        draw_gt=True,
        draw_pred=True))
log_level = 'INFO'
log_processor = dict(type='LogProcessor', window_size=10, by_epoch=True)
load_from = '/home/pc/mmocr/mmocr-1.0.0/work_dirs/dbnet_resnet18_fpnc_1200e_icdar2015_mydata2/epoch_20.pth'
resume = False
val_evaluator = dict(type='HmeanIOUMetric')
test_evaluator = dict(type='HmeanIOUMetric')
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='TextDetLocalVisualizer',
    name='visualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    save_dir='/home/pc/mmocr/mmocr-1.0.0/show-dir/test')
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr=0.007, momentum=0.9, weight_decay=0.0001))
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=20, val_interval=20)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
param_scheduler = [dict(type='PolyLR', power=0.9, eta_min=1e-07, end=1200)]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='OCRDataset',
        data_root='data/mydata2',
        ann_file='det.json',
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(
                type='LoadOCRAnnotations',
                with_polygon=True,
                with_bbox=True,
                with_label=True),
            dict(
                type='TorchVisionWrapper',
                op='ColorJitter',
                brightness=0.12549019607843137,
                saturation=0.5),
            dict(
                type='ImgAugWrapper',
                args=[['Fliplr', 0.5], {
                    'cls': 'Affine',
                    'rotate': [-10, 10]
                }, ['Resize', [0.5, 3.0]]]),
            dict(type='RandomCrop', min_side_ratio=0.1),
            dict(type='Resize', scale=(640, 640), keep_ratio=True),
            dict(type='Pad', size=(640, 640)),
            dict(
                type='PackTextDetInputs',
                meta_keys=('img_path', 'ori_shape', 'img_shape'))
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='OCRDataset',
        data_root='data/mydata2',
        ann_file='det.json',
        test_mode=True,
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(type='Resize', scale=(1333, 736), keep_ratio=True),
            dict(
                type='LoadOCRAnnotations',
                with_polygon=True,
                with_bbox=True,
                with_label=True),
            dict(
                type='PackTextDetInputs',
                meta_keys=('img_path', 'ori_shape', 'img_shape',
                           'scale_factor'))
        ]))
test_dataloader = dict(
    batch_size=1,
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='OCRDataset',
        data_root='data/mydata2',
        ann_file='det.json',
        test_mode=True,
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(type='Resize', scale=(1333, 736), keep_ratio=True),
            dict(
                type='LoadOCRAnnotations',
                with_polygon=True,
                with_bbox=True,
                with_label=True),
            dict(
                type='PackTextDetInputs',
                meta_keys=('img_path', 'ori_shape', 'img_shape',
                           'scale_factor'))
        ]))
auto_scale_lr = dict(base_batch_size=2)
launcher = 'none'
work_dir = './work_dirs/dbnet_resnet18_fpnc_1200e_icdar2015_mydata2'

**Comment by leemayi** [comment]
Yes, except for modifying the dataset, I did not modify the model configuration of DBNet. So what should I do? Do I need to modify the versions of mmengine, mmcv, mmocr or mmdeploy?

**Comment by AllentDan** [comment]
The error log did not provide enough information. That's why I suggest you convert the official DBNet toTensorRT and check if the error appears.

**Comment by leemayi** [comment]
now I use the pretrain model https://gitee.com/link?target=https%3A%2F%2Fdownload.openmmlab.com%2Fmmocr%2Ftextdet%2Fdbnet%2Fdbnet_resnet18_fpnc_1200e_icdar2015%2Fdbnet_resnet18_fpnc_1200e_icdar2015_20220825_221614-7c0e94f2.pth
i got same error:

(mmdeploy_1.1) PS D:\mmdep\mmdeploy-1.1.0\mmdeploy-1.1.0> python ./tools/deploy.py  configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-2240x2240.py D:/mmdep/mmdeploy-1.1.0/mmocr-1.0.0/configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py D:/mmdep/mmdeploy-1.1.0/dbnet_resnet18_fpnc_1200e_icdar2015_20220825_221614-7c0e94f2.pth D:/mmdep/mm/datas/ocr_mydata2/det/1.jpg --work-dir D:/mmdep/mm/datas/ocr_mydata2/det/trt --show --device cuda:0
06/16 10:26:41 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
06/16 10:26:42 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
06/16 10:26:42 - mmengine - WARNING - Failed to search registry with scope "mmocr" in the "mmocr_tasks" registry tree. As a workaround, the current "mmocr_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmocr" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: D:/mmdep/mmdeploy-1.1.0/dbnet_resnet18_fpnc_1200e_icdar2015_20220825_221614-7c0e94f2.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

06/16 10:26:43 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
06/16 10:26:43 - mmengine - INFO - Export PyTorch model to ONNX: D:/mmdep/mm/datas/ocr_mydata2/det/trt\end2end.onnx.
06/16 10:26:43 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
06/16 10:26:43 - mmengine - WARNING - Can not find mmdet.models.utils.transformer.PatchMerging.forward, function rewrite will not be applied
06/16 10:27:49 - mmengine - ERROR - d:\mmdep\mmdeploy-1.1.0\mmdeploy-1.1.0\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

the cmd  :

python ./tools/deploy.py  configs/mmocr/text-detection/text-detection_tensorrt_dynamic-320x320-2240x2240.py D:/mmdep/mmdeploy-1.1.0/mmocr-1.0.0/configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py D:/mmdep/mmdeploy-1.1.0/dbnet_resnet18_fpnc_1200e_icdar2015_20220825_221614-7c0e94f2.pth D:/mmdep/mm/datas/ocr_mydata2/det/1.jpg --work-dir D:/mmdep/mm/datas/ocr_mydata2/det/trt --show --device cuda:0

**Comment by AllentDan** [comment]
Cannot reproduce the bug. @RunningLeon Do we have any method that can trace the detailed error log instead of just `pop_mp_output `?
