### ISSUE TITLE
[Docs] Build for Windows 7 with onnx inference engine sdk

### ISSUE THREAD

**Issue by blakeliu** [open-mmlab/mmdeploy#2198]
### 📚 The doc issue

1. Whether MMDEPLOY supports Win7?
2. Any doc for build win7 ?

**Comment by irexyc** [comment]
You can refer to [this](https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/01-how-to-build/windows.md)

Win7 is OK, we require vs studio >= 2019.

**Comment by blakeliu** [comment]
miss api-ms-win-core-libraryloader-l1-2-0.dll, but i download dll from [api-ms-win-core-libraryloader-l1-2-0](https://www.sts-tutorial.com/download/api-ms-win-core-libraryloader-l1-2-0) solved this problem!

**Comment by irexyc** [comment]
yeah, some vs runtime is needed, 

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
