### ISSUE TITLE
[Feature] support mmpretrain multitask

### ISSUE THREAD

**Issue by lonely0000cc** [open-mmlab/mmdeploy#2199]
### Motivation

could we support mmpretrain multitask deploy? current main branch there is no such feature and I didn't find any issue talking about this problem

**Comment by RunningLeon** [comment]
@lonely0000cc hi, can it be more specific? which model serves the multi-task in mmpretrain?

**Comment by frontierkodiak** [comment]
Has anybody tackled this? I'm considering tackling it this week. 

Will be a tall task, I expect a lot of workarounds to trace MultiTaskHead outputs. Probably not going to try adapting for C++ SDK unless it seems trivial or I find extra time on my hands.

Will submit a PR but it may be a while as I don't have much time to run tests or regressions right now.
