### ISSUE TITLE
There is a bug while visulizing the result.

### ISSUE THREAD

**Issue by Stephenfang51** [open-mmlab/mmdeploy#22]
https://github.com/open-mmlab/mmdeploy/blob/f2594c624b67910e55e24418832bd96685425b2f/mmdeploy/codebase/mmdet/deploy/object_detection_model.py#L586

This function only return the class name for open datasets like Cocodataset, not for custom.
Therefore it can't correctly put the right classname on imgs.
for now I can just change the return value to `list(model_cfg.classes)` to solve temporary
Thanks !

**Comment by RunningLeon** [comment]
@SingleZombie Could you take a look at this?

**Comment by SingleZombie** [comment]
> @SingleZombie Could you take a look at this?

I have figured out how to fix this bug. I think it is better to invite a maintainer of MMDet to review the PR. Who should we invite?

I also read the docs of MMCls and MMSeg. Their custom dataset doesn't contains `classes` field. This is an inconsistency. We should suggest other codebases to align the behavior.

**Comment by lvhan028** [comment]
> > @SingleZombie Could you take a look at this?
> 
> I have figured out how to fix this bug. I think it is better to invite a maintainer of MMDet to review the PR. Who should we invite?
@hhaAndroid

> I also read the docs of MMCls and MMSeg. Their custom dataset doesn't contains `classes` field. This is an inconsistency. We should suggest other codebases to align the behavior.

Please write it down in the requirement document

**Comment by SingleZombie** [comment]
> Please write it down in the requirement document

OK. I have written it down.
