### ISSUE TITLE
Is it possible to export onnx model with static shape but batch size >1 for the mmocr SATRN model?

### ISSUE THREAD

**Issue by Daisy5296** [open-mmlab/mmdeploy#2205]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Just a quick question as titled. The current static convertion can only use batch size =1.  How should I set the configs for batch size>1?

### Reproduction

python tools/deploy.py \
    configs/mmocr/text-recognition/text-recognition_onnxruntime_static.py \
    pthmodels/recog/tmp2/config.py \
    pthmodels/recog/tmp2/epoch_50.pth \
    demo/resources/text_recog.jpg \
    --work-dir mmdeploy_models/recog/onnx \
    --device cpu \
    --show \
    --dump-info

### Environment

```Shell
no need for this information currently.
```

**Comment by Ji-Hu** [comment]
python tools/deploy.py
configs/mmocr/text-recognition/text-recognition_onnxruntime_dynamic.py
pthmodels/recog/tmp2/config.py
pthmodels/recog/tmp2/epoch_50.pth
demo/resources/text_recog.jpg
--work-dir mmdeploy_models/recog/onnx
--device cpu
--show
--dump-info

**Comment by RunningLeon** [comment]
hi, you can try with dynamic batch deploy config like [configs/mmocr/text-recognition/text-recognition_dynamic.py](https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmocr/text-recognition/text-recognition_dynamic.py)

**Comment by Daisy5296** [comment]
But I actually need to set a fixed batch size, which cannot realized in the dynamic config, right? Only the width and height can be set fixed in the dynamic config.

**Comment by RunningLeon** [comment]
@Daisy5296 hi, you could try with this to make dynamic batch to fixed:
https://onnxruntime.ai/docs/tutorials/mobile/helpers/make-dynamic-shape-fixed.html

**Comment by Daisy5296** [comment]
Thanks! I managed to fix the dimensions. But there is a new problem. I fixed the input of satrn model to 16x3x32x100, and then I test it using the following code. The inference result is incorrect, where the result for the first data is different from the results for the rest 15 data. Could you please help to have a look? Thanks!

import numpy as np
import onnx
import onnxruntime as rt
 
#create input data
input_data = np.ones((16, 3, 32, 100), dtype=np.float32)
#create runtime session
sess = rt.InferenceSession("mmdeploy_models/recog/onnx/end2end_simp_static.onnx")
# get output name
input_name = sess.get_inputs()[0].name
print("input name", input_name)
output_name= sess.get_outputs()[0].name
print("output name", output_name)
output_shape = sess.get_outputs()[0].shape
print("output shape", output_shape)
#forward model
res = sess.run([output_name], {input_name: input_data})
out = np.array(res)
print("0: ", out[0][0])
print("2: ", out[0][2])
print("15: ", out[0][15])

**Comment by RunningLeon** [comment]
@Daisy5296 Hi, could you try with official model config and ckpt and use docker image so that we could reproduce your issue?
https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/build_from_docker.html#use-docker-image

**Comment by Daisy5296** [comment]
Thanks for reply! The problem can be easily reproduced using the official files. I found this issue reporting the same problem: https://github.com/open-mmlab/mmocr/issues/678 , and I can now get correct onnx inference result by revising the code in satrn model.

**Comment by RunningLeon** [comment]
> Thanks for reply! The problem can be easily reproduced using the official files. I found this issue reporting the same problem: [open-mmlab/mmocr#678](https://github.com/open-mmlab/mmocr/issues/678) , and I can now get correct onnx inference result by revising the code in satrn model.

@Daisy5296 hi, you can try add the rewriting function in mmdeploy like this. If this is a solution, welcome to give us a PR to fix the issue.
https://github.com/open-mmlab/mmdeploy/blob/d7489c883b6137e17518824b2b83b8624cbbb7ea/mmdeploy/codebase/mmocr/models/text_recognition/satrn_encoder.py#L11-L42
