### ISSUE TITLE
Can you provide an example explains how to convert models from pytorch to onnx or openvino?

### ISSUE THREAD

**Issue by TTgogogo** [open-mmlab/mmdeploy#221]
I need a detailed example, since I want to deploy the model in C++ on CPU, or C #. The first step is convert the model from pytorch to openvino, because I need to deploy on CPU.

**Comment by lvhan028** [comment]
@VVsssssk, could you provide an example of converting a mmdetection model to openvino?

**Comment by VVsssssk** [comment]
Hi, Convert model example:
```bash 
>>> python tools/deploy.py configs/mmdet/detection/detection_openvino_dynamic-800x1344.py \
${MMDET_DIR}/configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py \
${MMDET_DIR}/checkpoints/fcos_r50_caffe_fpn_gn-head_1x_coco-821213aa.pth \
${MMDET_DIR}/demo/demo.jpg \
--work-dir \
openvino_model \
--show \
--device \
cpu
```
MMDET_DIR is your mmdetection path. You can instead of model config and checkpoints. Result in openvino_model/.

**Comment by stephansturges** [comment]
> @VVsssssk, could you provide an example of converting a mmdetection model to openvino?

I'm confused by this too... I have read the docs but can't find a clear example of how to reference the openvino format.
