### ISSUE TITLE
[Bug] Can not install mmcv2.x on JetPack4.6.1

### ISSUE THREAD

**Issue by lurenzhouyi** [open-mmlab/mmdeploy#2219]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When I followed the tutorial https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/01-how-to-build/jetsons.md, I got an error that mmcv requires python>=3.7 when installing the mmcv. But the tutorial says that "JetPack SDK 4+ 自带 python 3.6。我们强烈建议使用默认的 python 版本。尝试升级 python 可能会破坏 JetPack 环境。"
So, how could I continue?
Maybe I can change the setup.py under /mmcv to make python>=3.6?

### Reproduction

sudo apt-get install -y libssl-dev
git clone --branch 2.x https://github.com/open-mmlab/mmcv.git
cd mmcv
MMCV_WITH_OPS=1 pip install -e .

### Environment

```Shell
Package           Version  Editable project location
----------------- -------- --------------------------------
addict            2.4.0
cycler            0.11.0
dataclasses       0.8
kiwisolver        1.3.1
matplotlib        3.3.4
mmengine          0.4.0
numpy             1.19.5
opencv-python     4.7.0.72
packaging         21.3
Pillow            8.4.0
pip               21.3.1
pyparsing         3.1.0
python-dateutil   2.8.2
PyYAML            6.0
setuptools        58.0.4
six               1.16.0
tensorrt          8.2.1.8
termcolor         1.1.0
torch             1.10.0
torchvision       0.11.1
typing_extensions 4.1.1
wheel             0.37.1
yapf              0.32.0

# R32 (release), REVISION: 7.4, GCID: 33514132, BOARD: t210ref, EABI: aarch64, DATE: Fri Jun  9 04:25:08 UTC 2023

python -c "import tensorrt; print(tensorrt.__version__)" # 将会打印出 TensorRT 版本
8.2.1.8
```

**Comment by RunningLeon** [comment]
pls. refer to same issue https://github.com/open-mmlab/mmdeploy/issues/2176#issuecomment-1588454586

**Comment by lurenzhouyi** [comment]
> pls. refer to same issue [#2176 (comment)](https://github.com/open-mmlab/mmdeploy/issues/2176#issuecomment-1588454586)

Ok, thank you
