### ISSUE TITLE
Why Function initLibMMCVInferPlugins() must be set in trt_plugin.cpp？

### ISSUE THREAD

**Issue by ethanyhzhang** [open-mmlab/mmdeploy#222]
Hi, 
    According to https://mmcv.readthedocs.io/en/latest/deployment/tensorrt_plugin.html, I need to add 

```
extern "C" {
bool initLibMMCVInferPlugins() { return true; }
}  // extern "C"
```

in trt_plugin.cpp when using custom plugin.

May I ask why it is needed? It seems to be called nowhere.

However, if it is not set, core dump happens when inferring.

Thanks~~

**Comment by grimoire** [comment]
Yes, It is not necessary. We used to register the ops creator in this function so users can optionally load the plugin.
Actually, we do not have such a function in this repo, each op is registered in its own codes.

**Comment by ethanyhzhang** [comment]
> Yes, It is not necessary. We used to register the ops creator in this function so users can optionally load the plugin. Actually, we do not have such a function in this repo, each op is registered in its own codes.

Got it! Maybe something else might go wrong when I get rid of this function. I'll check again.
