### ISSUE TITLE
[Feature]  add is_resize_mask configuration option in instance_segmentation.cpp

### ISSUE THREAD

**Issue by ruisv** [open-mmlab/mmdeploy#2227]
### Motivation

Hi,
I found that when using the mmdeploy sdk to infer the instance segmentation model, the mask is resized and cropped by default.
eg:
<img width="469" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/27017322/c3f5a8b0-9ed0-4e4c-9f53-f528882889b3">

Somtime, the user may need to keep the original mask (such as the shape of the input image is consistent).
eg:
<img width="397" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/27017322/6427fa03-8ce3-4a41-b968-4d6dc4cf9baf">

I think a configuration option should be added to control. (pipeline.json)
eg:
<img width="289" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/27017322/7d2b3e4f-c18d-4e9b-a766-5c317e98940f">

Thanks.

### Additional context

The following repo contains my commits.
[https://github.com/ruisv/mmdeploy/commit/599617e41d041ebccdc14e58d7e8fba80cdcea48](https://github.com/ruisv/mmdeploy/commit/599617e41d041ebccdc14e58d7e8fba80cdcea48)

**Comment by irexyc** [comment]
@ruisv 
I agree with you.

Could you please create a pull request to merge your changes to our main branch?

Moreover, I think you should export the `is_resize_mask` param when convert the model.
https://github.com/open-mmlab/mmdeploy/blob/main/mmdeploy/codebase/mmdet/deploy/object_detection.py#L317-L318

**Comment by ruisv** [comment]
Thank you for your reply .
I will create a pull request later.

**Comment by ruisv** [comment]
Hi,
I have submitted a pull request wit u advice.
https://github.com/open-mmlab/mmdeploy/pull/2229
