### ISSUE TITLE
官网docker镜像没有python解释器么[Bug] 

### ISSUE THREAD

**Issue by lychenpan** [open-mmlab/mmdeploy#2233]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

deploy 的docker环境，没有python解释器 

### Reproduction

`docker run -itd --name cp2 --gpus=all 72f61909817b`
`docker exec -it cp2 /bin/bash`
![image](https://github.com/open-mmlab/mmdeploy/assets/6816307/6c97c8f7-b33e-46fb-8f7b-9d62b7f93e85)

### Environment

```Shell
官网 docker 环境
```

**Comment by RunningLeon** [comment]
@lychenpan hi, should use `python3` or you could create the soft-link: `ln -sf /usr/bin/python3 /usr/bin/python`
