### ISSUE TITLE
[Bug]C++ calls to versions 1.2.0 and 1.1.0 found no inference possible(windows)

### ISSUE THREAD

**Issue by wys2641970184** [open-mmlab/mmdeploy#2234]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/open-mmlab/mmdeploy/assets/26566137/543c0ed5-b931-4b13-aff1-198bc9b3e653)
This error will not occur every time but will occur quite often:
my call code:
cv::Mat  DetectorImage(cv::Mat img)
{
    try
    {
        const char* device_name = "cpu";
        int device_id = 0;
        // mmdeploy SDK model，以上文中转出的 faster r-cnn 模型为例
        std::string model_path = "C:\\MyOpenMMService\\Run2";
        //std::string image_path = "C:\\MyOpenMMService\\Run\\1.png";
        //// 1. 读取模型
        //mmdeploy::Model model(model_path);

        //// construct a detector instance
        //mmdeploy::Context ctx{};
        //mmdeploy::Device device{ "cpu" };
        //ctx.Add(device);
        //mmdeploy::RotatedDetector detector(model, ctx);

        // construct a detector instance
        mmdeploy::RotatedDetector detector(mmdeploy::Model{ model_path }, mmdeploy::Device{ "cpu" });

        // apply the detector, the result is an array-like class holding references to
        // `mmdeploy_rotated_detection_t`, will be released automatically on destruction
        //mmdeploy::RotatedDetector::Result dets = detector.Apply(img);

        // 2. 创建预测器
       //mmdeploy::RotatedDetector detector(model, mmdeploy::Device{ device_name, device_id });
        // 3. 读取图像
        //cv::Mat img = cv::imread(image_path);

        // 4. 应用预测器推理
        auto dets = detector.Apply(img);

### Reproduction

versions 1.2.0 and 1.1.0

### Environment

```Shell
windows  vs2022
```

**Comment by irexyc** [comment]
建议在cmd中跑跑看，一般会有一些提示。你这个问题有可能是跟系统自带的onnxruntime.dll冲突了，你可以把`thirdparty/onnxruntime/lib/`目录下的dll拷贝到你编译出来的exe目录下面再跑跑看

**Comment by wys2641970184** [comment]
> 建议在cmd中跑跑看，一般会有一些提示。你这个问题有可能是跟系统自带的onnxruntime.dll冲突了，你可以把`thirdparty/onnxruntime/lib/`目录下的dll拷贝到你编译出来的exe目录下面再跑跑看

感谢您的回复,已经把onnxruntime.dll放到exe的执行目录下了

**Comment by irexyc** [comment]
> 感谢您的回复,已经把onnxruntime.dll放到exe的执行目录下了

还会报错不

**Comment by wys2641970184** [comment]
> > 感谢您的回复,已经把onnxruntime.dll放到exe的执行目录下了
> 
> 还会报错不

之前就是放里面的 不是这块的问题，现在发现是cuda可以不报错，cpu就会报错，但是更奇怪的是cpu成功的时候推理一张图片大约是1秒，cuda推理一张图片大约是2.2秒

**Comment by irexyc** [comment]
你不会只是看第一次的耗时吧，怎么着你也得循环跑100次看平均吧。

cpu有时失败有时成功？可以把你的代码贴出来看看

**Comment by wys2641970184** [comment]
> 你不会只是看第一次的耗时吧，怎么着你也得循环跑100次看平均吧。
> 
> cpu有时失败有时成功？可以把你的代码贴出来看看

cv::Mat  DetectorImage(cv::Mat img)
{
    try
    {
        const char* device_name = "cuda";
        int device_id = 0;
        // mmdeploy SDK model，以上文中转出的 faster r-cnn 模型为例
        std::string model_path = "C:\\MyOpenMMService\\Run2";
        //std::string image_path = "C:\\MyOpenMMService\\Run\\1.png";
        // 1. 读取模型
        mmdeploy::Model model(model_path);

        // 2. 创建预测器
        mmdeploy::RotatedDetector detector(model, mmdeploy::Device{ device_name, device_id });
        // 3. 读取图像
        //cv::Mat img = cv::imread(image_path);

        //提高推理速度减小图片大小，该操作对速度的影响有限
        int cols = img.cols;
        int rows = img.rows;
        int factor = 2; //缩小比例
        cv::Mat outImg;
        cv::resize(img, outImg, cv::Size(cols/ factor, rows/ factor));
        // 4. 应用预测器推理
        auto dets = detector.Apply(outImg);

**Comment by irexyc** [comment]
有完整的代码么？跑demo的面的代码会失败么？

不要每次都传图片都创建一次RotatedDetector，创建handle尤其是cuda上面的比较耗时。在你程序的生命周期中应该是只创建一次
