### ISSUE TITLE
Is there any docker for mmdeploy?

### ISSUE THREAD

**Issue by LLsmile** [open-mmlab/mmdeploy#2237]
### Motivation

It seems the latest version doesn't support latest mmdet/mmrotate. So is there any docker for latest version?
`python3 tools/scripts/build_ubuntu_x64_ort.py $(nproc)` shows following info:

07/03 14:59:55 - mmengine - INFO - **********Codebase information**********
07/03 14:59:56 - mmengine - INFO - mmdet:	2.28.2
07/03 14:59:56 - mmengine - INFO - mmseg:	None
07/03 14:59:56 - mmengine - INFO - mmcls:	None
07/03 14:59:56 - mmengine - INFO - mmocr:	None
07/03 14:59:56 - mmengine - INFO - mmedit:	None
07/03 14:59:56 - mmengine - INFO - mmdet3d:	None
07/03 14:59:56 - mmengine - INFO - mmpose:	None
07/03 14:59:56 - mmengine - INFO - mmrotate:	0.3.4
07/03 14:59:56 - mmengine - INFO - mmaction:	None

**Comment by RunningLeon** [comment]
@LLsmile hi, 
1. for docker usage, you could refer to https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/build_from_docker.html#get-prebuilt-docker-images
2. could use `dev-1.x` for `mmrotate`

**Comment by LLsmile** [comment]
I'm confusd with those repo. Is dev-1.x latest version for all mm-repo? I have tried main branch and 1.x branch but failed. dev-1.x for mmdeploy works but the model is trained on 1.x branch of mmrotate.

**Comment by RunningLeon** [comment]
@LLsmile hi, most repos based on openmmlab2.0 have switched the default branch to `main` branch. You may ask in mmrotate repo for the branch issue.

**Comment by RunningLeon** [comment]
@LLsmile most likely no need to retrain. You could ask it in mmrotate repo and get how to adapt the config

**Comment by LLsmile** [comment]
ok, thanks.
