### ISSUE TITLE
How to integrate a new third-party library and use it？

### ISSUE THREAD

**Issue by Josh1021** [open-mmlab/mmdeploy#2238]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I want to encrypt the TensorRT model converted by MMDeploy using [Crypto++](https://github.com/weidai11/cryptopp)， then decrypt model to buffer, and use ` mmdeploy_detector_create` to load model.
I have organized the header files and library files,  and put them in the `third_party` directory and added `test.cpp` to the demo for testing the encryption and decryption interfaces. However, it is showing an error indicating that the dependent header files cannot be found.
So I'm unsure where to place them and how to modify the makefile to correctly invoke them.

### Reproduction

no

### Environment

```Shell
2023-07-03 17:00:54,036 - mmdeploy - INFO - sys.platform: win32
2023-07-03 17:00:54,036 - mmdeploy - INFO - Python: 3.8.16 (default, Jun 12 2023, 21:00:42) [MSC v.1916 64 bit (AMD64)]
2023-07-03 17:00:54,037 - mmdeploy - INFO - CUDA available: True
2023-07-03 17:00:54,037 - mmdeploy - INFO - GPU 0: NVIDIA GeForce GTX 1660 Ti
2023-07-03 17:00:54,038 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
2023-07-03 17:00:54,038 - mmdeploy - INFO - NVCC: Not Available
2023-07-03 17:00:54,038 - mmdeploy - INFO - GCC: n/a
2023-07-03 17:00:54,039 - mmdeploy - INFO - PyTorch: 1.10.0+cu113
2023-07-03 17:00:54,039 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

2023-07-03 17:00:54,040 - mmdeploy - INFO - TorchVision: 0.11.0+cu113
2023-07-03 17:00:54,040 - mmdeploy - INFO - OpenCV: 4.7.0
2023-07-03 17:00:54,041 - mmdeploy - INFO - MMCV: 1.4.0
2023-07-03 17:00:54,041 - mmdeploy - INFO - MMCV Compiler: MSVC 192930151
2023-07-03 17:00:54,041 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2023-07-03 17:00:54,042 - mmdeploy - INFO - MMDeploy: 0.14.0+c737563
2023-07-03 17:00:54,043 - mmdeploy - INFO -

2023-07-03 17:00:54,043 - mmdeploy - INFO - **********Backend information**********
2023-07-03 17:00:56,184 - mmdeploy - INFO - tensorrt:   8.2.3.0
2023-07-03 17:00:56,184 - mmdeploy - INFO - tensorrt custom ops:        Available
2023-07-03 17:00:56,320 - mmdeploy - INFO - ONNXRuntime:        None
2023-07-03 17:00:56,320 - mmdeploy - INFO - ONNXRuntime-gpu:    1.8.1
2023-07-03 17:00:56,321 - mmdeploy - INFO - ONNXRuntime custom ops:     Available
2023-07-03 17:00:56,325 - mmdeploy - INFO - pplnn:      None
2023-07-03 17:00:56,347 - mmdeploy - INFO - ncnn:       None
2023-07-03 17:00:56,388 - mmdeploy - INFO - snpe:       None
2023-07-03 17:00:56,392 - mmdeploy - INFO - openvino:   None
2023-07-03 17:00:56,396 - mmdeploy - INFO - torchscript:        1.10.0+cu113
2023-07-03 17:00:56,396 - mmdeploy - INFO - torchscript custom ops:     NotAvailable
2023-07-03 17:00:56,449 - mmdeploy - INFO - rknn-toolkit:       None
2023-07-03 17:00:56,449 - mmdeploy - INFO - rknn2-toolkit:      None
2023-07-03 17:00:56,455 - mmdeploy - INFO - ascend:     None
2023-07-03 17:00:56,457 - mmdeploy - INFO - coreml:     None
2023-07-03 17:00:56,459 - mmdeploy - INFO - tvm:        None
2023-07-03 17:00:56,460 - mmdeploy - INFO -

2023-07-03 17:00:56,460 - mmdeploy - INFO - **********Codebase information**********
2023-07-03 17:01:01,656 - mmdeploy - INFO - mmdet:      2.23.0
2023-07-03 17:01:01,656 - mmdeploy - INFO - mmseg:      None
2023-07-03 17:01:01,657 - mmdeploy - INFO - mmcls:      None
2023-07-03 17:01:01,657 - mmdeploy - INFO - mmocr:      None
2023-07-03 17:01:01,657 - mmdeploy - INFO - mmedit:     None
2023-07-03 17:01:01,658 - mmdeploy - INFO - mmdet3d:    None
2023-07-03 17:01:01,658 - mmdeploy - INFO - mmpose:     None
2023-07-03 17:01:01,658 - mmdeploy - INFO - mmrotate:   None
2023-07-03 17:01:01,659 - mmdeploy - INFO - mmaction:   None
```

**Comment by irexyc** [comment]
You need to organize CMakeLists files, but It's not easy to explain the details.

You can fork mmdeploy, commit changes to your repo, so the we can give you some advice.

**Comment by Josh1021** [comment]
@irexyc hi，i forked [mmdeploy](https://github.com/Josh1021/mmdeploy/tree/main), and commit changes to my repo, here are three commits：
1. add .h and lib of cryptopp to third_party 
2. add encryptor.cxx in demo\csrc\cpp\ ,, the encryptor.cxx simplely test api of cryptopp. 
3. add `add_example(detector cpp encryptor)` to  demo\csrc\CMakeLists.txt
please give me some advice of how to organize CMakeLists and encryptor.cxx

**Comment by Josh1021** [comment]
@irexyc hi,  I modified the CMakeLists.txt file and added two lines of code. 
```
include_directories(${CMAKE_SOURCE_DIR}/third_party/cryptopp/include)
link_directories($${CMAKE_SOURCE_DIR}/third_party/cryptopp/lib)
```
When building, I encountered the following error，is it because the library is not correctly linked?:
```
encrypt.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl CryptoPP::Algorithm::Algorithm(bool)" (??0Algorithm@Crypto
PP@@QEAA@_N@Z)，函数 "public: __cdecl CryptoPP::SourceTemplate<class CryptoPP::StringStore>::SourceTemplate<class CryptoPP
::StringStore>(class CryptoPP::BufferedTransformation *)" (??0?$SourceTemplate@VStringStore@CryptoPP@@@CryptoPP@@QEAA@P
EAVBufferedTransformation@1@@Z) 中引用了该符号 [C:\project\mmdeploy\build\demo\csrc\encrypt.vcxproj]
encrypt.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl CryptoPP::SimpleKeyingInterface::SetKey(unsig
ned char const *,unsigned __int64,class CryptoPP::NameValuePairs const &)" (?SetKey@SimpleKeyingInterface@CryptoPP@@UEA
AXPEBE_KAEBVNameValuePairs@2@@Z) [C:\project\mmdeploy\build\demo\csrc\encrypt.vcxproj]
encrypt.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl CryptoPP::SimpleKeyingInterface::SetKeyWithIV(unsigne
d char const *,unsigned __int64,unsigned char const *,unsigned __int64)" (?SetKeyWithIV@SimpleKeyingInterface@CryptoPP@
@QEAAXPEBE_K01@Z)，函数 main 中引用了该符号 [C:\project\mmdeploy\build\demo\csrc\encrypt.vcxproj]
...
encrypt.exe : fatal error LNK1120: 93 个无法解析的外部命令
```

**Comment by irexyc** [comment]
You forget to link cryptopp library.

I suggest you to use the cmake version of [cryptopp](https://github.com/abdes/cryptopp-cmake) for better project management.

```
git clone https://github.com/abdes/cryptopp-cmake
cd cryptopp-cmake
mkdir build
cd build
cmake .. -A x64 -T v142 -DCMAK_INSTALL_PREFIX=install
cmake --build . --config Release
cmake --install . --config Relase
```

After build cryptopp, you can use it in your project like this
```
# the project folder
CMakeLists.txt
demo.cpp
```

```
# the content of CMakeLists.txt

cmake_minimum_required(VERSION 3.14)
project(mmdeploy-example)

find_package(cryptopp REQUIRED)
add_executable(demo demo.cpp)
target_link_libraries(demo cryptopp::cryptopp)
```


```
# in project folder
mkdir build
cd build
cmake .. -A x64 -T v142 -Dcryptopp_DIR=\path\to\cryptopp-repo\build\install\share\cmake\cryptopp
cmake --build . --config Release
```

**Comment by Josh1021** [comment]
@irexyc thank you very much for your advice！！
I followed your advice step by step, but encountered an error in the last step. It reported the following error：
```
LINK : fatal error LNK1104: 无法打开文件“cryptopp::cryptopp-NOTFOUND.obj” [C:\project\cryptopp-cmake\demo\build\encrypt.vcxproj]
```
and one difference is that ` -Dcryptopp_DIR=\path\to\cryptopp-repo\build\install\share\cmake\cryptopp ` is different from mine. The structure of my path is like this:
` -Dcryptopp_DIR="C:\Program Files\cryptopp-cmake\share\cmake\cryptopp"` , this path is  automatically generated。

**Comment by Josh1021** [comment]
When I was installing, it automatically installed to this path `C:/Program Files/cryptopp-cmake/`, it should be installed under the path `C:\project\cryptopp-cmake\build\install`。。I tried to modify `-DCMAKE_INSTALL_PREFIX` didn't work either,,,,,
```
git clone https://github.com/abdes/cryptopp-cmake
...
cmake --install . --config Relase
```

**Comment by Josh1021** [comment]
My installation folder structure, is different from you.
```
PS C:\project\cryptopp-cmake\build\install>
|-- include
|   `-- cryptopp
`-- share
    |-- cmake
    |-- cryptopp
    `-- pkgconfig
```

**Comment by Josh1021** [comment]
> It's strange, you can use the upload file. [install.zip](https://github.com/open-mmlab/mmdeploy/files/11958022/install.zip)
it's works, thank you!!
Now i using mmdeploy api to load decrypted engine model, this is my code, `decrypt ` outputs the decrypted string model, i saved decrypted string model and it is same with ori model,
```
std::string decrypted_model{};
auto ret = decrypt(full_model_path.c_str(), sKey, s_iv, decrypted_model);
const void* buffer = reinterpret_cast<const void*>(decrypted_model.c_str());
size_t size_in_bytes = decrypted_model.length() * sizeof(char);
mmdeploy_model_t model{};
ec = mmdeploy_model_create(buffer, size_in_bytes, &model);
ec = mmdeploy_detector_create(model, device_name, device_id, &detector_);

```
but there is an error, could you help me confirm if I have correctly used the API?
```
 [mmdeploy] [error] [model.cpp:57] Failed to parse model buffer, implementations tried: [("DirectoryModel", 0)]
 [mmdeploy] [error] [model.cpp:34] failed to create model: not supported (2)
```

**Comment by irexyc** [comment]
@Josh1021 

The model loader only support `DirectoryModel` before v1.2.0 in prebuild package. After v1.2.0(enclude) we build sdk package with `MMDEPLOY_ZIP_MODEL=ON`, therefore it support `ZipModel` (reading model in zip format).

To use the `ZipModel` model reader, you have to first convert the model to a directory, then compress the folder in zip format. As you want to encrypt the model, then you should encrypt the zip file.

In short, If you used the prebuild package, please use version >= v1.2.0. When encrypt the model, encrypt the zip file(compressed folder) instead of the engine file like .engine or .onnx.

Moreover, the prebuild package are provided as a dynamic library. The model weights are at risk of leaking as the user could build mmdeploy themselves and replace the library. To avoid this, you can build mmdeploy yourself, either build it as static library or add the decrypt code to mmdeploy and build them same time. You can find our prebuild command and environment in this [ci file](https://github.com/open-mmlab/mmdeploy/blob/main/.github/workflows/prebuild.yml)

**Comment by Josh1021** [comment]
Understood，but i builded mmdeploy-0.14.0 from source on windows，can it work  if  i rebuild sdk package with MMDEPLOY_ZIP_MODEL=ON and  decrypt the zip file?

**Comment by irexyc** [comment]
Honestly speadking, we haven't updated 0.x branch for a long time. The `MMDEPLOY_ZIP_MODEL=ON` option only support on 1.x branch. You can use main branch (1.x), their difference is very small and some bug fixed only commited to 1.x. 

If you use old mmocr and mmdeploy 0.x to convert the model, you needs modify some places in pipeline.json to inference the model with mmdeploy sdk 1.x . But from my experience,  mmdet should be ok without modification. If you encounter any problems with mmdeploy sdk 1.x, you can paste the pipeline.json and I will check it.

**Comment by Josh1021** [comment]
Hi，I upgrade mmdeploy to 1.2 and rebuild from source on Windows with `MMDEPLOY_ZIP_MODEL=ON` and decrypt code to mmdeploy. It worked when I encrypted and decrypted the zip format model converted from mmdeploy 0.x and mmdet 2.x, and then used `mmdeploy_model_create` and `mmdeploy_detector_create` to create and apply the detector. Thank you for the great work!
