### ISSUE TITLE
ONNX inference in batch mode?

### ISSUE THREAD

**Issue by Macok** [open-mmlab/mmdeploy#2241]
### 📚 The doc issue

I converted my detection model to ONNX, but I don't know how to run inference in batch mode.

```
from mmdeploy_runtime import Detector
imgs = [cv2.imread('./test.jpg')] * 10
detector = Detector(model_path='mmdeploy_model/my_model', device_name='cpu', device_id=0)
bboxes, labels, _ = detector(imgs)
```
Results in:
```
RuntimeError: continuous uint8 HWC array expected
```
How do I run inference in batch mode?

**Comment by irexyc** [comment]
https://github.com/open-mmlab/mmdeploy/blob/main/csrc/mmdeploy/apis/python/detector.cpp#L72-L83

Try this:
```
bboxes, labels, _ = detector.batch(imgs)
```

**Comment by Macok** [comment]
Thanks, it worked!

But do you have any idea why using batch mode gives me no speed-up over a simple for loop?
I used this config to convert my RTMDet model to ONNX:
`configs/mmdet/detection/detection_onnxruntime_dynamic.py`
I'm using CPU for inference.

**Comment by irexyc** [comment]
You can try edit `pipeline.json` like this https:github.com/open-mmlab/mmdeploy/issues/917#issuecomment-1235269474

If there is still no speed-up, you can check if there is a speed-up when you use pure onnxruntime api like:

```python
import onnxruntime as ort
import numpy as np
import time

# the input shape, input/output names different according to your onnx model, you can check yours through netron.

height = 300
width = 300

single = np.random.randn(1, 3, height, width).astype(np.float32) 
sess = ort.InferenceSession('end2end.onnx')

def perf(bsz = 1, n = 100):
  batch_input = single.repeat(bsz, axis=0)
  t1 = time.perf_counter()
  for i in  range(n):
    dets, labels = sess.run(['dets', 'labels'], input_feed = {'input': batch_input})
  t2 = time.perf_counter()
  print((t2 - t1) / n * 1000)


perf(1)
perf(2)
perf(4)
perf(8)



```

**Comment by Macok** [comment]
@irexyc Thanks a lot for your help.

I run your code and here are the results:
```
$ python3 test.py
35.33875143970363
69.82134588062763
141.44253252074122
284.8587305599358
```
So apparently there's no speedup even with pure ONNX api. Do you have any idea why it is so?

**Comment by irexyc** [comment]
Some layers may not benefit from batching.

Onnxruntime has a [profiling tools](https://onnxruntime.ai/docs/performance/tune-performance/profiling-tools.html) that you can use.

You can also try to run it on cuda with `CUDAExecutionProvider`
