### ISSUE TITLE
Mask Rcnn (engine gpu model), the mask predicted by the model is out of bounds

### ISSUE THREAD

**Issue by SHX9610** [open-mmlab/mmdeploy#2243]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I use mask rcnn (engine model, gpu, converted by mmdeploy) to predict test-datasets, then, I find the predicted mask **exceeds the boundary**(mask beyond image resolution, such as bottom > image.height or right > image.width).

The first time I encountered this situation，not sure if there is a problem with **mm conversion** or **not enough model training** data.

### Reproduction

Nothing

Just train model in MMdetection and convert model in MMdeploy

### Environment

```Shell
Nothing
```

**Comment by RunningLeon** [comment]
@SHX9610 hi, pls. try with the official model config and ckpt.
