### ISSUE TITLE
[Bug] infer ocr tensort with 10 batch， got wrong result

### ISSUE THREAD

**Issue by leemayi** [open-mmlab/mmdeploy#2244]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I use a 10-batch tensorrt model(satrn) and the prediction is wrong, but the prediction result using 1 batch is correct

the mmocr model :  satrn

the wrong result: 
Except for the first one are 0000000000000000000000000000000000000000000000000000000000000000000000000000000000

bbox_count=18
box[0]: 2
x: 755.00, y: 630.00, x: 782.00, y: 629.00, x: 784.00, y: 692.00, x: 757.00, y: 693.00,
box[1]: 0000000000000000000000000
x: 786.00, y: 687.00, x: 786.00, y: 625.00, x: 817.00, y: 625.00, x: 817.00, y: 687.00,
box[2]: 0000000000000000000000000
x: 816.00, y: 624.00, x: 847.00, y: 622.00, x: 850.00, y: 685.00, x: 820.00, y: 687.00,
box[3]: 0000000000000000000000000
x: 846.00, y: 626.00, x: 873.00, y: 624.00, x: 879.00, y: 686.00, x: 852.00, y: 688.00,
box[4]: 0000000000000000000000000
x: 876.00, y: 626.00, x: 905.00, y: 624.00, x: 908.00, y: 685.00, x: 880.00, y: 687.00,
box[5]: 0000000000000000000000000
x: 913.00, y: 689.00, x: 913.00, y: 629.00, x: 940.00, y: 629.00, x: 940.00, y: 689.00,
box[6]: 0000000000000000000000000
x: 720.00, y: 634.00, x: 752.00, y: 633.00, x: 754.00, y: 696.00, x: 723.00, y: 697.00,
box[7]: 0000000000000000000000000
x: 687.00, y: 641.00, x: 718.00, y: 639.00, x: 721.00, y: 704.00, x: 691.00, y: 706.00,
box[8]: 0000000000000000000000000
x: 854.00, y: 698.00, x: 882.00, y: 697.00, x: 886.00, y: 757.00, x: 858.00, y: 759.00,
box[9]: 0000000000000000000000000
x: 825.00, y: 698.00, x: 853.00, y: 697.00, x: 855.00, y: 759.00, x: 827.00, y: 760.00,

### Reproduction

c++ sdk

mmocr tensorrt model : dbnet + satrn

the detail.json

{
    "version": "1.1.0",
    "codebase": {
        "task": "TextRecognition",
        "codebase": "mmocr",
        "version": "1.0.0",
        "pth": "satrn_mydata3.pth",
        "config": "satrn_mydata3.py"
    },
    "codebase_config": {
        "type": "mmocr",
        "task": "TextRecognition"
    },
    "onnx_config": {
        "type": "onnx",
        "export_params": true,
        "keep_initializers_as_inputs": false,
        "opset_version": 11,
        "save_file": "end2end.onnx",
        "input_names": [
            "input"
        ],
        "output_names": [
            "output"
        ],
        "input_shape": null,
        "optimize": true,
        "dynamic_axes": {
            "input": {
                "0": "batch",
                "3": "width"
            },
            "output": {
                "0": "batch",
                "1": "seq_len",
                "2": "num_classes"
            }
        }
    },
    "backend_config": {
        "type": "tensorrt",
        "common_config": {
            "fp16_mode": true,
            "max_workspace_size": 1073741824
        },
        "model_inputs": [
            {
                "input_shapes": {
                    "input": {
                        "min_shape": [
                            10,
                            3,
                            32,
                            100
                        ],
                        "opt_shape": [
                            10,
                            3,
                            32,
                            100
                        ],
                        "max_shape": [
                            10,
                            3,
                            32,
                            100
                        ]
                    }
                }
            }
        ]
    },
    "calib_config": {}
}

### Environment

```Shell
07/05 13:05:50 - mmengine - [4m[97mINFO[0m -

07/05 13:05:50 - mmengine - [4m[97mINFO[0m - **********Environmental information**********
07/05 13:05:52 - mmengine - INFO - sys.platform: win32
07/05 13:05:52 - mmengine - INFO - Python: 3.8.16 (default, Jun 12 2023, 21:00:42) [MSC v.1916 64 bit (AMD64)]
07/05 13:05:52 - mmengine - INFO - CUDA available: True
07/05 13:05:52 - mmengine - INFO - numpy_random_seed: 2147483648
07/05 13:05:52 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3060
07/05 13:05:52 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
07/05 13:05:52 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.112
07/05 13:05:52 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31629 版
07/05 13:05:52 - mmengine - INFO - GCC: n/a
07/05 13:05:52 - mmengine - INFO - PyTorch: 1.12.1+cu116
07/05 13:05:52 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

07/05 13:05:52 - mmengine - INFO - TorchVision: 0.13.1+cu116
07/05 13:05:52 - mmengine - INFO - OpenCV: 4.7.0
07/05 13:05:52 - mmengine - INFO - MMEngine: 0.7.4
07/05 13:05:52 - mmengine - INFO - MMCV: 2.0.0
07/05 13:05:52 - mmengine - INFO - MMCV Compiler: MSVC 192829924
07/05 13:05:52 - mmengine - INFO - MMCV CUDA Compiler: 11.6
07/05 13:05:52 - mmengine - INFO - MMDeploy: 1.1.0+
07/05 13:05:52 - mmengine - INFO -

07/05 13:05:52 - mmengine - INFO - **********Backend information**********
07/05 13:05:52 - mmengine - INFO - tensorrt:    8.6.1
07/05 13:05:52 - mmengine - INFO - tensorrt custom ops: Available
07/05 13:05:52 - mmengine - INFO - ONNXRuntime: None
07/05 13:05:52 - mmengine - INFO - pplnn:       None
07/05 13:05:52 - mmengine - INFO - ncnn:        None
07/05 13:05:52 - mmengine - INFO - snpe:        None
07/05 13:05:52 - mmengine - INFO - openvino:    None
07/05 13:05:52 - mmengine - INFO - torchscript: 1.12.1+cu116
07/05 13:05:52 - mmengine - INFO - torchscript custom ops:      NotAvailable
07/05 13:05:52 - mmengine - INFO - rknn-toolkit:        None
07/05 13:05:52 - mmengine - INFO - rknn-toolkit2:       None
07/05 13:05:52 - mmengine - INFO - ascend:      None
07/05 13:05:52 - mmengine - INFO - coreml:      None
07/05 13:05:52 - mmengine - INFO - tvm: None
07/05 13:05:52 - mmengine - INFO - vacc:        None
07/05 13:05:52 - mmengine - INFO -

07/05 13:05:52 - mmengine - INFO - **********Codebase information**********
07/05 13:05:52 - mmengine - INFO - mmdet:       3.0.0
07/05 13:05:52 - mmengine - INFO - mmseg:       None
07/05 13:05:52 - mmengine - INFO - mmpretrain:  None
07/05 13:05:52 - mmengine - INFO - mmocr:       1.0.0
07/05 13:05:52 - mmengine - INFO - mmagic:      None
07/05 13:05:52 - mmengine - INFO - mmdet3d:     None
07/05 13:05:52 - mmengine - INFO - mmpose:      None
07/05 13:05:52 - mmengine - INFO - mmrotate:    None
07/05 13:05:52 - mmengine - INFO - mmaction:    None
07/05 13:05:52 - mmengine - INFO - mmrazor:     None
```

### Error traceback

```Shell
bbox_count=18
box[0]: 2
x: 755.00, y: 630.00, x: 782.00, y: 629.00, x: 784.00, y: 692.00, x: 757.00, y: 693.00,
box[1]: 0000000000000000000000000
x: 786.00, y: 687.00, x: 786.00, y: 625.00, x: 817.00, y: 625.00, x: 817.00, y: 687.00,
box[2]: 0000000000000000000000000
x: 816.00, y: 624.00, x: 847.00, y: 622.00, x: 850.00, y: 685.00, x: 820.00, y: 687.00,
box[3]: 0000000000000000000000000
x: 846.00, y: 626.00, x: 873.00, y: 624.00, x: 879.00, y: 686.00, x: 852.00, y: 688.00,
box[4]: 0000000000000000000000000
x: 876.00, y: 626.00, x: 905.00, y: 624.00, x: 908.00, y: 685.00, x: 880.00, y: 687.00,
box[5]: 0000000000000000000000000
x: 913.00, y: 689.00, x: 913.00, y: 629.00, x: 940.00, y: 629.00, x: 940.00, y: 689.00,
box[6]: 0000000000000000000000000
x: 720.00, y: 634.00, x: 752.00, y: 633.00, x: 754.00, y: 696.00, x: 723.00, y: 697.00,
box[7]: 0000000000000000000000000
x: 687.00, y: 641.00, x: 718.00, y: 639.00, x: 721.00, y: 704.00, x: 691.00, y: 706.00,
box[8]: 0000000000000000000000000
x: 854.00, y: 698.00, x: 882.00, y: 697.00, x: 886.00, y: 757.00, x: 858.00, y: 759.00,
box[9]: 0000000000000000000000000
x: 825.00, y: 698.00, x: 853.00, y: 697.00, x: 855.00, y: 759.00, x: 827.00, y: 760.00,
```

**Comment by irexyc** [comment]
Please use MMDeploy 1.2.0, there is a fix for satrn export after 1.1.0

<img width="944" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/16019484/d2d229b7-2876-45f3-8851-c6e92838ea6b">

**Comment by leemayi** [comment]
Version 1.2 does work.
But I'm a little confused.  10 batches take 250ms but 1 batch takes 30ms. Can I reduce the time of 10batch to the time frame of 1batch?
model is: satrn tensorrt

**Comment by irexyc** [comment]
I'm afraid you can't. You can use trtexec to test the pure inference time(without pre/post processing). We can't reduce time less than that.

To test time using of each module in pipeline(inference, pre/post processing) in c++, you can refer to [this doc](https://mmdeploy.readthedocs.io/en/latest/sdk_usage/profiler.html)
