### ISSUE TITLE
Compile the SDK in Windows CUDA，the spdlog-1.9.2 ought to configure Release，the Debug version is compiled as a result（spdlogd.lib），Cause this compilation error，Ask for your help

### ISSUE THREAD

**Issue by 1wang11lijian1** [open-mmlab/mmdeploy#225]
(base) PS C:\Users\Administrator\MMDeploy\build> conda activate mmd
(mmd) PS C:\Users\Administrator\MMDeploy\build> cd C:\Windows\spdlog-1.9.2
(mmd) PS C:\Windows\spdlog-1.9.2> cd build
(mmd) PS C:\Windows\spdlog-1.9.2\build> cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- The CXX compiler identification is MSVC 19.29.30140.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.9.2
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE
-- Build type: Release
-- Generating example(s)
-- Generating install
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Windows/spdlog-1.9.2/build
(mmd) PS C:\Windows\spdlog-1.9.2\build> **cmake --build . --target install -j --config Release**
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Building Custom Rule C:/Windows/spdlog-1.9.2/CMakeLists.txt
  spdlog.cpp
  stdout_sinks.cpp
  color_sinks.cpp
  file_sinks.cpp
  async.cpp
  cfg.cpp
  fmt.cpp
  正在生成代码...
  spdlog.vcxproj -> C:\Windows\spdlog-1.9.2\build\Debug\spdlogd.lib
  Building Custom Rule C:/Windows/spdlog-1.9.2/example/CMakeLists.txt
  example.cpp
  example.vcxproj -> C:\Windows\spdlog-1.9.2\build\example\Debug\example.exe
  Building Custom Rule C:/Windows/spdlog-1.9.2/CMakeLists.txt
  -- **Install configuration: "Debug"**
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/async.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/async_logger-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/async_logger.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/cfg
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/cfg/argv.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/cfg/env.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/cfg/helpers-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/cfg/helpers.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/common-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/common.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/backtracer-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/backtracer.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/circular_q.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/console_globals.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/file_helper-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/file_helper.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/fmt_helper.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/log_msg-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/log_msg.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/log_msg_buffer-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/log_msg_buffer.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/mpmc_blocking_q.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/null_mutex.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/os-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/os.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/periodic_worker-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/periodic_worker.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/registry-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/registry.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/synchronous_factory.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/tcp_client-windows.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/tcp_client.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/thread_pool-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/thread_pool.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/details/windows_include.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bin_to_hex.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/chrono.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/compile.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/fmt.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/ostr.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/xchar.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/formatter.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fwd.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/logger-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/logger.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/pattern_formatter-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/pattern_formatter.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/android_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/ansicolor_sink-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/ansicolor_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/base_sink-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/base_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/basic_file_sink-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/basic_file_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/daily_file_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/dist_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/dup_filter_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/hourly_file_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/mongo_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/msvc_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/null_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/ostream_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/qt_sinks.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/ringbuffer_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/rotating_file_sink-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/rotating_file_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/sink-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/stdout_color_sinks-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/stdout_color_sinks.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/stdout_sinks-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/stdout_sinks.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/syslog_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/systemd_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/tcp_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/wincolor_sink-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/wincolor_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/sinks/win_eventlog_sink.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/spdlog-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/spdlog.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/stopwatch.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/tweakme.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/version.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/lib/spdlogd.lib
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled/
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//args.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//chrono.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//color.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//compile.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//core.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//format-inl.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//format.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//locale.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//os.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//ostream.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//printf.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//ranges.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/include/spdlog/fmt/bundled//xchar.h
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/lib/pkgconfig/spdlog.pc
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/lib/cmake/spdlog/spdlogConfigTargets.cmake
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/lib/cmake/spdlog/spdlogConfigTargets-debug.cmake
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/lib/cmake/spdlog/spdlogConfig.cmake
  -- Installing: C:/Windows/spdlog-1.9.2/build/install/lib/cmake/spdlog/spdlogConfigVersion.cmake
(mmd) PS C:\Windows\spdlog-1.9.2\build> cd C:\Users\Administrator\MMDeploy\build
(mmd) PS C:\Users\Administrator\MMDeploy\build> cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 `
>>    -DMMDEPLOY_BUILD_SDK=ON `
>>    -DMMDEPLOY_TARGET_DEVICES="cuda" `
>>    -DMMDEPLOY_TARGET_BACKENDS="trt" `
>>    -DMMDEPLOY_CODEBASES="all" `
>>    -Dpplcv_DIR=C:/Users/Administrator/ppl.cv/pplcv-build/install/lib/cmake/ppl `
>>    -DTENSORRT_DIR=C:/Windows/TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2/TensorRT-8.2.3.0 `
>>    -DCUDNN_DIR=C:/Windows/cudnn-11.3-windows-x64-v8.2.1.32/cuda `
>>    -Dspdlog_DIR=C:/Windows/spdlog-1.9.2/build/install/lib/cmake/spdlog `
>>    -DOpenCV_DIR=C:/Windows/opencv/build
-- CMAKE_INSTALL_PREFIX: C:/Users/Administrator/MMDeploy/build/install
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- Build TensorRT custom ops.
-- Found TensorRT headers at C:/Windows/TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2/TensorRT-8.2.3.0/include
-- Found TensorRT libs at C:/Windows/TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2/TensorRT-8.2.3.0/lib/nvinfer.lib;C:/Windows/TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2/TensorRT-8.2.3.0/lib/nvinfer_plugin.lib
-- spdlog is found
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 4.5.5 in C:/Windows/opencv/build/x64/vc15/lib
-- You might need to add C:\Windows\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 4.5.5 in C:/Windows/opencv/build/x64/vc15/lib
-- You might need to add C:\Windows\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- Found TensorRT headers at C:/Windows/TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2/TensorRT-8.2.3.0/include
-- Found TensorRT libs at C:/Windows/TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2/TensorRT-8.2.3.0/lib/nvinfer.lib;C:/Windows/TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2/TensorRT-8.2.3.0/lib/nvinfer_plugin.lib
-- build codebase: mmcls
-- build codebase: mmdet
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 4.5.5 in C:/Windows/opencv/build/x64/vc15/lib
-- You might need to add C:\Windows\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- build codebase: mmseg
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 4.5.5 in C:/Windows/opencv/build/x64/vc15/lib
-- You might need to add C:\Windows\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- build codebase: mmocr
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 4.5.5 in C:/Windows/opencv/build/x64/vc15/lib
-- You might need to add C:\Windows\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- build codebase: mmedit
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 4.5.5 in C:/Windows/opencv/build/x64/vc15/lib
-- You might need to add C:\Windows\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- Configuring done
CMake Warning (dev) in csrc/net/trt/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "mmdeploy_trt_net".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in csrc/net/trt/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "mmdeploy_trt_net".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in csrc/net/trt/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "mmdeploy_trt_net".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in csrc/net/trt/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "mmdeploy_trt_net".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: C:/Users/Administrator/MMDeploy/build
(mmd) PS C:\Users\Administrator\MMDeploy\build> **cmake --build . --config Release -- /maxcpucount:4**
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

**spdlogd.lib**(fmt.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(device_impl.obj 中) [C:\Users\Adminis
trator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(fmt.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(device_impl.
obj 中) [C:\Users\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(spdlog.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(device_impl.obj 中) [C:\Users\Admi
nistrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(spdlog.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(device_im
pl.obj 中) [C:\Users\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(cfg.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(device_impl.obj 中) [C:\Users\Adminis
trator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(cfg.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(device_impl.
obj 中) [C:\Users\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(stdout_sinks.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(device_impl.obj 中) [C:\User
s\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(stdout_sinks.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(dev
ice_impl.obj 中) [C:\Users\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(async.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(device_impl.obj 中) [C:\Users\Admin
istrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(async.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(device_imp
l.obj 中) [C:\Users\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(color_sinks.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“2”不匹配值“0”(device_impl.obj 中) [C:\Users
\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(color_sinks.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MDd_DynamicDebug”不匹配值“MD_DynamicRelease”(devi
ce_impl.obj 中) [C:\Users\Administrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
    正在创建库 C:/Users/Administrator/MMDeploy/build/lib/Release/mmdeploy_core.lib 和对象 C:/Users/Administrator/MMDeploy/build
  /lib/Release/mmdeploy_core.exp
LINK : warning LNK4098: 默认库“MSVCRTD”与其他库的使用冲突；请使用 /NODEFAULTLIB:library [C:\Users\Administrator\MMDeploy\build\csrc\cor
e\mmdeploy_core.vcxproj]
spdlogd.lib(async.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter [C:\Users\Administrator\MMDeploy\build\csrc\
core\mmdeploy_core.vcxproj]
spdlogd.lib(color_sinks.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter [C:\Users\Administrator\MMDeploy\build
\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(fmt.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter [C:\Users\Administrator\MMDeploy\build\csrc\co
re\mmdeploy_core.vcxproj]
spdlogd.lib(spdlog.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter [C:\Users\Administrator\MMDeploy\build\csrc
\core\mmdeploy_core.vcxproj]
spdlogd.lib(cfg.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter [C:\Users\Administrator\MMDeploy\build\csrc\co
re\mmdeploy_core.vcxproj]
spdlogd.lib(stdout_sinks.obj) : error LNK2001: 无法解析的外部符号 __imp__invalid_parameter [C:\Users\Administrator\MMDeploy\buil
d\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(fmt.obj) : error LNK2019: 无法解析的外部符号 __imp__calloc_dbg，函数 "char * __cdecl std::_Maklocstr<char>(char const *
,char *,struct _Cvtvec const &)" (??$_Maklocstr@D@std@@YAPEADPEBDPEADAEBU_Cvtvec@@@Z) 中引用了该符号 [C:\Users\Administrator\M
MDeploy\build\csrc\core\mmdeploy_core.vcxproj]
spdlogd.lib(async.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport [C:\Users\Administrator\MMDeploy\build\csrc\core\
mmdeploy_core.vcxproj]
spdlogd.lib(color_sinks.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport [C:\Users\Administrator\MMDeploy\build\csrc
\core\mmdeploy_core.vcxproj]
spdlogd.lib(fmt.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport [C:\Users\Administrator\MMDeploy\build\csrc\core\mm
deploy_core.vcxproj]
spdlogd.lib(spdlog.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport [C:\Users\Administrator\MMDeploy\build\csrc\core
\mmdeploy_core.vcxproj]
spdlogd.lib(cfg.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport [C:\Users\Administrator\MMDeploy\build\csrc\core\mm
deploy_core.vcxproj]
spdlogd.lib(stdout_sinks.obj) : error LNK2001: 无法解析的外部符号 __imp__CrtDbgReport [C:\Users\Administrator\MMDeploy\build\csr
c\core\mmdeploy_core.vcxproj]
C:\Users\Administrator\MMDeploy\build\bin\Release\mmdeploy_core.dll : fatal error LNK1120: 3 个无法解析的外部命令 [C:\Users\Admin
istrator\MMDeploy\build\csrc\core\mmdeploy_core.vcxproj]
  mmdeploy_tensorrt_ops_obj.vcxproj -> C:\Users\Administrator\MMDeploy\build\csrc\backend_ops\tensorrt\mmdeploy_tensorr
  t_ops_obj.dir\Release\mmdeploy_tensorrt_ops_obj.lib
  mmdeploy_tensorrt_ops.vcxproj -> C:\Users\Administrator\MMDeploy\build\bin\Release\mmdeploy_tensorrt_ops.dll
(mmd) PS C:\Users\Administrator\MMDeploy\build>

**Comment by lvhan028** [comment]
Could you please change the title in English?

**Comment by 1wang11lijian1** [comment]
> Could you please change the title in English?
OK

**Comment by lvhan028** [comment]
Have you tried to remove all the files under `build` and do `cmake ..` again?

**Comment by 1wang11lijian1** [comment]
> Have you tried to remove all the files under `build` and do `cmake ..` again?

Yes, I tried deleting the build folder and recompiling, but the result was still Debug. I also tried reinstalling VS2019, but the result was still not good

**Comment by 1wang11lijian1** [comment]
I would like to ask if this problem is related to environment variable configuration, but I do not understand the relationship, just a possible suggestion.  I wonder why it didn't execute according to the command RELEASE I gave, but gave the result of Debug.

**Comment by lvhan028** [comment]
We haven't figured out the root cause yet. Perhaps I can provide a binary spdlog to you

**Comment by 1wang11lijian1** [comment]
> We haven't figured out the root cause yet. Perhaps I can provide a binary spdlog to you
OK，Whatever solves this problem, I'll try the binary spdlog.

**Comment by 1wang11lijian1** [comment]
> We haven't figured out the root cause yet. Perhaps I can provide a binary spdlog to you

OK ,Whatever solves this problem, I'll try the binary spdlog.   Thank you for your help.

**Comment by lvhan028** [comment]
[spdlog-1.9.2-lib.zip](https://github.com/open-mmlab/mmdeploy/files/8231627/spdlog-1.9.2-lib.zip)
