### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by yzh3124** [open-mmlab/mmdeploy#2250]
### 📚 The doc issue

Using the.pth model trained in the linux system with mmcv = 1.3.6, mmsegmentation = 0.19.0, how to realize the pth model to onnx model in the windows system with mmcv = 2.0.0, mmsegmentation = 1.0, mmdeploy = 1.0.0, and realize the deployment of the model.

**Comment by irexyc** [comment]
Can you load your model with mmsegmentation 1.x ? If so, you can use mmdeploy 1.x to convert the model. 

There is a document you can refer to: https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/02-how-to-run/convert_model.md
