### ISSUE TITLE
successfully generate onnx file of mmpose, but it can't work on mult-person image

### ISSUE THREAD

**Issue by SunWeimiao** [open-mmlab/mmdeploy#2252]
### 📚 The doc issue

I trained a custom model by mmpose.
 And I successfully generate onnx file, but it can only work on single-person image, cannot work on mult-person image.
When inference mult-person image, the running results of the model will be very poor and it seems that only one person can be identified.
I generate the onnx file by following script:
```
python mmdeploy/tools/deploy.py \
mmdeploy/configs/mmpose/pose-detection_hrnet-w48_8xb32-210e_384x288.py \
configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/hrnet-w48_8xb32-210e_coco33wholebody-384x288.py \
work_dirs/hrnet_w32_tiny_coco_256x192/best_PCK_epoch_15.pth\
mmdeploy/demo/resources/human-pose.jpg \
--work-dir mmdeploy_models/mmpose/hrnet_test_0 \
--device cpu \
--dump-info
```
The content of **pose-detection_hrnet-w48_8xb32-210e_384x288.py** is as follow:
```
_base_ = ['./pose-detection_static.py', '../_base_/backends/onnxruntime.py']

onnx_config = dict(input_shape=None)
```

I wonder which configurations need to be added or which documents need to be viewed  to achieve pose estimation for multi person images.

**Comment by irexyc** [comment]
The pose detector supply two [process apis](https://github.com/open-mmlab/mmdeploy/blob/main/csrc/mmdeploy/apis/c/mmdeploy/pose_detector.h#L53-L83). The first api takes only image as input (take full image as box), the second api takes image and boxes as input. What you want is the second api. If you pass n boxes, you will get n results.

To get the person boxes, you also need a detection model. There are two examples you can refer to:
https://github.com/open-mmlab/mmdeploy/blob/main/demo/csrc/cpp/det_pose.cxx
https://github.com/open-mmlab/mmdeploy/blob/main/demo/python/det_pose.py
