### ISSUE TITLE
[Docs] General SDK Questions

### ISSUE THREAD

**Issue by martin-cooper** [open-mmlab/mmdeploy#2257]
### 📚 The doc issue

I have deployed the ABINet and DBNet models to the tensorrt backend, however I have a couple questions about using the SDK:

Do we have to worry about thread safety when performing inference on loaded models? I know that Tensorrt expects different threads to have their own execution contexts, I was wondering if/how the SDK wrapped this functionality. For example, if we wanted to split up the text recognition workload across multiple workloads, could we do something like this in pseudocode:

```
thread.run(recognizer(images, bboxes[0:len/2]))
thread.run(recognizer(images, bboxes[len/2:]))
```

Or does each thread need its own recognizer? I just wanted a bit more context on how the mental model I should have of the execution pipeline.

Somewhat tangentially, for the MMOCR models, is there any utility to help postprocessing in merging the bounding boxes of detected text? For example in a picture like the following, is there a tool to create one large bounding box for all the text and combine all the words or is this something the user has to implement?

![image](https://github.com/open-mmlab/mmdeploy/assets/42585129/ac178013-fb24-499f-bc6b-645ca8328ef6)

Thank you all for your hard work!

**Comment by irexyc** [comment]
It's thread safe for loading models. But running the same model concurrently requires maintaining multiple instances of TensorRT ExecutionContext, which is not supported yet, so each thread need its own recognizer.

We don't have such function to merge boxes, you could ask in https://github.com/open-mmlab/mmocr to see if there are some methods to achieve this and implement that methods yourself.
