### ISSUE TITLE
[Bug] ValueError: Invalid target_platform 'rv1126'!

### ISSUE THREAD

**Issue by zhanghui-china** [open-mmlab/mmdeploy#2261]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

my board is Rock5a ,  RK3588

python tools/deploy.py \
    configs/mmpretrain/classification_rknn-int8_static-224x224.py \
    ~/mmpretrain/configs/resnet/resnet50_8xb32_in1k.py \
    /resnet50_batch256_imagenet_20200708-cfb998bf.pth \
    ~/mmpretrain/demo/demo.JPEG \
    --work-dir mmdeploy_models/mmpretrain/resnet50 \
    --device cpu \
    --dump-info

when i execute model convert from onnx to rknn:

(mmdeploy) zhanghui@zhanghui-ubuntu2204:~/MMDeploy$ sh ./rknn_resnet50.sh

ValueError: Invalid target_platform 'rv1126'!

### Reproduction

(mmdeploy) zhanghui@zhanghui-ubuntu2204:~/MMDeploy$ sh ./rknn_resnet50.sh
07/09 07:53:14 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/09 07:53:14 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "mmpretrain_tasks" registry tree. As a workaround, the current "mmpretrain_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/09 07:53:15 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
07/09 07:53:15 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
07/09 07:53:15 - mmengine - WARNING - Failed to search registry with scope "mmpretrain" in the "mmpretrain_tasks" registry tree. As a workaround, the current "mmpretrain_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpretrain" is a correct scope, or whether the registry is initialized.
Loads checkpoint by local backend from path: ./resnet50_batch256_imagenet_20200708-cfb998bf.pth
07/09 07:53:15 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
07/09 07:53:15 - mmengine - INFO - Export PyTorch model to ONNX: mmdeploy_models/mmpretrain/resnet50/end2end.onnx.
07/09 07:53:15 - mmengine - WARNING - Can not find torch._C._jit_pass_onnx_autograd_function_process, function rewrite will not be applied
07/09 07:53:18 - mmengine - INFO - Execute onnx optimize passes.
07/09 07:53:18 - mmengine - INFO - Finish pipeline mmdeploy.apis.pytorch2onnx.torch2onnx
07/09 07:53:19 - mmengine - INFO - Start pipeline mmdeploy.apis.utils.utils.to_backend in main process
07/09 07:53:19 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
W __init__: rknn-toolkit2 version: 1.5.0+1fa95b5c
E config: Invalid target_platform 'rv1126'!
W config: ===================== WARN(1) =====================
E rknn-toolkit2 version: 1.5.0+1fa95b5c
Traceback (most recent call last):
  File "tools/deploy.py", line 335, in <module>
    main()
  File "tools/deploy.py", line 259, in main
    backend_files = to_backend(
  File "/home/zhanghui/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/home/zhanghui/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/home/zhanghui/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/home/zhanghui/MMDeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/zhanghui/MMDeploy/mmdeploy/apis/utils/utils.py", line 98, in to_backend
    return backend_mgr.to_backend(
  File "/home/zhanghui/MMDeploy/mmdeploy/backend/rknn/backend_manager.py", line 147, in to_backend
    onnx2rknn(onnx_path, output_path, deploy_cfg)
  File "/home/zhanghui/MMDeploy/mmdeploy/backend/rknn/onnx2rknn.py", line 72, in onnx2rknn
    rknn.config(**common_params)
  File "/home/zhanghui/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/rknn/api/rknn.py", line 118, in config
    return self.rknn_base.config(args)
  File "rknn/api/rknn_base.py", line 890, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 112, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!

### Environment

```Shell
Ubuntu 22.04 LTS X86
gcc 11.3.0
conda python 3.8
MMDEPLOY_DIR=~/MMDeploy
ONNXRUNTIME_DIR=onnxruntime-linux-x64-1.8.1
LD_LIBRARY_PATH=$ONNXRUNTIME_DIR/lib:$LD_LIBRARY_PATH
pytorch 1.8.1
mmcv>=2.0.0rc2
rknn_toolkit2-1.5.0+1fa95b5c-cp38-cp38-linux_x86_64.whl
```

**Comment by zhanghui-china** [comment]
How can i change target platform from rv1126 to rk3588?

**Comment by AllentDan** [comment]
Change the [config line](https://github.com/open-mmlab/mmdeploy/blob/0a8cbe2286dcb226f3140d0bae8700cdfaf37a47/configs/_base_/backends/rknn.py#L4) please.
