### ISSUE TITLE
[Docs] Where can I access class names in the trained model with mmdet 3.x and mmdeploy 1.x?

### ISSUE THREAD

**Issue by fujikosu** [open-mmlab/mmdeploy#2263]
### 📚 The doc issue

I'm loading a trained model like this below.

```py
task_processor = build_task_processor(model_config, deploy_config, "cuda")
model = task_processor.build_pytorch_model(model_path)
```

And then I want to access class id->class names mapping

in mmdet2.x + mmdeploy 0.x, I could access model names like below

```py
model.CLASSES
```

But this property is gone in mmdet 3.x and mmdeploy 0.x that I can't find a way to access class names a model was trained with. Thus I can't reporduce id->classes mapping anymore.

Where was this class list information moved to in mmdeploy 1.x?

Envs
```sh
openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.2.0
mim install mmdet==3.1.0
```

Thanks!

**Comment by RunningLeon** [comment]
@fujikosu hi, you could get it through `_get_dataset_metainfo` in here
https://github.com/open-mmlab/mmdeploy/blob/0a8cbe2286dcb226f3140d0bae8700cdfaf37a47/mmdeploy/codebase/mmdet/deploy/object_detection.py#L84

**Comment by fujikosu** [comment]
@RunningLeon  Thank you! I ran it like this below and I could access to class information. I didn't see class information defined in model config file itself but when I pass that model config to `_get_dataset_metainfo`, I could retrieve model class names. So I'm not sure where the actual information is coming from. Is it expected? 

```py
deploy_config, model_config = load_config(
        deploy_config_path, model_config_path
)
_get_dataset_metainfo(model_config)["classes"]
```

One more question. I'm currently using pretrained model. Can a fine-tuned model give us new class list in this way too?

**Comment by RunningLeon** [comment]
hi, it parses from dataset classes like https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/mmdet/datasets/coco.py#L17
