### ISSUE TITLE
[Bug] pointpillar test failed

### ISSUE THREAD

**Issue by JunLFang** [open-mmlab/mmdeploy#2268]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

It raised error in file mmdeploy/mmdeploy/codebase/base/task.py
dataset = DATASETS.build(dataset_cfg)

Exception has occurred: ValueError
class `NuScenesDataset` in mmdet3d/datasets/nuscenes_dataset.py: Annotation must have data_list and metainfo keys
ValueError: Annotation must have data_list and metainfo keys

During handling of the above exception, another exception occurred:

  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/task.py", line 157, in build_dataset
    dataset = DATASETS.build(dataset_cfg)
  File "/root/workspace/mmdeploy/tools/test.py", line 120, in main
    dataset = task_processor.build_dataset(test_dataloader['dataset'])
  File "/root/workspace/mmdeploy/tools/test.py", line 159, in <module>
    main()
ValueError: class `NuScenesDataset` in mmdet3d/datasets/nuscenes_dataset.py: Annotation must have data_list and metainfo keys

### Reproduction

export DEPLOY_CFG=configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-nus-64x4.py
export MODEL_CFG=/mmdeploy_ori/mmdetection3d/configs/pointpillars/pointpillars_hv_fpn_sbn-all_8xb4-2x_nus-3d.py

export TENSORRT_DIR=/workspace/tensorrt/
export LD_LIBRARY_PATH=$TENSORRT_DIR/lib:/usr/local/cuda/lib64

python tools/test.py $DEPLOY_CFG $MODEL_CFG --model ./pointpillar_trt/end2end.engine --device cuda --show

### Environment

```Shell
07/11 02:12:47 - mmengine - INFO - **********Environmental information**********
07/11 02:12:47 - mmengine - INFO - sys.platform: linux
07/11 02:12:47 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
07/11 02:12:47 - mmengine - INFO - CUDA available: True
07/11 02:12:47 - mmengine - INFO - numpy_random_seed: 2147483648
07/11 02:12:47 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3090
07/11 02:12:47 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
07/11 02:12:47 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
07/11 02:12:47 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
07/11 02:12:47 - mmengine - INFO - PyTorch: 1.10.0
07/11 02:12:47 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

07/11 02:12:47 - mmengine - INFO - TorchVision: 0.11.0
07/11 02:12:47 - mmengine - INFO - OpenCV: 4.7.0
07/11 02:12:47 - mmengine - INFO - MMEngine: 0.1.0
07/11 02:12:47 - mmengine - INFO - MMCV: 2.0.0rc1
07/11 02:12:47 - mmengine - INFO - MMCV Compiler: GCC 9.3
07/11 02:12:47 - mmengine - INFO - MMCV CUDA Compiler: 11.3
07/11 02:12:47 - mmengine - INFO - MMDeploy: 1.0.0+3b62b21
07/11 02:12:47 - mmengine - INFO - 

07/11 02:12:47 - mmengine - INFO - **********Backend information**********
07/11 02:12:47 - mmengine - INFO - tensorrt:	8.2.4.2
07/11 02:12:47 - mmengine - INFO - tensorrt custom ops:	Available
07/11 02:12:47 - mmengine - INFO - ONNXRuntime:	1.15.0
07/11 02:12:47 - mmengine - INFO - ONNXRuntime-gpu:	1.8.1
07/11 02:12:47 - mmengine - INFO - ONNXRuntime custom ops:	Available
07/11 02:12:47 - mmengine - INFO - pplnn:	None
07/11 02:12:47 - mmengine - INFO - ncnn:	None
07/11 02:12:47 - mmengine - INFO - snpe:	None
07/11 02:12:47 - mmengine - INFO - openvino:	None
07/11 02:12:47 - mmengine - INFO - torchscript:	1.10.0
07/11 02:12:47 - mmengine - INFO - torchscript custom ops:	NotAvailable
07/11 02:12:47 - mmengine - INFO - rknn-toolkit:	None
07/11 02:12:47 - mmengine - INFO - rknn-toolkit2:	None
07/11 02:12:47 - mmengine - INFO - ascend:	None
07/11 02:12:47 - mmengine - INFO - coreml:	None
07/11 02:12:47 - mmengine - INFO - tvm:	None
07/11 02:12:47 - mmengine - INFO - vacc:	None
07/11 02:12:47 - mmengine - INFO - 

07/11 02:12:47 - mmengine - INFO - **********Codebase information**********
07/11 02:12:47 - mmengine - INFO - mmdet:	3.0.0rc1
07/11 02:12:47 - mmengine - INFO - mmseg:	1.0.0rc0
07/11 02:12:47 - mmengine - INFO - mmpretrain:	None
07/11 02:12:47 - mmengine - INFO - mmocr:	None
07/11 02:12:47 - mmengine - INFO - mmedit:	None
07/11 02:12:47 - mmengine - INFO - mmdet3d:	1.1.0rc1
07/11 02:12:47 - mmengine - INFO - mmpose:	None
07/11 02:12:47 - mmengine - INFO - mmrotate:	None
07/11 02:12:47 - mmengine - INFO - mmaction:	None
07/11 02:12:47 - mmengine - INFO - mmrazor:	None
```

### Error traceback

```Shell
Exception has occurred: ValueError
class `NuScenesDataset` in mmdet3d/datasets/nuscenes_dataset.py: Annotation must have data_list and metainfo keys
ValueError: Annotation must have data_list and metainfo keys

During handling of the above exception, another exception occurred:

  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/task.py", line 157, in build_dataset
    dataset = DATASETS.build(dataset_cfg)
  File "/root/workspace/mmdeploy/tools/test.py", line 120, in main
    dataset = task_processor.build_dataset(test_dataloader['dataset'])
  File "/root/workspace/mmdeploy/tools/test.py", line 159, in <module>
    main()
ValueError: class `NuScenesDataset` in mmdet3d/datasets/nuscenes_dataset.py: Annotation must have data_list and metainfo keys
```

**Comment by JunLFang** [comment]
I doubt that it maybe casued by mmegine version, but when I upgrade mmengine into 0.7.4 , teh error come out 
 Traceback (most recent call last):
  File "tools/test.py", line 159, in <module>
    main()
  File "tools/test.py", line 105, in main
    task_processor = build_task_processor(model_cfg, deploy_cfg, args.device)
  File "/root/workspace/mmdeploy/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/__init__.py", line 36, in import_codebase
    codebase = get_codebase_class(codebase_type)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 79, in get_codebase_class
    importlib.import_module(f'mmdeploy.codebase.{codebase.value}.deploy')
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/__init__.py", line 2, in <module>
    from .deploy import MMDetection3d, VoxelDetection
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/deploy/__init__.py", line 2, in <module>
    from .voxel_detection import MMDetection3d, VoxelDetection
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py", line 8, in <module>
    from mmdet3d.structures import get_box_type
  File "/mmdeploy_ori/mmdetection3d/mmdet3d/__init__.py", line 4, in <module>
    import mmdet
  File "/opt/conda/lib/python3.8/site-packages/mmdet/__init__.py", line 21, in <module>
    assert (mmengine_version >= digit_version(mmengine_minimum_version)
AssertionError: MMEngine==0.7.4 is used but incompatible. Please install mmengine>=0.0.0, <0.2.0.

**Comment by RunningLeon** [comment]
hi, could try update mmdet3d to `v1.2.0` by `pip install -U openmim && mim install mmdet3d==1.2.0`

**Comment by JunLFang** [comment]
> hi, could try update mmdet3d to `v1.2.0` by `pip install -U openmim && mim install mmdet3d==1.2.0`. BTW, TensorRT should be >=8.4.1.5

Thank you for your comment , yes, I have update the tensorrt , and now I used the mmdet3d v1.1.1  and tensorrt: 8.5.3.1

**Comment by JunLFang** [comment]
This issue has been resolved , it cased by the evaluation nusence data set file is not correct, I convert it with mmdetection3d==v1.1.1, now the issue is resolved
