### ISSUE TITLE
[Bug] infer mmyolo yolox onnx model used by python infrence sdk failed with mmdeploy1.2.0

### ISSUE THREAD

**Issue by PancakeAwesome** [open-mmlab/mmdeploy#2274]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

code running until below:
python mmdeploy/demo/python/object_detection.py
loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-07-13 01:20:26.739] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/root/deploy/det/"
Segmentation fault

### Reproduction

from mmdeploy_runtime import Detector

detector = Detector(model_path='mmdeploy_models/coco/yolox_s.py', device_name='cuda', device_id=0)

errors:
loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-07-13 01:20:26.739] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/root/deploy/det/"
Segmentation fault

### Environment

```Shell
07/13 01:22:19 - mmengine - INFO - TorchVision: 0.15.2+cu117
07/13 01:22:19 - mmengine - INFO - OpenCV: 4.6.0
07/13 01:22:19 - mmengine - INFO - MMEngine: 0.8.1
07/13 01:22:19 - mmengine - INFO - MMCV: 2.0.1
07/13 01:22:19 - mmengine - INFO - MMCV Compiler: GCC 9.3
07/13 01:22:19 - mmengine - INFO - MMCV CUDA Compiler: 11.7
07/13 01:22:19 - mmengine - INFO - MMDeploy: 1.2.0+
07/13 01:22:19 - mmengine - INFO - 

07/13 01:22:19 - mmengine - INFO - **********Backend information**********
07/13 01:22:19 - mmengine - INFO - tensorrt:    None
07/13 01:22:19 - mmengine - INFO - ONNXRuntime: None
07/13 01:22:19 - mmengine - INFO - ONNXRuntime-gpu:     1.15.1
07/13 01:22:19 - mmengine - INFO - ONNXRuntime custom ops:      Available
07/13 01:22:19 - mmengine - INFO - pplnn:       None
07/13 01:22:19 - mmengine - INFO - ncnn:        None
07/13 01:22:19 - mmengine - INFO - snpe:        None
07/13 01:22:19 - mmengine - INFO - openvino:    None
07/13 01:22:19 - mmengine - INFO - torchscript: 2.0.1
07/13 01:22:19 - mmengine - INFO - torchscript custom ops:      NotAvailable
07/13 01:22:19 - mmengine - INFO - rknn-toolkit:        None
07/13 01:22:19 - mmengine - INFO - rknn-toolkit2:       None
07/13 01:22:19 - mmengine - INFO - ascend:      None
07/13 01:22:19 - mmengine - INFO - coreml:      None
07/13 01:22:19 - mmengine - INFO - tvm: None
07/13 01:22:19 - mmengine - INFO - vacc:        None
07/13 01:22:19 - mmengine - INFO - 

07/13 01:22:19 - mmengine - INFO - **********Codebase information**********
07/13 01:22:19 - mmengine - INFO - mmdet:       3.0.0
07/13 01:22:19 - mmengine - INFO - mmseg:       None
07/13 01:22:19 - mmengine - INFO - mmpretrain:  None
07/13 01:22:19 - mmengine - INFO - mmocr:       None
07/13 01:22:19 - mmengine - INFO - mmagic:      None
07/13 01:22:19 - mmengine - INFO - mmdet3d:     None
07/13 01:22:19 - mmengine - INFO - mmpose:      None
07/13 01:22:19 - mmengine - INFO - mmrotate:    None
07/13 01:22:19 - mmengine - INFO - mmaction:    None
07/13 01:22:19 - mmengine - INFO - mmrazor:     None
07/13 01:22:19 - mmengine - INFO - mmyolo:      0.5.0
```

**Comment by PancakeAwesome** [comment]
@RunningLeon @irexyc please help me and thank you very much

**Comment by PancakeAwesome** [comment]
and i use cpu infer process well like this:
from mmdeploy_runtime import Detector
detector = Detector(model_path='mmdeploy_models/coco/yolox_s.py', device_name='cuda', device_id=0)

loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-07-13 01:28:11.269] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/root/deploy/det/"
load model success
model result: bboxes: [[8.5859296e+02 5.5908411e+02 9.6924103e+02 6.5538458e+02 9.2067564e-01]
 [7.5709344e+02 5.3196289e+02 8.1455975e+02 5.7099774e+02 5.9835866e-02]
 [7.5274329e+02 5.3167188e+02 8.1357788e+02 6.1321948e+02 1.5869465e-03]
 [7.4765155e+02 4.9749841e+02 8.3047821e+02 5.6415839e+02 1.1477348e-03]
 [7.6034540e+02 5.3849530e+02 8.1604028e+02 5.8682361e+02 1.0199388e-03]], labels: [0 0 0 0 0]

**Comment by irexyc** [comment]
We use onnxruntime-1.8.1 to build mmdeploy and put `libonnxruntime.so.1.8.1` in python wheel pacakge. The python package will load `libonnxruntime_providers_cuda.so` if you use cuda device. Therefore if you have `/usr/ed/onnxruntime-linux-x64-gpu-1.15.1/lib` in your `$LD_LIBRARY_PATH`, you could try to downgrade your onnxruntime library version, the problem may be version dismatch.

**Comment by PancakeAwesome** [comment]
> We use onnxruntime-1.8.1 to build mmdeploy and put `libonnxruntime.so.1.8.1` in python wheel pacakge. The python package will load `libonnxruntime_providers_cuda.so` if you use cuda device. Therefore if you have `/usr/ed/onnxruntime-linux-x64-gpu-1.15.1/lib` in your `$LD_LIBRARY_PATH`, you could try to downgrade your onnxruntime library version, the problem may be version dismatch.

thank you for your help, with your resolvement,my problem fixed.
