### ISSUE TITLE
May I ask if mmdeploy supports the deployment of mmyolo

### ISSUE THREAD

**Issue by ainndejj11** [open-mmlab/mmdeploy#2284]
### Motivation

I want to train an RTMDet and YOLOv5 using MMYOLO. Can MMdeploy's C++demo support it

There is another question:

Should I choose mmdetection or use mmyolo for training rtmdet？？

**Comment by irexyc** [comment]
> I want to train an RTMDet and YOLOv5 using MMYOLO. Can MMdeploy's C++demo support it

The c++ demo can support yolov5 and rtmdet.

> Should I choose mmdetection or use mmyolo for training rtmdet？？

Either is OK. If you use mmdetection, you should use model configs in [mmdeply](https://github.com/open-mmlab/mmdeploy/tree/main/configs/mmdet/detection). if you use mmyolo, you should use model configs in [mmyolo](https://github.com/open-mmlab/mmyolo/tree/main/configs/deploy)

---

There are some useful docs you can refer to:

https://github.com/open-mmlab/mmyolo/blob/dc85144fab20a970341550794857a2f2f9b11564/docs/en/recommended_topics/deploy/mmdeploy_guide.md

https://github.com/open-mmlab/mmyolo/blob/dc85144fab20a970341550794857a2f2f9b11564/docs/en/recommended_topics/deploy/mmdeploy_yolov5.md?plain=1#L219
