### ISSUE TITLE
[Bug] Do mmdeploy support slide mode in mmseg

### ISSUE THREAD

**Issue by kkpssr** [open-mmlab/mmdeploy#2285]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

I finished model convert and meet error in img test like Input shape should be between (1, 3, 512, 1024) and (1, 3, 2048, 2048) but get (1, 3, 512, 872),model cfg i use is convnext-base_upernet_8xb2-amp-160k_ade20k-512x512.py and the infer mode is slide, infer shape is (512,512) with 361 stride ,so input shape should be 512x512 not 512x847 in inference, Convert cfg i use is segmentation_tensorrt-fp16_dynamic-512x1024-2048x2048.py.so how to use slide mode in mmdeploy.

### Reproduction

python mmdeploy/tools/deploy.py mmdeploy/configs/mmseg/segmentation_tensorrt-fp16_dynamic-512x1024-2048x2048.py configs/convnext/convnext-base_upernet_8xb2-amp-160k_ade20k-512x512.py iter_112000.pth  test.jpg --work-dir dmodel/ --device cuda --dump-info

### Environment

```Shell
mmcv 2.0
```

**Comment by RunningLeon** [comment]
hi, slide inference mode is not supported by mmdeploy.

**Comment by OutOfBounds42** [comment]
@RunningLeon Is there any way to get ConvNeXt to work with TensorRT via mmdeploy? Do I have to retrain the model with slide inference disabled?
The onnx export did work for me, just not the TensorRT export.

**Comment by RunningLeon** [comment]
> @RunningLeon Is there any way to get ConvNeXt to work with TensorRT via mmdeploy at this point in time? Is it sufficient to disable sliding inference (see [here](https://mmsegmentation.readthedocs.io/en/latest/advanced_guides/models.html#prediction-modes))? I'm asking because onnx export without TensorRT did work for me, even though ConvNeXt is not officially supported.
> 
> Edit: I'm getting the same error, even when I define test_cfg(mode='whole'), even if I define this before training my model.

@OutOfBounds42 hi, sorry for the late reply. You could try to use static shape config like https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmseg/segmentation_tensorrt-fp16_static-512x512.py

**Comment by kkpssr** [comment]
> hi, slide inference mode is not supported by mmdeploy.

hi, is there any plan to support slide model in future？and do i have any way to infer with fp16 percesion in mmseg.

**Comment by RunningLeon** [comment]
Hi, slide inference will not be supported.

**Comment by OutOfBounds42** [comment]
@RunningLeon https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmseg/segmentation_tensorrt_static-512x1024.py ended up working for me! Thank you for the pointer!
