### ISSUE TITLE
[Bug] Pointpillar test failed with mmdet3d error

### ISSUE THREAD

**Issue by JunLFang** [open-mmlab/mmdeploy#2287]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

/opt/conda/lib/python3.8/site-packages/mmdet3d/models/dense_heads/anchor3d_head.py:94: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
Traceback (most recent call last):
  File "tools/test.py", line 163, in <module>
    main()
  File "tools/test.py", line 154, in main
    runner.test()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1781, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 454, in run_iter
    outputs = self.runner.model.test_step(data_batch)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py", line 97, in forward
    prediction = VoxelDetectionModel.postprocess(
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py", line 241, in postprocess
    data_instances_3d = head.predict_by_feat(
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d/models/dense_heads/base_3d_dense_head.py", line 232, in predict_by_feat
    mlvl_priors = self.prior_generator.grid_anchors(
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d/models/task_modules/anchor/anchor_3d_generator.py", line 111, in grid_anchors
    **assert self.num_levels == len(featmap_sizes)**
AssertionError

### Reproduction

export DEPLOY_CFG=configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-nus-64x4.py
export MODEL_CFG=/mmdeploy_ori/mmdetection3d/configs/pointpillars/pointpillars_hv_fpn_sbn-all_8xb4-2x_nus-3d.py
python tools/test.py $DEPLOY_CFG $MODEL_CFG --model ./pointpillar_trt/end2end.engine --device cuda --show

### Environment

```Shell
07/17 09:43:47 - mmengine - INFO - 

07/17 09:43:47 - mmengine - INFO - **********Environmental information**********
07/17 09:43:47 - mmengine - INFO - sys.platform: linux
07/17 09:43:47 - mmengine - INFO - Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
07/17 09:43:47 - mmengine - INFO - CUDA available: True
07/17 09:43:47 - mmengine - INFO - numpy_random_seed: 2147483648
07/17 09:43:47 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3090
07/17 09:43:47 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
07/17 09:43:47 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
07/17 09:43:47 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
07/17 09:43:47 - mmengine - INFO - PyTorch: 1.12.1
07/17 09:43:47 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

07/17 09:43:47 - mmengine - INFO - TorchVision: 0.13.1
07/17 09:43:47 - mmengine - INFO - OpenCV: 4.7.0
07/17 09:43:47 - mmengine - INFO - MMEngine: 0.8.2
07/17 09:43:47 - mmengine - INFO - MMCV: 2.0.0rc4
07/17 09:43:47 - mmengine - INFO - MMCV Compiler: GCC 9.3
07/17 09:43:47 - mmengine - INFO - MMCV CUDA Compiler: 11.3
07/17 09:43:47 - mmengine - INFO - MMDeploy: 1.0.0+3b62b21
07/17 09:43:47 - mmengine - INFO - 

07/17 09:43:47 - mmengine - INFO - **********Backend information**********
07/17 09:43:47 - mmengine - INFO - tensorrt:    8.5.3.1
07/17 09:43:47 - mmengine - INFO - tensorrt custom ops: Available
07/17 09:43:47 - mmengine - INFO - ONNXRuntime: 1.15.0
07/17 09:43:47 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
07/17 09:43:47 - mmengine - INFO - ONNXRuntime custom ops:      Available
07/17 09:43:47 - mmengine - INFO - pplnn:       None
07/17 09:43:47 - mmengine - INFO - ncnn:        None
07/17 09:43:47 - mmengine - INFO - snpe:        None
07/17 09:43:47 - mmengine - INFO - openvino:    None
07/17 09:43:47 - mmengine - INFO - torchscript: 1.11.0
07/17 09:43:47 - mmengine - INFO - torchscript custom ops:      NotAvailable
07/17 09:43:47 - mmengine - INFO - rknn-toolkit:        None
07/17 09:43:47 - mmengine - INFO - rknn-toolkit2:       None
07/17 09:43:47 - mmengine - INFO - ascend:      None
07/17 09:43:47 - mmengine - INFO - coreml:      None
07/17 09:43:47 - mmengine - INFO - tvm: None
07/17 09:43:47 - mmengine - INFO - vacc:        None
07/17 09:43:47 - mmengine - INFO - 

07/17 09:43:47 - mmengine - INFO - **********Codebase information**********
07/17 09:43:48 - mmengine - INFO - mmdet:       3.0.0
07/17 09:43:48 - mmengine - INFO - mmseg:       1.0.0rc0
07/17 09:43:48 - mmengine - INFO - mmpretrain:  None
07/17 09:43:48 - mmengine - INFO - mmocr:       None
07/17 09:43:48 - mmengine - INFO - mmedit:      None
07/17 09:43:48 - mmengine - INFO - mmdet3d:     1.1.1
07/17 09:43:48 - mmengine - INFO - mmpose:      None
07/17 09:43:48 - mmengine - INFO - mmrotate:    None
07/17 09:43:48 - mmengine - INFO - mmaction:    None
07/17 09:43:48 - mmengine - INFO - mmrazor:     None
```

**Comment by RunningLeon** [comment]
@JunLFang hi, the same issue as #2200 and is fixed in https://github.com/open-mmlab/mmdeploy/pull/2210. You could upgrade mmdeploy or modify the source code of mmdeploy in your local machine.

**Comment by JunLFang** [comment]
> @JunLFang hi, the same issue as #2200 and is fixed in #2210. You could upgrade mmdeploy or modify the source code of mmdeploy in your local machine.

Thank you for your feedback, I modified the code based on this [comment ](https://github.com/open-mmlab/mmdeploy/issues/2200#issuecomment-1598331721), but new error happened . 
```
rporated into box coder in the future
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "single_infer.py", line 21, in <module>
    result = model.test_step(model_inputs)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py", line 102, in forward
    prediction = VoxelDetectionModel.postprocess(
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py", line 246, in postprocess
    data_instances_3d = head.predict_by_feat(
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d/models/dense_heads/base_3d_dense_head.py", line 247, in predict_by_feat
    results = self._predict_by_feat_single(
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d/models/dense_heads/base_3d_dense_head.py", line 306, in _predict_by_feat_single
    assert len(cls_score_list) == len(bbox_pred_list) == len(mlvl_priors)
AssertionError
```

Anyway , I will try the new mmdeploy version , and try to avoid this bug

**Comment by RunningLeon** [comment]
hi, could you try official model config and checkpoint like these two?
https://github.com/open-mmlab/mmdeploy/blob/0a8cbe2286dcb226f3140d0bae8700cdfaf37a47/tests/regression/mmdet3d.yml#L83-L87

**Comment by JunLFang** [comment]
> hi, could you try official model config and checkpoint like these two?
> 
> https://github.com/open-mmlab/mmdeploy/blob/0a8cbe2286dcb226f3140d0bae8700cdfaf37a47/tests/regression/mmdet3d.yml#L83-L87

Thank you for your feedback , but our target is nuscence , anyway , I will have a try

**Comment by JunLFang** [comment]
Dear， I just made a dockerfile like below
`FROM openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy

# install TRT 8.4.1.5
COPY ./TensorRT-8.4.1.5.Linux.x86_64-gnu.cuda-11.6.cudnn8.4.tar.gz /root/workspace
RUN tar -xvf TensorRT-8.4.1.5.Linux.x86_64-gnu.cuda-11.6.cudnn8.4.tar.gz
RUN pip install TensorRT-8.4.1.5/python/tensorrt-8.4.1.5-cp38-none-linux_x86_64.whl
ENV TENSORRT_DIR=/root/workspace/TensorRT-8.4.1.5
ENV LD_LIBRARY_PATH=/root/workspace/TensorRT-8.4.1.5/lib:$LD_LIBRARY_PATH

# install mmdet3d + configs
RUN git clone https://github.com/open-mmlab/mmdetection3d.git -b v1.2.0 /root/workspace/mmdetection3d
RUN mim install "mmdet3d==1.2.0"

# Fix Error:
# mmengine 0.7.4 is not comppatible with mmdeploy 1.2.0/ mmdet3d 1.2.0
RUN mim install "mmengine==0.8.0"
`
the env is ok for me to infer pointpillar
But it seems the result got a big difference between with mmdet3d torch version
MMdetect3d v1.2.0 reference nuscence mini dataset result
`Evaluating bboxes of pred_instances_3d
mAP: 0.4967
mATE: 0.4602
mASE: 0.3413
mAOE: 0.3994
mAVE: 0.4056
mAAE: 0.3779
NDS: 0.5499
Eval time: 2.8s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.823   0.210   0.152   0.177   0.203   0.134
truck   0.468   0.461   0.215   0.105   0.136   0.528
bus     0.658   0.499   0.181   0.147   0.941   0.148
trailer 0.742   0.683   0.277   0.037   0.008   1.000
construction_vehicle    0.000   1.000   1.000   1.000   1.000   1.000
pedestrian      0.841   0.134   0.265   0.218   0.264   0.066
motorcycle      0.320   0.292   0.337   1.553   0.129   0.140
bicycle 0.366   0.255   0.242   0.324   0.564   0.006
traffic_cone    0.004   0.481   0.456   nan     nan     nan
barrier 0.745   0.587   0.288   0.034   nan     nan
`


mmdepoy with tensorrt engine infer result：
`
Evaluating bboxes of pred_instances_3d
mAP: 0.2138
mATE: 0.8053
mASE: 0.6936
mAOE: 0.6247
mAVE: 0.6739
mAAE: 0.7247
NDS: 0.2547
Eval time: 0.8s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.336   0.400   0.227   0.329   0.305   0.072
truck   0.401   0.476   0.251   0.111   0.142   0.579
bus     0.659   0.495   0.181   0.146   0.937   0.147
trailer 0.742   0.682   0.277   0.037   0.008   1.000
construction_vehicle    0.000   1.000   1.000   1.000   1.000   1.000
pedestrian      0.000   1.000   1.000   1.000   1.000   1.000
motorcycle      0.000   1.000   1.000   1.000   1.000   1.000
bicycle 0.000   1.000   1.000   1.000   1.000   1.000
traffic_cone    0.000   1.000   1.000   nan     nan     nan
barrier 0.000   1.000   1.000   1.000   nan     nan
`

Have you ever compared the result between them ？
Thank you very much

**Comment by RunningLeon** [comment]
hi, actually, we have not used `tools/test.py` to compare the evaluation results. Simply check the visualized 3d result. Maybe there's something wrong. We'll try to evaluate the converted tensorrt engine and come back to you later.

**Comment by JunLFang** [comment]
> hi, actually, we have not used `tools/test.py` to compare the evaluation results. Simply check the visualized 3d result. Maybe there's something wrong. We'll try to evaluate the converted tensorrt engine and come back to you later.

Dear , have you got some progress about it? Thank you very much.

**Comment by RunningLeon** [comment]
hi, have not started, but it is in the to-do-list.
