### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Wooho-Moon** [open-mmlab/mmdeploy#2291]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When I convert satrn model to tensorrt, the process success. but the result is different compared to onnx result. I don't know why. What should I do? Any ideas?

The result is following. Onnx result is correct, but tesorrt result is wrong... :(

![output_tensorrt](https://github.com/open-mmlab/mmdeploy/assets/98577354/538ad9f2-6617-49cc-b122-606e7f993c4e)
![output_pytorch](https://github.com/open-mmlab/mmdeploy/assets/98577354/442eb2ec-8b43-4813-a013-fda367fe9efe)

### Reproduction

python ./tools/deploy.py  \
    ../mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py \
    ../mmocr/configs/textrecog/satrn/satrn_shallow-small_5e_st_mj.py \
    https://download.openmmlab.com/mmocr/textrecog/satrn/satrn_shallow-small_5e_st_mj/satrn_shallow-small_5e_st_mj_20220915_152442-5591bf27.pth\
    ../mmocr/demo/demo_text_recog.jpg \
    --work-dir ./tmp/tensorrt/satrn_small \
    --device cuda \
    --dump-info 

### Environment

```Shell
I use the orin-nx
jetpack version : 5.1.1
tensorrt : 8.5.2.2.
cuda : 11.4
torch : 1.11
```

### Error traceback

```Shell
there's no bugs. But, the results between onnx and tensorrt are different!
```

**Comment by AllentDan** [comment]
I tested SATRN on TensorRT using a 1060 card and my visualization result seemed fine. Could you share your conversion script? And please post the log of `python tools/check_env.py`.

**Comment by AllentDan** [comment]
Here is the script I used.
```shell
python tools/deploy.py configs/mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py ../mmocr/configs/textrecog/satrn/satrn_shallow_5e_st_mj.py https://download.openmmlab.com/mmocr/textrecog/satrn/satrn_shallow_5e_st_mj/satrn_shallow_5e_st_mj_20220915_152443-5fd04a4c.pth ../mmocr/demo/demo_text_recog.jpg --work-dir work_dirs/tensorrt/ocr/satrn --device cuda --show --dump-info
```

**Comment by Wooho-Moon** [comment]
> I tested SATRN on TensorRT using a 1060 card and my visualization result seemed fine. Could you share your conversion script? And please post the log of `python tools/check_env.py`.

my script is here
python ./tools/deploy.py
../mmocr/text-recognition/text-recognition_tensorrt_dynamic-32x32-32x640.py
../mmocr/configs/textrecog/satrn/satrn_shallow-small_5e_st_mj.py
[https://download.openmmlab.com/mmocr/textrecog/satrn/satrn_shallow-small_5e_st_mj/satrn_shallow-small_5e_st_mj_20220915_152442-5591bf27.pth\](https://download.openmmlab.com/mmocr/textrecog/satrn/satrn_shallow-small_5e_st_mj/satrn_shallow-small_5e_st_mj_20220915_152442-5591bf27.pth%5C)
../mmocr/demo/demo_text_recog.jpg
--work-dir ./tmp/tensorrt/satrn_small
--device cuda
--dump-info

Also, the log is here
07/20 13:17:50 - mmengine - INFO - **********Environmental information**********
07/20 13:17:52 - mmengine - INFO - sys.platform: linux
07/20 13:17:52 - mmengine - INFO - Python: 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:09:18) [GCC 7.3.0]
07/20 13:17:52 - mmengine - INFO - CUDA available: True
07/20 13:17:52 - mmengine - INFO - numpy_random_seed: 2147483648
07/20 13:17:52 - mmengine - INFO - GPU 0: Orin
07/20 13:17:52 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
07/20 13:17:52 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.315
07/20 13:17:52 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
07/20 13:17:52 - mmengine - INFO - PyTorch: 1.11.0
07/20 13:17:52 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_87,code=sm_87
  - CuDNN 8.6
    - Built with CuDNN 8.3.2
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.3.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

07/20 13:17:52 - mmengine - INFO - TorchVision: 0.12.0
07/20 13:17:52 - mmengine - INFO - OpenCV: 4.8.0
07/20 13:17:52 - mmengine - INFO - MMEngine: 0.8.0
07/20 13:17:52 - mmengine - INFO - MMCV: 2.0.0
07/20 13:17:52 - mmengine - INFO - MMCV Compiler: GCC 9.4
07/20 13:17:52 - mmengine - INFO - MMCV CUDA Compiler: 11.4
07/20 13:17:52 - mmengine - INFO - MMDeploy: 1.2.0+ae381c8
07/20 13:17:52 - mmengine - INFO - 

07/20 13:17:52 - mmengine - INFO - **********Backend information**********
07/20 13:17:52 - mmengine - INFO - tensorrt:    8.5.2.2
07/20 13:17:52 - mmengine - INFO - tensorrt custom ops: Available
07/20 13:17:52 - mmengine - INFO - ONNXRuntime: None
07/20 13:17:52 - mmengine - INFO - pplnn:       None
07/20 13:17:52 - mmengine - INFO - ncnn:        None
07/20 13:17:52 - mmengine - INFO - snpe:        None
07/20 13:17:52 - mmengine - INFO - openvino:    None
07/20 13:17:52 - mmengine - INFO - torchscript: 1.11.0
07/20 13:17:52 - mmengine - INFO - torchscript custom ops:      NotAvailable
07/20 13:17:53 - mmengine - INFO - rknn-toolkit:        None
07/20 13:17:53 - mmengine - INFO - rknn-toolkit2:       None
07/20 13:17:53 - mmengine - INFO - ascend:      None
07/20 13:17:53 - mmengine - INFO - coreml:      None
07/20 13:17:53 - mmengine - INFO - tvm: None
07/20 13:17:53 - mmengine - INFO - vacc:        None
07/20 13:17:53 - mmengine - INFO - 

07/20 13:17:53 - mmengine - INFO - **********Codebase information**********
07/20 13:17:53 - mmengine - INFO - mmdet:       3.0.0
07/20 13:17:53 - mmengine - INFO - mmseg:       None
07/20 13:17:53 - mmengine - INFO - mmpretrain:  None
07/20 13:17:53 - mmengine - INFO - mmocr:       1.0.1
07/20 13:17:53 - mmengine - INFO - mmagic:      None
07/20 13:17:53 - mmengine - INFO - mmdet3d:     None
07/20 13:17:53 - mmengine - INFO - mmpose:      None
07/20 13:17:53 - mmengine - INFO - mmrotate:    None
07/20 13:17:53 - mmengine - INFO - mmaction:    None
07/20 13:17:53 - mmengine - INFO - mmrazor:     None
07/20 13:17:53 - mmengine - INFO - mmyolo:      None

**Comment by AllentDan** [comment]
It is hard to say since TensorRT itself sometimes does optimization according to hardware devices.
