### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sk-zhang** [open-mmlab/mmdeploy#2293]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

failed to load library libmmdeploy_trt_net.so and libmmdeploy_ort_net.so

### Reproduction

import argparse

import cv2
import numpy as np
from mmdeploy_runtime import PoseDetector

def parse_args():
    parser = argparse.ArgumentParser(
        description='show how to use sdk python api')
    parser.add_argument('--device_name', default='cuda', help='name of device, cuda or cpu')
    parser.add_argument(
        '--model_path',default='rtmpose-trt/rtmpose-m',
        help='path of mmdeploy SDK model dumped by model converter')
    parser.add_argument('--image_path', default='/media/lxd/新建卷3/zsk/mmpose/tests/data/h36m/S1/S1_Directions_1.54138969/S1_Directions_1.54138969_000001.jpg', help='path of an image')
    parser.add_argument(
        '--bbox',
        default=None,
        nargs='+',
        type=int,
        help='bounding box of an object in format (x, y, w, h)')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    img = cv2.imread(args.image_path)

    detector = PoseDetector(
        model_path=args.model_path, device_name=args.device_name, device_id=0)

    if args.bbox is None:
        result = detector(img)
    else:
        # converter (x, y, w, h) -> (left, top, right, bottom)
        print(args.bbox)
        bbox = np.array(args.bbox, dtype=int)
        bbox[2:] += bbox[:2]
        result = detector(img, bbox)
    print(result)

    _, point_num, _ = result.shape
    points = result[:, :, :2].reshape(point_num, 2)
    for [x, y] in points.astype(int):
        cv2.circle(img, (x, y), 1, (0, 255, 0), 2)

    cv2.imwrite('output_pose.png', img)

if __name__ == '__main__':
    main()

### Environment

```Shell
1/run python tools/check_env.py

07/19 22:24:24 - mmengine - INFO - **********Environmental information**********
07/19 22:24:26 - mmengine - INFO - sys.platform: linux
07/19 22:24:26 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
07/19 22:24:26 - mmengine - INFO - CUDA available: True
07/19 22:24:26 - mmengine - INFO - numpy_random_seed: 2147483648
07/19 22:24:26 - mmengine - INFO - GPU 0: NVIDIA TITAN Xp
07/19 22:24:26 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
07/19 22:24:26 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.4, V11.4.48
07/19 22:24:26 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
07/19 22:24:26 - mmengine - INFO - PyTorch: 1.12.1+cu113
07/19 22:24:26 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2.1
    - Built with CuDNN 8.3.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

07/19 22:24:26 - mmengine - INFO - TorchVision: 0.13.1+cu113
07/19 22:24:26 - mmengine - INFO - OpenCV: 4.8.0
07/19 22:24:26 - mmengine - INFO - MMEngine: 0.8.1
07/19 22:24:26 - mmengine - INFO - MMCV: 2.0.1
07/19 22:24:26 - mmengine - INFO - MMCV Compiler: GCC 9.3
07/19 22:24:26 - mmengine - INFO - MMCV CUDA Compiler: 11.3
07/19 22:24:26 - mmengine - INFO - MMDeploy: 1.2.0+0a8cbe2
07/19 22:24:26 - mmengine - INFO -

07/19 22:24:26 - mmengine - INFO - **********Backend information**********
07/19 22:24:26 - mmengine - INFO - tensorrt:	8.2.3.0
07/19 22:24:26 - mmengine - INFO - tensorrt custom ops:	Available
07/19 22:24:26 - mmengine - INFO - ONNXRuntime:	1.8.1
07/19 22:24:26 - mmengine - INFO - ONNXRuntime-gpu:	None
07/19 22:24:26 - mmengine - INFO - ONNXRuntime custom ops:	Available
07/19 22:24:26 - mmengine - INFO - pplnn:	None
07/19 22:24:26 - mmengine - INFO - ncnn:	1.0.20230719
07/19 22:24:26 - mmengine - INFO - ncnn custom ops:	Available
07/19 22:24:26 - mmengine - INFO - snpe:	None
07/19 22:24:26 - mmengine - INFO - openvino:	None
07/19 22:24:26 - mmengine - INFO - torchscript:	1.12.1+cu113
07/19 22:24:26 - mmengine - INFO - torchscript custom ops:	NotAvailable
07/19 22:24:26 - mmengine - INFO - rknn-toolkit:	None
07/19 22:24:26 - mmengine - INFO - rknn-toolkit2:	None
07/19 22:24:26 - mmengine - INFO - ascend:	None
07/19 22:24:26 - mmengine - INFO - coreml:	None
07/19 22:24:26 - mmengine - INFO - tvm:	None
07/19 22:24:26 - mmengine - INFO - vacc:	None
07/19 22:24:26 - mmengine - INFO -

07/19 22:24:26 - mmengine - INFO - **********Codebase information**********
07/19 22:24:26 - mmengine - INFO - mmdet:	3.0.0
07/19 22:24:26 - mmengine - INFO - mmseg:	None
07/19 22:24:26 - mmengine - INFO - mmpretrain:	None
07/19 22:24:26 - mmengine - INFO - mmocr:	None
07/19 22:24:26 - mmengine - INFO - mmagic:	None
07/19 22:24:26 - mmengine - INFO - mmdet3d:	None
07/19 22:24:26 - mmengine - INFO - mmpose:	1.1.0
07/19 22:24:26 - mmengine - INFO - mmrotate:	None
07/19 22:24:26 - mmengine - INFO - mmaction:	None
07/19 22:24:26 - mmengine - INFO - mmrazor:	None
07/19 22:24:26 - mmengine - INFO - mmyolo:	0.5.0

2/I installed Pytorch using pip.
```

### Error traceback

```Shell
/home/lxd/anaconda3/envs/zskmm/bin/python /media/lxd/新建卷3/zsk/mmdeploy/test.py
loading libmmdeploy_trt_net.so ...
failed to load library libmmdeploy_trt_net.so
loading libmmdeploy_ort_net.so ...
failed to load library libmmdeploy_ort_net.so
[2023-07-19 22:19:44.689] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "rtmpose-trt/rtmpose-m"
[2023-07-19 22:19:44.918] [mmdeploy] [error] [net_module.cpp:47] Net backend not found: tensorrt, available backends: [("onnxruntime", 0)]
[2023-07-19 22:19:44.919] [mmdeploy] [error] [task.cpp:99] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "topdownposeestimator",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by RunningLeon** [comment]
hi, what is it inside your `test.py`? have you parse device with `cuda'?

**Comment by sk-zhang** [comment]
1)I put the contents of my test.py in the Reproduction section as follows. I was trying to load the deployed rtmdet and rtmpose models.


import argparse
import cv2
import numpy as np
from mmdeploy_runtime import PoseDetector

def parse_args():
    parser = argparse.ArgumentParser(
        description='show how to use sdk python api')
    parser.add_argument('--device_name', default='cuda', help='name of device, cuda or cpu')
    parser.add_argument(
        '--model_path',default='rtmpose-trt/rtmpose-m',
        help='path of mmdeploy SDK model dumped by model converter')
    parser.add_argument('--image_path', default='/media/lxd/新建卷3/zsk/mmpose/tests/data/h36m/S1/S1_Directions_1.54138969/S1_Directions_1.54138969_000001.jpg', help='path of an image')
    parser.add_argument(
        '--bbox',
        default=None,
        nargs='+',
        type=int,
        help='bounding box of an object in format (x, y, w, h)')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    img = cv2.imread(args.image_path)

    detector = PoseDetector(
        model_path=args.model_path, device_name=args.device_name, device_id=0)

    if args.bbox is None:
        result = detector(img)
    else:
        # converter (x, y, w, h) -> (left, top, right, bottom)
        print(args.bbox)
        bbox = np.array(args.bbox, dtype=int)
        bbox[2:] += bbox[:2]
        result = detector(img, bbox)
    print(result)

    _, point_num, _ = result.shape
    points = result[:, :, :2].reshape(point_num, 2)
    for [x, y] in points.astype(int):
        cv2.circle(img, (x, y), 1, (0, 255, 0), 2)

    cv2.imwrite('output_pose.png', img)

if __name__ == '__main__':
    main()

2）Does that mean the cuda will work? Then yes.



> hi, what is it inside your `test.py`? have you passed the device type of `cuda'?

**Comment by sk-zhang** [comment]
The contents of test.py are the examples of how to load the model as given in rtm's readme file.

**Comment by RunningLeon** [comment]
@sk-zhang hi, how did you install mmdeploy? maybe you could add libs in to `LD_LIBRARY_PATH` and `PYTHONPATH`.
```
cd mmdeploy
export LD_LIBRARY_PATH=$(pwd)/build/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$(pwd)/build/lib:$PYTHONPATH
```

**Comment by sk-zhang** [comment]
Thank you for your suggestion. After adding the path, I still encountered the same error. Moreover, when I checked the "builld/lib" folder, I noticed that there were no "libmmdeploy_trt_net.so" and "libmmdeploy_ort_net.so" files. There were only three files with the ".so" extension: "libmmdeploy.so", "libmmdeploy_onnxruntime_ops.so", and "libmmdeploy_tensorrt_ops.so". However, there were "libmmdeploy_trt_net.a" and "libmmdeploy_ort_net.a" files. I'm wondering if it's a problem with the cmake compilation. Despite re-executing the tutorial following the instructions, the same issue persists.

**Comment by sk-zhang** [comment]
The way I install mmdeploy is as follows：
git clone https://github.com/open-mmlab/mmdeploy.git
cd mmdeploy
mim install -e .

**Comment by RunningLeon** [comment]
pls. follow the [get_started ](https://mmdeploy.readthedocs.io/en/latest/get_started.html)to install mmdeploy.

**Comment by sk-zhang** [comment]
Thank you very much, the program is now working properly.

**Comment by sk-zhang** [comment]
Thank you very much, the program is now working properly.

**Comment by sk-zhang** [comment]
Why can I only succeed by running in the terminal now? I still get an error when directly running the test.py file.

**Comment by RunningLeon** [comment]
@sk-zhang hi, good to know it's solved. If you feel mmdeploy is useful, pls. give us a star on the GitHub. We'd appreciate your gesture.

**Comment by YingjianYu** [comment]
What's you solution?
