### ISSUE TITLE
[Bug] Build mmdeploy on jetson, there may be bugs about shapely

### ISSUE THREAD

**Issue by da13132** [open-mmlab/mmdeploy#2295]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

After I followed the steps to build mmdeploy on jetson, I found that the program could not be run, and I was prompted 'OSError: /home/zhanglei/archiconda3/envs/mmdeploy/lib/libgeos_c.so: cannot open shared object file: No such file or directory'. I noticed that this may be related to the shapely version, my current version is 1.8.5, however when I try to install shapely==2.0 it fails, python3.6 does not support this package. I tried adding libgeos_c.so to environment variables, but that still doesn't work. Very much hope to get your help！

### Reproduction

from mmdeploy.apis.utils import build_task_processor
from mmdeploy.utils import get_input_shape, load_config
import torch

deploy_cfg = 'configs/mmpose/pose-detection_onnxruntime_static.py'
model_cfg = '/home/zhanglei/Desktop/zhanglei/mmpose/configs/body_2d_keypoint/simcc/coco/nextvit.py'
device = 'cpu'
backend_model = ['end2end.onnx']
image = './demo/resources/human-pose.jpg'

# read deploy_cfg and model_cfg
deploy_cfg, model_cfg = load_config(deploy_cfg, model_cfg)

# build task and backend model
task_processor = build_task_processor(model_cfg, deploy_cfg, device)
model = task_processor.build_backend_model(backend_model)

# process input image
input_shape = get_input_shape(deploy_cfg)
model_inputs, _ = task_processor.create_input(image, input_shape)

# do model inference
with torch.no_grad():
    result = model.test_step(model_inputs)

# visualize results
task_processor.visualize(
    image=image,
    model=model,
    result=result[0],
    window_name='visualize',
    output_file='output_pose.png')

### Environment

```Shell
07/21 01:31:53 - mmengine - INFO - 

07/21 01:31:53 - mmengine - INFO - **********Environmental information**********
07/21 01:31:56 - mmengine - INFO - sys.platform: linux
07/21 01:31:56 - mmengine - INFO - Python: 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 19:12:04) [GCC 9.4.0]
07/21 01:31:56 - mmengine - INFO - CUDA available: True
07/21 01:31:56 - mmengine - INFO - numpy_random_seed: 2147483648
07/21 01:31:56 - mmengine - INFO - GPU 0: Xavier
07/21 01:31:56 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
07/21 01:31:56 - mmengine - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.300
07/21 01:31:56 - mmengine - INFO - GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
07/21 01:31:56 - mmengine - INFO - PyTorch: 1.10.0
07/21 01:31:56 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.2.1
    - Built with CuDNN 8.0
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=8.0.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, 

07/21 01:31:56 - mmengine - INFO - TorchVision: 0.11.1
07/21 01:31:56 - mmengine - INFO - OpenCV: 4.8.0
07/21 01:31:56 - mmengine - INFO - MMEngine: 0.8.2
07/21 01:31:56 - mmengine - INFO - MMCV: 2.0.0
07/21 01:31:56 - mmengine - INFO - MMCV Compiler: GCC 7.5
07/21 01:31:56 - mmengine - INFO - MMCV CUDA Compiler: 10.2
07/21 01:31:56 - mmengine - INFO - MMDeploy: 1.2.0+553f9b8
07/21 01:31:56 - mmengine - INFO - 

07/21 01:31:56 - mmengine - INFO - **********Backend information**********
07/21 01:31:57 - mmengine - INFO - tensorrt:	8.0.1.6
07/21 01:31:57 - mmengine - INFO - tensorrt custom ops:	Available
07/21 01:31:57 - mmengine - INFO - ONNXRuntime:	None
07/21 01:31:57 - mmengine - INFO - pplnn:	None
07/21 01:31:57 - mmengine - INFO - ncnn:	None
07/21 01:31:57 - mmengine - INFO - snpe:	None
07/21 01:31:57 - mmengine - INFO - openvino:	None
07/21 01:31:57 - mmengine - INFO - torchscript:	1.10.0
07/21 01:31:57 - mmengine - INFO - torchscript custom ops:	NotAvailable
07/21 01:31:57 - mmengine - INFO - rknn-toolkit:	None
07/21 01:31:57 - mmengine - INFO - rknn-toolkit2:	None
07/21 01:31:57 - mmengine - INFO - ascend:	None
07/21 01:31:57 - mmengine - INFO - coreml:	None
07/21 01:31:57 - mmengine - INFO - tvm:	None
07/21 01:31:57 - mmengine - INFO - vacc:	None
07/21 01:31:57 - mmengine - INFO - 

07/21 01:31:57 - mmengine - INFO - **********Codebase information**********
07/21 01:31:57 - mmengine - INFO - mmdet:	3.0.0
07/21 01:31:57 - mmengine - INFO - mmseg:	None
07/21 01:31:57 - mmengine - INFO - mmpretrain:	None
07/21 01:31:57 - mmengine - INFO - mmocr:	None
07/21 01:31:57 - mmengine - INFO - mmagic:	None
07/21 01:31:57 - mmengine - INFO - mmdet3d:	None
07/21 01:31:57 - mmengine - INFO - mmpose:	1.1.0
07/21 01:31:57 - mmengine - INFO - mmrotate:	None
07/21 01:31:57 - mmengine - INFO - mmaction:	None
07/21 01:31:57 - mmengine - INFO - mmrazor:	None
07/21 01:31:57 - mmengine - INFO - mmyolo:	None

export PATH=$PATH:~/archiconda3/bin
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
# set environment variable for pip
export OPENBLAS_CORETYPE=ARMV8
# set environment variable for TensorRT
export TENSORRT_DIR=/usr/include/aarch64-linux-gnu
# set environment variable for CUDA
export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
# set environment variable for ppl.cv
export PPLCV_DIR=/home/zhanglei/Desktop/zhanglei/ppl.cv-master
# set environment variable for TensorRT
export TENSORRT_DIR=/usr/include/aarch64-linux-gnu
# set environment variable for CUDA
export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH/usr/lib/aarch64-linux-gnu
export CUDA_ROOT=/usr/local/cuda
# set environment variable for ppl.cv
export PPLCV_DIR=/home/zhanglei/Desktop/zhanglei/ppl.cv
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "111onnx.py", line 15, in <module>
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/apis/utils/utils.py", line 46, in build_task_processor
    import_codebase(codebase_type, custom_module_list)
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/__init__.py", line 37, in import_codebase
    codebase.register_all_modules()
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection.py", line 133, in register_all_modules
    cls.register_deploy_modules()
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmpose/deploy/pose_detection.py", line 123, in register_deploy_modules
    import mmdeploy.codebase.mmdet.models
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmdet/models/__init__.py", line 3, in <module>
    from . import dense_heads  # noqa: F401,F403
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/__init__.py", line 2, in <module>
    from . import base_dense_head  # noqa: F401,F403
  File "/home/zhanglei/Desktop/zhanglei/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py", line 5, in <module>
    from mmdet.models.dense_heads import PAAHead
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..layers import CSPLayer
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/models/layers/__init__.py", line 3, in <module>
    from .bbox_nms import fast_nms, multiclass_nms
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/models/layers/bbox_nms.py", line 8, in <module>
    from mmdet.structures.bbox import bbox_overlaps
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/home/zhanglei/Desktop/zhanglei/mmdetection/mmdet/structures/mask/structures.py", line 10, in <module>
    import shapely.geometry as geometry
  File "/home/zhanglei/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/zhanglei/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/zhanglei/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/home/zhanglei/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/shapely/geos.py", line 94, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
  File "/home/zhanglei/archiconda3/envs/mmdeploy/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/zhanglei/archiconda3/envs/mmdeploy/lib/libgeos_c.so: cannot open shared object file: No such file or directory
```

**Comment by irexyc** [comment]
please try install libgeos-dev: `sudo apt-get install libgeos-dev`

**Comment by tpoisonooo** [comment]
try  `apt-get install libgeos-dev` and check this https://stackoverflow.com/questions/19742406/could-not-find-library-geos-c-or-load-any-of-its-variants

**Comment by da13132** [comment]
> please try install libgeos-dev: `sudo apt-get install libgeos-dev`

> try `apt-get install libgeos-dev` and check this https://stackoverflow.com/questions/19742406/could-not-find-library-geos-c-or-load-any-of-its-variants


Thank you very much！I finally solved this problem using the command: conda install geos . But now I have encountered a new problem. When installing xtcocotools, an error is reported: 'unable to execute 'aarch64-conda_cos7-linux-gnu-gcc': No such file or directory'. I've tried pip install xtcocotools or building from local with no success.
The following is the specific error message：
    ERROR: Command errored out with exit status 1:
     command: /home/zhanglei/archiconda3/envs/mmdeploy/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dgk0kqhm/xtcocotools_71e5954f08ad4954a73fe39de4188f12/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dgk0kqhm/xtcocotools_71e5954f08ad4954a73fe39de4188f12/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sq1mvqiy/install-record.txt --single-version-externally-managed --compile --install-headers /home/zhanglei/archiconda3/envs/mmdeploy/include/python3.6m/xtcocotools
         cwd: /tmp/pip-install-dgk0kqhm/xtcocotools_71e5954f08ad4954a73fe39de4188f12/
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/xtcocotools
    copying xtcocotools/__init__.py -> build/lib.linux-aarch64-3.6/xtcocotools
    copying xtcocotools/version.py -> build/lib.linux-aarch64-3.6/xtcocotools
    copying xtcocotools/coco.py -> build/lib.linux-aarch64-3.6/xtcocotools
    copying xtcocotools/mask.py -> build/lib.linux-aarch64-3.6/xtcocotools
    copying xtcocotools/cocoeval.py -> build/lib.linux-aarch64-3.6/xtcocotools
    running build_ext
    building 'xtcocotools._mask' extension
    creating build/temp.linux-aarch64-3.6
    creating build/temp.linux-aarch64-3.6/xtcocotools
    creating build/temp.linux-aarch64-3.6/common
    aarch64-conda_cos7-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/python_1550972156032/work=/usr/local/src/conda/python-3.6.7 -fdebug-prefix-map=/home/zhanglei/archiconda3/envs/mmdeploy=/usr/local/src/conda-prefix -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/python_1550972156032/work=/usr/local/src/conda/python-3.6.7 -fdebug-prefix-map=/home/zhanglei/archiconda3/envs/mmdeploy=/usr/local/src/conda-prefix -fPIC -I/home/zhanglei/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/numpy/core/include -I./common -I/home/zhanglei/archiconda3/envs/mmdeploy/include/python3.6m -c xtcocotools/_mask.c -o build/temp.linux-aarch64-3.6/xtcocotools/_mask.o
    unable to execute 'aarch64-conda_cos7-linux-gnu-gcc': No such file or directory
    error: command 'aarch64-conda_cos7-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zhanglei/archiconda3/envs/mmdeploy/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dgk0kqhm/xtcocotools_71e5954f08ad4954a73fe39de4188f12/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dgk0kqhm/xtcocotools_71e5954f08ad4954a73fe39de4188f12/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sq1mvqiy/install-record.txt --single-version-externally-managed --compile --install-headers /home/zhanglei/archiconda3/envs/mmdeploy/include/python3.6m/xtcocotools Check the logs for full command output.

**Comment by irexyc** [comment]
Have no idea why it uses `aarch64-conda_cos7-linux-gnu-gcc` instead of system gcc.

You can try to install gcc_linux-aarch64 by `conda install gcc_linux-aarch64` and reinstall xtcocotools

You can also try this whl (don't know if it will work on your system)
[xtcocotools-1.13-cp36-cp36m-linux_aarch64.whl.zip](https://github.com/open-mmlab/mmdeploy/files/12121964/xtcocotools-1.13-cp36-cp36m-linux_aarch64.whl.zip)

**Comment by da13132** [comment]
> 不知道为什么它使用`aarch64-conda_cos7-linux-gnu-gcc`而不是系统gcc。
> 
> 您可以尝试通过`conda install gcc_linux-aarch64`安装gcc_linux-aarch 64并重新安装xtcocotools
> 
> 你也可以试试这个whl（不知道它是否能在你的系统上工作） [xtcocotools-1.13-cp36-cp36m-linux_aarch64.whl.zip](https://github.com/open-mmlab/mmdeploy/files/12121964/xtcocotools-1.13-cp36-cp36m-linux_aarch64.whl.zip)
> 
> 您可能遇到的其他错误 https://forums.developer.nvidia.com/t/illegal-instruction-core-dumped/165488/13

Thank you very much for your reply, I use the command: conda install -c anaconda gxx_linux-64 also solved this problem with gcc, then, I can't compile xtcocotools correctly, the precompiled file you provided successfully solved this problem, although I still haven't figured out why xtcocotools can't compile correctly in my jetson. So far, with the help of you and your team, I have successfully run mmdeploy in jetson, thank you very much for your work and these efficient open source frameworks.

**Comment by da13132** [comment]
> Have no idea why it uses `aarch64-conda_cos7-linux-gnu-gcc` instead of system gcc.
> 
> You can try to install gcc_linux-aarch64 by `conda install gcc_linux-aarch64` and reinstall xtcocotools
> 
> You can also try this whl (don't know if it will work on your system) [xtcocotools-1.13-cp36-cp36m-linux_aarch64.whl.zip](https://github.com/open-mmlab/mmdeploy/files/12121964/xtcocotools-1.13-cp36-cp36m-linux_aarch64.whl.zip)
> 
> Other errors you may meet https://forums.developer.nvidia.com/t/illegal-instruction-core-dumped/165488/13

Thank you very much for your reply, I use the command: conda install -c anaconda gxx_linux-64 also solved this problem with gcc, then, I can't compile xtcocotools correctly, the precompiled file you provided successfully solved this problem, although I still haven't figured out why xtcocotools can't compile correctly in my jetson. So far, with the help of you and your team, I have successfully run mmdeploy in jetson, thank you very much for your work and these efficient open source frameworks.
