### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sunwenhaopro** [open-mmlab/mmdeploy#2297]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I compiled and generated the java SDK api under Windows without errors. When I called the mmdeploy.jar package in the IDEA project, an error was generated.
`Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Program Files\Java\jdk-13\bin\mmdeploy_java.dll: %1 不是有效的 Win32 应用程序。
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:806)
	at java.base/java.lang.System.loadLibrary(System.java:1906)
	at com.example.demo.DemoApplication.main(DemoApplication.java:15)`
This is an error with the mmdeploy_java.dll file, which I have placed in the jdk/bin directory. I have also tried to value other 64-bit dll files with success. I also checked the mmdeploy_java.dll file is also 64-bit

### Reproduction

I just run the compile with the documentation

### Environment

```Shell
I just run the compile with the documentation
```

**Comment by irexyc** [comment]
@sunwenhaopro 
What backend are you using when you build mmdeploy? 

If it is onnxruntime, you can use [this tools](https://github.com/lucasg/Dependencies) to check if it find the right dll. Usually you need to hide the onnxruntime.dll(rename or delete) in the C drive.

https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/faq.md#onnx-runtime

**Comment by sunwenhaopro** [comment]
Thank you very much. I already know where I went wrong. I once downloaded the X86 onnx, so the onnxRuntime. dll in the c disk is 32-bit, the X64 onnxruntime dll file that I downloaded when compiling could not overwrite the original dll file, so it caused an error
