### ISSUE TITLE
How to deploy the model on mobile phone?

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmdeploy#2298]
### 📚 The doc issue

As the rtmpose project mentioned in [here](https://github.com/Tau-J/mmpose/tree/tau/rtm/projects/rtmpose), the inference of rtmpose can be tested by Snapdragon 865 chip. And I would like to ask that does the model run like an app on mobile phone's chip for the inference? I am eager to test it on smart phone. May I have an quick example ?
Just like the [this](https://zhuanlan.zhihu.com/p/492090146?utm_id=0)
I have read the [doc](https://github.com/open-mmlab/mmdeploy/tree/main/demo/java) and the [issues](https://github.com/open-mmlab/mmdeploy/issues/2158). I got no idea whether it runs on android or some where

Thank you!!!

**Comment by irexyc** [comment]
There is a repo you can refer to https://github.com/hanrui1sensetime/PoseTracker-Android-Prototype
