### ISSUE TITLE
[Bug] AttributeError: 'torch._C.Graph' object has no attribute 'opset'

### ISSUE THREAD

**Issue by caj-github** [open-mmlab/mmdeploy#2299]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

when export tensorrt with dynamic shape, report a error:AttributeError: 'torch._C.Graph' object has no attribute 'opset'

### Reproduction

![image](https://github.com/open-mmlab/mmdeploy/assets/55951697/1c60bba0-5e85-4fab-97f5-4e3afd28c54d)

### Environment

```Shell
win10
mmdeploy1.2.0
```

**Comment by lvhan028** [comment]
Could you share the result of `python tools/check_env.py`?

**Comment by caj-github** [comment]
07/26 18:12:47 - mmengine - INFO - **********Environmental information**********
07/26 18:12:51 - mmengine - INFO - sys.platform: win32
07/26 18:12:51 - mmengine - INFO - Python: 3.10.11 | packaged by Anaconda, Inc. | (main, May 16 2023, 00:55:32) [MSC v.1916 64 bit (AMD64)]
07/26 18:12:51 - mmengine - INFO - CUDA available: True
07/26 18:12:51 - mmengine - INFO - numpy_random_seed: 2147483648
07/26 18:12:51 - mmengine - INFO - GPU 0: NVIDIA TITAN RTX
07/26 18:12:51 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
07/26 18:12:51 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.124
07/26 18:12:51 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32217.1 版
07/26 18:12:51 - mmengine - INFO - GCC: n/a
07/26 18:12:51 - mmengine - INFO - PyTorch: 1.13.1+cu116
07/26 18:12:51 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

07/26 18:12:51 - mmengine - INFO - TorchVision: 0.14.1+cu116
07/26 18:12:51 - mmengine - INFO - OpenCV: 4.8.0
07/26 18:12:51 - mmengine - INFO - MMEngine: 0.8.2
07/26 18:12:51 - mmengine - INFO - MMCV: 2.0.1
07/26 18:12:51 - mmengine - INFO - MMCV Compiler: MSVC 193532217
07/26 18:12:51 - mmengine - INFO - MMCV CUDA Compiler: 11.6
07/26 18:12:51 - mmengine - INFO - MMDeploy: 1.2.0+
07/26 18:12:51 - mmengine - INFO -

07/26 18:12:51 - mmengine - INFO - **********Backend information**********
07/26 18:12:51 - mmengine - INFO - tensorrt:    8.4.0.6
07/26 18:12:51 - mmengine - INFO - tensorrt custom ops: Available
07/26 18:12:51 - mmengine - INFO - ONNXRuntime: None
07/26 18:12:51 - mmengine - INFO - ONNXRuntime-gpu:     1.12.1
07/26 18:12:51 - mmengine - INFO - ONNXRuntime custom ops:      Available
07/26 18:12:51 - mmengine - INFO - pplnn:       None
07/26 18:12:51 - mmengine - INFO - ncnn:        None
07/26 18:12:51 - mmengine - INFO - snpe:        None
07/26 18:12:51 - mmengine - INFO - openvino:    None
07/26 18:12:51 - mmengine - INFO - torchscript: 1.13.1+cu116
07/26 18:12:51 - mmengine - INFO - torchscript custom ops:      NotAvailable
07/26 18:12:51 - mmengine - INFO - rknn-toolkit:        None
07/26 18:12:51 - mmengine - INFO - rknn-toolkit2:       None
07/26 18:12:51 - mmengine - INFO - ascend:      None
07/26 18:12:51 - mmengine - INFO - coreml:      None
07/26 18:12:51 - mmengine - INFO - tvm: None
07/26 18:12:51 - mmengine - INFO - vacc:        None
07/26 18:12:51 - mmengine - INFO -

07/26 18:12:51 - mmengine - INFO - **********Codebase information**********
07/26 18:12:51 - mmengine - INFO - mmdet:       3.0.0
07/26 18:12:51 - mmengine - INFO - mmseg:       1.1.1
07/26 18:12:51 - mmengine - INFO - mmpretrain:  1.0.0
07/26 18:12:51 - mmengine - INFO - mmocr:       1.0.1
07/26 18:12:51 - mmengine - INFO - mmagic:      None
07/26 18:12:51 - mmengine - INFO - mmdet3d:     None
07/26 18:12:51 - mmengine - INFO - mmpose:      None
07/26 18:12:51 - mmengine - INFO - mmrotate:    1.0.0rc1
07/26 18:12:51 - mmengine - INFO - mmaction:    None
07/26 18:12:51 - mmengine - INFO - mmrazor:     None
07/26 18:12:51 - mmengine - INFO - mmyolo:      0.5.0

**Comment by irexyc** [comment]
Could you provide the full model cfg?
