### ISSUE TITLE
[Bug] build_dsk.ps1 is not digitally signed, cannot install mmdeploy from prebuild source

### ISSUE THREAD

**Issue by bc-arl** [open-mmlab/mmdeploy#2313]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

I am trying to build mmdeploy from the prebuild release on windows
I followed the instructions like so:
* Downloaded "mmdeploy-1.1.0-windows-amd64-cuda11.3.zip" from [the releases page](https://github.com/open-mmlab/mmdeploy/releases/download/v1.1.0/mmdeploy-1.1.0-windows-amd64-cuda11.3.zip)
* Extracted the zip file
* Opened windows powershell as administrator
* Set the execution policy to allow signed powershell scripts
```
set-ExecutionPolicy RemoteSigned
```
* I then run build_dsk powershell script but I get an error saying the powershell script is not digitally signed

### Reproduction

```
.\build_sdk.ps1
```

### Environment

```Shell
Not related.
```

### Error traceback
.\build_sdk.ps1: File C:\Users\USER\Downloads\mmdeploy-1.1.0-windows-amd64-cuda11.3\mmdeploy-1.1.0-windows-amd64-cuda11.3\build_sdk.ps1 cannot be loaded. The file C:\Users\USER\Downloads\mmdeploy-1.1.0-windows-amd64-cuda11.3\mmdeploy-1.1.0-windows-amd64-cuda11.3\build_sdk.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.

I also verified using Get-AuthenticodeSignature, and it said none of the powershell scripts are signed.

**Comment by irexyc** [comment]
You can refer to this methods https://windowsreport.com/powershell-not-digitally-signed/

a) run powershell as admin
b) ​​Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass​​
