### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by GiovanniFyc** [open-mmlab/mmdeploy#2314]
### 📚 The doc issue

![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/715b04f0-315b-4d71-9093-9d313b3d086d)
There should be an error here

**Comment by RunningLeon** [comment]
hi, can you elaborate more on the issue?

**Comment by fanyunchao** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/e24898b0-21d3-41d6-8bcb-bdc3faf39d83)
when i test  for the c++ code in getstart at mmdeploy docs,the bboxes is not exist,it should be replaced by dets[i].

**Comment by RunningLeon** [comment]
@fanyunchao hi, thanks for your reply. Could you pull a request to fix the document?

**Comment by fanyunchao** [comment]
I have already pull a request
