### ISSUE TITLE
[Bug] `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

### ISSUE THREAD

**Issue by bluesoulh** [open-mmlab/mmdeploy#2326]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi!
Thank you always for your continuous support.

I had the following issues when using my trained model for ONNX transformation

08/03 16:30:27 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
08/03 16:30:27 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
08/03 16:30:29 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
08/03 16:30:30 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
08/03 16:30:30 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
/root/mmsegmentation/mmseg/models/builder.py:36: UserWarning: ``build_loss`` would be deprecated soon, please use ``mmseg.registry.MODELS.build()`` 
  warnings.warn('``build_loss`` would be deprecated soon, please use '
/root/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/root/mmsegmentation/mmseg/structures/sampler/builder.py:11: UserWarning: ``build_pixel_sampler`` would be deprecated soon, please use ``mmseg.registry.TASK_UTILS.build()`` 
  warnings.warn(
Loads checkpoint by local backend from path: ../autodl-tmp/checkpoint/OceanDataset/dmnetfinal/iter_36800.pth
08/03 16:30:31 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
08/03 16:30:31 - mmengine - INFO - Export PyTorch model to ONNX: mmseg2onnx_dmnet/end2end.onnx.
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/core/optimizers/function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
08/03 16:30:35 - mmengine - WARNING - `adaptive_avg_pool2d` would be replaced to `avg_pool2d` explicitly
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/pytorch/functions/adaptive_pool.py:26: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  k = [int(size[i] / output_size[i]) for i in range(0, len(size))]
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/codebase/mmseg/models/segmentors/base.py:61: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if seg_logit.shape[1] == 1:
/root/miniconda3/lib/python3.8/site-packages/torch/onnx/_internal/jit_utils.py:306: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Process Process-2:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 131, in export
    torch.onnx.export(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1891, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 2451, in _convolution
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of convolution for kernel of unknown shape.  [Caused by the value '654 defined in (%654 : Float(*, *, *, *, strides=[15663104, 30592, 239, 1], requires_grad=0, device=cpu) = onnx::Pad[mode="constant"](%623, %652, %653), scope: mmseg.models.segmentors.encoder_decoder.EncoderDecoder::/mmseg.models.decode_heads.dm_head.DCM::dcm_modules.0 # /root/mmsegmentation/mmseg/models/decode_heads/dm_head.py:77:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Pad'.] 
    (node defined in /root/mmsegmentation/mmseg/models/decode_heads/dm_head.py(77): forward
/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/root/mmsegmentation/mmseg/models/decode_heads/dm_head.py(157): forward
/root/mmsegmentation/mmseg/models/decode_heads/decode_head.py(281): predict
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py(26): encoder_decoder__predict
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/codebase/mmseg/models/segmentors/base.py(51): base_segmentor__forward
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py(123): wrapper
/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/root/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(118): wrapper
/root/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(127): forward
/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py(1501): _call_impl
/root/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py(1268): _get_trace_graph
/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py(893): _trace_and_get_graph_from_model
/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py(989): _create_jit_graph
/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py(1113): _model_to_graph
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/onnx/optimizer.py(27): model_to_graph__custom_optimizer
/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py(1548): _export
/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py(506): export
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py(131): export
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py(107): __call__
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py(275): call_function_local
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py(326): call_function
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py(356): _wrap
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py(98): torch2onnx
/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py(107): __call__
/root/miniconda3/lib/python3.8/multiprocessing/process.py(108): run
/root/miniconda3/lib/python3.8/multiprocessing/process.py(315): _bootstrap
/root/miniconda3/lib/python3.8/multiprocessing/spawn.py(129): _main
/root/miniconda3/lib/python3.8/multiprocessing/spawn.py(116): spawn_main
<string>(1): <module>
)

    Inputs:
        #0: 623 defined in (%623 : Float(*, *, *, *, strides=[15663104, 30592, 239, 1], requires_grad=0, device=cpu) = onnx::Reshape(%603, %622), scope: mmseg.models.segmentors.encoder_decoder.EncoderDecoder::/mmseg.models.decode_heads.dm_head.DCM::dcm_modules.0 # /root/mmsegmentation/mmseg/models/decode_heads/dm_head.py:68:0
    )  (type 'Tensor')
        #1: 652 defined in (%652 : Long(8, strides=[1], device=cpu) = onnx::Cast[to=7](%651), scope: mmseg.models.segmentors.encoder_decoder.EncoderDecoder::/mmseg.models.decode_heads.dm_head.DCM::dcm_modules.0 # /root/mmsegmentation/mmseg/models/decode_heads/dm_head.py:77:0
    )  (type 'Tensor')
        #2: 653 defined in (%653 : Float(device=cpu) = onnx::Constant[value={0}](), scope: mmseg.models.segmentors.encoder_decoder.EncoderDecoder::/mmseg.models.decode_heads.dm_head.DCM::dcm_modules.0 # /root/mmsegmentation/mmseg/models/decode_heads/dm_head.py:77:0
    )  (type 'Tensor')
    Outputs:
        #0: 654 defined in (%654 : Float(*, *, *, *, strides=[15663104, 30592, 239, 1], requires_grad=0, device=cpu) = onnx::Pad[mode="constant"](%623, %652, %653), scope: mmseg.models.segmentors.encoder_decoder.EncoderDecoder::/mmseg.models.decode_heads.dm_head.DCM::dcm_modules.0 # /root/mmsegmentation/mmseg/models/decode_heads/dm_head.py:77:0
    )  (type 'Tensor')
08/03 16:30:38 - mmengine - ERROR - /root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

The final error is 08/03 16:30:38 - mmengine - ERROR - /root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

How should I modify and convert successfully？

### Reproduction

Here is the code I run

!python tools/deploy.py \
        configs/mmseg/segmentation_onnxruntime_dynamic.py \
        ../autodl-tmp/checkpoint/OceanDataset/dmnetfinal/20230802_161925/vis_data/config.py \
        ../autodl-tmp/checkpoint/OceanDataset/dmnetfinal/iter_36800.pth \
        ../mmsegmentation/data/OceanData/img_dir/val/00275.jpg \
        --work-dir mmseg2onnx_dmnet \
        --dump-info

### Environment

```Shell
MMDeploy version 1.2.0

ONNXRuntime version 1.15.1

python3.8 + cuda11.3
```

**Comment by RunningLeon** [comment]
@bluesoulh hi, could you try `tools/torch2onnx.py` and check the error message?

**Comment by bluesoulh** [comment]
@RunningLeon Thank you very much for your reply Are you Chinese I use Chinese description can you understand?

If you don't understand Chinese, please reply to me. I will reply to you again in English。 thank you！

这是/root/miniconda3/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py 中有关于该错误的代码
def pop_mp_output(self, call_id: int = None) -> Any:
        """pop multiprocess output."""
        assert self._mp_dict is not None, 'mp_dict is None.'
        call_id = self._call_id if call_id is None else call_id
        if call_id not in self._mp_dict:
            get_root_logger().error(
                f'`{self._func_name}` with Call id: {call_id} failed. exit.')
            exit(1)
        ret = self._mp_dict[call_id]
        self._mp_dict.pop(call_id)
        return ret

在torch2onnx.py中我没有找到相关错误信息 抱歉

这段报错中间还有一句错误如下 
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of convolution for kernel of unknown shape.  [Caused by the value '654 defined in (%654 : Float(*, *, *, *, strides=[15663104, 30592, 239, 1], requires_grad=0, device=cpu) = onnx::Pad[mode="constant"](%623, %652, %653), scope: mmseg.models.segmentors.encoder_decoder.EncoderDecoder::/mmseg.models.decode_heads.dm_head.DCM::dcm_modules.0 # /root/mmsegmentation/mmseg/models/decode_heads/dm_head.py:77:0

dm_head.py中77行内容为 x = F.pad(input=x, pad=p2d, mode='constant', value=0)
这是相关函数代码段
 def forward(self, x):
        """Forward function."""
        generated_filter = self.filter_gen_conv(
            F.adaptive_avg_pool2d(x, self.filter_size))
        x = self.input_redu_conv(x)
        b, c, h, w = x.shape
        # [1, b * c, h, w], c = self.channels
        x = x.view(1, b * c, h, w)
        # [b * c, 1, filter_size, filter_size]
        generated_filter = generated_filter.view(b * c, 1, self.filter_size,
                                                 self.filter_size)
        pad = (self.filter_size - 1) // 2
        if (self.filter_size - 1) % 2 == 0:
            p2d = (pad, pad, pad, pad)
        else:
            p2d = (pad + 1, pad, pad + 1, pad)
        x = F.pad(input=x, pad=p2d, mode='constant', value=0)
        # [1, b * c, h, w]
        output = F.conv2d(input=x, weight=generated_filter, groups=b * c)
        # [b, c, h, w]
        output = output.view(b, c, h, w)
        if self.norm is not None:
            output = self.norm(output)
        output = self.activate(output)

        if self.fusion:
            output = self.fusion_conv(output)

        return output
是否影响后续错误？应该如何调整？

还有一点是我在尝试静态转换时成功 我把configs/mmseg/segmentation_onnxruntime_dynamic.py改为configs/mmseg/segmentation_onnxruntime_static-1024x2048.py后可以成功转换 是否我训练的网络不支持动态转换？ 

在训练时数据集图片输入尺寸均为512×1024  按照静态1024×2048转换后是否影响原模型性能？ 如果不影响的话我可以直接采用静态转换  动态转换我不知道错误出在哪里

非常感谢你的回复 如果您可以继续提供帮助我将感激不尽 麻烦您了 谢谢

**Comment by RunningLeon** [comment]
hi, `adaptive_avg_pool2d` is dynamic operator and it's not supported in onnx. For mmseg models, strongly suggest use static shape for deployment.

**Comment by bluesoulh** [comment]
@RunningLeon  I am very glad to receive your reply! If a static shape is used for deployment, will it affect the performance of the model after deployment?  
and what meaning of 1024× 2048 in static deployment？
I would be glad to hear from you, thank you！

**Comment by RunningLeon** [comment]
`1024x2048` is for evaluating model on Cityscapes dataset with `whole` inference mode. Maybe for your case, you could modify the test pipeline  in model config that would pad the image to the same shape
