### ISSUE TITLE
AttributeError: module 'mmcv' has no attribute '__version__'

### ISSUE THREAD

**Issue by 1xinyi** [open-mmlab/mmdeploy#2330]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

初步估计应该是版本问题，开发人员删除了相应的功能

### Reproduction

命令：python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg
没有更改

### Environment

```Shell
python3.10.8
cudatoolkit10.2.89
mmcv-full 1.7.1
mmdet2.28.2
mmrotate0.8.4
pytorch2.0.1
torchvision 0.15.2
```

### Error traceback

```Shell
(op) D:\picture\conan\mmrotate-0.3.4\mmrotate-0.3.4>python demo/image_demo.py demo/demo.jpg oriented_rcnn_r50_fpn_1x_dota_le90.py oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth --out-file result.jpg
Traceback (most recent call last):
  File "D:\picture\conan\mmrotate-0.3.4\mmrotate-0.3.4\demo\image_demo.py", line 4, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result_pyplot
  File "D:\Anaconda3\Anaconda\envs\op\lib\site-packages\mmdet\__init__.py", line 21, in <module>
    mmcv_version = digit_version(mmcv.__version__)
AttributeError: module 'mmcv' has no attribute '__version__'
```

**Comment by irexyc** [comment]
这个命令似乎跟mmdeploy没什么关系，因该去mmrotate repo下面提issue
