### ISSUE TITLE
[Docs] https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/01-how-to-build/jetsons.md

### ISSUE THREAD

**Issue by zhanghui-china** [open-mmlab/mmdeploy#2331]
### 📚 The doc issue

git clone https://github.com/pytorch/vision torchvision
cd torchvision
git checkout tags/v0.11.1 -b v0.11.1
export BUILD_VERSION=0.11.1
pip install -e .

The last operation cannot install torchvision

### Suggest a potential alternative/fix

need to change to 
python setup.py install

**Comment by RunningLeon** [comment]
if you are using the same tag, then it's supposed to run in the right way.
