### ISSUE TITLE
import mmdeploy_python还是import mmdeploy 

### ISSUE THREAD

**Issue by futureflsl** [open-mmlab/mmdeploy#2344]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

感觉mmdeploy版本有点混乱，源码是mmdeploy，在源码里面直接用import mmdeploy，但是安装whl到anaconda里面确实mmdepliy_python，请问这个有什么区别吗

### Reproduction

import mmdeploy_python还是import mmdeploy 

### Environment

```Shell
import mmdeploy_python还是import mmdeploy
```

### Error traceback

```Shell
import mmdeploy_python还是import mmdeploy
```

**Comment by RunningLeon** [comment]
hi, sorry for the confusion. mmdeploy packages is for convert, visualize, align pytorch model to backend model. `mmdeploy_python` which is changed to `mmdeploy_runtime` is the python package for inference sdk. You can check [this](https://mmdeploy.readthedocs.io/en/latest/get_started.html#introduction) doc for more info.
