### ISSUE TITLE
how to git clone specific mmdeploy version and its submodule

### ISSUE THREAD

**Issue by futureflsl** [open-mmlab/mmdeploy#2346]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I want to git clone mmdeploy==0.8.0 and its submodules,but now I just can download source code in release log and I can not know its submodule version,like spdlog version.I use 
git clone -b 0.8.0 https://github.com/open-mmlab/mmdeploy --recursive
it show error for no such branch

### Reproduction

git clone -b 0.8.0 https://github.com/open-mmlab/mmdeploy --recursive
this can not git clone correctly

### Environment

```Shell
windows x64
```

**Comment by RunningLeon** [comment]
hi, you could try `git clone -b v0.8.0 --recursive https://github.com/open-mmlab/mmdeploy.git`
