### ISSUE TITLE
About modify the POSETRACKER.apply function

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmdeploy#2358]
### 📚 The doc issue

Hi,
May I ask about how to modify the java file of POSETRACKER?
It seems that if I use POSETRACKER.apply, it will return the bbox and keypoints simultaneously. And I cannot find more detail about the apply function.
Because I want to analyze the execution time of object detection model and keypoints detection model respectively.
Is it possible to reach that? If so, could you please tell me which doc I should modify.

### Suggest a potential alternative/fix

None

**Comment by kdavidlp123** [comment]
Hi, Is there any solution?
Thank you!!!

**Comment by irexyc** [comment]
@kdavidlp123 

`POSETRACKER.apply` not only contains model inference(object detection and  keypoints detection) but also some tracking strategies like `KalmanFilter`.

To analyze the  execution time of object detection or keypoints detection, I suggest you to modify the code based on `demo/java/src/PoseDetection.java` and `demo/java/src/ObjectDetection.java` as these two demos only contains single task.

The sdk has a [profiling function](https://mmdeploy.readthedocs.io/en/latest/sdk_usage/profiler.html). To use this in java, you have to modify some code.
