### ISSUE TITLE
docker build gpu error

### ISSUE THREAD

**Issue by hyaihjq** [open-mmlab/mmdeploy#236]
1、运行命令
docker build docker/GPU/ -t mmdeploy:master-gpu
2、报错
Build files have been written to: /root/workspace/mmdeploy/build/install/example/build
[ 10%] Building CXX object CMakeFiles/ocr.dir/ocr.cpp.o
[ 20%] Linking CXX executable ocr
/usr/bin/ld: warning: libcuda.so.1, needed by /root/workspace/mmdeploy/build/install/lib/libmmdeploy_cuda_device.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /root/workspace/mmdeploy/build/install/lib/libmmdeploy_cuda_device.so: undefined reference to `cuCtxGetCurrent'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ocr.dir/build.make:172: ocr] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: CMakeFiles/ocr.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
The command '/bin/sh -c cd /root/workspace/mmdeploy &&    rm -rf build/CM* &&    mkdir -p build && cd build &&    cmake ..         -DMMDEPLOY_BUILD_SDK=ON         -DCMAKE_CXX_COMPILER=g++         -Dpplcv_DIR=/root/workspace/ppl.cv/cuda-build/install/lib/cmake/ppl         -DTENSORRT_DIR=${TENSORRT_DIR}         -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON         -DMMDEPLOY_TARGET_DEVICES="cuda;cpu"         -DMMDEPLOY_TARGET_BACKENDS="trt"         -DMMDEPLOY_CODEBASES=all &&    cmake --build . -- -j$(nproc) && cmake --install . &&    cd install/example  && mkdir -p build && cd build &&    cmake -DMMDeploy_DIR=/root/workspace/mmdeploy/build/install/lib/cmake/MMDeploy .. &&    cmake --build . && export SPDLOG_LEVEL=warn &&    if [ -z ${VERSION} ] ; then echo "Built MMDeploy master for GPU devices successfully!" ; else echo "Built MMDeploy version v${VERSION} for GPU devices successfully!" ; fi' returned a non-zero code: 2

**Comment by lvhan028** [comment]
@AllentDan please check the path of `libcuda.so`

**Comment by AllentDan** [comment]
The same as issue [230](https://github.com/open-mmlab/mmdeploy/issues/230)

**Comment by hyaihjq** [comment]
> The same as issue [230](https://github.com/open-mmlab/mmdeploy/issues/230)

只能build VERSION=0.2.0的mmdeploy版本？0.3.0及之后的不支持？

**Comment by hyaihjq** [comment]
> @AllentDan please check the path of `libcuda.so`

thanks

**Comment by lvhan028** [comment]
> > @AllentDan please check the path of `libcuda.so`
> 
> thanks

It is resolved by PR #249. You can try the docker build with latest master of MMDeploy

**Comment by hyaihjq** [comment]
> > > @AllentDan please check the path of `libcuda.so`
> > 
> > 
> > thanks
> 
> It is resolved by PR #249. You can try the docker build with latest master of MMDeploy

thanks
