### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by lbq779660843** [open-mmlab/mmdeploy#2365]
### 📚 The doc issue

I convert my model which was trained by my custom dataset which is strictly defined according to the coco dataset pose estimation standard in MMPose from .pth to .onnx, the output image of onnxruntime and PyTorch both perform badly, but the .pth model can get normal results.

output_onnxruntime
![output_onnxruntime](https://github.com/open-mmlab/mmpose/assets/27773249/a1514a45-784a-4abc-a9e6-78d79aa0b421)
output_pytorch
![output_pytorch](https://github.com/open-mmlab/mmpose/assets/27773249/cd449d0d-7037-4db4-be27-1f281a867894)

normal results
![20181002000013-00-00 MP4_1457_0](https://github.com/open-mmlab/mmpose/assets/27773249/7737c97c-eb58-48bc-9ce7-ff52aea0b474)
![20181002000013-00-00 MP4_1457_1](https://github.com/open-mmlab/mmpose/assets/27773249/2ec23df2-f3b3-420c-a702-487b7069b500)
![20181002000013-00-00 MP4_1457_2](https://github.com/open-mmlab/mmpose/assets/27773249/eb45ba53-6ea9-4cee-a039-91173e924cad)

Additionally, I'm trying to deploy the models on onnxruntime and tensorrt based on this [link](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose/examples/RTMPose-Deploy)supplied by RTMPose, and I've trained the object detection model in mmdetection and converted this model to .onnx and .engine files, the bbox result is fine but the poses are wrong.
![1](https://github.com/open-mmlab/mmpose/assets/27773249/3d094d70-a40a-4117-aad4-b2750d7c727b)
![2](https://github.com/open-mmlab/mmpose/assets/27773249/e2303483-5691-4b6e-9b2a-fbf73889da00)
“”“

**Comment by RunningLeon** [comment]
hi, pls. provide relevant resources to reproduce.

**Comment by lbq779660843** [comment]
Thanks, you can get my configs and models in [there](https://drive.google.com/drive/folders/1E41EIR-Rontla9L0BX4L8f7y1e1qfgKf?usp=drive_link).

--- RTMDET
||______   rtmdet.pth
||______  rtmdet_s_8xb32-300e_coco-slot.py    (path_to_mmdetection/configs/rtmdet/)
--- RTMPOSE
||______   rtmpose.pth
||______   rtmpose-s_8xb256-420e_coco-slot-256x192.py    (path_to_mmpose/configs/body_2d_keypoint/rtmpose/coco/)

**Comment by RunningLeon** [comment]
Ok. Will try to reproduce when the resources are available to download.
