### ISSUE TITLE
[Bug] There was a problem when I deployed in C++

### ISSUE THREAD

**Issue by PlutoNov** [open-mmlab/mmdeploy#2369]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I compiled using cmake and got a project. But when I was ready to execute, there was an error ,VS prompts application error, application cannot start normally (0xc000007b),and I couldn't fix this, hope it helps
![2](https://github.com/open-mmlab/mmdeploy/assets/70734763/7a03f5c7-4753-4470-9515-49c4cdae77b6)
![1](https://github.com/open-mmlab/mmdeploy/assets/70734763/ad213694-cc51-49f2-936c-d32098eeb6cc)

### Reproduction

The image_segmentation.cpp generated by cmake compilation

### Environment

```Shell
opencv,onnxruntime
```

**Comment by irexyc** [comment]
Please remove there two files and try again:
```
C:\Windows\SysWOW64\onnxruntime.dll
C:\Windows\System32\onnxruntime.dll
```

**Comment by fromchina-nb** [comment]
> Please remove there two files and try again:
> 
> ```
> C:\Windows\SysWOW64\onnxruntime.dll
> C:\Windows\System32\onnxruntime.dll
> ```

Sorry I didn't see a reply during this time, I just tried it, and after deleting it it will say that the dll is missing and the program cannot be executed.
