### ISSUE TITLE
How to pass data to variable 'img_metas'?

### ISSUE THREAD

**Issue by xd-HKPC** [open-mmlab/mmdeploy#237]
Hello, I would like to use CenterNet detector head. It requires `batch_input_shape` and `border` info in `img_metas`. Should I need to rewrite the CenterNet detector head?

It seems `img_metas` in this function is always as `None`.
https://github.com/open-mmlab/mmdeploy/blob/776659a6ce98395833ae02d9429076bc8e161890/mmdeploy/codebase/mmdet/models/detectors/base.py#L33

Could you give me any solution? Thank you in advance.

**Comment by RunningLeon** [comment]
@xd-HKPC Hi, centerNet has  not been supported yet. You may have to rewrite CenterNet Head.
 `batch_input_shape` can be put into `img_metas` just like `img_shape`.
https://github.com/open-mmlab/mmdeploy/blob/776659a6ce98395833ae02d9429076bc8e161890/mmdeploy/codebase/mmdet/models/detectors/base.py#L26

It seems `batch_input_shape` is equal to `img_shape`. If it's true, you can use `img_shape` directly.

And `ctx.cfg` is the original `model_config` and `border` can be extracted from `ctx.cfg`.

When you get these two args, then you can rewrite centernet_head.

**Comment by xd-HKPC** [comment]
> @xd-HKPC Hi, centerNet has not been supported yet. You may have to rewrite CenterNet Head. `batch_input_shape` can be put into `img_metas` just like `img_shape`.
> 
> https://github.com/open-mmlab/mmdeploy/blob/776659a6ce98395833ae02d9429076bc8e161890/mmdeploy/codebase/mmdet/models/detectors/base.py#L26
> 
> It seems `batch_input_shape` is equal to `img_shape`. If it's true, you can use `img_shape` directly.
> 
> And `ctx.cfg` is the original `model_config` and `border` can be extracted from `ctx.cfg`.
> 
> When you get these two args, then you can rewrite centernet_head.

Thank you for your suggestion. I will try.

**Comment by xd-HKPC** [comment]
> @xd-HKPC Hi, centerNet has not been supported yet. You may have to rewrite CenterNet Head. `batch_input_shape` can be put into `img_metas` just like `img_shape`.
> 
> https://github.com/open-mmlab/mmdeploy/blob/776659a6ce98395833ae02d9429076bc8e161890/mmdeploy/codebase/mmdet/models/detectors/base.py#L26
> 
> It seems `batch_input_shape` is equal to `img_shape`. If it's true, you can use `img_shape` directly.
> 
> And `ctx.cfg` is the original `model_config` and `border` can be extracted from `ctx.cfg`.
> 
> When you get these two args, then you can rewrite centernet_head.

Hi, it seems `ctx.cfg` only contains `deploy_config` since the rewriter only pass the `deploy_config`.
https://github.com/open-mmlab/mmdeploy/blob/26d40fe883c941a668bf7c309b168e4f01a6f6c2/mmdeploy/apis/pytorch2onnx.py#L87-L91

**Comment by RunningLeon** [comment]
Yes. It' deploy_cfg. However, `boder` is set to `None` in CenterNet config. Maybe we can ignore this argument.

**Comment by xd-HKPC** [comment]
Yes, thank you for your help. I solved it and exported CenterNet to tensorRT successfully. Parameters like `img_shape`, `scale_factor` and `border` in `img_metas` is related to `model.test.pipeline` the model config .  It will cause troubles if I applied `RandomCenterCropPad` in data transforms but not specify `crop_size`, since the `decode_heatmap` function in `centernet_head` requires padded border pixels to correct the bbox size.

Thank you again!

**Comment by RunningLeon** [comment]
> 

@xd-HKPC Hi, good to hear from you. If you have successfully supported deploy CenterNet with mmdeploy on TensorRT, we sincerely hope you could submit this feature to mmdeploy through a PR, which could be beneficial to other users in the community.

**Comment by xd-HKPC** [comment]
@RunningLeon Sure. However, I am still facing problems in test data augmentation. I cannot support the `RandomCenterCropPad` but it seems critical to CenterNet. I think I should add this support outside the model exportation. Without this data aug, mAP drops from 29.5 to 28.1. 

The results of tensorRT model in test.py are:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.281
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.446
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.291
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.086
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.293
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.484
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.423
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.423
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.423
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.150
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.456
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.696

**Comment by RunningLeon** [comment]
@xd-HKPC Thanks for your test results. MMDeploy does not support aug_test, we can compare results when both PyTorch model and TensorRT model use `simple_test`. What's mAP with no aug_test for PyTorch model? If it is aligned with TensorRT, then the model conversion is fine.
