### ISSUE TITLE
[Feature] EfficientNetCenterCrop didn't realize

### ISSUE THREAD

**Issue by yinfan98** [open-mmlab/mmdeploy#2370]
### Motivation

Unable to find Transform creator: EfficientNetCenterCrop. Available transforms: [("CenterCrop", 0), ("Collect", 0), ("Compose", 0), ("DefaultFormatBundle", 0), ("FormatShape", 0), ("ImageToTensor", 0), ("LetterResize", 0), ("Lift", 0), ("LoadImageFromFile", 0), ("Normalize", 0), ("Pad", 0), ("RescaleToHeight", 0), ("Resize", 0), ("ResizeOCR", 0), ("ShortScaleAspectJitter", 0), ("TenCrop", 0), ("ThreeCrop", 0), ("TopDownAffine", 0), ("TopDownGetBboxCenterScale", 0)]

**Comment by yinfan98** [comment]
I want to realize it and PR, are there some guide for contributor？

**Comment by RunningLeon** [comment]
@yinfan98 hi, you can refer to this https://github.com/open-mmlab/mmdeploy/blob/main/csrc/mmdeploy/preprocess/transform/center_crop.cpp.
