### ISSUE TITLE
[Docs] How to use the OpenVINO backend for inference in the Python SDK?

### ISSUE THREAD

**Issue by vicnoah** [open-mmlab/mmdeploy#2372]
### 📚 The doc issue

I couldn't find any examples or usage instructions on how to use the OpenVINO backend for inference in the documentation. I request additional documentation to supplement this information.

**Comment by RunningLeon** [comment]
hi, you could build mmdeploy sdk with openvino runtime.
Pls. refer to https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/openvino.html

**Comment by RunningLeon** [comment]
yes. you can give it a try.

**Comment by vicnoah** [comment]
openvino build failed.
`root@c23161b387b2:/mmdeploy/build#` make -j$(nproc) && make install
make: *** No rule to make target 'install'.  Stop.

**Comment by RunningLeon** [comment]
> openvino build failed. `root@c23161b387b2:/mmdeploy/build#` make -j$(nproc) && make install make: *** No rule to make target 'install'. Stop.

@vicnoah hi, what you script of running `cmake`?

**Comment by vicnoah** [comment]
> > openvino build failed. `root@c23161b387b2:/mmdeploy/build#` make -j$(nproc) && make install make: *** No rule to make target 'install'. Stop.
> 
> @vicnoah hi, what you script of running `cmake`?
This is my operation log, and I don't know what happened.

`root@d04cdd81f696:~/mmdeploy/build# cmake -DMMDEPLOY_TARGET_DEVICES='cpu' -DMMDEPLOY_TARGET_BACKENDS=openvino -DInferenceEngine_DIR=${InferenceEngine_DIR} ..
-- CMAKE_INSTALL_PREFIX: /root/mmdeploy/build/install
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    InferenceEngine_DIR


-- Build files have been written to: /root/mmdeploy/build
root@d04cdd81f696:~/mmdeploy/build# make -j$(nproc) && make install
make: *** No rule to make target 'install'.  Stop.`

**Comment by vicnoah** [comment]
> hi, is your openvino runtime installed correctly? you can refer to [this](https://github.com/open-mmlab/mmdeploy/blob/8478249ed8112444d2aef5e58cb57a80b045d5a6/docker/Base/Dockerfile#L113C4-L113C4) and suggest you use [docker image ](https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/build_from_docker.html) with everything is installed.

I installed OpenVINO following the instructions in the documentation, and I will try to compile it using Docker.

```Install python package
Install OpenVINO. It is recommended to use the installer or install using pip. Installation example using pip:

pip install openvino-dev[onnx]==2022.3.0
Download OpenVINO runtime for SDK (Optional)
If you want to use OpenVINO in SDK, you need install OpenVINO with install_guides. Take openvino==2022.3.0 as example:

wget https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.3/linux/l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64.tgz
tar xzf ./l_openvino_toolkit*.tgz
cd l_openvino*
export InferenceEngine_DIR=$pwd/runtime/cmake
bash ./install_dependencies/install_openvino_dependencies.sh```

**Comment by vicnoah** [comment]
> hi, is your openvino runtime installed correctly? you can refer to [this](https://github.com/open-mmlab/mmdeploy/blob/8478249ed8112444d2aef5e58cb57a80b045d5a6/docker/Base/Dockerfile#L113C4-L113C4) and suggest you use [docker image ](https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/build_from_docker.html) with everything is installed.

I have successfully executed the compilation now, but I encountered some issues. Let me describe my process.

**First Compilation (Failed):**

1. Use the official docker image environment and install the package using the following command:
   ```
   pip install openvino-dev[onnx]==2022.3.0
   ```

2. Set the environment variable:
   ```
   export InferenceEngine_DIR=/root/workspace/openvino_toolkit/runtime/cmake
   ```

3. Execute the OpenVINO installation script:
   ```
   bash ./install_dependencies/install_openvino_dependencies.sh
   ```

4. Enter the `mmdeploy` source code directory and delete the `build` folder and its contents.

5. Perform the compilation steps:
   ```
   mkdir -p build && cd build
   cmake -DMMDEPLOY_TARGET_DEVICES='cpu' -DMMDEPLOY_TARGET_BACKENDS=openvino -DInferenceEngine_DIR=${InferenceEngine_DIR} ..
   make -j$(nproc) && make install
   ```

**Second Compilation (Successful):**

1. Use the official docker image environment.

2. Set the environment variable:
   ```
   export InferenceEngine_DIR=/root/workspace/openvino_toolkit/runtime/cmake
   ```

3. Execute the OpenVINO installation script:
   ```
   bash ./install_dependencies/install_openvino_dependencies.sh
   ```

4. Enter the `mmdeploy/build` directory and perform the compilation steps (without deleting the existing files in the build directory):
   ```
   mkdir -p build && cd build
   cmake -DMMDEPLOY_TARGET_DEVICES='cpu' -DMMDEPLOY_TARGET_BACKENDS=openvino -DInferenceEngine_DIR=${InferenceEngine_DIR} ..
   make -j$(nproc) && make install
   ```

First Compilation (Failed):
```
root@2c91a6a7213a:~/workspace/mmdeploy/build# ls
CMakeCache.txt  CMakeFiles  Makefile  cmake_install.cmake  csrc
root@2c91a6a7213a:~/workspace/mmdeploy/build# make -j$(nproc) && make install
make: *** No rule to make target 'install'.  Stop.
root@2c91a6a7213a:~/workspace/mmdeploy/build#
```

Second Compilation (Successful):
```
root@413241f7d646:~/workspace/mmdeploy/build# ls
CMakeCache.txt               Makefile             demo                  lib.linux-x86_64-3.8
CMakeFiles                   bin                  install               temp.linux-x86_64-3.8
MMDeployConfig.cmake         cmake_install.cmake  install_manifest.txt
MMDeployConfigVersion.cmake  csrc                 lib
root@413241f7d646:~/workspace/mmdeploy/build# cmake -DMMDEPLOY_TARGET_DEVICES='cpu' -DMMDEPLOY_TARGET_BACKENDS=openvino -DInferenceEngine_DIR=${InferenceEngine_DIR} ..
-- CMAKE_INSTALL_PREFIX: /root/workspace/mmdeploy/build/install
-- Build spdlog: 1.10.0
-- Build type: Release
-- build codebase: mmcls
-- build codebase: mmdet
-- build codebase: mmseg
-- build codebase: mmocr
-- build codebase: mmedit
-- build codebase: mmpose
-- build codebase: mmrotate
-- build codebase: mmaction
-- pybind11 v2.9.0 dev1
-- Configuring done
-- Generating done
-- Build files have been written to: /root/workspace/mmdeploy/build
root@413241f7d646:~/workspace/mmdeploy/build# make -j$(nproc) && make install
[  1%] Building CXX object csrc/mmdeploy/core/spdlog/CMakeFiles/spdlog.dir/src/spdlog.cpp.o
```

**Comment by RunningLeon** [comment]
@vicnoah thanks for your detailed info. We'll reproduce it in a clean docker image and check if there's something wrong.

**Comment by RunningLeon** [comment]
@vicnoah hi, `MMDEPLOY_BUILD_SDK=OFF` by default, if you want to use mmdeploy-sdk, you should add this cmake argument.
```
mkdir -p build && cd build
cmake -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=openvino -DInferenceEngine_DIR=$InferenceEngine_DIR -DMMDEPLOY_BUILD_SDK=ON  .. 
make -j$(nproc) && make install
```
https://github.com/open-mmlab/mmdeploy/blob/bb031c698f34fb7b7ad8d098bf1f706bfe636b3e/CMakeLists.txt#L30-L40

**Comment by vicnoah** [comment]
> @vicnoah hi, `MMDEPLOY_BUILD_SDK=OFF` by default, if you want to use mmdeploy-sdk, you should add this cmake argument.
> 
> ```
> mkdir -p build && cd build
> cmake -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=openvino -DInferenceEngine_DIR=$InferenceEngine_DIR -DMMDEPLOY_BUILD_SDK=ON  .. 
> make -j$(nproc) && make install
> ```
> 
> https://github.com/open-mmlab/mmdeploy/blob/bb031c698f34fb7b7ad8d098bf1f706bfe636b3e/CMakeLists.txt#L30-L40

I have successfully compiled using the new method you provided. I greatly appreciate your help.

**Comment by RunningLeon** [comment]
hi, if you find mmdeploy useful, appreciate it if you could star and fork this repo.
