### ISSUE TITLE
[Bug] the wrong formal parameter in create_input function of mono_detection.py

### ISSUE THREAD

**Issue by RookieHuang** [open-mmlab/mmdeploy#2374]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi,I think there is a bug in the create_input function of mono_detection.py.
The mono_detection is used by mono3d detection algorithm without point cloud input,but the formal parameter of the create_input is pcd.I think it should be something like data information list.
Anyone could help?
Thanks!

### Reproduction

I establish my own mmdeploy config fcos3d.py by integrate the official configs as follow.
codebase_config = dict(
    type='mmdet3d', task='MonoDetection', model_type='end2end')
onnx_config = dict(
    type='onnx',
    export_params=True,
    keep_initializers_as_inputs=False,
    opset_version=11,
    save_file='end2end.onnx',
    input_names=['input'],
    output_names=['0','1','2','3','4','5'],
    input_shape=None,
    optimize=True)
backend_config = dict(type='onnxruntime')

### Environment

```Shell
python mmdeploy/tools/deploy.py mmdeploy/configs/mmdet3d/mono-detection/fcos3d.py configs/fcos3d/fcos3d_kitti.py work_dirs/fcos3d_kitti/epoch_48.pth demo/0.png --work-dir mmdeplopy_model
```

**Comment by RookieHuang** [comment]
https://github.com/open-mmlab/mmdeploy/blob/b7024ddfe5b435a7aa481f81a9449dc485fd71b4/mmdeploy/codebase/mmdet3d/deploy/mono_detection.py#L74

**Comment by RunningLeon** [comment]
@RookieHuang hi, fcos3d is not supported by [this doc](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet3d.html#supported-models). mono_deteciont is for SMOKE like and only support input files from kitti and nus datasets.

**Comment by artificialzjy** [comment]
> @RookieHuang hi, fcos3d is not supported by [this doc](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet3d.html#supported-models). Besides, mono_deteciont is for SMOKE like and only support input files from kitti and nus datasets.

But the input format is ".pcd", KITTI has not this format data
