### ISSUE TITLE
[Potential Bug] FAIL : Load model from end2end.onnx failed:Fatal error: mmdeploy:grid_sampler(-1) is not a registered function/op

### ISSUE THREAD

**Issue by hasanirtiza** [open-mmlab/mmdeploy#2377]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

Most probably it is not a bug and I have missed something. However, I am trying to convert mmsegmentation model mask2former (mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth ). I have successfully converted previously certain models, so my installation etc seems fine. The command I am ruining is the following

`python3 tools/deploy.py   configs/mmseg//segmentation_onnxruntime_static-512x512.py   ../mmsegmentation/configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py   ../mmsegmentation/checkpoints/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth   ../mmsegmentation/demo_images/a2.png   --work-dir ./work_dirs/mmseg-onnx   --device cpu   --dump-info`

It works just fine, I get the end2end.onnx model and the converted demo images of pytorch and onnx appear perfect. However when I try to load this model in onnxruntime I get the following error

" FAIL : Load model from end2end_semantic.onnx failed:Fatal error: mmdeploy:grid_sampler(-1) is not a registered function/op"

My onnxruntime version is 1.8.1
and I saw some bits which were not helpful in this previous version documentation.
https://mmcv.readthedocs.io/en/v1.3.10/deployment/onnxruntime_op.html

  

### Reproduction

python3 tools/deploy.py   configs/mmseg//segmentation_onnxruntime_static-512x512.py   ../mmsegmentation/configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py   ../mmsegmentation/checkpoints/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth   ../mmsegmentation/demo_images/a2.png   --work-dir ./work_dirs/mmseg-onnx   --device cpu   --dump-info

### Environment

```Shell
08/25 13:48:03 - mmengine - INFO - TorchVision: 0.15.2+cu117
08/25 13:48:03 - mmengine - INFO - OpenCV: 4.8.0
08/25 13:48:03 - mmengine - INFO - MMEngine: 0.8.4
08/25 13:48:03 - mmengine - INFO - MMCV: 2.0.1
08/25 13:48:03 - mmengine - INFO - MMCV Compiler: GCC 9.3
08/25 13:48:03 - mmengine - INFO - MMCV CUDA Compiler: 11.7
08/25 13:48:03 - mmengine - INFO - MMDeploy: 1.0.0rc3+a7e9be2
08/25 13:48:03 - mmengine - INFO -

08/25 13:48:03 - mmengine - INFO - **********Backend information**********
08/25 13:48:03 - mmengine - INFO - tensorrt:    None
08/25 13:48:03 - mmengine - INFO - ONNXRuntime: 1.8.1
08/25 13:48:03 - mmengine - INFO - ONNXRuntime-gpu:     None
08/25 13:48:03 - mmengine - INFO - ONNXRuntime custom ops:      Available
08/25 13:48:03 - mmengine - INFO - pplnn:       None
08/25 13:48:03 - mmengine - INFO - ncnn:        None
08/25 13:48:03 - mmengine - INFO - snpe:        None
08/25 13:48:03 - mmengine - INFO - openvino:    None
08/25 13:48:03 - mmengine - INFO - torchscript: 2.0.1
08/25 13:48:03 - mmengine - INFO - torchscript custom ops:      NotAvailable
08/25 13:48:04 - mmengine - INFO - rknn-toolkit:        None
08/25 13:48:04 - mmengine - INFO - rknn-toolkit2:       None
08/25 13:48:04 - mmengine - INFO - ascend:      None
08/25 13:48:04 - mmengine - INFO - coreml:      None
08/25 13:48:04 - mmengine - INFO - tvm: None
08/25 13:48:04 - mmengine - INFO -

08/25 13:48:04 - mmengine - INFO - **********Codebase information**********
08/25 13:48:04 - mmengine - INFO - mmdet:       3.1.0
08/25 13:48:04 - mmengine - INFO - mmseg:       1.1.1
08/25 13:48:04 - mmengine - INFO - mmcls:       None
08/25 13:48:04 - mmengine - INFO - mmocr:       None
08/25 13:48:04 - mmengine - INFO - mmedit:      None
08/25 13:48:04 - mmengine - INFO - mmdet3d:     None
08/25 13:48:04 - mmengine - INFO - mmpose:      None
08/25 13:48:04 - mmengine - INFO - mmrotate:    None
08/25 13:48:04 - mmengine - INFO - mmaction:    None
```

**Comment by RunningLeon** [comment]
@hasanirtiza hi, grid_sampler is a custom op for onnxruntime and you have to load the built custom lib `mmdeploy/lib/libmmdeploy_onnxruntime_ops.so`  in your onnxruntime inference code, just like here
https://github.com/open-mmlab/mmdeploy/blob/b7024ddfe5b435a7aa481f81a9449dc485fd71b4/mmdeploy/backend/onnxruntime/wrapper.py#L47

**Comment by hasanirtiza** [comment]
It works, thanks and just in case someone stumbles upon this, this exactly how I did it, after converting to onnx.

path = "./site-packages/mmdeploy/lib/libmmdeploy_onnxruntime_ops.so"
model_path =  "end2end-mask2former.onnx"
session_options = ort.SessionOptions()
session_options.register_custom_ops_library(path)
ort_session = ort.InferenceSession(model_path,session_options)`

**Comment by GeorgePearse** [comment]
Are there any other approaches to this? Trying to use it on an Arm machine, and the .so files aren't available (we'll have to build from source).

**Comment by hasanirtiza** [comment]
@GeorgePearse Appears building from source to be the most viable option in that case, at least to the best of my knowledge. Not 100% sure, but may be you can use those "popular" Arm-compatible docker images for this purpose (not confident if it will work at all).

**Comment by liyufan** [comment]
> Are there any other approaches to this? Trying to use it on an Arm machine, and the .so files aren't available (we'll have to build from source).

Same problem here, please let me know if you have any solution.

**Comment by GeorgePearse** [comment]
Still working on it / looking at workarounds.

**Comment by Fredrik00** [comment]
I built the custom ops for onnxruntime 1.15.0 and registered them with register_custom_ops_library.
Still, when I try tor run an ONNX exported model for dino I get:
`Fatal error: mmdeploy:grid_sampler(-1) is not a registered function/op`

Does anyone know the latest version of onnxruntime that works with custom ops (1.15.0 was the earliest availble for python 3.11.4)? Anyone else who had the same issue after registering the custom ops?
