### ISSUE TITLE
[Feature] EFFICIENTFORMER

### ISSUE THREAD

**Issue by azuryl** [open-mmlab/mmdeploy#2385]
### Motivation

It is pure ViT real-time model, EfficientFormer-L1, achieves 79.2% top-1 accuracy on ImageNet-1K with only 1.6 ms inference latency on iPhone 12 (compiled with CoreML), which runs as fast as MobileNetV2×1.4 (1.6 ms, 74.7% top-1), and our largest model, EfficientFormer-L7, obtains 83.3% accuracy with only 7.0 ms latency. They work proves that properly designed transformers can reach extremely low latency on mobile devices while maintaining high performanc

### Related resources

https://mmpretrain.readthedocs.io/zh_CN/latest/papers/efficientformer.html#how-to-use-it
mmpretrain have suppoerted it
https://github.com/snap-research/EfficientFormer

**Comment by RunningLeon** [comment]
hi, this model is supported according to this doc: https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmpretrain.html#supported-models.
