### ISSUE TITLE
[Bug] Inference time is unstable

### ISSUE THREAD

**Issue by gitleej** [open-mmlab/mmdeploy#2391]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I use mmdeploy csharp api to deploy my segmentation model. When continuous inference without interruption, the inference time is stable at 55 milliseconds.
When two images are inferred with a time interval of 100 ms, the inference time fluctuates between 60 ms and 100 ms.
When two images are inferred with a time interval of 200 ms, the inference time fluctuates between 60 ms and 200 ms, up to 300 ms.

### Reproduction

model: STDC2
API: MMDeploy CSharp

### Environment

```Shell
OS:Windows10
CUDA:11.2
TensorRT:8.4
```

**Comment by RunningLeon** [comment]
hi, profiling is tricky. Maybe you can monitor the usage of CPU and GPU on your machine.

**Comment by irexyc** [comment]
You can read there two issues

https: //github.com/NVIDIA/TensorRT/issues/2107
https: //github.com/NVIDIA/TensorRT/issues/2042

**Comment by gitleej** [comment]
> hi, profiling is tricky. Maybe you can monitor the usage of CPU and GPU on your machine.

https://zhuanlan.zhihu.com/p/619947091
This link helped me to solve my problem.

**Comment by gitleej** [comment]
> You can read there two issues
> 
> https: //github.com/[NVIDIA/TensorRT/issues/2107](https://github.com/NVIDIA/TensorRT/issues/2107) https: //github.com/[NVIDIA/TensorRT/issues/2042](https://github.com/NVIDIA/TensorRT/issues/2042)

thanks for your reply.
