### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by dino-illumix** [open-mmlab/mmdeploy#2393]
### 📚 The doc issue

How do I create an ONNX model in Channels Last format? 
mmsegmentation is giving me a model with input format (1, 3, 512, 512) and output format (1, 1, 512, 512) but I need (1, 512, 512, 3) (1, 512, 512, 1). I've tried setting the config parameters for the backbone to in_channels=(512, 512, 3) and data_format='channels_last) but I still get a .onnx model with channels first. There's no documentation on this and I'm not sure whether the problem is in the mmsegmentation training configuration or in the conversion to .onnx

**Comment by RunningLeon** [comment]
hi, 
first of all, pls. ask it in [mmsegmentation](https://github.com/open-mmlab/mmsegmentation/issues) for whether it supports model training with the channel in the last dim.

**Comment by dino-illumix** [comment]
Thanks. Have raised the same question on the mmsegmentation github page.
