### ISSUE TITLE
[Bug] By not providing "Findpplcv.cmake" in CMAKE_MODULE_PATH this project has   asked CMake to find a package configuration file provided by "pplcv", but   CMake did not find one.

### ISSUE THREAD

**Issue by facias914** [open-mmlab/mmdeploy#2395]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I want to compile SDK and Demos following this [doc](https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/01-how-to-build/linux-x86_64.md), but meeting an error.

I am sure I have built ppl.cv from source following this [doc](https://github.com/openppl-public/ppl.cv). But when I run this command,  it still got this error

### Reproduction

cmake .. 
-DCMAKE_CXX_COMPILER=g++-7     
-DMMDEPLOY_BUILD_SDK=ON     
-DMMDEPLOY_BUILD_EXAMPLES=ON     
-DMMDEPLOY_BUILD_SDK_PYTHON_API=ON     
-DMMDEPLOY_TARGET_DEVICES="cuda;cpu"     
-DMMDEPLOY_TARGET_BACKENDS=trt Dpplcv_DIR=/the/path/to/ppl.cv/cuda-build/install/lib/cmake/ppl 
-DTENSORRT_DIR=/the/path/to/TensorRT-8.6.0.12 
-DCUDNN_DIR=/the/path/to/cuda-11.6/include

### Environment

```Shell
export TENSORRT_DIR=/the/path/to/TensorRT-8.6.0.12
export LD_LIBRARY_PATH=$TENSORRT_DIR/lib:$LD_LIBRARY_PAT
export CUDNN_DIR=/the/path/to/cuda-11.6
export LD_LIBRARY_PATH=$CUDNN_DIR/lib:$LD_LIBRARY_PATH

export MMDEPLOY_DIR=/the/path/to/mmdeploy
export PPLCV_DIR=/the/path/to/ppl.cv
```

### Error traceback

```Shell
-- Check for working CUDA compiler: /usr/local/cuda-11.6/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Build TensorRT custom ops.
-- Found TensorRT headers at /home/facias/Downloads/TensorRT-8.6.0.12/include
-- Found TensorRT libs at /home/facias/Downloads/TensorRT-8.6.0.12/lib/libnvinfer.so;/home/facias/Downloads/TensorRT-8.6.0.12/lib/libnvinfer_plugin.so
-- Found TENSORRT: /home/facias/Downloads/TensorRT-8.6.0.12/include  
-- Found OpenCV: /usr/local/opencv (found version "3.4.12") 
-- Build spdlog: 1.10.0
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Build type: Release
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
CMake Error at csrc/mmdeploy/operation/cuda/CMakeLists.txt:7 (find_package):
  By not providing "Findpplcv.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pplcv", but
  CMake did not find one.

  Could not find a package configuration file provided by "pplcv" with any of
  the following names:

    pplcvConfig.cmake
    pplcv-config.cmake

  Add the installation prefix of "pplcv" to CMAKE_PREFIX_PATH or set
  "pplcv_DIR" to a directory containing one of the above files.  If "pplcv"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

**Comment by facias914** [comment]
This problem has been sloved.
But I met another question. My mmdeploy folder does not have the /lib/cmake/MMdeploy path. And the error is :

Could not find a package configuration file provided by "MMDeploy" with any
  of the following names:

    MMDeployConfig.cmake
    mmdeploy-config.cmake

**Comment by rookie1999** [comment]
> This problem has been sloved. But I met another question. My mmdeploy folder does not have the /lib/cmake/MMdeploy path. And the error is :
> 
> Could not find a package configuration file provided by "MMDeploy" with any of the following names:
> 
> ```
> MMDeployConfig.cmake
> mmdeploy-config.cmake
> ```

How do you fix the problem, I have met the same problem as you when building mmdeploy using pplcv.
