### ISSUE TITLE
[Bug] How can I convert a model with two inputs

### ISSUE THREAD

**Issue by facias914** [open-mmlab/mmdeploy#2397]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I modified a model and changed its input interface from one input image to accept two input images at the same time. The model is trained and everything works fine. I now want to convert it to onnx and trt format, but it seems that the deploy.py file does not support this.

One thing that needs to be reminded is that when I transformed the model, I also modified the data processing part, such as random rotation operations, etc., so that two images can be received and processed at the same time. This should affect model conversion.

Also I noticed that the deploy.py file can only accept one image as input at a time

### Reproduction

python tools/deploy.py ......

### Environment

```Shell
markdown                  3.4.4                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
matplotlib                3.7.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mmcv                      2.0.1                    pypi_0    pypi
mmdeploy                  1.2.0                     dev_0    <develop>
mmdet                     3.1.0                     dev_0    <develop>
mmengine                  0.8.4                    pypi_0    pypi
```

**Comment by RunningLeon** [comment]
@facias914 hi, mmdeploy supports torch2onnx with multi-inputs and multi-outputs. Which model do you want to deploy?

**Comment by facias914** [comment]
> @facias914 hi, mmdeploy supports torch2onnx with multi-inputs and multi-outputs. Which model from which codebase do you want to deploy?

I modified  the RTMDet-Rotated Model  and changed its input interface from one input image to accept two input images at the same time. The codebase should be rotated_detector. 

Meanwhile, I also modified the data loader and data augmentation pipline so that they can accept and process two input images at the same time.

**Comment by RunningLeon** [comment]
hi, 
1. you need to make sure the model.forward function could accept two tensor inputs. For instance, we add this [rewrite](https://github.com/open-mmlab/mmdeploy/blob/5479c8774f5b88d7ed9d399d4e305cb42cc2e73a/mmdeploy/codebase/mmdet3d/models/base.py#L12) to let mmdet3d models accept three inputs.
2. you need to change the input_names in deploy config. Could take this [config ](https://github.com/open-mmlab/mmdeploy/blob/5479c8774f5b88d7ed9d399d4e305cb42cc2e73a/configs/mmdet3d/voxel-detection/voxel-detection_static.py#L5C32-L5C32)as an example. 
3. You need to modify the [create_input ](https://github.com/open-mmlab/mmdeploy/blob/5479c8774f5b88d7ed9d399d4e305cb42cc2e73a/mmdeploy/codebase/mmrotate/deploy/rotated_detection.py#L236C34-L236C34) . Refer to [this](https://github.com/open-mmlab/mmdeploy/blob/5479c8774f5b88d7ed9d399d4e305cb42cc2e73a/mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py#L119).
4. deploy.py only accept one image by far, maybe you can create two images in `create_input` function  as a temporary workaround

**Comment by facias914** [comment]
Thanks! I convert the model to trt successfully!
By the way, I don't yet have a thorough understanding of the principles of converting models to onnx and trt formats. I would like to ask if the trt format file I converted can be run directly without being in the mmdeploy environment. For example, I want to deploy the trt file to another device, the tensorrt version is the same, just without the mmdeploy environment.
That is, after the trt file is successfully converted and run successfully, can the trt file be run directly using NVIDIA's API interface?

**Comment by RunningLeon** [comment]
hi, you can run trt engine without mmdeploy. However, if your model has custom trt plugins from mmdeploy, you need to load it.
