### ISSUE TITLE
[Feature] Reduce unnecessary dependencies for backend inference

### ISSUE THREAD

**Issue by cosimo17** [open-mmlab/mmdeploy#2400]
### Motivation

The sample code about backend inference in the mmdeploy doc page always import torch first.
I think this is not necessary for some backends such as onnxruntime and tensorrt.
Please consider to remove the unnecessary dependencies like this.

**Comment by RunningLeon** [comment]
hi, you can use mmdeploy sdk for inference, which has python api.

**Comment by cosimo17** [comment]
> hi, you can use mmdeploy sdk for inference, which has python api.

Thanks for your quick replay. 
Is the SDK a built-in inference engine? What is the difference between SDK and backend inference?

**Comment by RunningLeon** [comment]
could refer to this doc: https://mmdeploy.readthedocs.io/en/latest/get_started.html#introduction

**Comment by cosimo17** [comment]
> could refer to this doc: https://mmdeploy.readthedocs.io/en/latest/get_started.html#introduction

I want to create multiple model instance with multiprocessing, but it seems sdk does not support this feature.
The following code will raise error

```from mmdeploy_runtime import Classifier
from multiprocessing import Process
def work():
    model = Classifier(xxxxxx)

for i in range(2):
    p = Process(target=work)
    p.start()
```

**Comment by RunningLeon** [comment]
@irexyc hi, could you take a look at this issue? 

> > could refer to this doc: https://mmdeploy.readthedocs.io/en/latest/get_started.html#introduction
> 
> I want to create multiple model instance with multiprocessing, but it seems sdk does not support this feature. The following code will raise error. If I use onnxruntime directly, it works well.
> 
> ```
> from mmdeploy_runtime import Classifier
> from multiprocessing import Process
> def work():
>     model = Classifier(xxxxxx)
> 
> for i in range(2):
>     p = Process(target=work)
>     p.start()
> ```

**Comment by irexyc** [comment]
@cosimo17 

Could you use sdk like this ?

``` python
from mmdeploy_runtime import Classifier
from multiprocessing import Process
import multiprocessing as mp
import cv2

def work():
    model = Classifier('/model/mmcls', 'cuda')
    img = cv2.imread('/model/mmcls/demo.jpg')
    while True:
      res = model(img)
      print(res)


def main():
    proc = []
    for i in range(2):
        p = Process(target=work)
        p.start()
        proc.append(p)

    for p in proc:
        p.join()

if __name__ == '__main__':
    # https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
    mp.set_start_method('spawn') # the default value if fork on linux 
    main()
```

**Comment by cosimo17** [comment]
> @cosimo17
> 
> Could you use sdk like this ?
> 
> ```python
> from mmdeploy_runtime import Classifier
> from multiprocessing import Process
> import multiprocessing as mp
> import cv2
> 
> def work():
>     model = Classifier('/model/mmcls', 'cuda')
>     img = cv2.imread('/model/mmcls/demo.jpg')
>     while True:
>       res = model(img)
>       print(res)
> 
> 
> def main():
>     proc = []
>     for i in range(2):
>         p = Process(target=work)
>         p.start()
>         proc.append(p)
> 
>     for p in proc:
>         p.join()
> 
> if __name__ == '__main__':
>     # https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
>     mp.set_start_method('spawn') # the default value is fork on linux 
>     main()
> ```

The error missed, but it still does not work. The program finished without error but the code after the model instantiation is not executed.

**Comment by irexyc** [comment]
之前的问题是因为Process linux下会默认用fork的形式启动进程，而import mmdeploy_runtime 会自动cuda初始化，但是cuda
context没办法在多个进程中共享。

解决的办法一个是按照我上面的修改，另一个是不要在全局import mmdeploy_runtime在每个进程内单独import。我这边测试都是可以的。

你最后说到的代码没办法运行，我不了解是什么现象，程序卡主？device改成cpu是否正常？不用multiprocessing知否正常？

**Comment by cosimo17** [comment]
> 之前的问题是因为Process linux下会默认用fork的形式启动进程，而import mmdeploy_runtime 会自动cuda初始化，但是cuda context没办法在多个进程中共享。
> 
> 解决的办法一个是按照我上面的修改，另一个是不要在全局import mmdeploy_runtime在每个进程内单独import。我这边测试都是可以的。
> 
> 你最后说到的代码没办法运行，我不了解是什么现象，程序卡主？device改成cpu是否正常？不用multiprocessing知否正常？

没有卡住。现象就是创建模型后运行推理，打印结果，什么都没有发生，在加载模型后执行个最近的的print语句也不会执行。程序直接就结束了，也没有报错信息。通用的代码，如果把device改成cpu，就会打印出推理结果。不要multiprocessing，单进程单个模型的话，是可以工作的

**Comment by irexyc** [comment]
看起来直接退出了？你可以试试把from mmdeploy_runtime import Classifier 放到 work()里面

不用multiprocess，单进程单模型能成功是用的cuda么？

**Comment by cosimo17** [comment]
> 看起来直接退出了？你可以试试把from mmdeploy_runtime import Classifier 放到 work()里面
> 
> 不用multiprocess，单进程单模型能成功是用的cuda么？

更换mmdeploy版本后，放在work内import，多进程也可以正常工作了。我发现问题出现在mmdeploy 1.3.0上，降级到1.2.0上后才能正常工作，在1.3.0上单进程单模型也会报错Segmentation fault
