### ISSUE TITLE
[Bug] jetson安装 C/C++ Inference SDK出现Makefile:132: recipe for target 'all' failed

### ISSUE THREAD

**Issue by 564192234** [open-mmlab/mmdeploy#2404]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

python3.6，cuda10.2，jetpack4.5，跟着文档走，在安装 C/C++ Inference SDK的make -j$(nproc) && make install出现了Makefile:132: recipe for target 'all' failed问题。

### Reproduction

mkdir -p build && cd build
cmake .. \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
    -DMMDEPLOY_TARGET_BACKENDS="trt" \
    -DMMDEPLOY_CODEBASES=all \
    -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl
make -j$(nproc) && make install

### Environment

```Shell
2023-09-05 14:41:37,084 - mmdeploy - INFO - 

2023-09-05 14:41:37,084 - mmdeploy - INFO - **********Environmental information**********
2023-09-05 14:41:42,293 - mmdeploy - INFO - sys.platform: linux
2023-09-05 14:41:42,294 - mmdeploy - INFO - Python: 3.6.7 | packaged by conda-forge | (default, Feb 24 2019, 02:17:42) [GCC 7.3.0]
2023-09-05 14:41:42,295 - mmdeploy - INFO - CUDA available: True
2023-09-05 14:41:42,295 - mmdeploy - INFO - GPU 0: Xavier
2023-09-05 14:41:42,295 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2023-09-05 14:41:42,296 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.89
2023-09-05 14:41:42,296 - mmdeploy - INFO - GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
2023-09-05 14:41:42,296 - mmdeploy - INFO - PyTorch: 1.10.0
2023-09-05 14:41:42,296 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.0
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=8.0.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, 

2023-09-05 14:41:42,297 - mmdeploy - INFO - OpenCV: 4.8.0
2023-09-05 14:41:42,297 - mmdeploy - INFO - MMCV: 1.4.0
2023-09-05 14:41:42,297 - mmdeploy - INFO - MMCV Compiler: n/a
2023-09-05 14:41:42,297 - mmdeploy - INFO - MMCV CUDA Compiler: n/a
2023-09-05 14:41:42,297 - mmdeploy - INFO - MMDeploy: 0.5.0+4335313
2023-09-05 14:41:42,298 - mmdeploy - INFO - 

2023-09-05 14:41:42,298 - mmdeploy - INFO - **********Backend information**********
2023-09-05 14:41:45,225 - mmdeploy - INFO - onnxruntime: None	ops_is_avaliable : False
2023-09-05 14:41:45,338 - mmdeploy - INFO - tensorrt: 7.1.3.0	ops_is_avaliable : True
2023-09-05 14:41:45,408 - mmdeploy - INFO - ncnn: None	ops_is_avaliable : False
2023-09-05 14:41:45,411 - mmdeploy - INFO - pplnn_is_avaliable: False
2023-09-05 14:41:45,415 - mmdeploy - INFO - openvino_is_avaliable: False
2023-09-05 14:41:45,416 - mmdeploy - INFO - 

2023-09-05 14:41:45,416 - mmdeploy - INFO - **********Codebase information**********
2023-09-05 14:41:45,420 - mmdeploy - INFO - mmdet:	None
2023-09-05 14:41:45,421 - mmdeploy - INFO - mmseg:	None
2023-09-05 14:41:45,421 - mmdeploy - INFO - mmcls:	None
2023-09-05 14:41:45,421 - mmdeploy - INFO - mmocr:	None
2023-09-05 14:41:45,421 - mmdeploy - INFO - mmedit:	None
2023-09-05 14:41:45,421 - mmdeploy - INFO - mmdet3d:	None
2023-09-05 14:41:45,422 - mmdeploy - INFO - mmpose:	None
2023-09-05 14:41:45,422 - mmdeploy - INFO - mmrotate:	None
```

### Error traceback

```Shell
[  0%] Building CXX object csrc/core/spdlog/CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
[  2%] Building CXX object csrc/core/spdlog/CMakeFiles/spdlog.dir/src/spdlog.cpp.o
[  2%] Building CXX object csrc/core/spdlog/CMakeFiles/spdlog.dir/src/async.cpp.o
[  3%] Building CXX object csrc/core/spdlog/CMakeFiles/spdlog.dir/src/color_sinks.cpp.o
[  3%] Building CXX object csrc/core/spdlog/CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
[  4%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/trt_batched_nms.cpp.o
[  4%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_rotated_nms/trt_batched_rotated_nms.cpp.o
[  4%] Building CXX object csrc/core/spdlog/CMakeFiles/spdlog.dir/src/cfg.cpp.o
[  5%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/bicubic_interpolate/trt_bicubic_interpolate.cpp.o
[  5%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/bicubic_interpolate/trt_bicubic_interpolate_kernel.cu.o
[  6%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/allClassNMS.cu.o
[  7%] Building CXX object csrc/core/spdlog/CMakeFiles/spdlog.dir/src/fmt.cpp.o
[  8%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/allClassRotatedNMS.cu.o
[  8%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/batched_nms_kernel.cpp.o
[  9%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/gatherNMSOutputs.cu.o
[  9%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/kernel.cu.o
[ 10%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/permuteData.cu.o
[ 11%] Linking CXX static library ../../../lib/libspdlog.a
[ 11%] Built target spdlog
[ 11%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/device_impl.cpp.o
[ 11%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerClass.cu.o
[ 12%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerImage.cu.o
[ 13%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/logger.cpp.o
[ 13%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/graph.cpp.o
[ 13%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/trt_cuda_helper.cu.o
[ 14%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/deform_conv/trt_deform_conv.cpp.o
[ 15%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/deform_conv/trt_deform_conv_kernel.cu.o
[ 16%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/mat.cpp.o
[ 16%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/model.cpp.o
[ 17%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/module.cpp.o
[ 17%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_sampler/trt_grid_sampler.cpp.o
[ 18%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/net.cpp.o
[ 19%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_sampler/trt_grid_sampler_kernel.cu.o
[ 19%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/operator.cpp.o
[ 19%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/instance_norm/trt_instance_norm.cpp.o
[ 20%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/status_code.cpp.o
[ 21%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/modulated_deform_conv/trt_modulated_deform_conv.cpp.o
[ 21%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/tensor.cpp.o
[ 21%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/modulated_deform_conv/trt_modulated_deform_conv_kernel.cu.o
[ 22%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/registry.cpp.o
[ 22%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/utils/device_utils.cpp.o
[ 23%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/utils/formatter.cpp.o
[ 24%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/multi_level_roi_align/trt_multi_level_roi_align.cpp.o
[ 24%] Building CXX object csrc/core/CMakeFiles/mmdeploy_core.dir/utils/stacktrace.cpp.o
[ 24%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/multi_level_roi_align/trt_multi_level_roi_align_kernel.cu.o
[ 25%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/roi_align/trt_roi_align.cpp.o
[ 25%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/roi_align/trt_roi_align_kernel.cu.o
[ 26%] Building CXX object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/scatternd/trt_scatternd.cpp.o
[ 27%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/scatternd/trt_scatternd_kernel.cu.o
In file included from /home/nvidia/process_inspection/mmdeploy/csrc/archive/json_archive.h:8:0,
                 from /home/nvidia/process_inspection/mmdeploy/csrc/core/utils/formatter.cpp:5:
/home/nvidia/process_inspection/mmdeploy/third_party/json/json.hpp: In member function ‘void nlohmann::detail::serializer<BasicJsonType>::dump_escaped(const string_t&, bool) [with BasicJsonType = nlohmann::basic_json<>]’:
/home/nvidia/process_inspection/mmdeploy/third_party/json/json.hpp:15817:10: warning: ‘%.2X’ directive output may be truncated writing between 2 and 8 bytes into a region of size 3 [-Wformat-truncation=]
     void dump_escaped(const string_t& s, const bool ensure_ascii)
          ^~~~~~~~~~~~
/home/nvidia/process_inspection/mmdeploy/third_party/json/json.hpp:15817:10: note: directive argument in the range [0, 2147483647]
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/ostream:38,
                 from /home/nvidia/process_inspection/mmdeploy/csrc/core/utils/formatter.h:6,
                 from /home/nvidia/process_inspection/mmdeploy/csrc/core/utils/formatter.cpp:3:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 3 and 9 bytes into a destination of size 3
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
[ 28%] Linking CXX shared library ../../lib/libmmdeploy_core.so
[ 28%] Built target mmdeploy_core
[ 28%] Building CXX object csrc/execution/CMakeFiles/mmdeploy_execution.dir/schedulers/schedulers.cpp.o
[ 28%] Building CXX object csrc/utils/opencv/CMakeFiles/mmdeploy_opencv_utils.dir/opencv_utils.cpp.o
[ 29%] Building CXX object csrc/device/cpu/CMakeFiles/mmdeploy_cpu_device.dir/cpu_device.cpp.o
[ 30%] Building CXX object csrc/device/cuda/CMakeFiles/mmdeploy_cuda_device.dir/cuda_device.cpp.o
[ 30%] Building CUDA object csrc/device/cuda/CMakeFiles/mmdeploy_cuda_device.dir/cuda_builtin_kernels.cu.o
[ 30%] Built target mmdeploy_tensorrt_ops_obj
[ 30%] Building CXX object csrc/graph/CMakeFiles/mmdeploy_graph.dir/common.cpp.o
[ 30%] Linking CXX shared library ../../../lib/libmmdeploy_cpu_device.so
[ 30%] Built target mmdeploy_cpu_device
[ 31%] Building CXX object csrc/model/CMakeFiles/mmdeploy_directory_model.dir/directory_model_impl.cpp.o
[ 32%] Linking CXX shared library ../../lib/libmmdeploy_execution.so
[ 32%] Built target mmdeploy_execution
[ 32%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/collect.cpp.o
[ 33%] Linking CXX shared library ../../../lib/libmmdeploy_opencv_utils.so
[ 33%] Built target mmdeploy_opencv_utils
[ 34%] Building CXX object csrc/graph/CMakeFiles/mmdeploy_graph.dir/task.cpp.o
[ 34%] Building CXX object csrc/graph/CMakeFiles/mmdeploy_graph.dir/pipeline.cpp.o
[ 35%] Linking CXX shared library ../../../lib/libmmdeploy_cuda_device.so
[ 35%] Built target mmdeploy_cuda_device
[ 36%] Building CXX object csrc/graph/CMakeFiles/mmdeploy_graph.dir/inference.cpp.o
[ 37%] Building CXX object csrc/net/CMakeFiles/mmdeploy_net_module.dir/net_module.cpp.o
[ 38%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/compose.cpp.o
[ 39%] Linking CXX shared library ../../lib/libmmdeploy_directory_model.so
[ 39%] Built target mmdeploy_directory_model
[ 39%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/crop.cpp.o
[ 40%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/image2tensor.cpp.o
[ 41%] Building CXX object csrc/graph/CMakeFiles/mmdeploy_graph.dir/flatten.cpp.o
[ 42%] Linking CXX shared library ../../lib/libmmdeploy_net_module.so
[ 42%] Built target mmdeploy_net_module
[ 43%] Building CXX object csrc/net/trt/CMakeFiles/mmdeploy_trt_net.dir/trt_net.cpp.o
[ 43%] Building CXX object csrc/graph/CMakeFiles/mmdeploy_graph.dir/unflatten.cpp.o
/home/nvidia/process_inspection/mmdeploy/csrc/net/trt/trt_net.cpp: In member function ‘virtual mmdeploy::Result<void> mmdeploy::TRTNet::Init(const mmdeploy::Value&)’:
/home/nvidia/process_inspection/mmdeploy/csrc/net/trt/trt_net.cpp:153:13: error: ‘class nvinfer1::IExecutionContext’ has no member named ‘setOptimizationProfileAsync’; did you mean ‘setOptimizationProfile’?
   context_->setOptimizationProfileAsync(0, static_cast<cudaStream_t>(stream_.GetNative()));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
             setOptimizationProfile
Scanning dependencies of target mmdeploy_mmcls
[ 43%] Building CXX object csrc/codebase/mmcls/CMakeFiles/mmdeploy_mmcls.dir/linear_cls.cpp.o
csrc/net/trt/CMakeFiles/mmdeploy_trt_net.dir/build.make:65: recipe for target 'csrc/net/trt/CMakeFiles/mmdeploy_trt_net.dir/trt_net.cpp.o' failed
make[2]: *** [csrc/net/trt/CMakeFiles/mmdeploy_trt_net.dir/trt_net.cpp.o] Error 1
CMakeFiles/Makefile2:1193: recipe for target 'csrc/net/trt/CMakeFiles/mmdeploy_trt_net.dir/all' failed
make[1]: *** [csrc/net/trt/CMakeFiles/mmdeploy_trt_net.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 44%] Building CXX object csrc/codebase/mmcls/CMakeFiles/mmdeploy_mmcls.dir/mmcls.cpp.o
[ 45%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/default_format_bundle.cpp.o
[ 45%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/load.cpp.o
[ 46%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/normalize.cpp.o
[ 47%] Linking CXX shared library ../../lib/libmmdeploy_graph.so
[ 47%] Built target mmdeploy_graph
[ 47%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/pad.cpp.o
[ 48%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/resize.cpp.o
[ 48%] Linking CXX shared library ../../../lib/libmmdeploy_mmcls.so
[ 48%] Built target mmdeploy_mmcls
[ 48%] Building CXX object csrc/preprocess/transform/CMakeFiles/mmdeploy_transform.dir/transform.cpp.o
[ 49%] Linking CXX shared library ../../../lib/libmmdeploy_transform.so
[ 49%] Built target mmdeploy_transform
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by irexyc** [comment]
你的tensorrt的版本应该小于7.2 tensorrt 7.1. 你可以参考这个issue来改一下代码应该就可以编译了 https://github.com/open-mmlab/mmdeploy/issues/114 但是有反馈精度可能对不齐pytorch，你可以先测试一下，我们目前没有设备来验证。

**Comment by irexyc** [comment]
> [ 43%] Building CXX object csrc/graph/CMakeFiles/mmdeploy_graph.dir/unflatten.cpp.o
/home/nvidia/process_inspection/mmdeploy/csrc/net/trt/trt_net.cpp: In member function ‘virtual mmdeploy::Result<void> mmdeploy::TRTNet::Init(const mmdeploy::Value&)’:
/home/nvidia/process_inspection/mmdeploy/csrc/net/trt/trt_net.cpp:153:13: error: ‘class nvinfer1::IExecutionContext’ has no member named ‘setOptimizationProfileAsync’; did you mean ‘setOptimizationProfile’?
   context_->setOptimizationProfileAsync(0, static_cast<cudaStream_t>(stream_.GetNative()));


这句话tensorrt小于7.2的话是没有的，
context_->setOptimizationProfileAsync(0, static_cast<cudaStream_t>(stream_.GetNative()));

114 把这句话改成了
context_->setOptimizationProfile(0);

**Comment by 564192234** [comment]
我按照您说的去做了，后面还额外改了几个，例如：/home/nvidia/process_inspection/mmdeploy/csrc/preprocess/cuda/pad_impl.cpp:24:71: error: ‘BORDER_TYPE_CONSTANT’ is not a member of ‘ppl::cv’
     map<string, ppl::cv::BorderType> border_map{{"constant", ppl::cv::BORDER_TYPE_CONSTANT},
                                                                       ^~~~~~~~~~~~~~~~~~~~
/home/nvidia/process_inspection/mmdeploy/csrc/preprocess/cuda/pad_impl.cpp:24:71: note: suggested alternative: ‘BORDER_CONSTANT’
     map<string, ppl::cv::BorderType> border_map{{"constant", ppl::cv::BORDER_TYPE_CONSTANT},
                                                                       ^~~~~~~~~~~~~~~~~~~~
                                                                       BORDER_CONSTANT
/home/nvidia/process_inspection/mmdeploy/csrc/preprocess/cuda/pad_impl.cpp:25:67: error: ‘BORDER_TYPE_REPLICATE’ is not a member of ‘ppl::cv’
                                                 {"edge", ppl::cv::BORDER_TYPE_REPLICATE},
                                                                   ^~~~~~~~~~~~~~~~~~~~~，成功编译了。
///////////////////////////
但是我碰到了一个新问题，我的jetpack版本是4.5配套的python是3.6.，tensorrt版本是7.1.3，在安装的时候就注意到了只能安装mmdeploy不能安装mmrotate，转换模型我选择在linux_x86上进行，他的tensorrt版本是8.2.3.0。转换成功以后，我把转换的engine、json文件拷贝到jetson上运行python demo/python/rotated_object_detection.py ../try_mmdeploy ../try_mmdeploy/output_image2126.jpg 出现了如下的报错，我改如何解决，谢谢：
[2023-09-06 10:05:07.697] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
[2023-09-06 10:05:10.772] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "image"
  ],
  "name": "mmrotate",
  "output": [
    "det"
  ],
  "params": {
    "model": "../try_mmdeploy"
  },
  "type": "Inference"
}
[2023-09-06 10:05:10.773] [mmdeploy] [info] [model.cpp:38] DirectoryModel successfully load sdk model ../try_mmdeploy
[2023-09-06 10:05:10.774] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "fuse_transform": false,
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "sha256": "83ba9eb66901a32e1fe5ebcff0a6375706597472e185e1d94aee2043a7399d3b",
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "size": [
        1024,
        1024
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "type": "DefaultFormatBundle"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "img_shape",
        "flip_direction",
        "ori_filename",
        "filename",
        "scale_factor",
        "pad_shape",
        "flip",
        "ori_shape",
        "img_norm_cfg",
        "valid_ratio"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2023-09-06 10:05:10.774] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "fuse_transform": false,
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "sha256": "83ba9eb66901a32e1fe5ebcff0a6375706597472e185e1d94aee2043a7399d3b",
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "size": [
        1024,
        1024
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "type": "DefaultFormatBundle"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "img_shape",
        "flip_direction",
        "ori_filename",
        "filename",
        "scale_factor",
        "pad_shape",
        "flip",
        "ori_shape",
        "img_norm_cfg",
        "valid_ratio"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2023-09-06 10:05:10.775] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "rotatedretinanet",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}
[2023-09-06 10:05:10.775] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "rotatedretinanet",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}
[2023-09-06 10:05:10.775] [mmdeploy] [info] [cuda_device.cpp:61] Default CUDA allocator initialized
[2023-09-06 10:05:19.153] [mmdeploy] [error] [trt_net.cpp:28] TRTNet: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[2023-09-06 10:05:19.157] [mmdeploy] [error] [trt_net.cpp:28] TRTNet: INVALID_STATE: std::exception
[2023-09-06 10:05:19.157] [mmdeploy] [error] [trt_net.cpp:28] TRTNet: INVALID_CONFIG: Deserialize the cuda engine failed.
[2023-09-06 10:05:19.158] [mmdeploy] [error] [trt_net.cpp:75] failed to deserialize TRT CUDA engine
[2023-09-06 10:05:19.247] [mmdeploy] [error] [task.cpp:67] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "rotatedretinanet",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}
[2023-09-06 10:05:19.247] [mmdeploy] [error] [pipeline.cpp:146] could not create rotatedretinanet: Task
[2023-09-06 10:05:19.248] [mmdeploy] [error] [pipeline.cpp:160] error parsing config: unknown (6) @ /home/nvidia/process_inspection/mmdeploy/csrc/graph/pipeline.cpp:147
[2023-09-06 10:05:19.248] [mmdeploy] [error] [rotated_detector.cpp:58] exception caught: unknown (6) @ /home/nvidia/process_inspection/mmdeploy/csrc/graph/pipeline.cpp:161
Traceback (most recent call last):
  File "demo/python/rotated_object_detection.py", line 51, in <module>
    main()
  File "demo/python/rotated_object_detection.py", line 26, in main
    detector = RotatedDetector(args.model_path, args.device_name, 0)
RuntimeError: failed to create rotated detector

**Comment by irexyc** [comment]
trt的模型要想在别的机器用，需要 1.设备架构相同(比如都是图灵架构) 2.trt版本一致。你在其他设备上转的模型这两点都不满足，显然不能拿来用。

关于mm系列python pacakge的安装。需要你从源码编译，编译的时候去掉setup.py里面对于python >= 3.7的限制。你可能会遇到一些问题，可以参考一些issue。

或者看看能不能升级一下jetpack的版本，python 3.6确实很不方便

**Comment by 564192234** [comment]
好的，我会尝试将jetpack升级到5.0配合python3.8使用。我将在linux_x86训练我自己的mmrotate模型，在jeston将pth转为trt，并在jeston上部署，应该是没有问题的吧。请问有什么需要注意的，谢谢。

**Comment by irexyc** [comment]
没有问题，也可以用一下这个平台 https://platform.openmmlab.com/deploee
jetsonorin 装的是 jetpack5.1.2

**Comment by 564192234** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/73697191/a9d6146d-80fb-4fc7-ad07-9fc36ce7de13)
我用的是mmrotate0.3.4的版本训练的，转换也需要用mmdeploy0.x的版本，是不是https://platform.openmmlab.com/deploee 平台就不太可用，还是能够兼容mmrotate的版本呢

**Comment by 564192234** [comment]
好的，谢谢
