### ISSUE TITLE
An error is reported when calling the converted onnx format model for inference

### ISSUE THREAD

**Issue by PlutoNov** [open-mmlab/mmdeploy#2408]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

My training uses 4-band remote sensing images, and both training and inference can be done with pytorch, but after switching to onnx, an error is reported when I use mmdeploy_runtime for inference.

### Reproduction

import os
import numpy as np
import cv2
from tqdm import tqdm
import rasterio as rio
from mmseg.apis import init_model, inference_model, show_result_pyplot
import mmcv
from rasterio import windows
import matplotlib.pyplot as plt
from itertools import product
import time

from mmdeploy_runtime import Segmentor

def split_image(image_path, tile_size):
    """
    将图像分割为指定大小的小图。
    :param image_path: 要分割的图像的路径。
    :param tile_size: 小图的大小（以像素为单位）。
    :return: 一个包含所有小图数据的列表。
    """
    tiles = []
    with rio.open(image_path) as inds:
        nols, nrows = inds.meta['width'], inds.meta['height']
        total_meta = inds.meta.copy()
        offsets = product(range(0, nols, tile_size), range(0, nrows, tile_size))
        splitlen = len(range(0, nrows, tile_size))
        big_window = windows.Window(col_off=0, row_off=0, width=nols, height=nrows)
        # i = 1
        for col_off, row_off in offsets:
            # print('col_off is ',col_off)
            # print('row_off is ',row_off)
            window = windows.Window(col_off=col_off, row_off=row_off, width=tile_size, height=tile_size).intersection(big_window)
            transform = windows.transform(window, inds.transform)
            meta = inds.meta.copy()
            meta['transform'] = transform
            meta['width'], meta['height'] = window.width, window.height
            print('tile shape is ',inds.read(window=window).shape)
            title = inds.read(window=window)
            title_4bands = np.einsum('ijk->jki', title)
            tiles.append(title)
            
            # print('------------'+str(i)+'----------------')
            # i += 1
    return tiles,splitlen,total_meta

def join_image(tiles,splitlen,meta,output_path):
    axis_y_merge = []
    for num,tile in enumerate(tiles):
        if (num+1) % splitlen == 0:
            temp_tiles_data = tiles[(num-(splitlen-1)):(num+1)]
            print(len(temp_tiles_data))
            axis_y_merge.append(np.concatenate(temp_tiles_data,axis=1))
            
    print(len(axis_y_merge))
    big_merge = np.concatenate(axis_y_merge,axis=2)
    # big_merge = big_merge[:3]
    print(big_merge.shape)
    meta.update(count=big_merge.shape[0])
    with rio.open(output_path,'w',**meta) as outds:
        outds.write(big_merge)

def process_single_img(img_path,output_path, save=True):
    opacity = 0.3
    # img_bgr = cv2.imread(img_path)
    # with rasterio.open(img_path) as src:
    #     img = src.read()
    #     img_4bands = np.einsum('ijk->jki', img)
    tiles_data,splitlen,total_meta = split_image(img_path,tile_size=896)
    pred_mask_bgrs = []
    for img_4band in tiles_data:
        # 语义分割预测
        seg = '/root/MMSegmentation_Tutorials-main/20230816/mmdeploy/mmseg2onnx_GFswin2'
        device = 'cpu'
        print(img_4band.shape)
        segmentor = Segmentor(seg, device)
        
        pred_mask = segmentor(img_4band)
        pred_mask_bgr_out = np.einsum('ijk->kij', pred_mask)
        pred_mask_bgrs.append(pred_mask_bgr_out)
    join_image(pred_mask_bgrs,splitlen,total_meta,output_path)

if __name__ == "__main__":

    # 模型 config 配置文件
    config_file = r'/root/MMSegmentation_Tutorials-main/20230816/mmsegmentation/work_dirs/GF2MultiDataset-Swintrans/GF2MultiDataset_Swintrans_20230904.py'

    # 模型 checkpoint 权重文件
    checkpoint_file = r'/root/MMSegmentation_Tutorials-main/20230816/mmsegmentation/work_dirs/GF2MultiDataset-Swintrans/best_mIoU_iter_27700.pth'

    # 计算硬件
    # device = 'cpu'
    device = 'cuda:0'

    model = init_model(config_file, checkpoint_file, device=device)
    # 每个类别的 BGR 配色
    palette = [
        ['background', [0,0,0]],
        ['crop', [0,127,255]],
        ['road', [110,144,128]],
        ['water', [100,237,149]],
    ]

    palette_dict = {}
    for idx, each in enumerate(palette):
        palette_dict[idx] = each[1]
    
    if not os.path.exists(r'/root/MMSegmentation_Tutorials-main/20230816/mmsegmentation/outputs/testset-pred_gf122'):
        os.mkdir(r'/root/MMSegmentation_Tutorials-main/20230816/mmsegmentation/outputs/testset-pred_gf122')

    PATH_IMAGE = r'/root/autodl-tmp/test_2'
    os.chdir(PATH_IMAGE)
    for img_path in os.listdir(PATH_IMAGE):
        output_path = os.path.join(r'/root/MMSegmentation_Tutorials-main/20230816/mmsegmentation/outputs/testset-pred_gf122',img_path) 
        process_single_img(img_path,output_path)

### Environment

```Shell
System environment:
    sys.platform: linux
    Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
    CUDA available: True
    numpy_random_seed: 0
    GPU 0: NVIDIA RTX A5000
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.3, V11.3.109
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.10.1+cu113
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.11.2+cu113
    OpenCV: 4.8.0
    MMEngine: 0.8.4
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/root/MMSegmentation_Tutorials-main/20230816/mmdeploy/tools/mmdeployruntime.py", line 115, in <module>
    process_single_img(img_path,output_path)
  File "/root/MMSegmentation_Tutorials-main/20230816/mmdeploy/tools/mmdeployruntime.py", line 78, in process_single_img
    pred_mask = segmentor(img_4band)
RuntimeError: images of 1 or 3 channels are supported
```

**Comment by RunningLeon** [comment]
@fromchina-nb mmdeploy_runtime requires input is raw image data with shape as (h,w,c)
https://github.com/open-mmlab/mmdeploy/blob/a3c2fae41caf9cd322a878218749b14653394342/mmdeploy/codebase/mmseg/deploy/segmentation_model.py#L186-L190
