### ISSUE TITLE
support HTC

### ISSUE THREAD

**Issue by sipie800** [open-mmlab/mmdeploy#2409]
### Motivation

We've been working around HTC in mmdet. It's doing well in our project. However after expensive training effort, when we try to deploy it it took long time for us to find that mmdeploy doesn't support it. It's quite depressing.
IMO you might write supported models in a standing out position in doc. Perhaps at first of other items.

Nevertheless, we are still struggling to figure out how to support HTC in mmdeploy. The mmdeploy does implement supported models in its own version right? What is the purpose? Can we just export any torch models to onnx and trt in reguler way without mmdeploy? 

Or we also may implement HTC support in mmdeploy by self. Can you provide some clue about how can we start ?

We do know that Cascade RCNN is supported. But for a hard project, it doesn't meet our need as much as HTC.

**Comment by RunningLeon** [comment]
hi, welcome to support HTC and PR to us. You may need to add some rewriting functions to support torch2onnx. Could refer to this doc: https://mmdeploy.readthedocs.io/en/latest/07-developer-guide/support_new_model.html

**Comment by irexyc** [comment]
Hi @sipie800 , you can test if https://github.com/open-mmlab/mmdeploy/pull/2438 can solve your problem.

I test it with official model and below is my convert command.

```
python3 tools/deploy.py configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py /root/workspace/mmdetection/configs/htc/htc_r50_fpn_1x_coco.py https://download.openmmlab.com/mmdetection/v2.0/htc/htc_r50_fpn_1x_coco/htc_r50_fpn_1x_coco_20200317-7332cf16.pth /root/workspace/mmdetection/demo/demo.jpg --work-dir work/htc-onnx --dump-info

python3 tools/deploy.py configs/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py /root/workspace/mmdetection/configs/htc/htc_r50_fpn_1x_coco.py https://download.openmmlab.com/mmdetection/v2.0/htc/htc_r50_fpn_1x_coco/htc_r50_fpn_1x_coco_20200317-7332cf16.pth /root/workspace/mmdetection/demo/demo.jpg --work-dir work/htc-trt --dump-info --device cuda
```

**Comment by sipie800** [comment]
Thank you. It works!
