### ISSUE TITLE
 pt to onnx

### ISSUE THREAD

**Issue by shituo123456** [open-mmlab/mmdeploy#241]
Use the official file(pytorch2onnx.py) to export onnX,but less accurate than pt 

backbone: resnet50v1c, model:deeplabv3+

please help me to solve this problem.

**Comment by AllentDan** [comment]
Hi, @shituo123456. Please note that the test pipeline in MMDeploy did not use the `slide` mode for MMSeg models. Could you make sure that you used the exact same strategy for both PyTorch and ONNX models? And how much does the accuracy drops?
