### ISSUE TITLE
[Bug] I pull mmdeploy docker, but it doesn't have python.

### ISSUE THREAD

**Issue by PeterKim1** [open-mmlab/mmdeploy#2416]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hello.

Thanks for your great library.

I want to use mmseg, and need to deploy model. So, I try to use mmdeploy from docker.

But after pull mmdeploy docker, it seems that it doesn't have python.

![image](https://github.com/open-mmlab/mmdeploy/assets/57930520/6b352a13-43a4-46fc-b9e2-f2cb114a906d)

I'm not expert on docker system, so maybe it becuz of my fault or need to do something.

Is it your docker image issue? Or I need to do something if i want to use python?

### Reproduction

docker pull openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.2.0

docker run --gpus '"device=3"' -itd --name gpu3_mmdeploy -v /:/home -p 5005:8888 openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.2.0 bash

docker exec -it gpu3_mmdeploy bash

python 

=>> bash: python: command not found

(I don't make any modifications.)

### Environment

```Shell
Currently, bash: python: command not found. So, I can't attach my python tools/check_env.py. Sorry.
```

**Comment by RunningLeon** [comment]
hi, could use `python3`

**Comment by PeterKim1** [comment]
Hi @RunningLeon . 

I can use python3! 


![image](https://github.com/open-mmlab/mmdeploy/assets/57930520/74a0c137-00a8-4855-86a5-e8382219eced)


Thanks for your very fast response. I always use command 'python', so I used it habitually.
