### ISSUE TITLE
About converting RTMdet model to ncnn backend

### ISSUE THREAD

**Issue by kdavidlp123** [open-mmlab/mmdeploy#2420]
### 📚 The doc issue

I have looked up [the config folder of detection in mmdet](https://github.com/open-mmlab/mmdeploy/tree/main/configs/mmdet/detection), but it seemed that the ncnn backend only supported size 320 ([this](https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmdet/detection/single-stage_ncnn_static-320x320.py)). Because in the mmdet, the input size of [model](https://github.com/open-mmlab/mmdetection/blob/main/configs/rtmdet/rtmdet_l_8xb32-300e_coco.py) is 640. And I had a custom dataset to train on RTMdet, may I ask about which doc and line I should modify in order to fit the size of ncnn converter(like [this](https://github.com/open-mmlab/mmpose/blob/main/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py) ).

### Suggest a potential alternative/fix

None

**Comment by RunningLeon** [comment]
hi, you could change the input_shape to `[640,640]` in deploy config:
https://github.com/open-mmlab/mmdeploy/blob/6e60cae48599947ea1756c147f558565fd8991dc/configs/mmdet/detection/single-stage_ncnn_static-320x320.py#L4

**Comment by fzait** [comment]
> ### 📚 The doc issue
> I have looked up [the config folder of detection in mmdet](https://github.com/open-mmlab/mmdeploy/tree/main/configs/mmdet/detection), but it seemed that the ncnn backend only supported size 320 ([this](https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmdet/detection/single-stage_ncnn_static-320x320.py)). Because in the mmdet, the input size of [model](https://github.com/open-mmlab/mmdetection/blob/main/configs/rtmdet/rtmdet_l_8xb32-300e_coco.py) is 640. And I had a custom dataset to train on RTMdet, may I ask about which doc and line I should modify in order to fit the size of ncnn converter(like [this](https://github.com/open-mmlab/mmpose/blob/main/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py) ).
> 
> ### Suggest a potential alternative/fix
> None

I'm working also on the deployment of the rtmdet model, and I would like to keep in contact
