### ISSUE TITLE
[Bug] AssertionError: scope_name should be a string, but got None. (converting mmseg model to onnx)

### ISSUE THREAD

**Issue by PeterKim1** [open-mmlab/mmdeploy#2423]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Hi. Thanks for you great works.

I want to convert mmseg model to onnx, but some error occur.

I refer to https://github.com/open-mmlab/mmdeploy/issues/2030 this post, so I try to use your mmdeploy docker.

The steps I took are as follows.

First, docker pull openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.2.0. and run this docker images.

Second, i need to use mmseg model, so I installed mmseg in this mmdeploy docker. (Followed the installation instructions in mmseg)

Third, python3 tools/deploy.py. But these error occur.

09/11 02:24:49 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
09/11 02:24:49 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
09/11 02:24:49 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/DINOv2/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 135, in __init__
    super(Segmentation, self).__init__(model_cfg, deploy_cfg, device)
  File "/DINOv2/mmdeploy/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/DINOv2/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/DINOv2/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/DINOv2/mmdeploy/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/DINOv2/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
AssertionError: class `Segmentation` in mmdeploy/codebase/mmseg/deploy/segmentation.py: scope_name should be a string, but got None
09/11 02:24:50 - mmengine - ERROR - /DINOv2/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

This is my first time to use mmseg and mmdeploy, so i don't know well about mmdeploy.

But after i read these error messages, maybe i think there seems to be more steps I need to proceed.

I want you to let me know if this error should be considered a bug or if it's because I didn't do anything.

Thanks.

### Reproduction

First, docker pull openmmlab/mmdeploy:ubuntu20.04-cuda11.3-mmdeploy1.2.0. and run this docker images.

Second, i need to use mmseg model, so I installed mmseg in this mmdeploy docker. (Followed the installation instructions in mmseg)

Third, python3 tools/deploy.py. But these error occur.

### Environment

```Shell
09/12 00:50:01 - mmengine - INFO - 

09/12 00:50:01 - mmengine - INFO - **********Environmental information**********
09/12 00:50:02 - mmengine - INFO - sys.platform: linux
09/12 00:50:02 - mmengine - INFO - Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
09/12 00:50:02 - mmengine - INFO - CUDA available: True
09/12 00:50:02 - mmengine - INFO - numpy_random_seed: 2147483648
09/12 00:50:02 - mmengine - INFO - GPU 0: NVIDIA RTX A6000
09/12 00:50:02 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
09/12 00:50:02 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
09/12 00:50:02 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
09/12 00:50:02 - mmengine - INFO - PyTorch: 1.10.0+cu113
09/12 00:50:02 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

09/12 00:50:02 - mmengine - INFO - TorchVision: 0.11.0+cu113
09/12 00:50:02 - mmengine - INFO - OpenCV: 4.5.4
09/12 00:50:02 - mmengine - INFO - MMEngine: 0.7.4
09/12 00:50:02 - mmengine - INFO - MMCV: 2.0.1
09/12 00:50:02 - mmengine - INFO - MMCV Compiler: GCC 9.3
09/12 00:50:02 - mmengine - INFO - MMCV CUDA Compiler: 11.3
09/12 00:50:02 - mmengine - INFO - MMDeploy: 1.2.0+a3c2fae
09/12 00:50:02 - mmengine - INFO - 

09/12 00:50:02 - mmengine - INFO - **********Backend information**********
09/12 00:50:02 - mmengine - INFO - tensorrt:    8.2.3.0
09/12 00:50:02 - mmengine - INFO - tensorrt custom ops: NotAvailable
09/12 00:50:02 - mmengine - INFO - ONNXRuntime: None
09/12 00:50:02 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
09/12 00:50:02 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/12 00:50:02 - mmengine - INFO - pplnn:       0.8.1
09/12 00:50:02 - mmengine - INFO - ncnn:        1.0.20230224
09/12 00:50:02 - mmengine - INFO - ncnn custom ops:     NotAvailable
09/12 00:50:02 - mmengine - INFO - snpe:        None
09/12 00:50:02 - mmengine - INFO - openvino:    2022.3.0
09/12 00:50:02 - mmengine - INFO - torchscript: 1.10.0+cu113
09/12 00:50:02 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/12 00:50:02 - mmengine - INFO - rknn-toolkit:        None
09/12 00:50:02 - mmengine - INFO - rknn-toolkit2:       None
09/12 00:50:02 - mmengine - INFO - ascend:      None
09/12 00:50:02 - mmengine - INFO - coreml:      None
09/12 00:50:02 - mmengine - INFO - tvm: None
09/12 00:50:02 - mmengine - INFO - vacc:        None
09/12 00:50:02 - mmengine - INFO - 

09/12 00:50:02 - mmengine - INFO - **********Codebase information**********
09/12 00:50:02 - mmengine - INFO - mmdet:       None
09/12 00:50:02 - mmengine - INFO - mmseg:       1.1.1
09/12 00:50:02 - mmengine - INFO - mmpretrain:  None
09/12 00:50:02 - mmengine - INFO - mmocr:       None
09/12 00:50:02 - mmengine - INFO - mmagic:      None
09/12 00:50:02 - mmengine - INFO - mmdet3d:     None
09/12 00:50:02 - mmengine - INFO - mmpose:      None
09/12 00:50:02 - mmengine - INFO - mmrotate:    None
09/12 00:50:02 - mmengine - INFO - mmaction:    None
09/12 00:50:02 - mmengine - INFO - mmrazor:     None
09/12 00:50:02 - mmengine - INFO - mmyolo:      None
```

**Comment by RunningLeon** [comment]
hi, could you try to upgrade mmeinge to the newst?

**Comment by PeterKim1** [comment]
@RunningLeon Hi. Sorry for late reply.

Check https://github.com/open-mmlab/mmengine, and use command 'mim install mmengine==0.8.4'.

But similar error occur.

09/13 02:11:44 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
09/13 02:11:45 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
09/13 02:11:45 - mmengine - WARNING - Failed to search registry with scope "mmseg" in the "mmseg_tasks" registry tree. As a workaround, the current "mmseg_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmseg" is a correct scope, or whether the registry is initialized.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/DINOv2/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/DINOv2/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 61, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/DINOv2/mmdeploy/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/DINOv2/mmdeploy/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/DINOv2/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 135, in __init__
    super(Segmentation, self).__init__(model_cfg, deploy_cfg, device)
  File "/DINOv2/mmdeploy/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None
09/13 02:11:45 - mmengine - ERROR - /DINOv2/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

And this is my env:

# python3 tools/check_env.py
09/13 02:12:29 - mmengine - INFO - 

09/13 02:12:29 - mmengine - INFO - **********Environmental information**********
09/13 02:12:30 - mmengine - INFO - sys.platform: linux
09/13 02:12:30 - mmengine - INFO - Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
09/13 02:12:30 - mmengine - INFO - CUDA available: True
09/13 02:12:30 - mmengine - INFO - numpy_random_seed: 2147483648
09/13 02:12:30 - mmengine - INFO - GPU 0: NVIDIA RTX A6000
09/13 02:12:30 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
09/13 02:12:30 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.109
09/13 02:12:30 - mmengine - INFO - GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
09/13 02:12:30 - mmengine - INFO - PyTorch: 1.10.0+cu113
09/13 02:12:30 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

09/13 02:12:30 - mmengine - INFO - TorchVision: 0.11.0+cu113
09/13 02:12:30 - mmengine - INFO - OpenCV: 4.5.4
09/13 02:12:30 - mmengine - INFO - MMEngine: 0.8.4
09/13 02:12:30 - mmengine - INFO - MMCV: 2.0.1
09/13 02:12:30 - mmengine - INFO - MMCV Compiler: GCC 9.3
09/13 02:12:30 - mmengine - INFO - MMCV CUDA Compiler: 11.3
09/13 02:12:30 - mmengine - INFO - MMDeploy: 1.2.0+a3c2fae
09/13 02:12:30 - mmengine - INFO - 

09/13 02:12:30 - mmengine - INFO - **********Backend information**********
09/13 02:12:30 - mmengine - INFO - tensorrt:    8.2.3.0
09/13 02:12:30 - mmengine - INFO - tensorrt custom ops: NotAvailable
09/13 02:12:30 - mmengine - INFO - ONNXRuntime: None
09/13 02:12:30 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
09/13 02:12:30 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/13 02:12:30 - mmengine - INFO - pplnn:       0.8.1
09/13 02:12:30 - mmengine - INFO - ncnn:        1.0.20230224
09/13 02:12:30 - mmengine - INFO - ncnn custom ops:     NotAvailable
09/13 02:12:30 - mmengine - INFO - snpe:        None
09/13 02:12:30 - mmengine - INFO - openvino:    2022.3.0
09/13 02:12:30 - mmengine - INFO - torchscript: 1.10.0+cu113
09/13 02:12:30 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/13 02:12:30 - mmengine - INFO - rknn-toolkit:        None
09/13 02:12:30 - mmengine - INFO - rknn-toolkit2:       None
09/13 02:12:30 - mmengine - INFO - ascend:      None
09/13 02:12:30 - mmengine - INFO - coreml:      None
09/13 02:12:30 - mmengine - INFO - tvm: None
09/13 02:12:30 - mmengine - INFO - vacc:        None
09/13 02:12:30 - mmengine - INFO - 

09/13 02:12:30 - mmengine - INFO - **********Codebase information**********
09/13 02:12:30 - mmengine - INFO - mmdet:       None
09/13 02:12:30 - mmengine - INFO - mmseg:       1.1.1
09/13 02:12:30 - mmengine - INFO - mmpretrain:  1.0.2
09/13 02:12:30 - mmengine - INFO - mmocr:       None
09/13 02:12:30 - mmengine - INFO - mmagic:      None
09/13 02:12:30 - mmengine - INFO - mmdet3d:     None
09/13 02:12:30 - mmengine - INFO - mmpose:      None
09/13 02:12:30 - mmengine - INFO - mmrotate:    None
09/13 02:12:30 - mmengine - INFO - mmaction:    None
09/13 02:12:30 - mmengine - INFO - mmrazor:     None
09/13 02:12:30 - mmengine - INFO - mmyolo:      None

**Comment by RunningLeon** [comment]
hi， what's your model config? can you try other models like fastscnn?
