### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Jianfeng777** [open-mmlab/mmdeploy#2431]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

用onnxruntime cuda的话，你需要
1. pip install mmdeploy-runtime-gpu
2. 下载onnxruntime-gpu 1.8.1，并把其中的lib目录添加到LD_LIBRARY_PATH
https://github.com/microsoft/onnxruntime/releases/tag/v1.8.1

我按着这个要求去做了，但是还是出现下面这个Bug
![790887b11a95c55fded36fae1c10a71](https://github.com/open-mmlab/mmdeploy/assets/108343727/794f78bd-99ca-4f4d-b317-5e808cb6c53c)

这个要怎么处理呢？是要我重新下载尝试吗？还是说只能出GPU版本呢

### Reproduction

就是demo\python里进行预测

### Environment

```Shell
(mmdeploy) jianfeng@Administrator:/mnt/e/AI/mmdeploy$ python tools/check_env.py
09/13 17:50:08 - mmengine - INFO -

09/13 17:50:08 - mmengine - INFO - **********Environmental information**********
/bin/sh: 1: /usr/local/cuda-11.8/bin/nvcc: not found
/bin/sh: 1: /usr/local/cuda-11.8/bin/nvcc: not found
09/13 17:50:10 - mmengine - INFO - sys.platform: linux
09/13 17:50:10 - mmengine - INFO - Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
09/13 17:50:10 - mmengine - INFO - CUDA available: True
09/13 17:50:10 - mmengine - INFO - numpy_random_seed: 2147483648
09/13 17:50:10 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3070 Ti
09/13 17:50:10 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.8
09/13 17:50:10 - mmengine - INFO - NVCC: Not Available
09/13 17:50:10 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
09/13 17:50:10 - mmengine - INFO - PyTorch: 2.0.1+cu118
09/13 17:50:10 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

09/13 17:50:10 - mmengine - INFO - TorchVision: 0.15.2+cu118
09/13 17:50:10 - mmengine - INFO - OpenCV: 4.8.0
09/13 17:50:10 - mmengine - INFO - MMEngine: 0.8.4
09/13 17:50:10 - mmengine - INFO - MMCV: 2.0.1
09/13 17:50:10 - mmengine - INFO - MMCV Compiler: GCC 9.3
09/13 17:50:10 - mmengine - INFO - MMCV CUDA Compiler: 11.8
09/13 17:50:10 - mmengine - INFO - MMDeploy: 1.2.0+8478249
09/13 17:50:10 - mmengine - INFO -

09/13 17:50:10 - mmengine - INFO - **********Backend information**********
09/13 17:50:10 - mmengine - INFO - tensorrt:    None
09/13 17:50:10 - mmengine - INFO - ONNXRuntime: 1.15.1
09/13 17:50:10 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
09/13 17:50:10 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/13 17:50:10 - mmengine - INFO - pplnn:       None
09/13 17:50:10 - mmengine - INFO - ncnn:        None
09/13 17:50:11 - mmengine - INFO - snpe:        None
09/13 17:50:11 - mmengine - INFO - openvino:    None
09/13 17:50:11 - mmengine - INFO - torchscript: 2.0.1+cu118
09/13 17:50:11 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/13 17:50:11 - mmengine - INFO - rknn-toolkit:        None
09/13 17:50:11 - mmengine - INFO - rknn-toolkit2:       None
09/13 17:50:11 - mmengine - INFO - ascend:      None
09/13 17:50:11 - mmengine - INFO - coreml:      None
09/13 17:50:11 - mmengine - INFO - tvm: None
09/13 17:50:11 - mmengine - INFO - vacc:        None
09/13 17:50:11 - mmengine - INFO -

09/13 17:50:11 - mmengine - INFO - **********Codebase information**********
09/13 17:50:11 - mmengine - INFO - mmdet:       3.1.0
09/13 17:50:11 - mmengine - INFO - mmseg:       1.1.1
09/13 17:50:11 - mmengine - INFO - mmpretrain:  None
09/13 17:50:11 - mmengine - INFO - mmocr:       None
09/13 17:50:11 - mmengine - INFO - mmagic:      None
09/13 17:50:11 - mmengine - INFO - mmdet3d:     None
09/13 17:50:11 - mmengine - INFO - mmpose:      None
09/13 17:50:11 - mmengine - INFO - mmrotate:    None
09/13 17:50:11 - mmengine - INFO - mmaction:    None
09/13 17:50:11 - mmengine - INFO - mmrazor:     None
09/13 17:50:11 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
(mmdeploy) jianfengAdministrator:/mnt/e/AI/mmdeploy$ SPDLOG LEVEL=error pythonmntrerntetection.pycuda /mnt/e/AI/mmdeployloading libmmdeplov ort net.so .2023-09-13 11:56:57.710] mmdeploy] [error [common.cpp:671 Device "cuda" not foundraceback (most recent call last):File "/mnt/e/AI/mmdeploy/demo/python/object detection.py"，line 53,in <module>
main()File "/mnt/e/AI/mmdeploy/demo/python/object detection.py"，line 25, in maindetector = Detector(RuntimeError: failed to create detector
```

**Comment by irexyc** [comment]
<img width="709" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/16019484/6eec3952-1d4e-44c1-b6c3-69a142ff48ba">

你看这里的log，因为你之前装了mmdeploy-runtime，所以需要先卸载再安装。

**Comment by Jianfeng777** [comment]
> <img alt="image" width="709" src="https://user-images.githubusercontent.com/16019484/267615490-6eec3952-1d4e-44c1-b6c3-69a142ff48ba.png">
> 你看这里的log，因为你之前装了mmdeploy-runtime，所以需要先卸载再安装。
> 
> 装了mmdeploy-runtime-gpu之后，启动程序的时候会尝试 load 两个 net (trt, ort)，环境满足的话会load成功。 <img alt="image" width="1125" src="https://user-images.githubusercontent.com/16019484/267616075-a8c3f210-995a-49aa-a102-ebcaa6fcb81c.png">

你看这里，我就算安装了cuda11.0也出现了下面的bug
[(mmdeploy) jianfeng@Administrator:/mnt/e/AI/mmdeploy$ python /mnt/e/AI/mmdeploy/demo/python/image_segmentation.py cuda /mnt/e/AI/mmdeploy/output/red_tree /mnt/e/AI/mmdeploy/project/red_tree_segmentation/DJI_20230309103852_0001_W.jpg
loading libmmdeploy_trt_net.so ...
failed to load library libmmdeploy_trt_net.so
loading libmmdeploy_ort_net.so ...
[2023-09-13 18:12:21.248] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/mnt/e/AI/mmdeploy/output/red_tree"
2023-09-13 18:12:21.782783406 [E:onnxruntime:, provider_bridge_ort.cc:901 Ensure] Failed to load library libonnxruntime_providers_shared.so with error: libonnxruntime_providers_shared.so: cannot open shared object file: No such file or directory
[2023-09-13 18:12:21.783] [mmdeploy] [error] [ort_net.cpp:205] unhandled exception when creating ORTNet: OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
[2023-09-13 18:12:21.783] [mmdeploy] [error] [net_module.cpp:54] Failed to create Net backend: onnxruntime, config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "depthwiseseparableaspp",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}
[2023-09-13 18:12:21.783] [mmdeploy] [error] [task.cpp:99] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "is_batched": true,
  "module": "Net",
  "name": "depthwiseseparableaspp",
  "output": [
    "infer_output"
  ],
  "output_map": {},
  "type": "Task"
}
Segmentation fault](url)

**Comment by irexyc** [comment]
> [2023-09-13 18:12:21.782783406 [E:onnxruntime:, provider_bridge_ort.cc:901 Ensure] Failed to load library libonnxruntime_providers_shared.so with error: libonnxruntime_providers_shared.so: cannot open shared object file: No such file or directory](https://github.com/open-mmlab/mmdeploy/issues/url)

检查下这个shell的LD_LIBRARY_PATH，一般是 onnxruntime-gpu 的 lib 没有设置好
