### ISSUE TITLE
[Bug] 运行text_ocr例子，使用c++接口时文本识别部分字符识别不全，text部分只能输出单个字符，使用python接口时报错找不到cpu，请问这两个问题该如何解决

### ISSUE THREAD

**Issue by woshinangua** [open-mmlab/mmdeploy#2434]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

1，运行text_ocr可执行文件，文本识别部分输出信息的text为单个字符
2，使用python接口运行ocr.py时报错PANHead: implementation for platform "cpu" not found. Available platforms: [("cuda", 0)]，使用python接口运行object_detection.py没有此问题

### Reproduction

1，/text_ocr --device cpu /home/yejian/lh/mmdeploy_model/text_det_onnx /home/yejian/lh/mmdeploy_model/text_recog_onnx /home/yejian/lh/mmocr/demo/demo_text_ocr.jpg
![text_ocr_output](https://github.com/open-mmlab/mmdeploy/assets/127652739/94aad5e7-13c1-4e21-8cec-234d5d8a91ed)

2，python example/python/ocr.py --textdet /home/yejian/lh/mmdeploy_model/text_det_onnx --textrecog/home/yejian/lh/mmdeploy_model/text_recog_onnx cpu /home/yejian/lh/mmocr/demo/demo_text_ocr.jpg

### Environment

```Shell
09/13 22:45:24 - mmengine - INFO - **********Environmental information**********
09/13 22:45:26 - mmengine - INFO - sys.platform: linux
09/13 22:45:26 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
09/13 22:45:26 - mmengine - INFO - CUDA available: True
09/13 22:45:26 - mmengine - INFO - numpy_random_seed: 2147483648
09/13 22:45:26 - mmengine - INFO - GPU 0,1: GeForce RTX 3090
09/13 22:45:26 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.1
09/13 22:45:26 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
09/13 22:45:26 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
09/13 22:45:26 - mmengine - INFO - PyTorch: 1.8.0
09/13 22:45:26 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

09/13 22:45:26 - mmengine - INFO - TorchVision: 0.9.0
09/13 22:45:26 - mmengine - INFO - OpenCV: 4.8.0
09/13 22:45:26 - mmengine - INFO - MMEngine: 0.8.4
09/13 22:45:26 - mmengine - INFO - MMCV: 2.0.1
09/13 22:45:26 - mmengine - INFO - MMCV Compiler: GCC 7.3
09/13 22:45:26 - mmengine - INFO - MMCV CUDA Compiler: 11.1
09/13 22:45:26 - mmengine - INFO - MMDeploy: 1.2.0+7c7e43b
09/13 22:45:26 - mmengine - INFO -

09/13 22:45:26 - mmengine - INFO - **********Backend information**********
09/13 22:45:26 - mmengine - INFO - tensorrt:    8.2.3.0
09/13 22:45:26 - mmengine - INFO - tensorrt custom ops: Available
09/13 22:45:26 - mmengine - INFO - ONNXRuntime: 1.8.1
09/13 22:45:26 - mmengine - INFO - ONNXRuntime-gpu:     1.8.1
09/13 22:45:26 - mmengine - INFO - ONNXRuntime custom ops:      Available
09/13 22:45:26 - mmengine - INFO - pplnn:       None
09/13 22:45:26 - mmengine - INFO - ncnn:        None
09/13 22:45:26 - mmengine - INFO - snpe:        None
09/13 22:45:26 - mmengine - INFO - openvino:    None
09/13 22:45:26 - mmengine - INFO - torchscript: 1.8.0
09/13 22:45:26 - mmengine - INFO - torchscript custom ops:      NotAvailable
09/13 22:45:26 - mmengine - INFO - rknn-toolkit:        None
09/13 22:45:26 - mmengine - INFO - rknn-toolkit2:       None
09/13 22:45:26 - mmengine - INFO - ascend:      None
09/13 22:45:26 - mmengine - INFO - coreml:      None
09/13 22:45:26 - mmengine - INFO - tvm: None
09/13 22:45:26 - mmengine - INFO - vacc:        None
09/13 22:45:26 - mmengine - INFO -

09/13 22:45:26 - mmengine - INFO - **********Codebase information**********
09/13 22:45:26 - mmengine - INFO - mmdet:       3.1.0
09/13 22:45:26 - mmengine - INFO - mmseg:       None
09/13 22:45:26 - mmengine - INFO - mmpretrain:  None
09/13 22:45:26 - mmengine - INFO - mmocr:       1.0.1
09/13 22:45:26 - mmengine - INFO - mmagic:      None
09/13 22:45:26 - mmengine - INFO - mmdet3d:     None
09/13 22:45:26 - mmengine - INFO - mmpose:      None
09/13 22:45:26 - mmengine - INFO - mmrotate:    None
09/13 22:45:26 - mmengine - INFO - mmaction:    None
09/13 22:45:26 - mmengine - INFO - mmrazor:     None
09/13 22:45:26 - mmengine - INFO - mmyolo:      None
```

### Error traceback

```Shell
1,[2023-09-13 16:21:17.557] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_det_onnx"
[2023-09-13 16:21:18.147] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_recog_onnx"
[2023-09-13 16:21:19.189] [mmdeploy] [warning] [base_convertor.cpp:104] padding does not exist in the dictionary
[2023-09-13 16:21:19.189] [mmdeploy] [info] [inference.cpp:54] ["img"] <- ["patches"]
[2023-09-13 16:21:19.189] [mmdeploy] [info] [inference.cpp:65] ["post_output"] -> ["texts"]
bbox[0]: (215.49, 43.46), (153.98, 36.63), (157.10, 8.61), (218.60, 15.44), 0.97
eext[0]: s
bbox[1]: (66.32, 56.36), (33.16, 56.36), (33.16, 39.78), (66.32, 39.78), 0.94
eext[1]: s
bbox[2]: (580.22, 116.61), (459.16, 105.93), (464.03, 50.78), (585.09, 61.46), 0.97
lext[2]: a
bbox[3]: (706.10, 130.99), (579.28, 117.87), (585.05, 62.11), (711.87, 75.23), 0.97
rext[3]: y
bbox[4]: (16.58, 116.03), (16.58, 89.51), (79.58, 89.51), (79.58, 116.03), 0.98
eext[4]: s
bbox[5]: (658.94, 248.03), (443.91, 226.95), (449.76, 167.33), (664.78, 188.41), 0.98
dext[5]: r
bbox[6]: (53.05, 238.70), (13.26, 238.70), (13.26, 212.17), (53.05, 212.17), 0.87
0ext[6]: 7
bbox[7]: (510.04, 299.23), (442.27, 289.55), (444.85, 271.45), (512.63, 281.13), 0.97
1ext[7]: 1
bbox[8]: (577.88, 307.60), (515.03, 299.75), (517.43, 280.57), (580.27, 288.42), 0.96
sext[8]: b
bbox[9]: (635.71, 309.62), (579.18, 304.91), (580.69, 286.80), (637.21, 291.51), 0.95
eext[9]: o
bbox[10]: (636.64, 305.00), (636.64, 291.74), (673.12, 291.74), (673.12, 305.00), 0.96
mext[10]: f
bbox[11]: (493.98, 320.36), (438.25, 310.22), (441.64, 291.55), (497.38, 301.68), 0.96
eext[11]: 1
bbox[12]: (586.47, 329.67), (497.08, 321.55), (498.79, 302.72), (588.18, 310.84), 0.97
sext[12]: p
bbox[13]: (653.22, 328.21), (590.22, 328.21), (590.22, 311.63), (653.22, 311.63), 0.94
dext[13]: g
bbox[14]: (554.51, 414.91), (470.44, 404.41), (474.57, 371.36), (558.64, 381.86), 0.95
cext[14]: o
bbox[15]: (560.38, 414.40), (560.38, 384.57), (620.06, 384.57), (620.06, 414.40), 0.94
kext[15]: b


2,loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-09-13 15:21:30.289] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_det_onnx"
[2023-09-13 15:21:30.941] [mmdeploy] [error] [panet.cpp:40] PANHead: implementation for platform "cpu" not found. Available platforms: [("cuda", 0)]
[2023-09-13 15:21:30.941] [mmdeploy] [error] [task.cpp:99] error parsing config: {
  "component": "PANHead",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmocr",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {},
  "type": "Task"
}
Segmentation fault (core dumped)
```

**Comment by AllentDan** [comment]
Can not reproduce the above errors with the latest MMDeploy. `example/python/ocr.py` accepts only one task, either text detection or text recognition.

**Comment by woshinangua** [comment]
> Can not reproduce the above errors with the latest MMDeploy. `example/python/ocr.py` accepts only one task, either text detection or text recognition.

![text_ocr_output](https://github.com/open-mmlab/mmdeploy/assets/127652739/c0a4120b-8733-41f9-9eb7-4401c4f7ee2c)
The text recognition part of this picture is not working well. How can I solve it

**Comment by woshinangua** [comment]
> Can not reproduce the above errors with the latest MMDeploy. `example/python/ocr.py` accepts only one task, either text detection or text recognition.

I did print out text using only the text recognition task, but the text detection task still gets the above error message [2023-09-14 11:23:24.440] [mmdeploy] [error] [panet.cpp:40] PANHead: implementation for platform "cpu" not found. Available platforms: [("cuda", 0)]

**Comment by woshinangua** [comment]
> > Can not reproduce the above errors with the latest MMDeploy. `example/python/ocr.py` accepts only one task, either text detection or text recognition.
> 
> I did print out text using only the text recognition task, but the text detection task still gets the above error message [2023-09-14 11:23:24.440] [mmdeploy] [error] [panet.cpp:40] PANHead: implementation for platform "cpu" not found. Available platforms: [("cuda", 0)]

(mmdeploy) root@2084a876b2bd:/home/yejian/lh/mmdeploy/build/install/example/python# python ocr.py --textrecog /home/yejian/lh/mmdeploy_model/text_recog_onnx cpu /home/yejian/lh/mmocr/demo/demo_text_recog.jpg
loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-09-14 11:08:32.512] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_recog_onnx"
[2023-09-14 11:08:33.414] [mmdeploy] [warning] [base_convertor.cpp:104] padding does not exist in the dictionary
[2023-09-14 11:08:33.414] [mmdeploy] [info] [inference.cpp:54] ["img"] <- ["patches"]
[2023-09-14 11:08:33.414] [mmdeploy] [info] [inference.cpp:65] ["post_output"] -> ["texts"]
('s\rt\ra\rr\r', [0.9999845027923584, 0.9999897480010986, 0.9999806880950928, 0.9998551607131958])

**Comment by woshinangua** [comment]
> > > Can not reproduce the above errors with the latest MMDeploy. `example/python/ocr.py` accepts only one task, either text detection or text recognition.
> > 
> > 
> > I did print out text using only the text recognition task, but the text detection task still gets the above error message [2023-09-14 11:23:24.440] [mmdeploy] [error] [panet.cpp:40] PANHead: implementation for platform "cpu" not found. Available platforms: [("cuda", 0)]
> 
> (mmdeploy) root@2084a876b2bd:/home/yejian/lh/mmdeploy/build/install/example/python# python ocr.py --textrecog /home/yejian/lh/mmdeploy_model/text_recog_onnx cpu /home/yejian/lh/mmocr/demo/demo_text_recog.jpg loading libmmdeploy_trt_net.so ... loading libmmdeploy_ort_net.so ... [2023-09-14 11:08:32.512] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_recog_onnx" [2023-09-14 11:08:33.414] [mmdeploy] [warning] [base_convertor.cpp:104] padding does not exist in the dictionary [2023-09-14 11:08:33.414] [mmdeploy] [info] [inference.cpp:54] ["img"] <- ["patches"] [2023-09-14 11:08:33.414] [mmdeploy] [info] [inference.cpp:65] ["post_output"] -> ["texts"] ('s\rt\ra\rr\r', [0.9999845027923584, 0.9999897480010986, 0.9999806880950928, 0.9998551607131958])

(mmdeploy) root@2084a876b2bd:/home/yejian/lh/mmdeploy/build/install/example/python# python ocr.py --textrecog /home/yeji
an/lh/mmdeploy_model/text_det_onnx cpu /home/yejian/lh/mmocr/demo/demo_text_det.jpg
loading libmmdeploy_trt_net.so ...
loading libmmdeploy_ort_net.so ...
[2023-09-14 11:22:17.466] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_det_onnx"
[2023-09-14 11:22:18.161] [mmdeploy] [error] [panet.cpp:40] PANHead: implementation for platform "cpu" not found. Available platforms: [("cuda", 0)]
[2023-09-14 11:22:18.162] [mmdeploy] [error] [task.cpp:99] error parsing config: {
  "component": "PANHead",
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output",
    "infer_output"
  ],
  "module": "mmocr",
  "name": "postprocess",
  "output": [
    "post_output"
  ],
  "params": {},
  "type": "Task"
}

**Comment by woshinangua** [comment]
> > Can not reproduce the above errors with the latest MMDeploy. `example/python/ocr.py` accepts only one task, either text detection or text recognition.
> 
> ![text_ocr_output](https://user-images.githubusercontent.com/127652739/267846870-c0a4120b-8733-41f9-9eb7-4401c4f7ee2c.jpg) The text recognition part of this picture is not working well. How can I solve it
上述是运行如下命令生成的：/text_ocr --device cpu /home/yejian/lh/mmdeploy_model/text_det_onnx /home/yejian/lh/mmdeploy_model/text_recog_onnx /home/yejian/lh/mmocr/demo/demo_text_ocr.jpg

**Comment by woshinangua** [comment]
> > > Can not reproduce the above errors with the latest MMDeploy. `example/python/ocr.py` accepts only one task, either text detection or text recognition.
> > 
> > 
> > I did print out text using only the text recognition task, but the text detection task still gets the above error message [2023-09-14 11:23:24.440] [mmdeploy] [error] [panet.cpp:40] PANHead: implementation for platform "cpu" not found. Available platforms: [("cuda", 0)]
> 
> (mmdeploy) root@2084a876b2bd:/home/yejian/lh/mmdeploy/build/install/example/python# python ocr.py --textrecog /home/yejian/lh/mmdeploy_model/text_recog_onnx cpu /home/yejian/lh/mmocr/demo/demo_text_recog.jpg loading libmmdeploy_trt_net.so ... loading libmmdeploy_ort_net.so ... [2023-09-14 11:08:32.512] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_recog_onnx" [2023-09-14 11:08:33.414] [mmdeploy] [warning] [base_convertor.cpp:104] padding does not exist in the dictionary [2023-09-14 11:08:33.414] [mmdeploy] [info] [inference.cpp:54] ["img"] <- ["patches"] [2023-09-14 11:08:33.414] [mmdeploy] [info] [inference.cpp:65] ["post_output"] -> ["texts"] ('s\rt\ra\rr\r', [0.9999845027923584, 0.9999897480010986, 0.9999806880950928, 0.9998551607131958])

The character on the demo picture can only be correctly identified by "star", and the picture with more characters can only be identified by a limited number of characters, and can not be fully identified

**Comment by AllentDan** [comment]
I used CRNN for text recognition. What is your recognition model?

**Comment by woshinangua** [comment]
> I used CRNN for text recognition. What is your recognition model?

The two text recognition models I use are abinet and aster, The identification image is demo_text_ocr.jpg, and the output of the two models for the same image is [2023-09-14 14:24:47.505] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load  model: "/home/yejian/lh/mmdeploy_model/text_recog_onnx"
[2023-09-14 14:24:48.148] [mmdeploy] [warning] [base_convertor.cpp:104] padding does not exist in the dictionary
[2023-09-14 14:24:48.148] [mmdeploy] [info] [inference.cpp:54] ["img"] <- ["patches"]
[2023-09-14 14:24:48.148] [mmdeploy] [info] [inference.cpp:65] ["post_output"] -> ["texts"]
('p\re\ro\re\r', [0.14017368853092194, 0.198134183883667, 0.102793678641927, 0.10916060209274292])


[2023-09-14 14:25:51.097] [mmdeploy] [info] [Model.cpP :35] [DirectoryModel] Load model: "/home/yejian/lh/mmdeploy_model/text_recog_onnx_aster/"
[2023-09-14 14:25:52.701] [mmdeploy] [info] [inference.cpp:54] ["img"] <- ["patches"]
[2023-09-14 14:25:52.701] [mmdeploy] [info] [inference.cpp:65] ["post_output"] -> ["texts"]
('t\rh\re\r', [0.13230185210704803, 0.9004704356193542, 0.7610591650009155])

**Comment by woshinangua** [comment]
I use crnn as the text recognition model. When converting to onnx, the result of output_pytorch.jpg and out_onnxruntime.jpg in the saved folder are both wrong, the correct result should be "star ", and the error results of the two output pictures are the same, both are" enr".How i can solve this?

**Comment by woshinangua** [comment]
> I use crnn as the text recognition model. When converting to onnx, the result of output_pytorch.jpg and out_onnxruntime.jpg in the saved folder are both wrong, the correct result should be "star ", and the error results of the two output pictures are the same, both are" enr".How i can solve this?

![Uploading output_onnxruntime.jpg…]()

**Comment by AllentDan** [comment]
> I use crnn as the text recognition model. When converting to onnx, the result of output_pytorch.jpg and out_onnxruntime.jpg in the saved folder are both wrong, the correct result should be "star ", and the error results of the two output pictures are the same, both are" enr".How i can solve this?

CRNN is not that smart, but only one wrong prediction does not mean everything. We did not support aster model yet.

**Comment by AllentDan** [comment]
This is not normal. But we did not support aster, so the result is not assured.
