### ISSUE TITLE
[Bug] CMake Error set_target_properties Can not find target to add properties to: spdlog

### ISSUE THREAD

**Issue by azuryl** [open-mmlab/mmdeploy#2435]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

cmake ..     -DCMAKE_CXX_COMPILER=g++-7     -DMMDEPLOY_BUILD_SDK=ON     -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON     -DMMDEPLOY_BUILD_EXAMPLES=ON     -DMMDEPLOY_TARGET_DEVICES="cuda;cpu"     -DMMDEPLOY_TARGET_BACKENDS=trt     -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl     -DTENSORRT_DIR=${TENSORRT_DIR}     -DCUDNN_DIR=${CUDNN_DIR}
-- CMAKE_INSTALL_PREFIX: /home/azuryl/project/mmdeploy/build/install
-- Build TensorRT custom ops.
-- Found TensorRT headers at /home/azuryl/project/download/TensorRT-8.2.3.0/include
-- Found TensorRT libs at /home/azuryl/project/download/TensorRT-8.2.3.0/lib/libnvinfer.so;/home/azuryl/project/download/TensorRT-8.2.3.0/lib/libnvinfer_plugin.so
CMake Error at csrc/mmdeploy/core/CMakeLists.txt:15 (add_subdirectory):
  The source directory

    /home/azuryl/project/mmdeploy/third_party/spdlog

  does not contain a CMakeLists.txt file.

CMake Error at csrc/mmdeploy/core/CMakeLists.txt:16 (set_target_properties):
  set_target_properties Can not find target to add properties to: spdlog

### Reproduction

cuda + TensorRT

cd ${MMDEPLOY_DIR}
mkdir -p build && cd build
cmake .. \
    -DCMAKE_CXX_COMPILER=g++-7 \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_BUILD_EXAMPLES=ON \
    -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
    -DMMDEPLOY_TARGET_BACKENDS=trt \
    -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl \
    -DTENSORRT_DIR=${TENSORRT_DIR} \
    -DCUDNN_DIR=${CUDNN_DIR}

### Environment

```Shell
(MDE) azuryl@light-28e:~/project/mmdeploy$ python tools/check_env.py 
09/13 15:09:42 - mmengine - INFO - 

09/13 15:09:42 - mmengine - INFO - **********Environmental information**********
09/13 15:09:42 - mmengine - INFO - sys.platform: linux
09/13 15:09:42 - mmengine - INFO - Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
09/13 15:09:42 - mmengine - INFO - CUDA available: True
09/13 15:09:42 - mmengine - INFO - numpy_random_seed: 2147483648
09/13 15:09:42 - mmengine - INFO - GPU 0,1,2,3,4,5,6,7: NVIDIA RTX A6000
09/13 15:09:42 - mmengine - INFO - CUDA_HOME: /usr/local/cuda/
09/13 15:09:42 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.58
09/13 15:09:42 - mmengine - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
09/13 15:09:42 - mmengine - INFO - PyTorch: 1.8.0
09/13 15:09:42 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

09/13 15:09:42 - mmengine - INFO - TorchVision: 0.9.0
09/13 15:09:42 - mmengine - INFO - OpenCV: 4.8.0
09/13 15:09:42 - mmengine - INFO - MMEngine: 0.8.4
09/13 15:09:42 - mmengine - INFO - MMCV: 2.0.1
09/13 15:09:42 - mmengine - INFO - MMCV Compiler: GCC 7.3
09/13 15:09:42 - mmengine - INFO - MMCV CUDA Compiler: 11.1
09/13 15:09:42 - mmengine - INFO - MMDeploy: 1.2.0+8478249
09/13 15:09:42 - mmengine - INFO - 

09/13 15:09:42 - mmengine - INFO - **********Backend information**********
09/13 15:09:42 - mmengine - INFO - tensorrt:	8.2.3.0
09/13 15:09:42 - mmengine - INFO - tensorrt custom ops:	Available
09/13 15:09:42 - mmengine - INFO - ONNXRuntime:	1.8.1
09/13 15:09:42 - mmengine - INFO - ONNXRuntime-gpu:	None
09/13 15:09:42 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
09/13 15:09:42 - mmengine - INFO - pplnn:	None
09/13 15:09:42 - mmengine - INFO - ncnn:	None
09/13 15:09:42 - mmengine - INFO - snpe:	None
09/13 15:09:42 - mmengine - INFO - openvino:	None
09/13 15:09:42 - mmengine - INFO - torchscript:	1.8.0
09/13 15:09:42 - mmengine - INFO - torchscript custom ops:	NotAvailable
09/13 15:09:42 - mmengine - INFO - rknn-toolkit:	None
09/13 15:09:42 - mmengine - INFO - rknn-toolkit2:	None
09/13 15:09:42 - mmengine - INFO - ascend:	None
09/13 15:09:42 - mmengine - INFO - coreml:	None
09/13 15:09:42 - mmengine - INFO - tvm:	None
09/13 15:09:42 - mmengine - INFO - vacc:	None
09/13 15:09:42 - mmengine - INFO - 

09/13 15:09:42 - mmengine - INFO - **********Codebase information**********
09/13 15:09:42 - mmengine - INFO - mmdet:	None
09/13 15:09:42 - mmengine - INFO - mmseg:	None
09/13 15:09:42 - mmengine - INFO - mmpretrain:	None
09/13 15:09:42 - mmengine - INFO - mmocr:	None
09/13 15:09:42 - mmengine - INFO - mmagic:	None
09/13 15:09:42 - mmengine - INFO - mmdet3d:	None
09/13 15:09:42 - mmengine - INFO - mmpose:	None
09/13 15:09:42 - mmengine - INFO - mmrotate:	None
09/13 15:09:42 - mmengine - INFO - mmaction:	None
09/13 15:09:42 - mmengine - INFO - mmrazor:	None
09/13 15:09:42 - mmengine - INFO - mmyolo:	None
```

### Error traceback

```Shell
(MDE) azuryl@light-28e:~/project/mmdeploy/build$ cmake ..     -DCMAKE_CXX_COMPILER=g++-7     -DMMDEPLOY_BUILD_SDK=ON     -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON     -DMMDEPLOY_BUILD_EXAMPLES=ON     -DMMDEPLOY_TARGET_DEVICES="cuda;cpu"     -DMMDEPLOY_TARGET_BACKENDS=trt     -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl     -DTENSORRT_DIR=${TENSORRT_DIR}     -DCUDNN_DIR=${CUDNN_DIR}
-- CMAKE_INSTALL_PREFIX: /home/azuryl/project/mmdeploy/build/install
-- Build TensorRT custom ops.
-- Found TensorRT headers at /home/azuryl/project/download/TensorRT-8.2.3.0/include
-- Found TensorRT libs at /home/azuryl/project/download/TensorRT-8.2.3.0/lib/libnvinfer.so;/home/azuryl/project/download/TensorRT-8.2.3.0/lib/libnvinfer_plugin.so
CMake Error at csrc/mmdeploy/core/CMakeLists.txt:15 (add_subdirectory):
  The source directory

    /home/azuryl/project/mmdeploy/third_party/spdlog

  does not contain a CMakeLists.txt file.


CMake Error at csrc/mmdeploy/core/CMakeLists.txt:16 (set_target_properties):
  set_target_properties Can not find target to add properties to: spdlog


CMake Error at csrc/mmdeploy/core/CMakeLists.txt:18 (target_compile_options):
  Cannot specify compile options for target "spdlog" which is not built by
  this project.


CMake Error at csrc/mmdeploy/core/CMakeLists.txt:72 (target_include_directories):
  Cannot specify include directories for target "spdlog" which is not built
  by this project.


-- Found TensorRT headers at /home/azuryl/project/download/TensorRT-8.2.3.0/include
-- Found TensorRT libs at /home/azuryl/project/download/TensorRT-8.2.3.0/lib/libnvinfer.so;/home/azuryl/project/download/TensorRT-8.2.3.0/lib/libnvinfer_plugin.so
-- build codebase: mmcls
-- build codebase: mmdet
-- build codebase: mmseg
-- build codebase: mmocr
-- build codebase: mmedit
-- build codebase: mmpose
-- build codebase: mmrotate
-- build codebase: mmaction
CMake Error at csrc/mmdeploy/apis/python/CMakeLists.txt:19 (add_subdirectory):
  The source directory

    /home/azuryl/project/mmdeploy/third_party/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at csrc/mmdeploy/apis/python/CMakeLists.txt:26 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/home/azuryl/project/mmdeploy/build/CMakeFiles/CMakeOutput.log".
See also "/home/azuryl/project/mmdeploy/build/CMakeFiles/CMakeError.log".
```

**Comment by RunningLeon** [comment]
hi, 
1. could you check if you have clone the spdlog successfully in the third_party directory.
2. have you installed pybind11 through pip?

**Comment by azuryl** [comment]
it should git clone -b main --recursive https://github.com/open-mmlab/mmdeploy.git
but in https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/linux-x86_64.md did not introduced

**Comment by RunningLeon** [comment]
hi, it's part of building documents and you could start with here https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/build_from_source.md#build-from-source

**Comment by azuryl** [comment]
excuse me how to build Object Detection demo in X86 there is not introduced in https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/linux-x86_64.md
but in jetson https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/jetsons.md have :
Install [MMDetection](https://github.com/open-mmlab/mmdetection) which is needed for model conversion
MMDetection is an open source object detection toolbox based on PyTorch

git clone -b 3.x https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"
Follow [this document](https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/02-how-to-run/convert_model.md) on how to convert model files.
For this example, we have used [retinanet_r18_fpn_1x_coco.py](https://github.com/open-mmlab/mmdetection/blob/3.x/configs/retinanet/retinanet_r18_fpn_1x_coco.py) as the model config, and [this file](https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r18_fpn_1x_coco/retinanet_r18_fpn_1x_coco_20220407_171055-614fd399.pth) as the corresponding checkpoint file. Also for deploy config, we have used [detection_tensorrt_dynamic-320x320-1344x1344.py](https://github.com/open-mmlab/mmdeploy/tree/main/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py)

python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    $PATH_TO_MMDET/configs/retinanet/retinanet_r18_fpn_1x_coco.py \
    retinanet_r18_fpn_1x_coco_20220407_171055-614fd399.pth \
    $PATH_TO_MMDET/demo/demo.jpg \
    --work-dir work_dir \
    --show \
    --device cuda:0 \
    --dump-info
Finally run inference on an image

**Comment by RunningLeon** [comment]
hi, you need to add `-DMMDEPLOY_BUILD_EXAMPLES=ON`. as in here https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/linux-x86_64.md#build-sdk-and-demo

**Comment by RunningLeon** [comment]
hi，you could refer to this doc https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html
