### ISSUE TITLE
[Bug] How to deploy soft-teacher on jetson nano

### ISSUE THREAD

**Issue by zqd-big** [open-mmlab/mmdeploy#2437]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

**I use:**
 python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    /home/zqd/mmdeploy/config.py \
    iter_180000.pth \
    15513434.jpg \
    --work-dir work_dir2 \
    --show \
    --device cuda:0 \
    --dump-info
**and here is bug:**
Traceback (most recent call last):
  File "./tools/deploy.py", line 309, in <module>
    main()
  File "./tools/deploy.py", line 134, in main
    device=args.device)
  File "/home/zqd/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 348, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)
  File "/home/zqd/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 285, in get_pipeline
    deploy_cfg, model_cfg, work_dir, device=device)
  File "/home/zqd/mmdeploy/mmdeploy/backend/sdk/export_info.py", line 233, in get_postprocess
    post_processor = task_processor.get_postprocess(work_dir)
  File "/home/zqd/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 306, in get_postprocess
    params = self.model_cfg.model.test_cfg
  File "/home/zqd/archiconda3/envs/mmdeploy/lib/python3.6/site-packages/mmengine/config/config.py", line 53, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'

### Reproduction

**I use:**
 python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    /home/zqd/mmdeploy/config.py \
    iter_180000.pth \
    15513434.jpg \
    --work-dir work_dir2 \
    --show \
    --device cuda:0 \
    --dump-info

### Environment

```Shell
Package            Version   Editable project location
------------------ --------- -------------------------
addict             2.4.0
aenum              3.1.15
appdirs            1.4.4
cycler             0.11.0
Cython             0.29
dataclasses        0.8
decorator          5.1.1
dill               0.3.4
grpcio             1.48.2
h5py               2.9.0rc1
importlib-metadata 4.8.3
kiwisolver         1.3.1
Mako               1.1.6
MarkupSafe         2.0.1
matplotlib         3.3.4
mmcv               2.0.0rc1  /home/zqd/mmcv-2.0.0rc1
mmdeploy           1.0.0rc2  /home/zqd/mmdeploy
mmdet              3.0.0rc4  /home/zqd/mmdetection
mmengine           0.4.0
mpmath             1.3.0
multiprocess       0.70.12.2
ndindex            1.4
numpy              1.19.5
onnx               1.11.0
opencv-python      4.8.0.76
packaging          21.3
Pillow             8.4.0
pip                21.3.1
platformdirs       2.4.0
prettytable        2.5.0
protobuf           3.19.6
pycocotools        2.0.7
pycuda             2020.1
pyparsing          3.1.1
python-dateutil    2.8.2
pytools            2022.1.12
PyYAML             6.0.1
scipy              1.5.4
setuptools         58.0.4
six                1.16.0
sympy              1.9
tensorrt           8.2.1.8
termcolor          1.1.0
terminaltables     3.1.10
torch              1.10.0
torchvision        0.11.1    /home/zqd/torchvision
typing_extensions  4.1.1
versioned-hdf5     1.2
wcwidth            0.2.6
wheel              0.37.1
yapf               0.32.0
zipp               3.6.0
```

**Comment by RunningLeon** [comment]
@zqd-big hi, seems your custom model config does not follow mmdet style. Could you change it and make it run with mmdet's `image_demo.py`.

**Comment by zqd-big** [comment]
> 嗨，您的自定义模型配置似乎不遵循 MMDET 样式。你能改变它并让它与 mmdet 一起运行吗？`image_demo.py`

Hello, my config file was pasted from mmdetection's workdir. Do I need to put it in mmdet

**Comment by RunningLeon** [comment]
can you run with https://github.com/open-mmlab/mmdetection/blob/main/demo/image_demo.py? maybe you could post your model cfg in here.
