### ISSUE TITLE
Adding CO-DETR export to onnx

### ISSUE THREAD

**Issue by MarouaneMja** [open-mmlab/mmdeploy#2440]
### Motivation

Hello,

Currently, the CO-DETR model has achieved the best results on the COCO-test-dev set for object detection. Are you considering adding the model export to various backends, particularly ONNX?"

Sincerely,
Marouane

### Related resources

Here is leader board of the best models in object detection : https://paperswithcode.com/sota/object-detection-on-coco

**Comment by RunningLeon** [comment]
hi, currenty we have no plan, but you can fill your request in this issue: https://github.com/open-mmlab/mmdeploy/issues/170

**Comment by MarouaneMja** [comment]
Hello, thank you. I have already fill the request.
