### ISSUE TITLE
Does the Inference SDK support batch inference？

### ISSUE THREAD

**Issue by flytocc** [open-mmlab/mmdeploy#2444]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

When I test the object detection model performance using `tools/profiler.py`, the per-image inference latency decreases with increasing batch size. However, when I run the same test using the Inference SDK (C#), a larger batch size can not to reduce the inference latency.

When I check the problem, I found the following code:

https://github.com/open-mmlab/mmdeploy/blob/71a1e6cc1859d8692cea134946bdc249ad0e5400/csrc/mmdeploy/net/net_module.cpp#L222-L230

It seems that each image will be processed step by step, not batched.

In Python Convert Inference pipeline, the `data_preprocessor` will form a batch inputs from images. There doesn't seem to be this step in the Inference SDK?

### Reproduction

none

### Environment

```Shell
none
```

### Error traceback

```Shell
none
```

**Comment by irexyc** [comment]
For batch inference, you have to add this line `"is_batched": true,` to `pipeline.json`, you can refer to this reply https://github.com/open-mmlab/mmdeploy/issues/839#issuecomment-1206029364

**Comment by flytocc** [comment]
The officials don't seem to believe this issue exists, as they think batched inference is working correctly. I'm not sure if I'm using it incorrectly.
Perhaps you could open another issue to address this problem.
