### ISSUE TITLE
when I try to convert mvxnet pytorch model into onnx，it report: ONNX export failed: Couldn't export Python operator _DynamicScatter[Bug] 

### ISSUE THREAD

**Issue by wangjunquan911** [open-mmlab/mmdeploy#2460]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

09/25 03:32:47 - mmengine - INFO - Execute onnx optimize passes.
09/25 03:32:47 - mmengine - WARNING - Can not optimize model, please build torchscipt extension.
More details: https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/experimental/onnx_optimizer.md
Traceback (most recent call last):
  File "/data/mmdeploy/tools/torch2onnx.py", line 97, in <module>
    main()
  File "/data/mmdeploy/tools/torch2onnx.py", line 59, in main
    torch2onnx(
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/data/mmdeploy/mmdeploy/apis/onnx/export.py", line 138, in export
    torch.onnx.export(
  File "/opt/conda/envs/openmmlab/lib/python3.9/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/envs/openmmlab/lib/python3.9/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/envs/openmmlab/lib/python3.9/site-packages/torch/onnx/utils.py", line 737, in _export
    proto, export_map, val_use_external_data_format = graph._export_onnx(
RuntimeError: ONNX export failed: Couldn't export Python operator _DynamicScatter

### Reproduction

I run modified mmdeploy for mvxnet. 

### Environment

```Shell
09/25 03:45:17 - mmengine - INFO - 

09/25 03:45:17 - mmengine - INFO - **********Environmental information**********
09/25 03:45:18 - mmengine - INFO - sys.platform: linux
09/25 03:45:18 - mmengine - INFO - Python: 3.9.0 (default, Nov 15 2020, 14:28:56) [GCC 7.3.0]
09/25 03:45:18 - mmengine - INFO - CUDA available: True
09/25 03:45:18 - mmengine - INFO - numpy_random_seed: 2147483648
09/25 03:45:18 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3060
09/25 03:45:18 - mmengine - INFO - CUDA_HOME: /usr/local/cuda
09/25 03:45:18 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
09/25 03:45:18 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
09/25 03:45:18 - mmengine - INFO - PyTorch: 1.10.1+cu111
09/25 03:45:18 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

09/25 03:45:18 - mmengine - INFO - TorchVision: 0.11.2+cu111
09/25 03:45:18 - mmengine - INFO - OpenCV: 4.8.0
09/25 03:45:18 - mmengine - INFO - MMEngine: 0.8.2
09/25 03:45:18 - mmengine - INFO - MMCV: 2.0.1
09/25 03:45:18 - mmengine - INFO - MMCV Compiler: GCC 7.3
09/25 03:45:18 - mmengine - INFO - MMCV CUDA Compiler: 11.1
09/25 03:45:18 - mmengine - INFO - MMDeploy: 1.3.0+1132e82
09/25 03:45:18 - mmengine - INFO - 

09/25 03:45:18 - mmengine - INFO - **********Backend information**********
09/25 03:45:18 - mmengine - INFO - tensorrt:	None
09/25 03:45:18 - mmengine - INFO - ONNXRuntime:	None
09/25 03:45:18 - mmengine - INFO - ONNXRuntime-gpu:	1.8.1
09/25 03:45:18 - mmengine - INFO - ONNXRuntime custom ops:	NotAvailable
09/25 03:45:18 - mmengine - INFO - pplnn:	None
09/25 03:45:18 - mmengine - INFO - ncnn:	None
09/25 03:45:18 - mmengine - INFO - snpe:	None
09/25 03:45:18 - mmengine - INFO - openvino:	None
09/25 03:45:18 - mmengine - INFO - torchscript:	1.10.1+cu111
09/25 03:45:18 - mmengine - INFO - torchscript custom ops:	NotAvailable
09/25 03:45:18 - mmengine - INFO - rknn-toolkit:	None
09/25 03:45:18 - mmengine - INFO - rknn-toolkit2:	None
09/25 03:45:18 - mmengine - INFO - ascend:	None
09/25 03:45:18 - mmengine - INFO - coreml:	None
09/25 03:45:18 - mmengine - INFO - tvm:	None
09/25 03:45:18 - mmengine - INFO - vacc:	None
09/25 03:45:18 - mmengine - INFO - 

09/25 03:45:18 - mmengine - INFO - **********Codebase information**********
09/25 03:45:18 - mmengine - INFO - mmdet:	3.0.0
09/25 03:45:18 - mmengine - INFO - mmseg:	None
09/25 03:45:18 - mmengine - INFO - mmpretrain:	None
09/25 03:45:18 - mmengine - INFO - mmocr:	None
09/25 03:45:18 - mmengine - INFO - mmagic:	None
09/25 03:45:18 - mmengine - INFO - mmdet3d:	1.1.1
09/25 03:45:18 - mmengine - INFO - mmpose:	None
09/25 03:45:18 - mmengine - INFO - mmrotate:	None
09/25 03:45:18 - mmengine - INFO - mmaction:	None
09/25 03:45:18 - mmengine - INFO - mmrazor:	None
09/25 03:45:18 - mmengine - INFO - mmyolo:	None

Process finished with exit code 0
```

**Comment by RunningLeon** [comment]
hi, mvxnet is not supported:  https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet3d.html#supported-models. I'm afraid you have to do the torch2onnx on your own.
