### ISSUE TITLE
Could you release a example of converting swin mmdet into onnx?

### ISSUE THREAD

**Issue by Bryce-HJ** [open-mmlab/mmdeploy#247]
I have trained a swin transformer model on my own dataset, i want to embeded it into edge device, so could you release a example of converting swin mmdet into onnx? 
Thanks!!!!

**Comment by lvhan028** [comment]
Hi, transformer model deployment is not a snap. We are gonna do the job in April on the target devices  x86_64 cpu and the NVIDIA GPU. So, what's your target edge device?

**Comment by Bryce-HJ** [comment]
> 

Hi，my device is 晶晨A311D，i'd appreciate about your future job! Thanks~

**Comment by lvhan028** [comment]
Make swin transformer deployment as a future feature of MMDeploy. Close this issue for now
