### ISSUE TITLE
[Feature] Support for FP16 ONNX Model Conversion in MMDeploy for Segformer

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [open-mmlab/mmdeploy#2477]
### Motivation

When converting the Segformer model from PyTorch to a TensorRT (TRT) engine using FP16, the resulting TRT engine produces incorrect inference results. This issue arises during the conversion of an FP32 ONNX model to an FP16 TRT engine.

A workaround to this issue is to first convert the PyTorch model to an FP16 ONNX model. Subsequently, converting this FP16 ONNX model to an FP32 TRT engine results in correct inference outcomes.

I propose to add this feature to MMDeploy to facilitate the correct conversion and subsequent inference when utilizing FP16 models.

**Comment by rpl-alan-shangguan** [comment]
using opset_version=17 also solves the problem.

**Comment by RunningLeon** [comment]
hi, thanks for your info. Maybe using `opset_version=17` is a more reasonable solution.

> using opset_version=17 also solves the problem.
