### ISSUE TITLE
[Bug]  Cant set size of ONNX export

### ISSUE THREAD

**Issue by GeorgePearse** [open-mmlab/mmdeploy#2478]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I would like to be able to run models over 500x832 images, but the input_shape argument in the export config currently seems to have no impact. 

(For context, the current resulting exports require 1920x1088, which I'm assuming I must have set somewhere, because it's very appropriate for most of our problems, but I can't find it)

### Reproduction

This is my export config
```
onnx_config = dict(
    type='onnx',
    export_params=True,
    keep_initializers_as_inputs=False,
    opset_version=11,
    save_file='end2end.onnx',
    input_names=['input'],
    output_names=['dets', 'labels'],
    input_shape=[500,832],
    optimize=True
)

codebase_config = dict(
    type='mmdet',
    task='ObjectDetection',
    model_type='end2end',
    post_processing=dict(
        score_threshold=0.05,
        confidence_threshold=0.005,  # for YOLOv3
        iou_threshold=0.5,
        max_output_boxes_per_class=200,
        pre_top_k=5000,
        keep_top_k=100,
        background_label_id=-1,
    ))

backend_config = dict(type='onnxruntime')

```
I just use this, and the out of the box tools/deploy.py script. 

### Environment

```Shell
Latest mmdet, mmcv and mmengine.
```

**Comment by RunningLeon** [comment]
hi, you can set `input_shape`
```
_base_ = ['./detection_onnxruntime_static.py']

onnx_config = dict(input_shape=[832, 500])
```

**Comment by GeorgePearse** [comment]
Hi @RunningLeon 

I'm fairly confident that your response is incorrect. Changing this value does not impact images that the model can be run on , but changing some values within the model config does. At the minute I'm using a catchall and replacing the values in the config that I know the models are currently exported to, with what I want them to be, and it's working

**Comment by RunningLeon** [comment]
hi, changing `input_shape` for the official model config with static shape deploy config. Maybe you could post your `test_pipeline` in model config and let's see if there's something we can do.
