### ISSUE TITLE
About "mmdeploy_classifier_create_by_path"

### ISSUE THREAD

**Issue by TTgogogo** [open-mmlab/mmdeploy#248]
In the function mmdeploy_classifier_create_by_path(model_path, device_name, 0, &classifier), does "model_path" mean the path of the .pth model file?

**Comment by lvhan028** [comment]
No, it's path of mmclassification **sdk model exported by mmdeploy model converter**.
It is actually the `--work-dir` argument of `tools/deploy.py`. And it HAS TO pass `--dump-info` when converting a PyTorch model.
You can find the detail in https://mmdeploy.readthedocs.io/en/latest/get_started.html

**Comment by TTgogogo** [comment]
@lvhan028 Could you provide a detailed example of how to use the function?

**Comment by lvhan028** [comment]
As I said previously, "it's path of mmclassification **sdk model exported by mmdeploy model converter.**"

Let's see how MMDeploy Converter exports SDK model. The following command is an example to convert and export faster-rcnn training model to SDK model, which is presented in [get_started](https://mmdeploy.readthedocs.io/en/latest/get_started.html)
```bash
python ${MMDEPLOY_DIR}/tools/deploy.py \
    ${MMDEPLOY_DIR}/configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    ${MMDET_DIR}/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    ${CHECKPOINT_DIR}/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    ${INPUT_IMG} \
    --work-dir ${WORK_DIR} \
    --device cuda:0 \
    --dump-info
```
- `${MMDEPLOY_DIR}`: the root path of mmdeploy's source code
- `${MMDET_DIR}`: the root path of mmdetection's source code
- `${CHECKPOINT_DIR}`: the directory where you save the trained model
- `${INPUT_IMG}`: the input image
- `${WORK_DIR}`: the directory where you want mmdeploy to save the deployed model. In the above example, the deployed model means the tensorrt model. 
- `--dump-info`: exporting the meta information of the deployed model

When the above command executes successfully, you will find a bunch of files in `${WORK_DIR}`. They as a whole make up what we called the SDK model. So, the `model_path` in `mmdeploy_xxxx_create_by_path` means `${WORK_DIR}`
