### ISSUE TITLE
[Bug] mmrotate 我用c++做推理时 发现模型中的pipeline里面的tasks里面的transforms里面有ConvertBoxType就会导致崩溃

### ISSUE THREAD

**Issue by gstariarch** [open-mmlab/mmdeploy#2480]
### Checklist

- [x] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

原因是c++中无法创建这个ConvertBoxType对应的函数 导致空指针
{
    "pipeline": {
        "input": [
            "img"
        ],
        "output": [
            "post_output"
        ],
        "tasks": [
            {
                "type": "Task",
                "module": "Transform",
                "name": "Preprocess",
                "input": [
                    "img"
                ],
                "output": [
                    "prep_output"
                ],
                "transforms": [
                    {
                        "type": "LoadImageFromFile",
                        "file_client_args": {
                            "backend": "disk"
                        }
                    },
                    {
                        "type": "Resize",
                        "keep_ratio": false,
                        "size": [
                            1024,
                            1024
                        ]
                    },
                    {
                        "type": "Pad",
                        "size": [
                            1024,
                            1024
                        ],
                        "pad_val": {
                            "img": [
                                114,
                                114,
                                114
                            ]
                        }
                    },
                    {
                        "type": "ConvertBoxType",
                        "box_type_mapping": {
                            "gt_bboxes": "rbox"
                        }
                    },
                    {
                        "type": "Normalize",
                        "to_rgb": false,
                        "mean": [
                            103.53,
                            116.28,
                            123.675
                        ],
                        "std": [
                            57.375,
                            57.12,
                            58.395
                        ]
                    },
                    {
                        "type": "Pad",
                        "size_divisor": 1
                    },
                    {
                        "type": "DefaultFormatBundle"
                    },
                    {
                        "type": "Collect",
                        "meta_keys": [
                            "img_norm_cfg",
                            "flip_direction",
                            "img_path",
                            "filename",
                            "img_shape",
                            "valid_ratio",
                            "ori_shape",
                            "scale_factor",
                            "pad_shape",
                            "flip",
                            "ori_filename",
                            "img_id"
                        ],
                        "keys": [
                            "img"
                        ]
                    }
                ]
            },
            {
                "name": "mmdet.rtmdet",
                "type": "Task",
                "module": "Net",
                "is_batched": false,
                "input": [
                    "prep_output"
                ],
                "output": [
                    "infer_output"
                ],
                "input_map": {
                    "img": "input"
                },
                "output_map": {}
            },
            {
                "type": "Task",
                "module": "mmrotate",
                "name": "postprocess",
                "component": "ResizeRBBox",
                "params": {
                    "nms_pre": 2000,
                    "min_bbox_size": 0,
                    "score_thr": 0.05,
                    "nms": {
                        "type": "nms_rotated",
                        "iou_threshold": 0.1
                    },
                    "max_per_img": 2000
                },
                "output": [
                    "post_output"
                ],
                "input": [
                    "prep_output",
                    "infer_output"
                ]
            }
        ]
    }
}

### Reproduction

mmdeploy_rotated_detector_apply

### Environment

```Shell
vs2022 c++
```

**Comment by RunningLeon** [comment]
so you may have to support ConvertBoxType in csrc

**Comment by gstariarch** [comment]
是的
