### ISSUE TITLE
[Feature] Any prebuilted mmdeploy>=1.0.0 which supporting CUDA 10.2?

### ISSUE THREAD

**Issue by MR-hyj** [open-mmlab/mmdeploy#2485]
### Motivation

My environment:
- mmcls=1.0.0rc6
- mmcv=2.0.0
- mmdet=3.1.0
- mmengine=0.8.5
- mmrazor=1.0.0rc2
- mmyolo=0.6.0
- torch=1.10.1+cu102
- torchvision=0.11.2+cu102

I'm trying convert a `.pth` to `.onnx`, but there seems no release of mmdeploy==1.3.0 supporting CUDA10.2 in this repo, which means I have to build from source. Unfortunately, I don't have the root permission on my Centos7.

**Comment by RunningLeon** [comment]
hi, sorry for the trouble. We don't have prebuilt packages with cuda10.2.

**Comment by MR-hyj** [comment]
> hi, sorry for the trouble. We don't have prebuilt packages with cuda10.2.

that's unfortunate. guess I have to think of other solutions...
Thank you all the same
