### ISSUE TITLE
请问什么时候能支持 grounding dino训练输出的模型 转成Onnx格式

### ISSUE THREAD

**Issue by formance** [open-mmlab/mmdeploy#2503]
### Motivation

grounding dino训练模型部署

**Comment by RunningLeon** [comment]
hi, we have no plan to support this model due to the lack of resources. Welcome to PR us.

**Comment by formance** [comment]
> hi, we have no plan to support this model due to the lack of resources. Welcome to PR us.

got it, thank your reply!

**Comment by QzYER** [comment]
> hi, we have no plan to support this model due to the lack of resources. Welcome to PR us.

I have successfully transferred the engine file, but the output accuracy and pytorch cannot be aligned. May I ask if you have resolved it?

**Comment by blacksino** [comment]
> > hi, we have no plan to support this model due to the lack of resources. Welcome to PR us.
> 
> I have successfully transferred the engine file, but the output accuracy and pytorch cannot be aligned. May I ask if you have resolved it?

same problem

**Comment by Hongyuan-Liu** [comment]
> > > 嗨，由于缺乏资源，我们没有计划支持此模型。欢迎来到公关我们。
> > 
> > 
> > 我已成功传输引擎文件，但输出精度和 pytorch 无法对齐。请问你有没有解决过这个问题？
> 
> 同样的问题

你好，我转换的时候报Exporting the operator 'aten::__ior_' to ONNX opset version 16 is not supported.的问题，opset 设置成19都是这个问题，为什么你们没有遇到？我的torch版本是2.0.1

**Comment by xiyangyang99** [comment]
我们也是精度无法对其，需要将一些算子替换。tokenzier无法onnx，需要拆分结构。你们mmdetection的兄弟不是说你们1月份开源GD的加速嘛？现在yolo-world貌似可以替换GD了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 上午8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdeploy] 请问什么时候能支持 grounding dino训练输出的模型 转成Onnx格式 (Issue #2503)





    
嗨，由于缺乏资源，我们没有计划支持此模型。欢迎来到公关我们。
  
我已成功传输引擎文件，但输出精度和 pytorch 无法对齐。请问你有没有解决过这个问题？
  
同样的问题
  
你好，我转换的时候报Exporting the operator 'aten::_ior' to ONNX opset version 16 is not supported.的问题，opset 设置成19都是这个问题，为什么你们没有遇到？我的torch版本是2.0.1

**Comment by shiyongde** [comment]
mmd是不是没人维护了？ 感觉都没更新了

**Comment by yu1206** [comment]
AttributeError: 'DetDataSample' object has no attribute 'text'

**Comment by yu1206** [comment]
grouding dino 转 onnx时，AttributeError: 'DetDataSample' object has no attribute 'text'

**Comment by h030162** [comment]
DetDataSample' object has no attribute 'text'

**Comment by yu1206** [comment]
&nbsp;请问什么时候能支持 grounding dino训练输出的模型 转成Onnx格式
------------
