### ISSUE TITLE
[Bug] MMdeploy Python api

### ISSUE THREAD

**Issue by wahaha** [open-mmlab/mmdeploy#2504]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

When I used MMdeploy python api to inference one image, I find that the results were different every time I inferenced. 

### Reproduction

# Copyright (c) OpenMMLab. All rights reserved.
import argparse

import cv2
from mmdeploy_runtime import Detector
import time

def parse_args():
    parser = argparse.ArgumentParser(
        description='show how to use sdk python api')
    parser.add_argument('--device_name', default='cpu', help='name of device, cuda or cpu')
    parser.add_argument(
        '--model_path',
        default= r"D:\Estun_Projects\Deploy\v130\workpieceDeploy\CPU\rtmdet\MMDeploy\trt\workpieceTest4\rtmdet\rtmdet-ins_tiny_8xb32-300e_coco\20231008\v1",
        help='path of mmdeploy SDK model dumped by model converter')
    parser.add_argument('--image_path',
                        default=r'D:\Estun_Projects\DataSet\workpiece\workpiece_test\2_crop\0.png',
                        help='path of an image')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    img = cv2.imread(args.image_path)
    T1_start = time.time()
    detector = Detector(
        model_path=args.model_path, device_name=args.device_name, device_id=0)
    bboxes, labels, masks = detector(img)

    T1_end= time.time()
    print("The time consuming of load model: %s ms" % ((T1_end - T1_start) * 1000))
    indices = [i for i in range(len(bboxes))]
    for index, bbox, label_id in zip(indices, bboxes, labels):
        [left, top, right, bottom], score = bbox[0:4].astype(int), bbox[4]
        if score < 0.8:
            continue

        cv2.rectangle(img, (left, top), (right, bottom), (0, 0, 255))

        if masks[index].size:
            mask = masks[index]
            blue, green, red = cv2.split(img)
            mask_img = blue[top:top + mask.shape[0], left:left + mask.shape[1]]

            cv2.bitwise_or(mask, mask_img, mask_img)
            # cv2.imshow("mask_img", mask_img)
            # cv2.waitKey(0)
            img = cv2.merge([blue, green, red])

    # cv2.imwrite('output_detection.png', img)
    cv2.imshow("output_detection.png", img)
    cv2.waitKey(0)

if __name__ == '__main__':
    main()

### Environment

```Shell
10/19 10:05:12 - mmengine - INFO - **********Environmental information**********
10/19 10:05:21 - mmengine - INFO - sys.platform: win32
10/19 10:05:21 - mmengine - INFO - Python: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
10/19 10:05:21 - mmengine - INFO - CUDA available: True
10/19 10:05:21 - mmengine - INFO - numpy_random_seed: 2147483648
10/19 10:05:21 - mmengine - INFO - GPU 0: NVIDIA GeForce GTX 1660 Ti
10/19 10:05:21 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
10/19 10:05:21 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.105
10/19 10:05:21 - mmengine - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30148 版
10/19 10:05:21 - mmengine - INFO - GCC: n/a
10/19 10:05:21 - mmengine - INFO - PyTorch: 1.8.0
10/19 10:05:21 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

10/19 10:05:21 - mmengine - INFO - TorchVision: 0.9.0
10/19 10:05:21 - mmengine - INFO - OpenCV: 4.6.0
10/19 10:05:21 - mmengine - INFO - MMEngine: 0.8.3
10/19 10:05:21 - mmengine - INFO - MMCV: 2.0.0
10/19 10:05:21 - mmengine - INFO - MMCV Compiler: MSVC 192829924
10/19 10:05:21 - mmengine - INFO - MMCV CUDA Compiler: 11.1
10/19 10:05:21 - mmengine - INFO - MMDeploy: 1.3.0+
10/19 10:05:21 - mmengine - INFO - 

10/19 10:05:21 - mmengine - INFO - **********Backend information**********
10/19 10:05:21 - mmengine - INFO - tensorrt:	8.2.3.0
10/19 10:05:21 - mmengine - INFO - tensorrt custom ops:	NotAvailable
10/19 10:05:22 - mmengine - INFO - ONNXRuntime:	1.8.1
10/19 10:05:22 - mmengine - INFO - ONNXRuntime-gpu:	None
10/19 10:05:22 - mmengine - INFO - ONNXRuntime custom ops:	Available
10/19 10:05:22 - mmengine - INFO - pplnn:	None
10/19 10:05:22 - mmengine - INFO - ncnn:	None
10/19 10:05:22 - mmengine - INFO - snpe:	None
10/19 10:05:22 - mmengine - INFO - openvino:	2022.3.0
10/19 10:05:22 - mmengine - INFO - torchscript:	1.8.0
10/19 10:05:22 - mmengine - INFO - torchscript custom ops:	NotAvailable
10/19 10:05:22 - mmengine - INFO - rknn-toolkit:	None
10/19 10:05:22 - mmengine - INFO - rknn-toolkit2:	None
10/19 10:05:22 - mmengine - INFO - ascend:	None
10/19 10:05:22 - mmengine - INFO - coreml:	None
10/19 10:05:22 - mmengine - INFO - tvm:	None
10/19 10:05:22 - mmengine - INFO - vacc:	None
10/19 10:05:22 - mmengine - INFO - 

10/19 10:05:22 - mmengine - INFO - **********Codebase information**********
10/19 10:05:22 - mmengine - INFO - mmdet:	3.0.0
10/19 10:05:22 - mmengine - INFO - mmseg:	None
10/19 10:05:22 - mmengine - INFO - mmpretrain:	None
10/19 10:05:22 - mmengine - INFO - mmocr:	None
10/19 10:05:22 - mmengine - INFO - mmagic:	None
10/19 10:05:22 - mmengine - INFO - mmdet3d:	None
10/19 10:05:22 - mmengine - INFO - mmpose:	None
10/19 10:05:22 - mmengine - INFO - mmrotate:	None
10/19 10:05:22 - mmengine - INFO - mmaction:	None
10/19 10:05:22 - mmengine - INFO - mmrazor:	None
10/19 10:05:22 - mmengine - INFO - mmyolo:	None

Process finished with exit code 0
```

**Comment by RunningLeon** [comment]
hi, this is a bit strange and could you use docker image to reproduce it? https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/build_from_docker.html
