### ISSUE TITLE
Support Mask2former for semantic segmentation [Feature] 

### ISSUE THREAD

**Issue by gnscc** [open-mmlab/mmdeploy#2508]
### Motivation

It would be amazing to support the deployment of MMSegmentation Mask2former models. I'm aware of #2347 but this does not solve the issue for semantic segmentation.

### Additional context

Even though I realize is not supported, I tried to follow the steps to deploy a mask2former model and the result feels like is almost there. Using [segmentation_tensorrt_static-512x512.py](https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmseg/segmentation_tensorrt_static-512x512.py), I had to add ```onnx_config.opset_version=12``` to be able to perform the einsum operation.
After that, everything compiles (with a lot of warnings) and provides valid output files. However, when I do the inference with the SDK I get a mask out of place, much bigger than the actual object and some pixels spaced between the pixels that actually conform the mask.
![image](https://github.com/open-mmlab/mmdeploy/assets/56470395/c1426ca7-ddf8-4aad-bf64-6ab8607bc86c)

Looking forward to get this amazing feature to be able to run this model in production! 
Thanks in advance

**Comment by AnushaManila** [comment]
@gnscc 
Could you please provide details on the steps you followed to deploy a mask2former model?
Where did you set onnx_config.opset_version=12? 
Was that in the file "segmentation_tensorrt_static-512x512.py"?

I used the below command
python ./tools/deploy.py '/mmdeploy/configs/mmseg/segmentation_tensorrt_static-512x1024.py' '/mmsegmentation/configs/mask2former/mask2former_r50_8xb2-90k_cityscapes-512x1024.py' '/model_final_4ab90c_R50_Cityscape_Panoptic.pkl' '/sample_test_images/0910_front.png' --work-dir work_dir --show --device cuda:0

But Im getting RuntimeError
RuntimeError: Invalid magic number; corrupt file?

**Comment by gnscc** [comment]
This is the segmentation_tensorrt_static-512x512.py modified. Notice that on line 3 ```opset_version=12``` is added:

```python3
_base_ = ['./segmentation_static.py', '../_base_/backends/tensorrt.py']

onnx_config = dict(input_shape=[512, 512], opset_version=12)
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 512, 512],
                    opt_shape=[1, 3, 512, 512],
                    max_shape=[1, 3, 512, 512])))
    ])

```

And this is how I execute the command. Notcie that I use the ```.pth``` model:
```bash
python3 mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmseg/segmentation_tensorrt_static-512x512.py \
    train_dir/cfg.py \
    train_dir/work_dir/best_mIoU_iter_30000.pth \
    test_img.bmp \
    --work-dir work_dir --device cuda --dump-info
```

**Comment by AnushaManila** [comment]
Thank you @gnscc for a quick response, appreciate it!

1. I used the script from the link here (https://github.com/facebookresearch/Mask2Former/issues/85#issuecomment-1105995081) 
to convert pkl to pth. 

2. I also tried doing 
`torch.save(demo.predictor.model.state_dict(), 'checkpoint.pth')`
after loading the pkl and before running inference

The conversion of 'pth' to onnx and then to 'trt'  seemed to be fine. But nothing changed in the state dict.
However, I used the pth model anyway and the inference using the 'pth' and 'trt' modes both are giving wrong outputs.

The output of deploy.py lists a bunch of **unexpected keys** and **missing keys** in source state_dict.

` python ./tools/deploy.py '/mmdeploy/configs/mmseg/segmentation_tensorrt_static-512x1024.py' '/mmsegmentation/configs/mask2former/mask2former_r50_8xb2-90k_cityscapes-512x1024.py' 'model_final_4ab90c_R50_Cityscape_Panoptic.pth' '/Sample_test_images/0910_front.png' --work-dir work_dir --show --device cuda:0`


`**unexpected key** in source state_dict: sem_seg_head.pixel_decoder.input_proj.0.0.weight, sem_seg_head.pixel_decoder.input_proj.0.0.bias, sem_seg_head.pixel_decoder.input_proj.0.1.weight, .
.....
backbone.res5.2.conv3.norm.num_batches_tracked

**missing keys in source state_dict:** backbone.conv1.weight, backbone.bn1.weight, backbone.bn1.bias, 
...,
decode_head.mask_embed.2.bias, decode_head.mask_embed.4.weight, decode_head.mask_embed.4.bias`



I found a script to convert pkl to pth for mask2transformer in [HuggingFace repo](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mask2former/convert_mask2former_original_pytorch_checkpoint_to_pytorch.py#L718).
I wish there was a way to convert mask2transformers pkl to pth without setting up the HugginFace transformers!

But how did you save the pth file?

**Comment by gnscc** [comment]
I just use a modified version of the [ADE20k example config](https://github.com/open-mmlab/mmsegmentation/blob/main/configs/mask2former/mask2former_swin-s_8xb2-160k_ade20k-512x512.py) to TRAIN the model. Then I get the pth model in the specified work_dir and deploy it as I stated before.

When deploying I experienced that it is normal to see many warnings, the model still works fine if the predictions are parsed properly.

Here is an example of the code that I use to generate a config training file for mmsegmentation that suits my need. The script basically gets the config example and changes the key aspects that I need to modify:

```python
import mmengine
import os

current_dir = os.path.dirname(os.path.abspath(__file__))

# Load config
cfg = mmengine.Config.fromfile(os.path.join(current_dir, '../../../mmsegmentation/configs/mask2former/mask2former_swin-s_8xb2-160k_ade20k-512x512.py'))

# Override config
cfg.data_root = '/home/user/datasets/my_dataset'
cfg.dataset_type = 'MyDataset'
cfg.num_classes = 2

cfg.train_dataloader.batch_size = 8

cfg.train_dataloader.dataset.data_root = cfg.data_root
cfg.train_dataloader.dataset.type = cfg.dataset_type
cfg.val_dataloader.dataset.data_root = cfg.data_root
cfg.val_dataloader.dataset.type = cfg.dataset_type
cfg.test_dataloader.dataset.data_root = cfg.data_root
cfg.test_dataloader.dataset.type = cfg.dataset_type

cfg.train_pipeline[1] = dict(type='LoadAnnotations', reduce_zero_label=False)
cfg.test_pipeline[2] = dict(type='LoadAnnotations', reduce_zero_label=False)
cfg.train_dataloader.dataset.pipeline[1] = dict(type='LoadAnnotations', reduce_zero_label=False)
cfg.val_dataloader.dataset.pipeline[2] = dict(type='LoadAnnotations', reduce_zero_label=False)
cfg.test_dataloader.dataset.pipeline[2] = dict(type='LoadAnnotations', reduce_zero_label=False)

cfg.model.decode_head.num_classes = cfg.num_classes
cfg.model.decode_head.loss_cls.class_weight = [0.4, 1.0, 0.1]

cfg.work_dir = os.path.join(current_dir, 'work_dir')
print(f'Config:\n{cfg.pretty_text}')

cfg.dump(os.path.join(current_dir, 'cfg.py'))
```
This outputs a ```cfg.py``` that I will use to train the model:
```bash
python3 mmsegmentation/tools/train.py path/to/project/cfg.py
```

I hope that this clarifies how to train a mask2former model in mmsegmentation.

**Comment by AnushaManila** [comment]
Thank you so much @gnscc, definitely clarifies my question earlier.
Appreciate your response!
