### ISSUE TITLE
[Bug] TENSORRT_DIR path in mmdeploy_builder.py

### ISSUE THREAD

**Issue by ilya-sha** [open-mmlab/mmdeploy#2514]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

**Crash on checking version of tensorrt.**

Line 182
```
    if osp.exists(TENSORRT_DIR):
        with open(
                osp.join(TENSORRT_DIR, 'include', 'NvInferVersion.h'),
                mode='r') as f:
            data = f.read()
            major = re.search(r'#define NV_TENSORRT_MAJOR (\d+)', data)
            minor = re.search(r'#define NV_TENSORRT_MINOR (\d+)', data)
            patch = re.search(r'#define NV_TENSORRT_PATCH (\d+)', data)
            build = re.search(r'#define NV_TENSORRT_BUILD (\d+)', data)
            if major is not None and minor is not None and patch is not None \
                    and build is not None:
                tensorrt_version = (f'{major.group(1)}.' +
                                    f'{minor.group(1)}.' +
                                    f'{patch.group(1)}.' + f'{build.group(1)}')

    env_info['trt_v'] = tensorrt_version

    return env_info
```

osp.join(TENSORRT_DIR, 'include', 'NvInferVersion.h'),
Please remove the **'include'** from the join operation.
"include" is not always existing in tensorrt path. The script fails due to this.

➜  ~ find /usr -name 'NvInferVersion.h'
**/usr/include/aarch64-linux-gnu/NvInferVersion.h**

➜  ~ find /usr -name 'NvInferVersion.h'
**/usr/include/x86_64-linux-gnu/NvInferVersion.h**

➜  ~ find tensorrt -name 'NvInferVersion.h'
**tensorrt/TensorRT-8.2.3.0/_include_/NvInferVersion.h**

### Reproduction

In the bug description

### Environment

```Shell
All envs
```

**Comment by RunningLeon** [comment]
what is your env `TENSORRT_DIR`？ You should set as this doc: https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/tensorrt.html#install-tensorrt

**Comment by ilya-sha** [comment]
I run the build script in a docker: nvcr.io/nvidia/tensorrt:22.04-py3

![image](https://github.com/open-mmlab/mmdeploy/assets/124576571/38506346-74dd-4404-af14-71835ab9029b)

**Comment by ilya-sha** [comment]
I just don't see any purpose in having the "include" appended to the TENSORRT_DIR path separately.
You can always set the TENSORRT_DIR to include the "include" in the path in first place

**Comment by RunningLeon** [comment]
You  are building in a tensorrt docker image and the INCLUDE_DIR is `/usr/include/x86_64-linux-gnu` and LIB_DIR is `/usr/lib/x86_64-linux-gnu`. So you could do softlink  for this case.
```
export TENSORRT_DIR=/workspace/tensorrt
ln -sf /usr/lib/x86_64-linux-gnu $TENSORRT_DIR/lib
ln -sf  /usr/include/x86_64-linux-gnu $TENSORRT_DIR/include
```

**Comment by ilya-sha** [comment]
@RunningLeon Thank you for this workaround
