### ISSUE TITLE
[Feature] mask2former instance segmentation model convert to onnx

### ISSUE THREAD

**Issue by rbli-john** [open-mmlab/mmdeploy#2520]
### Motivation

Hi, do you have any plan to convert mask2Former (instance segmentation model) to ONNX format?

**Comment by RunningLeon** [comment]
hi, mask2former has been supported in this PR https://github.com/open-mmlab/mmdeploy/pull/2347. Pls. have a try.
https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html#supported-models
