### ISSUE TITLE
convert CO-DETR error

### ISSUE THREAD

**Issue by lzxpaipai** [open-mmlab/mmdeploy#2522]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

mmdetion：https://github.com/open-mmlab/mmdetection/tree/dev-3.x/projects/CO-DETR  
mmdeploy：dev-1.x
convert co-detr error:
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData

### Reproduction

no code modify

### Environment

```Shell
python:3.8
pytorch:1.8.1+cu11
mmdetion:dev-3.x
mmdeploy:dev-1.x
```

**Comment by RunningLeon** [comment]
hi, this model has not been supported according to https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html#supported-models. If you have time to support it, you may refer to this PR: https://github.com/open-mmlab/mmdeploy/pull/2410
