### ISSUE TITLE
Questions about using mmdeploy converted models

### ISSUE THREAD

**Issue by rememberBr** [open-mmlab/mmdeploy#2524]
### Motivation

I used mmdeploy to convert mobilenetV3 in mmretrain and obtained the end2end.onnx model as well as files such as deploy.json, pipeline.json, etc. The reasoning results of mmdeploy during model conversion were completely correct. When I tried to directly call the end2end.onnx reasoning model using onnxruntime, the results were incorrect. The problem may be that I overlooked some processing steps in pipeline.json. If I don't want to use mmdeploy (c++), May I ask which parameters of pipeline.json should I pay attention to and what actions should I take?

### Related resources

pipeline.json
{
    "pipeline": {
        "input": [
            "img"
        ],
        "output": [
            "post_output"
        ],
        "tasks": [
            {
                "type": "Task",
                "module": "Transform",
                "name": "Preprocess",
                "input": [
                    "img"
                ],
                "output": [
                    "prep_output"
                ],
                "transforms": [
                    {
                        "type": "LoadImageFromFile"
                    },
                    {
                        "type": "Resize",
                        "keep_ratio": true,
                        "size": [
                            224,
                            -1
                        ]
                    },
                    {
                        "pad_val": {
                            "b": 114,
                            "g": 114,
                            "r": 114
                        },
                        "size": [
                            224,
                            224
                        ],
                        "type": "Pad"
                    },
                    {
                        "type": "Normalize",
                        "to_rgb": true,
                        "mean": [
                            123.675,
                            116.28,
                            103.53
                        ],
                        "std": [
                            58.395,
                            57.12,
                            57.375
                        ]
                    },
                    {
                        "type": "ImageToTensor",
                        "keys": [
                            "img"
                        ]
                    },
                    {
                        "type": "Collect",
                        "meta_keys": [
                            "img_shape",
                            "flip_direction",
                            "ori_shape",
                            "pad_shape",
                            "flip",
                            "img_norm_cfg",
                            "filename",
                            "valid_ratio",
                            "scale_factor",
                            "ori_filename"
                        ],
                        "keys": [
                            "img"
                        ]
                    }
                ]
            },
            {
                "name": "mobilenetv3",
                "type": "Task",
                "module": "Net",
                "is_batched": false,
                "input": [
                    "prep_output"
                ],
                "output": [
                    "infer_output"
                ],
                "input_map": {
                    "img": "input"
                },
                "output_map": {}
            },
            {
                "type": "Task",
                "module": "mmcls",
                "name": "postprocess",
                "component": "StackedLinearClsHead",
                "params": {
                    "act_cfg": {
                        "type": "HSwish"
                    },
                    "dropout_rate": 0.2,
                    "in_channels": 576,
                    "init_cfg": {
                        "bias": 0.0,
                        "layer": "Linear",
                        "mean": 0.0,
                        "std": 0.01,
                        "type": "Normal"
                    },
                    "loss": {
                        "alpha": 0.25,
                        "gamma": 2.0,
                        "loss_weight": 1.0,
                        "type": "FocalLoss"
                    },
                    "mid_channels": [
                        1024
                    ],
                    "num_classes": 5,
                    "topk": 1
                },
                "output": [
                    "post_output"
                ],
                "input": [
                    "infer_output"
                ]
            }
        ]
    }
}

**Comment by irexyc** [comment]
Resize and pad are important. you can refer to original model config in mmdetection repo and align the pre/post process.
