### ISSUE TITLE
[Bug] pipeline.json中，预处理可能存在问题

### ISSUE THREAD

**Issue by Hellcat1005** [open-mmlab/mmdeploy#2528]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [x] 3. The bug has not been fixed in the latest version.

### Describe the bug

我将一个yolov8模型转换为tensorrt模型，但是评测时指标降低了2个点。我观察到，训练时使用的预处理方式为：先keep ratio resize到640，然后再letter resize，其中allow_scale_up=false。但是转换为tensorrt模型后，生成的pipeline.json中，只剩下letter resize，没有keep ratio resize，而且allow_scale_up仍然为false。当图像尺寸小于设定的训练尺寸时，此时无法将长边resize到640，和训练时的情况不一致，导致指标下降。

在pipline.json中，在letter resize前增加resize流程，或者在letter resize中，设定allow_scale_up=true，都可以解决问题。
`{
                        "type": "Resize",
                        "keep_ratio": true,
                        "size": [
                            640,
                            640
                        ]
                    },
                    {
                        "type": "LetterResize",
                        "scale": [
                            640,
                            640
                        ],
                        "allow_scale_up": false,
                        "pad_val": {
                            "img": 114
                        }
                    }`

`{
                        "type": "LetterResize",
                        "scale": [
                            640,
                            640
                        ],
                        "allow_scale_up": true,
                        "pad_val": {
                            "img": 114
                        }
                    }`

### Reproduction

无。

### Environment

```Shell
无。
```

**Comment by RunningLeon** [comment]
hi, this seems to be a bug while exporting pipeline.json, could you pull a request to fix it. You can change in this function:
https://github.com/open-mmlab/mmdeploy/blob/e31f5a68b96e3335fb3e7557e25e132f3c9a283a/mmdeploy/codebase/mmdet/deploy/object_detection.py#L242-L250

**Comment by Hellcat1005** [comment]
> hi, this seems to be a bug while exporting pipeline.json, could you pull a request to fix it. You can change in this function:
> 
> https://github.com/open-mmlab/mmdeploy/blob/e31f5a68b96e3335fb3e7557e25e132f3c9a283a/mmdeploy/codebase/mmdet/deploy/object_detection.py#L242-L250

Hello，在这段代码中，现在跳过了YOLOv5KeepRatioResize。
https://github.com/open-mmlab/mmdeploy/blob/e31f5a68b96e3335fb3e7557e25e132f3c9a283a/mmdeploy/codebase/mmdet/deploy/object_detection.py#L282-L286

我看了一下YOLOv5KeepRatioResize的实现，它会根据缩放尺度有不同的插值方式。所以如果直接用Resize来替代YOLOv5KeepRatioResize的话，这个插值方式是不是会对应不上呢？
https://github.com/open-mmlab/mmyolo/blob/8c4d9dc503dc8e327bec8147e8dc97124052f693/mmyolo/datasets/transforms/transforms.py#L106-L116
