### ISSUE TITLE
[Bug] #error C++17 or later compatible compiler is required to use PyTorch

### ISSUE THREAD

**Issue by celpas** [open-mmlab/mmdeploy#2529]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

Installation fail on MacOS 14 with PyTorch 2.1 due to `#error C++17 or later compatible compiler is required to use PyTorch.`

Similar to https://github.com/open-mmlab/mmcv/issues/2916

### Reproduction

`pip install git+https://github.com/open-mmlab/mmdeploy.git@v1.3.0`

### Environment

```Shell
Torch 2.1 installed with pip and Python 3.10.
```

### Error traceback

```Shell
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/user/opt/anaconda3/envs/det_pt2/include -fPIC -O2 -isystem /Users/user/opt/anaconda3/envs/det_pt2/include -I/Users/user/opt/anaconda3/envs/det_pt2/lib/python3.10/site-packages/torch/include -I/Users/user/opt/anaconda3/envs/det_pt2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/Users/user/opt/anaconda3/envs/det_pt2/lib/python3.10/site-packages/torch/include/TH -I/Users/user/opt/anaconda3/envs/det_pt2/lib/python3.10/site-packages/torch/include/THC -I/Users/user/opt/anaconda3/envs/det_pt2/include/python3.10 -c ./csrc/mmdeploy/backend_ops/torchscript/optimizer/bind.cpp -o build/temp.macosx-10.9-x86_64-cpython-310/./csrc/mmdeploy/backend_ops/torchscript/optimizer/bind.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=ts_optimizer -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from ./csrc/mmdeploy/backend_ops/torchscript/optimizer/bind.cpp:4:
      In file included from /Users/user/opt/anaconda3/envs/det_pt2/lib/python3.10/site-packages/torch/include/torch/extension.h:5:
      /Users/user/opt/anaconda3/envs/det_pt2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: C++17 or later compatible compiler is required to use PyTorch.
      #error C++17 or later compatible compiler is required to use PyTorch.
       ^
```

**Comment by ruisv** [comment]
Hi, [celpas](https://github.com/celpas).
U can change "csrc/mmdeploy/backend_ops/CMakeLists.txt" line 2, set(CMAKE_CXX_STANDARD 17).

**Comment by celpas** [comment]
I've been able to solve the issue setting the following extra compile argument inside `setup.py`:
`extra_compile_args['cxx'] = ['-std=c++17']`

A PR should be opened on this as currently MMDeploy's compatibility with PyTorch 2.1 is broke.

**Comment by RunningLeon** [comment]
hi, thanks for your feedback. Welcome PR to fix it.
