### ISSUE TITLE
[Enhancement] GridSampler ONNX GPU Support for Mask2Former

### ISSUE THREAD

**Issue by dillonalaird** [open-mmlab/mmdeploy#2535]
### Motivation

For Mask2Former model with a Swin Tiny backbone (using the MMSeg model) I'm getting about ~54ms of latency on an A5000 using TensorRT. However, when I switch to using ONNXRuntime the latency shoots up to ~645ms. Looking at the profile it's mainly due to the GridSampler operator running on the CPU. Is there any plan to support GridSampler on GPU for ONNXRuntime similar to it's GPU support in TensorRT [here](https://github.com/open-mmlab/mmdeploy/tree/main/csrc/mmdeploy/backend_ops/tensorrt/grid_sampler)?

If not, is there an example of how to add a GPU operator for ONNXRuntime in mmdeploy I can look at?

**Comment by RunningLeon** [comment]
hi, you can refer to this doc: https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#custom-operators
