### ISSUE TITLE
How TensorRT custom ops is built on Linux? A tutorial is needed

### ISSUE THREAD

**Issue by williamlzw** [open-mmlab/mmdeploy#254]
linux 如何编译trt算子?给个教程

**Comment by lvhan028** [comment]
You can refer to https://mmdeploy.readthedocs.io/en/latest/backends/tensorrt.html. 

B.T.W, we recommend using English or Chinese&English to open an issue, and your question will help more users.

**Comment by RunningLeon** [comment]
@williamlzw Hi, have you successfully built TensorRT custom ops on Linux? If so, this issue could be closed.
