### ISSUE TITLE
[Bug] delta2bbox Rewrite

### ISSUE THREAD

**Issue by ozen** [open-mmlab/mmdeploy#2544]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

#1977 appears to cause shape incompatibility during the tensor operations. If I rollback the change, the reproduction code works fine.

### Reproduction

```python
from mmdeploy.codebase.mmdet.models.task_modules.coders.delta_xywh_bbox_coder import delta2bbox
import torch

rois = torch.randint(0, 100, (100, 4))
deltas = torch.randint(0, 10, (100, 4))
delta2bbox(rois, deltas)
```

### Environment

```Shell
mmdeploy 1.3.0
torch 2.1.0
Python 3.10.10
```

### Error traceback

```Shell
File mmdeploy/codebase/mmdet/models/task_modules/coders/delta_xywh_bbox_coder.py:140, in delta2bbox(rois, deltas, means, stds, max_shape, wh_ratio_clip, clip_border, add_ctr_clamp, ctr_clamp)
    137     from mmdeploy.codebase.mmdet.deploy import clip_bboxes
    138     x1, y1, x2, y2 = clip_bboxes(x1, y1, x2, y2, max_shape)
--> 140 bboxes = torch.stack([x1, y1, x2, y2], dim=-1).view(deltas.size())
    141 return bboxes

RuntimeError: shape '[100, 4]' is invalid for input of size 800
```
```

**Comment by RunningLeon** [comment]
hi, `rois` and `deltas` should batch dim in the first dim.

**Comment by ozen** [comment]
> hi, `rois` and `deltas` should batch dim in the first dim.

Hi RunningLeon. You are right, it works fine if the tensors have 3 dims instead of 2. Closing the issue.
