### ISSUE TITLE
[Feature] About the implementation of SDK registry 

### ISSUE THREAD

**Issue by xuyufeng1995** [open-mmlab/mmdeploy#2547]
### Motivation

using get_signature_t = decltype(get_signature(basic_type<T>{}));

I did not find the specific implementation of the get_signature function.Can you tell me where it comes from?

https://github.com/open-mmlab/mmdeploy/blob/2882c64eea8640f913588f6962e66abf2e7b6c86/csrc/mmdeploy/core/registry.h#L49C32-L49C32

**Comment by irexyc** [comment]
在这里
 https://github.com/open-mmlab/mmdeploy/blob/2882c64eea8640f913588f6962e66abf2e7b6c86/csrc/mmdeploy/core/registry.h#L212-L216

**Comment by xuyufeng1995** [comment]
> 在这里
> 
> https://github.com/open-mmlab/mmdeploy/blob/2882c64eea8640f913588f6962e66abf2e7b6c86/csrc/mmdeploy/core/registry.h#L212-L216

这个应该是get_registry的函数实现吧？

**Comment by irexyc** [comment]
> 这个应该是get_registry的函数实现吧？

是的

**Comment by xuyufeng1995** [comment]
get_registry和get_signature指的是同一个函数？

**Comment by irexyc** [comment]
对，也没有地方会调用get_signature，这里只是为了声明一下，然后利用decltype获取类型。

**Comment by xuyufeng1995** [comment]
好的，thanks
