### ISSUE TITLE
[Docs] 关于pointpillar tensorrt部署问题

### ISSUE THREAD

**Issue by fpeanut** [open-mmlab/mmdeploy#2551]
### 📚 The doc issue

请问mmdeploy pointpillar tensorrt cpp的推理代码在哪里，是开放的吗

**Comment by RunningLeon** [comment]
hi, do you mean trt plugins? all are in here https://github.com/open-mmlab/mmdeploy/tree/main/csrc/mmdeploy/backend_ops/tensorrt
