### ISSUE TITLE
[Feature] Request for Adding Support for "mmdeploy:GatherTopk(-1)" Operation in ONNX Runtime

### ISSUE THREAD

**Issue by CVHub520** [open-mmlab/mmdeploy#2564]
### Motivation

Hello,

I am contacting you regarding an issue that I am experiencing while working with ONNX models on the ONNXRuntime. I encountered a problem when trying to load a model that includes the operation "mmdeploy:GatherTopk(-1)". The error message suggests that this operation is not a registered function/op.

This operation seems to be vital for my current workflow and the model operations. I kindly request the development team to consider adding support for this specific operation, "mmdeploy:GatherTopk(-1)", to the ONNXRuntime functionality in an upcoming release.

The support for this operation would significantly assist in accomplishing my project's objectives and open new dimensions for ONNX model users who might need this operation in the future.

If additional details are necessary or you need more context related to this request, please feel free to reply to this email, and I would be happy to share more.

Thank you for taking the time to review my request. I am confident that adding support for this operation will contribute substantial value to the ONNXRuntime user community.

Best Regards

CVHub

**Comment by RunningLeon** [comment]
hi, it seems you are using an onnx exported with TensorRT backend deploy config file. TRT backends has GatherTopK in https://github.com/open-mmlab/mmdeploy/blob/8b1958640408397d0cf98f202defa58878baf05b/mmdeploy/codebase/mmdet/deploy/utils.py#L205C7-L205C20.

You should rerun `tools/deploy.py` with onnx backend deploy config such as [configs/mmdet/detection/detection_onnxruntime_dynamic.py](https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmdet/detection/detection_onnxruntime_dynamic.py) to get the correct onnx file.
