### ISSUE TITLE
[Docs] PPLCV requires CUDA 11.* , can I go around that limitation and build mmdeploy with CUDA 12.* ?

### ISSUE THREAD

**Issue by mchaniotakis** [open-mmlab/mmdeploy#2583]
### 📚 The doc issue

PPLCV currently only builds with CUDA 11.* . I want to build mmdeploy to take advantage of any custom ops that might be needed and deploy on triton with either ort or trt inference backend. I am using a dockerfile to build a container starting from a triton image. Would it be possible to go around this limitation PPLCV somehow?

**Comment by irexyc** [comment]
pplcv seems doesn't support cuda12 for now, but this issue indicates that you can comment Texture related code to compile it.

However If you just need the custom ops in mmdeploy, you don't have to build mmdeploy all. You can just build the custom ops. 
https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/linux-x86_64.md#build-model-converter
