### ISSUE TITLE
[Feature] Support PyTorch 2.0 for Jetson (with solution)

### ISSUE THREAD

**Issue by yinfan98** [open-mmlab/mmdeploy#2586]
### Motivation

The Jetson didn't support some higher version of PyTorch.
In https://github.com/open-mmlab/mmdeploy/blob/main/docs/en/01-how-to-build/jetsons.md
it tells that error: cannot import name 'ProcessGroup' from 'torch.distributed' &&
cannot import name 'ReduceOp' from 'torch.distributed
And I found that PyTorch has support ProcessGroup method for Jetpack5.1 PyTorch2.0.0 and still not support ReduceOp.

### Related resources

So I have some idea for this problem, cauz Jetson didn't support torch.distribute. I make a jetson_patch.py
- jetson_patch.py
```python
import torch.distributed
if !torch.distributeds_available():
    torch.distributed.ReduceOp = lambda: None
```
And if we need to use deploy.py or other python file, just import this file and can avoid torch.distributed.
I have already tested this method on Jetson AGX Orin.

### Additional context

1.I really know for solving this problem, my method is not particularly elegant... But it works well!
2.There may still be some other versions of PyTorch's distributed methods that are not supported, but I think emulating my approach could also solve the problem.

**Comment by RunningLeon** [comment]
hi, good idea. Maybe we can rewrite some dist related modules from pytorch for jetson like devices in here:
https://github.com/open-mmlab/mmdeploy/tree/main/mmdeploy/pytorch
