### ISSUE TITLE
[Feature] mmdeploy Pointpillar后处理 

### ISSUE THREAD

**Issue by fpeanut** [open-mmlab/mmdeploy#2598]
### Motivation

请问关于pointpillar推理模型的后处理是什么样子的，mmdeploy代码封装了，我看不到源码。

**Comment by RunningLeon** [comment]
hi, mmdeploy sdk has not implemented postprocessing of pointpillars. It calls from mmdet3d in python inference.
https://github.com/open-mmlab/mmdeploy/blob/660af62b945342276a6c813250a6fa4fcf5ff330/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py#L204

**Comment by fpeanut** [comment]
好的谢谢

**Comment by fpeanut** [comment]
> 您好，mmdeploy sdk 尚未实现 pointpillars 的后处理。它在 python 推理中从 mmdet3d 调用。
> 
> https://github.com/open-mmlab/mmdeploy/blob/660af62b945342276a6c813250a6fa4fcf5ff330/mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py#L204

还有个问题，就是pointpillar模型的kitti后处理和waymo的后处理是一样的吗

**Comment by fpeanut** [comment]
还有两者的前处理一样吗
