### ISSUE TITLE
Regarding supported version of spdlog

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#260]
Hello, 

I've had some issues building and running MMDeploy with older versions of spdlog (`libspdlog-dev/bionic 1:0.16.3-1 arm64
`, as installed by apt-get on Jetson). I had to update to the latest version on spdlog from git to solve the issue. It appears that MMDEPLOY_INFO, _ERROR messages result in a crash/segfault whenever I build with the old spdlog.

Are there any known compatibility issues with older versions of spdlog? I do not recall having this issue before upgrading to MMdeploy 0.3.0. 

Thanks!

**Comment by lzhangzz** [comment]
Hi,  

Sorry for the late reply. 

There is some adjustments on the project structure in v0.3.0, which may introduce some side-effects on linkage of some components.

Can provide more info about your settings and the excat cmake command used to configure the project so we can reproduce the problem?

**Comment by tehkillerbee** [comment]
Sure!

I previously installed libspdlog-dev using the package manager, as instructed in the user guide. On latest Ubuntu 20.04, this installs 1:1.5.0-1 while on 18.04 (eg. Jetson), this installs 1:0.16.3-1.

I then built ppl.cv and MMDeploy as usual

```bash
SPDLOG_DIR=${WORKING_DIR}/spdlog
PPLCV_DIR=${WORKING_DIR}/ppl.cv
MMDEPLOY_DIR=${WORKING_DIR}/MMDeploy

## install from package manager
sudo apt-get install libspdlog-dev

## pplcv
cd ${WORKING_DIR}
git clone https://github.com/openppl-public/ppl.cv.git ${PPLCV_DIR}
cd ${PPLCV_DIR}
git checkout tags/v0.6.2
./build.sh cuda

## mmdeploy SDK
cd ${WORKING_DIR}
git clone https://github.com/open-mmlab/mmdeploy.git ${MMDEPLOY_DIR}
cd ${MMDEPLOY_DIR}
git checkout tags/v0.3.0
git submodule update --init --recursive
pip install -e .

mkdir build -p && cd build
cmake .. \
  -DMMDEPLOY_BUILD_SDK=ON \
  -DCMAKE_CXX_COMPILER=g++ \
  -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl \
  -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
  -DMMDEPLOY_TARGET_BACKENDS=trt \
  -DMMDEPLOY_CODEBASES=all
cmake --build . -- -j$(nproc) && cmake --install .
```

After doing so, I could not run any examples and/or my own inference tools. It appeared that the applications crashed whenever a log message was called.

I then tried building and installing spdlog from source and then rebuilding MMDeploy. Then the issue disappeared.
```bash
## build & install spdlog from source
sudo apt-get remove libspdlog-dev -y

cd ${WORKING_DIR}
git clone https://github.com/gabime/spdlog.git ${SPDLOG_DIR}
cd ${SPDLOG_DIR}
git checkout tags/v1.8.1
mkdir build && cd build
# we must build spdlog with -fPIC enabled
cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON && make -j
sudo make install
sudo ldconfig
```

**Comment by lzhangzz** [comment]
@tehkillerbee I'm using a Jetson AGX Xavier on Ubuntu 18.04 with spdlog 1:0.16.3-1 installed via `apt`. However I can't reproduce the problem. Is there anything special about your environment?

**Comment by tehkillerbee** [comment]
@lzhangzz I think it might be because of the way I use mmdeploy logging in my own program. I still get the issue on a freshly installed Jetson AGX Xavier, where I use spdlog from apt

```cpp
...
auto mmdepLogger = mmdeploy::GetLogger();
//mmdepLogger->set_level(spdlog::level::off);
...
// Set config path - use default path if not set
fs::path configPath = fs::current_path().append("config.toml");
if (!fs::exists(configPath)) {
    fprintf(stderr, "config.toml does not exist in the expected directory!\n");
	mmdepLogger->error("config '{}' does not exist. Cannot continue!", configPath.string());
    exit(1);
}
...
```

My program crashes when I call mmdepLogger->error("..")

**Comment by lzhangzz** [comment]
@tehkillerbee 

I need more information on how you link mmdeploy in your own program. I just tried to use `MMDEPLOY_ERROR` in one of the examples and it worked.

Or perhaps you can try to reproduce it by modifying the examples?

**Comment by tehkillerbee** [comment]
@lzhangzz Thanks for your suggestion. I first made sure to downgrade to the "old" spdlog version.  I tried building one of the application tools and added the following to the main

```cpp
auto mmdepLogger = mmdeploy::GetLogger();
fprintf(stderr, "config.toml does not exist in the expected directory!\n");
mmdepLogger->error("config '{}' does not exist. Cannot continue!", "teststring");
```

I then tried building. This time I get an error I have not seen before (this error never occurred when building my own tool):
```
In file included from /home/nvidia/git/sscale_deployment/logends/MMDeploy/build/example/object_detection.cpp:7:0:
/usr/local/include/cpp/core/utils/formatter.h:39:45: error: ‘is_enum_v’ is not a member of ‘std’
 template <typename T, std::enable_if_t<std::is_enum_v<std::decay_t<T> >, bool> = true>
                                             ^~~~~~~~~
/usr/local/include/cpp/core/utils/formatter.h:39:45: note: suggested alternative: ‘is_enum’
 template <typename T, std::enable_if_t<std::is_enum_v<std::decay_t<T> >, bool> = true>
                                             ^~~~~~~~~
                                             is_enum
/usr/local/include/cpp/core/utils/formatter.h:39:45: error: ‘is_enum_v’ is not a member of ‘std’
/usr/local/include/cpp/core/utils/formatter.h:39:45: note: suggested alternative: ‘is_enum’
 template <typename T, std::enable_if_t<std::is_enum_v<std::decay_t<T> >, bool> = true>
                                             ^~~~~~~~~
                                             is_enum
/usr/local/include/cpp/core/utils/formatter.h:39:71: error: template argument 1 is invalid
 template <typename T, std::enable_if_t<std::is_enum_v<std::decay_t<T> >, bool> = true>
                                                                       ^
/usr/local/include/cpp/core/utils/formatter.h:39:80: error: expected unqualified-id before ‘=’ token
 template <typename T, std::enable_if_t<std::is_enum_v<std::decay_t<T> >, bool> = true>
```

**Comment by lzhangzz** [comment]
@tehkillerbee 

> error: ‘is_enum_v’ is not a member of ‘std’

Well this should be considered as a bug caused by missing `#include <type_traits>` in `formatter.h`. will fix it later.

> I have both spdlog and fmt available as submodules

This may be the root cause of the segfault. Usually fmt is bundled in spdlog, when you have them both available as submodules, the fmt inside spdlog and the other fmt as submodule may not be of the same version, resulting ODR violation (same symbols with different implementations in the binary) and undefined behavior.

**Comment by tehkillerbee** [comment]
@lzhangzz Thanks for your explanation, that makes sense. I think I will move away from using spdlog (and possibly fmt) as a submodule and just install libspdlog-dev on our machines - similar to how it is done with MMDeploy logger wrapper. Then there should be no interfering versions installed.

**Comment by lvhan028** [comment]
@tehkillerbee would you like to be one of our reviewers?

**Comment by tehkillerbee** [comment]
@lvhan028 Sure, that would be nice if I can contribute back to MMDeploy
