### ISSUE TITLE
Can't workout the divisability requirement 

### ISSUE THREAD

**Issue by GeorgePearse** [open-mmlab/mmdeploy#2611]
### 📚 The doc issue

ONNX model exports often get rounded up slightly in terms of the requested image dimensions vs. what gets exported. 

I'm not sure what the required divisor is, e.g. 8? 16? 32? 

So far I've just been using trial and error. 

Does it vary from model to model?

**Comment by GeorgePearse** [comment]
Is it based on the 32 here? 
![image](https://github.com/open-mmlab/mmdeploy/assets/47161914/a0afb7e7-227f-4219-bd96-f504fc4fdefc)

**Comment by RunningLeon** [comment]
> Is it based on the 32 here? ![image](https://private-user-images.githubusercontent.com/47161914/292212187-a0afb7e7-227f-4219-bd96-f504fc4fdefc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0ODQyNTEsIm5iZiI6MTcwMzQ4Mzk1MSwicGF0aCI6Ii80NzE2MTkxNC8yOTIyMTIxODctYTBhZmI3ZTctMjI3Zi00MjE5LWJkOTYtZjUwNGZjNGZkZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA1NTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxM2ZmYjU4YTRmNjBlZGE5OWRhNGIxNGM4MjNmYzc5N2NkZDExOGJmMGZhY2Y1ODUwZWY3MzNhMmQ2ZDBjZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.08eYw7cmP9pmDMg3wpfhy02RcPeGEzVVPvvNuU1234U)

hi, the padding part is in pre-processing and most of the time, mmdeploy will skip pre-processing while exporting to onnx. You have to take care of it outside before feeding an input to the exported model.
