### ISSUE TITLE
为什么同一张卡，在ubuntu上转出来的TRT模型，在windows上用不了呢 

### ISSUE THREAD

**Issue by kitterive** [open-mmlab/mmdeploy#2698]
### Motivation

同一张卡，在ubuntu上转出来的TRT模型，在windows上用不了呢 ？

**Comment by QzYER** [comment]
> ### Motivation
> 同一张卡，在ubuntu上转出来的TRT模型，在windows上用不了呢 ？
> 
> ### Related resources
> _No response_
> 
> ### Additional context
> _No response_

编译方式不一样。跨平台了。

**Comment by kitterive** [comment]
但 TensorRT在不同平台上转出来的模型是通用的，为啥这里就不行了呢，是因为前后处理的问题吗？

**Comment by QzYER** [comment]
不同平台、不同显卡、都要重新降torch2trt最好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月12日(星期二) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdeploy] 为什么同一张卡，在ubuntu上转出来的TRT模型，在windows上用不了呢  (Issue #2698)





 
但 TensorRT在不同平台上转出来的模型是通用的，为啥这里就不行了呢，是因为前后处理的问题吗？

**Comment by kitterive** [comment]
好的，谢谢
