### ISSUE TITLE
[Bug] Error exporting RTMO to ONNX and TensorRT

### ISSUE THREAD

**Issue by Daanfb** [open-mmlab/mmdeploy#2718]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [X] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [X] 3. The bug has not been fixed in the latest version.

### Describe the bug

I'm trying to export RTMO-S model to ONNX and TensorRT and i get an error for both cases.

### Reproduction

ONNX:
`python tools/deploy.py configs/mmpose/pose-detection_rtmo_onnxruntime_dynamic.py ../mmpose/configs/body_2d_keypoint/rtmo/body7/rtmo-s_8xb32-600e_body7-640x640.py https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-s_8xb32-600e_body7-640x640-dac2bf74_20231211.pth ../image.jpg --work-dir rtmo/rtmo-s --device cpu --show --dump-info  
`

`03/26 12:19:26 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
03/26 12:19:26 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
03/26 12:19:31 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
03/26 12:19:33 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
03/26 12:19:33 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
c:\users\jordi\desktop\daniel\mmpose\mmpose\mmpose\datasets\datasets\utils.py:102: UserWarning: The metainfo config file "configs/_base_/datasets/coco.py" does not exist. A matched config file "c:\users\jordi\desktop\daniel\mmpose\mmpose\mmpose\.mim\configs\_base_\datasets\coco.py" will be used instead.
  warnings.warn(
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-s_8xb32-600e_body7-640x640-dac2bf74_20231211.pth
03/26 12:19:34 - mmengine - INFO - module neck has been switched to deploy mode
C:\Users\Jordi\anaconda3\envs\mmpose\lib\site-packages\torch\functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3550.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
03/26 12:19:34 - mmengine - INFO - module neck.fpn_blocks.0.bottlenecks.0 has been switched to deploy mode
03/26 12:19:34 - mmengine - INFO - module neck.fpn_blocks.1.bottlenecks.0 has been switched to deploy mode
03/26 12:19:34 - mmengine - INFO - module neck.pan_blocks.0.bottlenecks.0 has been switched to deploy mode
03/26 12:19:34 - mmengine - INFO - module neck.pan_blocks.1.bottlenecks.0 has been switched to deploy mode
03/26 12:19:34 - mmengine - INFO - module head has been switched to deploy mode
03/26 12:19:34 - mmengine - INFO - module head.dcc has been switched to deploy mode
03/26 12:19:34 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
03/26 12:19:34 - mmengine - INFO - Export PyTorch model to ONNX: rtmo/rtmo-s\end2end.onnx.
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\core\optimizers\function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\mmcv\ops\nms.py:285: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\mmcv\ops\nms.py:286: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\pytorch\functions\topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\mmcv\ops\nms.py:45: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\mmcv\ops\nms.py:46: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
C:\Users\Jordi\anaconda3\envs\mmpose\lib\site-packages\mmcv\ops\nms.py:123: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
C:\Users\Jordi\anaconda3\envs\mmpose\lib\site-packages\mmcv\ops\nms.py:124: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)`

TensorRT:
`python tools/deploy.py configs/mmpose/pose-detection_rtmo_tensorrt-fp16_dynamic-640x640.py ../mmpose/configs/body_2d_keypoint/rtmo/body7/rtmo-s_8xb32-600e_body7-640x640.py https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-s_8xb32-600e_body7-640x640-dac2bf74_20231211.pth ../image.jpg --work-dir rtmo/rtmo-s-trt --device cuda:0 --show --dump-info  
`

`03/26 12:31:29 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
03/26 12:31:29 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
03/26 12:31:33 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
03/26 12:31:36 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
03/26 12:31:36 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "mmpose_tasks" registry tree. As a workaround, the current "mmpose_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
c:\users\jordi\desktop\daniel\mmpose\mmpose\mmpose\datasets\datasets\utils.py:102: UserWarning: The metainfo config file "configs/_base_/datasets/coco.py" does not exist. A matched config file "c:\users\jordi\desktop\daniel\mmpose\mmpose\mmpose\.mim\configs\_base_\datasets\coco.py" will be used instead.
  warnings.warn(
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmpose/v1/projects/rtmo/rtmo-s_8xb32-600e_body7-640x640-dac2bf74_20231211.pth
03/26 12:31:37 - mmengine - INFO - module neck has been switched to deploy mode
C:\Users\Jordi\anaconda3\envs\mmpose\lib\site-packages\torch\functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3550.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
03/26 12:31:37 - mmengine - INFO - module neck.fpn_blocks.0.bottlenecks.0 has been switched to deploy mode
03/26 12:31:37 - mmengine - INFO - module neck.fpn_blocks.1.bottlenecks.0 has been switched to deploy mode
03/26 12:31:37 - mmengine - INFO - module neck.pan_blocks.0.bottlenecks.0 has been switched to deploy mode
03/26 12:31:37 - mmengine - INFO - module neck.pan_blocks.1.bottlenecks.0 has been switched to deploy mode
03/26 12:31:37 - mmengine - INFO - module head has been switched to deploy mode
03/26 12:31:37 - mmengine - INFO - module head.dcc has been switched to deploy mode
03/26 12:31:37 - mmengine - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
03/26 12:31:37 - mmengine - INFO - Export PyTorch model to ONNX: rtmo/rtmo-s-trt\end2end.onnx.
03/26 12:31:37 - mmengine - WARNING - Can not find torch.nn.functional._scaled_dot_product_attention, function rewrite will not be applied
03/26 12:31:37 - mmengine - WARNING - Can not find mmdet.models.utils.transformer.PatchMerging.forward, function rewrite will not be applied
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\core\optimizers\function_marker.py:160: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\mmcv\ops\nms.py:477: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(scores.shape[-1]),
c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\mmcv\ops\nms.py:149: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
03/26 12:31:41 - mmengine - ERROR - c:\users\jordi\desktop\daniel\mmpose\mmdeploy\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.`

### Environment

```Shell
03/26 12:38:09 - mmengine - INFO - **********Environmental information**********
03/26 12:38:14 - mmengine - INFO - sys.platform: win32
03/26 12:38:14 - mmengine - INFO - Python: 3.8.19 (default, Mar 20 2024, 19:55:45) [MSC v.1916 64 bit (AMD64)]
03/26 12:38:14 - mmengine - INFO - CUDA available: True
03/26 12:38:14 - mmengine - INFO - MUSA available: False
03/26 12:38:14 - mmengine - INFO - numpy_random_seed: 2147483648
03/26 12:38:14 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 2060
03/26 12:38:14 - mmengine - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
03/26 12:38:14 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.6, V11.6.55
03/26 12:38:14 - mmengine - INFO - MSVC: Compilador de optimización de C/C++ de Microsoft (R) versión 19.39.33523 para x64
03/26 12:38:14 - mmengine - INFO - GCC: n/a
03/26 12:38:14 - mmengine - INFO - PyTorch: 2.2.1+cu118
03/26 12:38:14 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 201703
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

03/26 12:38:14 - mmengine - INFO - TorchVision: 0.17.1+cu118
03/26 12:38:14 - mmengine - INFO - OpenCV: 4.8.0
03/26 12:38:14 - mmengine - INFO - MMEngine: 0.10.3
03/26 12:38:14 - mmengine - INFO - MMCV: 2.1.0
03/26 12:38:14 - mmengine - INFO - MMCV Compiler: MSVC 193933523
03/26 12:38:14 - mmengine - INFO - MMCV CUDA Compiler: 11.6
03/26 12:38:14 - mmengine - INFO - MMDeploy: 1.3.1+bc75c9d
03/26 12:38:14 - mmengine - INFO -

03/26 12:38:14 - mmengine - INFO - **********Backend information**********
03/26 12:38:14 - mmengine - INFO - tensorrt:    8.6.1
03/26 12:38:14 - mmengine - INFO - tensorrt custom ops: NotAvailable
03/26 12:38:14 - mmengine - INFO - ONNXRuntime: None
03/26 12:38:14 - mmengine - INFO - ONNXRuntime-gpu:     1.16.0
03/26 12:38:14 - mmengine - INFO - ONNXRuntime custom ops:      NotAvailable
03/26 12:38:14 - mmengine - INFO - pplnn:       None
03/26 12:38:14 - mmengine - INFO - ncnn:        None
03/26 12:38:14 - mmengine - INFO - snpe:        None
03/26 12:38:14 - mmengine - INFO - openvino:    None
03/26 12:38:14 - mmengine - INFO - torchscript: 2.2.1+cu118
03/26 12:38:14 - mmengine - INFO - torchscript custom ops:      NotAvailable
03/26 12:38:15 - mmengine - INFO - rknn-toolkit:        None
03/26 12:38:15 - mmengine - INFO - rknn-toolkit2:       None
03/26 12:38:15 - mmengine - INFO - ascend:      None
03/26 12:38:15 - mmengine - INFO - coreml:      None
03/26 12:38:15 - mmengine - INFO - tvm: None
03/26 12:38:15 - mmengine - INFO - vacc:        None
03/26 12:38:15 - mmengine - INFO -

03/26 12:38:15 - mmengine - INFO - **********Codebase information**********
03/26 12:38:15 - mmengine - INFO - mmdet:       3.2.0
03/26 12:38:15 - mmengine - INFO - mmseg:       None
03/26 12:38:15 - mmengine - INFO - mmpretrain:  1.2.0
03/26 12:38:15 - mmengine - INFO - mmocr:       None
03/26 12:38:15 - mmengine - INFO - mmagic:      None
03/26 12:38:15 - mmengine - INFO - mmdet3d:     None
03/26 12:38:15 - mmengine - INFO - mmpose:      1.3.1
03/26 12:38:15 - mmengine - INFO - mmrotate:    None
03/26 12:38:15 - mmengine - INFO - mmaction:    None
03/26 12:38:15 - mmengine - INFO - mmrazor:     None
03/26 12:38:15 - mmengine - INFO - mmyolo:      None
```

**Comment by Daanfb** [comment]
I have been able to export on Ubuntu

**Comment by yeongjoon** [comment]
> I have been able to export on Ubuntu

Can you tell me your ubuntu environment for the tensorRT(ex) CUDA version, pytorch version, nvcc version, ...)

**Comment by Daanfb** [comment]
> > I have been able to export on Ubuntu
> 
> Can you tell me your ubuntu environment for the tensorRT(ex) CUDA version, pytorch version, nvcc version, ...)

04/29 11:23:29 - mmengine - INFO - 

04/29 11:23:29 - mmengine - INFO - **********Environmental information**********
04/29 11:23:31 - mmengine - INFO - sys.platform: linux
04/29 11:23:31 - mmengine - INFO - Python: 3.8.19 (default, Mar 20 2024, 19:58:24) [GCC 11.2.0]
04/29 11:23:31 - mmengine - INFO - CUDA available: True
04/29 11:23:31 - mmengine - INFO - MUSA available: False
04/29 11:23:31 - mmengine - INFO - numpy_random_seed: 2147483648
04/29 11:23:31 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 2060
04/29 11:23:31 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.8
04/29 11:23:31 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.8, V11.8.89
04/29 11:23:31 - mmengine - INFO - GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
04/29 11:23:31 - mmengine - INFO - PyTorch: 2.2.2
04/29 11:23:31 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

04/29 11:23:31 - mmengine - INFO - TorchVision: 0.17.2
04/29 11:23:31 - mmengine - INFO - OpenCV: 4.9.0
04/29 11:23:31 - mmengine - INFO - MMEngine: 0.10.3
04/29 11:23:31 - mmengine - INFO - MMCV: 2.1.0
04/29 11:23:31 - mmengine - INFO - MMCV Compiler: GCC 11.4
04/29 11:23:31 - mmengine - INFO - MMCV CUDA Compiler: not available
04/29 11:23:31 - mmengine - INFO - MMDeploy: 1.3.1+bc75c9d
04/29 11:23:31 - mmengine - INFO - 

04/29 11:23:31 - mmengine - INFO - **********Backend information**********
04/29 11:23:31 - mmengine - INFO - tensorrt:	8.6.1
04/29 11:23:31 - mmengine - INFO - tensorrt custom ops:	Available
04/29 11:23:31 - mmengine - INFO - ONNXRuntime:	None
04/29 11:23:31 - mmengine - INFO - ONNXRuntime-gpu:	1.8.1
04/29 11:23:31 - mmengine - INFO - ONNXRuntime custom ops:	Available
04/29 11:23:31 - mmengine - INFO - pplnn:	None
04/29 11:23:31 - mmengine - INFO - ncnn:	None
04/29 11:23:31 - mmengine - INFO - snpe:	None
04/29 11:23:31 - mmengine - INFO - openvino:	None
04/29 11:23:31 - mmengine - INFO - torchscript:	2.2.2
04/29 11:23:31 - mmengine - INFO - torchscript custom ops:	NotAvailable
04/29 11:23:31 - mmengine - INFO - rknn-toolkit:	None
04/29 11:23:31 - mmengine - INFO - rknn-toolkit2:	None
04/29 11:23:31 - mmengine - INFO - ascend:	None
04/29 11:23:31 - mmengine - INFO - coreml:	None
04/29 11:23:31 - mmengine - INFO - tvm:	None
04/29 11:23:31 - mmengine - INFO - vacc:	None
04/29 11:23:31 - mmengine - INFO - 

04/29 11:23:31 - mmengine - INFO - **********Codebase information**********
04/29 11:23:31 - mmengine - INFO - mmdet:	3.3.0
04/29 11:23:31 - mmengine - INFO - mmseg:	None
04/29 11:23:31 - mmengine - INFO - mmpretrain:	None
04/29 11:23:31 - mmengine - INFO - mmocr:	None
04/29 11:23:31 - mmengine - INFO - mmagic:	None
04/29 11:23:31 - mmengine - INFO - mmdet3d:	None
04/29 11:23:31 - mmengine - INFO - mmpose:	1.3.1
04/29 11:23:31 - mmengine - INFO - mmrotate:	None
04/29 11:23:31 - mmengine - INFO - mmaction:	None
04/29 11:23:31 - mmengine - INFO - mmrazor:	None
04/29 11:23:31 - mmengine - INFO - mmyolo:	None

**Comment by yeongjoon** [comment]
> > > I have been able to export on Ubuntu
> > 
> > 
> > Can you tell me your ubuntu environment for the tensorRT(ex) CUDA version, pytorch version, nvcc version, ...)
> 
> 04/29 11:23:29 - mmengine - INFO -
> 
> 04/29 11:23:29 - mmengine - INFO - **Environmental information** 04/29 11:23:31 - mmengine - INFO - sys.platform: linux 04/29 11:23:31 - mmengine - INFO - Python: 3.8.19 (default, Mar 20 2024, 19:58:24) [GCC 11.2.0] 04/29 11:23:31 - mmengine - INFO - CUDA available: True 04/29 11:23:31 - mmengine - INFO - MUSA available: False 04/29 11:23:31 - mmengine - INFO - numpy_random_seed: 2147483648 04/29 11:23:31 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 2060 04/29 11:23:31 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.8 04/29 11:23:31 - mmengine - INFO - NVCC: Cuda compilation tools, release 11.8, V11.8.89 04/29 11:23:31 - mmengine - INFO - GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 04/29 11:23:31 - mmengine - INFO - PyTorch: 2.2.2 04/29 11:23:31 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
> 
> * GCC 9.3
> * C++ Version: 201703
> * Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * LAPACK is enabled (usually provided by MKL)
> * NNPACK is enabled
> * CPU capability usage: AVX2
> * CUDA Runtime 11.8
> * NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
> * CuDNN 8.7
> * Magma 2.6.1
> * Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,
> 
> 04/29 11:23:31 - mmengine - INFO - TorchVision: 0.17.2 04/29 11:23:31 - mmengine - INFO - OpenCV: 4.9.0 04/29 11:23:31 - mmengine - INFO - MMEngine: 0.10.3 04/29 11:23:31 - mmengine - INFO - MMCV: 2.1.0 04/29 11:23:31 - mmengine - INFO - MMCV Compiler: GCC 11.4 04/29 11:23:31 - mmengine - INFO - MMCV CUDA Compiler: not available 04/29 11:23:31 - mmengine - INFO - MMDeploy: 1.3.1+bc75c9d 04/29 11:23:31 - mmengine - INFO -
> 
> 04/29 11:23:31 - mmengine - INFO - **Backend information** 04/29 11:23:31 - mmengine - INFO - tensorrt: 8.6.1 04/29 11:23:31 - mmengine - INFO - tensorrt custom ops: Available 04/29 11:23:31 - mmengine - INFO - ONNXRuntime: None 04/29 11:23:31 - mmengine - INFO - ONNXRuntime-gpu: 1.8.1 04/29 11:23:31 - mmengine - INFO - ONNXRuntime custom ops: Available 04/29 11:23:31 - mmengine - INFO - pplnn: None 04/29 11:23:31 - mmengine - INFO - ncnn: None 04/29 11:23:31 - mmengine - INFO - snpe: None 04/29 11:23:31 - mmengine - INFO - openvino: None 04/29 11:23:31 - mmengine - INFO - torchscript: 2.2.2 04/29 11:23:31 - mmengine - INFO - torchscript custom ops: NotAvailable 04/29 11:23:31 - mmengine - INFO - rknn-toolkit: None 04/29 11:23:31 - mmengine - INFO - rknn-toolkit2: None 04/29 11:23:31 - mmengine - INFO - ascend: None 04/29 11:23:31 - mmengine - INFO - coreml: None 04/29 11:23:31 - mmengine - INFO - tvm: None 04/29 11:23:31 - mmengine - INFO - vacc: None 04/29 11:23:31 - mmengine - INFO -
> 
> 04/29 11:23:31 - mmengine - INFO - **Codebase information** 04/29 11:23:31 - mmengine - INFO - mmdet: 3.3.0 04/29 11:23:31 - mmengine - INFO - mmseg: None 04/29 11:23:31 - mmengine - INFO - mmpretrain: None 04/29 11:23:31 - mmengine - INFO - mmocr: None 04/29 11:23:31 - mmengine - INFO - mmagic: None 04/29 11:23:31 - mmengine - INFO - mmdet3d: None 04/29 11:23:31 - mmengine - INFO - mmpose: 1.3.1 04/29 11:23:31 - mmengine - INFO - mmrotate: None 04/29 11:23:31 - mmengine - INFO - mmaction: None 04/29 11:23:31 - mmengine - INFO - mmrazor: None 04/29 11:23:31 - mmengine - INFO - mmyolo: None

Thanks!
