### ISSUE TITLE
yolact export error

### ISSUE THREAD

**Issue by NagatoYuki0943** [open-mmlab/mmdeploy#274]
When I exported yolact, I encountered an error.

Script:
python tools/deploy.py \
    configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    ../mmdetection/configs/yolact/yolact_r50_8x8_coco.py \
    ../mmdetection/checkpoints/yolact/yolact_r50_8x8_coco_20200908-ca34f5db.pth \
    ../mmdetection/demo/demo.jpg \
    --test-img ../mmdetection/demo/demo.jpg \
    --work-dir work_dir \
    --device cuda:0 \
    --log-level INFO \
    --show \
    --dump-info

Error：
  File "/home/ubuntu/.conda/envs/mm/lib/python3.8/site-packages/mmdet/models/dense_heads/yolact_head.py", line 349, in get_bboxes
    scale_factor = img_metas[img_id]['scale_factor']
KeyError: 'scale_factor'
2022-03-25 15:27:56,582 - mmdeploy - ERROR - torch2onnx failed.

It shows that img_metas[img_id] has no scale_ factor,then I print it and it really doesn't have scale_factor.
    print(img_metas[img_id])
    {'img_shape': tensor([550, 550])}

**Comment by VVsssssk** [comment]
Hi, we do not support the `yolact` model now. And this error is because we don't input original img_metas. We will modify it after.

**Comment by zhangzscn** [comment]
any update?
