### ISSUE TITLE
Error happened during custom ops build // Build custom ops 报告错误

### ISSUE THREAD

**Issue by xuhui1994** [open-mmlab/mmdeploy#279]
当自定义算子的时候最后一步报告错误

cd ${MMDEPLOY_DIR} # To MMDeploy root directory
mkdir -p build && cd build
cmake -DMMDEPLOY_TARGET_BACKENDS=trt ..
make -j$(nproc)

最后一步报告错误

(open-mmlab) [root@localhost build]# make -j$(nproc)
[  4%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/allClassNMS.cu.o
[ 21%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/permuteData.cu.o       
[ 21%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/kernel.cu.o
[ 21%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/sortScoresPerClass.cu.o
[ 21%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/gatherNMSOutputs.cu.o
[ 26%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/sortScoresPerImage.cu.o        
[ 30%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/trt_cuda_helper.cu.o
[ 34%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_sampler/trt_grid_sampler_kernel.cu.o  
[ 39%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/modulated_deform_conv/trt_modulated_deform_conv_kernel.cu.o
[ 47%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/scatternd/trt_scatternd_kernel.cu.o        
[ 47%] Building CUDA object csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/multi_level_roi_align/trt_multi_level_roi_align_kernel.cu.o
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/kernel.h:13,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/gatherNMSOutputs.cu:6:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/kernel.h:13,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/permuteData.cu:6:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/kernel.h:13,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/allClassNMS.cu:6:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align_kernel.cu:10:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/grid_sampler/trt_grid_sampler_kernel.cu:16:    
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/modulated_deform_conv/trt_modulated_deform_conv_kernel.cu:7:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/scatternd/trt_scatternd_kernel.cu:7:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/gatherNMSOutputs.cu.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/permuteData.cu.o] 错误 1
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/allClassNMS.cu.o] 错误 1
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common_impl/trt_cuda_helper.cu:3:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/multi_level_roi_align/trt_multi_level_roi_align_kernel.cu.o] 错误 1
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/modulated_deform_conv/trt_modulated_deform_conv_kernel.cu.o] 错误 1
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_sampler/trt_grid_sampler_kernel.cu.o] 错误 1        
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/scatternd/trt_scatternd_kernel.cu.o] 错误 1
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/trt_cuda_helper.cu.o] 错误 1
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/kernel.h:13,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/cub_helper.h:4,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/sortScoresPerImage.cu:7:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/kernel.h:13,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/kernel.cu:9:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/sortScoresPerImage.cu.o] 错误 1
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/kernel.cu.o] 错误 1
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntimeCommon.h:54,
                 from /mnt/data/local-disk2/IVPC/xh1994/TensorRT-7.2.3.4/include/NvInferRuntime.h:59,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/common/trt_plugin_helper.hpp:9,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/kernel.h:13,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/cub_helper.h:4,
                 from /mnt/data/local-disk2/IVPC/xh1994/MMDeploy/csrc/backend_ops/tensorrt/batched_nms/sortScoresPerClass.cu:7:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: 错误：#error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make[2]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/batched_nms/sortScoresPerClass.cu.o] 错误 1
make[1]: *** [csrc/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/all] 错误 2
make: *** [all] 错误 2

请问如何解决？期待回复

**Comment by lzhangzz** [comment]
compiling mmdeploy_tensorrt_ops requires at least gcc-5
