### ISSUE TITLE
[Feature] support python 3.9+

### ISSUE THREAD

**Issue by davidpagnon** [open-mmlab/mmdeploy#2830]
### Motivation

I would like to be able to run MMdeploy in the same environment as some libraries that do not support python < 3.9.
Is there any plan to support newer versions of Python in the near future?

**Comment by Kaeseknacker** [comment]
Did you try it with python 3.9?
I installed today a mmdeploy environment with python 3.9 and it works.

**Comment by davidpagnon** [comment]
Sorry, you are right, I also made it work!
It stalled for hours at 76%, but I just had to wait :)
