### ISSUE TITLE
How to deploy PSENet for text detection? // 文本检测网络psenet网络如何部署？

### ISSUE THREAD

**Issue by xuhui1994** [open-mmlab/mmdeploy#285]
目前只看到下图三个可以部署，那psenet有部署解决方案吗？期待回复
![image](https://user-images.githubusercontent.com/35833743/160554279-12bd6718-9853-415f-b690-649cb66e6258.png)

**Comment by lvhan028** [comment]
We recommend users to use English or English & Chinese for issue discussion so that people overseas can get what it is about. Would you please change the title?

**Comment by AllentDan** [comment]
We are gonna support the PSENet in MMDeploy soon. And we will inform you once it is done.
