### ISSUE TITLE
Which solution should I choose?

### ISSUE THREAD

**Issue by TTgogogo** [open-mmlab/mmdeploy#288]
I want to deploy mmdetection by mmdeploy, which solution should I choose? TensorRT , onnxruntime or OpenVino?

**Comment by lvhan028** [comment]
That depends on your target device. If it is NVIDIA GPU, TensorRT is recommended. If it is x86 CPU or Intel GPU, you can use OpenVINO. Otherwise, ONNXRuntime can be adopted.

**Comment by TTgogogo** [comment]
@lvhan028 does MMdeploy have detailed examples of deploying models in openvino or TensorRT?

**Comment by RunningLeon** [comment]
@TTgogogo Hi, please refer to our docs https://mmdeploy.readthedocs.io/en/latest/get_started.html
