### ISSUE TITLE
mmrotate support in mmdeploy

### ISSUE THREAD

**Issue by hust-lidelong** [open-mmlab/mmdeploy#289]
Could you support mmrotate in mmdeploy? For example, [Oriented R-CNN](https://github.com/open-mmlab/mmrotate/blob/main/configs/oriented_rcnn/README.md) or [S2A-Net](https://github.com/open-mmlab/mmrotate/blob/main/configs/s2anet/README.md). Thanks very much.

**Comment by lvhan028** [comment]
#349 is dealing with it.

**Comment by hust-lidelong** [comment]
> #349 is dealing with it.

When to support a two-stage rotated detector in MMRotate? Thanks

**Comment by zytx121** [comment]
We will support two-stage rotated detector  ASAP.

**Comment by BUAA-Worromot** [comment]
Are [Rotated RetinaNet, Rotated FasterRCNN, Oriented R-CNN, Gliding Vertex, RTMDET-R] all the rotation detection models supported by mmdeploy? (I obtained this list from the mmdeploy official website). In addition, I have converted Rotated RetinaNet, Gliding Vertex, and Oriented R-CNN into fp16 TensorRT models and tested the mAP of both TensorRT and pth on DOTA1.0. The test results show a large fluctuation. Is this normal?
<img width="1091" alt="image" src="https://github.com/open-mmlab/mmdeploy/assets/49706682/ebb7257b-ae0c-42bb-816c-2912640cd6ca">

**Comment by RunningLeon** [comment]
@BUAA-Worromot hi, something is wrong.  Could you test with fp32 precision?  BTW, the converted models were not tested on dataset.

**Comment by BUAA-Worromot** [comment]
Thanks for your reply. I tried to convert those three models mentioned above, but only gliding_vertex succeed,  the other two throw :```
[W] [TRT] Skipping tactic 0 due to Myelin error: autotuning: CUDA error 2 allocating 0-byte buffer: out of memory
[08/29/2023-16:28:00] [E] Error[10]: [optimizer.cpp::computeCosts::1981] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Unsqueeze_940...Slice_1018]}.) 
```
even when I set max_workspace_size to 16G. 
gliding_vertex with fp32 precision got mAP of 0.8110640048980713.
BTW, are [Rotated RetinaNet, Rotated FasterRCNN, Oriented R-CNN, Gliding Vertex, RTMDET-R] all the rotation detection models supported by mmdeploy?

**Comment by RunningLeon** [comment]
Could try with newer TRT. The supported model list is this https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmrotate.html#supported-models
