### ISSUE TITLE
Can support onnx simplify？

### ISSUE THREAD

**Issue by DDGRCF** [open-mmlab/mmdeploy#292]

**Comment by RunningLeon** [comment]
Hi, do you mean simplify onnx with [onnx-simplifier](https://github.com/daquexian/onnx-simplifier)?

**Comment by DDGRCF** [comment]
> Hi, do you mean simplify onnx with [onnx-simplifier](https://github.com/daquexian/onnx-simplifier)?

Yes, Can it support?

**Comment by RunningLeon** [comment]
@DDGRCF Hi, it depends. As far as I known, there's no plan for supporting onnx-simplifier in mmdeploy by far. Users can treat it as a post-processing of torch2onnx.
