### ISSUE TITLE
Looking forward exporting Mask2Former to ONNX

### ISSUE THREAD

**Issue by Kenneth-X** [open-mmlab/mmdeploy#298]
**Describe the feature**

**Motivation**

1. Many detection & sematic segmentation classical methods（e.g yolo,centernet, deeplabv3,ocrnet）has already  support  exporting to onnx and made a huge contribution for academia and industry field. But for panoptic segmentaion, mmlab series are still  not ready for that yet
2.  sota mask2former is a great achievement for  panoptic segmentaion( e.g transformer) . It will be wonderful if can be export to onnx（swin transfomer backbone） for depolyment

**Related resources**

If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.
`https://github.com/facebookresearch/Mask2Former`
`https://github.com/open-mmlab/mmdetection/tree/master/configs/mask2former`

**Comment by M-youyou** [comment]
Thanks for your advice. Looking forward exporting Mask2Former to ONNX, also.

**Comment by lvhan028** [comment]
Totally agree with the motivation. Transformer models will be our top priority in April.

**Comment by lvhan028** [comment]
This feature has been put into our backlog, which is supposed to be released in v0.6.0

**Comment by p890040** [comment]
> This feature has been put into our backlog, which is supposed to be released in v0.6.0

Hi, @lvhan028 
Thanks to the efforts of the mmopen team
The v0.6.0 version has been released, but I noticed that there is still no Mask2former feature.
Is there any difficulty in converting Onnx to Mask2former again? Or do you need additional operation support? 

Looking forward to your team's reply Thanks!

**Comment by lfxx** [comment]
> This feature has been put into our backlog, which is supposed to be released in v0.6.0

Any update on this?hope for onnx on Mask2Former.

**Comment by eliabruni** [comment]
I am also very interested, any updates? Thank you!

**Comment by fernandorovai** [comment]
Hello, any news on converting the mask2former? It opens the possibility to deploy this in large scale. Is there any way we can help?

**Comment by nubertj** [comment]
same here, we would also really appreciate this feature
@Idate96

**Comment by xunleiw** [comment]
Hello, is there an ETA when Mask2Former to ONNX feature will be supported?

**Comment by CristoJV** [comment]
any update now?

**Comment by nubertj** [comment]
@lvhan028 could you please reopen this issue?
Thank you :)

**Comment by lvhan028** [comment]
@RunningLeon may help handle this feature

**Comment by RunningLeon** [comment]
@Kenneth-X @nubertj @CristoJV @Robotatron @xunleiw hi, guys. If you have time, pls. try this PR https://github.com/open-mmlab/mmdeploy/pull/2347. Any comment on the PR is greatly appreciated.

**Comment by nubertj** [comment]
@RunningLeon amazing, thanks a lot.
We will give it a try :) M2F is still heavily used by us.

**Comment by nubertj** [comment]
@pascal-roth could successfully deploy it on our end, thanks a lot for the great contribution, @RunningLeon and @lvhan028! :)
