### ISSUE TITLE
Fail to run "cmake --build . --target install  --config Release -- /m"  for spdlog-1.9.2 in Windows CUDA，Ask for your help

### ISSUE THREAD

**Issue by Realxinhao** [open-mmlab/mmdeploy#299]
I run these codes in Pycharm Pro, with VS2019 16.11.11 and CUDA 11.3.
PS E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build> cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The CXX compiler identification is MSVC 19.29.30141.0
-- Detecting CXX compiler ABI info
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.9.2
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE
-- Build type: Release
-- Generating example(s)
-- Generating install
-- Configuring done
-- Generating done
-- Build files have been written to: E:/PycharmProjects/Deployment/MMDeploy/mmdeploy/spdlog-1.9.2/build
PS E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build> cmake --build . --target install  --config Release -- /m
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Building Custom Rule E:/PycharmProjects/Deployment/MMDeploy/mmdeploy/spdlog-1.9.2/CMakeLists.txt
  spdlog.cpp
  stdout_sinks.cpp
  color_sinks.cpp
  file_sinks.cpp
  async.cpp
  cfg.cpp
  fmt.cpp
  spdlog.vcxproj -> E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\Release\spdlog.lib
  Building Custom Rule E:/PycharmProjects/Deployment/MMDeploy/mmdeploy/spdlog-1.9.2/example/CMakeLists.txt
  example.cpp
  example.vcxproj -> E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\example\Release\example.exe
  Building Custom Rule E:/PycharmProjects/Deployment/MMDeploy/mmdeploy/spdlog-1.9.2/CMakeLists.txt
  -- Install configuration: "Release"
  CMake Error at cmake_install.cmake:36 (file):
    file INSTALL cannot make directory "C:/Program Files/spdlog/include": No
    such file or directory.

  -- Installing: C:/Program Files/spdlog/include
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: 命令“setlocal [E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd [E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [E:\PycharmProjects\Deployment\MMDeploy\mmdeplo 
y\spdlog-1.9.2\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel [E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\install.vcxproj]        
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1 [E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone [E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\ins 
roj]

**Comment by irexyc** [comment]
### Cause
The cmake default installation prefix is `C:/Program Files/`. Your powershell window didn't open as administrator, so you don't have right to write file to the system c:/ disk. 
```
CMake Error at cmake_install.cmake:36 (file):
file INSTALL cannot make directory "C:/Program Files/spdlog/include": No
such file or directory.
...
```

### Solution
When configure spdlog, try to set CMAEK_INSTALL_PREFIX variable.
```
PS E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build> cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DCMAEK_INSTALL_PREFIX=install
```
In your environment, it will be installed to 
```
E:\PycharmProjects\Deployment\MMDeploy\mmdeploy\spdlog-1.9.2\build\install\spdlog
```

**Comment by Realxinhao** [comment]
Thank U. It works
