### ISSUE TITLE
Support for MMRotate

### ISSUE THREAD

**Issue by bgsuello** [open-mmlab/mmdeploy#300]
Hello, are there any plans to support mmrotate?

**Comment by grimoire** [comment]
Hi,  @zytx121 is working on `roi_align_rotated` support for onnxruntime https://github.com/open-mmlab/mmdeploy/pull/277. And we are designing new apis so other repos can be supported easily.

**Comment by bgsuello** [comment]
thanks @grimoire

**Comment by Petros626** [comment]
@grimoire why finally so few `MMRotate` models are supported?
