### ISSUE TITLE
Support for Tengine

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#303]
https://github.com/OAID/Tengine

whether a plan to support the Tengine

**Comment by lvhan028** [comment]
Not yet. Our top priority this year is to make the model deployment of most OpenMMLab codebases come true. In q1, We've supported MMPose and MMDetection3D. In q2, we are going to support MMRotate, MMRazor, and Transformer-based models. In H2, the rest codebases will be addressed. And perhaps more devices will be taken into consideration. 
Regarding the backend engines, we are looking forward that the community can help us migrate them to MMDeploy

**Comment by vansin** [comment]
thanks
