### ISSUE TITLE
Text recognition module tensorrt conversion

### ISSUE THREAD

**Issue by WongVi** [open-mmlab/mmdeploy#315]
could you please write method to convert https://github.com/clovaai/deep-text-recognition-benchmark module into onnx and tensorrt ?

**Comment by lvhan028** [comment]
Currently, MMDeploy focuses on the deployment of OpenMMLab models. We are planning to support non-OpenMMLab models in the next few months.

@gaotongxiao, has MMOCR supported the models listed in the above benchmark?

**Comment by gaotongxiao** [comment]
MMOCR has only implemented CRNN in that benchmark. We might not include the other models in our recent dev plan, but we welcome and support any efforts from interested community members.
