### ISSUE TITLE
cmake error at csrc/preprocess/cuda/cmakelists.txt:7(find_packages):

### ISSUE THREAD

**Issue by ywfwyht** [open-mmlab/mmdeploy#322]
Installed the pplcv following the tutorial,  but find package was not found.

error message:
By not providing "Findpplcv.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "pplcv", but CMake did not find one.

Could not find a package configuration file provided by "pplcv" with any of the following names:
   pplcvConfig.cmake
   pplcv-config.cmake

add the installation prefix of "pplcv" to CMAKE_PREFIX_PATH or set "pplcv_DIR" to a directory containing one of the above files. If "pplcv" provides a separate development package or SDK, be sure it has been installed.

**Comment by grimoire** [comment]
As the error log mentioned, you need  to install pplcv before build sdk.
Read [install guide](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/build/linux.md) for more detail.

**Comment by grimoire** [comment]
As the error log mentioned, you need  to install pplcv before build sdk.
Read [install guide](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/build/linux.md) for more detail.

**Comment by vansin** [comment]
Could you provide more infos,

**Comment by vansin** [comment]
Could you provide more informations such as 

1. OS version
2. Cuda version
3. The installation log of ppl.cv

**Comment by ywfwyht** [comment]
> As the error log mentioned, you need to install pplcv before build sdk. Read [install guide](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/build/linux.md) for more detail.

This error occurs when compiling the sdk
