### ISSUE TITLE
how to init plugin in tensorrt（c++）

### ISSUE THREAD

**Issue by wang002** [open-mmlab/mmdeploy#327]
in python,we can use ctypes.CDLL(libmmdeploy_tensorrt_ops.so),but in c++,what should I do？
我在python里面是可以初始化plugin的，但是在c++无法运行原因是tensorrt找不到插件，tensorrt只能找到英伟达自己的插件。如何才能让它找到这个libmmdeploy_tensorrt_ops插件呢？

**Comment by lzhangzz** [comment]
On Linux, that would be [dlopen](https://man7.org/linux/man-pages/man3/dlopen.3.html). 

Or add `--no-as-needed mmdeploy_tensorrt_ops --as-needed` to your linker command to force linking without direct symbol reference.

**Comment by wang002** [comment]
Thank you for your help. It's useful
