### ISSUE TITLE
[bug] `os.getenv('DISPLAY')` failed on Windows

### ISSUE THREAD

**Issue by SingleZombie** [open-mmlab/mmdeploy#330]
Thanks for your bug report. We appreciate it a lot.

**Describe the bug**

When running `deploy.py` on my Windows laptop, I got the warning ""visualize_model" has been skipped" due to `os.getenv('DISPLAY')` returns `None`. However, it is impossible that my laptop doesn't have a display device. I guess `os.getenv('DISPLAY')` cannot work correctly on Windows.

PS: I think besides `is_display is not None`, `args.show` should also be checked when deciding whether to call visualization. Even when we are using a server, we need `visualize_model` to write the output to a file.

**Reproduction**

Run any script with `deploy.py` on Windows.

**Comment by grimoire** [comment]
@hanrui1sensetime Please have a look.

**Comment by hanrui1sensetime** [comment]
Hi, @SingleZombie , I will fix this bug by determine which os.

**Comment by hanrui1sensetime** [comment]
Hi, @SingleZombie  this bug has fixed and merged into master. You can have a try.
