### ISSUE TITLE
I want to contribute a precompiled package for Jetson nano.

### ISSUE THREAD

**Issue by PeterH0323** [open-mmlab/mmdeploy#343]
**Describe the feature**

Precompiled package for Jetson Nano.

**Motivation**

Hi, I see there is no precompiled package of mmdeploy for Jetson nano.

I want to know what should I pay attention to or avoide. And I need some guide at the same time. Thx! 😄

**Comment by grimoire** [comment]
Hi, I am working on a pre-build script for mmdeploy. Would you like to work together?

**Comment by PeterH0323** [comment]
> Hi, I am working on a pre-build script for mmdeploy. Would you like to work together?

Yes, I'd love to ! 😄

**Comment by tehkillerbee** [comment]
@grimoire I can probably help too, as I previously wrote a script for easier installation of MMDetection and MMDeploy on our Jetson platforms (NX, AGX and others). Feel free to write!

**Comment by grimoire** [comment]
@tehkillerbee welcome! I will create a discussion about our plan soon.

**Comment by grimoire** [comment]
https://github.com/open-mmlab/mmdeploy/discussions/354 Here is the discussion. We can discuss the task there.
