### ISSUE TITLE
Do you support inference the torchscript model with c++?

### ISSUE THREAD

**Issue by leeasong** [open-mmlab/mmdeploy#345]
I convert the mmdet faster rcnn model to torchscript. When i try to inference the torchscript model with c++, it failed. So i want to know if this is accessible. Many thanks.

**Comment by RunningLeon** [comment]
@leeasong Hi, could you post here what script you use and the error log if possible.

**Comment by leeasong** [comment]
I use this script to convert model to torchscript:
python ./tools/deploy.py configs/mmdet/detection/detection_torchscript.py /home/liw/mmdetection/tools/output_baseline/baseline_config.py /home/liw/mmdetection/tools/output_baseline/epoch_10.pth /home/liw/VisDrone2019_10classes/val/valimg/0000001_02999_d_0000005.jpg --work-dir ./tools/out --device cuda \
it succeeded

then i want to inference the torchscript model with c++. I use the c++ code from detectron2 because i didn't find it in mmdeploy. When i cmake, it went wrong
CMake Error at CMakeLists.txt:13 (add_executable):
  Target "demo" links to target "Python3::Python" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
So i want to know if this is accessible or it's installation problem.

**Comment by leeasong** [comment]
I also want to know if it is accessible to inference the torchscript model with c++. If so, where can i get the c++ code or build docs. like this https://github.com/facebookresearch/detectron2/blob/main/tools/deploy/torchscript_mask_rcnn.cpp

**Comment by AllentDan** [comment]
By now, we did not provide c++ inference codes for torchscript models in mmdeploy.

**Comment by leeasong** [comment]
thank you! hope it coming soon

**Comment by lvhan028** [comment]
This feature will be put in v0.6.0

**Comment by Z-star1** [comment]
i have the same problem, how do you take this problem?

**Comment by GeorgePearse** [comment]
I can't workout how to separate out the preprocessing code from MMDeploy so that I can not depend on it, and just rely on torch. 

e.g. 
```
model = torch.jit.load(<model-path>)
data = preprocessing(image)
result = model(data)
```
