### ISSUE TITLE
麻烦问下onnxruntime中ONNXTensorElementDataType：ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL 对应咱们mmdeploy中DataType哪一个数据类型

### ISSUE THREAD

**Issue by zly19540609** [open-mmlab/mmdeploy#350]
麻烦问下onnxruntime中ONNXTensorElementDataType：ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL
对应咱们mmdeploy中DataType哪一个数据类型
`enum class DataType : int32_t {
  kFLOAT,
  kHALF,
  kINT8,
  kINT32,
  kINT64
};`

**Comment by lzhangzz** [comment]
According to https://github.com/microsoft/onnxruntime/issues/3689, the closest thing we have is `DataType::kINT8`

**Comment by zly19540609** [comment]
Thanks for your answer.
