### ISSUE TITLE
image_segmentation.cpp call onnxruntime-cuda thrown an abnormal

### ISSUE THREAD

**Issue by joryoker** [open-mmlab/mmdeploy#351]
win10 mmdeploy image_segmentation.cpp call onnxruntime-static-cuda and onnxruntime-dynamic-cuda thrown an abnormal
call onnxruntime-static-cpu and onnxruntime-dynamic-cpu is ok
call tensorrt-static-cuda is ok
call tensorrt-dynamic-cuda error

![1649925571(1)](https://user-images.githubusercontent.com/45837432/163348480-755afba3-de9c-4e76-b989-371dd33c8619.png)
![1649925671(1)](https://user-images.githubusercontent.com/45837432/163348517-d6637dd9-6c56-4fd4-8e6c-651a3ffe7670.png)
![1649925777(1)](https://user-images.githubusercontent.com/45837432/163348536-39e2f89d-13eb-4f88-93f7-addf1027d451.png)
![1649925905(1)](https://user-images.githubusercontent.com/45837432/163348701-810c3aa1-e54e-4f55-b7d7-8719bf864027.png)

**Comment by irexyc** [comment]
For tensorrt-dynamic-cuda, according to segmentation_tensorrt_dynamic-512x1024-2048x2048.py, the minimum shape of width is 1024, and you supply 512, so as the log said, your input is not corrent.
```
input_shapes=dict(
    input=dict(
        min_shape=[1, 3, 512, 1024],
        opt_shape=[1, 3, 1024, 2048],
        max_shape=[1, 3, 2048, 2048])))
```

For onnxruntime cuda, what onnxruntime version are you using? I will check it on my machine.

**Comment by joryoker** [comment]
> For tensorrt-dynamic-cuda, according to segmentation_tensorrt_dynamic-512x1024-2048x2048.py, the minimum shape of width is 1024, and you supply 512, so as the log said, your input is not corrent.

thanks for you answer!
my onnxruntime version is 1.8.1

**Comment by irexyc** [comment]
Found the reason. There is a bug in mmseg postprocess, should be fixed with PR363

**Comment by joryoker** [comment]
i switch the csrc/codebase/mmseg，compile the mmdeploy SDK, but the same abnormal throwned.

> Found the reason. There is a bug in mmseg postprocess, should be fixed with PR363

**Comment by irexyc** [comment]
Do you use the [onnxruntime-win-gpu-x64-1.8.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.8.1/onnxruntime-win-gpu-x64-1.8.1.zip) instead of [onnxruntime-win-x64-1.8.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.8.1/onnxruntime-win-x64-1.8.1.zip) ?

Can you paste the dll loaded when you run image-segmentation like this:
![image](https://user-images.githubusercontent.com/16019484/163522064-136eb1a0-616a-473b-962d-9951efdae812.png)

**Comment by joryoker** [comment]
> Do you use the [onnxruntime-win-gpu-x64-1.8.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.8.1/onnxruntime-win-gpu-x64-1.8.1.zip) instead of [onnxruntime-win-x64-1.8.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.8.1/onnxruntime-win-x64-1.8.1.zip) ?
> 
> Can you paste the dll loaded when you run image-segmentation like this: ![image](https://user-images.githubusercontent.com/16019484/163522064-136eb1a0-616a-473b-962d-9951efdae812.png)

I use the onnxruntime-win-gpu-x64-1.8.1.zip，and object_detection.cpp is run OK
![1649999457(1)](https://user-images.githubusercontent.com/45837432/163523657-23f57fee-96e9-428f-804c-7889fcd98a9f.png)

![1649999482(1)](https://user-images.githubusercontent.com/45837432/163523668-68dc6721-eda4-4b45-9a35-f0fb0a043887.png)

**Comment by irexyc** [comment]
The crash on my machine is due to the wrong output [buffer](https://github.com/open-mmlab/mmdeploy/blob/8f67bb2a8a3a4fa114fec02fcc7cee596ccab164/csrc/codebase/mmseg/segment.cpp#L45) that opencv resize used.  The last two line shows errors in ```opencv_world455.dll``` so I doubt whether the code you corrected is right. :cry:

Can you check if the [code](https://github.com/open-mmlab/mmdeploy/blob/8f67bb2a8a3a4fa114fec02fcc7cee596ccab164/csrc/codebase/mmseg/segment.cpp) here is same with yours?  And don't forget to install the build dll to your path(D:\mm\mmdeploy\build\install\bin\)

**Comment by joryoker** [comment]
> 

I update you code ,compile the mmdeploy SDK,when I shell cmake --install . --config Release, the following error occurs

![1650010417(1)](https://user-images.githubusercontent.com/45837432/163544622-b2df6c86-e853-4307-addc-9021171592dc.png)

**Comment by joryoker** [comment]
> The crash on my machine is due to the wrong output [buffer](https://github.com/open-mmlab/mmdeploy/blob/8f67bb2a8a3a4fa114fec02fcc7cee596ccab164/csrc/codebase/mmseg/segment.cpp#L45) that opencv resize used. The last two line shows errors in `opencv_world455.dll` so I doubt whether the code you corrected is right. 😢
> 
> Can you check if the [code](https://github.com/open-mmlab/mmdeploy/blob/8f67bb2a8a3a4fa114fec02fcc7cee596ccab164/csrc/codebase/mmseg/segment.cpp) here is same with yours? And don't forget to install the build dll to your path(D:\mm\mmdeploy\build\install\bin)

I update you code ,compile the mmdeploy SDK,when I shell cmake --install . --config Release, the following error occurs

![1650010824(1)](https://user-images.githubusercontent.com/45837432/163545521-4e61cd52-ab96-490d-ab42-deed217953f3.png)

**Comment by irexyc** [comment]
Try empty the build dir and make a clean configure and build?

Or if cmake --build . --config Release -j success and mmdeploy_mmseg.dll generated after you delete it, you can manually copy the mmdeploy_mmseg.dll to the install/bin/ dir.

**Comment by joryoker** [comment]
> Try empty the build dir and make a clean configure and build?

I empty the build dir,shell cmake --build . --config Release -- /m, but the mmdeploy_mmseg.dll not generated and the following error occurs

![1650074856(1)](https://user-images.githubusercontent.com/45837432/163657598-39d040c9-b891-4566-8245-da78bb14cea7.png)

**Comment by irexyc** [comment]
Sorry, didn't test the code. 

I test the new [code](https://github.com/open-mmlab/mmdeploy/blob/a97ecb7bacb330fe7799a9894a6ced40747a6521/csrc/codebase/mmseg/segment.cpp), it should the work now,

**Comment by joryoker** [comment]
> Sorry, didn't test the code that can not be built.
> 
> I test the new [code](https://github.com/open-mmlab/mmdeploy/blob/a97ecb7bacb330fe7799a9894a6ced40747a6521/csrc/codebase/mmseg/segment.cpp), it should work now,

Thanks! I test the new code, It can be call  onnxruntime-cuda normally.

**Comment by joryoker** [comment]
> > Sorry, didn't test the code that can not be built.
> > I test the new [code](https://github.com/open-mmlab/mmdeploy/blob/a97ecb7bacb330fe7799a9894a6ced40747a6521/csrc/codebase/mmseg/segment.cpp), it should work now,
> 
> Thanks! I test the new code, It can be call onnxruntime-cuda normally.

Hi irexyc, 
I run the image_segmentation.cpp, obtain the mask of the whole image. but I only  obtain the mask of a class of defect, what should i do?

![1650242123(1)](https://user-images.githubusercontent.com/45837432/163738203-b3c2b970-1891-4050-a628-3260f24a85fa.png)

**Comment by irexyc** [comment]
Which image do you use?

I use the demo\resources\human-pose.jpg and the result is:
![image](https://user-images.githubusercontent.com/16019484/163788102-32bc059a-a374-469b-9eab-e2cc651f97c7.png)
![image](https://user-images.githubusercontent.com/16019484/163788018-9e733758-501a-4b69-ab3a-769a68b227af.png)

**Comment by irexyc** [comment]
I think your purple line has a label id and the background also has a label id. You can set the background color black like:

```
for (auto iter = color_mask.begin<cv::Vec3b>(); iter != color_mask.end<cv::Vec3b>(); ++iter) {
  if (result->mask[pos] != your background label id) {
    *iter = palette[result->mask[pos++]]; // or whatever the color you want 
  } else {
    pos++;
  }
}
```

Is that what you want?.  

I think it is a problem of how to use or show the segmentation mask that you should modify the demo code according to your purpose, other than a problem of running issue or something.

**Comment by joryoker** [comment]
Ok, thanks!
