### ISSUE TITLE
Centerpoint Conversion Error

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmdeploy#355]
Hi, I tried to deploy centerpoint with; 

DEPLOY_CFG_PATH="./configs/mmdet3d/voxel-detection/voxel-detection_static.py" 
MODEL_CFG_PATH="$HOME/mmdetection3d/configs/centerpoint/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus.py"
MODEL_CHECKPOINT_PATH="$HOME/mmdetection3d/checkpoints/centerpoint/centerpoint_02pillar_second_secfpn_circlenms_4x8_cyclic_20e_nus_20201004_170716-a134a233.pth"
INPUT_IMG="$HOME/mmdetection3d/demo/data/kitti/kitti_000008.bin"
WORK_DIR="$HOME/MMDeploy/logs/"

    python ./tools/deploy.py \
        ${DEPLOY_CFG_PATH} \
        ${MODEL_CFG_PATH} \
        ${MODEL_CHECKPOINT_PATH} \
        ${INPUT_IMG} \
       --work-dir ${WORK_DIR} \
       --log-level "INFO" \
       --show \
       --dump-info

However I got;

    File "./tools/deploy.py", line 102, in main
      dump_info(deploy_cfg, model_cfg, args.work_dir, pth=checkpoint_path)
    File "/home/orcun/MMDeploy/mmdeploy/utils/export_info.py", line 363, in dump_info
      deploy_info = get_deploy(deploy_cfg, model_cfg, work_dir=work_dir)
    File "/home/orcun/MMDeploy/mmdeploy/utils/export_info.py", line 283, in get_deploy
      cls_name = task_map[task]['cls_name']
    KeyError: <Task.VOXEL_DETECTION: 'VoxelDetection'>

**Comment by VVsssssk** [comment]
Hi. You can try to use other deploy configs that specify the backend, just like `configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-nus.py`. Voxel-detection_static.py and voxel-detection_dynamic.py cannot be used directly.

**Comment by OrcunCanDeniz** [comment]
Tried it as 

     python3 ./tools/deploy.py
        ./configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-nus.py     
        ${MODEL_CFG_PATH}     ${MODEL_CHECKPOINT_PATH}
        ${INPUT_IMG}    --work-dir ${WORK_DIR}    
        --log-level "INFO"    --show    --dump-info

Still no luck. Additionally I only want to export .onnx. Not trying to create the TRT engine right away. Would running TRT configs also serialize onnx format model too?

**Comment by VVsssssk** [comment]
OK, I find the problem. Please remove `--dump-info` args in your command because mmdeploy SDK does not support mmdet3d.

**Comment by tobeprozy** [comment]
ImportError: mmdet3d has not been installed. Import mmdet3d failed.
