### ISSUE TITLE
Will mmdeploy support SNPE or tflite in the future? Is there any plan?

### ISSUE THREAD

**Issue by starlitsky2010** [open-mmlab/mmdeploy#358]

**Comment by tpoisonooo** [comment]
* about SNPE
In the near future, mmdeploy intend to increase support on mobile/edge, SNPE is a great idea~

* about tflite
I am not sure, we need more dicussion.

**Comment by tpoisonooo** [comment]
snpe support is  WIP: https://github.com/open-mmlab/mmdeploy/pull/722

**Comment by tpoisonooo** [comment]
snpe support merged, close this issue.
