### ISSUE TITLE
Bug using ORTwrapper 

### ISSUE THREAD

**Issue by Stephenfang51** [open-mmlab/mmdeploy#37]
Here is the code using ortwrapper to inference on device
The model is maskrcnn trained through mmdet

Env:
torch1.8 
cuda 11.1 
onnx 1.8

```
from mmdeploy.backend.onnxruntime import ORTWrapper
import torch

onnx_file = 'end2end.onnx'

#gpu
model = ORTWrapper(onnx_file, 'cuda:3', ['dets', 'labels', 'masks'])
inputs = dict(input=torch.randn(1, 3, 768, 1344, device='cuda:3'))

outputs = model(inputs)
print(outputs)
```
no matter on host or device, it still got the error on reshape1588 node

[[21~2021-12-31 13:20:33.759103638 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_1588' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,3}, requested shape:{1,3,3}

**but works fine using `./tools/test.py`, did not see differnece between using ORTwrapper directly.**

**Comment by SingleZombie** [comment]
Hi. I run the same code on 'cpu' and 'cuda:0' successfully.  I think the error is caused by the environment (ONNX Runtime). Could you provide your ONNX Runtime version?

My Env:
torch 1.8.0
cuda 11.1
onnx 1.10.1
onnxruntime 1.9.0 (1.8.1 is enough)

**Comment by Stephenfang51** [comment]
@SingleZombie  Hi Zombie
my onnxruntime-gpu is 1.8 same as onnx
I think it may not cause by env since I use `tools/test.py` and it runs fine.

**Comment by SingleZombie** [comment]
@Stephenfang51 Hi. We tried many times and cannot reproduce the bug. Could you please upload your "end2end.onnx"?

**Comment by Stephenfang51** [comment]
> @Stephenfang51 Hi. We tried many times and cannot reproduce the bug. Could you please upload your "end2end.onnx"? We guess that the model maybe wrong.

Hi here's the link [end2end.onnx](https://drive.google.com/file/d/11TriYKSXqGqDJvC-sokEkLcMCwFJ5xiE/view?usp=sharing)
and HappyNewYear !

**Comment by SingleZombie** [comment]
Happy New Year! We may reply you in the next year.

**Comment by SingleZombie** [comment]
@Stephenfang51 Hi. Seems we don't have the access to the file. Could you open the access?

**Comment by Stephenfang51** [comment]
> @Stephenfang51 Hi. Seems we don't have the access to the file. Could you open the access?

Sorry about that, just updated. [end2end.onnx](https://drive.google.com/file/d/11TriYKSXqGqDJvC-sokEkLcMCwFJ5xiE/view?usp=sharing)

**Comment by grimoire** [comment]
Hi, could you provide more detail about your environment? Such as version of MMDetection(We only support mmdet>=2.19.0) and model config?

**Comment by Stephenfang51** [comment]
@grimoire 

The mmdet version  is 2.19.1

below is the config

```
_base_ = '../mask_rcnn/mask_rcnn_x101_64x4d_fpn_2x_coco.py'

model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=2),
        mask_head=dict(num_classes=2)))

# Modify dataset related settings
dataset_type = 'CocoDataset'
classes = ('class1','class2')
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=3,
    train=dict(
        type=dataset_type,
        img_prefix='data/myimg/images/train2017',
        classes=classes,
        ann_file='data/mylabel/annotations/instances_train2017.json'),
    val=dict(
        type=dataset_type,
        img_prefix='data/myimg/images/val2017',
        classes=classes,
        ann_file='data/mylabel/annotations/instances_val2017.json'),
    test=dict(
        type=dataset_type,
        img_prefix='/home/pathtouser/mmdetection-master/data/myimg/images/val2017',
        classes=classes,
        ann_file='/home/myimg/mmdetection-master/data/mylabel/annotations/instances_val2017.json'))

runner = dict(type='EpochBasedRunner', max_epochs=100)
load_from = "/home/pathtouser/mmdetection-master/weights/mask_rcnn_x101_64x4d_fpn_mstrain-poly_3x_coco_20210526_120447-c376f129.pth"
```

Did you guys test on my onnx model? How's going?

**Comment by SingleZombie** [comment]
Hi @Stephenfang51 , We did some experiments:
1. Why ORTWrapper throw errors when running the onnx model but other methods (`test.py`,` infernce_model`, `export`) not?

- We fed ORTWrapper a tensor in the normal distribution without preprocessing. Other methods preprocess the tensor (`create_input`, `build_dataset`).
- **Conclusion**: The model may throw errors to some specific inputs. This is a bug. 
2. Where is the bug?

- We exported your model to an onnx model. The file size of the onnx file was the same as yours, but we could not reproduce the bug on our model.
- We traced the output of `Reshape_1588` shown in the error log. We found that the output size of NMS is not correct. The output of NMS may generate an empty tensor in the subsequent operations. But it is strange that our model is different from yours.
- **Conclusion**: The empty tensor cause the bug. We cannot reproduce the bug on our exported model. Maybe our checkpoint or input image is different.

3. How to fix the bug?

    In `mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py::select_nms_index`, change `return batched_dets[:, 0:-1, :], batched_labels[:, 0:-1]` to `return batched_dets, batched_labele` may fix the bug.

Since we cannot reproduce the bug on our model, could you give us your checkpoint and input image?

**Comment by Stephenfang51** [comment]
Hi, @SingleZombie 

below are img and checkpoints, since all are unpublished, I will remove the sharelink by tomorrow.

[demo_img](https://drive.google.com/file/d/1kXZf67EdKLFDj_HGCZqlucXvs7G2gVhe/view?usp=sharing)
[maskrcnn_checkpoints](https://drive.google.com/file/d/1ipVc5kBO4g61XNGUZqun-48Pcnm3XSw3/view?usp=sharing)

**Comment by SingleZombie** [comment]
> 

Thanks for providing your checkpoint! We will test and fix the bug in the next PR.
