### ISSUE TITLE
How to call TensorRT's inference engine SDK through C++ or C#?

### ISSUE THREAD

**Issue by 1wang11lijian1** [open-mmlab/mmdeploy#375]
How to call TensorRT's inference engine SDK through C++ or C#?

**Comment by lzhangzz** [comment]
If you mean "inference with TensorRT model converted by MMDeploy", please refer to demo/csrc.

Currently we maintain stable APIs for C and Python. C# API is in WIP status.

**Comment by 1wang11lijian1** [comment]
> 

OK, Thanks. Does the model_path in object_detection.cpp refer to the converted TensorRT inference engine? What is the content of detector.h file in object_detection.cpp?

**Comment by lzhangzz** [comment]
- `model_path` refers to the directory passed via `--work-dir` when converting the model. (notice that --dump-info must be supplied to genrated the meta files needed by SDK)
- `detector.h` is a header file in mmdeploy C API, which will be installed to specifed location after building mmdeploy SDK.

**Comment by 1wang11lijian1** [comment]
> 

Hi, I have figured out what you mean. Now I start to run the object_detection.cpp file, and there is a problem, I hope you can help me solve it again, thank you very much!

_**error LNK2019 unresolved external symbol mmdeploy_detector_create_by_path, referenced in function main**_
