### ISSUE TITLE
can you share a compiled docker image ?

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdeploy#376]
Hi I have tried many times to build a docker image with the docker/GPU/Dockerfile, but I couldn't make it as every time I ran into this problem:

> [ 1/12] FROM nvcr.io/nvidia/tensorrt:21.04-py3@sha256:7d6115baf9b7a810cf825414330853dc3640cbf9e0278b942db2ad7711d600b3:
> ------
> failed to copy: httpReadSeeker: failed open: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized

I was wondering if you can share a compiled docker image so that I can use it without building. Thanks.

**Comment by lvhan028** [comment]
As a matter of fact, we discussed providing the built docker image. But the question is where to put it. If we put it to docker hub, you will still face the same awkward situation.

**Comment by hyz-xmaster** [comment]
Thanks for your reply. Is it possible to put it on some clouds, like ali yun?

**Comment by lvhan028** [comment]
> Thanks for your reply. Is it possible to put it on some clouds, like ali yun?

We'll discuss it internally and let you know the result asap

**Comment by lvhan028** [comment]
Hi, @hyz-xmaster. After internal discussion, I am sorry to let you know we are not going to provide the docker image service on aliyun this year due to the budget.
