### ISSUE TITLE
[DOC] Benchmark Performance DOC BUGs

### ISSUE THREAD

**Issue by PeterH0323** [open-mmlab/mmdeploy#384]
# DOC
`docs/en/benchmark.md#Performance benchmark`

# MMCLS
## Title
`TorchScript` blow `seresnet` -> `FP32`

## Incorrect Config
| Model Name | Config Name | Suggestion |
| --- | --- | --- | 
| SE-ResNet-50 | $MMCLS_DIR/configs/resnext/resnext50_32x4d_b32x8_imagenet.py | $MMCLS_DIR/configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py |
| MobileNet V2 | $MMEDIT_DIR/configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py | configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py |

## Can't find info in model metafile
| Model Name | Config Name | Suggestion |
| --- | --- | --- | 
| ShuffleNetV1 1.0x | $MMCLS_DIR/configs/shufflenet_v1/shufflenet_v1_1x_b64x16_linearlr_bn_nowd_imagenet.py | $MMCLS_DIR/configs/shufflenet_v1/shufflenet-v1-1x_16xb64_in1k.py |
| ShuffleNetV2 1.0x | $MMCLS_DIR/configs/shufflenet_v2/shufflenet_v2_1x_b64x16_linearlr_bn_nowd_imagenet.py | $MMCLS_DIR/configs/shufflenet_v2/shufflenet-v2-1x_16xb64_in1k.py |
| MobileNet V2 | $MMEDIT_DIR/configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py | configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py |

**Comment by RunningLeon** [comment]
Agree to use suggested configs. As for missing info in metafile of mmcls, it would be covered in this issue: https://github.com/open-mmlab/mmclassification/issues/800
