### ISSUE TITLE
OCRNet onnx convert tensorrt failed

### ISSUE THREAD

**Issue by elfpattern-code** [open-mmlab/mmdeploy#387]
**Describe the bug**
<img width="741" alt="image" src="https://user-images.githubusercontent.com/84064744/164589305-4bc0a77f-86e1-460b-b00c-5621a7c2755f.png">

1. What command or script did you run?
python deploy.py  ocrnet18/deploy/segmentation_tensorrt-fp16_static-512x512.py  ocrnet18/ocrnet_hr18s_512x1024_160k_cityscapes.py  mmsegmentation-0.21.1/tools/work_dirs/ocrnet_hr18s_512x1024_160k_cityscapes/iter_160000.pth /mnt/net_school/libu_test_dataset/test.jpg  --test-img /mnt/net_school/cityscapes/leftImg8bit/val/ --dump-info --work-dir /home/zj/pass_seg/ocrnet18/

2. I found the code is wrong, How to fix it?
<img width="587" alt="image" src="https://user-images.githubusercontent.com/84064744/164589478-14ab6fe8-74c6-4c26-a536-f27efb7da7a0.png">

**Comment by AllentDan** [comment]
Thanks for reporting the bug, get fixed in PR #394
