### ISSUE TITLE
How to set verbose=True when export onnx using tools/deploy.py configs/mmdet/detection/detection_onnxruntime_dynamic.py

### ISSUE THREAD

**Issue by pengaoao** [open-mmlab/mmdeploy#400]
How to set verbose=True when export onnx using tools/deploy.py configs/mmdet/detection/detection_onnxruntime_dynamic.py

**Comment by hanrui1sensetime** [comment]
Please refer to https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/apis/pytorch2onnx.py line35.
You can add `verbose=True` in `configs/_base_/onnx_config.py`, and enjoy it.
