### ISSUE TITLE
shufflenet_v1 and  shufflenet_v2 conver dynamic fail

### ISSUE THREAD

**Issue by PeterH0323** [open-mmlab/mmdeploy#405]
## Describe the bug

shufflenet_v1 using cfg below convert to TensorRT fail.
- `configs/shufflenet_v1/shufflenet-v1-1x_16xb64_in1k.py`

shufflenet_v2 using cfg below convert to TensorRT fail.
- `configs/shufflenet_v2/shufflenet-v2-1x_16xb64_in1k.py`

## Fail message
![0569ab53871d36d1221012c047a53e7](https://user-images.githubusercontent.com/25873202/167884335-7f67f383-fd40-49dd-b481-73337557ff03.jpg)

## Env info
![00293a014f1622d688a1e3da53ad52c](https://user-images.githubusercontent.com/25873202/167884233-a8da6138-b618-4669-b7b4-daa1984eef5d.jpg)

**Comment by RunningLeon** [comment]
@hanrui1sensetime Hi, pls. take a look at this issue.

**Comment by hanrui1sensetime** [comment]
Hi, @PeterH0323 I will contact you about this issue.

**Comment by RunningLeon** [comment]
@PeterH0323 we may close this issue.

**Comment by PeterH0323** [comment]
The convertion, which fail, of my env is:
- trt 8.2.1.8
- cuda 11.5
- cudnn 8.0.5.39

When I am using env below it work !
- trt 7.2.1.6
- cudnn 8.0.5.39
- cuda 11.1

**Comment by lvhan028** [comment]
Hi, @PeterH0323 is it still an issue in mmdeploy v0.5.0?

**Comment by PeterH0323** [comment]
Still not working when using dynamic
![image](https://user-images.githubusercontent.com/25873202/174421010-799346ca-7a4a-451d-9f2b-ed02f56f9f22.png)

I suggest add `*` for `shufflenet_v1` and `shufflenet_v2` in the model support list

**Comment by PeterH0323** [comment]
Hi @lvhan028 
I tested on 0.5.0 and I still got errot when using dynamic:

![image](https://user-images.githubusercontent.com/25873202/174421010-799346ca-7a4a-451d-9f2b-ed02f56f9f22.png)

I suggest add `*` for `shufflenet_v1` and `shufflenet_v2` in the model support list
