### ISSUE TITLE
Difference between keep_top_k and max_output_boxes_per_class

### ISSUE THREAD

**Issue by Unlucky910** [open-mmlab/mmdeploy#406]
Can somebody explain the difference between keep_top_k and max_output_boxes_per_class in the onnx_config files?

Kind regards

**Comment by RunningLeon** [comment]
@Unlucky910 Hi, `keep_top_k` means max number of totally output bboxes after nms. `max_output_boxes_per_class` means max number of output bboxes of each class after multiclass-nms. The later parameter is aligned with nms defined in onnx op: https://github.com/onnx/onnx/blob/main/docs/Operators.md#nonmaxsuppression

**Comment by RunningLeon** [comment]
There's only one nms and the second step is only to keep top k boxes of concat of all output bboxes per class. You can refer to this code:
https://github.com/open-mmlab/mmdeploy/blob/f6fcee5f12085a70eb5f5fc0804a5cdaef97fd9c/mmdeploy/mmcv/ops/nms.py#L43

**Comment by RunningLeon** [comment]
Closed due to time. Feel free to reopen.
