### ISSUE TITLE
instance segmentation support/example using C API

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#41]
**Describe the feature**
Instance segmentation does not appear to be supported by the C API at this point. This would be a very welcome addition.

**Motivation**
I looked at the MMDeploy SDK C code and noticed that the examples do not cover Instance segmentation.

However, it is possible to deploy a model for instance segmentation (Mask RCNN) using TensorRT backend. The resulting TensorRT model works correctly. Visualizing the output shows identical output for PyTorch/TensorRT (albeit with incorrect CLASSES, since I use custom classes). Running the same model with the "object_detection.cpp" does work, although with no masks.

If this feature is already supported internally by the C API, feel free to point me in the right direction so I can make an example application myself.

**Comment by lvhan028** [comment]
Hi, @tehkillerbee. Please refer to `detector.h`. It supports both object detection and instance segmentation.

**Comment by tehkillerbee** [comment]
@lvhan028 Thank you for your advice, I managed to get it working. Should I update the `object_detection.cpp` example accordingly or should I add a separate instance segmentation example?

**Comment by lvhan028** [comment]
I think it's better to update `object_detection.cpp`.  For one thing, it is consistent with the header file , for another the user document won't be changed:)

**Comment by tehkillerbee** [comment]
Ok! I need to make sure the example still works with mmdetection models that does not use mask output. Can I assume that "bboxes[i].mask" will be a nullptr, if the mask is not used?

**Comment by lvhan028** [comment]
> Ok! I need to make sure the example still works with mmdetection models that does not use mask output. Can I assume that "bboxes[i].mask" will be a nullptr, if the mask is not used?

sure

**Comment by lvhan028** [comment]
pr #55
