### ISSUE TITLE
compilation error requires c++20

### ISSUE THREAD

**Issue by nihui** [open-mmlab/mmdeploy#413]
in cmakelists.txt, it claims c++17
```cmake
set(CMAKE_CXX_STANDARD 17)
```

however, std::source_location is only available from C++20 onwards

```
In file included from /home/nihui/osd/MMDeploy/csrc/core/status_code.h:11,
                 from /home/nihui/osd/MMDeploy/csrc/core/status_code.cpp:3:
/home/nihui/osd/MMDeploy/csrc/core/utils/source_location.h:9:29: 错误：‘source_location’不是命名空间‘std’中的一个类型名
    9 | using SourceLocation = std::source_location;
      |                             ^~~~~~~~~~~~~
/home/nihui/osd/MMDeploy/csrc/core/utils/source_location.h:9:24: 附注：‘std::source_location’ is only available from C++20 onwards
    9 | using SourceLocation = std::source_location;
      |                        ^
```

**Comment by lzhangzz** [comment]
It looks like there is a bug when detecting whether source_location is available. 

`std::source_location` has experimental support in libstdc++ even without C++20 support for quite a while. We tried to detect whether it's available with some macros, however it failed to work on your compiler.

So, what compiler are you using to compile mmdeploy?

**Comment by nihui** [comment]
fedora 35
gcc 11.2.1
