### ISSUE TITLE
build docker image error from Dockerfile

### ISSUE THREAD

**Issue by zranguai** [open-mmlab/mmdeploy#420]
I have tried many times, and failed to build from the Dockfile many times due to network reasons, etc. Can you provide the .tar.gz file or publish the compiled docker image to the docker hub

**Comment by GeneralJing** [comment]
almost the same problem. a docker image from the docker hub is a better solution. can you supply it?

**Comment by lvhan028** [comment]
> almost the same problem. a docker image from the docker hub is a better solution. can you supply it?

OK. We will work on it.

**Comment by GeneralJing** [comment]
fast reply, thank you. here are the errors.
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavutil56_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 185.125.190.36 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavcodec58_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 185.125.190.36 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libs/libssh/libssh-gcrypt-4_0.9.3-2ubuntu2.2_amd64.deb  Connection failed [IP: 91.189.91.38 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libswscale-dev_4.2.4-1ubuntu0.1_amd64.deb  Connection failed [IP: 185.125.190.36 80]
Almost always these files cannot be downloaded，even i use different computers.

**Comment by lvhan028** [comment]
@GeneralJing @zranguai Have you guys tried to build docker image passing args `USE_SRC_INSIDE=true`? If it is turned on, aliyun source will be adopted.

**Comment by GeneralJing** [comment]
yes, i let the USE_SRC_INSIDE=true. the files listed above can be downloaded. but when going to download mmdeploy, it stucked. I commented the last few steps, and when the docker image is built, I downloaded and installed the last step files manually and install by mapping inside the container.

**Comment by lvhan028** [comment]
> yes, i let the USE_SRC_INSIDE=true. the files listed above can be downloaded. but when going to download mmdeploy, it stucked. I commented the last few steps, and when the docker image is built, I downloaded and installed the last step files manually and install by mapping inside the container.

Well, that sounds an optional solution.

**Comment by lvhan028** [comment]
Sorry, folks. The built image is too large, over 14G. #683 
We haven't figured out a good solution yet.

**Comment by GeneralJing** [comment]
i think that size is normal. Users need is a correct env, the size is the second consideration.
