### ISSUE TITLE
Support non-rgb inputs

### ISSUE THREAD

**Issue by GPhilo** [open-mmlab/mmdeploy#437]
**Describe the feature**

Add support for models that don't take 3-channel images as input (e.g., grayscale-only models)

**Motivation**

Currently, the library always assumes that the input is a 3 channels image, while it's possible to train models (e.g., in mmclassification) that take a different number of channels as input. 

**Additional context**

Supporting grayscale input is relatively simple, as the changes that need to be done are minimal.
In my forked codebase (I'm using v0.25.1), this is what I did:

1) Add channels information in deploy config

The way I did it was adding an optional third value to `onnx_config['input_shape']` ad adapting `get_input_shape` in config_utils to allow length 2 or 3 instead of always expecting length 2. , In hindsight I'd rather add it separately as `onnx_config['input_channels']` or something similarly named and add a matching getter function in config_utils.

2) Make the input grayscale if the number of channels is 1

This only needs to be done in 2 points:

(`input_channels` is the channels information extracted from the configuration)

In `torch2onnx()`:

After loading the model inputs via `data, model_inputs = task_processor.create_input(img, input_shape)`:
```python
    if input_channels == 1:
        model_inputs = model_inputs[:,0,None,...]
```
(I didn't do a proper grayscale conversion as I believe it was not needed, but this is also easy to change if that should be necessary)

In visualize_model():

```python
    if input_channels == 1:
        model_inputs['img'] = model_inputs['img'][:,0,None,...]
```

With these modifications, I can now export models with single-channel input.

**Comment by grimoire** [comment]
Thanks for the advice. But why don't we just edit the model config? There is a `color_type` flag in the `LoadImageFromFile`.

https://github.com/open-mmlab/mmclassification/blob/7c5ddb1e5bee68d52ff8b5622cdbd75c02792c07/mmcls/datasets/pipelines/loading.py#L31

you can edit your model config without changing anything else.

**Comment by GPhilo** [comment]
Sorry, I should have mentioned this in the orginal post: I already have that in my model config:

```python
test_pipeline = [
    dict(type='LoadImageFromFile', color_type='grayscale'),
    dict(type='GenerateBBoxFromCharactersBox', is_training=False),
    dict(type='TopDownAffine'),
    dict(type='ToTensor'),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'image_file', 'center', 'scale', 'rotation', 'bbox_score',
            'flip_pairs'
        ]),
]
```

(You can ignore the `GenerateBBoxFromCharactersBox` step, it's a custom step I wrote that is irrelevant to the issue)
Still, [create_input always loads an RGB image if it's given as a filename](https://github.com/open-mmlab/mmdeploy/blob/86ab0637bc771a08f47f409b683a327c1b0d5da7/mmdeploy/codebase/mmpose/deploy/pose_detection.py#L148), ignoring the model configuration for `LoadImageFromFile`, and then it feeds the numpy array through the rest of the pipeline.
So perhaps the best solution would be to fix `create_input` to stick to the color type given in the model config instead.

**Comment by GPhilo** [comment]
This is how you would change `create_input` to let `LoadImageFromFile` load the image, while still retaining the width and height information to build the rest of the data dict:

```patch
diff --git a/mmdeploy/codebase/mmpose/deploy/pose_detection.py b/mmdeploy/codebase/mmpose/deploy/pose_detection.py
index 0405523..ec83b62 100644
--- a/mmdeploy/codebase/mmpose/deploy/pose_detection.py
+++ b/mmdeploy/codebase/mmpose/deploy/pose_detection.py
@@ -145,8 +145,10 @@ class PoseDetection(BaseTask):
         dataset_info = DatasetInfo(dataset_info)
 
         if isinstance(imgs, str):
-            imgs = mmcv.imread(imgs)
-        height, width = imgs.shape[:2]
+            _im = mmcv.imread(imgs)
+        else:
+            _im = imgs
+        height, width = _im.shape[:2]
         # create dummy person results
         person_results = [{'bbox': np.array([0, 0, width, height])}]
         bboxes = np.array([box['bbox'] for box in person_results])
@@ -165,8 +167,6 @@ class PoseDetection(BaseTask):
 
             # prepare data
             data = {
-                'img':
-                imgs,
                 'center':
                 center,
                 'scale':
@@ -189,6 +189,10 @@ class PoseDetection(BaseTask):
                     'flip_pairs': flip_pairs
                 }
             }
+            if isinstance(imgs, str):
+                data.update(image_file=imgs)
+            else:
+                data.update(img=imgs)
 
             data = test_pipeline(data)
             batch_data.append(data)
```
With this, no other modifications are necessary in the codebase.
