### ISSUE TITLE
Onnx wrapper gpu,cpu support bug

### ISSUE THREAD

**Issue by sanjaypavo** [open-mmlab/mmdeploy#444]
Hi , I am facing an issue when trying to infer in onnx model in **cpu**. The problem is [wrapper.py](https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/backend/onnxruntime/wrapper.py) in this script in the [line53](https://github.com/open-mmlab/mmdeploy/blob/f45c1f09b15aaca227a91ecaed8123d308044aae/mmdeploy/backend/onnxruntime/wrapper.py#L53), which sets the provider to CUDA if the device is CUDA enabled. I have debugged the error, willing to give a PR. Thanks in advance.

**Comment by lvhan028** [comment]
Look forward to your PR

**Comment by lvhan028** [comment]
@sanjaypavo Thanks very much for your PR (#532)
