### ISSUE TITLE
Warning regarding pre_top_k

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#452]
Hey guys,

When running model generation on Jetson AGX Xavier, we get the following warning:

```
[TensorRT] INFO:   Calibrated batch 41 in 2.60759 seconds.
Warning: pre_top_k need to be reduced for devices with arch 7.2, got pre_top_k=1000
Warning: pre_top_k need to be reduced for devices with arch 7.2, got pre_top_k=1000
```

As I understand from the jetson documentation, this only applies to TX2 and Nano but we get the warning also on AGX. Is this intentional? FYI, the model generation appears to work fine on AGX - even when leavning pre_top_k unchanged or reducing it to 1000, as I did in the above example. 

Do we reduce pre_top_k due to a cuda Compute Capability limitation or a GPU memory limitation?

I seem to remember an issue describing why pre_top_k must be reduced on some Jetson platforms - but I cannot find it.

**Comment by lzhangzz** [comment]
Actually the arch is wrong here. This only applies to `sm_53` (Jetson Nano) and `sm_62` (Jetson TX2). And maybe it's better to defer the diagnostic until the kernel launch is failed. Care to submit a PR to fix this?

> Do we reduce pre_top_k due to a cuda Compute Capability limitation or a GPU memory limitation?

The exact root cause is unclear at the moment. But I suspect this is caused by archs leading to certain launch configuration so that more shared memroy is requested than the device actually have.

**Comment by tehkillerbee** [comment]
@lzhangzz That makes sense. I will look at a PR to fix this issue ASAP. 

The arch looks straightforward to change in `allClassNMS.cu`

You suggest moving it until after kernel launch has failed, do you mean we check for cudaErrors and print the warning accordingly if kernel launch failed (i.e. if a relevant cudaError occured)? Something like this:

```cpp
  cudaError_t code = cudaGetLastError();
  if (code != cudaSuccess && code != <launch error code>) {
    printf("Warning: pre_top_k need to be reduced for devices with arch 7.2, got pre_top_k=%d\n",
           top_k);
    LOG(ERROR) << "CUDA error: " << cudaGetErrorString(code);
    return RC_DEVICE_RUNTIME_ERROR;
  }
```

If so, should we still do this check in `allClassNMS()`?

**Comment by lzhangzz** [comment]
Yes, we can replace 

https://github.com/open-mmlab/mmdeploy/blob/37868566603b363b2f77da369c279e28461de123/csrc/backend_ops/tensorrt/batched_nms/allClassNMS.cu#L215

with something like the code you mentioned above.
