### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

### ISSUE THREAD

**Issue by GeneralJing** [open-mmlab/mmdeploy#454]
execute 'pip install -e .' command. it occured error:
ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxx/data/projects/xxx/work/MMDeploy/setup.py'"'"'; __file__='"'"'/home/idriver/data/projects/xxx/work/MMDeploy/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tgk9t2hm
         cwd: /home/xxx/data/projects/xxx/work/MMDeploy/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxx/data/projects/xxx/work/MMDeploy/setup.py", line 132, in <module>
        install_requires=parse_requirements('requirements/runtime.txt'),
      File "/home/xxx/data/projects/xxx/work/MMDeploy/setup.py", line 103, in parse_requirements
        packages = list(gen_packages_items())
      File "/home/xxx/data/projects/xxx/work/MMDeploy/setup.py", line 91, in gen_packages_items
        for info in parse_require_file(require_fpath):
      File "/home/xxx/data/projects/xxx/work/MMDeploy/setup.py", line 83, in parse_require_file
        for line in f.readlines():
      File "/opt/conda/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

**Comment by tpoisonooo** [comment]
Since `0x87` in [ascii table](https://www.rapidtables.com/code/text/ascii-table.html) is not defined, I deduce that your `runtime.txt` is not an utf-8 file.

Would you please try these:

* pdb `/path/to/MMDeploy/setup.py` line 91, check what is really read from the file, it should be
```bash
h5py
matplotlib
numpy
onnx>=1.8.0
six
terminaltables
```
* `git checkout requirements/runtime.txt`  and make sure it is an utf-8 file  
* make sure that your local language in terminla  is utf8 (en or zh_cn):
```bash
$ locale -a
...
en_US.utf8
...
```

**Comment by GeneralJing** [comment]
solved. thank you, big guy.

**Comment by L-Carson** [comment]
I met the problem, alse. Could you tell me how you deal with it
