### ISSUE TITLE
Quantized Model for Torchscript

### ISSUE THREAD

**Issue by xingyueye** [open-mmlab/mmdeploy#456]
Hello～ Do you have plan to support quantized models for torchscript?

**Comment by tpoisonooo** [comment]
Work In Progress.

It is very likely not to use torch directly, we need convert it to onnx first, quantize model based on **static graph**.

**Comment by tpoisonooo** [comment]
In **dynamic graph**, you define  a `tensor` and slice it with `[]`. It would be converted to `gather` opr. Not to mention `if` clause.

**Comment by tpoisonooo** [comment]
https://github.com/open-mmlab/mmdeploy/pull/476
