### ISSUE TITLE
ImportError: mmdet3d has not been installed. Import mmdeploy.codebase.mmdet3d failed.

### ISSUE THREAD

**Issue by GeneralJing** [open-mmlab/mmdeploy#458]
after building the docker images with the Dockerfile, i want to conver the model to tensorrt. the command:
python tools/deploy.py ./configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-kitti.py ../mmdetection3d/configs/pointpillars/hv
_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py ../mmdetection3d/checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth ../mmdetection3d/demo/data/kitti/kitti_000008.bin --work-dir converted_model/ --device cuda:0 --show
i got the errors below:
2022-05-10:07:14:04,root ERROR    [utils.py:43] mmdet3d has not been installed. Import mmdeploy.codebase.mmdet3d failed.
Traceback (most recent call last):
  File "/home/xxx/data/projects/xxx/work/MMDeploy/mmdeploy/utils/utils.py", line 38, in target_wrapper
    result = target(*args, **kwargs)
  File "/home/xxx/data/projects/xxx/work/MMDeploy/mmdeploy/apis/pytorch2onnx.py", line 102, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/home/xxx/data/projects/xxx/work/MMDeploy/mmdeploy/apis/utils.py", line 21, in build_task_processor
    import_codebase(codebase_type)
  File "/home/xxx/data/projects/xxx/work/MMDeploy/mmdeploy/codebase/__init__.py", line 27, in import_codebase
    raise ImportError(
ImportError: mmdet3d has not been installed. Import mmdeploy.codebase.mmdet3d failed.
2022-05-10 07:14:04,591 - mmdeploy - ERROR - torch2onnx failed.

https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_convert_model.html#:~:text=MMSegmentation%2C%20MMOCR%2C%20MMEditing.-,How%20to%20convert%20models%20from%20Pytorch%20to%20other%20backends,-Prerequisite
from the how_to_convert_model.html, there are two prerequisites. before converting the model, should i install tensorrt and mmdetection? the error is about mmdet3d, are these related? or, should i install mmdetection3d?
in the docker container, i can find the tensorrt as follows:
ii  libnvinfer-bin                       7.2.3-1+cuda11.1                  amd64        TensorRT binaries
ii  libnvinfer-dev                       7.2.3-1+cuda11.1                  amd64        TensorRT development libraries and headers
ii  libnvinfer-plugin-dev                7.2.3-1+cuda11.1                  amd64        TensorRT plugin libraries and headers
ii  libnvinfer-plugin7                   7.2.3-1+cuda11.1                  amd64        TensorRT plugin library
ii  libnvinfer7                          7.2.3-1+cuda11.1                  amd64        TensorRT runtime libraries
ii  libnvonnxparsers-dev                 7.2.3-1+cuda11.1                  amd64        TensorRT ONNX libraries
ii  libnvonnxparsers7                    7.2.3-1+cuda11.1                  amd64        TensorRT ONNX libraries
ii  libnvparsers-dev                     7.2.3-1+cuda11.1                  amd64        TensorRT parsers libraries
ii  libnvparsers7                        7.2.3-1+cuda11.1                  amd64        TensorRT parsers libraries
i'm confused, can you give some advice?

**Comment by AllentDan** [comment]
@GeneralJing You have to install mmdet3d first before you use it. MMDeploy does not pre-install any other OpenMMLab packages for users.

**Comment by GeneralJing** [comment]
thank you for your reply. i have already done that.

**Comment by ke-dev** [comment]
hello developer, i have the same problem, can you please explain in detail how to solve it, it will be of great help to me, thanks @GeneralJing

**Comment by ke-dev** [comment]
How to install another docker environment inside one docker

**Comment by ke-dev** [comment]
How to install another docker environment inside one docker @AllentDan

**Comment by ke-dev** [comment]
run command `python setup.py develop`

**Comment by GeneralJing** [comment]
thank you
