### ISSUE TITLE
Retardation of model inference

### ISSUE THREAD

**Issue by zhaoyuan1209** [open-mmlab/mmdeploy#46]
I'm inference on the CPU. YOLOF model is converted to ONNX model from 2S to 4S. The YOLOX model is also slowed down. Why is that?

**Comment by lvhan028** [comment]
Hi, could you please provide your test setting?

**Comment by zhaoyuan1209** [comment]
I'm sorry, but I found it took a lot of time to load the model during the experiment today. I rewrote the Inference_Model method to separate the loading model from the inference. I find that inference time is accelerated.
