### ISSUE TITLE
end2end.engine to Triton

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmdeploy#465]
Hi, I built the MMDeploy GPU Dockerfile and installed MMDetection on top of it to generate an `end2end.engine` file.

I tried to run this in NVIDIA’s Triton docker image, but got errors due to missing plugins.

I see that there’s some documentation on installing plugins, but it does not seem straight forward to add those instructions to a Dockerfile that uses Triton’s image as a base.

Since this is probably a very common use case, could I request details or a feature request to include a Dockerfile for Triton server with necessary plugins added?

Appreciate any assistance or advice, thanks!

**Comment by lvhan028** [comment]
@austinmw Is it related to #460? 
Regarding " got errors due to missing plugins", could you paste the error log?
Can you let me know how to reproduce it? I'll fix it as soon as possible. Or you can make a PR if you'd like. We'll appreciate it a lot.

**Comment by lvhan028** [comment]
I got it. 
When MMDeploy develops a bunch of custom tensorrt plugins for model deployment, especially the detection models. Those plugins are built into a dynamic lib 'libmmdeploy_tensorrt_ops.so', which has to be loaded before inference. 

Let me find out if there is any improvement.

**Comment by lvhan028** [comment]
Hi, @austinmw sorry for replying late. 
I am afraid "LD_PRELOAD" has to be used. Otherwise, the custom ops cannot be found. 
MMDeploy providing a prebuilt package might be a better way to improve the experience.

**Comment by austinmw** [comment]
Thanks for your response!

**Comment by austinmw** [comment]
@manhtd98 You need to set the batch dimension in the mmdeploy config file to the max batch size in `opt_shape` and `max_shape` for it to allow batches.

**Comment by manhtd98** [comment]
@austinmw Error when create tensorrt file. here is config file: Error Code 4: Internal Error (input: kMAX dimensions in profile 0 are [128,3,800,1344] but input has static dimensions [1,3,800,1344].)
```
_base_ = ['./base_static.py', '../../_base_/backends/tensorrt-fp16.py']

onnx_config = dict(input_shape=(1344, 800))

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 800, 1344],
                    opt_shape=[128, 3, 800, 1344],
                    max_shape=[128, 3, 800, 1344])))
    ])

```

**Comment by austinmw** [comment]
I didn't use an `onnx_config` like that, it may be incorrect. I think you need to use one of the dynamic config files as a base instead of the static config. For example, starting with [this](https://github.com/open-mmlab/mmdeploy/blob/master/configs/mmdet/_base_/base_tensorrt-fp16_dynamic-320x320-1344x1344.py) and then increasing batch dimension.

Also probably unrelated, but you may want to increase the `max_workspace_size`.

**Comment by manhtd98** [comment]
```
python3 ./tools/deploy.py ./configs/mmdet/instance-seg/instance-seg_tensorrt_dynamic-320x320-1344x1344.py ../mmdetection/configs/insurance/cascade_mask_rcnn_restnext101.py ../mmdetection/pretrained/cascade_mask_rcnn_restnext101.pth ./demo/demo.jpg --device cuda:0
```
I can convert yolo but for cascade only batch 1 success. There are error:  Error[10]: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[3450 + (Unnamed Layer* 3695) [Shuffle]...Reshape_1887 + Reshape_1889 + Unsqueeze_1890 + Reshape_1905]}.)
[06/07/2022-20:30:15] [E] Error[2]: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )

**Comment by leemengwei** [comment]
@manhtd98 Hi
Have you solved it ?  I had same issue for maskrcnn.  Batch = 1 ok, not for others!

**Comment by manhtd98** [comment]
@leemengwei you need to increase `workspace` size in the trtexec
It insreace size of model and more batch

**Comment by austinmw** [comment]
I used Amazon SageMaker docker container to run Triton: https://github.com/aws/amazon-sagemaker-examples/tree/main/sagemaker-triton

**Comment by manhtd98** [comment]
@austinmw could you provide same code. I tried many time and stuck in there
```
request_body, header_length = httpclient.InferenceServerClient.generate_request_body(
            inputs, outputs=outputs)

    headers = {
        'Content-Type':
            'application/vnd.sagemaker-triton.binary+json;json-header-size={}'
            .format(header_length)
    }
    import requests
    r = requests.post("http://192.168.81.111:8080", data=request_body, headers=headers)
    r.raise_for_status()
    results = dict((el, []) for el in keys)
    user_data = r.body
```

**Comment by hh123445** [comment]
> 我使用 Amazon SageMaker docker 容器来运行 Triton：https://github.com/aws/amazon-sagemaker-examples/tree/main/sagemaker-triton

Hello, I'm trying to convert the model on mmdetection into an. engine file through mmdeploy and deploy it to a triton. But when I make an inference request, the output of the model is all 0 and - 1. I need your help! For detailed description of the problem, please refer to the following:
[https://github.com/triton-inference-server/server/issues/5382#issue-1590658373](url)

Thank you very much!
