### ISSUE TITLE
[Feature]: Export static ONNX models with different batch size

### ISSUE THREAD

**Issue by SingleZombie** [open-mmlab/mmdeploy#469]
**Motivation**

In our current static onnx config, we use `input_shape` to denote the resolution of input image:
```
onnx_config = dict(input_shape=(300, 300))
```

However, sometimes we want to export a model with different batch size other than 1. For example, we want the input shape to be [2, 3, 300, 300] or [3, 3, 300, 300]

I think we can add a new parameter in onnx_config to denote the batch size. For implementation, in `torch2onnx_impl`, we can repeat the input tensor to a multi-batch tensor. What's your thoughts?

**Comment by grimoire** [comment]
Actually, I don't like this `input_shape` since our model might not accept `image inputs`. Or if we do have to add such an argument, the shape should include every dimension, including `batch`.

**Comment by SingleZombie** [comment]
> Actually, I don't like this `input_shape` since our model might not accept `image inputs`. Or if we do have to add such an argument, the shape should include every dimension, including `batch`.

Agree. I think input shape should be the full shape same as the shape in tensorrt config.
