### ISSUE TITLE
C++ inference encounters this error：failed to create detector, code: 6

### ISSUE THREAD

**Issue by 1wang11lijian1** [open-mmlab/mmdeploy#481]
[2022-05-17 11:21:22.741] [mmdeploy] [error] [device_impl.cpp:147] 0, -1
[2022-05-17 11:21:22.742] [mmdeploy] [error] [detector.cpp:58] exception caught: invalid argument (1) @ :0
failed to create detector, code: 6

I can't create a detector when using the C++ inference interface, need your help

**Comment by lvhan028** [comment]
Can you share your build command and execution command? It looks like device module is not loaded successfully.

**Comment by lzhangzz** [comment]
> [2022-05-17 11:21:22.741] [mmdeploy] [error] [device_impl.cpp:147] 0, -1

The log indicates device support is not loaded.

**Comment by 1wang11lijian1** [comment]
> Can you share your build command and execution command? It looks like device module is not loaded successfully.

#include <fstream>
#include <opencv2/imgcodecs/imgcodecs.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <string>
#include "c/detector.h"

using namespace std;

int main() {

    const char* model_path  = "D:\\WIN\\work_dir_yolox_3";
    const char* image_path  = ""D:\\WIN\\work_dir_yolox_3\\20210722_162700_235.jpg";
    const char* device_name = "cuda";   //"cpu", "cuda"

    cv::Mat img = cv::imread(image_path);
    if (!img.data) {
        fprintf(stderr, "failed to load image: %s\n", image_path);
        return 1;
    }

    mm_handle_t detector{};
    int status{};
    status = mmdeploy_detector_create_by_path(model_path, device_name, 0, &detector);
    if (status != MM_SUCCESS) {
        fprintf(stderr, "failed to create detector, code: %d\n", (int)status);
        return 1;
    }

    mm_mat_t mat{ img.data, img.rows, img.cols, 3, MM_BGR, MM_INT8 };

    mm_detect_t* bboxes{};
    int* res_count{};
    status = mmdeploy_detector_apply(detector, &mat, 1, &bboxes, &res_count);
    if (status != MM_SUCCESS) {
        fprintf(stderr, "failed to apply detector, code: %d\n", (int)status);
        return 1;
    }

    fprintf(stdout, "bbox_count=%d\n", *res_count);

    for (int i = 0; i < *res_count; ++i) {
        const auto& box = bboxes[i].bbox;
        const auto& mask = bboxes[i].mask;

        fprintf(stdout, "box %d, left=%.2f, top=%.2f, right=%.2f, bottom=%.2f, label=%d, score=%.4f\n",
                i, box.left, box.top, box.right, box.bottom, bboxes[i].label_id, bboxes[i].score);

        // skip detections with invalid bbox size (bbox height or width < 1)
        if ((box.right - box.left) < 1 || (box.bottom - box.top) < 1) {
            continue;
        }

        // skip detections less than specified score threshold
        if (bboxes[i].score < 0.1) {
            continue;
        }

        // generate mask overlay if model exports masks
        if (mask != nullptr) {
            fprintf(stdout, "mask %d, height=%d, width=%d\n", i, mask->height, mask->width);

            cv::Mat imgMask(mask->height, mask->width, CV_8UC1, &mask->data[0]);
            auto x0 = std::max(std::floor(box.left) - 1, 0.f);
            auto y0 = std::max(std::floor(box.top) - 1, 0.f);
            cv::Rect roi((int)x0, (int)y0, mask->width, mask->height);

            // split the RGB channels, overlay mask to a specific color channel
            cv::Mat ch[3];
            split(img, ch);
            int col = 0;  // int col = i % 3;
            cv::bitwise_or(imgMask, ch[col](roi), ch[col](roi));
            merge(ch, 3, img);
        }

        cv::rectangle(img, cv::Point{ (int)box.left, (int)box.top },
                      cv::Point{ (int)box.right, (int)box.bottom }, cv::Scalar{ 0, 255, 0 });
    }

    cv::imwrite("output_detection.png", img);

    mmdeploy_detector_release_result(bboxes, res_count, 1);

    mmdeploy_detector_destroy(detector);

    return 0;
}

This is my execution command，I am going to reconfigure the dependencies of C++ reasoning before this problem occurs. [https://github.com/open-mmlab/mmdeploy/issues/280](url). This problem is exactly the same as I encountered

**Comment by lvhan028** [comment]
All your questions in #280 have been resolved, right?
What's your cmake file? How did you build your program?

**Comment by lvhan028** [comment]
```shell
cd $env:MMDEPLOY_DIR
mkdir build
cd build
cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 `
  -DMMDEPLOY_BUILD_SDK=ON `
  -DMMDEPLOY_TARGET_DEVICES="cuda" `
  -DMMDEPLOY_TARGET_BACKENDS="trt" `
  -DMMDEPLOY_CODEBASES="all" `
  -Dpplcv_DIR="$env:PPLCV_DIR/pplcv-build/install/lib/cmake/ppl" `
  -DTENSORRT_DIR="$env:TENSORRT_DIR" `
  -DCUDNN_DIR="$env:CUDNN_DIR"

cmake --build . --config Release -- /m
cmake --install . --config Release
```
This is used to build MMDeploy SDK. 

What's the command for building your own program?

**Comment by 1wang11lijian1** [comment]
> ```shell
> cd $env:MMDEPLOY_DIR
> mkdir build
> cd build
> cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 `
>   -DMMDEPLOY_BUILD_SDK=ON `
>   -DMMDEPLOY_TARGET_DEVICES="cuda" `
>   -DMMDEPLOY_TARGET_BACKENDS="trt" `
>   -DMMDEPLOY_CODEBASES="all" `
>   -Dpplcv_DIR="$env:PPLCV_DIR/pplcv-build/install/lib/cmake/ppl" `
>   -DTENSORRT_DIR="$env:TENSORRT_DIR" `
>   -DCUDNN_DIR="$env:CUDNN_DIR"
> 
> cmake --build . --config Release -- /m
> cmake --install . --config Release
> ```
> 
> This is used to build MMDeploy SDK.
> 
> What's the command for building your own program?

Sorry, I don't know how to compile my own project's instructions, can you teach me?

**Comment by 1wang11lijian1** [comment]
Hello, the problem I am encountering now is that I can use the dll of the C++ inference engine normally on my local computer, because I have been configured and compiled on this computer, but it cannot be used on other computers. I want to know what I should do How to do it smoothly on other computers

**Comment by lvhan028** [comment]
> Hello, the problem I am encountering now is that I can use the dll of the C++ inference engine normally on my local computer, because I have been configured and compiled on this computer, but it cannot be used on other computers. I want to know what I should do How to do it smoothly on other computers

What the error log says when you porting to the other environment?

**Comment by lvhan028** [comment]
Please refer to #685
