### ISSUE TITLE
[Feature] wrap libtorch as net module in MMDeploy SDK

### ISSUE THREAD

**Issue by lvhan028** [open-mmlab/mmdeploy#487]
**Describe the feature**
As described in the title, this feature requests developing NetModule by wrapping libtorch in MMDeploy SDK.
Therefore, we can do torchscript model  inference via SDK API

**Motivation**
#345

**Related resources**

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by PeterH0323** [comment]
Hi @lvhan028 , I want to pick this one 😄

**Comment by lvhan028** [comment]
Great. Thank you so much ^^

**Comment by PeterH0323** [comment]
Hi @lvhan028 
Sorry, I am temporarily unable to complete my contribution due to my working stuff. Please assign it to others.
I'm very sorry. 😭 

I will continue to make contributions to MMDeploy when my work is relatively idle. 😄
