### ISSUE TITLE
[Enhancement] Correct docstring format

### ISSUE THREAD

**Issue by lvhan028** [open-mmlab/mmdeploy#488]
**Describe the feature**
As shown in the following picture, there are unpleasant blanks in the strings. 
We need to remove them.

**Motivation**

![image](https://user-images.githubusercontent.com/4560679/168780256-bef8f43f-e6ec-4ebb-8218-0d30f055ce94.png)

**Comment by triple-Mu** [comment]
I claim this assignment.

**Comment by lvhan028** [comment]
> I claim this assignment.

Thanks a lot:)
