### ISSUE TITLE
how to deploy model trained by other repo

### ISSUE THREAD

**Issue by will-wiki** [open-mmlab/mmdeploy#490]
Hello, I would like to know how to deploy the Faster RCNN model trained by other repo to Tensorrt using this script, and my model does not have FPN module，Thank you very much for your help！

**Comment by will-wiki** [comment]
anyone can help me

**Comment by will-wiki** [comment]
I noticed that tools/model_convert contains the code for converting the model, but I found no relevant instructions and no corresponding explanation in the code file, so I would like to know which is appropriate for converting the faster rcnn model without FPN module

**Comment by grimoire** [comment]
It is a little bit complex.
First, you need to add some `rewriter`. If these is a function that block the onnx export, a rewriter can replace it with a supported one. For example:

```python
# a rewriter function
from mmdeploy.core import FUNCTION_REWRITER
@FUNCTION_REWRITER.register_rewriter(func_name='the.function.you.want.to.rewrite')
def func(ctx, *args, **kwargs):
     ....

# use the rewrite and export the onnx
with RewriterContext(
       cfg={}, backend='tensorrt', opset=11), torch.no_grad():
    torch.onnx.export(....)
```

Once you success, you can use `torch.backend.tensorrt.create_trt_engine` to create a TensorRT model.

And MMDetection should have support to model without a neck. It would be a good choice.

**Comment by will-wiki** [comment]
In fact, I think the easiest way is to use the Faster RCNN model in the MMDetection repository that does not contain the FPN module to load the model I am currently using, and then use the MMDeploy script to transfer tensorrt. But it is not clear which script under tool/model_convert is appropriate for conversion

**Comment by will-wiki** [comment]
@grimoire Thank you for your reply. Maybe I don't know how to start just by reading this explanation. Is there a more detailed tutorial or example that I can try to follow step by step

**Comment by grimoire** [comment]
If you are using model trained in MMDetection, just follow:

https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/get_started.md#model-conversion
