### ISSUE TITLE
Deployment of Mask-RCNN model on TensorRT 8.2.1.8 and Jetson AGX Xavier: Are plugins needed for running inference?

### ISSUE THREAD

**Issue by habjoel** [open-mmlab/mmdeploy#491]
Hi there, 

I have successfully exported a Mask-RCNN (mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py) to TensorRT using MMDeploy. I would now like to use the TensorRT API for running inference. 

TensorRT provides a script called `trtexec` to test models instantly.  
However if I run `trtexec --loadEngine=end2end.engine`, the following error occurs:

```
[05/17/2022-12:19:37] [E] Error[1]: [pluginV2Runner.cpp::load::290] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[05/17/2022-12:19:37] [E] Error[4]: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
[05/17/2022-12:19:37] [E] Failed to create engine from model.
[05/17/2022-12:19:37] [E] Engine set up failed
```
To me it seems that TensorRT is trying to find the Plugins from the engine model but cannot manage to do so. I know that custom plugins from MMDeploy are used when exporting the model but do I need them also when running the converted model on TensorRT? If yes, how do I provide the Plugins to it?

Many thanks for your help!

**Comment by tehkillerbee** [comment]
I have never tested with `trtexec` directly but I used the MMDeploy SDK example code to test the models and perform inference.
As an alternative, I have also looked at the output images generated by `deploy.py` to check the generated engine.

Out of curiosity, is there a reason you prefer to use `trtexec` to test it?

**Comment by lzhangzz** [comment]
For Mask R-CNN, RoIAlign and NMS are implemented as plugins. Add `--plugins` when using `trtexec`

**Comment by habjoel** [comment]
@tehkillerbee I don't necessarily want to use trtexec itself... that's just a first step to test the model on TensorRT. But I would really like to the TensorRT Python API by any chance. Just for the ease of implementation and maybe not having to install all the libraries used to by the MMDeploy conversion scripts and SDK each time I want to deploy the model on a Jetson. 

The general goal is to use the model inside a ROS (Robotic Operating System) node having a live image stream from a camera as input. I just guessed that it's easier for me to do using TensorRT's API. The SDK from MMDeploy is not that well documented.

**Comment by habjoel** [comment]
Hi @lzhangzz, thanks for the input. I have tried `trtexec --loadEngine=end2end.engine --plugins` but it doesn't change anything. Also, checking in the TensorRT Documentation (https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#trtexec-serialized-timing-cache), the flag --plugins is not described...

**Comment by tehkillerbee** [comment]
@habjoel I understand your concern about the installing libs and I hope this step will be easier in the future. I know work is being done by the excellent MMLabs team.

IMO, the MMDeploy SDK c++ examples are relatively straight forward and allows for easy integration with OpenCV or similar, but they do require some prerequisites to be installed first, as you've mentioned.

**Comment by habjoel** [comment]
Thank you @lzhangzz, it worked :)
Now I only need to find out how to provide the plugins in a script using TensorRT API...

**Comment by lzhangzz** [comment]
Have a look at https://github.com/open-mmlab/mmdeploy/blob/69111a6b956fd147d1590f0b808e545cebf45eeb/mmdeploy/backend/tensorrt/init_plugins.py#L21-L37

**Comment by Luwill6** [comment]
I want to know how to use libmmdeploy_tensorrt_ops.so in tensorrt(cpp)
