### ISSUE TITLE
THC/THC.h: No such file or directory

### ISSUE THREAD

**Issue by percer013** [open-mmlab/mmdeploy#492]
when compile mmcv，have THC/THC.h: No such file or directory err
pytorch version 1.11.0
pytorch remove THC/THC.h 
https://github.com/CoinCheung/pytorch-loss/pull/37
how do i fix this in mmcv

**Comment by lvhan028** [comment]
Hi, @zhouzaida
Can you help handling this issue?

**Comment by chenxyyy** [comment]
you can Comment out `#include <THC/THC.h>`
