### ISSUE TITLE
AssertionError: model config lack topk

### ISSUE THREAD

**Issue by royiluo** [open-mmlab/mmdeploy#494]
I am trying to deploy models swin-transformer to openvino, I have install mmcv, mmcls and mmdeploy in the docker container. Here is my model deployment script.

```
#!/bin/bash

MMDEPLOY_DIR=/root/workspace/mmdeploy
MMCLS_DIR=/root/workspace/mmclassification
CHECKPOINT_DIR=/root/workspace/models
INPUT_IMG=${MMCLS_DIR}/demo/demo.JPEG
WORK_DIR=/root/workspace/models/output


python ${MMDEPLOY_DIR}/tools/deploy.py \
    ${MMDEPLOY_DIR}/configs/mmcls/classification_openvino_dynamic-224x224.py \
    ${MMCLS_DIR}/configs/swin_transformer/swin_base_224_b16x64_300e_imagenet.py \
    ${CHECKPOINT_DIR}/swin_base_224_b16x64_300e_imagenet_20210616_190742-93230b0d.pth \
    ${INPUT_IMG} \
    --work-dir ${WORK_DIR} \
    --device cpu \
    --dump-info
```

When I run the script, I got an error message below:

2022-05-18 04:42:23.782] [mmdeploy] [info] Register 'DirectoryModel'
/opt/conda/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "/root/workspace/mmdeploy/tools/deploy.py", line 313, in <module>
    main()
  File "/root/workspace/mmdeploy/tools/deploy.py", line 102, in main
    dump_info(deploy_cfg, model_cfg, args.work_dir, pth=checkpoint_path)
  File "/root/workspace/mmdeploy/mmdeploy/utils/export_info.py", line 364, in dump_info
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir=work_dir)
  File "/root/workspace/mmdeploy/mmdeploy/utils/export_info.py", line 305, in get_pipeline
    postprocess = get_postprocess(deploy_cfg, model_cfg)
  File "/root/workspace/mmdeploy/mmdeploy/utils/export_info.py", line 249, in get_postprocess
    params = task_processor.get_postprocess()
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmcls/deploy/classification.py", line 280, in get_postprocess
    assert 'topk' in postprocess, 'model config lack topk'
AssertionError: model config lack topk

I tried to set the topk in the config file:

```
model = dict(
    head=dict(
        topk=(1, 5),
    ))
```

But it does not work. How can I solve the issue? 
Thank you~

**Comment by AllentDan** [comment]
Hi, @royiluo. This is raised by `--dump-info`. You may remove it when converting the model to openvino.

**Comment by royiluo** [comment]
Thanks, I have deployed the model.
