### ISSUE TITLE
Segformer B0 fails to convert despite being supported

### ISSUE THREAD

**Issue by LemurPwned** [open-mmlab/mmdeploy#502]
**Describe the bug**

When converting `segformer_mit-b0_512x512_160k_ade20k` to TRT with `mmdeploy` I'm getting `[TensorRT] ERROR: Gather_107: index to gather must be non-negative` error.

The `segformer` is indicated as convertible on the documentation page with supported `mmseg` models.

**Reproduction**
I used the `mmdeploy` script for TRT conversion using, as indicated by the documentation, the `static` deploy config 
```
DEPLOY_CFG_PATH="mmdeploy/configs/mmseg/segmentation_tensorrt_static-512x512.py"
MODEL_CFG_PATH="mmsegmentation/configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py"
MODEL_CHECKPOINT_PATH="${ROOT}/segformer_mit-b0_512x512_160k_ade20k_20210726_101530-8ffa8fda.pth"
```

**Environment**

I'm running the conversion inside the `mmdeploy` gpu Docker container (as recommended by the documentation)

**Error traceback**

If applicable, paste the error trackback here.

![image](https://user-images.githubusercontent.com/8441184/169483005-3fd446db-37e5-4080-9a90-544b2451c120.png)

**Comment by RunningLeon** [comment]
@LemurPwned Hi, please try with TensorRT==8.x. Tested Ok on TensorRT==8.2.1.6.

**Comment by RunningLeon** [comment]
Feel free to reopen if still have the same issue.
