### ISSUE TITLE
AssertionError: The size and size_divisor must be None when pad2square is True

### ISSUE THREAD

**Issue by sanjaypavo** [open-mmlab/mmdeploy#507]
**Describe the bug**

When converting yolox models into onnx, if the input shape for the conversion was given, facing the pad2square issue
 
**Reproduction**

1. What command or script did you run?

```none
python3 ./tools/deploy.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Specifically added the input shape for onnx conversion in deploy config.

**Error traceback**

If applicable, paste the error trackback here.

```none
AssertionError: MultiScaleFlipAug: Pad: The size and size_divisor must be None when pad2square is True

```

**Comment by irexyc** [comment]
@sanjaypavo Which config do you use when you converted the model? You may paste the *full command* not just ```python3 ./tools/deploy.py```

**Comment by sanjaypavo** [comment]
> @sanjaypavo Which config do you use when you converted the model? You may paste the _full command_ not just `python3 ./tools/deploy.py`

The configs are 
[configs](https://github.com/open-mmlab/mmdeploy/tree/master/configs)/[mmdet](https://github.com/open-mmlab/mmdeploy/tree/master/configs/mmdet)/[detection](https://github.com/open-mmlab/mmdeploy/tree/master/configs/mmdet/detection)/detection_onnxruntime_dynamic.py
and 
[mmdetection](https://github.com/open-mmlab/mmdetection)/[configs](https://github.com/open-mmlab/mmdetection/tree/master/configs)/[yolox](https://github.com/open-mmlab/mmdetection/tree/master/configs/yolox)/yolox_s_8x8_300e_coco.py

python3  ./tools/deploy.py \
    configs/mmdet/detection/detection_onnxruntime_dynamic.py  \
   mmdetection/configs/yolox/yolox_s_8x8_300e_coco.py \
    mmdetection/checkpoints/yolox/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth \
    mmdetection/demo/demo.jpg \
    --work-dir work_dir \

**Comment by irexyc** [comment]
Can't reproduce the problem. Moreover, the ```AssertionError``` is in this [line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L615-L616). I checked the [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/yolox/yolox_s_8x8_300e_coco.py#L70-L86), the there is only pad2square parameter, not size_divisor.

Do you have modified the config? Or you may paste your mmdeploy and mmdetection version info

**Comment by sanjaypavo** [comment]
> Can't reproduce the problem. Moreover, the `AssertionError` is in this [line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L615-L616). I checked the [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/yolox/yolox_s_8x8_300e_coco.py#L70-L86), the there is only pad2square parameter, not size_divisor.
> 
> Do you have modified the config? Or you may paste your mmdeploy and mmdetection version info

This was the slightly modified deploy configs I used(input size was added).


onnx_config = {'type': 'onnx', 'export_params': True, 'keep_initializers_as_inputs': False, 'opset_version': 11, 'save_file': 'end2end.onnx', 'input_names': ['input'], 'output_names': ['dets', 'labels'], 'input_shape': [640, 640], 'dynamic_axes': {'input': {0: 'batch', 2: 'height', 3: 'width'}, 'dets': {0: 'batch', 1: 'num_dets'}, 'labels': {0: 'batch', 1: 'num_dets'}}}
codebase_config = {'type': 'mmdet', 'task': 'ObjectDetection', 'model_type': 'end2end', 'post_processing': {'score_threshold': 0.05, 'confidence_threshold': 0.005, 'iou_threshold': 0.5, 'max_output_boxes_per_class': 200, 'pre_top_k': 5000, 'keep_top_k': 100, 'background_label_id': -1}}
backend_config = {'type': 'onnxruntime'}

**Comment by irexyc** [comment]
If you want a static input shape like [640, 640], you should remove the ```dynamic_axes```.

**Comment by sanjaypavo** [comment]
That solved the error. Thank you for your response
