### ISSUE TITLE
[Enhancement] Load OpenVINO model from stream.

### ISSUE THREAD

**Issue by grimoire** [open-mmlab/mmdeploy#51]
Hi, @SemyonBevzuk 

We are working on integrating OpenVINO into our SDK. It seems that we can not load CNNNetwork from a stream. And export ExecutableNetwork is not implemented. So we have to create a temp folder and load the model from it (which violates our design).

https://github.com/open-mmlab/mmdeploy/blob/03ae26c91cd088806f9ab22eae4a05650404e062/csrc/net/openvino/openvino_net.cpp#L88

Is there any way to load the model from a stream? Or does OpenVINO have any plan to add the interface?

**Comment by SemyonBevzuk** [comment]
Unfortunately, this is currently not possible.
This proposal was passed to the MO developers. Maybe in the future this will be improved.
