### ISSUE TITLE
能否先分类模型检测，再目标模型检测，Can classification detection model detection be followed by target detection model detection

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdeploy#520]
能否先分类模型检测，再目标模型检测

代码应该要怎么写才合理

Can classification detection model detection be followed by target detection model detection

How should the code be written

**Comment by tpoisonooo** [comment]
## 先放结论

工业上 99% 的做法是：先检测、再分类。

## 为什么不应该先分类？

常识告诉我们，同样精力，相对于做两件事、肯定只做一件事结果更好。

检测器要完成两个任务：给bbox、给类别；分类模型只需要判类别。

如果先分类，做事的先后顺序显得很“诡异”：
* 输入的图片里，有多个不同种类的目标怎么办，分类结果没法给，给个 list 么？
* 检测器的给类别的能力是浪费的，因为已经分类过了

如果先检测：
* 检测器先给候选目标，扣出小图
* 再把小图给分类器，第二次的判断更准，可以做一些过滤修正

**Comment by tpoisonooo** [comment]
## 什么时候可以先分类？

先判断大的场景，不同细分场景用不同的检测器。这种可以，属于那 1% 的情况。
