### ISSUE TITLE
mmdeploy教程感觉繁琐,python部署是否能简单一点,Mmdeploy tutorial feels cumbersome,Can Python deployment be simpler

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdeploy#524]
mmdeploy教程感觉繁琐
Mmdeploy tutorial feels cumbersome

python部署是否能简单一点
Can Python deployment be simpler

`pip install mmdeploy`

```
from mmdeploy.apis import inference_model

model_cfg = ""
deploy_cfg = ""
backend_files = ""
img = ""
device = ""

result = inference_model(model_cfg, deploy_cfg, backend_files, img=img, device=device)
```

这种方式可以用不
This method can be used without

示例代码 应该要怎么写
How should the sample code be written

能否给一个实际可用的源码 demo
Can you give a demo of the actual available source code

**Comment by monkeycc** [comment]
`https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/prediction.md`

能否学习这个

一个框架 全部模型

直接选择模型的目录就行了

从代码 到 预测结果
简单明了

再回头看看我们的教程
```
from mmdeploy.apis import inference_model
result = inference_model(model_cfg, deploy_cfg, backend_files, img=img, device=device)
```
函数参数  怎么调用  不知道
model_cfg, deploy_cfg, backend_files
教程一个字 都不多写一个

其他MM系列  训练出来的模型  
用代码方式  怎么用  不知道
怎么搞出预测结果的  不知道

我python代码部署
还要让我编译这个 编译那个
python就不能直接用？

问题是按照教程 我没办法部署成功  
训练出来的模型  怎么在mmdeploy中 用代码API直接调用

而不是让我编译来编译去 最后还要接口的形式来调用 
然后靠自己摸索 踩坑 摸索 踩坑

**Comment by lvhan028** [comment]
Thanks for your great suggestion. We are working on it.

**Comment by tpoisonooo** [comment]
嗯，俺也觉得易用性有要修改的地方，所以现在还在改。感谢佬的批评。

Well, I also think that the ease of use needs to be improved, so it is still changing. Thanks for the criticism.

**Comment by tpoisonooo** [comment]
简化 SDK cmake option 为 1 个选项即可。 https://github.com/open-mmlab/mmdeploy/pull/832

**Comment by tpoisonooo** [comment]
https://github.com/open-mmlab/mmdeploy/pull/919

**Comment by tpoisonooo** [comment]
* 已提供 预编译包、自动化脚本；
* 改了编译选项、重构了所有文档结构。

这个 issue 就先关掉了，有啥别的想法 reopen 吧。
