### ISSUE TITLE
error pulling image configuration: download failed after attempts=6: dial tcp: lookup ngc.download.nvidia.cn: Temporary failure in name resolution

### ISSUE THREAD

**Issue by Mactarvish** [open-mmlab/mmdeploy#525]
构建docker时：
`sudo docker build docker/GPU/ -t mmdeploy:inside --build-arg  USE_SRC_INSIDE=true`

报错：
`error pulling image configuration: download failed after attempts=6: dial tcp: lookup ngc.download.nvidia.cn: Temporary failure in name resolution`

**Comment by lvhan028** [comment]
I googled it. Hope this [article](https://blog.csdn.net/qq_30841655/article/details/121768388) helps.

**Comment by Mactarvish** [comment]
谢谢，可以用
