### ISSUE TITLE
When exporting to TensorRT, number of detections is capped at 200

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#53]
Hello,

Thanks for this nice toolkit - so far it is working as expected, a part from a few minor issues. 

After deploying my mmdetection model using the TensorRT backend, I noticed that the number of detections (bbox_count) is capped at 200, even though  max_per_img in my model config has been set to 1000.

It looks like the number of detections is capped by mmdeploy; `base_static.py` config is used as a base for the tensorrt deploy_cfg.
https://github.com/open-mmlab/mmdeploy/blob/03ae26c91cd088806f9ab22eae4a05650404e062/configs/mmdet/_base_/base_static.py#L14 and this config sets the max number of output boxes.

Increasing the variable `max_output_boxes_per_class` solves the problem. But naturally, there are other parameters in the model cfg that differ from the ones set in the deploy_cfg. Shouldn't the `max_output_boxes_per_class` and other relevant variables be set from the model config automatically?

What is the correct approach? According to the [documentation](https://mmdeploy.readthedocs.io/en/latest/tutorials/how_to_convert_model.html#how-to-find-the-corresponding-deployment-config-of-a-pytorch-model), I can use the generic deploy configs included by mmdeploy without modification (eg. `configs/mmdet/instance-seg/instance-seg_tensorrt-fp16_dynamic-320x320-1344x1344.py`, as I have been using up to this point). Should I make my own deploy_cfg instead?

**Comment by lvhan028** [comment]
Hi, @RunningLeon Could you please handle this issue?

**Comment by RunningLeon** [comment]
@tehkillerbee Hi, you could create your custom deploy_cfg file by changing `keep_top_k=1000`. And `max_output_boxes_per_class` is controlling max number of detection results for each class.
A simple way is to inherit and overwrite by creating a new deploy config file: 
```
# in mmdeploy/configs/mmdet/detection/new_config.py 
_base_ = ['../_base_/base_tensorrt_dynamic-320x320-1344x1344.py']
# got everything from base config

# overwriting parameters you want to change
codebase_config = dict(
    post_processing=dict(
        max_output_boxes_per_class=200,
        keep_top_k=1000 # update to 1000
    ))
```

**Comment by tehkillerbee** [comment]
@RunningLeon Ok, that is a good solution then - similar to how the mmdet configs can inherit from eachother and how values can be overwritten.

FYI, I am working on a model, where only a single class is detected, but with a high number of detections per image (eg. 1000) so this was why I set the `max_output_boxes_per_class` higher. Previously, I did not change `keep_top_k`, but I still got more than 100 results.

**Comment by RunningLeon** [comment]
> @RunningLeon Ok, that is a good solution then - similar to how the mmdet configs can inherit from eachother and how values can be overwritten.
> 
> FYI, I am working on a model, where only a single class is detected, but with a high number of detections per image (eg. 1000) so this was why I set the `max_output_boxes_per_class` higher. Previously, I did not change `keep_top_k`, but I still got more than 100 results.
@tehkillerbee Yes, you're right.
That's because parameters are set based on original model config at first. If nothing found in original model config, then it would be set based on deploy config.
You could take a look at here

https://github.com/open-mmlab/mmdeploy/blob/9fd15e3843700bf93be6a303ed3a80f02ea2f1e0/mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py#L168

**Comment by tehkillerbee** [comment]
Closing this issue, as it is not a MMdeploy bug
