### ISSUE TITLE
Result divergence of deployed ConvNeXt model

### ISSUE THREAD

**Issue by haofanwang** [open-mmlab/mmdeploy#546]
I used the latest MMDeploy tool to convert ConvNeXt into tensorRT backend. It converted successfully. However, when I visualized the results, I found the output from tensorRT backend was totally wrong.

I did checked the export process. I found that the output from intermediate ONNX model was correct. So I guess this issue is from the tensorRT model.

Below is the command and configs I have used. 
```
python tools/deploy.py \
configs/mmseg/segmentation_tensorrt-fp16_static-512x512.py \
./mmsegmentation/configs/convnext/upernet_convnext_tiny_fp16_512x512_160k_ade20k.py \
./mmsegmentation/ckpts/upernet_convnext_tiny_fp16_512x512_160k_ade20k_20220227_124553-cad485de.pth \ 
./test.jpg \
--work-dir work-dirs 
--device cuda:0
```

[segmentation_tensorrt-fp16_static-512x512.py](https://github.com/open-mmlab/mmdeploy/blob/master/configs/mmseg/segmentation_tensorrt-fp16_static-512x512.py)

[upernet_convnext_tiny_fp16_512x512_160k_ade20k.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/convnext/upernet_convnext_tiny_fp16_512x512_160k_ade20k.py)

[upernet_convnext_tiny_fp16_512x512_160k_ade20k_20220227_124553-cad485de.pth](https://download.openmmlab.com/mmsegmentation/v0.5/convnext/upernet_convnext_tiny_fp16_512x512_160k_ade20k/upernet_convnext_tiny_fp16_512x512_160k_ade20k_20220227_124553-cad485de.pth)

**Comment by RunningLeon** [comment]
@haofanwang Are you testing onnx with FP32 in onnxruntime? Maybe you could try with tensorrt FP32 as well. BTW, we'll check the problems of  exporting PyTorch FP16 model to TensorRT FP16/INT8 later.

**Comment by haofanwang** [comment]
Thanks for reply. I have tried tensorrt FP32 config, but it doesn't work. By the way, for convnext model, it only provides fp16 config, would it matter?

When exporting tensorrt backend, I get some infos as below for reference.

```

[06/02/2022-13:48:49] [TRT] [I] MatMul_556: broadcasting input1 to make tensors conform, dims(input0)=[1,16,16,768][NONE] dims(input1)=[1,1,768,3072][NONE].
[06/02/2022-13:48:49] [TRT] [I] MatMul_566: broadcasting input1 to make tensors conform, dims(input0)=[1,16,16,3072][NONE] dims(input1)=[1,1,3072,768][NONE].
[06/02/2022-13:48:49] [TRT] [I] MatMul_584: broadcasting input1 to make tensors conform, dims(input0)=[1,16,16,768][NONE] dims(input1)=[1,1,768,3072][NONE].
[06/02/2022-13:48:49] [TRT] [I] MatMul_594: broadcasting input1 to make tensors conform, dims(input0)=[1,16,16,3072][NONE] dims(input1)=[1,1,3072,768][NONE].
```

**Comment by RunningLeon** [comment]
> FP32 works. Please let me know if there any update in FP16, thx.

Hi,
Yes, there is a noticeable difference between FP16 PyTorch model and the converted FP16 TensorRT model. Not sure which layer has problems such as numerical overflow. Maybe you could ask suggestions from [nvidia repo](https://github.com/NVIDIA/TensorRT) as well.

**Comment by huliang2016** [comment]
@haofanwang have you solved your problem?

**Comment by sipie800** [comment]
Same here. convnext in a detection model is prone to trt fp16. For convnext v2, the problem is even worse due to GRN. With that, trt fp16 can't detection anything!
