### ISSUE TITLE
convert queryinst 

### ISSUE THREAD

**Issue by MaxLin86** [open-mmlab/mmdeploy#548]
I have convert queryinst model from .pth to .engine.
only query_roi_head.py was rewrite by myself, and add it into mmdeploy/codebase/mmdet/models/roi_heads.

my queryinst structure:
backbone: regnet
neck: fpn
rpn_head: embeddingRPNHead
roi_head: QueryROIHead(already rewrite)

My question is:  regnet+fpn+embeddingRPNHead should be add by myself ?

**Comment by MaxLin86** [comment]
because the conf from bboxes were almost 0

**Comment by RunningLeon** [comment]
@MaxLin86 Hi, could provide us which standard model config and ckpt from mmdet you are using? If you're supporting standard model from mmseg, you could give us a PR and let's see if other rewriting should be added.

**Comment by RunningLeon** [comment]
feel free to reopen if you still have the issue.
