### ISSUE TITLE
RuntimeError and ImportError

### ISSUE THREAD

**Issue by ke-dev** [open-mmlab/mmdeploy#550]
hello, develop, When I try to use mmdeploy on docker I got an error like below
![ed75600ee1400101f6dae4c6c4b1b9e](https://user-images.githubusercontent.com/59656387/171592163-fa8d5431-b79f-449d-a460-3934af5885e3.png)
I downloaded mmsegmentation,and then when I try to run`python setup.py develop` 
The first error disappeared, the second error appeared
![5b2789daf7d100c2225dd001088c21c](https://user-images.githubusercontent.com/59656387/171592501-81bc9dbb-feb4-481c-9b86-39b40d6ddb2b.png)
Is the pytorch version too high?
I would be very grateful if you could offer some advice.

**Comment by AllentDan** [comment]
Seems you are trying new models with a roll operator involved. A higher version of PyTorch is recommended. You may try PyTorch 1.10+.
