### ISSUE TITLE
Exported Mask-RCNN model shows worse accuracy with larger image sizes

### ISSUE THREAD

**Issue by habjoel** [open-mmlab/mmdeploy#552]
Hi there, 

I have successfully exported a Mask-RCNN model to ONNX and TensorRT for inference. It works well. However I am realizing that the accuracy of the predictions on the images decays a lot with larger image sizes such as 3MP (1544x2064). Also too small images such as 480p (480x640) give a bit of a worse accuracy. I have exported the model for each image size I tested with a static export config analogous to configs/mmdet/instance-seg/instance-seg_tensorrt-fp16_static-800x1344.py. In my tests, I have used the exact same images and resized them to different sizes. The results are evident.

I have recognized that the model performs best when the image dimensions are within a range of [800, 1344]. This is also written on [this page from ONNX on Mask-RCNN](https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/mask-rcnn):

*"This model can take images of different sizes as input. However, to achieve best performance, it is recommended to resize the image such that both height and width are within the range of [800, 1333], and then pad the image with zeros such that both height and width are divisible by 32."*

Also, the already available configs from MMDeploy export the models to a input size of max. 1344. 
I have even seen that the `opt_shape` inside instance-seg_tensorrt_dynamic-320x320-1344x1344.py is set to `opt_shape=[1, 3, 800, 1344]`. I am thinking that this cannot be a coincidence. ONNX states that models of size [800, 1344] work best and your configs target exactly that size.

Could someone explain to me the reason for this? I get that smaller images might lead to worse results because there are less pixels available for object detection. But why does the accuracy drop with larger images? I would really like to do inference with higher resolutions such as 5MP so this information is quite critical for my further proceedings.

Thanks a lot for your help!

**Comment by RunningLeon** [comment]
Hi, thank for your question.
1. Shape of [800,1344] is based on statistics from COCO dataset. You can change the range based on your spacial cases.
2. `min_shape`, `opt_shape`, `max_shape` are minimum/optimum/maximum dimensions for a dynamic input tensor in TensorRT, you could set them properly base on your case as well.
3. For higher resolution inference, we suggest to crop images to certain size.

**Comment by habjoel** [comment]
Thank you for your answer @RunningLeon ! 
I am aware that I can change the input sizes for TensorRT in the configs using `min_shape`, `opt_shape` and `max_shape`. Until now I have used static exports meaning that I have set all these 3 values to the same dimensions. It works, but I am wondering why the accuracy of the predictions get worse if I go for resolutions higher than the range [800, 1344]. Do you have an explanation for this?

What do you mean by "Shape of [800,1344] is based on statistics from COCO dataset."? Are the images of COCO in that size range and is the pretrained Mask-RCNN model therefore "specialized" on this input shape?

Many thanks!

**Comment by RunningLeon** [comment]
Hi,
1. Performance drop for large resolutions may be related to anchor size and scales. The model is trained on COCO dataset and the anchors may not cover objects  in your HR images.
2. All test image from coco val dataset are preprocessed to shape less then 800x1344, thus we set to this shape.

**Comment by habjoel** [comment]
Alright, thank you @RunningLeon . I am not an expert regarding anchor size and scale...
Are these trained parameters or how can I adjust them?

**Comment by RunningLeon** [comment]
> 
@habjoel 
Hi,
this is more a  training related question, we would like you to put it in the [mmdetection](https://github.com/open-mmlab/mmdetection) repo for the benefit of community.
