### ISSUE TITLE
UNAVAILABLE: Internal: autofill failed for model 'yolox': configuration specified max-batch 128 but TensorRT engine only supports max-batch 1

### ISSUE THREAD

**Issue by manhtd98** [open-mmlab/mmdeploy#556]
**Describe the bug**

The tensorrt converted model only can run with batch_size=1

**Reproduction**

What command or script did you run?

```none
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_tensorrt-fp16_static-800x1344.py \
    mmdetection/configs/yolox/yolox_s_8x8_300e_coco.py \
    volume_share/checkpoint.pth \
    mmdetection/demo/demo.jpg \
    --show \
    --device cuda:0
```

**Comment by lvhan028** [comment]
MMDeploy set batch==1 in every 'tensorrt-*-static' config.  You can find it from `base_tensorrt-fp16_static-800x1344.py`

```python
_base_ = ['./base_static.py', '../../_base_/backends/tensorrt-fp16.py']

onnx_config = dict(input_shape=(1344, 800))

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 800, 1344],
                    opt_shape=[1, 3, 800, 1344],
                    max_shape=[1, 3, 800, 1344])))
    ])

```

If you would like to specify a static batch size like 128, you ought to change the batch dims in above `min_shape`, `opt_shape`, `max_shape`

**Comment by manhtd98** [comment]
@lvhan028 [06/07/2022-14:11:24] [TRT] [E] 4: [network.cpp::operator()::2971] Error Code 4: Internal Error (input: kOPT dimensions in profile 0 are [128,3,800,1344] but input has static dimensions [1,3,800,1344].)
i got this error

**Comment by manhtd98** [comment]
Here is config file:
```
_base_ = ['./base_static.py', '../../_base_/backends/tensorrt-fp16.py']

onnx_config = dict(input_shape=(1344, 800))

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[128, 3, 800, 1344],
                    opt_shape=[128, 3, 800, 1344],
                    max_shape=[128, 3, 800, 1344])))
    ])
```

**Comment by lvhan028** [comment]
> Error Code 4: Internal Error (input: kOPT dimensions in profile 0 are [128,3,800,1344] but input has static dimensions [1,3,800,1344].)

Oops, the shape of input data should be [128, 3, 800, 1344], too.
But unfortunately, `tools/deploy.py` can only process one image.
Let's find a way later on.

**Comment by lzhangzz** [comment]
@manhtd98 try setting `min_shape` to `[1, 3, 800, 1344]`

**Comment by manhtd98** [comment]
the same error when set `min_shape` to [1, 3, 800, 1344]

**Comment by lzhangzz** [comment]
@manhtd98 I'm using the following config for YOLOX-s  in my own project, it accepts input batch size range from 1 to 8 without any problem.

```Python
_base_ = ['../_base_/base_dynamic.py', '../../_base_/backends/tensorrt.py']

backend_config = dict(
    common_config=dict(max_workspace_size=1 << 32),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 640, 640],
                    opt_shape=[8, 3, 640, 640],
                    max_shape=[8, 3, 640, 640])))
    ])
```

**Comment by lvhan028** [comment]
Closing it since no more discussions over a month. Feel free to reopen it if it is still an issue

**Comment by wonjun-chung** [comment]
@lzhangzz 
tools/deploy.py can only process one image.
How do you process multiple images for batch inference?
