### ISSUE TITLE
[Question] MMCodebase does not need to be instantiated

### ISSUE THREAD

**Issue by hhaAndroid** [open-mmlab/mmdeploy#56]
```python
def __build_codebase_class(codebase: Codebase, registry: Registry):
    return registry.module_dict[codebase.value]


CODEBASE = Registry('Codebases', build_func=__build_codebase_class)
```

I found that CODEBASE-related classes do not need to be instantiated, is this expected behavior?  If classes such as MMClassification and MMDetection do not need to be instantiated, it is better to have a clearer description. And the `build_dataloader` method of MMClassification lacks the `@staticmethod` decorator. Maybe it's a bug. 

```python
def build_dataloader(dataset: Dataset,
                         samples_per_gpu: int,
                         workers_per_gpu: int,
                         num_gpus: int = 1,
                         dist: bool = False,
                         shuffle: bool = False,
                         round_up: bool = True,
                         seed: Optional[int] = None,
                         pin_memory: bool = True,
                         persistent_workers: bool = True,
                         **kwargs) -> DataLoader:
```

**Comment by RunningLeon** [comment]
@SingleZombie Hi, could you kindly reply this?

**Comment by SingleZombie** [comment]
1) Yes, we want to get the class of the derived classes of MMCodebase instead of its instance. So the name of the API function is `get_codebase_class`. Maybe we should add more comments here.
2) Yes, the `build_dataloader` in MMClassification lacks a `@staticmethod`. We will fix it.

**Comment by hhaAndroid** [comment]
> 

Ok. Thank you very much for your reply.
