### ISSUE TITLE
calibration data can not be used in "trtexec"

### ISSUE THREAD

**Issue by ChenDirk** [open-mmlab/mmdeploy#581]
Hi
I hope to visualize the tensorrt engine, according to the code "https://github.com/pytorch/pytorch/pull/66431/files", in order to visualize the engine, I need to use the log_file that create during building the engine, but I find there is no function to get the log_file. So, I hope to use the "trtexec" file to create the engine again and get the log_file, but when I use the calibration data which created by mmdeploy, the calibration failed. I don't know how to get the calibration data by python api, and don't know why the calibration data can not be used. Or can you tell me other method to visualize tensorrt engine without log_file.
Thank you so much.

**Comment by grimoire** [comment]
You can add a [custom profiler](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Profiler.html) to the [context](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/ExecutionContext.html) you create from the engine.
