### ISSUE TITLE
c++:visual studio build object detection example encountered with device implement error，but the .exe build by cmake runs correctly.  

### ISSUE THREAD

**Issue by xuebuaa** [open-mmlab/mmdeploy#584]
### console log shows as bellow:
[2022-06-09 23:17:02.004] [mmdeploy] [error] [device_impl.cpp:147] 0, -1
[2022-06-09 23:17:02.006] [mmdeploy] [error] [detector.cpp:58] exception caught: invalid argument (1) @ :0
failed to create detector, code: 6
### what I changed in cpp.
	//auto device_name = argv[1];
	//auto model_path = argv[2];
	//auto image_path = argv[3];
	auto device_name = "cuda";
	auto model_path = "D:\\mmdetection\\runs";
	auto image_path = "D:\\mmdetection\\demo\\demo.jpg";
property sheet has include the .h and .lib file path.

**Comment by lzhangzz** [comment]
> property sheet has include the .h and .lib file path.

Setting .h and .lib path correctly is not enough for loading the modules correctly. There is no direct symbol reference to the modules in SDK, simply linking the modules won't work. This is why we recommand to use `mmdeploy_load_static` and `mmdeploy_load_dynamic` in as the demo.

To force the modules to be linked when using static libs
- Link the .lib files using `/WHOLEARCHIVE` flag, this is what `mmdeploy_load_static` does for you.  See https://docs.microsoft.com/en-us/cpp/build/reference/wholearchive-include-all-library-object-files?view=msvc-160

To load the modules when using dynamic libs (DLLs)
- Load the modules with `LoadLibraryA` before using the SDK, this is whtat `mmdeploy_load_dynamic` does for you. See https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya

**Comment by TTgogogo** [comment]
@xuebuaa Did you solve this problem? I can not load the onnx model correctly. What setting should I use in VS?

**Comment by TTgogogo** [comment]
I add /WHOLEARCHIVE in Configuration Properties > Linker > Command Line, But a lot of errors occur:
LNK2005 _NULL_IMPORT_DESCRIPTOR is already defined in opencv_world34. What should I do to solve this problem?

**Comment by xmyyzy123** [comment]
> To load the modules when using dynamic libs (DLLs)
> 
> * Load the modules with `LoadLibraryA` before using the SDK, this is whtat `mmdeploy_load_dynamic` does for you. See https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya

Hi, @lzhangzz, I followed your suggestions using `LoadLibraryA` to load DLLs, the visual studio project works well. But I put DLLs into the folder same with `.exe`, or add DLLs' path in visual studio's environment path, the visual studio project does not work. Could you tell me why i must use `LoadLibraryA` to load DLLs? Thank you.😄

**Comment by xmyyzy123** [comment]
Hi, I dont add `/WHOLEARCHIVE` when compile the code, just load DLLs.
```
void* mmdeploy_load_library(const char* name)
 {    fprintf(stderr, "loading %s ...\n", name);
    auto handle = LoadLibraryA(name);
    if (!handle) {
        fprintf(stderr, "failed to load library %s\n", name);
        return nullptr;
    }
    return handle;
}

int main(int argc, char* argv[]) 
{
    const char* modules[] = {
        "mmdeploy_execution",
        "mmdeploy_cpu_device",
        "mmdeploy_cuda_device",
        "mmdeploy_graph",
        "mmdeploy_directory_model",
        "mmdeploy_transform",
        "mmdeploy_cpu_transform_impl",
        "mmdeploy_cuda_transform_impl",
        "mmdeploy_transform_module",
        "mmdeploy_trt_net",
        "mmdeploy_net_module",
        "mmdeploy_mmcls",
        "mmdeploy_mmdet",
        "mmdeploy_mmseg",
        "mmdeploy_mmocr",
        "mmdeploy_mmedit",
        "mmdeploy_mmpose",
        "mmdeploy_mmrotate"
    };
    for (const auto name : modules) {
        mmdeploy_load_library(name);
    }
   
   // do something

}
```
