### ISSUE TITLE
A slight typo in [Build for Jetson](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/jetsons.md)

### ISSUE THREAD

**Issue by liuqc11** [open-mmlab/mmdeploy#585]
In the [Build for Jetson](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/jetsons.md)

in **Install MMdeploy** part **Install C/C++ Inference SDK** 2. Build SDK demos
```shell
cd ${MMDEPLOY_DIR}/build/install/example
mkdir -p build && cd build
cmake .. -DMMDeploy_DIR=${MMDEPLOY_DIR}/buildinstall/lib/cmake/MMDeploy
make -j$(nproc)
```
In that  **buildinstall** does not exist. It should be as follows. **build/install**
```shell
cd ${MMDEPLOY_DIR}/build/install/example
mkdir -p build && cd build
cmake .. -DMMDeploy_DIR=${MMDEPLOY_DIR}/build/install/lib/cmake/MMDeploy
make -j$(nproc)
```

**Comment by RunningLeon** [comment]
@liuqc11 Hi, welcome PR  to fix it.
