### ISSUE TITLE
Read the csrc source code to run Buffer error

### ISSUE THREAD

**Issue by zgq91** [open-mmlab/mmdeploy#590]
Hi:
   When I run the following code:

    using namespace deploy;
    int size = 1024*1024*3;
    Device device = Device("cpu");
    Buffer buffer = Buffer(device, size);

 error:
 mmdeploy::StatusDomain::_do_throw_exception(const system_error2::status_code<void> & code) 

    Source code for Device("cpu"):

       Device::Device(const char* platform_name, int device_id)
	{
		platform_id_ = gPlatformRegistry().GetPlatformId(platform_name);
		device_id_ = device_id;
	}

	PlatformRegistry& gPlatformRegistry() {
		static PlatformRegistry instance;
		return instance;
	}

but static PlatformRegistry instance not  Register;  
How do I initialize the Device class?

**Comment by lzhangzz** [comment]
`gPlatformRegistry` is a global function to access the instance of `PlatformRegistry` singleton.

The CPU platform is registered via

https://github.com/open-mmlab/mmdeploy/blob/e84bc30f4a036dd19cb3af854203922a91098e84/csrc/device/cpu/cpu_device.cpp#L398-L405

As you can see there is no direct symbol reference from the API to a specify device implementation, for a device to be found in the registry, device modules like `libmmdeploy_xxx_device` must be whole-archived (for static libs build), force linked or dynamically loaded at runtime.
