### ISSUE TITLE
failed:Fatal error: NMSRotated is not a registered function/op

### ISSUE THREAD

**Issue by Jianchun-Huo** [open-mmlab/mmdeploy#593]
问题：
你好，根据教程，我尝试将MMrotate中的RotatedRetinaNet模型转换为onnx格式，转换后当我尝试加载onnx时出现了以下报错：onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from end2end.onnx failed:Fatal error: NMSRotated is not a registered function/op

（1）onnx转换
`python tools/deploy.py \
configs/mmrotate/rotated-detection_onnxruntime_dynamic.py \
$MMROTATE_DIR/configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_le135.py \
$MMROTATE_DIR/checkpoints/rotated_retinanet_obb_r50_fpn_1x_dota_le135-e4131166.pth \
$MMROTATE_DIR/demo/demo.jpg \
--work-dir work-dirs/mmrotate/rotated_retinanet/ort \
--device cpu`
![image](https://user-images.githubusercontent.com/52435695/173264767-5865ac77-56c1-4383-ab0c-92a7785450b0.png)

（2）尝试加载onnx，报错
![image](https://user-images.githubusercontent.com/52435695/173264882-ef10d231-2e07-459d-8e17-df43ca11f851.png)

此外，我发现build/lib下是存在libmmdeploy_onnxruntime_ops.so文件的，我该如何解决这个问题呢？

**Comment by irexyc** [comment]
Your usage:
```
import onnxruntime as ort
ort.InferenceSession("end2end.onnx")
```
didn't use the libmmdeploy_onnxruntime_ops.so

please refer to this code:
https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/backend/onnxruntime/wrapper.py#L36-L64

**Comment by Jianchun-Huo** [comment]
The problem has been solved. Thank you for your reply！

**Comment by jzlin1997** [comment]
hello, I want to ask how to modify it. 
change onnx: 
`python tools/deploy.py configs/mmrotate/rotated-detection_onnxruntime_dynamic.py ../mmrotate/configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_oc.py ../mmrotate/pre_models/rotated_retinanet_hbb_r50_fpn_1x_dota_oc-e8a7c7df.pth ../mmrotate/demo/demo.jpg --work-dir work_dir --show`
use onnx: 
```
         >>> from mmdeploy.backend.onnxruntime import ORTWrapper
         >>> import torch
         >>> onnx_file = 'model.onnx'
         >>> model = ORTWrapper(onnx_file, 'cpu')
```
but i got 
`failed:Fatal error: NMSRotated is not a registered function/op`

**Comment by Jianchun-Huo** [comment]
@jzlin1997 I had this problem before, and then I solved it according to the following method：
(1) Query the path of mmdeploy_onnxruntime_ops. dll
```
>>> from mmdeploy.backend.onnxruntime import get_ops_path
>>> get_ops_path()
'D:\\project\\mmdeploy\\mmdeploy\\lib\\mmdeploy_onnxruntime_ops.dll'
```
(2) Copy onnxruntime. dll to the path where mmdeploy_onnxruntime_ops. dll is stored
```
copy mmdeploy\\onnxruntime-win-x64-1.8.1\\lib\\onnxruntime.dll   ->   mmdeploy\\mmdeploy\\lib\\
```

**Comment by irexyc** [comment]
The docs miss the installation command, so the costom op lib may not install to the mmdeploy/lib dir if you didn't do ``` make install```

This pr fixed it https://github.com/open-mmlab/mmdeploy/pull/625/files

And on windows, there exists two onnxruntime.dll in system32 and syswow64 which load first than your download version. And there exists some methods to solve it.

**Comment by serser** [comment]
Docs: https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/linux-x86_64.md
