### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Failed to load library, error code: 193

### ISSUE THREAD

**Issue by Jianchun-Huo** [open-mmlab/mmdeploy#597]
你好，在Win10环境下，当我使用以下命令尝试将mmrotate模型转换为onnx格式时，出现报错：onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Failed to load library, error code: 193
```
python tools/deploy.py \
configs/mmrotate/rotated-detection_onnxruntime_dynamic.py \
$MMROTATE_DIR/configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_le135.py \
$MMROTATE_DIR/checkpoints/rotated_retinanet_obb_r50_fpn_1x_dota_le135-e4131166.pth \
$MMROTATE_DIR/demo/demo.jpg \
--work-dir work-dirs/mmrotate/rotated_retinanet/ort \
--device cpu
```
报错信息：
![image](https://user-images.githubusercontent.com/52435695/173483050-e8a77fb0-ed48-44e8-82a3-25854b875506.png)

这是因为无法加载mmdeploy_onnxruntime_ops.dll的原因吗？但是我通过get_ops_path()方法能够查询到mmdeploy_onnxruntime_ops.dll的路径，请问我该如何解决这个问题呢？

**Comment by irexyc** [comment]
There are two onnxruntime.dll in system path:
```
C:\Windows\system32\onnxruntime.dll
C:\Windows\SysWOW64\onnxruntime.dll
```

try to rename them (hide from path):
```
onnxruntime.dll -> onnxruntime.dll--
```

or copy your download onnxruntime lib to your virtualenv python path (the folder where python.exe exists)
or adjust your system PATH to make sure your download onnxruntime lib show up first.


I suggest rename the two onnxruntime.dll（have no idea what is the use of these two dlls, if you encounter some problem after renaming, you can try the other methods)

**Comment by Jianchun-Huo** [comment]
Thank you for your reply, but I did not solve the problem after I tried your method

**Comment by Jianchun-Huo** [comment]
I solved the problem in this way：
(1) Query the path of mmdeploy_onnxruntime_ops. dll
```
>>> from mmdeploy.backend.onnxruntime import get_ops_path
>>> get_ops_path()
'D:\\project\\mmdeploy\\mmdeploy\\lib\\mmdeploy_onnxruntime_ops.dll'
```

(2) Copy onnxruntime. dll to the path where mmdeploy_onnxruntime_ops. dll is stored
```
copy mmdeploy\\onnxruntime-win-x64-1.8.1\\lib\\onnxruntime.dll   ->   mmdeploy\\mmdeploy\\lib\\
```

**Comment by chl916185** [comment]
r3det_r50_fpn_1x_dota_oc.py 
get the following error：

> sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from tmp.onnx failed:Fatal error: MMCVRotatedFeatureAlign is not a registered function/op
@Jianchun-Huo @irexyc

**Comment by irexyc** [comment]
@chl916185 
You have to load the build ops lib for onnx, 

you can refer to https://github.com/open-mmlab/mmdeploy/blob/master/mmdeploy/backend/onnxruntime/wrapper.py#L45-L46

**Comment by zerovirus123** [comment]
@Jianchun-Huo  I tried to copy onnxruntime.dll to the path where mmdeploy_onnxruntime_ops.dll is stored, but that did not resolve my issue. Did you rename the onnxruntime.dll in C:\System32 and C:\SysWOW64 or remove those paths from your environment variables?

**Comment by Jianchun-Huo** [comment]
@zerovirus123 I did not rename onnxRuntime.dll in C:\System32 and C:\SysWOW64 or remove these paths from environment variables.

**Comment by zerovirus123** [comment]
@Jianchun-Huo Where did you get the onnxruntime.dll? From C:\System32 and C:\SysWOW64, or from some other sources? It seems like mmdeploy_onnxruntime_ops.dll requires onnxruntime.dll as a dependency, and onnxruntime.dll requires other dlls as dependencies as well.

![Screenshot from 2022-09-05 09-56-49](https://user-images.githubusercontent.com/9401015/188352104-ef775b3f-2e79-46ee-8bea-0b85d94815bc.png)

**Comment by Jianchun-Huo** [comment]
@zerovirus123 My onnxruntime.dll is from onnxruntime-win-x64-1.8.1.zip，refer:https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/windows.md
![image](https://user-images.githubusercontent.com/52435695/188352799-dafd1555-fc9f-45b8-a10c-74f723ed1167.png)

More questions, it is estimated that you need the help of @irexyc

**Comment by zerovirus123** [comment]
@Jianchun-Huo That fixed the issue. Thanks for your help!
