### ISSUE TITLE
外围注册接口，兼容第三方库 // Can other thirdparty inference backends register to mmdeploy?

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmdeploy#598]
我们也按照openmmlab的格式，做了一个自己lib，想用mmdeploy来导出；
能否提供接口从外围注册lib ？

**Comment by lvhan028** [comment]
In one word, yes, you can.

If you are trying to register a new inference backend to convert onnx model to your target inference engine file, you can refer to https://github.com/open-mmlab/mmdeploy/tree/master/mmdeploy/backend/* for examples. 
Meanwhile, you can also customize the inference backend in MMDeploy SDK, like what we did about tensorrt. Please read https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/net/trt/trt_net.cpp, in which the tensorrt engine is registered by `REGISTER_MODULE(Net, TRTNetCreator);`

In fact, lots of modules in MMDeploy SDK can be customized, such as inference engine, preprocessing, and postprocessing modules, even the deployed model reader. 

For example, we register `TransformModule` by `REGISTER_MODULE(Module, TransformModuleCreator);`  to do image processing, and `ResizeBBox` module by `REGISTER_CODEBASE_COMPONENT(MMDetection, ResizeBBox);` to get bbboxes from the detection model inference tensor.

**Comment by lvhan028** [comment]
Closing it since no more discussions for over a month. Feel free to reopen it if it is still an issue
