### ISSUE TITLE
Build windows sdk failed

### ISSUE THREAD

**Issue by HuangLonghao** [open-mmlab/mmdeploy#602]
当我试图按照官方教程构建windows mmdeploy sdk（cuda11.0，cudnn 8.0，tensorrt7.2）时，遇到了以下问题：
pplcv_static.lib(cvtcolor.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”，
但是我构建pplcv的时候，只能够编译出static_release版本的库，请问我应该如何解决这个问题？
以下是我编译pplcv时cmake相关信息：
cmake .. -G "Visual Studio 16 2019" -T v142 -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DHPCC_USE_CUDA=ON -DHPCC_MSVC_MD=ON
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.28.29336.0
-- The CXX compiler identification is MSVC 19.28.29336.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Populating hpcc
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- Configuring done
-- Generating done
-- Build files have been written to: F:/MyProjects/ppl.cv/deps/hpcc-subbuild
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
版权所有(C) Microsoft Corporation。保留所有权利。

  Performing update step for 'hpcc-populate'
  No patch step for 'hpcc-populate'
  No configure step for 'hpcc-populate'
  No build step for 'hpcc-populate'
  No install step for 'hpcc-populate'
  No test step for 'hpcc-populate'
  Completed 'hpcc-populate'
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
-- Performing Test HAVE_C_FLAG_MP
-- Performing Test HAVE_C_FLAG_MP - Success
-- Performing Test HAVE_C_FLAG_OPENMP
-- Performing Test HAVE_C_FLAG_OPENMP - Success
-- Performing Test HAVE_CXX_FLAG_MP
-- Performing Test HAVE_CXX_FLAG_MP - Success
-- Performing Test HAVE_CXX_FLAG_OPENMP
-- Performing Test HAVE_CXX_FLAG_OPENMP - Success
-- Performing Test HAVE_CXX_FLAG_WD4244
-- Performing Test HAVE_CXX_FLAG_WD4244 - Success
-- Performing Test HAVE_CXX_FLAG_WD4251
-- Performing Test HAVE_CXX_FLAG_WD4251 - Success
-- Performing Test HAVE_CXX_FLAG_WD4267
-- Performing Test HAVE_CXX_FLAG_WD4267 - Success
-- Performing Test HAVE_CXX_FLAG_WD4305
-- Performing Test HAVE_CXX_FLAG_WD4305 - Success
-- Performing Test HAVE_CXX_FLAG_WD4503
-- Performing Test HAVE_CXX_FLAG_WD4503 - Success
-- Performing Test HAVE_CXX_FLAG_WD4819
-- Performing Test HAVE_CXX_FLAG_WD4819 - Success
-- Performing Test HAVE_CXX_FLAG_WD4800
-- Performing Test HAVE_CXX_FLAG_WD4800 - Success
-- Performing Test HAVE_CXX_FLAG_WD4996
-- Performing Test HAVE_CXX_FLAG_WD4996 - Success
-- Performing Test HAVE_CXX_FLAG_WD4828
-- Performing Test HAVE_CXX_FLAG_WD4828 - Success
-- Performing Test HAVE_CXX_FLAG_UTF_8
-- Performing Test HAVE_CXX_FLAG_UTF_8 - Success
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0 (found version "11.0")
-- The CUDA compiler identification is NVIDIA 11.0.194
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Populating pplcommon
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- Configuring done
-- Generating done
-- Build files have been written to: F:/MyProjects/ppl.cv/deps/pplcommon-subbuild
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
版权所有(C) Microsoft Corporation。保留所有权利。

  Performing update step for 'pplcommon-populate'
  No patch step for 'pplcommon-populate'
  No configure step for 'pplcommon-populate'
  No build step for 'pplcommon-populate'
  No install step for 'pplcommon-populate'
  No test step for 'pplcommon-populate'
  Completed 'pplcommon-populate'
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "pplcv_static".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "pplcv_static".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "pplcv_static".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "pplcv_static".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: F:/MyProjects/ppl.cv/build

**Comment by HuangLonghao** [comment]
Hi,thanks for your suggestion.I have done what you recommanded,but it didn’t seem to work.There might be something wrong with my building steps.Could you please give me more suggestions to solve this problem?There are some more details : 
 cmake .. -G "Visual Studio 16 2019" -A x64 -T v142 `
>>   -DMMDEPLOY_BUILD_SDK=ON `
>>   -DMMDEPLOY_TARGET_DEVICES="cuda" `
>>   -DMMDEPLOY_TARGET_BACKENDS="trt" `
>>   -DMMDEPLOY_CODEBASES="all" `
>>   -Dpplcv_DIR="C:\Program Files (x86)\ppl.cv\lib\cmake\ppl" `
>>   -DTENSORRT_DIR="F:\MyProjects\TensorRT-7.2.2.3" `
>>   -DCUDNN_DIR="%cudnn_dir%" -DOpenCV_DIR="F:\MyTools\opencv4.5.1_build_vs2019_gpu"

error info:
 [F:\M
yProjects\mmdeploy\build\csrc\backend_ops\tensorrt\mmdeploy_tensorrt_ops_obj.vcxproj]
  正在生成代码...
  mmdeploy_tensorrt_ops_obj.vcxproj -> F:\MyProjects\mmdeploy\build\csrc\backend_ops\tensorrt\mmdeploy_tensorrt_ops_obj.dir\Release\mmdep
  loy_tensorrt_ops_obj.lib
  Building Custom Rule F:/MyProjects/mmdeploy/csrc/net/trt/CMakeLists.txt
  Building Custom Rule F:/MyProjects/mmdeploy/csrc/backend_ops/tensorrt/CMakeLists.txt
pplcv_static.lib(cvtcolor.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中) [F:\MyPr
ojects\mmdeploy\build\csrc\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
pplcv_static.lib(copymakeborder.cu.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中)
 [F:\MyProjects\mmdeploy\build\csrc\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
pplcv_static.lib(resize.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中) [F:\MyProj
ects\mmdeploy\build\csrc\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
pplcommon_static.lib(log.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中) [F:\MyPro
jects\mmdeploy\build\csrc\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
    正在创建库 F:/MyProjects/mmdeploy/build/lib/Release/mmdeploy_cuda_transform_impl.lib 和对象 F:/MyProjects/mmdeploy/build/lib/Release/mmdeploy
  _cuda_transform_impl.exp
LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library

**Comment by lzhangzz** [comment]
what's your commit id of hpcc inside `ppl.cv/deps/hpcc`?

**Comment by lzhangzz** [comment]
That's wired, our prebuilt binary is using the same commit id and it works.

You may try to remove ppl.cv folder completely and redo the ppl.cv steps. 

You may also open `ppl.cv.sln` generated by cmake to verify the flags are working. Right click on the `pplcv_static` project and open `Properties` page; under `C/C++` -> `Code Generation`, the `RuntimeLibrary` field should be `Multi-threaded DLL (/MD)`.

**Comment by lzhangzz** [comment]
Also, notice that for ppl.cv, there are cached cmake variables stored in both 'deps' and `build` folder, make sure they are both deleted before retrying.

**Comment by HuangLonghao** [comment]
> That's wired, our prebuilt binary is using the same commit id and it works.
> 
> You may try to remove ppl.cv folder completely and redo the ppl.cv steps.
> 
> You may also open `ppl.cv.sln` generated by cmake to verify the flags are working. Right click on the `pplcv_static` project and open `Properties` page; under `C/C++` -> `Code Generation`, the `RuntimeLibrary` field should be `Multi-threaded DLL (/MD)`.

It seems to work，thanks a lot
