### ISSUE TITLE
cannot set batch size 

### ISSUE THREAD

**Issue by wojiaohumaocheng** [open-mmlab/mmdeploy#608]
the file: pose-detection_tensorrt_static-256x192.py

onnx_config = dict(input_shape=[192, 256])
backend_config = dict(
    common_config=dict(max_workspace_size=1 << 30),
    model_inputs=[
        dict(
            input_shapes=dict(
                input=dict(
                    min_shape=[1, 3, 256, 192],
                    opt_shape=[5, 3, 256, 192],
                    max_shape=[10, 3, 256, 192])))
    ])

[TensorRT] ERROR: 4: [network.cpp::operator()::2734] Error Code 4: Internal Error (input: kOPT dimensions in profile 0 are [5,3,256,192] but input has static dimensions [1,3,256,192].)

**Comment by irexyc** [comment]
The file `pose-detection_tensorrt_static-256x192.py` inherits config `../_base_/onnx_config.py` which has static input shape. When you set the input_shape of [192 x 256], the exported onnx model has as fix shape with 1 x 3 x 224 x 224.

To convert a model which supports batch size > 1, you can refer to the config of mmcls which inherits xxx_dynamic.py

For your case, the simple way is change the config:
```
<------------------
onnx_config = dict(input_shape=[192, 256])

--------------------->
onnx_config = dict(
    input_shape=[192, 256],
    dynamic_axes={
        'input': {
            0: 'batch',
            2: 'height',
            3: 'width'
        },
        'output': {
            0: 'batch'
        }
    }, )

```
