### ISSUE TITLE
Encountered when compiling the SDK:  /home/sw/PycharmProjects/mmdeploy/third_party/pybind11    does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by wangshiwei567** [open-mmlab/mmdeploy#611]
Error while compiling SDK (ONNXRuntime and TensorRT as reasoning engine), request help!! 

CMake Error at csrc/mmdeploy/apis/python/CMakeLists.txt:15 (add_subdirectory):
  The source directory

    /home/sw/PycharmProjects/mmdeploy/third_party/pybind11

  does not contain a CMakeLists.txt file.

CMake Error at csrc/mmdeploy/apis/python/CMakeLists.txt:33 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

The command I typed was:

cmake .. \
    -DCMAKE_CXX_COMPILER=g++-9 \
    -DMMDEPLOY_BUILD_SDK=ON \
    -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON \
    -DMMDEPLOY_TARGET_DEVICES="cuda;cpu" \
    -DMMDEPLOY_TARGET_BACKENDS=trt \
    -DMMDEPLOY_CODEBASES=all \
    -Dpplcv_DIR=${PPLCV_DIR}/cuda-build/install/lib/cmake/ppl \
    -DTENSORRT_DIR=${TENSORRT_DIR} \
    -DCUDNN_DIR=${CUDNN_DIR}

**Comment by wangshiwei567** [comment]
This issue has been resolved！

**Comment by 8633136** [comment]
I have the same problem, how did you solve it?

**Comment by 8633136** [comment]
I have the same problem, how did you solve it? @wangshiwei567

**Comment by StevenGerrad** [comment]
I use `git submodule update --init --recursive` to solve it.

**Comment by FunnyWii** [comment]
> I use `git submodule update --init --recursive` to solve it.

Very new bee

**Comment by SparKgod1** [comment]
> > I use `git submodule update --init --recursive` to solve it.
> 
> Very new bee

NB
