### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdeploy_python'

### ISSUE THREAD

**Issue by wangshiwei567** [open-mmlab/mmdeploy#622]
I set the PATHONPATH right as follow command

export PYTHONPATH=/mmdeploy/build/lib/

import mmdeploy_python
import sys
import cv2
detector = mmdeploy_python.Detector('/project/mmlab_template/work_dirs/xxxxx/faster_rcnn/xxxxx', 'cuda', 0)
img = cv2.imread('/project/mmlab_template/data/xxxxxx/training/TRACKA/x/xx.jpg')
result = detector([img])
print(result)

/mmdeploy/build/lib/ files show follow

libmmdeploy_classifier.so           libmmdeploy_directory_model.so  libmmdeploy_model.so            libmmdeploy_tensorrt_ops.so
libmmdeploy_core.so                 libmmdeploy_graph.so            libmmdeploy_net_module.so       libmmdeploy_text_detector.so
libmmdeploy_cpu_device.so           libmmdeploy_mmcls.so            libmmdeploy_onnxruntime_ops.so  libmmdeploy_text_recognizer.so
libmmdeploy_cpu_transform_impl.so   libmmdeploy_mmdet.so            libmmdeploy_opencv_utils.so     libmmdeploy_transform_module.so
libmmdeploy_cuda_device.so          libmmdeploy_mmedit.so           libmmdeploy_ort_net.so          libmmdeploy_transform.so
libmmdeploy_cuda_transform_impl.so  libmmdeploy_mmocr.so            libmmdeploy_restorer.so         libmmdeploy_trt_net.so
libmmdeploy_detector.so             libmmdeploy_mmseg.so            libmmdeploy_segmentor.so      

No mmdeploy_python.cpython-39-x86_64-linux-gnu.so

Requesting Help！！！

**Comment by wangshiwei567** [comment]
@RunningLeon That's the problem, I don't have you built with cmake flags DMMDEPLOY_BUILD_SDK_PYTHON_API=ON.
Thank you.

**Comment by RunningLeon** [comment]
Great. You could join our WeChat group and have instant discussion with developers and users from community. Could refer to  https://github.com/open-mmlab/mmdeploy/blob/master/README_zh-CN.md
