### ISSUE TITLE
ocr识别模型master // Can MASTER from mmocr be deployed? 

### ISSUE THREAD

**Issue by lyc728** [open-mmlab/mmdeploy#623]
你好，关于模型MASTER能进行相应的部署吗？转成onnx后部署trt

**Comment by AllentDan** [comment]
Sorry, it is not in the supported model [list](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/03-benchmark/supported_models.md) now. If it is possible, you may try deploying it yourself and pull a request to us.

**Comment by lvhan028** [comment]
@lyc728 I record MASTER in issue #170 We'll let the community know when mmdeploy supports it.
