### ISSUE TITLE
How to make source code changes on python that still work after conversion to onnx

### ISSUE THREAD

**Issue by 6-9FC81** [open-mmlab/mmdeploy#629]
The `pipeline-LoadImageFromFile` has a parameter `color_type`, which is defined in [mmcv/image/io.py](https://github.com/open-mmlab/mmcv/blob/1f2500102834a01b86bf9ae4db227cd8d724fa6e/mmcv/image/io.py) as:

```python
imread_flags = {
    'color': IMREAD_COLOR,
    'grayscale': IMREAD_GRAYSCALE,
    'unchanged': IMREAD_UNCHANGED,
    'color_ignore_orientation': IMREAD_IGNORE_ORIENTATION | IMREAD_COLOR,
    'grayscale_ignore_orientation':
    IMREAD_IGNORE_ORIENTATION | IMREAD_GRAYSCALE
}
```

The text recognition model (CRNN) I trained requires a single channel image as input, and in [mmocr/.../crnn_pipeline.py](https://github.com/open-mmlab/mmocr/blob/d669ce2e8286937e1ed16ec9feae6401ce5893f5/configs/_base_/recog_pipelines/crnn_pipeline.py), this parameter is configured to `'grayscale'` by default, but my dataset does not easily distinguish between text and background in grayscale images, so I tried to modify this parameter so that the image read in `LoadImageFromFile` during CRNN training is a red single channel.

So I added the following to the function `imfrombytes` in [mmcv/image/io.py](https://github.com/open-mmlab/mmcv/blob/1f2500102834a01b86bf9ae4db227cd8d724fa6e/mmcv/image/io.py):

```python
    elif flag == 'color_R':
        img_np = np.frombuffer(content, np.uint8)
        img = cv2.imdecode(img_np, IMREAD_COLOR)
        _, _, r = cv2.split(img)
        return r
```

Modified:

```python
def imfrombytes(content, flag='color', channel_order='bgr', backend=None):
    if backend is None:
        backend = imread_backend
    if backend not in supported_backends:
        raise ValueError(
            f'backend: {backend} is not supported. Supported '
            "backends are 'cv2', 'turbojpeg', 'pillow', 'tifffile'")
    if backend == 'turbojpeg':
        img = jpeg.decode(content, _jpegflag(flag, channel_order))
        if img.shape[-1] == 1:
            img = img[:, :, 0]
        return img
    elif backend == 'pillow':
        with io.BytesIO(content) as buff:
            img = Image.open(buff)
            img = _pillow2array(img, flag, channel_order)
        return img
    elif backend == 'tifffile':
        with io.BytesIO(content) as buff:
            img = tifffile.imread(buff)
        return img
    elif flag == 'color_R':
        img_np = np.frombuffer(content, np.uint8)
        img = cv2.imdecode(img_np, IMREAD_COLOR)
        _, _, r = cv2.split(img)
        return r
    else:
        img_np = np.frombuffer(content, np.uint8)
        flag = imread_flags[flag] if is_str(flag) else flag
        img = cv2.imdecode(img_np, flag)
        if flag == IMREAD_COLOR and channel_order == 'rgb':
            cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)
        return img
```

Now I can train and reason normally on python without any problem.

But when I convert the trained model to onnx and use the c api for inference I get the wrong result (no error is reported during the process).

I guess I need to change the `pipeline-LoadImageFromFile` in the c code of mmdeploy to be consistent with the changes in python. Where do I need to change?

Any help is appreciated.

**Comment by lzhangzz** [comment]
IMO it's better to register a new transformation in MMOCR's preprocess pipeline instead of modifying MMCV. This part of code is not traced into ONNX.

If you are going to use SDK for inference, a similar transform has to be added in mmdeploy SDK in C++.

If preprocessing speed is not a concern, you can drop the first 2 channels in your model's `forward` method (which is going to be traced).

**Comment by 6-9FC81** [comment]
> IMO 最好在 MMOCR 的预处理管道中注册新的转换，而不是修改 MMCV。这部分代码不会跟踪到 ONNX 中。
> 
> 如果要使用 SDK 进行推理，则必须在 C++ 的 mmdeploy SDK 中添加类似的转换。
> 
> 如果您不关心预处理速度，则只需删除模型方法中的前 2 个通道（如果转换为 RGB，则删除最后 2 个通道）（将被跟踪）。`forward`

What should I do, Can you give me an example?

Also, in the case of grayscale images that do not distinguish well between text and background, which would have higher accuracy, training with three channels of RGB or training with a single channel of red? Or do these two approaches not have an improving effect relative to using the default configuration (grayscale images)?

**Comment by 6-9FC81** [comment]
> IMO it's better to register a new transformation in MMOCR's preprocess pipeline instead of modifying MMCV. This part of code is not traced into ONNX.
> 
> If you are going to use SDK for inference, a similar transform has to be added in mmdeploy SDK in C++.
> 
> If preprocessing speed is not your concern, you can simply drop the first 2 channels (or the last 2 if converted to RGB) in your model's method (which is going to be traced).`forward`


What should I do, Can you give me an example?

Also, in the case of grayscale images that do not distinguish well between text and background, which would have higher accuracy, training with three channels of RGB or training with a single channel of red? Or do these two approaches not have an improving effect relative to using the default configuration (grayscale images)?

**Comment by lzhangzz** [comment]
> What should I do, Can you give me an example?

For example, modify encoder_decoder_recognizer.py, or use mmdeploy to rewrite EncodeDecodeRecognizer.extract_feat like

```Python
def extract_feat(self, img):
    """Directly extract features from the backbone."""
    if self.preprocessor is not None:
        img = self.preprocessor(img)

    x = self.backbone(img[:,0:1]) # drop last 2 channels

    return x
```


> Also, in the case of grayscale images that do not distinguish well between text and background, which would have higher accuracy, training with three channels of RGB or training with a single channel of red? Or do these two approaches not have an improving effect relative to using the default configuration (grayscale images)?

That depends on your dataset. Also, folks from mmocr may be a lot more informative on this question.

**Comment by 6-9FC81** [comment]
> For example, modify encoder_decoder_recognizer.py, or use mmdeploy to rewrite EncodeDecodeRecognizer.extract_feat like
> 
> ```python
> def extract_feat(self, img):
>     """Directly extract features from the backbone."""
>     if self.preprocessor is not None:
>         img = self.preprocessor(img)
> 
>     x = self.backbone(img[:,0:1]) # drop last 2 channels
> 
>     return x
> ```


I don't find the definition of the function extract_feat in encoder_decoder_recognizer.py and other files, do I need to define a new one?
Also, do I need to recompile and install mmdeploy and recompile the SDK to generate dynamic libraries after the changes?
