### ISSUE TITLE
cannot find ResizeOCR implementation on specific platform cuda

### ISSUE THREAD

**Issue by caj-github** [open-mmlab/mmdeploy#630]
text_recognizer SDK
[2022-06-22 11:55:06.473] [mmdeploy] [warning] [transform.h:45] cannot find ResizeOCR implementation on specific platform cuda
[2022-06-22 11:55:06.473] [mmdeploy] [info] [transform.h:49] fallback ResizeOCR implementation to platform cpu
[2022-06-22 11:55:06.473] [mmdeploy] [error] [compose.cpp:23] unable to find creator: ToTensorOCR
[2022-06-22 11:55:06.493] [mmdeploy] [error] [task.cpp:67] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "height": 48,
      "keep_aspect_ratio": true,
      "max_width": 160,
      "min_width": 48,
      "type": "ResizeOCR",
      "width_downsample_ratio": 0.25
    },
    {
      "type": "ToTensorOCR"
    },
    {
      "mean": [
        0.5,
        0.5,
        0.5
      ],
      "std": [
        0.5,
        0.5,
        0.5
      ],
      "type": "NormalizeOCR"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "filename",
        "img_shape",
        "resize_shape",
        "valid_ratio",
        "pad_shape",
        "ori_filename",
        "ori_shape",
        "img_norm_cfg",
        "scale_factor",
        "flip",
        "flip_direction"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-06-22 11:55:06.495] [mmdeploy] [error] [pipeline.cpp:146] could not create Preprocess: Task
[2022-06-22 11:55:06.513] [mmdeploy] [error] [pipeline.cpp:160] error parsing config: unknown (6) @ :0

**Comment by lzhangzz** [comment]
`ResizeOCR` is not the problem it's going to use the cpu fallback implementation, the problem is `ToTensorOCR` and `ToTensorOCR` which we don't support.

What's your MMOCR version and model config?

**Comment by lzhangzz** [comment]
SAR models are not supported by the SDK. Currently CRNN is the only text recognition model supported by SDK.

**Comment by caj-github** [comment]
thanks, Is there any plan to support other recognition model recently?

**Comment by lvhan028** [comment]
We may not consider text recognition model in the next two months. 
Please leave your request to pinned issue #170. We'll put that in our backlog
