### ISSUE TITLE
Any support on cuda11.x version?

### ISSUE THREAD

**Issue by XWHtorrentx** [open-mmlab/mmdeploy#631]
I notice that dockerfile build-up is based on cuda10.2. Is it possible to build with later version of torch, mmcv, onnxruntime and cuda11.x? 

If the answer is yes please be specific about versions of prerequisites, thanks!

**Comment by AllentDan** [comment]
You may pass the `CUDA=11.x` arg in to the dockerfile when building docker image.

**Comment by XWHtorrentx** [comment]
> 

I have tried with CUDA=11.1 (what is supposed to be the most common choice). However conda won't install pytorch LTS with cuda support.
I modified the command with official one : `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch-lts -c nvidia`, and it turns out that I cannot have pytorch installed with cuda support either.
