### ISSUE TITLE
whether custom ops like NMSRotated is supported in onnxruntime gpu version?

### ISSUE THREAD

**Issue by huanghaifeng1234** [open-mmlab/mmdeploy#632]
whether custom ops like NMSRotated is supported in onnxruntime gpu version?

**Comment by irexyc** [comment]
The NMSRotated op can't, while the conv op in the model can run on gpu. 

I test the onnx model before, it has about 5fps on 1024x1024 input.

If you already have a gpu, you may convert to tensorrt which is much faster then onnxruntime. Single stage is already supported and two stage roated detector will be supported after https://github.com/open-mmlab/mmdeploy/pull/530
