### ISSUE TITLE
transformed OrientedRcnn to end2end.onnx, how to deploy it using C++ api?

### ISSUE THREAD

**Issue by huanghaifeng1234** [open-mmlab/mmdeploy#633]
I have transformed OrientedRcnn to end2end.onnx and build custom ops dependency "libmmdeploy_onnxruntime_ops.so", and I have succesfully deployed it using ORTWrapper in python, but how to deploy it using C++ api? Could you please give me an example or instructions for how to do that, thanks!

**Comment by irexyc** [comment]
**1. build mmdeploy with SDK part.**
When you build mmdeploy, you need build SDK part with ```-DMMDEPLOY_BUILD_SDK=ON``` and other options like MMDEPLOY_CODEBASES and  DONNXRUNTIME_DIR. You can refer to [this doc](https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/01-how-to-build/linux-x86_64.md) Or you can download the prebuilt package [here](https://github.com/open-mmlab/mmdeploy/releases)(still need to download onnxruntime).

**2. export sdk info**
When you export the model, you need export the information which sdk need. When convert the model  add --dump-info options. You can refer to [this](https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/02-how-to-run/convert_model.md)

**3. sdk inference(c api)**
There is already an example explain how to use the c api to inference a mmrotate model, you can refer to [this](https://github.com/open-mmlab/mmdeploy/blob/master/demo/csrc/rotated_object_detection.cpp).

**Comment by huanghaifeng1234** [comment]
@irexyc hi, because I want to deploy the sdk inference (c api) in tensor-rt in windows system, but I get stuck in the building process of custom ops of onnxruntime, could you help me check where is the problem?
![image](https://user-images.githubusercontent.com/81546069/175882569-5c15c13e-e31c-4d56-b08d-8890bd401d72.png)
Like in the image, I have set the root directory of onnxruntime, tensorrt and cudnn

**Comment by irexyc** [comment]
If you only want to run the trt model, you don't have to build the ort backend.

The way to use environment varialbe on windows is different from linux.

Please refer to the 'cuda + TensorRT' part of this [doc](https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/01-how-to-build/windows.md#%E7%BC%96%E8%AF%91-sdk)

**Comment by huanghaifeng1234** [comment]
hi, I have followed the instructions to build sdk in windows, but I encounter this problem.

I run with 
```
make .. -G "Visual Studio 16 2019" -A x64 -T v142 `
  -DMMDEPLOY_BUILD_SDK=ON `
  -DMMDEPLOY_TARGET_DEVICES="cuda" `
  -DMMDEPLOY_TARGET_BACKENDS="trt" `
  -DMMDEPLOY_CODEBASES="all" `
  -Dpplcv_DIR="$env:PPLCV_DIR/pplcv-build/install/lib/cmake/ppl" `
  -DTENSORRT_DIR="$env:TENSORRT_DIR" `
  -DCUDNN_DIR="$env:CUDNN_DIR"
```
but I got this
```
-- Found TensorRT libs at D:/install/TensorRT-8.4.0.6.Windows10.x86_64.cuda-11.6.cudnn8.3/TensorRT-8.4.0.6/lib/nvinfer.lib;D:/install/TensorRT-8.4.0.6.Windows10.x86_64.cuda-11.6.cudnn8.3/TensorRT-8.4.0.6/lib/nvinfer_plugin.lib
CMake Error at csrc/mmdeploy/core/CMakeLists.txt:15 (add_subdirectory):
  The source directory

    D:/workspace/repo/mmdeploy/third_party/spdlog

  does not contain a CMakeLists.txt file.


CMake Error at csrc/mmdeploy/core/CMakeLists.txt:16 (set_target_properties):
  set_target_properties Can not find target to add properties to: spdlog


CMake Error at cmake/MMDeploy.cmake:8 (install):
  install TARGETS given target "spdlog" which does not exist.
Call Stack (most recent call first):
  csrc/mmdeploy/core/CMakeLists.txt:18 (mmdeploy_export)
```

**Comment by irexyc** [comment]
Could you check the commit id of the mmdeploy you used? You can use ```git log``` command to check this.

**Comment by huanghaifeng1234** [comment]
```
Author: Chen Xin <xinchen.tju@gmail.com>
Date:   Tue Jun 21 19:19:44 2022 +0800

    [Fix] fix csharp api detector release result (#620)

    * fix csharp api detector release result

    * fix wrong count arg of xxx_release_result in c# api

commit 9c8168f39ac6e1fa7ae359433387a86bb6c6c6f9
Author: Ryan_Huang <44900829+DrRyanHuang@users.noreply.github.com>
Date:   Mon Jun 20 14:46:56 2022 +0800

    make -install -> make install (#621)

    change `make -install` to `make install`

    https://github.com/open-mmlab/mmdeploy/issues/618

commit ac0b52f12ac897867b9bf3dae74b4192493b3d5f
Author: Li Zhang <lzhang329@gmail.com>
Date:   Fri Jun 17 14:06:35 2022 +0800

    add dim param for `Tensor::Squeeze` (#603)

commit a822ba7330e184bf78aa3fd5832089b700f04b6b
Author: Li Zhang <lzhang329@gmail.com>
Date:   Fri Jun 17 13:56:45 2022 +0800

    add `MMDEPLOY_TASKS` & simplify demo cmake (#606)

    * add `MMDEPLOY_TASKS` & simply cmake

    * remove debug log

commit 296412fd08ff9fa62cb0ccbb721de16e2048555e
Author: RunningLeon <mnsheng@yeah.net>
Date:   Fri Jun 17 09:19:10 2022 +0800

    [Docs] Replace markdownlint with mdformat and configure myst-parser (#610)

    * replace mdlint with mdformat

    * set myst_heading_anchor for doc

    * update precommit yml

    * format md files

commit 3e594b28f60ab4f5b921ed60746ab2ca47c8b024
Author: RunningLeon <mnsheng@yeah.net>
Date:   Thu Jun 16 18:45:04 2022 +0800

    Fix index.rst and add check ci (#607)

    * move doc link check to lint ci and add index.rst file check

    * fix filename
```

**Comment by irexyc** [comment]
You may update the mmdeploy since the two-stage rotated detector is supported after 0cac515

https://github.com/open-mmlab/mmdeploy/commits/master

**Comment by huanghaifeng1234** [comment]
hi i have successfully converted the model into tensorrt and test the model result ( cuda 11.6 , windows 11). but when  i use another windows 10 machine with cuda 11.0 (tensorrt: 8.2.0.6, cudnn: 8.2.0.53), i can't succesfully converted the same pth checkpoint

the code i run
```
python ./tools/deploy.py `
    ${env:MMDEPLOY_DIR}/configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024.py `
    ${env:MMROTATE_DIR}/configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_ms_rr_le90.py `
    ${env:MMDEPLOY_DIR}/model/retina
    ${env:MMDEPLOY_DIR}/images/test.bmp `net_torch/latest.pth `
    --test-img ${env:MMDEPLOY_DIR}/images/test.bmp `
    --work-dir ${env:MMDEPLOY_DIR}/model/retinanet_trt `
    --device cuda `
    --log-level INFO `
    --show `
    --dump-info
```

i get the following
```
load checkpoint from local path: D:\all_install\mmdeploy/model/retinanet_torch/latest.pth
2022-06-29 00:06:29,354 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future.
2022-06-29 00:06:29,355 - mmdeploy - INFO - Export PyTorch model to ONNX: D:\all_install\mmdeploy/model/retinanet_trt\end2end.onnx.
d:\all_install\mmdeploy\mmdeploy\core\optimizers\function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
d:\all_install\mmdeploy\mmdeploy\pytorch\functions\topk.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k > size:
d:\all_install\mmrotate\mmrotate\core\bbox\coder\delta_xywha_rbbox_coder.py:101: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
d:\all_install\mmdeploy\mmdeploy\codebase\mmrotate\core\post_processing\bbox_nms.py:163: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(scores.shape[-1]),
d:\all_install\mmdeploy\mmdeploy\mmcv\ops\nms_rotated.py:120: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out_boxes = min(num_boxes, after_topk)
self._mp_dict:  {}
Traceback (most recent call last):
  File "./tools/deploy.py", line 366, in <module>
    main()
  File "./tools/deploy.py", line 129, in main
    torch2ir(ir_type)(
  File "d:\all_install\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 355, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "d:\all_install\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 323, in call_function
    return self.get_result_sync(call_id)
  File "d:\all_install\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 304, in get_result_sync
    ret = self.get_caller(func_name).pop_mp_output(call_id)
  File "d:\all_install\mmdeploy\mmdeploy\apis\core\pipeline_manager.py", line 80, in pop_mp_output
    assert call_id in self._mp_dict, \
AssertionError: `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed.
```

**Comment by huanghaifeng1234** [comment]
by the way, i test both oriented-rcnn and rotated-retinanet, pytorch and tensorrt model of rotated-retinanet can get the same image result, but pytorch and tensorrt model of oriented-rcnn can't get the same result.
below is the output of pytorch model of oriented-rcnn
![oriented_rcnn_pytorch](https://user-images.githubusercontent.com/81546069/176356007-e05db332-f66f-4adc-99ab-e26fbae0e053.png)
below is the output of tensorrt model of oriented-rcnn
![oriented_rcnn_tensorrt](https://user-images.githubusercontent.com/81546069/176356049-31094e8c-8db6-4dde-98a4-80581eb3a780.png)

**Comment by grimoire** [comment]
There is a bug in MMDeploy TensorRT Rotated NMS plugin,

https://github.com/open-mmlab/mmdeploy/blob/0f0f676d1f43c0476a36fe172dce8ac4e0394b8e/csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/allClassRotatedNMS.cu#L296-L299

The return value should be 1.0f instead of 0.0f. I am not sure if this bug is related to your error or not.

**Comment by irexyc** [comment]
@[huanghaifeng1234](https://github.com/huanghaifeng1234) 
Thanks for your feedback.

Recently, many people have reported the problem to export onnx model on windows. We are working on it, you can temporarily convert the model on linux.

**Comment by huanghaifeng1234** [comment]
hi, thanks for your help. I wonder whether I can convert the model in linux and deploy it in windows？



---Original---
From: "Chen ***@***.***&gt;
Date: Wed, Jun 29, 2022 14:11 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [open-mmlab/mmdeploy] transformed OrientedRcnn to end2end.onnx,how to deploy it using C++ api? (Issue #633)




 
@huanghaifeng1234
 Thanks for your feedback.
 
Recently, many people have reported the problem to export onnx model on windows. We are working on it, you can temporarily convert the model on linux.

**Comment by irexyc** [comment]
Yes, it can convert on linux and deploy on windows. 

You should make sure the version of tensorrt, cudnn installed on linux is same on windows. To convert the model, if the pytorch you installed is with cudatoolkit 11.1, you should install cuda 11.1. The serialized model has some version check logic, if you deploy the model with different lib, you will encounter the version mismatch problem.

**Comment by huanghaifeng1234** [comment]
thanks, I will give it a try

**Comment by huanghaifeng1234** [comment]
hi, I have builded binary executable rotated_object_detection.exe which can get the correct result,  and I want to transplant to another project on the same windows machine, but I get error when initialized the tensorrt model
the error is
```
failed to create rotated detector, code: 6
```
![image](https://user-images.githubusercontent.com/81546069/176414868-3e502179-413a-4cf0-a103-c43987282d5a.png)
I wonder if I want to deploy the model successfully, what are the library files I need when I build the binary and what are the shared files I need when I start the binary.

The library files I have used
![image](https://user-images.githubusercontent.com/81546069/176415770-0ffa09b2-e1a0-483e-aef3-2020b84c2c7a.png)

The shared files I have used
![image](https://user-images.githubusercontent.com/81546069/176415962-a088b06b-b09f-4460-8f6e-70357dcc6547.png)

**Comment by irexyc** [comment]
You need to:
1. copy the mmdeploy install dlls
2. copy cudnn and tensorrt with same version
3. copy opencv if you build with shared lib
4. Install cuda with same version. 
5. May need to install Microsoft Visual C++ 2015-2019 Redistributable.

Use cmd to run the exe and if you miss some dll, it will tell you. Don't use powershell as it won't tell what dll is missing.

**Comment by huanghaifeng1234** [comment]
thanks, problem resolved

**Comment by Audrey528** [comment]
Based on mmdetection2.25.1, I added a head and changed the test part, I wanna generate .engine by .pth, but I met some questions. The below code generate node “nonzero” in .onnx and tensorrt8.4  doesn't support "nonzero". I know tensorrt8.5 in docker can support, but I wanna build env in vitural env. Can you guys give me some revisions? Thanks very much.
```
def multiclass_nms1(multi_bboxes,
                   multi_scores,
                   det_labels,
                   num_classes,
                   nms_cfg,
                   max_num=-1,
                   score_factors=None):
    """NMS for multi-class bboxes.

    Args:
        multi_bboxes (Tensor): shape (n, #class*4) or (n, 4)
        multi_scores (Tensor): shape (n, #class)
        score_thr (float): bbox threshold, bboxes with scores lower than it
            will not be considered.
        nms_thr (float): NMS IoU threshold
        max_num (int): if there are more than max_num bboxes after NMS,
            only top max_num will be kept.
        score_factors (Tensor): The factors multiplied to scores before
            applying NMS

    Returns:
        tuple: (bboxes, labels), tensors of shape (k, 5) and (k, 1). Labels
            are 0-based.
    """
    bboxes, labels = [], []
    nms_cfg_ = nms_cfg.copy()
    nms_type = nms_cfg_.pop('type', 'nms')
    nms_op = getattr(nms_wrapper, nms_type)
    for i in range(0, num_classes):
        cls_inds = det_labels == i
        if not cls_inds.any():
            continue
        # get bboxes and scores of this class
        if multi_bboxes.shape[1] == 4:
            _bboxes = multi_bboxes[cls_inds, :]
        else:
            _bboxes = multi_bboxes[cls_inds, i * 4:(i + 1) * 4]
        _scores = multi_scores[cls_inds]
        if score_factors is not None:
            _scores *= score_factors[cls_inds]
        cls_dets = torch.cat([_bboxes, _scores[:, None]], dim=1)

        cls_dets, _ = nms_op(cls_dets, **nms_cfg_)
        cls_labels = multi_bboxes.new_full(
            (cls_dets.shape[0], ), i, dtype=torch.long)
        bboxes.append(cls_dets)
        labels.append(cls_labels)
    if bboxes:
        bboxes = torch.cat(bboxes)
        labels = torch.cat(labels)
        if bboxes.shape[0] > max_num:
            _, inds = bboxes[:, -1].sort(descending=True)
            inds = inds[:max_num]
            bboxes = bboxes[inds]
            labels = labels[inds]
    else:
        bboxes = multi_bboxes.new_zeros((0, 5))
        labels = multi_bboxes.new_zeros((0, ), dtype=torch.long)

    return bboxes, labels
```
The wrong onnx part :
<img width="303" alt="1666341926789" src="https://user-images.githubusercontent.com/68552295/197153788-5b225876-fef4-4cc9-9d0c-a536f6ad53a9.png">
