### ISSUE TITLE
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.

### ISSUE THREAD

**Issue by XWHtorrentx** [open-mmlab/mmdeploy#642]
Encounter bugs while load tensorrt engine transformed from YOLOX and YOLOV3. My MMDeploy is built in a container with cuda11.1 torch1.8.2 mmcv1.4.0

```
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin TRTBatchedNMS version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
```

**Comment by XWHtorrentx** [comment]
#65

**Comment by irexyc** [comment]
It seems like you didn't use mmdeploy sdk api to load the model.

May similiar to https://github.com/open-mmlab/mmdeploy/issues/327?

**Comment by lvhan028** [comment]
Hi, @XWHtorrentx could you provide your way to load tensorrt engine?

**Comment by lvhan028** [comment]
Hi, @XWHtorrentx could you kindly let us know the way to reproduce this issue? like the Dockerfile you use, the env info (executing `mmdeploy/tools/check_env.py`), and so on.

**Comment by XWHtorrentx** [comment]
I solved this issue by building

**Comment by XWHtorrentx** [comment]
I solved this issue by rebuilding with latest Nvidia official Pytorch container, Cuda 11.6. I guess it has something to do with compatibility.
