### ISSUE TITLE
mmdeploy 2022 开源夏令营

### ISSUE THREAD

**Issue by tpoisonooo** [open-mmlab/mmdeploy#651]
夏令营只有学生能参加
夏令营只有学生能参加
夏令营只有学生能参加

## 背景
* GLCC 的经费确实有限
* 参加报名的学生确实都很优秀

OpenMMLab mmdeploy repo 单独准备了一些题目和礼品，作为开源 GLCC 夏令营的补充。
有兴趣的同学，请直接评论自己的 **微信** 账号，附加题目名字作为认领方式。

### 一、改善 arm Linux 部署体验
【难度】⭐⭐⭐
【描述】jetson nano 有 arm CPU， mmdeploy 团队提供 arm 设备登录方式。希望参考已有的 android ncnn 部署文档，写一份 arm linux 部署说明；遇到不合理的点直接修改，一起 PR 到 mmdeploy
【学习技能】
    1. cmake
    2. Linux 常用命令

### 二、优化 ncnn int8 模型部署
【最多可 7 位同学同时选择】
【难度】⭐⭐⭐⭐
【描述】mmdeploy 目前支持 ncnn int8。但很多模型都没有验证。希望验证 mmdet/mmpose/mmtrack 等 repo 模型量化后的精度。如遇精度问题需给出掉点原因。测试结果 PR 到 mmdeploy；掉点结果需要写出知乎小软文。
【学习技能】
    1. ncnn int8 原理
    2. 对应 repo 下模型论文

### 三、优化 trt int8 量化模型部署
【难度】⭐⭐⭐⭐
【描述】mmdeploy 目前未接入 trt int8 量化。希望参考接入 ncnn int8 方法，新增 trt 量化接口，PR 到  mmdeploy
【学习技能】
    1. nvidia trt 量化原理
    2. ppq 用法

### 四、改进 CI 覆盖
【听起来不难，实际上巨麻烦】
【难度】⭐⭐⭐⭐
【描述】mmdeploy githuh action 目前没有覆盖完整的 end2end 转换。希望 CI 增加 cls/det/track 等 repo 到对应硬件的模型测试
【学习技能】
    1. mm 系列大部分 repo 用法
    2. Github Action 开发和调试

### 五、新增 snpe backend
【需要 qcom 芯片手机才能调试】
【难度】⭐⭐⭐⭐⭐
【描述】参考 docs 中如何接入新的 backend 文档，支持高通推理框架 snpe，完成 fp32 模型推理。PR 到 mmdeploy
【学习技能】
    1. 学习 snpe
    3. 学习 cmake
    4. 学习 gcc-arm 交叉编译

### 六、新增 golang 接口
【难度】⭐⭐⭐⭐⭐
【描述】参考 mmdeploy 已支持的 c api 接口，新增 golang API。
【学习技能】
    1. Golang
    2. mmdeploy SDK

### 七、新增 Rust 接口
【难度】⭐⭐⭐⭐⭐⭐
【描述】参考 mmdeploy 已支持的 c api 接口，新增 Rust API，并发布到 crates.io 上。最终可通过 cargo 直接集成 Rust mmdeploy。可以参考 rust-ncnn/mgelite-rs 等 rust 系列 repo
 【学习技能】
    1. 学习 Rust
    2. mmdeploy SDK
    3. 上传 crates.io，以及如何单独维护一个小型 repo

## 和 [GLCC 夏令营](https://github.com/open-mmlab/mmdeploy/issues/512) 的差异
GLCC 的经费来自 CCFxGitlink，我们需要保证项目可在 DDL 内完成，所以 GLCC 倾向已经具备对应技能的同学。

mmdeploy 的经费来自 OpenMMLab，【学习技能】指 “**现在可能还不会，未来 3 个月即将学会**”。

**Comment by Chunsheng13** [comment]
Chunsheng13/改善 arm Linux 部署体验

**Comment by Qingrenn** [comment]
Qingrenn / diligentyqr + 优化 ncnn int8 模型部署

**Comment by tpoisonooo** [comment]
> Chunsheng13/改善 arm Linux 部署体验

你微信号多少？我错了不该让你们留 github ID。

**Comment by Chunsheng13** [comment]
微信号:
FlyingHigh1988
手机号:17315091809

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tpoisonooo ***@***.***&gt;
发送时间: 2022年6月27日 11:56
收件人: open-mmlab/mmdeploy ***@***.***&gt;
抄送: Zhang Chunsheng ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[open-mmlab/mmdeploy] mmdeploy 2022 开源夏令营 (Issue #651)

**Comment by kaizhong2021** [comment]
微信号：chaikaizhong2021
题目    ：优化 trt int8 量化模型部署

**Comment by wangyifan97** [comment]
微信号：18280382462
题目：优化 ncnn int8 模型部署

**Comment by tpoisonooo** [comment]
> 微信号：18280382462 题目：优化 ncnn int8 模型部署

收到。

**Comment by lx-r** [comment]
Weixin ID: **langerdoer**
Task: **二、优化 ncnn int8 模型部署**

**Comment by tpoisonooo** [comment]
ncnn int8 模型部署还剩最后 1 个名额。

**Comment by tpoisonooo** [comment]
> Weixin ID: **langerdoer** Task: **二、优化 ncnn int8 模型部署**

夏令营只有学生能参加。

**Comment by Uoruichi** [comment]
wx id:Uoruichi
Task:新增 Rust 接口

**Comment by ueanperfect** [comment]
Weixin ID:ueanperfect Task:六、新增 golang 接口

**Comment by liu-mengyang** [comment]
申领任务：新增rust接口
微信号：EthanLmy

**Comment by LiuYi-Up** [comment]
任务申领：二、优化 ncnn int8 模型部署
微信号：ly1150854440

**Comment by Shirley866** [comment]
二、优化 ncnn int8 模型部署
微信号：Sophine3

**Comment by tpoisonooo** [comment]
最后一个 1  ncnn int8 名额，其他题目均已选完。

**Comment by AnnYellow** [comment]
二、优化ncnn int8 模型部署
微信号：18428077318
（我是非全日制研究生，可以吗？）

**Comment by tpoisonooo** [comment]
> 二、优化ncnn int8 模型部署 微信号：18428077318 （我是非全日制研究生，可以吗？）

可以啊。

**Comment by tpoisonooo** [comment]
所有题目人选已经定下来。感谢大家关注和支持！
