### ISSUE TITLE
How Build C# API from source code?

### ISSUE THREAD

**Issue by centerzong** [open-mmlab/mmdeploy#661]
I want run some model with c#, so  I build the C++ sdk,but I do not known how to build the C# nupkg. thanks for your help.

**Comment by irexyc** [comment]
please refer to this [doc](https://github.com/open-mmlab/mmdeploy/tree/master/csrc/mmdeploy/apis/csharp)

If you use master branch other than v0.5.0, you may edit [this line](https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/apis/csharp/MMDeploy/MMDeploy.csproj#L17) to:
```
<MMDeployExternalNativeDlls>$(MSBuildThisFileDirectory)\..\..\..\..\..</MMDeployExternalNativeDlls>
```

**Comment by centerzong** [comment]
this method work very well, thank you very match
