### ISSUE TITLE
torch2onnx failed during make cascade_rcnn pth convertion to onnx

### ISSUE THREAD

**Issue by kelvinwang139** [open-mmlab/mmdeploy#662]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.  yes
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.    yes
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

import argparse
import logging
import os.path as osp

from mmdeploy.apis import torch2onnx
from mmdeploy.utils import get_root_logger

logger = get_root_logger(log_level='INFO')

deploy_cfg_path = 'mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py'
model_cfg_path = '/tmp/cascade_model/cascade_rcnn.py'
checkpoint_path = '/tmp/cascade_model/epoch_16.pth'
img = 'mmdeploy/demo/demo.jpg'
output_path = '/tmp/cascade_model/1.onnx'
work_dir, save_file = osp.split(output_path)
device = 'cuda'

logger.info(f'torch2onnx: \n\tmodel_cfg: {model_cfg_path} '
            f'\n\tdeploy_cfg: {deploy_cfg_path}')
try:
    torch2onnx(
        img,
        work_dir,
        save_file,
        deploy_cfg=deploy_cfg_path,
        model_cfg=model_cfg_path,
        model_checkpoint=checkpoint_path,
        device=device)
    logger.info('torch2onnx success.')
except Exception as e:
    logger.error(e)
    logger.error('torch2onnx failed.')

Error Logs:
/root/fengzf/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-06-28 10:02:24,459 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-06-28 10:02:24,460 - mmdeploy - INFO - Export PyTorch model to ONNX: /tmp/cascade_model/1.onnx.
/root/fengzf/mmdeploy/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/cnn/bricks/generalized_attention.py:179: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h_idxs = torch.linspace(0, h - 1, h).to(device=device, dtype=dtype)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/cnn/bricks/generalized_attention.py:182: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w_idxs = torch.linspace(0, w - 1, w).to(device=device, dtype=dtype)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/cnn/bricks/generalized_attention.py:185: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h_kv_idxs = torch.linspace(0, h_kv - 1, h_kv).to(
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/cnn/bricks/generalized_attention.py:189: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w_kv_idxs = torch.linspace(0, w_kv - 1, w_kv).to(
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/cnn/bricks/generalized_attention.py:204: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  dim_mat = torch.Tensor([wave_length]).to(device=device, dtype=dtype)
/root/fengzf/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/root/fengzf/mmdetection/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/root/fengzf/mmdetection/mmdet/core/anchor/anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
/root/fengzf/mmdeploy/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/root/fengzf/mmdeploy/mmdeploy/pytorch/functions/topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/root/fengzf/mmdeploy/mmdeploy/pytorch/functions/topk.py:33: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ctx.origin_func(input, k, dim=dim, largest=largest, sorted=sorted)
/root/fengzf/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/root/fengzf/mmdeploy/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/root/fengzf/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:92: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/root/fengzf/mmdeploy/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:93: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/root/fengzf/mmdeploy/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/root/fengzf/mmdeploy/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/ops/nms.py:171: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/ops/nms.py:172: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/ops/nms.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
/root/fengzf/mmdeploy/mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert proposals.shape[0] == 1, 'Only support one input image ' \
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/ops/roi_align.py:81: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.size(1) == 5, 'RoI must be (idx, x1, y1, x2, y2)!'
2022-06-28 10:02:28,810 - mmdeploy - ERROR - Exporting the operator linspace to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
2022-06-28 10:02:28,812 - mmdeploy - ERROR - torch2onnx failed.

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.

(mmdeploy) root@dell-Precision-7920-Tower:~/fengzf/mmdeploy# python tools/check_env.py
2022-06-28 12:07:00,730 - mmdeploy - INFO -

2022-06-28 12:07:00,730 - mmdeploy - INFO - **********Environmental information**********
2022-06-28 12:07:00,993 - mmdeploy - INFO - sys.platform: linux
2022-06-28 12:07:00,993 - mmdeploy - INFO - Python: 3.7.0 (default, Oct  9 2018, 10:31:47) [GCC 7.3.0]
2022-06-28 12:07:00,993 - mmdeploy - INFO - CUDA available: True
2022-06-28 12:07:00,993 - mmdeploy - INFO - GPU 0,1: NVIDIA GeForce RTX 3090
2022-06-28 12:07:00,993 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda/bin
2022-06-28 12:07:00,993 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.1, V11.1.74
2022-06-28 12:07:00,993 - mmdeploy - INFO - GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
2022-06-28 12:07:00,993 - mmdeploy - INFO - PyTorch: 1.8.0
2022-06-28 12:07:00,994 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

2022-06-28 12:07:00,994 - mmdeploy - INFO - TorchVision: 0.9.0
2022-06-28 12:07:00,994 - mmdeploy - INFO - OpenCV: 4.6.0
2022-06-28 12:07:00,994 - mmdeploy - INFO - MMCV: 1.5.3
2022-06-28 12:07:00,994 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-06-28 12:07:00,994 - mmdeploy - INFO - MMCV CUDA Compiler: 11.1
2022-06-28 12:07:00,994 - mmdeploy - INFO - MMDeploy: 0.5.0+0cac515
2022-06-28 12:07:00,994 - mmdeploy - INFO -

2022-06-28 12:07:00,994 - mmdeploy - INFO - **********Backend information**********
2022-06-28 12:07:01,419 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-06-28 12:07:01,426 - mmdeploy - INFO - tensorrt: None      ops_is_avaliable : False
2022-06-28 12:07:01,447 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-06-28 12:07:01,448 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-06-28 12:07:01,449 - mmdeploy - INFO - openvino_is_avaliable: False
2022-06-28 12:07:01,449 - mmdeploy - INFO -

2022-06-28 12:07:01,449 - mmdeploy - INFO - **********Codebase information**********
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmdet:      2.24.1
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmseg:      None
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmcls:      None
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmocr:      None
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmedit:     None
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmdet3d:    None
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmpose:     None
2022-06-28 12:07:01,450 - mmdeploy - INFO - mmrotate:   None
(mmdeploy) root@dell-Precision-7920-Tower:~/fengzf/mmdeploy#

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]   Conda
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RunningLeon** [comment]
@kelvinwang139 Hi, cascade_rcnn with [GeneralizedAttention](https://github.com/open-mmlab/mmcv/blob/d71d067da19d71d79e7b4d7ae967891c7bb00c05/mmcv/cnn/bricks/generalized_attention.py#L14) is not supported by far. But you can try with latest PyTorch since exporting the operator `linspace` to ONNX  is added in https://github.com/pytorch/pytorch/pull/60246

**Comment by kelvinwang139** [comment]
> @kelvinwang139 Hi, cascade_rcnn with [GeneralizedAttention](https://github.com/open-mmlab/mmcv/blob/d71d067da19d71d79e7b4d7ae967891c7bb00c05/mmcv/cnn/bricks/generalized_attention.py#L14) is not supported by far. But you can try with latest PyTorch since exporting the operator `linspace` to ONNX is added in [pytorch/pytorch#60246](https://github.com/pytorch/pytorch/pull/60246)

Hi Leon，thanks for your response. We shall try it and respond you. In addition, is any plan to support cascade_rcnn with GeneralizeAttention?

**Comment by RunningLeon** [comment]
Hi, by far, we have no plan. Welcome to PR us.

**Comment by kelvinwang139** [comment]
Ok，when upgrade the latest torch version this issue(linespace) is resolved and I'd like to close it. Thanks Leon nice supports!
