### ISSUE TITLE
support mmrazor prune

### ISSUE THREAD

**Issue by Hiwyl** [open-mmlab/mmdeploy#666]
**Describe the feature**

export  onnx with classification weights by mmrazor prune, but get the weights has same size as  not pruned weights

**Comment by AllentDan** [comment]
Hi, I saw your PR in MMRazor [here](https://github.com/open-mmlab/mmrazor/pull/193). Is it solved?

**Comment by Hiwyl** [comment]
> Hi, I saw your PR in MMRazor [here](https://github.com/open-mmlab/mmrazor/pull/193). Is it solved?

mmrazor split checkpoints solved, but with mmdeploy export onnx‘s model size equal by https://github.com/open-mmlab/mmdeploy/pull/220

**Comment by AllentDan** [comment]
> equal

Hi, thanks for reporting it. We've already located the bug and mmrazor will fix it soon.

**Comment by AllentDan** [comment]
> 

Seems the methods of MMRazor that updates the model through changing the attribute of the nn.Module which is not updated to ONNX when exporting. They will renew a new model which is safer in the upcoming codes.

**Comment by Hiwyl** [comment]
Thank you

**Comment by AllentDan** [comment]
You are welcome.
