### ISSUE TITLE
exporting onnx fails with squeeze op

### ISSUE THREAD

**Issue by fengzf-github** [open-mmlab/mmdeploy#678]
import argparse
import logging
import os.path as osp
from mmdeploy.apis import torch2onnx
from mmdeploy.utils import get_root_logger

logger = get_root_logger(log_level='INFO')

deploy_cfg_path = '/root/fengzf/jupyter_workdir/mmdeploy/mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py'
model_cfg_path = '/tmp/cascade_model/cascade_rcnn.py'
checkpoint_path = '/tmp/cascade_model/epoch_16.pth'
img = '/root/fengzf/jupyter_workdir/mmdeploy/mmdeploy/demo/demo.jpg'
output_path = '/tmp/cascade_model/1.onnx'
work_dir, save_file = osp.split(output_path)
device = 'cuda'

logger.info(f'torch2onnx: \n\tmodel_cfg: {model_cfg_path} '
            f'\n\tdeploy_cfg: {deploy_cfg_path}')
try:
    torch2onnx(
        img,
        work_dir,
        save_file,
        deploy_cfg=deploy_cfg_path,
        model_cfg=model_cfg_path,
        model_checkpoint=checkpoint_path,
        device=device)
    logger.info('torch2onnx success.')
except Exception as e:
    logger.error(e)
    logger.error('torch2onnx failed.')

2022-06-29 17:45:47,586 - mmdeploy - INFO - torch2onnx: 
	model_cfg: /tmp/cascade_model/cascade_rcnn.py 
	deploy_cfg: /root/fengzf/jupyter_workdir/mmdeploy/mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py
load checkpoint from local path: /tmp/cascade_model/epoch_16.pth
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-06-29 17:45:52,330 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-06-29 17:45:52,332 - mmdeploy - INFO - Export PyTorch model to ONNX: /tmp/cascade_model/1.onnx.
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:179: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h_idxs = torch.linspace(0, h - 1, h).to(device=device, dtype=dtype)
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:182: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w_idxs = torch.linspace(0, w - 1, w).to(device=device, dtype=dtype)
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:185: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h_kv_idxs = torch.linspace(0, h_kv - 1, h_kv).to(
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:189: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w_kv_idxs = torch.linspace(0, w_kv - 1, w_kv).to(
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:204: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  dim_mat = torch.Tensor([wave_length]).to(device=device, dtype=dtype)
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/core/anchor/anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/pytorch/functions/topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/pytorch/functions/topk.py:33: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ctx.origin_func(input, k, dim=dim, largest=largest, sorted=sorted)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/deploy/utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:92: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:93: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/root/fengzf/mmcv/mmcv/ops/nms.py:171: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/root/fengzf/mmcv/mmcv/ops/nms.py:172: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/root/fengzf/mmcv/mmcv/ops/nms.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert proposals.shape[0] == 1, 'Only support one input image ' \
/root/fengzf/mmcv/mmcv/ops/roi_align.py:83: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.size(1) == 5, 'RoI must be (idx, x1, y1, x2, y2)!'
2022-06-29 17:48:11,951 - mmdeploy - ERROR - <mmdeploy.core.rewriters.rewriter_utils.ContextCaller object at 0x7f8a75703128> is not a module, class, method, or function. 
(Occurred when translating squeeze).
2022-06-29 17:48:11,953 - mmdeploy - ERROR - torch2onnx failed.2022-06-29 17:45:47,586 - mmdeploy - INFO - torch2onnx: 
	model_cfg: /tmp/cascade_model/cascade_rcnn.py 
	deploy_cfg: /root/fengzf/jupyter_workdir/mmdeploy/mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py
load checkpoint from local path: /tmp/cascade_model/epoch_16.pth
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
2022-06-29 17:45:52,330 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-06-29 17:45:52,332 - mmdeploy - INFO - Export PyTorch model to ONNX: /tmp/cascade_model/1.onnx.
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:179: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h_idxs = torch.linspace(0, h - 1, h).to(device=device, dtype=dtype)
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:182: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w_idxs = torch.linspace(0, w - 1, w).to(device=device, dtype=dtype)
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:185: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  h_kv_idxs = torch.linspace(0, h_kv - 1, h_kv).to(
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:189: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w_kv_idxs = torch.linspace(0, w_kv - 1, w_kv).to(
/root/fengzf/mmcv/mmcv/cnn/bricks/generalized_attention.py:204: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  dim_mat = torch.Tensor([wave_length]).to(device=device, dtype=dtype)
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/core/anchor/anchor_generator.py:333: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/root/fengzf/jupyter_workdir/mmdeploy/mmdetection/mmdet/core/anchor/anchor_generator.py:370: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/pytorch/functions/topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/pytorch/functions/topk.py:33: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ctx.origin_func(input, k, dim=dim, largest=largest, sorted=sorted)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/deploy/utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:92: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py:93: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/mmcv/ops/nms.py:40: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  score_threshold = float(score_threshold)
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/mmcv/ops/nms.py:41: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  iou_threshold = float(iou_threshold)
/root/fengzf/mmcv/mmcv/ops/nms.py:171: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/root/fengzf/mmcv/mmcv/ops/nms.py:172: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/root/fengzf/mmcv/mmcv/ops/nms.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num > 0:
/usr/local/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmdeploy-0.5.0-py3.7.egg/mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py:41: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert proposals.shape[0] == 1, 'Only support one input image ' \
/root/fengzf/mmcv/mmcv/ops/roi_align.py:83: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.size(1) == 5, 'RoI must be (idx, x1, y1, x2, y2)!'
2022-06-29 17:48:11,951 - mmdeploy - ERROR - <mmdeploy.core.rewriters.rewriter_utils.ContextCaller object at 0x7f8a75703128> is not a module, class, method, or function. 
(Occurred when translating squeeze).
2022-06-29 17:48:11,953 - mmdeploy - ERROR - torch2onnx failed.

**Comment by kelvinwang139** [comment]
Some clues：
mmdeploy project:    mmdeploy/pytorch/ops/squeeze.py:
# Copyright (c) OpenMMLab. All rights reserved.
import torch.onnx.symbolic_helper as sym_help

from mmdeploy.core import SYMBOLIC_REWRITER


@SYMBOLIC_REWRITER.register_symbolic('squeeze', is_pytorch=True)
def squeeze__default(ctx, g, self, dim=None):
    """Register default symbolic function for `squeeze`.

    squeeze might be exported with IF node in ONNX, which is not supported in
    lots of backend.
    """
    if dim is None:
        dims = []
        for i, size in enumerate(self.type().sizes()):
            if size == 1:
                dims.append(i)
    else:
        dims = [sym_help._get_const(dim, 'i', 'dim')]

    return g.op('Squeeze', self, axes_i=dims)


The install torch packages:     /site-packages/torch/onnx/symbolic_helper.py

def _squeeze_helper(g, input, axes_i):
    if _is_constant(axes_i[0]):
        if GLOBALS.export_onnx_opset_version >= 13:
            axes = g.op("Constant", value_t=torch.tensor(axes_i, dtype=torch.long))
            return g.op("Squeeze", input, axes)
        return g.op("Squeeze", input, axes_i=axes_i)
    # Tensor type
    if GLOBALS.export_onnx_opset_version < 13:
        raise ValueError(
            f"Opset version must be >= 13 for Squeeze with dynamic axes. {input.node().sourceRange()}"
        )
    axes_t = axes_i[0]
    axes_rank = _get_tensor_rank(axes_t)
    if axes_rank > 1:
        raise ValueError(
            "For Squeeze axses as input, the axes rank must be one in ONNX spec."
        )
    elif axes_rank == 0:
        # The axes is a scalar. Unsqueeze it to a rank 1 tensor.
        axes_t = _unsqueeze_helper(g, axes_t, [0])
        return g.op("Squeeze", input, axes_t)
    return g.op("Squeeze", input, axes_t)

What's the relationship between these two definitions? 

During make the onnx convert the mmdeploy default version of opset_version is 11. If just change the version to 13 to fix this issue?

**Comment by RunningLeon** [comment]
@fengzf-github Because `If` op would be exported in `squeeze` somtimes with torch==1.8.0, thus we add this rewriting. For latest torch, maybe you could try to remove it in `mmdeploy/pytorch/ops/__init__.py`

**Comment by RunningLeon** [comment]
Closed for no response in a long time.
