### ISSUE TITLE
Dockerfile so large

### ISSUE THREAD

**Issue by manhtd98** [open-mmlab/mmdeploy#683]
I use the dockerfile to build the enviroment to deploy mmdeploy application. It took so much memory(18GB).
Could you provide the betterversion lightly weight?

**Comment by AllentDan** [comment]
OK. We will work on it.

**Comment by AllentDan** [comment]
We will let you know if there is any progress.

**Comment by manhtd98** [comment]
Thanks you for quick reply!

**Comment by AllentDan** [comment]
> Thanks you for quick reply!

Hi, @manhtd98. After a period of practicing, I've only cut the size of the docker image down from 14.2GB to 14GB through the multistage building. The base image of TensorRT from Nvidia is 5.63GB. May I ask what is the expected size for you?

**Comment by lvhan028** [comment]
> i found that nvidia and pytorch take 6gb compression memory. My all compression memory only takes 9GB. Can you try to copy nvidia-torch-runtime to Dockerfile, it's so light and maybe can resize images

Hi, @manhtd98 could you provide an example?

**Comment by lvhan028** [comment]
Hi, @manhtd98 thanks so much for your suggestion.

I checked the above link. The base image is `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`.
But our base image is `nvcr.io/nvidia/tensorrt:21.04-py3` with size 5.6+G
```shell
nvcr.io/nvidia/tensorrt   21.04-py3                         7e51c9c7a756   14 months ago   5.63GB
```
And we have to install PyTorch in this image, which costs more than 1G space. 

@AllentDan I think we can use multistage build to remove temporary build files of  `ppl.cv` and `mmdeploy`. 
Also, it seems we don't need `conda install conda-build pyyaml numpy ipython cython typing typing_extensions mkl mkl-include ninja`.

**Comment by lvhan028** [comment]
As I tested, based on `nvcr.io/nvidia/tensorrt:21.04-py3`, the docker image size will increase to `14+G` by just installing `conda` and `PyTorch`. 
I am afraid we can do little to shrink the size.

**Comment by AllentDan** [comment]
> As I tested, based on `nvcr.io/nvidia/tensorrt:21.04-py3`, the docker image size will increase to `14+G` by just installing `conda` and `PyTorch`. I am afraid we can do little to shrink the size.

The same here from my experience.
