### ISSUE TITLE
Net how to input image data

### ISSUE THREAD

**Issue by zgq91** [open-mmlab/mmdeploy#686]
Hi:
    I was confused when I read the source code.  In the  csrc\net\openvino folder,  How does the OpenVINONet member function Forword input image data for reasoning

**Comment by lzhangzz** [comment]
Setting inputs for `InferenceEngine::InferRequest` is done by calling the `SetBlob` static function

https://github.com/open-mmlab/mmdeploy/blob/17a7d60c7d6ee0c0012a55e6a0735a5b268c1bc5/csrc/mmdeploy/net/openvino/openvino_net.cpp#L238-L241

**Comment by zgq91** [comment]
> Using the `Net` interface, something like
> 
> ```c++
> auto input_tensors = net->GetInputTensors().value();
> 
> // now fill the input tensors
> 
> net->Forward();
> 
> auto output_tensors = net->GetOutputTensors().value();
> 
> // extract the result from output tensors
> ```

thanks
