### ISSUE TITLE
Need to deploy MultiViewImage Model BEVFormer based on mmdet3d

### ISSUE THREAD

**Issue by zkdliushuo** [open-mmlab/mmdeploy#688]
**Describe the feature**

Want to deploy BEVFormer from this [repo](https://github.com/zhiqi-li/BEVFormer). However, this work intends to use deformable attention to do 3D object detection on multiview image dataset and MMDeploy doesn't support it in codebase `mmdet3d`. 

NeedS deployment support for BEVFormer.  

**Motivation**

BEVFormer is a camera-based detector using BEV features transformed from multiview images, which achieves SOTA performance on Waymo and nusenes. It is beneficial to have a close insight of its inference performance after being deployed on backend TensorRT.

**Related resources**

BEVFormer repo: https://github.com/zhiqi-li/BEVFormer

**Additional context**

I use the following command to deploy：
```
python ./tools/deploy.py ./configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py /data/workspace/BEVFormer/projects/configs/bevformer/bevformer_base.py /data/workspace/BEVFormer/ckpts/bevformer_r101_dcn_24ep.pth /workspace/mmdetection/demo/demo.jpg --work-dir ./tmp/bevformmer_base_trt --device cuda:2 --dump-info
```
which shows:
```
error:KeyError: 'BEVFormer is not in the models registry'
```

And I believe it is due to using the wrong framework, so I search for deploy config under mmdet3d repo, and there are only configs for VoxelDetection tasks. The Error is like the follows:
```
python ./tools/deploy.py ./configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-nus.py /data/workspace/BEVFormer/projects/configs/bevformer/bevformer_base.py /data/workspace/BEVFormer/ckpts/bevformer_r101_dcn_24ep.pth /workspace/mmdetection/demo/demo.jpg --work-dir ./tmp/bevformmer_base_trt --device cuda:2 --dump-info
error:KeyError: <Task.VOXEL_DETECTION: 'VoxelDetection'>
```

**Comment by zkdliushuo** [comment]
Or s there any other approaches to deploying BEVFormer? I read the codes of BEVFormer and I find there are some modules related to `deformable attention` be implenmented based on `mmcv`. So I think it is not easy to build an TRT engine directly.

**Comment by RunningLeon** [comment]
@zkdliushuo Hi, we do not support bevformer because it is not included in [mmdet3d](https://github.com/open-mmlab/mmdetection3d).

**Comment by DerryHub** [comment]
@zkdliushuo Hi, this repo might be able to help you. https://github.com/DerryHub/BEVFormer_tensorrt
