### ISSUE TITLE
forward_test output wrong

### ISSUE THREAD

**Issue by manhtd98** [open-mmlab/mmdeploy#691]
heree is my inference code. image shape is `6*3*800*1088`
output only [(1,28,28), (1, 100), (1,4)]
why i pass batch input with 6 samples but output only have 1 sample output
model tenssort + gpu

**Comment by manhtd98** [comment]
I check the tensorrt wrapper and output of this function always have 1 sample output. Plz check the forward method of it

**Comment by lvhan028** [comment]
Hi, @manhtd98. Sorry for replying so late. 
Would you mind sharing your test code?

**Comment by manhtd98** [comment]
input_img shape is `6*3*800*1088`
```
input_img = data["img"][0].contiguous()
 img_metas = data["img_metas"]
 outputs = self.model.forward_test(
 input_img, img_metas, return_loss=False, rescale=True)
```
But the output is only 1 images process

**Comment by lvhan028** [comment]
What's your command to convert the model? How do you prepare the input tensor?
