### ISSUE TITLE
TopDownGetBboxCenterScale is not in the pipeline registry

### ISSUE THREAD

**Issue by zambranohally** [open-mmlab/mmdeploy#696]
Hi guys, I encounter this issue when using converted mmpose model to onnx.
I tried latest version of mmpose and also the lower version of it, still error exist.
Can somebody help. Maybe I have missed something in my code.
Thanks in advance.
![image](https://user-images.githubusercontent.com/63218980/177075362-88102f87-0a84-48a3-868f-59dfd85b43ec.png)

**Comment by irexyc** [comment]
Can you check if this command can run success.

```from mmpose.datasets.pipelines import TopDownGetBboxCenterScale```

![image](https://user-images.githubusercontent.com/16019484/177092086-a15137a6-9f8f-4c21-ab8d-6f67c69e4fb8.png)

**Comment by zambranohally** [comment]
@irexyc Thank you...
I solved the issue. It is because I am using the old version of mmpose...
When I updated to latest it is now working.
