### ISSUE TITLE
Onnx to TensorRt failed: Range Operator failed 

### ISSUE THREAD

**Issue by jyang68sh** [open-mmlab/mmdeploy#711]
Hi thanks for your great work!

when Trying to convert onnx to tensorrt, I got this error:

RuntimeError: Failed to parse onnx, In node 251 (importRange): UNSUPPORTED_NODE: Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"

Can anyone help me?

Thanks!

**Comment by RunningLeon** [comment]
@jyang68sh Hi, could you post here what script you run?

**Comment by jyang68sh** [comment]
> @jyang68sh Hi, could you post here what script you run?

Hi sure. 

The script is tools/deploy.py

mmdeploy/configs/mmseg/segmentation_tensorrt-int8_static-1024x1024.py

mmseg config is a custom config: fam_stdc.py

Is this enough?

The script is tools/deploy.py

mmdeploy/configs/mmseg/segmentation_tensorrt-int8_static-1024x1024.py

mmseg config is a custom config: fam_stdc.py

Is this enough?

**Comment by jyang68sh** [comment]
@RunningLeon I also tried segmentation_tensorrt-static-1024x1024.py. Got the same error

**Comment by RunningLeon** [comment]
@jyang68sh If it's custom config, then you might need to check where you use `torch.arange` and convert the output from `troch.arange` to `torch.float32` for following computing.

**Comment by jyang68sh** [comment]
> @jyang68sh If it's custom config, then you might need to check where you use `torch.arange` and convert the output from `troch.arange` to `torch.float32` for following computing.

The custom config was to add sfnet_head as decoder to stdc backbone as 

https://github.com/MengzhangLI/mmsegmentation/blob/SFNet/mmseg/models/decode_heads/sfnet_head.py

I didnt find torch.arange  

Thanks anyway

**Comment by jyang68sh** [comment]
> @jyang68sh If it's custom config, then you might need to check where you use `torch.arange` and convert the output from `troch.arange` to `torch.float32` for following computing.

Hi I think the error suggests that it only accepts int32, shouldnt I convert the output to Int32? I got confused.

**Comment by jyang68sh** [comment]
@RunningLeon 

Hi Thanks for you suggestion. I found that my code casted tensor to float32 before range operator.

After I commented out the casting code. The model converter could run successfully.

**Comment by RunningLeon** [comment]
> @RunningLeon
> 
> Hi Thanks for you suggestion. I found that my code casted tensor to float32 before range operator.
> 
> After I commented out the casting code. The model converter could run successfully.

@jyang68sh Good to know it is solved. Welcome to star the mmdeploy on github if you haven't.  :neckbeard:

**Comment by jyang68sh** [comment]
Hi 

@RunningLeon 

Is there a way to modify Onnx Node dtype. 

In my Case I want to modify the input type of Range operator from FP32 to INT32.

I have done some research and I read the document from MMdeploy on how to modify ONX model, but didnt find a way.

If it is simply undoable, I may just modify Range operator to accept FP32 as input. I havent done it before but it is a way to solve the problem. 

Thanks

**Comment by RunningLeon** [comment]
@jyang68sh Hi, if you are ok with a static(fixed) model input shape, you could add `grid = grid.data` below [here](https://github.com/MengzhangLI/mmsegmentation/blob/12def7c0fded15798bb91017e6648884dc39f7ce/mmseg/models/decode_heads/sfnet_head.py#L211) to make sure there's no `range` op exported in onnx.

**Comment by jyang68sh** [comment]
> @jyang68sh Hi, if you are ok with a static(fixed) model input shape, you could add `grid = grid.data` below [here](https://github.com/MengzhangLI/mmsegmentation/blob/12def7c0fded15798bb91017e6648884dc39f7ce/mmseg/models/decode_heads/sfnet_head.py#L211) to make sure there's no `range` op exported in onnx.

Hi thanks Leon. It worked. 

I tried to play around torch.linspace with following code:

`
        h_n = np.linspace(-1,1,out_h).reshape(-1,1)
        h_n = np.tile(h_n, (1, out_w))
        h = torch.from_numpy(h_n)

        w_n = np.linspace(-1,1,out_w)
        w_n = np.tile(w_n, (out_h, 1))
        w = torch.from_numpy(w_n)
        grid = torch.cat((w.unsqueeze(2), h.unsqueeze(2)), 2)
`
This also worked.

From your perspective, what is the disadvantage to create tensor from numpy? What is the disadv to use static shape?

Thanks so much
