### ISSUE TITLE
About mmdeploy as a docker service 

### ISSUE THREAD

**Issue by leemengwei** [open-mmlab/mmdeploy#712]
Hi, I build docker image of mmdeploy following [https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/build_from_docker.md](url)
Instruction told me to run it with `docker run --gpus all -it -p 8080:8081 mmdeploy:master-gpu`

want to ask What's the point exposing its port to 8080?  running the cmd take me into the docker anyway...

**Comment by AllentDan** [comment]
Well, nothing special. Just in case there is a need for multiple users running the same image. `8080` is a random valid number.
