### ISSUE TITLE
Do I need to compile mmdeploy by myself?

### ISSUE THREAD

**Issue by TTgogogo** [open-mmlab/mmdeploy#714]
Can you provide a compiled package of mmdeploy? I want to use the c API of mmdeploy. I don't know how to use it. I only saw the python API.

**Comment by lvhan028** [comment]
Since v0.5.0, mmdeploy provides prebuild package. You can find them in the release note attachments. 

Regarding the usage of C API, please refer to the demos listed in [here](https://github.com/open-mmlab/mmdeploy/tree/master/demo/csrc)
