### ISSUE TITLE
Cannot change the Logging Level for TensorRT

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmdeploy#730]
The default logging level for TRT is set to `logging.INFO`. Is there any reason for this?
https://github.com/open-mmlab/mmdeploy/blob/8bdf1cfa5a833e3ec8c233d74ddefed8aaf8e35f/tools/deploy.py#L198

And I found that chaning the line as `PIPELINE_MANAGER.set_log_level(log_level, [onnx2tensorrt])` does not change the level of TRT logger,
https://github.com/open-mmlab/mmdeploy/blob/8bdf1cfa5a833e3ec8c233d74ddefed8aaf8e35f/mmdeploy/backend/tensorrt/utils.py#L167

After I change the line
https://github.com/open-mmlab/mmdeploy/blob/8bdf1cfa5a833e3ec8c233d74ddefed8aaf8e35f/mmdeploy/apis/core/pipeline_manager.py#L92
as
```
-        logger = get_root_logger(log_level=self._log_level)
+        logger = get_root_logger()
+        logger.setLevel(self._log_level)
```
, I found that `--log-level` of argparse in `tools/deploy.py` controls TRT logger normally.
The reason for this is that the root logger for `mmdeploy` is already initialized before line 92.

Is it intentional? or should it be fixed?

**Comment by grimoire** [comment]
The `set_log_level` is used to set the `PIPELINE` log. I designed the pipeline API intend to support conversion pipelines (such as async function calls). It is reasonable to synchronize the log level between the pipeline and other logs. Please feel free to fix it.
