### ISSUE TITLE
How do you write the code for loading a single image in the back-end model inference?

### ISSUE THREAD

**Issue by ymw123** [open-mmlab/mmdeploy#731]
```
model_inputs, _ = task_processor.create_input(img, input_shape)
result_seg = task_processor.run_inference(model, model_inputs)
```
I only saw these two sentences, and these two sentences seem to take longer to reason.

**Comment by RunningLeon** [comment]
@ymw123 Hi, maybe you could try with tools in https://github.com/open-mmlab/mmdeploy/pull/665

**Comment by ymw123** [comment]
![图片](https://user-images.githubusercontent.com/23358682/178253438-adfa55a2-d8ac-4ac4-bb24-316378c44149.png)
Is it written like this?

**Comment by RunningLeon** [comment]
@ymw123 Hi, you missed one step: normalize the image.
