### ISSUE TITLE
Custom mmdet model cannot be export because of the ctx.names is not same as the setting of onnx_config.output_name. 

### ISSUE THREAD

**Issue by jsxapril** [open-mmlab/mmdeploy#737]
I want to export a MMDET detection model, but the result formate is different from the general form: that is (det, label, det2, label2). However, after modifying some rewrite functions of the model,  at the final stage of exporting custom model,  ctx. names is still (det, label, mask) which is not changed by new onnx_config. I have changed onnx_config in indetection_onnxrutime_dynamic.py to make sure that the final output_names used by funtion “torch.onnx.export” is right.  How should I modify this different output to complete the export? 

Thank you~

environment:
onnx-1.8.1
Pytorch1.8
mmdeploy-2.0
mmcv-full-1.4.8
mmdet-2.22.0
cuda-10.1
ubuntu-18

**Comment by hanrui1sensetime** [comment]
Hi, @jsxapril  could you please your code changes for more information?

**Comment by jsxapril** [comment]
I have fix this problem by changed mmdeploy-codebase-mmdet-base.py. I rewirte a decorator function for the new model's forward with new output_names.
