### ISSUE TITLE
cpu or gpu，dynamic_export=true  or dynamic_export=false ，the result is  different

### ISSUE THREAD

**Issue by Winnie202** [open-mmlab/mmdeploy#739]
I'm using realbasicsvr for pytorch2onnx conversion and I'm having some problems, in the condition of model.cpu().eval(), when using dynamic_export, np.allclose(pytorch_result, onnx_result, rtol=1e-5,atol=1e- 5) The results show The numerical values are the same between Pytorch and ONNX, when dynamic_export is not used, the results of np.allclose (pytorch_result, onnx_result, rtol=1e-5, atol=1e-5) show The outputs are different between Pytorch and ONNX.
But under the condition of model.eval().to('cuda'), np.allclose(pytorch_result, onnx_result, rtol=1e-5, atol=1e-4) can achieve the above results.

**Comment by RunningLeon** [comment]
@Winnie202 Hi, please post here the full script you are running and env if possible by `python tools/check_env.py`

**Comment by RunningLeon** [comment]
Closed due to no response in a long time.
