### ISSUE TITLE
IsADirectoryError with inference_model

### ISSUE THREAD

**Issue by cyning911** [open-mmlab/mmdeploy#743]
from mmdeploy.apis import inference_model
import cv2

model_cfg = '/project/ev_sdk/config/deeplabv3plus_r101-d8_512x512_40k_voc12aug.py'
deploy_cfg = '/project/ev_sdk/src/mmdeploy/configs/mmseg/segmentation_tensorrt-fp16_static-512x512.py'
backend_files = '/project/ev_sdk/model/deeplabv3plus_r101_classes_2_sim.engine'

image_name = '/project/ev_sdk/data/demo.jpg'
img = cv2.imread(image_name)

result = inference_model(model_cfg, deploy_cfg, backend_files, img=img, device='cuda:0')

2022-07-13 14:27:53,861 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /usr/local/lib/python3.6/dist-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
2022-07-13 14:27:53,863 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /usr/local/lib/python3.6/dist-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so

IsADirectoryError                         Traceback (most recent call last)
<ipython-input-16-7e5b0330927f> in <module>
      9 img = cv2.imread(image_name)
     10 
---> 11 result = inference_model(model_cfg, deploy_cfg, backend_files, img=img, device='cuda:0')
     12 result.shape

/usr/local/lib/python3.6/dist-packages/mmdeploy/apis/inference.py in inference_model(model_cfg, deploy_cfg, backend_files, img, device)
     43     task_processor = build_task_processor(model_cfg, deploy_cfg, device)
     44 
---> 45     model = task_processor.init_backend_model(backend_files)
     46 
     47     input_shape = get_input_shape(deploy_cfg)

/usr/local/lib/python3.6/dist-packages/mmdeploy/codebase/mmseg/deploy/segmentation.py in init_backend_model(self, model_files, **kwargs)
     71         from .segmentation_model import build_segmentation_model
     72         model = build_segmentation_model(
---> 73             model_files, self.model_cfg, self.deploy_cfg, device=self.device)
     74         return model.eval()
     75 

/usr/local/lib/python3.6/dist-packages/mmdeploy/codebase/mmseg/deploy/segmentation_model.py in build_segmentation_model(model_files, model_cfg, deploy_cfg, device, **kwargs)
    229         palette=palette,
    230         deploy_cfg=deploy_cfg,
--> 231         **kwargs)
    232 
    233     return backend_segmentor

/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py in build(self, *args, **kwargs)
    235 
    236     def build(self, *args, **kwargs):
--> 237         return self.build_func(*args, **kwargs, registry=self)
    238 
    239     def _add_children(self, registry):

/usr/local/lib/python3.6/dist-packages/mmdeploy/codebase/mmseg/deploy/segmentation_model.py in __build_backend_model(cls_name, registry, *args, **kwargs)
     16 
     17 def __build_backend_model(cls_name: str, registry: Registry, *args, **kwargs):
---> 18     return registry.module_dict[cls_name](*args, **kwargs)
     19 
     20 

/usr/local/lib/python3.6/dist-packages/mmdeploy/codebase/mmseg/deploy/segmentation_model.py in __init__(self, backend, backend_files, device, class_names, palette, deploy_cfg)
     52         self.deploy_cfg = deploy_cfg
     53         self._init_wrapper(
---> 54             backend=backend, backend_files=backend_files, device=device)
     55 
     56     def _init_wrapper(self, backend, backend_files, device):

/usr/local/lib/python3.6/dist-packages/mmdeploy/codebase/mmseg/deploy/segmentation_model.py in _init_wrapper(self, backend, backend_files, device)
     62             input_names=[self.input_name],
     63             output_names=output_names,
---> 64             deploy_cfg=self.deploy_cfg)
     65 
     66     def forward(self, img: Sequence[torch.Tensor],

/usr/local/lib/python3.6/dist-packages/mmdeploy/codebase/base/backend_model.py in _build_wrapper(backend, backend_files, device, input_names, output_names, deploy_cfg, *args, **kwargs)
     65             from mmdeploy.backend.tensorrt import TRTWrapper
     66             return TRTWrapper(
---> 67                 engine=backend_files[0], output_names=output_names)
     68         elif backend == Backend.PPLNN:
     69             from mmdeploy.backend.pplnn import PPLNNWrapper

/usr/local/lib/python3.6/dist-packages/mmdeploy/backend/tensorrt/wrapper.py in __init__(self, engine, output_names)
     82         self.engine = engine
     83         if isinstance(self.engine, str):
---> 84             self.engine = load(engine)
     85 
     86         if not isinstance(self.engine, trt.ICudaEngine):

/usr/local/lib/python3.6/dist-packages/mmdeploy/backend/tensorrt/utils.py in load(path)
     33     load_tensorrt_plugin()
     34     with trt.Logger() as logger, trt.Runtime(logger) as runtime:
---> 35         with open(path, mode='rb') as f:
     36             engine_bytes = f.read()
     37         engine = runtime.deserialize_cuda_engine(engine_bytes)

IsADirectoryError: [Errno 21] Is a directory: '/'

**Comment by irexyc** [comment]
The backend_files shoud be a list:
try to use:
backend_files = ['/project/ev_sdk/model/deeplabv3plus_r101_classes_2_sim.engine']

**Comment by cyning911** [comment]
@irexyc Thank you! It workes.

**Comment by RunningLeon** [comment]
> 
maybe we could add explicit type checking in some important api functions.
