### ISSUE TITLE
Which version of mmdeploy support openvino and libtorch on windows platform?// window平台编译的mmdeloy大概在哪个版本支持openvino和libtorch框架推理部署

### ISSUE THREAD

**Issue by machine52vision** [open-mmlab/mmdeploy#748]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by irexyc** [comment]
Currently, we already support openvino. 

As for libtorch support, it is not very urgent. Because if you want to deploy a model on cpu, openvino is your first choice. And if you want to deploy it on gpu, tensorrt may be the fast backend.

While a pr is welcomed if you are insterested on it.

**Comment by lvhan028** [comment]
lvhan@pjlab.org.cn
