### ISSUE TITLE
Error occurred when compile SDK on Windows platform // 编译SDK时cmake错误

### ISSUE THREAD

**Issue by fat-921** [open-mmlab/mmdeploy#761]
我按照编译SDK的教程执行下面语句是报错，不知道该怎么处理，想请教一下。
![image](https://user-images.githubusercontent.com/66895706/179645653-87c86d53-ce96-4f38-8c5f-678783a32029.png)
![image](https://user-images.githubusercontent.com/66895706/179646010-cf8dfa2d-dba1-43a2-a7d8-7e76d564e425.png)
我使用的是VS2017编译。

**Comment by lvhan028** [comment]
Could you try VS2019?

**Comment by chl916185** [comment]
I have the same problem, how do I solve it？
@fat-921

**Comment by fat-921** [comment]
> I have the same problem, how do I solve it？ @fat-921

换成VS2019编译就不会报错了
