### ISSUE TITLE
I just want to convert an onnx model

### ISSUE THREAD

**Issue by FieldRen** [open-mmlab/mmdeploy#769]
I just want to convert an onnx model, I don't want to compile that complex environment.
Can you make a tutorial with only model converter?

**Comment by lvhan028** [comment]
What's your target device?

**Comment by FieldRen** [comment]
My target device is arm cpu，inference framework is MNN. So I just need onnx model to convert mnn

**Comment by lvhan028** [comment]
1. install conda, pytorch and mmcv-full as described in the `get_started` document
2. download and install mmdeploy
```shell
git clone --recursive https://github.com/open-mmlab/mmdeploy.git
cd mmdeploy
pip install -v -e .
```
3. install onnxruntime
```shell
pip install onnxruntime==1.8.1
```
4. (option) build onnxruntime custom ops
depends on your interested model

5. convert  model by `tools/deploy.py`
You can refer to `docs/en/02-how-to-run/convert_model.md`

You may wonder why onnxruntime is needed. That's because `pytorch2onnx` in MMDeploy is backend sensitive, meaning users must pick up a deployment config with a specific backend.

**Comment by lvhan028** [comment]
@grimoire what's the best practice in this case?

**Comment by grimoire** [comment]
`mmdeploy.apis.torch2onnx` can be used to convert models from OpenMMLab with just some configs.
You can also use `mmdeploy.apis.onnx.export`, which share similar usage as `torch.onnx.export`. You might need to import related rewriter with `mmdeploy.codebase.import_codebase` before export.

**Comment by lvhan028** [comment]
> `mmdeploy.apis.torch2onnx` can be used to convert models from OpenMMLab with just some configs. You can also use `mmdeploy.apis.onnx.export`, which share similar usage as `torch.onnx.export`. You might need to import related rewriter with `mmdeploy.codebase.import_codebase` before export.

Would you mind giving an example, for instance, `mmdet`? That will benefits our community a lot especially for those who are working on the backends or devices we are not supported now.

**Comment by grimoire** [comment]
torch2onnx
```python
    from mmdeploy.apis import torch2onnx
    img = 'demo.jpg'
   work_dir = 'work_dir'
    save_file = 'fcos.onnx'
    deploy_cfg = ('configs/mmdet/detection/'
                      'detection_onnxruntime_dynamic.py')
    model_cfg = ('mmdetection/configs/fcos/'
                     'fcos_r50_caffe_fpn_gn-head_1x_coco.py')
   model_checkpoint = ('checkpoints/'
                            'fcos_r50_caffe_fpn_gn-head_1x_coco-821213aa.pth')
   device = 'cpu'
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg, model_checkpoint, device)
```

```python
from mmdeploy.codebase import import_codebase
from mmdeploy.apis.onnx import export
import_codebase('mmdet')

model = ....
inputs = ....

export(model , inputs, output)

```
