### ISSUE TITLE
Can't convert oriented_rcnn model with angle_version = 'le135'

### ISSUE THREAD

**Issue by irexyc** [open-mmlab/mmdeploy#776]
**The command:**

```
python tools/deploy.py configs/mmrotate/rotated-detection_tensorrt_dynamic-320x320-1024x1024.py /data/test/oriented_rcnn_r50_fpn_1x_dota_le135.py /data/test/latest.pth /data/BaiduNetdiskDownload/a_2022-05-19-16-13-02.jpg --work-dir trt --dump-info --device cuda
```

**The log:**
https://justpaste.it/2h5g2

**The pth and config can be download from here:**
链接:https://pan.baidu.com/s/1dKzAJqhBDpAfWPNytUNK2Q?fm=lk0 
提取码:abcd
链接:https://pan.baidu.com/s/11RKHEHj-KuRQJlWRwanJlQ?fm=lk0 
提取码:abcd

**The image:**

![a_2022-05-19-16-13-02](https://user-images.githubusercontent.com/16019484/179924014-ce51e5b5-19be-48d7-b836-19c5f5631a70.jpg)

**Comment by irexyc** [comment]
@qiuchun

**Comment by grimoire** [comment]
https://github.com/open-mmlab/mmdeploy/pull/788
Note that I can not detect anything even with the PyTorch model. Please provide the right model or a script to use the model.
