### ISSUE TITLE
Using onnxruntime can transform the model, but the reasoning fails

### ISSUE THREAD

**Issue by qiuchun** [open-mmlab/mmdeploy#778]
the command:

./rotated_object_detection cpu D:\MMbushu\mmdeploy\tools\work_dir\2 D:\MMbushu\mmdeploy\tools\1.jpg

the end2end.onnx and img be download from here

链接:https://pan.baidu.com/s/1IXO6QAFct04J1OSqch3MDw?fm=lk0?
提取码:abcd

The log during reasoning is as follows：

loading mmdeploy_execution ...
loading mmdeploy_cpu_device ...
loading mmdeploy_graph ...
loading mmdeploy_directory_model ...
[2022-07-20 17:51:50.985] [mmdeploy] [info] [model.cpp:95] Register 'DirectoryModel'
loading mmdeploy_transform ...
loading mmdeploy_cpu_transform_impl ...
loading mmdeploy_transform_module ...
loading mmdeploy_ort_net ...
failed to load library mmdeploy_ort_net
loading mmdeploy_net_module ...
loading mmdeploy_mmcls ...
loading mmdeploy_mmdet ...
loading mmdeploy_mmseg ...
loading mmdeploy_mmocr ...
loading mmdeploy_mmedit ...
loading mmdeploy_mmpose ...
loading mmdeploy_mmrotate ...
[2022-07-20 17:51:51.065] [mmdeploy] [info] [model.cpp:38] DirectoryModel successfully load sdk model D:\MMbushu\mmdeploy\tools\work_dir\2
[2022-07-20 17:51:51.065] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "stream": "<any>"
  },
  "input": [
    "image"
  ],
  "name": "mmrotate",
  "output": [
    "det"
  ],
  "params": {
    "model": "<any>"
  },
  "type": "Inference"
}
[2022-07-20 17:51:51.066] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "size": [
        1024,
        1024
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "type": "DefaultFormatBundle"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "pad_shape",
        "flip_direction",
        "scale_factor",
        "img_norm_cfg",
        "filename",
        "flip",
        "ori_shape",
        "valid_ratio",
        "img_shape",
        "ori_filename"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-07-20 17:51:51.067] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "img"
  ],
  "module": "Transform",
  "name": "Preprocess",
  "output": [
    "prep_output"
  ],
  "transforms": [
    {
      "type": "LoadImageFromFile"
    },
    {
      "keep_ratio": true,
      "size": [
        1024,
        1024
      ],
      "type": "Resize"
    },
    {
      "mean": [
        123.675,
        116.28,
        103.53
      ],
      "std": [
        58.395,
        57.12,
        57.375
      ],
      "to_rgb": true,
      "type": "Normalize"
    },
    {
      "size_divisor": 32,
      "type": "Pad"
    },
    {
      "type": "DefaultFormatBundle"
    },
    {
      "keys": [
        "img"
      ],
      "meta_keys": [
        "pad_shape",
        "flip_direction",
        "scale_factor",
        "img_norm_cfg",
        "filename",
        "flip",
        "ori_shape",
        "valid_ratio",
        "img_shape",
        "ori_filename"
      ],
      "type": "Collect"
    }
  ],
  "type": "Task"
}
[2022-07-20 17:51:51.067] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "orientedrcnn",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-07-20 17:51:51.068] [mmdeploy] [info] [common.h:29] config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "orientedrcnn",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-07-20 17:51:51.068] [mmdeploy] [error] [net_module.cpp:37] Net backend not found: onnxruntime
[2022-07-20 17:51:51.068] [mmdeploy] [error] [task.cpp:67] error parsing config: {
  "context": {
    "device": "<any>",
    "model": "<any>",
    "stream": "<any>"
  },
  "input": [
    "prep_output"
  ],
  "input_map": {
    "img": "input"
  },
  "module": "Net",
  "name": "orientedrcnn",
  "output": [
    "infer_output"
  ],
  "type": "Task"
}
[2022-07-20 17:51:51.069] [mmdeploy] [error] [pipeline.cpp:146] could not create orientedrcnn: Task
[2022-07-20 17:51:51.069] [mmdeploy] [error] [pipeline.cpp:160] error parsing config: unknown (6) @ :0
[2022-07-20 17:51:51.069] [mmdeploy] [error] [pipeline.cpp:27] exception caught: unknown (6) @ :0
failed to create rotated detector, code: 6

**Comment by jiaqizhang123-stack** [comment]
I have the same problem, can you tell me how to solve it?

**Comment by wsora** [comment]
There are lack of some dependent dll, such as onnxruntime.dll
