### ISSUE TITLE
Make it possible to silence MMDeploy spdlog logger instance, move some log messages to DEBUG

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdeploy#78]
Hello,

I have noticed that  mmdeploy SDK generates quite a bit of log output when running inference. Therefore, I wanted to silence it. I did that by setting the log level early in my program.
```
auto mmdepLogger = mmdeploy::GetLogger();
mmdepLogger->set_level(spdlog::level::off);
```

While this almost works as expected, it looks like mmdeploy still manages to print output to the log.
```
[2022-01-14 16:48:58.176] [mmdeploy] [info] [model.cpp:97] Register 'DirectoryModel'
```
Is there a better way to silence mmdeploy? :)

Maybe some of these log messages should be DEBUG only to avoid them showing up?

**Comment by lvhan028** [comment]
You can set an env variable `SPDLOG_LEVEL` to suppress log
```bash
SPDLOG_LEVEL=error <your executable program> 
```

**Comment by tehkillerbee** [comment]
@lvhan028 Thanks, that's an OK workaround for me.  Closing this issue now.
