### ISSUE TITLE
It can reason normally on pytorch, but the visualization result of the transformation model is abnormal and it cannot rinference normally

### ISSUE THREAD

**Issue by qiuchun** [open-mmlab/mmdeploy#782]
the  mmrotate commend:
`python  demo/huge_image_demo.py  1.jpg   configs\oriented_rcnn\oriented_rcnn_r50_fpn_1x_dota_le90.py tools/run/6/latest.pth
`
the mmdeploy commend:
`python  tools/deploy.py configs/mmrotate/rotated-detection_onnxruntime_dynamic.py /data/test/oriented_rcnn_r50_fpn_1x_dota_le90.py /data/test/latest.pth data/test//1.jpg --work-dir ort --dump-info --device cpu`

the .pth、.engine、img and config can be download from here 

https://pan.baidu.com/s/1fa3tpVK5SeH9iyuM5u27-g?fm=lk0?
提取码:abcd

the pycharm`s environment on windows10:
![image](https://user-images.githubusercontent.com/65998432/180111581-ce772169-77ad-407a-83d5-0da4373a7b20.png)
![image](https://user-images.githubusercontent.com/65998432/180111635-b19021d0-59ba-4cb9-b758-fcd7fc1decc7.png)

**Comment by grimoire** [comment]
How do you perform inference with PyTorch?

**Comment by qiuchun** [comment]
the mmrotate commend:

python demo/huge_image_demo.py --img 1.jpg  --config configs\oriented_rcnn\oriented_rcnn_r50_fpn_1x_dota_le90.py 
 --checkpoint  tools/run/6/latest.pth

**Comment by grimoire** [comment]
MMRotate uses
 https://github.com/open-mmlab/mmrotate/blob/c62f148fcc2c8253218e67f2277cb8770bcd7df0/mmrotate/apis/inference.py#L13 
which will split huge image into patches and do inference on each patch.
MMDeploy is used to convert model in each codebase to the backend you want, we will NOT perform the trick in each codebae.

**Comment by qiuchun** [comment]
I also tried in mmdet, and the same problem occurred

In mmrotate, do you need to write your own code for image split and fusion during model transformation

**Comment by grimoire** [comment]
> In mmrotate, whether i need to write own code for image split and fusion during model transformation
Yes
