### ISSUE TITLE
It can reason normally on pytorch, but the visualization result of the transformation model is abnormal and it cannot reason normally

### ISSUE THREAD

**Issue by qiuchun** [open-mmlab/mmdeploy#783]
the  mmrotate commend:
`python  demo/huge_image_demo.py  1.jpg   configs\oriented_rcnn\oriented_rcnn_r50_fpn_1x_dota_le90.py tools/run/6/latest.pth
`
the mmdeploy commend:
`python  tools/deploy.py configs/mmrotate/rotated-detection_onnxruntime_dynamic.py /data/test/oriented_rcnn_r50_fpn_1x_dota_le90.py /data/test/latest.pth data/test//1.jpg --work-dir ort --dump-info --device cpu`

the .pth、.engine、img and config can be download from here 

https://pan.baidu.com/s/1fa3tpVK5SeH9iyuM5u27-g?fm=lk0?
提取码:abcd

the pycharm`s environment on windows10:
![image](https://user-images.githubusercontent.com/65998432/180111581-ce772169-77ad-407a-83d5-0da4373a7b20.png)
![image](https://user-images.githubusercontent.com/65998432/180111635-b19021d0-59ba-4cb9-b758-fcd7fc1decc7.png)

**Comment by lvhan028** [comment]
Duplicated issue to #782
