### ISSUE TITLE
[module_adapter.h:34] unhandled exception: invalid argument (1) @ /home/PJLAB/lvhan/Documents/projects/mmdeploy-release/mmdeploy/csrc/device/cuda/cuda_device.cpp:171 

### ISSUE THREAD

**Issue by qyf13505049895** [open-mmlab/mmdeploy#802]
[module_adapter.h:34] unhandled exception: invalid argument (1) @ /home/PJLAB/lvhan/Documents/projects/mmdeploy-release/mmdeploy/csrc/device/cuda/cuda_device.cop:171
terminate called after throwing an instance of 'system_error2::status_error<mmdeploy::StatusDomain>'
  what():  unknown (6) @ /home/PJLAB/lvhan/Documents/projects/mmdeploy-release/mmdeploy/csrc/experimental/module_adapter.h:35
Aborted (core dumped)

**Comment by tpoisonooo** [comment]
The log has showed `invalid argument (1)` for us, can you 

1) Give the command you are using and
2) `python3 tools/check_env.py` ?

I guess that `(1)` is device id ?

**Comment by tpoisonooo** [comment]
Close issue since no reply, If you have any question, please reopen it.
