### ISSUE TITLE
INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)

### ISSUE THREAD

**Issue by Yibin122** [open-mmlab/mmdeploy#82]
Running the example gives the error as titled.
`python ./tools/deploy.py \
    configs/mmdet/detection/detection_tensorrt_dynamic-320x320-1344x1344.py \
    $PATH_TO_MMDET/configs/yolo/yolov3_d53_mstrain-608_273e_coco.py \
    $PATH_TO_MMDET/checkpoints/yolo/yolov3_d53_mstrain-608_273e_coco.pth \
    $PATH_TO_MMDET/demo/demo.jpg \
    --work-dir work_dir \
    --show \
    --device cuda:0`

My environment:
- PyTorch 1.8.0
- TensorRT 7.1.3

It seems the TensorRT version is lower than required. Does MMDepoly only support TensorRT 8?

**Comment by AllentDan** [comment]
In my testing, TensorRT 7.2.3 works fine

**Comment by Yibin122** [comment]
TensorRT 8.0.3 also works fine. But can you confirm that TensorRT 7.1.3 is unsupported?

**Comment by AllentDan** [comment]
7.1.3 also works fine in my machine. I used tensorrt 7.1.3.4-cuda10.2 and 1660 card.

**Comment by lvhan028** [comment]
Close it because of no reply for a very long time

**Comment by VJoer** [comment]
I get the same error in tensorrt 7.0.0.11-cuda10.2
`python tools/deploy.py configs/mmdet/detection/detection_tensorrt_dynamic-300x300-512x512.py mmdetection/models/torch/fcos_r50_caffe_fpn_gn-head_1x_coco.py mmdetection/models/torch/fcos.pth images/1183.jpg --work-dir work_dir/fcos --device cuda:1`

my environment:
python 3.7
tensorrt 7.0.0.11
cuda 10.2
cudnn 7.6.5

**Comment by AllentDan** [comment]
TRT8+ is recommended as there are many bugs get fixed there
