### ISSUE TITLE
Sliding window detection, automatic clipping

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdeploy#820]
**Describe the feature**

Sliding window detection
Auto overlap crop

**Motivation**

The picture is too big
9000*9000

Cannot crop directly
Some details will be cropped and cannot be recognized normally
Overlapping clipping required

**Related resources**

If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**

![sliced_inference](https://user-images.githubusercontent.com/6490927/181139741-ab81da9f-12a7-4f29-b756-f3161dde3613.gif)
![__results___20_0](https://user-images.githubusercontent.com/6490927/181139760-d708d220-b3ce-4878-8435-ca4dd7d0015d.png)

**Comment by tpoisonooo** [comment]
I have not idea about any existed repo but I think it quite simple to implement:

1. crop Input and batching,  for example input shape [9, 3, 9000/4, 9000/4]
2. inference without  NMS
3. NMS cross batch in postprocess

**Comment by tpoisonooo** [comment]
Close this issue due to no reply for a long time. Please open a new one if you have any more ideas.
