### ISSUE TITLE
Dozens of glue OP are generated when converting Fasterrcnn/Maskrcnn to onnx

### ISSUE THREAD

**Issue by dygcjlu** [open-mmlab/mmdeploy#821]
i use the following command to convert faster rcnn to onnx,  but dozens of glue OP were generated instead of RPN layer. 
Any way to avoid that ? 

python /home/xxd/dyg/open-mmlab/mmdeploy/tools/deploy.py \
    /home/xxd/dyg/open-mmlab/mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py \
    /home/xxd/dyg/open-mmlab/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    /home/xxd/dyg/open-mmlab/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    /media/xxd/Data2/datasets/voc/test_img/2008_002378.jpg \
    --work-dir work_dir \
    --dump-info
![0727_1](https://user-images.githubusercontent.com/31989667/181173115-0bf40f9c-5c3b-4d02-8a9a-f1f9472e2110.png)
![0727_2](https://user-images.githubusercontent.com/31989667/181173123-f73ee8ab-c92f-4b17-8df3-ce6d6b6d8631.png)

**Comment by RunningLeon** [comment]
@dygcjlu Hi, because the postprocessing is included in the onnx. If you want to skip post-processing part while exporting to onnx, you can refer to https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/06-developer-guide/partition_model.md.

**Comment by RunningLeon** [comment]
feel free to reopen if you still have the issue.
