### ISSUE TITLE
ImportError:cannot import name 'points_in_polygons' from 'mmcv.ops'(D:\Anaconda3\envs\mmdeploy\lib\site-packages\mmcv\ops\__init__.py）

### ISSUE THREAD

**Issue by qiuchun** [open-mmlab/mmdeploy#823]
When I use tensorrt to deploy mmrotate, this problem occurs in the model transformation phase, but it does not occur when I perform mmdetection model transformation

the commend:
python deploy.py  --deploy_cfg  D:\MMbushu\mmdeploy\configs\mmrotate\rotated-detection_tensorrt_dynamic-320x320-1024x1024.py  --model_cfg  D:\pcb\models\xuanzhuan\mmrotate-main\configs\oriented_rcnn\oriented_rcnn_r50_fpn_1x_dota_le90.py  --checkpoint  D:\pcb\models\xuanzhuan\mmrotate-main\tools\run\6\latest.pth  --img 1.jpg --dump-info --show

the log of error:
![image](https://user-images.githubusercontent.com/65998432/181199542-f09dc27e-3846-46dc-9d83-2fcd08b9009d.png)

the check_env.py result:
![image](https://user-images.githubusercontent.com/65998432/181198728-f69120ec-d576-4c26-8ec2-255675d78d4b.png)
the pip list result:
![image](https://user-images.githubusercontent.com/65998432/181198783-088fcb68-22d3-48b5-a862-9eceb813e3c1.png)

Is this the reason for mmrotate or mmcv?

**Comment by tpoisonooo** [comment]
`points_in_polygons.py`  is a normal python file which defined in `https://github.com/open-mmlab/mmcv/tree/v1.4.2/mmcv/ops` 

It is first added from mmcv==v1.4.2,  so please upgrade your mmcv>=v1.4.2

**Comment by tpoisonooo** [comment]
Close this issue due to no reply for a long time. Please open a new one if this exception still not fixed.
