### ISSUE TITLE
help ! when i compile the latest mmdeploy, error ocuured on windows10.

### ISSUE THREAD

**Issue by centerzong** [open-mmlab/mmdeploy#824]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

D:\workspace\AIWork\mmdeploy\csrc\preprocess\cuda\resize_impl.cpp(47): error C2065: “INTERPOLATION_TYPE_LINEAR”: 未声明的标识符 [D:\workspace\AIWork\mmdeploy\build\csrc\preprocess\c
uda\mmdeploy_cuda_transform_impl.vcxproj]
D:\workspace\AIWork\mmdeploy\csrc\preprocess\cuda\resize_impl.cpp(64): error C2039: "INTERPOLATION_TYPE_NEAREST_POINT": 不是 "ppl::cv" 的成员 [D:\workspace\AIWork\mmdeploy\build\c
src\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
  D:\aiRunLib\ppl.cv\pplcv-build\install\lib\cmake\ppl\..\..\..\include\ppl/cv/cuda/resize.h(26): note: 参见“ppl::cv”的声明
D:\workspace\AIWork\mmdeploy\csrc\preprocess\cuda\resize_impl.cpp(47): error C2065: “INTERPOLATION_TYPE_NEAREST_POINT”: 未声明的标识符 [D:\workspace\AIWork\mmdeploy\build\csrc\prepr
ocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]

**Comment by irexyc** [comment]
Which ppl.cv version do you use?

**Comment by centerzong** [comment]
the ppl.cv version is 0.7.0 and the mmdeploy version is 0.5.0.

**Comment by irexyc** [comment]
You may edit `ppl.cv/cuda-build/install/lib/cmake/ppl/pplcv-config.cmake`

Change ppl.cv version to this:
```
set(PPLCV_VERSION_MAJOR 0)
set(PPLCV_VERSION_MINOR 6)
set(PPLCV_VERSION_PATCH 2)
```

After that, you may remove the build cache files and rebuild mmdeploy

**Comment by lvhan028** [comment]
mmdeploy v0.5.0 supports pplcv 0.6.2 and its previous version. 
So please clone pplcv v0.6.2 and rebuild it.

**Comment by centerzong** [comment]
I use pplcv0.6.2, another error is:
pplcv_static.lib(cvtcolor.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中) [E:\AIWork\mmdeploy\build\cs
rc\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
pplcv_static.lib(copymakeborder.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中) [E:\AIWork\mmdeploy\bu
ild\csrc\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
pplcv_static.lib(resize.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中) [E:\AIWork\mmdeploy\build\csrc
\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
pplcommon_static.lib(log.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(cast.obj 中) [E:\AIWork\mmdeploy\build\csr
c\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library [E:\AIWork\mmdeploy\build\csrc\preprocess\cuda\mmdeploy_cuda_transform_impl.vcxproj]
E:\AIWork\mmdeploy\build\bin\Release\mmdeploy_cuda_transform_impl.dll : fatal error LNK1319: 检测到 4 个不匹配项 [E:\AIWork\mmdeploy\build\csrc\preprocess\cuda\mmdep

**Comment by irexyc** [comment]
You can follow the document

The error you met is due to the `PPLCV_USE_MSVC_STATIC_RUNTIME` option, please to `OFF` and retry it.
```
git clone https://github.com/openppl-public/ppl.cv.git
cd ppl.cv
git checkout tags/v0.6.2 -b v0.6.2
$env:PPLCV_DIR = "$pwd"
mkdir pplcv-build
cd pplcv-build
cmake .. -G "Visual Studio 16 2019" -T v142 -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DPPLCV_USE_CUDA=ON -DPPLCV_USE_MSVC_STATIC_RUNTIME=OFF
cmake --build . --config Release -- /m
cmake --install . --config Release
cd ../..
```

**Comment by centerzong** [comment]
E:\AIWork\mmdeploy\mmdeploy\mmcv\ops\nms.py:181: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  (batch_size, out_boxes)).to(scores.device))
2022-08-01 09:06:28,636 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.



thanks for your help, there is another trouble, wo I convert the faster_rcnn model on windows, error ocurred!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmlab37\lib\multiprocessing\util.py", line 300, in _run_finalizers
    finalizer()
  File "C:\ProgramData\Anaconda3\envs\mmlab37\lib\multiprocessing\util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\mmlab37\lib\multiprocessing\managers.py", line 675, in _finalize_manager
    process.join(timeout=1.0)
  File "C:\ProgramData\Anaconda3\envs\mmlab37\lib\multiprocessing\process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "C:\ProgramData\Anaconda3\envs\mmlab37\lib\multiprocessing\popen_spawn_win32.py", line 104, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt

**Comment by irexyc** [comment]
Closed. as the initial problem is solved. 

The post problem can be discussed on #838
