### ISSUE TITLE
Error: export FCOS model!

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmdeploy#828]
I export my model use static graph, but got output is dynamic!
![image](https://user-images.githubusercontent.com/48318485/181416026-4c86fe9b-c96b-4c38-bfd4-d47bd3e7d8ff.png)

**Comment by RunningLeon** [comment]
@FDInSky Pls post your full script and the env with `python tools/check_ev.py`

**Comment by hanrui1sensetime** [comment]
@FDInSky  Hi, did you remember your script and the env with python tools/check_ev.py? Please post on here, thank you.

**Comment by hanrui1sensetime** [comment]
I will close this issue, if you have other questions about this issue, you can reopen it.
