### ISSUE TITLE
I'm running an error in docker .

### ISSUE THREAD

**Issue by zhaoyuan1209** [open-mmlab/mmdeploy#83]
I used the conversion command "python /home/zhaoyuan/MMDeploy//tools/deploy.py     /home/zhaoyuan/MMDeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py      mask_rcnn_x101_64x4d_fpn_1x_coco.py     epoch_100.pth     /home/zhaoyuan/code/index_recognize/test/202112221918072815.jpg     --work-dir ./     --device cuda:0     --dump-info" to generate the onnx file.

I call using the command "seg_result = inference_model(seg_config_file, "/home/zhaoyuan/MMDeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py",
                                 ["/home/zhaoyuan/code/index_recognize/mask_rcnn_x101_1x/end2end.onnx"], img=bbox_image[0], device=device)[0][1]" in the code.

Then I ran an error in docker:"onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /root/mm_index/config/end2end.onnx failed:Fatal error: MMCVRoiAlign is not a registered function/op"

why is this ?

**Comment by RunningLeon** [comment]
@zhaoyuan1209 Hi, have you built custom ops for onnxruntime? If not, could refer to https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/backends/onnxruntime.md#build-custom-ops

**Comment by RunningLeon** [comment]
feel free to reopen if have any issue.
