### ISSUE TITLE
使用tensorrt原生API推理oriented_rcnn时，获得的结果中，没法得到框的类型值。请问如何得到框的类型值。

### ISSUE THREAD

**Issue by bfdong** [open-mmlab/mmdeploy#836]
使用tensorrt原生API推理oriented_rcnn时，获得的结果中，没法得到框的类型值。请问如何得到框的类型值。

**Comment by lvhan028** [comment]
Have you tried to use `inference_model` to check if `oriented_rcnn` can be deployed successfully?
