### ISSUE TITLE
make -j$(nproc) mmdeploy error

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [open-mmlab/mmdeploy#837]
Hello,  When I compile mmdeploy I get the following problem. I don't know why, thank you so much
(mmdeploy) zhang@zhang-QiTianM540-A739:~/mmdeploy/build$ make -j$(nproc)
Consolidate compiler generated dependencies of target mmdeploy_onnxruntime_ops_obj
Consolidate compiler generated dependencies of target mmdeploy_tensorrt_ops_obj
[ 15%] Built target mmdeploy_onnxruntime_ops_obj
[ 18%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/kernel.cu.o
[ 21%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/deform_conv/trt_deform_conv_kernel.cu.o
[ 26%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/trt_cuda_helper.cu.o
[ 26%] Building CXX object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/deform_conv/trt_deform_conv.cpp.o
[ 28%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerImage.cu.o
[ 31%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerClass.cu.o
[ 34%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_sampler/trt_grid_sampler_kernel.cu.o
[ 36%] Building CXX object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_priors/trt_grid_priors.cpp.o
[ 39%] Building CXX object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/multi_level_roi_align/trt_multi_level_roi_align.cpp.o
[ 42%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_priors/trt_grid_priors_kernel.cu.o
[ 44%] Building CXX object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/grid_sampler/trt_grid_sampler.cpp.o
[ 47%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/modulated_deform_conv/trt_modulated_deform_conv_kernel.cu.o
[ 50%] Building CUDA object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/multi_level_roi_align/trt_multi_level_roi_align_kernel.cu.o
[ 52%] Built target mmdeploy_onnxruntime_ops
[ 55%] Building CXX object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/instance_norm/trt_instance_norm.cpp.o
[ 57%] Building CXX object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/modulated_deform_conv/trt_modulated_deform_conv.cpp.o
[ 60%] Building CXX object csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/multi_level_rotated_roi_align/trt_multi_level_rotated_roi_align.cpp.o
In file included from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/../util_ptx.cuh:40:0,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/block_exchange.cuh:37,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/block_radix_sort.cuh:37,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/block_histogram_sort.cuh:36,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/block_histogram.cuh:36,
                 from /home/zhang/mmdeploy/third_party/cub/cub/cub.cuh:40,
                 from /home/zhang/mmdeploy/csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/kernel.cu:6:
/home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/../util_debug.cuh:42:10: fatal error: nv/target: 没有那个文件或目录
 #include <nv/target>
          ^~~~~~~~~~~
compilation terminated.
csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/build.make:187: recipe for target 'csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/kernel.cu.o' failed
make[2]: *** [csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/kernel.cu.o] Error 1
make[2]: *** 正在等待未完成的任务....
In file included from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/../util_ptx.cuh:40:0,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/block_exchange.cuh:37,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/block_radix_sort.cuh:37,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/block_histogram_sort.cuh:36,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/block_histogram.cuh:36,
                 from /home/zhang/mmdeploy/third_party/cub/cub/cub.cuh:40,
                 from /home/zhang/mmdeploy/csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/sortScoresPerClass.cu:6:
/home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/../util_debug.cuh:42:10: fatal error: nv/target: 没有那个文件或目录
 #include <nv/target>
          ^~~~~~~~~~~
compilation terminated.
csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/build.make:215: recipe for target 'csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerClass.cu.o' failed
make[2]: *** [csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerClass.cu.o] Error 1
In file included from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/../util_ptx.cuh:40:0,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/block_exchange.cuh:37,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/block_radix_sort.cuh:37,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/specializations/block_histogram_sort.cuh:36,
                 from /home/zhang/mmdeploy/third_party/cub/cub/block/block_histogram.cuh:36,
                 from /home/zhang/mmdeploy/third_party/cub/cub/cub.cuh:40,
                 from /home/zhang/mmdeploy/csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/sortScoresPerImage.cu:6:
/home/zhang/mmdeploy/third_party/cub/cub/block/specializations/../../block/../util_debug.cuh:42:10: fatal error: nv/target: 没有那个文件或目录
 #include <nv/target>
          ^~~~~~~~~~~
compilation terminated.
csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/build.make:229: recipe for target 'csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerImage.cu.o' failed
make[2]: *** [csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/common_impl/nms/sortScoresPerImage.cu.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/all' failed
make[1]: *** [csrc/mmdeploy/backend_ops/tensorrt/CMakeFiles/mmdeploy_tensorrt_ops_obj.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

(mmdeploy) zhang@zhang-QiTianM540-A739:~/mmdeploy/build$ cmake -DCMAKE_CXX_COMPILER=g++-7       -DMMDEPLOY_TARGET_BACKENDS='ort;trt'       -DONNXRUNTIME_DIR=/home/zhang/onnxruntime-linux-x64-gpu-1.11.0       -DTENSORRT_DIR=/home/zhang/TensorRT-8.2.3.0       -DCUDNN_DIR=/home/zhang/cuda .. 
-- CMAKE_INSTALL_PREFIX: /home/zhang/mmdeploy/build/install
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-7 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda-10.2 (found version "10.2") 
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Build ONNXRUNTIME custom ops.
-- Build TensorRT custom ops.
-- Found TensorRT headers at /home/zhang/TensorRT-8.2.3.0/include
-- Found TensorRT libs at /home/zhang/TensorRT-8.2.3.0/lib/libnvinfer.so;/home/zhang/TensorRT-8.2.3.0/lib/libnvinfer_plugin.so
-- Found TENSORRT: /home/zhang/TensorRT-8.2.3.0/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhang/mmdeploy/build

**Comment by lzhangzz** [comment]
You are using wrong commit of cub.

https://github.com/NVIDIA/cub/tree/c3cceac115c072fb63df1836ff46d8c60d9eb304

doesn't have `#include <nv/target>` on `util_debug.cuh:42`

**Comment by jiaqizhang123-stack** [comment]
ok, thank you very much

**Comment by hch-baobei** [comment]
> ok, thank you very much

你好，你是怎么解决的cub安装问题，可以分享一下吗？

**Comment by jiaqizhang123-stack** [comment]
https://github.com/NVIDIA/cub/tree/c3cceac115c072fb63df1836ff46d8c60d9eb304 
cub downloaded from this url
