### ISSUE TITLE
Error occured when I try Install pyncnn

### ISSUE THREAD

**Issue by Qingrenn** [open-mmlab/mmdeploy#854]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

After installing pyncnn following [linux-x86_64](https://github.com/open-mmlab/mmdeploy/blob/master/docs/zh_cn/01-how-to-build/linux-x86_64.md), ncnn can not be imprted normaly.
```bash
cd ${NCNN_DIR}/python
pip install -e .
```
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/45782082/182522994-cfac3858-0b3c-4da9-a512-02df8966fadf.png">

Therefore I uninstall it and try install by
```bash
cd ${NCNN_DIR}
pip install .
```

ncnn can be imported normaly
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/45782082/182523303-142a1df4-2977-4bb4-9fc1-98370edcbef9.png">

**Comment by tpoisonooo** [comment]
Fixed and close the issue.
