### ISSUE TITLE
Error in doc

### ISSUE THREAD

**Issue by chenyiminch** [open-mmlab/mmdeploy#856]
Thanks for your bug report. We appreciate it a lot.

**Describe the bug**

https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/01-how-to-build/linux-x86_64.md

In the step "Build Demo", the cmd should be

`
cd ${MMDEPLOY_DIR}/build/install/example/cpp
`

instead of 

`
cd ${MMDEPLOY_DIR}/build/install/example
`

**Comment by tpoisonooo** [comment]
Any PR is welcomed, feel free to fix it~
