### ISSUE TITLE
find some improvements when I follow the docs to quantize model using ncnn

### ISSUE THREAD

**Issue by OldDreamInWind** [open-mmlab/mmdeploy#867]
1. I use docker to build mmdeploy, the cpu version. In docker/CPU/Dockerfile, when building ncnn, it doesn't use "make -j$(nproc)", so only one core is used.
2. Without setting the path of ncnn2int8 in dockerfile, ncnn2int8 may can't be found.
3. In docs/zh_cn/02-how-to-run/quantize_model.md, MODEL_PATH and MODEL_CONFIG should exchange.
4. When I use tools/deploy.py to quantize model, I set "--device cpu". But it doesn't work. Then I find that this parameter missed in function get_table.

I opened 2 pr to solve these questions.

**Comment by OldDreamInWind** [comment]
#840

**Comment by tpoisonooo** [comment]
Thanks for your contribution !
