### ISSUE TITLE
c++ SDK problem

### ISSUE THREAD

**Issue by Nuralill** [open-mmlab/mmdeploy#885]
I use c++ SDK in my server and use the command `object_detection.exe cuda E:\\PycharmProjects\\mmdeploy_out\\mmdet\\faster_rcnn_r50_trt E:\\PycharmProjects\\mmdetection-master\\demo\\1.jpg` could successfully run ，but when I download the related code and compile success,I use same command ,it shows
`[2022-08-10 13:12:34.783] [mmdeploy] [error] [model.cpp:44] no ModelImpl can read model D:/pythonProject/mmdeploy_out/mmdet/faster_rcnn_r50_trt
[2022-08-10 13:12:34.784] [mmdeploy] [error] [model.cpp:15] load model failed. Its file path is 'D:/pythonProject/mmdeploy_out/mmdet/faster_rcnn_r50_trt'
[2022-08-10 13:12:34.786] [mmdeploy] [error] [model.cpp:20] failed to create model: not supported (2)
failed to create detector, code: 6`
could you help me?
Should I disposition tensorRT environment in my computer with visual stusdio?
我在服务器上已经能够通过c++推理运行相关代码了，但是当我把trt模型文件下载到自己电脑，并且也下载其他相关代码而且编译成功没有报错了，在运行exe文件时，出现了上述报错。会不会是我在vs中没有配置tensorRT的问题呢？但是我在编译过程中并没有任何报错

**Comment by lvhan028** [comment]
Maybe similar to #883.
Can you share the compiling command?

**Comment by Nuralill** [comment]
I create a Release x64 item in visual studio 2019.Then I create an new item  `object_detection.cpp`,linked enviroment and download the dll files which are reminds me lacked.And in vs2019 click make, exe file will generate.
我就是把 `object_detection.cpp`的代码复制下来，然后在vs2019里面新建项目，之后添加opencv等包含目录，然后连接dll，生成exe文件以后提示缺少的dll下载移到项目文件夹中，直到成功生成exe文件，但在运行exe文件时会出现上述报错。

**Comment by irexyc** [comment]
你可以研究一下mmdeploy的cmake工程，在编译example的时候，`mmdeploy_load_dynamic`其实是构建了一个loader，然后在exe中静态链接了一个函数，该函数使用LoadLibraryA去加载一些module的dll。

You can study the cmake project of mmdeploy. When compiling the example, `mmdeploy_load_dynamic` statically link a loader to the exe. The loader uses LoadLibraryA to load some module dlls.

https://github.com/open-mmlab/mmdeploy/blob/master/demo/csrc/CMakeLists.txt#L23
https://github.com/open-mmlab/mmdeploy/blob/master/cmake/MMDeploy.cmake#L161-L166
https://github.com/open-mmlab/mmdeploy/blob/master/cmake/loader.cpp.in

如果编译example的时候想脱离cmake的工程的话，可以在编译mmdeploy的时候，加上`-D MMDEPLOY_BUILD_SDK_MONOLITHIC=ON`选项，然后会生成一个`mmdeploy.dll`的动态库，在生成exe的时候只链接这个dll就可以(之前的dll变成了`mmdeploy.dll`的依赖，还是需要移动到项目文件夹或者添加PATH）

If you want to build project without cmake when compiling the example, you can add the `-D MMDEPLOY_BUILD_SDK_MONOLITHIC=ON` option when compiling mmdeploy. It will  generate dynamic library called `mmdeploy.dll`. When compile example, you only need to link that lib(the previous dll has become a dependency of `mmdeploy.dll`, and it still needs to be moved to the project folder or added to the PATH)

**Comment by Nuralill** [comment]
How can I just move a part of function to another computer？
For example，I config all in my 3060 and got the trained file, I just want to use mmseg SDK to run my trt file in another computer 3080 ,and I dont  want to config the environment again,download entire mmdeploy . What should I do?

**Comment by irexyc** [comment]
可以参考这个issue的说明  https://github.com/open-mmlab/mmdeploy/issues/685
