### ISSUE TITLE
How can i add a new custom op for TensorRT in mmdeploy?

### ISSUE THREAD

**Issue by Hou-MY** [open-mmlab/mmdeploy#901]
Is there any example or tutorial？ I  just saw the procedures of adding custom operators for ONNX Runtime in MMDeploy. I want to implement soft_nms op in TensorRT .Because the mAP of trt is lower than pth.

**Comment by AllentDan** [comment]
Hi, you can refer to the [PR](https://github.com/open-mmlab/mmdeploy/pull/290).

**Comment by machine52vision** [comment]
> Hi, you can refer to the [PR](https://github.com/open-mmlab/mmdeploy/pull/290).

thanks,it work
