### ISSUE TITLE
Accrording the get_started.md, it occur the problem: cpu is invalid for the backend tensort

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdeploy#909]
Hello, this is my first time to use the mmdeploy, i follow the [get_started.md](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/get_started.md) to convert model with _Linux-x86_64, CUDA 11.x, TensorRT 8.2.5.1_, just like the **md** show 
![image](https://user-images.githubusercontent.com/86214036/185065382-9ff1e099-48df-439a-91b1-96a09831f3f7.png)

but it occur the problem: **ValueError: cpu is invalid for the backend tensort**.

By the way , my env as follow:
![40A687CFDC1C729D708693F8848FAC0D](https://user-images.githubusercontent.com/86214036/185069011-4d45043f-9161-4e4d-b53d-4e3369739934.png)
![0F13DD7514ED2B443CBBD92E2C0D5D3B](https://user-images.githubusercontent.com/86214036/185069049-55bbcee0-3eff-4dc0-8bf0-594729d3ef95.png)

**Comment by lijoe123** [comment]
Thank you for your answer immediately!!!!!! I  had use **--device cuda**  
![CE2BCF976B61F442245C502CFBF49D01](https://user-images.githubusercontent.com/86214036/185070640-bb105a37-9fe2-47c1-bbe7-ebdd0177c293.jpg)

**Comment by AllentDan** [comment]
> Thank you for your answer immediately!!!!!! I had use **--device cuda** ![CE2BCF976B61F442245C502CFBF49D01](https://user-images.githubusercontent.com/86214036/185070640-bb105a37-9fe2-47c1-bbe7-ebdd0177c293.jpg)

Thanks for reporting the bug. Will fix it ASAP.

**Comment by lijoe123** [comment]
Thank you Dan. I want to ask you another question: when i work on this step
![image](https://user-images.githubusercontent.com/86214036/185074363-4df55978-be1c-4717-8413-4c5ed15b7e02.png)
i found the file don't have the **lib64**, so i change **lib64** to **lib**, is that true?
export LD_LIBRARY_PATH=$CUDNN_DIR/**lib**:$LD_LIBRARY_PATH
![D6C0DDD5773CA97A2662C3A3D29B0FA7](https://user-images.githubusercontent.com/86214036/185074758-2d909647-70aa-41a0-b690-fc3533ed77b1.jpg)

**Comment by qiumeng6** [comment]
hi, i have the same problem, I think it is a bug caused by the parameter --dump-info. And I have not modified lib64, it can be run. But I have a problem, when I run ./tools/check_env, it shows that my cudnn version is 8.0.x, but I have installed 8.4.x, although the demo can run normally, but I am very confused.

**Comment by AllentDan** [comment]
@qiumeng6 How did you install PyTorch? If you installed it through conda, it is reasonable then.

**Comment by lijoe123** [comment]
Thank you for your answer @qiumeng6 , so i will delete the --dump-info to try to run it.
But i have some question:
1、the **$(pwd**) of _export CUDNN_DIR=$(pwd)/cuda_ , do i need to change the **$(pwd**) to my own path ? just like _export CUDNN_DIR=**/home/music/downloads**/cuda_
2、so, your cuda file have the **include file** and **lib file** just like me?
![image](https://user-images.githubusercontent.com/86214036/185081228-9bb02faa-f54d-4c4c-a6fd-a56efb548722.png)

**Comment by lijoe123** [comment]
When i remove the `--dump-info`, it occur other problem:
![6AB5E8D9AEB07B9EE621FD112E769CC0](https://user-images.githubusercontent.com/86214036/185082340-55d6117d-09a1-4630-be32-17b283b83aea.jpg)
Accually, i had run `pip install -v -e .`

**Comment by AllentDan** [comment]
> When i remove the `--dump-info`, it occur other problem: ![6AB5E8D9AEB07B9EE621FD112E769CC0](https://user-images.githubusercontent.com/86214036/185082340-55d6117d-09a1-4630-be32-17b283b83aea.jpg) Accually, i had run `pip install -v -e .`

Pls install mmdet first if you want to use it.

**Comment by qiumeng6** [comment]
@lijoe123 
1.Here is my example environment variable：
![image](https://user-images.githubusercontent.com/55289802/185084734-f12fb61e-a379-4ff2-9224-03d313f6fae5.png)
2. yes!

**Comment by qiumeng6** [comment]
@AllentDan yes! , i installed pytorch through conda . You mean cudnn already exists in my conda environment? How do I need to keep the versions consistent, or could you give me some relevant links.   +.+

**Comment by lijoe123** [comment]
> ![image](https://user-images.githubusercontent.com/55289802/185084734-f12fb61e-a379-4ff2-9224-03d313f6fae5.png)
> 2. yes!

Ok! Thank you guy!!!!

**Comment by AllentDan** [comment]
> @AllentDan yes! , i installed pytorch through conda . You mean cudnn already exists in my conda environment? How do I need to keep the versions consistent, or could you give me some relevant links. +.+

It is not a big deal as that's how conda works. And it does not influence the usage of MMDeploy.

**Comment by AllentDan** [comment]
BTW, it you insists on keeping the versions the same. Pls install the right version of PyTorch according to your local CUDNN. Or, you can also update your local CUDNN to the version of CUDNN in conda.

**Comment by qiumeng6** [comment]
> BTW, it you insists on keeping the versions the same. Pls install the right version of PyTorch according to your local CUDNN. Or, you can also update your local CUDNN to the version of CUDNN in conda.

Ok, thank you for your reply！
and  Which version will the MMDeploy use? .  0.0

**Comment by AllentDan** [comment]
> > BTW, it you insists on keeping the versions the same. Pls install the right version of PyTorch according to your local CUDNN. Or, you can also update your local CUDNN to the version of CUDNN in conda.
> 
> Ok, thank you for your reply！ and Which version will the MMDeploy use? . 0.0

MMDeploy has no requirements for CUDNN. It is those backends like TensorRT that require specific CUDA.

**Comment by qiumeng6** [comment]
Ok，thank you for your reply very much！

**Comment by qiumeng6** [comment]
> > > BTW, it you insists on keeping the versions the same. Pls install the right version of PyTorch according to your local CUDNN. Or, you can also update your local CUDNN to the version of CUDNN in conda.
> > 
> > 
> > Ok, thank you for your reply！ and Which version will the MMDeploy use? . 0.0
> 
> MMDeploy has no requirements for CUDNN. It is those backends like TensorRT that require specific CUDA.

Ok，thank you for your reply very much！

**Comment by AllentDan** [comment]
Close since all the issues got fixed.

**Comment by lijoe123** [comment]
I'm sorry! I still have the problem ：ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory
I had run the 
![image](https://user-images.githubusercontent.com/86214036/185113462-8fab107d-9f6f-4dd8-9bbd-13cbe2f0c87d.png)
but still had the problem!!!!!
Thank you!

**Comment by AllentDan** [comment]
Pls run `ls $TENSORRT_DIR/lib` and check if libnvinfer.so exists.
