### ISSUE TITLE
Error occured when converting SAR_Chinese text recognition model to onnx

### ISSUE THREAD

**Issue by DingchenYang99** [open-mmlab/mmdeploy#915]
Thanks for your bug report. We appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True.
2022-08-18 10:27:24,065 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

**Reproduction**

1. What command or script did you run?

python /root/autodl-tmp/MMdeploy/tools/deploy.py /root/autodl-tmp/MMdeploy/configs/mmocr/text-recognition/text-recognition_onnxruntime_dynamic.py /root/autodl-tmp/MMocr/configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py /root/.cache/torch/hub/checkpoints/sar_r31_parallel_decoder_chineseocr_20210507-b4be8214.pth /root/autodl-tmp/MMocr/demo/train/5_2.jpg --work-dir /root/autodl-tmp/MMdeploy/save_dir --device cuda --dump-info --show

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I have added 'use_external_data_format=True' in mmdeploy/apis/onnx/export.py, but it didn't work.

**Environment**
2022-08-18 10:37:03,419 - mmdeploy - INFO - 

2022-08-18 10:37:03,419 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-08-18 10:37:03,871 - mmdeploy - INFO - sys.platform: linux
2022-08-18 10:37:03,872 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
2022-08-18 10:37:03,872 - mmdeploy - INFO - CUDA available: True
2022-08-18 10:37:03,872 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 2080 Ti
2022-08-18 10:37:03,873 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-08-18 10:37:03,873 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.8
2022-08-18 10:37:03,873 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2022-08-18 10:37:03,873 - mmdeploy - INFO - PyTorch: 1.8.0
2022-08-18 10:37:03,873 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-08-18 10:37:03,873 - mmdeploy - INFO - TorchVision: 0.9.0
2022-08-18 10:37:03,873 - mmdeploy - INFO - OpenCV: 4.6.0
2022-08-18 10:37:03,873 - mmdeploy - INFO - MMCV: 1.6.0
2022-08-18 10:37:03,873 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-08-18 10:37:03,874 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2
2022-08-18 10:37:03,874 - mmdeploy - INFO - MMDeploy: 0.7.0+
2022-08-18 10:37:03,874 - mmdeploy - INFO - 

2022-08-18 10:37:03,874 - mmdeploy - INFO - **********Backend information**********
2022-08-18 10:37:04,698 - mmdeploy - INFO - onnxruntime: None   ops_is_avaliable : False
Traceback (most recent call last):
  File "/root/autodl-tmp/MMdeploy/tools/check_env.py", line 62, in <module>
    check_backend()
  File "/root/autodl-tmp/MMdeploy/tools/check_env.py", line 30, in check_backend
    import mmdeploy.apis.tensorrt as trt_apis
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/tensorrt/__init__.py", line 2, in <module>
    from mmdeploy.backend.tensorrt import is_available, is_custom_ops_available
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/__init__.py", line 30, in <module>
    from .utils import from_onnx, load, save
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 6, in <module>
    import tensorrt as trt
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/tensorrt/__init__.py", line 67, in <module>
    from .tensorrt import *
ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory

1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

Traceback (most recent call last):
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 92, in torch2onnx
    export(
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 122, in export
    torch.onnx.export(
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 706, in _export
    proto, export_map = graph._export_onnx(
RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True.
2022-08-18 10:27:24,065 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by AllentDan** [comment]
> Thanks for your bug report. We appreciate it a lot.
> 
> **Checklist**
> 
> 1. I have searched related issues but cannot get the expected help.
> 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
> 3. The bug has not been fixed in the latest version.
> 
> **Describe the bug**
> 
> RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True. 2022-08-18 10:27:24,065 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
> 
> **Reproduction**
> 
> 1. What command or script did you run?
> 
> python /root/autodl-tmp/MMdeploy/tools/deploy.py /root/autodl-tmp/MMdeploy/configs/mmocr/text-recognition/text-recognition_onnxruntime_dynamic.py /root/autodl-tmp/MMocr/configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py /root/.cache/torch/hub/checkpoints/sar_r31_parallel_decoder_chineseocr_20210507-b4be8214.pth /root/autodl-tmp/MMocr/demo/train/5_2.jpg --work-dir /root/autodl-tmp/MMdeploy/save_dir --device cuda --dump-info --show
> 
> 2. Did you make any modifications on the code or config? Did you understand what you have modified?
> 
> I have added 'use_external_data_format=True' in mmdeploy/apis/onnx/export.py, but it didn't work.
> 
> **Environment** 2022-08-18 10:37:03,419 - mmdeploy - INFO -
> 
> 2022-08-18 10:37:03,419 - mmdeploy - INFO - **********Environmental information********** fatal: not a git repository (or any of the parent directories): .git 2022-08-18 10:37:03,871 - mmdeploy - INFO - sys.platform: linux 2022-08-18 10:37:03,872 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0] 2022-08-18 10:37:03,872 - mmdeploy - INFO - CUDA available: True 2022-08-18 10:37:03,872 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 2080 Ti 2022-08-18 10:37:03,873 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda 2022-08-18 10:37:03,873 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 10.2, V10.2.8 2022-08-18 10:37:03,873 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 2022-08-18 10:37:03,873 - mmdeploy - INFO - PyTorch: 1.8.0 2022-08-18 10:37:03,873 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
> 
> * GCC 7.3
> * C++ Version: 201402
> * Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * NNPACK is enabled
> * CPU capability usage: AVX2
> * CUDA Runtime 10.2
> * NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
> * CuDNN 7.6.5
> * Magma 2.5.2
> * Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> 
> 2022-08-18 10:37:03,873 - mmdeploy - INFO - TorchVision: 0.9.0 2022-08-18 10:37:03,873 - mmdeploy - INFO - OpenCV: 4.6.0 2022-08-18 10:37:03,873 - mmdeploy - INFO - MMCV: 1.6.0 2022-08-18 10:37:03,873 - mmdeploy - INFO - MMCV Compiler: GCC 7.3 2022-08-18 10:37:03,874 - mmdeploy - INFO - MMCV CUDA Compiler: 10.2 2022-08-18 10:37:03,874 - mmdeploy - INFO - MMDeploy: 0.7.0+ 2022-08-18 10:37:03,874 - mmdeploy - INFO -
> 
> 2022-08-18 10:37:03,874 - mmdeploy - INFO - **********Backend information********** 2022-08-18 10:37:04,698 - mmdeploy - INFO - onnxruntime: None ops_is_avaliable : False Traceback (most recent call last): File "/root/autodl-tmp/MMdeploy/tools/check_env.py", line 62, in check_backend() File "/root/autodl-tmp/MMdeploy/tools/check_env.py", line 30, in check_backend import mmdeploy.apis.tensorrt as trt_apis File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/tensorrt/**init**.py", line 2, in from mmdeploy.backend.tensorrt import is_available, is_custom_ops_available File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/**init**.py", line 30, in from .utils import from_onnx, load, save File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 6, in import tensorrt as trt File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/tensorrt/**init**.py", line 67, in from .tensorrt import * ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory
> 
> 1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
> 2. You may add addition that may be helpful for locating the problem, such as
>    
>    * How you installed PyTorch [e.g., pip, conda, source]
>    * Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
> 
> **Error traceback**
> 
> If applicable, paste the error trackback here.
> 
> Traceback (most recent call last): File "/root/miniconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/root/miniconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in **call** ret = func(*args, **kwargs) File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 92, in torch2onnx export( File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap return self.call_function(func_name_, *args, **kwargs) File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function return self.call_function_local(func_name, *args, **kwargs) File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local return pipe_caller(*args, **kwargs) File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in **call** ret = func(*args, **kwargs) File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 122, in export torch.onnx.export( File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/**init**.py", line 271, in export return utils.export(model, args, f, export_params, verbose, training, File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export _export(model, args, f, export_params, verbose, training, input_names, output_names, File "/root/miniconda3/envs/mmdeploy/lib/python3.8/site-packages/torch/onnx/utils.py", line 706, in _export proto, export_map = graph._export_onnx( RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True. 2022-08-18 10:27:24,065 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
> 
> **Bug fix**
> 
> If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

Only the SAR for English is supported. There is a limitation size of ONNX file.

**Comment by DingchenYang99** [comment]
Thanks for the help! The SAR for english can be successfully exported.
