### ISSUE TITLE
pytorch_quantization

### ISSUE THREAD

**Issue by huyuanchao** [open-mmlab/mmdeploy#921]
i install mmdeply with docker, in which can not install pytorch_quantization module.

i quant a model in another environment, and export the quanted_model file into onnx file using mmdeploy/tools/deploy.py.

but when i opened the exported onnx file in Netron,  model graph-flow has no 'quant' related key words

who can tell how to export an quanted_onnx in mmdeploy docker????

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by tpoisonooo** [comment]
Please give the script for reproduce the bug.

For example:

```bash
$ docker run -it xxx
$ python3 tools/check_env.py
..
$ export MODEL_CONFIG=xxx
$ export MODEL_PATH=xxx
$ python3 tools/deploy.py xxxxx
```
Now you got an `.onnx` file ...  I guess that you expected the `.onnx` file has a  'quant'-like keywords.

Well ... mmdeploy is not simply pytorch quantization,  we use ppq to generate quant table, combine quant table and quantized onnx into real inference model. There is nothing to do with pytorch quantization.

**Comment by tpoisonooo** [comment]
If you have more quest, pls open a new one.
