### ISSUE TITLE
Could you describe the deployment steps using the edge device Jetson nano as an example?

### ISSUE THREAD

**Issue by sibet-lb** [open-mmlab/mmdeploy#923]
In the official instruction document (https://mmdeploy.readthedocs.io/zh_CN/latest/get_started.html)
The Faster R-CNN in MMDetection is used as an example in the operation overview to convert PyTorch models to TenorRT models for deployment on NVIDIA GPUs.
However, I noticed that there is no step in the text for deploying to a terminal GPU. Could you describe the deployment steps using the edge device Jetson nano as an example?

**Comment by lvhan028** [comment]
Hi, @sibet-lb Please refer to https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/jetsons.html

**Comment by sibet-lb** [comment]
Thank you for your reply! That's awesome! @lvhan028
