### ISSUE TITLE
TypeError: export2SDK() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by Vo-Linh** [open-mmlab/mmdeploy#927]
I want to convert model yolox to format .onnx but I got an error.
`TypeError: export2SDK() got an unexpected keyword argument 'device'`

**Reproduction**

My command

```none
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    mmdetection/configs/yolox/yolox_l_8x8_300e_coco.py \
    checkpoints/best_mAP_epoch_11.pth \
    mmdetection/demo/demo.jpg \
    --work-dir checkpoints \
    --device cpu \
    --dump-info
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

onnxruntime: 1.8.1	ops_is_avaliable : True
mmdet:	2.25.1
TorchVision: 0.13.1+cu113
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
 MMDeploy: 0.7.0+

**Comment by AllentDan** [comment]
Please update MMDeploy to the latest as we just made some modification to `tools/deploy.py` yesterday.
