### ISSUE TITLE
What version of MMDeploy supports CUDA 10.1?

### ISSUE THREAD

**Issue by xiangn95** [open-mmlab/mmdeploy#939]
My GPU can only run on CUDA 10.1, so I would like to know which version of MMDeploy supports this and how do I make sure that the installation of MMDeploy is compatible to my GPU.

**Comment by lvhan028** [comment]
We suggest using CUDA 10.2, the lts version.

**Comment by tpoisonooo** [comment]
I think the keypoint is GPU driver version.

mmdeploy depends on pytorch>=1.8 while pytorch does not directly use system cuda, it comes with independent cuda package. 

If you are using mmdeploy without TensorRT (for example ppl.nn), that doesn't matter which cuda you are using, just make sure that you can `import torch` successfully.

Please note that:
* pytorch1.8 not support cuda10.1
* you have to install pytorch with cuda10.2, please make sure that your gpu driver support cuda10.2, check this table:


CUDA Toolkit | Linux x86_64 Minimum Required Driver Version | Windows MinimumRequired Driver Version
-- | -- | --
CUDA 10.2 | >= 440.33 | >=441.22
CUDA 10.1 | >= 418.39 | >=418.96

**Comment by xiangn95** [comment]
My driver version does not support CUDA 10.2 but I don't use TensorRT either, I want to convert the model to ONNX instead. So currently ONNX does not have GPU support?

**Comment by tpoisonooo** [comment]
Now your driver do not support CUDA10.2,  you may not install pytorch>1.8 successfully, so mmdeploy would not work .
