### ISSUE TITLE
Fail to use make -j$(nproc)

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdeploy#943]
Hi developers of mmdeploy. I am newbie here. I failed to use the command make -j$(nproc) after I use the command "cmake -DMMDEPLOY_TARGET_BACKENDS=trt -DTENSORRT_DIR=${TENSORRT_DIR} .." successfully. The following error message came out. 

make: the '-j' option requires a positive integral argument
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  --eval=STRING               Evaluate STRING as a makefile statement.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from recipes.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no recipe; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo recipes.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  --trace                     Print tracing information.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.

This program built for i686-pc-mingw32
Report bugs to <bug-make@gnu.org>

I am not familiar with these. Could you please help me with this? Thank you very much.

**Comment by irexyc** [comment]
$(nproc) stands for the number of processing units available on your computer. [link](https://man7.org/linux/man-pages/man1/nproc.1.html)

You can use like `make -j6`, `make -j8`

If you use a windows pc, please use visual studio to compile the program.

**Comment by yeungkong** [comment]
I do use windows pc. If I run make -j6 in pycharm, it reads "make: *** No targets specified and no makefile found.  Stop.". So I need to run it in VS?

**Comment by irexyc** [comment]
Have you set variable `TENSORRT_DIR`?

I think the cmake configure process didn't return success. Could you print the full log after the command `cmake xxx`

**Comment by jslok** [comment]
@irexyc I am getting this same error. Any ideas please?

```
(openmmlab) C:\Users\jslok\mmdeploy\build>cmake -DMMDEPLOY_TARGET_BACKENDS=trt -DTENSORRT_DIR="C:\TensorRT-8.6.1.6" ..
-- Building for: Visual Studio 17 2022
-- CMAKE_INSTALL_PREFIX: C:/Users/jslok/mmdeploy/build/install
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.38.33135.0
-- The CXX compiler identification is MSVC 19.38.33135.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at cmake/cuda.cmake:5 (cmake_policy):
  The OLD behavior for policy CMP0104 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:99 (include)


CMake Warning (dev) at cmake/cuda.cmake:46 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:99 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8 (found version "11.8")
-- The CUDA compiler identification is NVIDIA 11.8.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin/nvcc.exe - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Build TensorRT custom ops.
-- Found TensorRT headers at C:/TensorRT-8.6.1.6/include
-- Found TensorRT libs at C:/TensorRT-8.6.1.6/lib/nvinfer.lib;C:/TensorRT-8.6.1.6/lib/nvinfer_plugin.lib
-- Found TENSORRT: C:/TensorRT-8.6.1.6/include
-- Configuring done (6.2s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/jslok/mmdeploy/build

(openmmlab) C:\Users\jslok\mmdeploy\build>make -j12 && make install
make: *** No targets specified and no makefile found.  Stop.
```
