### ISSUE TITLE
Running inference converted ONNX model without `mmdeploy` SDK but pure `onnxruntime` package

### ISSUE THREAD

**Issue by DangChuong-DC** [open-mmlab/mmdeploy#944]
Hello `mmdeploy` team,
First of all, thank you for your amazing work.

I have a question regarding running/loading converted `mmrotate` model using pure `onnxruntime` package without SDK from `mmdeploy`.
Long story short, I managed to successfully convert the trained `mmrotate` model into ONNX format using `mmdeploy` converter, I would like to run inference model with my own written script (as simple as `session = onnxruntime. InferenceSession(model path, **kwargs)`). However, I got an error message that a custom op has not been registered in `onnxruntime` --> image below.

What do I need to install? In addition, I tried to install only `mmdeploy` and build custom ops as following commands:
```
cd ${MMDEPLOY_DIR}
mkdir -p build && cd build
cmake -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR} ..
make -j$(nproc) && make install
```
It does not work!

How should I register custom op mentioned in the error message?

Any help would be very appreciated.
Thank you very much.

<img width="1128" alt="Screen Shot 2022-08-24 at 17 36 04" src="https://user-images.githubusercontent.com/40515271/186557706-bbbb94fb-889b-49b2-be3a-13ff5ce26797.png">

**Comment by grimoire** [comment]
You can get the custom ops path by `mmdeploy.backend.onnxruntime.get_ops_path()` 
Or read this
https://github.com/open-mmlab/mmdeploy/blob/b1e7579bdd7f41b198b25f5b726690acfba20830/mmdeploy/backend/onnxruntime/wrapper.py#L36-L64

Load thelibrary with `session_options.register_custom_ops_library(ort_custom_op_path)` before the session would give you access to the custom ops.

**Comment by DangChuong-DC** [comment]
@grimoire 
Thank you for your prompt response it works, but the result is not good.

How I managed to make it works:

1. install ONNX engine and `onnxruntime` package.
2. install `mmdeploy` and its custom op using:
```
cd ${MMDEPLOY_DIR}
mkdir -p build && cd build
cmake -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR} ..
make -j$(nproc) && make install
```
with `ONNXRUNTIME_DIR` from step 1.

3. load the library for custom_ops suggested above

And I could do the inference, yet in the inference I receive these messages --> image below
I'm wondering if it is fine?

<img width="1158" alt="Screen Shot 2022-08-25 at 16 26 45" src="https://user-images.githubusercontent.com/40515271/186628637-483effe4-9fc7-43f7-901a-c3594df24049.png">

Moreover, the main question is that, I unpacked the `inference_session` results and it is all 0. prediction. I am wondering what would be the issue here? 
Btw, do I need to install `mmcv` for inference with pure `onnxruntime` and custom_op? <<< Is this the potential problem that the result is very bad?

Any helps/suggestions would be very appreciated. 🙏 
I will try to look into it for more details as well. 👁️‍🗨️ 

Thanks again.

**Comment by grimoire** [comment]
We have done some optimization on the ONNX which might lead to some dangling nodes. It won't bring much trouble except for some annoying warning logs.
If the inference result is not expected, you can check if you have done the very same pre-process as the origin model.
And you don't need MMCV anymore if you just want to use ONNX Runtime. Custom ops library is all you need.

**Comment by DangChuong-DC** [comment]
@grimoire 
Thanks a lot, it works perfectly now.
It turned out as you suggested, I forgot to normalize the input.

Thank you very much for your help!
