### ISSUE TITLE
mask2former export onnx？

### ISSUE THREAD

**Issue by Kenneth-X** [open-mmlab/mmdeploy#946]
is there any schedule to  support mask2former exporting to onnx ？

**Comment by RunningLeon** [comment]
@Kenneth-X hi, is it for Panoptic segmentation or instance segmentation in mmdet? pls. post here a desired model config link from mmdet.

**Comment by Kenneth-X** [comment]
@RunningLeon hi，it is for Panoptic segmentation, which link is followed
https://github.com/open-mmlab/mmdetection/blob/master/configs/mask2former/mask2former_r50_lsj_8x2_50e_coco-panoptic.py

**Comment by RunningLeon** [comment]
@Kenneth-X Hi, panoptic segmentation is supported in the https://github.com/open-mmlab/mmdeploy/pull/649 by community contributor, it may take some time.

**Comment by KongCang** [comment]
> @RunningLeon hi，it is for Panoptic segmentation, which link is followed https://github.com/open-mmlab/mmdetection/blob/master/configs/mask2former/mask2former_r50_lsj_8x2_50e_coco-panoptic.py

Did you convert mask2former successfully? [#649](https://github.com/open-mmlab/mmdeploy/pull/649)

**Comment by RunningLeon** [comment]
@KongCang No. Did not support mask2former in #649

**Comment by fernandorovai** [comment]
Hi, any news on mask2former onnx conversion? Thanks

**Comment by RunningLeon** [comment]
@fernandorovai Hi, no plan to support by far. Welcome to contribute.
