### ISSUE TITLE
请问，后续是否会支持TVM？

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmdeploy#95]

**Comment by grimoire** [comment]
We plan to support more backends in the future. Of cause, TVM is one of them.
We want to carefully design the pipeline and APIs to ease the deployment. This might take some time.

**Comment by zhiqwang** [comment]
Just FYI @grimoire and @FDInSky ,

I link two issues about this:

- https://github.com/masahi/torchscript-to-tvm/issues/4
- https://github.com/apache/tvm/pull/7401

**Comment by FDInSky** [comment]
使用PAA转ONNX后， 然后使用TVM加载运行模型时，遇到错误
Check failed: fshape_func.count(op) > 0 (0 vs. 0) : Internal error, cannot find ShapeFunc for scatter_nd

**Comment by lvhan028** [comment]
Close it because TVM is not the current feature. It will be supported in future
