### ISSUE TITLE
Hi, I tried inference yolox trt model with batch images, but got "RuntimeError:continuous uint8 HWC array expected"

### ISSUE THREAD

**Issue by ShienLiXin** [open-mmlab/mmdeploy#973]
I have tried inference yolox trt model by SDK python API with one image successfully, however,when i modified input shape=16*640*640*3, i got the above err，onnx model input is 16*3*640*640，how should i solve this error，thank you！

**Comment by irexyc** [comment]
Could you paste your sample code here?

**Comment by ShienLiXin** [comment]
`from mmdeploy_python import Detector
import cv2

# 读取图片
img = cv2.imread('mmdetection/demo/demo.jpg')
imgs = []
for i in range(16):
    imgs.append(img)
# imgs = np.ascontigousarray(np.asarray(imgs))
# create detector
detector = Detector(model_path='mmdeploy_models/yolox', device_name='cuda', device_id=0)
# do inference
bboxes, labels, _ = detector(img)
indices = [i for i in range(len(bboxes))]
for index, bbox, label_id in zip(indices, bboxes, labels):
  [left, top, right, bottom], score = bbox[0:4].astype(int),  bbox[4]
  if score < 0.3:
      continue
  cv2.rectangle(img, (left, top), (right, bottom), (0, 255, 0))

cv2.imwrite('output_detection.png', img)`

**Comment by irexyc** [comment]
Please use this way:

```python
img = cv2.imread('mmdetection/demo/demo.jpg')
imgs = []
for i in range(16):
    imgs.append(img)

detector = Detector(model_path='mmdeploy_models/yolox', device_name='cuda', device_id=0)
result = detector.batch(imgs)
```

**Comment by ShienLiXin** [comment]
thanks very much @irexyc , it works, and where can i read he SDK python API docs?

**Comment by irexyc** [comment]
Sorry, you can only refer to the [header](https://github.com/open-mmlab/mmdeploy/tree/master/csrc/mmdeploy/apis/c/mmdeploy) file or or read the code to get the meaning of output.

We will add the api docs soon.

**Comment by Ruid6** [comment]
> Sorry, you can only refer to the [header](https://github.com/open-mmlab/mmdeploy/tree/master/csrc/mmdeploy/apis/c/mmdeploy) file or or read the code to get the meaning of output.
> 
> We will add the api docs soon.

Hi,i have seen **header** file and **ctypes** ,but i not find **batch()** function,Refer to the following example:
```
dll = ctypes.cdll.LoadLibrary
Detector = dll('./xxx.dll')
Detector.batch()
```
Am I going in the wrong direction?

**Comment by irexyc** [comment]
@Ruid6 

For python api, you can refer to https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/apis/python/detector.cpp#L82

For the output meaning, you can refer to this https://github.com/open-mmlab/mmdeploy/blob/master/csrc/mmdeploy/apis/c/mmdeploy/detector.h#L19-L30
