### ISSUE TITLE
how to implement the batch in mmdeploy using c++ ?

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdeploy#980]
mmdeploy部署c++的batch怎么实现，Python通过列表实现，c++怎么实现?有没有大佬解释一波

![image](https://user-images.githubusercontent.com/25839884/188048964-db4b7f69-02b6-4b85-a2fd-916c894efa99.png)

**Comment by vansin** [comment]
不清楚怎么搞，官方没有c++，demo参考，tensorrt batch推理才能发挥部署优势

**Comment by vansin** [comment]
same as  https://github.com/open-mmlab/mmdeploy/issues/917

**Comment by lvhan028** [comment]
Duplicated issue.
