### ISSUE TITLE
how to keep consistent with the trt plugin when exporting trt in another project 

### ISSUE THREAD

**Issue by cxiang26** [open-mmlab/mmdeploy#982]
1. I export the onnx model with some plugins by mmdeploy A;
2. I need to get trt model in another project B via the onnx model above;
3. the plugins are refactored in  project B, this project only supports onnx model as input;
4. the error is can't find plugins
![image](https://user-images.githubusercontent.com/22794673/188061514-d201834f-1a5d-47ad-92e7-d517e1cec27f.png)
mmdeploy and project B in the same environment
what should I do to load the plugin in project B correctly?
thanks in advance

**Comment by grimoire** [comment]
You can load the plugin with ctypes.CDLL in python or dlopen in c++.

**Comment by cxiang26** [comment]
> 

due to some limitations, I can't use the shared lib in project B

**Comment by grimoire** [comment]
You can build a static library and link it to your project. The ops srcs are placed in `csrc/mmdeploy/backend_ops/tensorrt`.
`REGISTER_TENSORRT_PLUGIN` macro will add the creators and any onnx node with type equal to `creator::getPluginName()` would be matched.

**Comment by cxiang26** [comment]
> You can build a static library and link it to your project. The ops srcs are placed in `csrc/mmdeploy/backend_ops/tensorrt`. `REGISTER_TENSORRT_PLUGIN` macro will add the creators and any onnx node with type equal to `creator::getPluginName()` would be matched.

thanks, I have solved this issue.
we just need to keep the same plugin name in here 
```c++
namespace {
static const char *PLUGIN_VERSION{"1"};
static const char *PLUGIN_NAME{"mypluginname"}; 
}  // namespace
```
