### ISSUE TITLE
MMDET3D: mmdeploy in  PointPillar model to trt【Win10】

### ISSUE THREAD

**Issue by BandyKenny** [open-mmlab/mmdeploy#994]
Thanks for your bug report. We appreciate it a lot.
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
BUG：_pickle.UnpicklingError: could not find MARK
- mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
![image](https://user-images.githubusercontent.com/43592362/188265461-ba3aa4a6-008d-477f-8dcd-bbe2c749d0eb.png)

**Reproduction**

1. What command or script did you run?
python tools/deploy.py configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-kitti.py ../mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py ../mmdetection3d/work_dir/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/latest.pth ../mmdetection3d/demo/data/kitti/kitti_000008.bin --work-dir ../mmdeploy_out/mmdet3d/pointpillar --device cuda:0

2. Did you make any modifications on the code or config? Did you understand what you have modified?

**Environment**

1. Please run `python tools/check_env.py` to collect necessary environment information and paste it here.
2022-09-03 17:54:40,495 - mmdeploy - INFO - **********Environmental information**********
系统找不到指定的路径。
fatal: not a git repository (or any of the parent directories): .git
2022-09-03 17:54:43,283 - mmdeploy - INFO - sys.platform: win32
2022-09-03 17:54:43,283 - mmdeploy - INFO - Python: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
2022-09-03 17:54:43,283 - mmdeploy - INFO - CUDA available: True
2022-09-03 17:54:43,283 - mmdeploy - INFO - GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
2022-09-03 17:54:43,283 - mmdeploy - INFO - CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin
2022-09-03 17:54:43,283 - mmdeploy - INFO - NVCC: Not Available
2022-09-03 17:54:43,283 - mmdeploy - INFO - MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30146 版
2022-09-03 17:54:43,283 - mmdeploy - INFO - GCC: n/a
2022-09-03 17:54:43,284 - mmdeploy - INFO - PyTorch: 1.8.0+cu111
2022-09-03 17:54:43,284 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

2022-09-03 17:54:43,284 - mmdeploy - INFO - TorchVision: 0.9.0+cu111
2022-09-03 17:54:43,284 - mmdeploy - INFO - OpenCV: 4.5.3
2022-09-03 17:54:43,285 - mmdeploy - INFO - MMCV: 1.6.0
2022-09-03 17:54:43,285 - mmdeploy - INFO - MMCV Compiler: MSVC 192930137
2022-09-03 17:54:43,285 - mmdeploy - INFO - MMCV CUDA Compiler: 11.1
2022-09-03 17:54:43,285 - mmdeploy - INFO - MMDeploy: 0.6.0+
2022-09-03 17:54:43,286 - mmdeploy - INFO -

2022-09-03 17:54:43,286 - mmdeploy - INFO - **********Backend information**********
2022-09-03 17:54:43,681 - mmdeploy - INFO - onnxruntime: 1.10.0 ops_is_avaliable : True
2022-09-03 17:54:43,704 - mmdeploy - INFO - tensorrt: 8.2.3.0   ops_is_avaliable : True
2022-09-03 17:54:43,717 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-09-03 17:54:43,720 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-09-03 17:54:43,726 - mmdeploy - INFO - openvino_is_avaliable: False
2022-09-03 17:54:43,727 - mmdeploy - INFO -

2022-09-03 17:54:43,728 - mmdeploy - INFO - **********Codebase information**********
2022-09-03 17:54:43,742 - mmdeploy - INFO - mmdet:      2.25.0
2022-09-03 17:54:43,743 - mmdeploy - INFO - mmseg:      0.27.0
2022-09-03 17:54:43,743 - mmdeploy - INFO - mmcls:      None
2022-09-03 17:54:43,751 - mmdeploy - INFO - mmocr:      None
2022-09-03 17:54:43,751 - mmdeploy - INFO - mmedit:     None
2022-09-03 17:54:43,751 - mmdeploy - INFO - mmdet3d:    1.0.0rc4
2022-09-03 17:54:43,752 - mmdeploy - INFO - mmpose:     None
2022-09-03 17:54:43,752 - mmdeploy - INFO - mmrotate:   None
3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by tpoisonooo** [comment]
You are using local file `../mmdetection3d/work_dir/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/latest.pth `  and it crashes on `pytorch/serialization.py`,   so .. what is the .pth file comes from ? 

The .pth file should be  https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth .

**Comment by tpoisonooo** [comment]
```bash
$ md5sum hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth 
3a31144a95704c42ada7d70e7520193f  hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
```

**Comment by BandyKenny** [comment]
Thanks for your answer. After using this hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth, I can perform normal ONNX and TRT conversion！
![image](https://user-images.githubusercontent.com/43592362/188358194-50f962f0-02d2-41f2-a37b-63fd4f6e8eef.png)
but, I don't understand why using the 'latest.pth' stored after training can't complete this process.
I only made the following changes to the training configuration:
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
It is worth noting that I did the model training on a server (ubuntu20.04) and then the mmdeploy test on Windows 10.

**Comment by tpoisonooo** [comment]
Since the error log comes from `torch/serialization.py`,  I doubt that is a break change between ubuntu pytorch and win10 pytorch. 

How about make this simple test:
1. Initialize the model on win10 (just give random weight, do not need real training), then convert with mmdeploy
2. If it works, there are some break change in ubuntu torch and win10 torch. Please open a new issue to pytorch
3. If it fails, maybe mmdet3d version mismatch. Print the model structure of `latest.pth` and `37dc2420.pth`

**Comment by BandyKenny** [comment]
Okay, so I've tested these questions：
 1. Initialize the model on win10 (just give random weight, do not need real training), then convert with mmdeploy：
 In mmDetection3d \configs\_base_\, Modified load_from = 'work_dir/ hv_pointpillars_secFPn_6X8_160e_KITti-3D-3class-old /latest.pth' in default_runtime.py, I put lattest.pth here and set runner = dict(max_epochs=0) to hv_pointpillars_secfpn_6x8_160e_kitti-3D-3class.py. 
Execute the command:python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
but load the model fail and view same bug：
![image](https://user-images.githubusercontent.com/43592362/188578822-5ef7b12b-d9ff-4fab-8e41-d689b662023c.png)
---------------------------------------------------------------------------------------------------------------------------------------
2.I tried to unify the Windows 10 and ubuntu20.04 environment versions:
![image](https://user-images.githubusercontent.com/43592362/188580948-ce51de11-b98b-4925-8cdd-f82721a70f05.png)
![image](https://user-images.githubusercontent.com/43592362/188580982-f7f36651-7dbc-40b8-9816-66a78506c131.png)
and, load_from = 'hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth' as a pre-training model.
then, I will get the new latest.pth in linux, put it into Windows 10 to do mmdeploy test, it successed!
-----------------------------------------------------------------------------------------------------------------------------------------
3. so, I think it might be a mismatch problem, maybe there is no pre-trained model? I test load_from = None.  Train Again.
ok, Without the pre-trained model, the trained PTH can still complete the model transformation on Win10!
so, It's really a version problem.
-----------------------------------------------------------------------------------------------------------------------------------------
4. But when I tried the mmdeploy task on Ubuntu20.04, I had a new problem:
Bug:TypeError: base3ddetector__forward() got an unexpected keyword argument 'img_metas' 
2022-09-06 16:36:02,656 - mmdeploy - ERROR - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
![image](https://user-images.githubusercontent.com/43592362/188589667-cb291f5e-f48f-459d-a8b0-8146f0884145.png)
The check - env is:
![image](https://user-images.githubusercontent.com/43592362/188589850-648f2b5d-6bfa-46d2-8104-a97185ca1a60.png)
The instructions to be executed are:
python tools/deploy.py configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-kitti.py ../mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py ../mmdetection3d/work_dirs/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/epoch_1.pth ../mmdetection3d/demo/data/kitti/kitti_000008.bin --work-dir ../mmdeploy_out/mmdet3d/pointpillar3 --device cuda:0
the model 'epoch_1.pth' with 1 training round (no pre-training model)
At the same time, I also tried to use 'hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth' for direct conversion, but ERRO is the same😂

**Comment by tpoisonooo** [comment]
Hot fix it:  `vim  /path/to/mmdeploy/apis/onnx/export.py` and remove `img_metas`.
