### ISSUE TITLE
yolact  torch model convert to onnx failed

### ISSUE THREAD

**Issue by cyning911** [open-mmlab/mmdeploy#996]
%cd ~/train/src_repo/mmdeploy
!python tools/torch2onnx.py \
    configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py \
    ~/train/models/yolact_r101_1x8_coco.py \
    ~/train/models/epoch_5.pth \
    demo/demo.jpg \
    --work-dir ~/train/models \
    --device cuda:0

* print:
/project/train/src_repo/mmdeploy
2022-09-05 10:28:00,075 - mmdeploy - INFO - torch2onnx: 
	model_cfg: /project/train/models/yolact_r101_1x8_coco.py 
	deploy_cfg: configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py
load checkpoint from local path: /project/train/models/epoch_5.pth
2022-09-05 10:30:07,249 - mmdeploy - WARNING - DeprecationWarning: get_onnx_config will be deprecated in the future. 
2022-09-05 10:30:07,250 - mmdeploy - INFO - Export PyTorch model to ONNX: /project/train/models/end2end.onnx.
/usr/local/lib/python3.7/dist-packages/mmdeploy/core/optimizers/function_marker.py:158: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ys_shape = tuple(int(s) for s in ys.shape)
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:407: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:418: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if 0 < nms_pre < scores.shape[0]:
/usr/local/lib/python3.7/dist-packages/mmdeploy/pytorch/functions/topk.py:28: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  k = torch.tensor(k, device=input.device, dtype=torch.long)
/usr/local/lib/python3.7/dist-packages/mmdeploy/pytorch/functions/topk.py:33: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ctx.origin_func(input, k, dim=dim, largest=largest, sorted=sorted)
/usr/local/lib/python3.7/dist-packages/mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/usr/local/lib/python3.7/dist-packages/mmdeploy/codebase/mmdet/deploy/utils.py:47: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  assert len(max_shape) == 2, '`max_shape` should be [h, w]'
/project/train/src_repo/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py:194: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (bboxes1.size(-1) == 4 or bboxes1.size(0) == 0)
/project/train/src_repo/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py:195: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (bboxes2.size(-1) == 4 or bboxes2.size(0) == 0)
/project/train/src_repo/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py:199: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert bboxes1.shape[:-2] == bboxes2.shape[:-2]
/project/train/src_repo/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py:207: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if rows * cols == 0:
/project/train/src_repo/mmdetection/mmdet/core/bbox/transforms.py:127: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.shape[0] == 0:
/project/train/src_repo/mmdetection/mmdet/core/bbox/transforms.py:131: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bboxes = bboxes.detach().cpu().numpy()
/project/train/src_repo/mmdetection/mmdet/core/bbox/transforms.py:132: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  labels = labels.detach().cpu().numpy()
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:974: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if all(det_bbox.shape[0] == 0 for det_bbox in det_bboxes):
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:731: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  h, w = cur_img_meta['img_shape'][:2]
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:994: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if det_bboxes[i].shape[0] == 0:
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:863: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if mask_pred.size(0) == 0:
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:870: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  mask_pred = mask_pred.cpu().numpy().astype(np.uint8)
/project/train/src_repo/mmdetection/mmdet/models/dense_heads/yolact_head.py:872: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for m, l in zip(mask_pred, label_pred):
Traceback (most recent call last):
  File "tools/torch2onnx.py", line 87, in <module>
    main()
  File "tools/torch2onnx.py", line 56, in main
    device=args.device)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/pytorch2onnx.py", line 105, in torch2onnx
    optimize=optimize)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/onnx/export.py", line 132, in export
    verbose=verbose)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/core/rewriters/rewriter_utils.py", line 379, in wrapper
    return self.func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdeploy/apis/onnx/optimizer.py", line 10, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray

**Comment by RunningLeon** [comment]
@cyning911 Hi, mmdeploy does not support yolact from mmdet based on the [list](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html). Maybe you could try to support it by referring to maskrcnn.

**Comment by VincentMy** [comment]
> @cyning911 Hi, mmdeploy does not support yolact from mmdet based on the [list](https://mmdeploy.readthedocs.io/en/latest/04-supported-codebases/mmdet.html). Maybe you could try to support it by referring to maskrcnn.

![image](https://user-images.githubusercontent.com/47235130/210765673-f96f74ee-648e-4429-8b3b-ae867ab6ee12.png)
it seems to support yolox
